### ISSUE TITLE
ArcGIS Server and CORS Support

### ISSUE THREAD

**Issue by keithmoss** [TerriaJS/terriajs#1003]
We’ve been trialling some new ArcGIS Server-based WMS services here and noticed a slight hiccup with CORS handling in NationalMap.

ArcGIS Server supports CORS, but [only responds with CORS headers if the requestor includes the Origin header](http://resources.arcgis.com/en/help/rest/apiref/config.html). (`Origin: *` is sufficient)

As TerriaJS doesn't seem to be including `Origin`, we're getting your standards CORS error modal dialog.

For some more background see this [ESRI-Leaflet GitHub issue](https://github.com/Esri/esri-leaflet/issues/563).

Happy to email the URL for a non-public test service at somebody :)

**Comment by kring** [comment]
Thanks for the report @keithmoss.  I'm pretty surprised to hear this, though.  Looking at the Network tab in the Chrome debugger, I can clearly see that NationalMap is including the `Origin` request header for datasets that it accesses via CORS (e.g. anything in the Communications folder).  It doesn't include that header when routing via the proxy, though, which it will do for anything in the proxy whitelist (which includes `*.gov.au`) that is not also explicitly in the `corsDomains` list in the `nm.json`.

In fact, for a cross-origin `XMLHttpRequest`, adding the `Origin` header is built-in browser behavior, and as far as I know we couldn't prevent it if we tried.

**Comment by keithmoss** [comment]
Cheers for the prompt response, Kevin.

Our services are at `services.slip.wa.gov.au`, so we'll be being caught by your *.gov.au proxy whitelist. But that doesn't explain the supposed CORS issue - so maybe we're running into a GetCapabilities parsing error?

Poking around in Chrome's Network panel shows `https://nationalmap.gov.au/proxy/_1d/{our_service_url}` returning 404 and triggers the "Group is not available" modal error.

![screen shot 2015-10-28 at 08 22 01](https://cloud.githubusercontent.com/assets/5944358/10776499/ff8b3764-7d4c-11e5-8fec-2bfed9297548.png)

What's the best email to use to flick you a link to our test service?

**Comment by kring** [comment]
Ok, so in that case you're probably not seeing a CORS problem at all, but some other problem.  TerriaJS doesn't do a very good job of distinguishing the two, partially because browsers do a poor job of reporting CORS failures in a meaningful way.

You can email me a link at the address on the website linked from my GitHub profile.

**Comment by keithmoss** [comment]
Shot you a link

**Comment by keithmoss** [comment]
Awesome! Good sleuthing, Kevin :) Thanks! :+1: 

Once merged will you need to update the GA deployment of NationalMap - or is your node proxy separate?

**Comment by kring** [comment]
More credit to @peterhassall and @meh9 than me!
Yes, GA will need to update their deployment.  That will happen with the next release, which we'll send to them on 15 November and they'll likely deploy within a few days after that.

**Comment by keithamoss** [comment]
Perfect - suits our timelines :)

Thanks Data61! \m/
