### ISSUE TITLE
Expanding Esri MapServer data details locks up

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1004]
1. Open layer information page for GA's "Roads" layer in NM (National Data Sets > Transport > Roads > Roads)
2. Click the arrow next to "Data Details"

In my browser (Chrome, OSX), the tab goes completely non-responsive for a long time (~30 seconds). 

Guessing that the issue is whatever mechanism retrieves the data service details, parses it and constructs the table is slow and synchronous.

**Comment by stevage** [comment]
(Confirming that this still happens.)

**Comment by kring** [comment]
The new UI doesn't have a Data Details section, so I'm closing this.
