### ISSUE TITLE
Hard to find datasets covering a given area

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1007]
Reporting a UX problem for which I don't have a solution.
1. I'm looking for trees data in a given state (say NT)
2. I search trees and see this:

<img width="345" alt="screenshot 2015-10-28 18 51 56" src="https://cloud.githubusercontent.com/assets/678344/10782511/03bc8c90-7da5-11e5-9796-ce1b8c9df70d.png">

None of these results are relevant. In this case, many have their locations in the title, but that's actually uncommon. Hovering over a title sometimes helps (if data comes from data.qld.gov.au then it's unlikely to cover NT), but overall the experience is frustrating.

Vague suggestions:
- somehow indicate the coverage of a dataset
- at least more visible indicate its source
- make search sensitive to current location, and prioritise nearby datasets.

**Comment by meh9** [comment]
Something to consider is to somehow display the path to the dataset in the Data Catalog as in many cases this would probably solve this problem. We have some fairly long paths to some things like Electricity Infrastructure -> Generation -> Live NEM Power Generation -> Renewable. If you search for "renewable" that layer comes up, but the added context of the path to it in the catalog is missing.

Similarly in your example above, the "Trees" dataset appears to be the Launceston layer, if we somehow displayed the fact that the location of it in the catalog was "data.gov.au -> City of Launceston -> Trees" then that gives a lot more context for the search result.

**Comment by kring** [comment]
@meh9 in case you didn't know, we display the full path to the catalog item when you hover the mouse over it.  I agree this should be more obvious, though.

**Comment by stevage** [comment]
> we display the full path to the catalog item when you hover the mouse over it

Annoyingly, that doesn't happen when the item is selected. So if you're trying to find out where a dataset is that you just turned on, you need to remove it again first...

**Comment by stevage** [comment]
Just thinking about what the ideal text to display would be, it could be complicated. In the Launceston case it would probably be "City of Launceston" (the organisation name in CKAN), but in others it would be the group name. Very hard to predict whether a given text string gives the user enough context or not. Hrm.

**Comment by kring** [comment]
> So if you're trying to find out where a dataset is that you just turned on, you need to remove it again first...

I just saw that yesterday myself, and was also surprised and annoyed by it.

**Comment by hilarycinis** [comment]
I'm a bit unclear on the issue, sorry. Are you trying to locate the data set in catalogue? Trying to find a contextually relevant data set for a location? Maybe if you can better describe what you expect to happen?

**Comment by stevage** [comment]
I'm trying to answer the question "Is there data about X in location Y". In my particular use case, it's things like "Is there data about aquifers in the Northern Territory", "Is there data about irrigation in northern WA?"

For search terms that yield many results, some of which are slow data layers, it's a very slow process of trial and error to see whether any particular result actually covers the area I'm looking for.

What I expect to happen is either:
- don't show me datasets that don't cover the area I'm interested in (however that is communicated); or
- give me enough information about the coverage of a dataset so I can mentally filter it out without having to turn it on/off

**Comment by hilarycinis** [comment]
I'm keen to see how folks are interacting with the map once we fix the search discovery issue. To date, they have search locations first either with zooming or search field (when they could find it). This implies location is the primary action to set up context. Then finding data happens. 

However if we can look at some data-first use cases provided from AREMI interviews we can work more on exploring those location/data relationships. This could be also be meta data we can surface better as suggested above in this issue thread.

**Comment by florianm** [comment]
I've got the same question, but I'm coming from the CKAN data cataloguing side. CKAN's main job and ability is to answer your question - find datasets by location (bbox), fulltext search, facet (keywords, thematic groups, owning organisations). [Example](http://catalogue.beta.data.wa.gov.au/dataset?ext_prev_extent=98.43750000000001%2C-43.707593504052944%2C137.10937500000003%2C-13.410994034321702&q=&ext_bbox=104.58984375000001%2C-39.36827914916012%2C130.95703125000003%2C-18.979025953255267&sort=score+desc%2C+metadata_modified+desc&groups=habitat-sampling-initiative&_groups_limit=0) of a bbox plus group search.
But CKAN only does a preview of one dataset (actually, only one data resource) at a time.

TerriaJS and NM are brilliant at showing a set of several datasets (plus some much needed reference layers) on a map.

My ideal scenario is a CKAN extension which adds a "map all the things" button to CKAN's dataset search page, which initialises a NM instance with the CKAN search settings (SolR q and fq string) and displays (only) the spatial resources of these datasets.

**Comment by stevage** [comment]
Btw another (not totally successful) example of a map-based data search: https://researchdata.ands.org.au/ (click 'map search')

**Comment by kring** [comment]
This is a very difficult thing to do in a client-only library like TerriaJS.  However, it makes sense to do it in a data catalogue (e.g. CKAN), and we're working on it for Magda, so I'm closing this.
