### ISSUE TITLE
Support FEATURE_COUNT parameter for GetFeatureInfo requests

### ISSUE THREAD

**Issue by axman6** [TerriaJS/terriajs#1010]
`GetFeatureInfo` requests by default return information for a single feature under the location clicked (default `FEATURE_COUNT=1`). With the new work to show information from each layer in #994 it would now be good to specify the `FEATURE_COUNT` to get all features. Ideally it would be possible to specify both an instance wide default and layer specific setting for value used.

**Comment by meh9** [comment]
The `GetFeatureInfo` equivalent for Esri ArcGIS services do return all or at least many features under the click for single layers, and #994 renders it perfectly. For example, turn on Transport -> Rail -> Railways and click on pretty much any busy east coast railway for multiple results.

**Comment by RacingTadpole** [comment]
@axman6 - can you point me to an example where we're seeing the problem?

**Comment by meh9** [comment]
This layer is a good example, just make sure you are reasonably zoomed out and click on one of the "tangles" of pipelines:

http://www.ga.gov.au/gis/services/topography/National_Onshore_Gas_Pipelines/MapServer/WMSServer

For example this `GetFeatureInfo` request which I've added `&FEATURE_COUNT=10` on the end, where you only get one result if you leave that off:

http://www.ga.gov.au/gis/services/topography/National_Onshore_Gas_Pipelines/MapServer/WMSServer?srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&service=WMS&version=1.1.1&request=GetFeatureInfo&layers=Gas_Pipelines&bbox=16280475.528516259%2C-3757032.814272985%2C17532819.79994059%2C-2504688.542848654&width=256&height=256&query_layers=Gas_Pipelines&x=64&y=122&info_format=text%2Fxml&FEATURE_COUNT=10

**Comment by RacingTadpole** [comment]
Thanks. Good news - it looks like this is already possible, eg. in the json catalog file, add `"feature_count": 20` to the `parameters` object in the `wms` item, and terria will start loading up to 20 features for that item.

So this leaves open the question - what is a sensible default?  The current 1 is unexpected, but 100000 may be impractical... any ideas (@kring)?

(For reference, changing the default in terria is simple - just add a line such as `feature_count: 20` to `WebMapServiceCatalogItem.defaultParameters`. But we may want to add it to Cesium too.)
