### ISSUE TITLE
Remove field name underscores from FeatureInfoPanel display

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1011]
Many feature properties have field names with underscores in them, which then show up in the feature info panel.  One simple way to improve user-friendliness would be to replace all underscores in property keys with spaces (in the absence of a template).

Eg. The broadband ADSL availability dataset has lots of field names like “availability_rating” and “adsl_speed_median".

This would apply to each data source type.

Templates could still be used to give even better descriptions.

**Comment by hilarycinis** [comment]
Sounds great. Also, some are in all caps, can we fix that programatically?

**Comment by RacingTadpole** [comment]
We could, but I'm not sure what the right rule would be - eg. ADSL, if it exists, should probably stay capitals, but DEPTH shouldn't.

**Comment by hilarycinis** [comment]
ah yes, good point. Removal of the underscores is good news, thanks.
