### ISSUE TITLE
Communicate search filter features to user

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1015]
A while ago, I added the ability to filter search:
- `url:ga.gov.au`
- `is:wms`
- `show:all`
- and negation, `-is:wms`

Obviously the user has no way to discover this. Perhaps we could have some tooltip, or a little help button or something?

**Comment by hilarycinis** [comment]
Great! Users can use search commands to filter search results. Definitely should go in the FAQ/Help pages. 

We're sorting out search location at the moment so I'll keep in mind. Primary communication is making sure location and data is searchable. 

Thanks!

**Comment by hilarycinis** [comment]
These instructions would be good in the FAQ's

**Comment by tkeuneman** [comment]
@kring We can just add this to the [FAQ](https://nationalmap.gov.au/help/help.html) under a heading called 'How to use advanced search'

url:ga.gov.au
is:wms
show:all
and negation, -is:wms

**Comment by stevage** [comment]
And maybe a little (?) icon next to the search box that links there?

**Comment by nf-s** [comment]
This no longer applies to version 8
