### ISSUE TITLE
CORS error reporting is imprecise

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1016]
Some servers don't support CORS, so requests fail. Terria doesn't detect this very well, causing two problems:
1. Sometimes, a CORS error is misreported as a generic dataset error. (For instance, add `http://www.asris.csiro.au/ArcGis/services/TERN/BDW_ACLEP_AU_NAT_C/MapServer/WMSServer` to NM - it offers to use our conversion service, or just says it "does not have the expected format"). This is misleading.
2. Sometimes, a non-CORS error is reported with a generic message that suggests CORS as one possible cause.  This is distracting, and not as helpful as it could be.

I frequently find myself popping open the console to find out what's going on - which isn't something most users know how to do.

(Side note: isn't it tempting to set up a proxy which will proxy _anything_ that looks like a GIS, as long as it has our referrer? The CORS issue is a pretty big blocker for a lot of evaluations...)

**Comment by kring** [comment]
The browser console will tell you about a CORS failure, but (as of last time I checked, it's possible something has changed), browsers will NOT report this to our code.  Apparently it's considered some kind of security problem?  So we can do a better job of detecting other kinds of failure (e.g. we got a 404, versus we got a response but it was the wrong format) and maybe assume that random unexplained failure means there was a CORS failure, but sadly we can't just detect a CORS failure outright and tailor the message accordingly.  Again, there's a small chance this is based on outdated information so I'm happy for someone to look into it again.

**Comment by stevage** [comment]
Ah, thanks. That would still definitely be a better UX I think: "We couldn't access your data for some reason. The most common cause is CORS..."

**Comment by kring** [comment]
Probably not going to happen.  Our current message is based on the assumption that most people don't add their own data.  So if something fails, it's not because the server doesn't support CORS (we would have already handled that when constructing the catalog) but because either the server or the user's internet connection is down.
