### ISSUE TITLE
Support for WMS 1.1.1?

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#1019]
It looks like TerriaJS only has support for WMS 1.3.0, not WMS 1.1.1, correct?

WMS 1.1.1 and WMS 1.3.0 are the most common WMS versions implemented in the wild, and there are still WMS servers  who did not upgrade to WMS 1.3.0 because the main difference was that the ordering of longitude and latitude was reversed (and SRS became CRS).   

Is there any plan to support WMS 1.1.1 in TerriaJS?

**Comment by rsignell-usgs** [comment]
Ack... My bad.   TerriaJS _does_ support WMS 1.1.1, doesn't it? 
I just needed to add the version number onto the `getCapabilities` endpoint:
http://sci-wms.whoi.edu/wms/datasets/coawst?service=WMS&version=1.1.1

**Comment by kring** [comment]
Yes it does.  TerriaJS will specify WMS 1.3.0 when doing a GetCapabilities request, but servers can (and should, according to the standard) respond with a 1.1.1 document if that's the latest version they support.  TerriaJS should be able to understand the 1.1.1 document without any trouble.
