### ISSUE TITLE
Style WMS GetFeatureInfo XML response

### ISSUE THREAD

**Issue by florianm** [TerriaJS/terriajs#1023]
Could XML response be styled as simple nested list? This would increase readability.

**Comment by stevage** [comment]
When is this needed?

**Comment by florianm** [comment]
When I raised this issue, WMS services added to NationalMap returned a WMS GetFeatureInfo XML response. I'm trying to reproduce the issue but I haven't got read permission to that particular source any more, and another WMS displays its GetFteatureInfo XML fine as a table now. Closing the issue.
