### ISSUE TITLE
Long mapserver URLs get cut off

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1030]
<img width="542" alt="screenshot 2015-11-04 12 32 20" src="https://cloud.githubusercontent.com/assets/678344/10926996/24768cec-82f0-11e5-9f4c-d924398001b5.png">

**Comment by kring** [comment]
I don't think it's actually cut off, is it?  That's an input box, so you can click and move the cursor around, or just click and copy the whole thing.

**Comment by stevage** [comment]
Err, yes. To be clearer: the box is too small, and doesn't make it easy to read the whole URL. You can't cursor around because it's read only, so the only option is pasting it somewhere else. If it was wider, a lot of the problem goes away.

**Comment by chloeleichen** [comment]
we can force line wrapping?

**Comment by stevage** [comment]
And make it wider - there's still space to the side.

**Comment by chloeleichen** [comment]
Made input box full width: https://github.com/TerriaJS/terriajs/commit/03a562e7478b0cdc3f72aa5fb113464d0c7b1a9d

Do you want the url to wrap or not @stevage ? Please see below the difference:
![screenshot](https://cloud.githubusercontent.com/assets/7508939/11362427/8b4d4e04-92e7-11e5-8aa7-6731e695fbd4.jpg)

**Comment by stevage** [comment]
Yeah, I think wrapping is better than cutting off. @hilarycinis or @philipgrimmett want to comment?

**Comment by kring** [comment]
@chloeleichen this seems like a nice improvement, and it seems like it'd be just a few minutes work to bring it over to the new UI.  What do you think?

**Comment by chloeleichen** [comment]
sure

**Comment by kring** [comment]
The box in Steve's screenshot is still not wrapping in the new UI, but there _is_ a clickable link right below it these days:
![image](https://user-images.githubusercontent.com/924374/36402803-1f79a320-1635-11e8-9bc9-65de6353d181.png)
I think that's good enough to close this issue.
