### ISSUE TITLE
10 data search results is too few

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1033]
When I'm searching for data, I frequently have to add `show:all` to see  enough results - our default cut off of 10 seems to be too few for me. I wanted to run this past UX before making a change though, to see if there's a downside to just increasing it to 20 or so.

Example: search for "mine" at NM. Results 10-20 are pretty relevant.

Ideally perhaps a little "Show more" icon would indicate that there are more results and make it easier to view them.

**Comment by kring** [comment]
+1 for the "Show more" idea.

**Comment by kring** [comment]
The new UI does not have a limit for data searches.
