### ISSUE TITLE
GeoJSON polygons with no fill don't display

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1034]
This GeoJSON file renders invisible: https://gist.github.com/anonymous/76b49ec911aa6e9f79ea

I think something is wrong with the logic that converts SimpleStyle properties to Cesium properties.

**Comment by stevage** [comment]
Err, I think the error is maybe just the opacity was 50 instead of 0.5.

**Comment by kring** [comment]
Can we close this then?
