### ISSUE TITLE
CSVs with 2 or more rows with the same lat/lon only allow the feature info of the last row to be viewed  

### ISSUE THREAD

**Issue by bsimyo** [TerriaJS/terriajs#1040]
Ideally clicking on a point should bring up the data from each of the rows.

@RacingTadpole  Is this addressed with the recent changes for showing feature info for each of the loaded layers or @stevage is this addressed with the recent csv changes. 

It may sound like an unlikely use case but actually I know of 2 NationalMap uses who want this (eg used when multiple organisations share the same building address).

**Comment by meh9** [comment]
The multi-feature-select is awesome, @RacingTadpole did a great job!

Not an unlikely case at all - AREMI has needed this for a long time. For example, with the new capability we now show all the individual generators of a power station (which are often registered at the same point location) at the same time with just one click, where before we were only able to show the details of one generator.

We've also discovered that a lot of the other layers (even within a single layer) will very often have multiple features in one location, and data is now shown for all of them. 

The next Terria release is going to be a really good one, this is just one of many new awesome features they've added. :)

**Comment by RacingTadpole** [comment]
Glad it works! I'll close this issue based on @stevage's results using csv test data (separately communicated). cf #994

**Comment by bsimyo** [comment]
Yep I see this works fine now with recent csv changes from @stevage - great!
