### ISSUE TITLE
Legend ticks disappear when changing data variable

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1049]
When you select a different data variable to display through the interface, the legend is redrawn without legend ticks.

(I'm currently working on the legend drawing code, so best not to touch it just yet - just making a note that this was broken before I got there :))

**Comment by meh9** [comment]
May be related to https://github.com/TerriaJS/terriajs/issues/798?

**Comment by stevage** [comment]
Ah, quite possibly, thanks.

**Comment by stevage** [comment]
I think maybe this is the source: https://github.com/TerriaJS/terriajs/blob/master/lib/Models/CsvCatalogItem.js#L569

**Comment by stevage** [comment]
Everything about this is different now.
