### ISSUE TITLE
`itemProperties` is not applied to groups inside a CkanCatalogGroup

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1052]
When all the data for a map comes from one CKAN, it makes sense to have the CkanCatalogGroup open by default and immediately start populating. Requested for City of Sydney ESP.

**Comment by kring** [comment]
@stevage you should be able to stick `isOpen: true` in the init file and it will do as you've described.  Is it not working?

**Comment by stevage** [comment]
@kring It's not.

http://nationalmap.research.nicta.com.au/sydney-esp/

http://nationalmap.research.nicta.com.au/sydney-esp/init/sydney.json

**Comment by stevage** [comment]
It's not a particularly up to date TerriaJS, though - has this been implemented recently?

**Comment by stevage** [comment]
(Definitely doesn't work even on up to date TerriaJS)

**Comment by stevage** [comment]
Looks like the Ckan results fetch is being triggered, it's just not actually ending up with an open menu.

**Comment by tephenavies** [comment]
The `itemProperties` property updates properties of data sources that belong the that top level group. In order to open subgroups of a top level group, a new property `childGroupProperties` could be added to the top level group. Including `isOpen: true` in the `childGroupProperties` would expand all second level groups of the specified top level group.

**Comment by stevage** [comment]
@steve9164 We actually already have `itemProperties` which pretty much behaves like that...except I think I tried it in this case and it didn't work.

**Comment by tephenavies** [comment]
@stevage `itemProperties` at this point sometimes applies to subgroups and sometimes to data sources within a group. I was going to clear up these inconsistencies by changing `itemProperties` to only refer to data sources and add a `childGroupProperties` to refer to subgroups.

The reason that the `isOpen: true` in the `itemProperties` currently doesn't work for CKAN is that in CkanCatalogGroup.js, `itemProperty` is only applied to data sources and not to the subgroups.
