### ISSUE TITLE
Why isn't the styles coming through on this json?

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#1055]
On this json, I've set the styles parameter:
http://dev.tampabaymap.org:9000/#https://raw.githubusercontent.com/rsignell-usgs/ehzrap/master/testing/mwra.json
but I can see from the URLs that terriaJS is requesting that the styles parameter is blank:
http://sci-wms.whoi.edu/wms/datasets/smast_wq?time=2015-10-20T00%3A00%3A00.000Z&colorscalerange=6.00%2C12.00&numcontours=50&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&service=WMS&version=1.1.1&request=GetMap&layers=DO&bbox=-7905423.213366069%2C5165920.119625352%2C-7827151.696402049%2C5244191.6365893725&width=256&height=256

What am I doing wrong in this json?
https://github.com/rsignell-usgs/ehzrap/blob/master/testing/mwra.json

**Comment by rsignell-usgs** [comment]
Sidenote: this layer is actually in Massachusetts, USA.   The initial view portal view is in Florida, and unfortunately if you click on "zoom to" you end up near the south pole, so we have some issue with our sci-wms service.  But that shouldn't impact the issue with the styles, right?

Here's what it looks like with the default style (which is why I'm trying to change to colormap jet):
![2015-11-10_17-06-50](https://cloud.githubusercontent.com/assets/1872600/11077321/90f10730-87cd-11e5-9e7d-a8fe96e5599e.jpg)

**Comment by meh9** [comment]
It works if you use a lowercase `styles` in the JSON, but I've not investigated why...

**Comment by RacingTadpole** [comment]
It looks like Cesium's WebMapServiceImageryProvider has a default 'styles' property (lowercase) = ''. Unfortunately it combines user parameters with its own before then converting them all to lowercase, and the default winds up overriding your user-set version. Hopefully a simple fix... I'll raise an issue with cesium now.

**Comment by rsignell-usgs** [comment]
my question was "why doesn't this work"  and now I know how to fix (just use `styles=` instead of `STYLES=`), so...

Should I close, or should we rename this issue "Allow capital STYLES="?

**Comment by RacingTadpole** [comment]
Great - I'll close this one, and when the new Cesium issue (#3195) above is fixed, it will fix the issue in terria as well, i.e. STYLES and styles will both work.

**Comment by RacingTadpole** [comment]
Turns out this is a terria issue. I have submitted a pull request to fix it.
