### ISSUE TITLE
Add support for a "color" column in CSVs

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#1057]
The column, probably with a standard name (e.g. `color`), would be used to set the color of the point or region directly.  CSVs with a color column would ignore the usual color ramp and use the explicitly-specified colors intead.

**Comment by kring** [comment]
Even better: `fillColor` and `strokeColor`.

**Comment by axman6** [comment]
Yes please =)

**Comment by axman6** [comment]
Although, since this is software being developed in Australia, should it not be `colour`?

**Comment by kring** [comment]
> Although, since this is software being developed in Australia, should it not be colour?

Haha, no, sorry.  TerriaJS uses American spellings.  This is partially because TerriaJS "exposes" a bunch of Cesium types that use American spelling, and it would be confusing if they were inconsistent, and partially because Keith and I started TerriaJS and we're not quite sure where to stick all the extra letters ya'll use. :)

**Comment by stevage** [comment]
Kevin and I have discussed this a bit further. A few points:
- `strokeColor` is not possible with the current WMS implementation
- `fillcolor` as a name would limit us to one data variable, and is semantically empty, so I propose "X_fillcolor", where X is the actual meaning of the column (eg `population_fillcolor` means the column is a color representation of population)
- We think it will be hard and messy to generate legends this way, so will probably avoid doing that to begin with.

**Comment by meh9** [comment]
@stevage with "X_fillcolor", just a request to make sure it also works with columns that have spaces in the name.

**Comment by stevage** [comment]
Hmm, good point. This could look weird: `number of immigrants_fillcolor`.

Maybe `_` isn't the best separator. Perhaps `number of immigrants:fillcolor`?

**Comment by meh9** [comment]
Well, I can imagine column names having : in them, maybe get creative and use something like `number of immigrants©fillcolor`? :)

(Option+G) on OSX.

Happy with whatever you think it should be.

**Comment by stevage** [comment]
Well, it wouldn't be a problem if they had another `:`, you just get `my:colon:obsession:fillcolor` which would still work.

Could just be permissive and allow any punctuation.

**Comment by kring** [comment]
> `strokeColor` is not possible with the current WMS implementation

Shouldn't be a problem with the MVT based implementation though. :tada:

**Comment by stevage** [comment]
Just re-reading this, one issue with "fillcolor" and "strokecolor" is they're not very intuitive names for point based CSVs (circles). Combining some of the above comments I think:

- color is a synonym for fillcolor
- "something fillcolor" is interpreted as a value called "something". Any punctutation between that and "fillcolor" is stripped and ignored.
- Hence, "fillcolor" or "color" alone are fine, they're essentially just a column with a meaning but no name - could use "color" as the name.

**Comment by meh9** [comment]
This would solve this issue: https://github.com/TerriaJS/NationalMap-Feedback/issues/668

**Comment by nf-s** [comment]
Done! https://github.com/TerriaJS/terriajs/pull/5736 
Maps will need to have `configParameter.enableGeojsonMvt = true` until we make it enabled by default
