### ISSUE TITLE
Fix misleading "WebGL not supported" message

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#1058]
When WebGL _is_ supported, but we fail to create a context because `majorPerformanceCaveat` is true, we still put up a message box that says "your system does not support WebGL."  This is confusing, especially when the user then clicks on the WebGL link and it reports that WebGL _is_ available.  We should tweak the wording when WebGL has a major performance caveat so that it is not so misleading.

**Comment by tobybellwood** [comment]
This happened to us when a browser had:
- not set "use hardware acceleration when available" (Chrome)
- set "Use software rendering instead of GPU rendering" (IE11).

(We had to change Group Policy to override these)
