### ISSUE TITLE
Having a column called 'depth' prevents CSV file from displaying

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1069]
I'm not totally sure how `depth` is supposed to work, but for at least one user, the effect of a file with many columns containing one column called `depth` is that [nothing displays at all](http://nationalmap.research.nicta.com.au/#start=%7B%22version%22%3A%220.0.05%22%2C%22initSources%22%3A%5B%22init%2Fnm.json%22%2C%7B%22catalog%22%3A%5B%7B%22type%22%3A%22group%22%2C%22name%22%3A%22User-Added%20Data%22%2C%22description%22%3A%22The%20group%20for%20data%20that%20was%20added%20by%20the%20user%20via%20the%20Add%20Data%20panel.%22%2C%22info%22%3A%5B%5D%2C%22isUserSupplied%22%3Atrue%2C%22isPromoted%22%3Afalse%2C%22isHidden%22%3Afalse%2C%22forceProxy%22%3Afalse%2C%22customProperties%22%3A%7B%7D%2C%22isOpen%22%3Atrue%2C%22items%22%3A%5B%7B%22type%22%3A%22csv%22%2C%22name%22%3A%22Rec2011_020_110706_noheader.csv%22%2C%22description%22%3A%22%22%2C%22info%22%3A%5B%5D%2C%22isUserSupplied%22%3Atrue%2C%22isPromoted%22%3Afalse%2C%22isHidden%22%3Afalse%2C%22forceProxy%22%3Afalse%2C%22customProperties%22%3A%7B%7D%2C%22nowViewingIndex%22%3A0%2C%22rectangle%22%3A%5B113.80920000000002%2C-43.3302%2C153.33350000000002%2C-11.0346%5D%2C%22url%22%3A%22https%3A%2F%2Fgist.githubusercontent.com%2Fstevage%2Fb1c090d3c2ee8b414256%2Fraw%2F13f2bfd4bf746899eea8005c943c8258d1a7489d%2FRec2011_020_110706_noheader.csv%22%2C%22isEnabled%22%3Atrue%2C%22isShown%22%3Atrue%2C%22isLegendVisible%22%3Atrue%2C%22isLoading%22%3Afalse%2C%22isMappable%22%3Atrue%2C%22showsInfo%22%3Atrue%2C%22legendUrls%22%3A%5B%5D%2C%22opacity%22%3A0.6%2C%22keepOnTop%22%3Afalse%2C%22disableUserChanges%22%3Afalse%2C%22tableStyle%22%3A%7B%22dataVariable%22%3A%22SITEID%22%7D%7D%5D%2C%22preserveOrder%22%3Afalse%7D%5D%2C%22catalogIsUserSupplied%22%3Atrue%7D%2C%7B%22catalog%22%3A%5B%7B%22name%22%3A%22User-Added%20Data%22%2C%22isOpen%22%3Atrue%2C%22items%22%3A%5B%7B%22name%22%3A%22Rec2011_020_110706_noheader.csv%22%2C%22nowViewingIndex%22%3A0%2C%22isEnabled%22%3Atrue%2C%22isShown%22%3Atrue%2C%22isLegendVisible%22%3Atrue%2C%22opacity%22%3A0.6%2C%22keepOnTop%22%3Afalse%2C%22disableUserChanges%22%3Afalse%2C%22tableStyle%22%3A%7B%22dataVariable%22%3A%22SITEID%22%7D%7D%5D%7D%5D%2C%22catalogOnlyUpdatesExistingItems%22%3Atrue%7D%2C%7B%22initialCamera%22%3A%7B%22west%22%3A108.58800592647073%2C%22south%22%3A-39.20666663543463%2C%22east%22%3A158.55469408730278%2C%22north%22%3A-11.607043439169967%2C%22position%22%3A%7B%22x%22%3A-6339107.022024166%2C%22y%22%3A6663386.815978299%2C%22z%22%3A-4707195.109531058%7D%2C%22direction%22%3A%7B%22x%22%3A0.6127033456752334%2C%22y%22%3A-0.6440464534663358%2C%22z%22%3A0.4580379634657747%7D%2C%22up%22%3A%7B%22x%22%3A-0.3157060305770131%2C%22y%22%3A0.3318561107365471%2C%22z%22%3A0.888932631881753%7D%7D%2C%22homeCamera%22%3A%7B%22west%22%3A109%2C%22south%22%3A-45%2C%22east%22%3A158%2C%22north%22%3A-8%7D%2C%22baseMapName%22%3A%22Positron%20%28Light%29%22%2C%22viewerMode%22%3A%223d%22%7D%5D%7D) (warning - 5MB download in that link).

IMHO 'depth' pretty often refers to something like a borehole depth, and the user has no desire to see a 3D interpretation of it. So I'd lean towards "opt-in" behaviour for recognising a field like this.

In this particular case, it's actually an enumerated field, containing values `BOS` and `TOS`. I don't know why that causes Terria to fail to display anything at this stage.

**Comment by tephenavies** [comment]
Seems to be fixed on [staging nationalmap](http://staging.nationalmap.nicta.com/#start=%7B%22version%22%3A%220.0.05%22%2C%22initSources%22%3A%5B%22init%2Fnm.json%22%2C%7B%22catalog%22%3A%5B%7B%22type%22%3A%22group%22%2C%22name%22%3A%22User-Added%20Data%22%2C%22description%22%3A%22The%20group%20for%20data%20that%20was%20added%20by%20the%20user%20via%20the%20Add%20Data%20panel.%22%2C%22info%22%3A%5B%5D%2C%22isUserSupplied%22%3Atrue%2C%22isPromoted%22%3Afalse%2C%22isHidden%22%3Afalse%2C%22forceProxy%22%3Afalse%2C%22customProperties%22%3A%7B%7D%2C%22isOpen%22%3Atrue%2C%22items%22%3A%5B%7B%22type%22%3A%22csv%22%2C%22name%22%3A%22Rec2011_020_110706_noheader.csv%22%2C%22description%22%3A%22%22%2C%22info%22%3A%5B%5D%2C%22isUserSupplied%22%3Atrue%2C%22isPromoted%22%3Afalse%2C%22isHidden%22%3Afalse%2C%22forceProxy%22%3Afalse%2C%22customProperties%22%3A%7B%7D%2C%22nowViewingIndex%22%3A0%2C%22rectangle%22%3A%5B113.80920000000002%2C-43.3302%2C153.33350000000002%2C-11.0346%5D%2C%22url%22%3A%22https%3A%2F%2Fgist.githubusercontent.com%2Fstevage%2Fb1c090d3c2ee8b414256%2Fraw%2F13f2bfd4bf746899eea8005c943c8258d1a7489d%2FRec2011_020_110706_noheader.csv%22%2C%22isEnabled%22%3Atrue%2C%22isShown%22%3Atrue%2C%22isLegendVisible%22%3Atrue%2C%22isLoading%22%3Afalse%2C%22isMappable%22%3Atrue%2C%22showsInfo%22%3Atrue%2C%22legendUrls%22%3A%5B%5D%2C%22opacity%22%3A0.6%2C%22keepOnTop%22%3Afalse%2C%22disableUserChanges%22%3Afalse%2C%22tableStyle%22%3A%7B%22dataVariable%22%3A%22SITEID%22%7D%7D%5D%2C%22preserveOrder%22%3Afalse%7D%5D%2C%22catalogIsUserSupplied%22%3Atrue%7D%2C%7B%22catalog%22%3A%5B%7B%22name%22%3A%22User-Added%20Data%22%2C%22isOpen%22%3Atrue%2C%22items%22%3A%5B%7B%22name%22%3A%22Rec2011_020_110706_noheader.csv%22%2C%22nowViewingIndex%22%3A0%2C%22isEnabled%22%3Atrue%2C%22isShown%22%3Atrue%2C%22isLegendVisible%22%3Atrue%2C%22opacity%22%3A0.6%2C%22keepOnTop%22%3Afalse%2C%22disableUserChanges%22%3Afalse%2C%22tableStyle%22%3A%7B%22dataVariable%22%3A%22SITEID%22%7D%7D%5D%7D%5D%2C%22catalogOnlyUpdatesExistingItems%22%3Atrue%7D%2C%7B%22initialCamera%22%3A%7B%22west%22%3A108.58800592647073%2C%22south%22%3A-39.20666663543463%2C%22east%22%3A158.55469408730278%2C%22north%22%3A-11.607043439169967%2C%22position%22%3A%7B%22x%22%3A-6339107.022024166%2C%22y%22%3A6663386.815978299%2C%22z%22%3A-4707195.109531058%7D%2C%22direction%22%3A%7B%22x%22%3A0.6127033456752334%2C%22y%22%3A-0.6440464534663358%2C%22z%22%3A0.4580379634657747%7D%2C%22up%22%3A%7B%22x%22%3A-0.3157060305770131%2C%22y%22%3A0.3318561107365471%2C%22z%22%3A0.888932631881753%7D%7D%2C%22homeCamera%22%3A%7B%22west%22%3A109%2C%22south%22%3A-45%2C%22east%22%3A158%2C%22north%22%3A-8%7D%2C%22baseMapName%22%3A%22Positron%20%28Light%29%22%2C%22viewerMode%22%3A%223d%22%7D%5D%7D).
