### ISSUE TITLE
Have a way to disable use of date fields

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1070]
Currently a `date` field in a CSV file always spawns a time slider. I don't think there's any way to disable this. Also, there's no way to specify a date field called anything different.

We could rectify both these issues by allowing:

```
tableStyle: {
  dateVariable: "mydatefield"
}
```

or

```
tableStyle: {
  dateVariable: false
}
```

(This issue comes from a user at the BOM)

**Comment by RacingTadpole** [comment]
Fixed by https://github.com/TerriaJS/terriajs/pull/1262
