### ISSUE TITLE
Generate reference documentation for JSON init/catalog format

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#1083]
It would be useful to have reference documentation for the init files, e.g. when trying to build a share URL (see NICTA/nationalmap#120).  Rather than copying/pasting out of the code or out of the JSONSchema (used for the [Data Source Editor](http://terria.io/DataSourceEditor/)), we should generate the documentation from one of those other sources.  Ideally we'd only have one source (code or JSONSchema) and generate the other two from it.

**Comment by stevage** [comment]
Thanks for raising it - definitely been on my mind for a bit, that they're already diverging fairly quickly.

**Comment by stevage** [comment]
I think https://github.com/TerriaJS/generate-terriajs-schema addresses this.
