### ISSUE TITLE
Support specifying a marker image to use for points in GeoJSON

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#1089]
We could have a solution to issue #1063  and other situations if TerriaJS supported reading `divIcon` from the GeoJSON.   Currently, [the TerrisJS code specifies a specific divIcon icon](https://github.com/TerriaJS/terriajs/blob/master/lib/Models/Leaflet.js#L61-L64) (the SVG image [here](https://github.com/TerriaJS/terriajs/blob/master/wwwroot/images/NM-LocationTarget.svg)).  

To display fields of vectors as well as other symbols, it would be great if it could read the `divIcon` from the GeoJSON files like this one:

```
{
    "type": "FeatureCollection", 
    "features": [
        {
            "geometry": {
                "type": "Point", 
                "coordinates": [
                    -85.427040100097656, 
                    29.559053421020508
                ]
            }, 
            "type": "Feature", 
            "properties": {
                "anchor_x": 6.0527030838993801, 
                "html": "<svg width=\"8px\" height=\"5px\" viewBox=\"-6.0527030839 -3.0210785979 8.0 5.0\" xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\">  <path d=\"M -0.249865829246 0.485500365554 L -0.7353661948 0.235634536307 L -0.749597487739 1.45650109666 L -4.85500365554 -2.49865829246 L 0.749597487739 -1.45650109666 L -0.235634536307 -0.7353661948 L 0.249865829246 -0.485500365554 L -0.249865829246 0.485500365554\" fill-opacity=\"None\" stroke=\"#000000\" stroke-width=\"0\" stroke-opacity=\"None\" fill=\"#FFFFFF\" /></svg>", 
                "anchor_y": 3.0210785979007113
            }
        }, 
        {
            "geometry": {
                "type": "Point", 
                "coordinates": [
                    -85.427627563476562, 
                    29.590583801269531
                ]
            }, 
            "type": "Feature", 
            "properties": {
                "anchor_x": 5.3397999770157512, 
                "html": "<svg width=\"7px\" height=\"6px\" viewBox=\"-5.33979997702 -3.68950133111 7.0 6.0\" xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\">  <path d=\"M -0.272844247079 0.449813269527 L -0.722657516606 0.176969022448 L -0.818532741238 1.34943980858 L -4.49813269527 -2.72844247079 L 0.818532741238 -1.34943980858 L -0.176969022448 -0.722657516606 L 0.272844247079 -0.449813269527 L -0.272844247079 0.449813269527\" fill-opacity=\"None\" stroke=\"#000000\" stroke-width=\"0\" stroke-opacity=\"None\" fill=\"#FFFFFF\" /></svg>", 
                "anchor_y": 3.6895013311055687
            }
        }, 
    ]
}
```

**Comment by metanomy** [comment]
There is now a bounty for this: https://www.bountysource.com/issues/28397348-support-reading-divicon-from-geojson-in-leaflet

**Comment by Vort** [comment]
Here is what I was able to achieve for now:
![terria_arrows](https://cloud.githubusercontent.com/assets/1242858/13695800/a6572a80-e76a-11e5-9d8e-212ef46c89c8.png)
https://github.com/Vort/terriajs/commit/6256792516c076f58dec5c23e0b4605d9cbf7159
https://github.com/Vort/cesium/commit/02d8c1e09f3201534a431c99f9261be54b894416

**Comment by rsignell-usgs** [comment]
@Vort, uh, this looks awesome!   So with these improvements folks can specify their own SVG divIcons, right?

**Comment by Vort** [comment]
@rsignell-usgs, this is not exactly the divIcon, but with this code, if point have svg image specified in it's "html" property, this image gets rendered instead of marker.
But this solution is not perfect. First, it is too laggy in Leaflet mode, second - arrows are not displayed in Cesium mode with Internet Explorer.
If this solution is acceptable in general, I can start investigating on how to solve this problems.

**Comment by Vort** [comment]
New version of my solution is available:
https://github.com/Vort/terriajs/commit/73f9655d6752f386687cd875147f939ee38c0f91
https://github.com/Vort/cesium/commit/f09da23732ea13ffe28911d610b5cc2e5d0b8e67

It is working in 3 browsers (both 2D and 3D mode):
- Vivaldi 1.0.418.3
- Firefox 45.0
- Internet Explorer 11.0

To be able to workaround Internet Explorer [bug](https://connect.microsoft.com/IE/feedback/details/828416/cavas-todataurl-method-doesnt-work-after-draw-svg-file-to-canvas), SVG rendering via [canvg](https://github.com/gabelerner/canvg) module was added.

**Comment by metanomy** [comment]
@rsignell-usgs Do you have a chance to test this?

**Comment by Vort** [comment]
Is there any news?

**Comment by metanomy** [comment]
@Vort, please go to bountysource and claim the bounty.

**Comment by rsignell-usgs** [comment]
@metanomy , I never figured out how to test this.  @jiwalker-usgs, could you try?

**Comment by Vort** [comment]
@metanomy, it is not possible to do when this report is in "open" state.
@rsignell-usgs, I can try to help with testing, but I don't know how.

**Comment by Vort** [comment]
@rsignell-usgs, I was able to set up an VM with TerriaJS installed.
You can connect to it via TeamViewer at least for several hours with login 136129459 and password 4323 and check how my setup is organized.

**Comment by rsignell-usgs** [comment]
@Vort , I cannot look at this today, unfortunately.

**Comment by Vort** [comment]
OK, I can start VM another time (~ at 5-16 UTC+0)

**Comment by kring** [comment]
Relevant comment from @stevage on #1063:

> #1089 is kind of a hacky way of supporting customer markers in GeoJSON files. In Leaflet, a "divIcon" is a way of embedding custom HTML at a point, and is being used here as a way of jamming the contents of an SVG file at the point, as expressed by an html property. It would be cleaner to indicate explicitly that this is an image, like markerImage or something. Unfortunately SimpleStyle doesn't support custom markers (only names of maki icons). So, if we're going to support custom markers in GeoJSON, let's rework this slightly.

**Comment by nf-s** [comment]
I believe this is now supported https://github.com/TerriaJS/terriajs/pull/5080

https://github.com/TerriaJS/terriajs/blob/f5598b672e63bceec9005ad3a586d4615762d019/lib/Traits/TraitsClasses/StyleTraits.ts#L35-L40

https://github.com/TerriaJS/terriajs/blob/92f47a6872b4d521093d01ddf776178d3fb71d67/lib/ModelMixins/GeojsonMixin.ts#L645-L646
