### ISSUE TITLE
Strange formatting of multi-line layers on Now Viewing tab

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#1104]
When catalog items with long names (e.g. `Western Australian Government -> Infrastructure and Utilities -> Odour Buffers Waste Water Treatment Plant WCORP` in NationalMap) are displayed on the Now Viewing tab, they end up centered horizontally and pushed up against the bottom:

![image](https://cloud.githubusercontent.com/assets/924374/11411074/bc649472-9420-11e5-9488-57d24bee3ae9.png)

We should make this look better.

The look of these long labels changed with (I think) #966.  Before that it was different, but still not amazing looking:

![image](https://cloud.githubusercontent.com/assets/924374/11411099/f14778bc-9420-11e5-9b7f-80d55edea079.png)

**Comment by kring** [comment]
@chloeleichen mind looking at this one?

**Comment by chloeleichen** [comment]
@kring , sure i'll make them left aligned and increase the line height a bit?

**Comment by chloeleichen** [comment]
<img width="349" alt="screen shot 2015-11-26 at 10 37 10 am" src="https://cloud.githubusercontent.com/assets/7508939/11411883/b8a7721a-9429-11e5-8c04-f298c6f67899.png">

**Comment by kring** [comment]
That looks great!

**Comment by chloeleichen** [comment]
i think this one can be closed?

**Comment by kring** [comment]
Yep, fixed by #1106.
