### ISSUE TITLE
in 2D mode, interaction with time controls cause map actions

### ISSUE THREAD

**Issue by dcrossleyau** [TerriaJS/terriajs#1107]
When in 2D mode, interation with the time controls cause map actions.
Doing a single-click on the "Play Faster" (or anywhere in the control panel) causes a "feature info" query on the map at that point.
Doing two quick clicks to go faster-faster causes the map to zoom in.
Simlarly when doing double-click anywhere on the time slider.

All is okay in 3D mode.

**Comment by tephenavies** [comment]
Working on this
