### ISSUE TITLE
Populate metadata from CKAN, even when catalog item comes from elsewhere

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#1115]
It's sometimes useful to specify that a catalog item's metadata (e.g. its description) should come from a CKAN dataset, even if the catalog item itself is a direct reference to somewhere else (e.g. a WMS layer).  I can think of two ways to do this:
1. Add a `CkanCatalogItem` (currently we only have `CkanCatalogGroup`) to point to the CKAN resource.  TerriaJS would query the CKAN resource to find out what type of thing it really is, and then access it as WMS, GeoJSON, etc. depending on the type of resource.  This is a bit tricky in our object model, but makes some sense conceptually.
2. Give `CatalogItem` a `ckanResourceUrl` property.  Any catalog item with this property defined would query CKAN for metadata, but would otherwise be a normal catalog item of some other type (e.g. `WebMapServiceCatalogItem`).

**Comment by stevage** [comment]
Fleshing out 1 a bit, would the model be:
- CkanCatalogGroup gets a list of things from the site, and creates a bunch of child CkanCatalogItems?
- and to solve the original problem, you can have a CkanCatalogItem, but override the actual "dataUrl" (or whatever)?

And for 2, do we want some kind of "Metadata" class of which CkanMetadataSource would be one subclass? Having an actual "CkanResourceURL" on objects that have nothing to do with Ckan seems pretty dirty, but a `metadataSource` object would be ok?

**Comment by kring** [comment]
Yeah I'm not a huge fan of 2, either...  I do like your idea of having (a) pluggable metadata source(s) though.

**Comment by RacingTadpole** [comment]
I hit this issue working on https://github.com/NICTA/nationalmap/issues/122 ; these environment.gov.au servers are all available with richer metadata on data.gov.au too.

We will hit a related issue if we want to drag and drop time-series csv files (cf #662). It is only after we load the csv file that we know whether to create a csvCatalogItem (for spatial csvs) or a timeseries-catalogItem. But currently it is the item itself that has the load function.
