### ISSUE TITLE
Switch to new new GA topographic basemap

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#1119]
http://services.ga.gov.au/gis/rest/services/NationalMap_Colour_Topographic_Base_World_WM/MapServer

The URL just needs to be updated in `createAustraliaBaseMapOptions.js`.  It would be good to resnap the thumbnail image (`images/australian-topo.png`) too.

**Comment by kring** [comment]
@steve9164 mind taking care of this one?

**Comment by tephenavies** [comment]
Sure.

**Comment by RacingTadpole** [comment]
@kring - can you fill me in on why we need this change?

**Comment by meh9** [comment]
@RacingTadpole, GA made a new more complete basemap, hosted on their new GIS infrastructure, and would like everybody to migrate off the old one.

**Comment by RacingTadpole** [comment]
great, thanks @meh9.
