### ISSUE TITLE
Error messages not consistent

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#1122]
Some error messages are nice such as the one on the left, however some are not such as the one on the right where `<a href="mailto:data@pmc.gov.au">data@pmc.gov.au</a>` is not even a hyperlink.
![image](https://cloud.githubusercontent.com/assets/13863530/11548300/f77b5936-99ae-11e5-8550-04a54529c9db.png)

This is because error messages are converted to HTML from Markdown, so the error messages that start with 4 or more spaces (caused by code indentation) will be treated as code and placed in `<pre><code></code></pre>` tags (hence the 2 nested blue boxes).

The simplest solution is to fix the error message strings in constructions of `ModelError` so that they are not indented.

**Comment by RacingTadpole** [comment]
Nice catch!
