### ISSUE TITLE
Automatically open the catalogue to show the selected data item after a search

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1135]
_Problem_: I searched for some data, it found some, I selected it, and I went back to the catalogue. Now I have no idea where in the catalogue that data came from.

_A solution_: I think it would be nice to automatically open the catalogue to show the selected data item after a search.  (I'm not saying to switch to the catalog tab automatically.)

@steve9164 showed me there is already a solution in place: you can hover over the checkbox or the info button, in the Search tab, to see where that data comes from.  But I didn't discover that by myself.

**Comment by kring** [comment]
Yeah, no one ever discovers that themselves. :)  Maybe the new UI is a good time to address this properly?

**Comment by hilarycinis** [comment]
Yep, its been observed in user testing too. I agree the new UI will be a better place to address a solution. 
I'll flag with CG,@philipgrimmett @chloeleichen

**Comment by chloeleichen** [comment]
This hasn't been implemented, but the plan is, in the new ui, after user select a data item, they can click on the info button to bring up the Data panel modal window where they'll see the nesting of that data item in data catalog: 
![screenshot](https://cloud.githubusercontent.com/assets/7508939/11620644/ecdd9824-9d08-11e5-8c7b-2968011577ce.jpg)

Also when user are searching the data, they can also click on the info button on the search result to see where this data belongs? Though i'm not quite sure how to indicate this in the modal window data panel, for example, should i set it as the item being previewed and therefore show up in the preview panel? @philipgrimmett? 

<img width="635" alt="screenshot2" src="https://cloud.githubusercontent.com/assets/7508939/11620677/37d9b3a8-9d09-11e5-8391-dc7e639e03b8.png">

**Comment by chloeleichen** [comment]
This is no longer an issue since the data catalog search now happens in the data catalog explorer, so closing this
