### ISSUE TITLE
Feature info on timeseries raster contain values for two times

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1139]
When you click on a raster layer that has a timeseries, like this one:

http://neii.bom.gov.au/services/solarclim/wms/data/monClim_dirNorExp1Day.nc

Then when the feature info window pops up you get two results, one for the time you are currently on, and one for the next time. I'm guessing this is because Cesium pre-loads the tiles for the next time so they are ready to switch to (or something like that).

It would be great to make it only return feature info for the current time interval.

As can be seen in the screenshots below there are two values returned, but only one has the layer name associated with it.

<img width="523" alt="screen shot 2015-12-07 at 15 45 16" src="https://cloud.githubusercontent.com/assets/5283003/11619246/c3664c52-9cf9-11e5-9b53-6f425cd1af8b.png">

<img width="523" alt="screen shot 2015-12-07 at 15 45 23" src="https://cloud.githubusercontent.com/assets/5283003/11619249/cabfcaf0-9cf9-11e5-84c5-3c47f37795cb.png">

**Comment by meh9** [comment]
This is one of our most used layers, so it would be great to have this fixed.

**Comment by kring** [comment]
Here is the code that is _supposed_ to make the "next" layer non-pickable:
https://github.com/TerriaJS/terriajs/blob/c6865feaadc378a7d0e26b27a142c094b3e648ee/lib/Models/ImageryLayerCatalogItem.js#L379

Unfortunately, it was doing this by poking into a Cesium implementation detail that changed recently.  So we either need to update the code to match the new implementation detail, or find a better way to do it.

**Comment by AlexGilleran** [comment]
Have submitted a PR to Cesium to make that toggle public and enabled for all ImageryProviders that support feature picking:

https://github.com/AnalyticalGraphicsInc/cesium/pull/3356

If accepted as is we can just strip the leading `_`s off `_enableFeaturePicking` and the current code will work.
