### ISSUE TITLE
Support property objects in CZML objects for use in templating FeatureInfo boxes

### ISSUE THREAD

**Issue by axman6** [TerriaJS/terriajs#1140]
Currently CZML files don't have a well defined way to attach structured information to CZML objects which can then be templated in the front end. @RacingTadpole and @kring have discussed how this might look, and how it would fit in with the rest of Cesium's time varying structure (if one of you two could add some more details of what you've discussed and the potential implementations that would be great). This is likely something we will need early in 2016 for the network opportunity opportunity mapping project on AREMI, which is one of the most highly sought out datasets on the platform.

**Comment by RacingTadpole** [comment]
Yes, here's the issue we raised in Cesium to discuss this - https://github.com/AnalyticalGraphicsInc/cesium/issues/3162

**Comment by axman6** [comment]
Great, I was sure something had happened, but couldn't find it. Is anyone in the Terria team working to get this into Cesium? We might need the feature before it becomes a part of the official Cesium due to the importance of this data.

**Comment by RacingTadpole** [comment]
It's on my list! We can certainly add it to our own fork of Cesium first.

**Comment by axman6** [comment]
That would be great, I'm happy work through it with you when you get to it. I'm hoping we can have something in place before we need to talk to the data custodian so we've got something clear and structured for them to target.

Worth noting that for our needs, we don't need descriptions to be time varying, so hopefully it'll be as easy as adding the data in the JSON under the "properties" key to the CZML object, and then passing that to the templating code when rendering the feature info for an object.
