### ISSUE TITLE
CKAN duplicate catalog items

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1142]
I'm intermittently seeing an issue where items in a CKAN (data.gov.au and data.vic.gov.au affected) appear duplicated:

![screenshot 2015-12-08 13 43 24](https://cloud.githubusercontent.com/assets/678344/11646393/bc81d312-9db1-11e5-9914-a675a9f78c8f.png)

I haven't investigated yet, and don't have a repro case. I've been doing quite a few searches, so maybe that's triggering it somehow.

**Comment by kring** [comment]
You said this was fixed on the data.gov.au side right?

**Comment by stevage** [comment]
No, that was a different dataset (Ballarat artwork).

**Comment by stevage** [comment]
We recently saw one instance where this problem went away by upgrading to latest Terria. Maybe it has completely gone away? @kring

**Comment by stevage** [comment]
Definitely can't reproduce this now.
