### ISSUE TITLE
ABS DataVariable sort order is unfriendly

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1143]
![screenshot 2015-12-08 14 02 01](https://cloud.githubusercontent.com/assets/678344/11646677/6dcb2bf8-9db4-11e5-9697-8af8d85daad9.png)

Not sure if we can fix this in the general case, or just have to apply specific sorting for these groups. It would be fairly easy to extract the first number with a regex, convert to integer, then use that as key.

**Comment by kring** [comment]
We have a natural sort function:

```
var naturalSort = require('javascript-natural-sort');
naturalSort.insensitive = true;
whatever.sort(naturalSort);
```

**Comment by stevage** [comment]
Thanks @kring
