### ISSUE TITLE
White and blue hover and selection boxes do not line up with base map images in settings panel

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#1145]
In 1.0.48, the boxes that indicate that a base map thumbnail is selected or the cursor is hovering over it line up nicely with the thumbnails, however the boxes are now too long.

1.0.48:
![1 0 48](https://cloud.githubusercontent.com/assets/13863530/11648982/cb0b16b6-9dcd-11e5-9d0e-8e860871a92f.png)

1.0.49:
![1 0 49](https://cloud.githubusercontent.com/assets/13863530/11648981/cb0b2142-9dcd-11e5-80ca-a933020847d7.png)

**Comment by kring** [comment]
Fixed by #1146.
