### ISSUE TITLE
WebMapServiceCatalogItem is broken for geoserver

### ISSUE THREAD

**Issue by leylines** [TerriaJS/terriajs#1152]
The fix in 1.0.47 causes my terriajs to show an empty "Layer name" in the info-window and a "error accessing catalogue item"-message appears when enabling WMS-Layers from geoserver. Version 1.0.46  works fine.

http://maps.leylines.ch:8080/geoserver/ancientMaps/wms?service=WMS&version=1.3.0&request=GetCapabilities
http://maps.leylines.ch:8080/geoserver/ancientMaps/wms?service=WMS&version=1.1.0&request=GetMap&layers=ancientMaps:Piri-Reis-transformiert&styles=&bbox=-89.69360914362133,-53.899457099495095,3.6775709919184862,80.9325719770967&width=531&height=768&srs=EPSG:4326&format=application/openlayers

Catalog Item:

```
            "layers": "ancientMaps:Piri-Reis-transformiert",
            "url": "http://maps.leylines.ch:8080/geoserver/ancientMaps/wms",
            "name": "Piri-Reis",
            "description": "Piri-Reis",
            "dataCustodian": "public",
            "type": "wms"
```

**Comment by meh9** [comment]
I don't know what, if anything, has changed to cause this, but if you change your layer name from `"ancientMaps:Piri-Reis-transformiert"` to `"Piri-Reis-transformiert"` then it works again.

**Comment by kring** [comment]
In 1.0.47 we tightened up TerriaJS's verification of layer names.  Previously it would blindly use whatever you provided, but now it checks the layer name against GetCapabilities.  We could consider some changes here (e.g. if the layer name doesn't match anything in GetCapabilities, just try it anyway, even though that prevents us from retrieving the layer's metadata from GetCapabilities).  But you're probably better off just using the proper layer name reported in GetCapabilities.  Does that work for you @leylines?

**Comment by leylines** [comment]
Thank you very much. It works fine for most of the layers but one layer that i use in the createGlobalBaseMapOptions.js still does not work (it also does not work as Catalog-Item):

http://maps.leylines.ch:8080/geoserver/baseMaps/wms?service=WMS&version=1.3.0&request=GetCapabilities
http://maps.leylines.ch:8080/geoserver/baseMaps/wms?service=WMS&version=1.1.0&request=GetMap&layers=baseMaps:naturalEarthII&styles=&bbox=-180.0,-90.000000000036,180.000000000072,90.0&width=768&height=384&srs=EPSG:4326&format=application/openlayers

Catalog Item:
           {
                "name": "naturalEarthII",
                "description": "naturalEarthII",
                "dataCustodian": "public",
                "type": "wms",
                "url": "http://maps.leylines.ch:8080/geoserver/baseMaps/wms",
                "layers": "naturalEarthII",
                "parameters": {
                        "tiled": true
                },
                "dataUrlType": "none"
           }

Thank you for your help :-)

**Comment by kring** [comment]
TerriaJS is attempting to request tiles using EPSG:3857 (which the server reports in GetCapabilities that it supports) and is getting an error back from the server:

``` xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE ServiceExceptionReport SYSTEM "http://maps.leylines.ch:8080/geoserver/schemas/wms/1.1.1/WMS_exception_1_1_1.dtd"> <ServiceExceptionReport version="1.1.1" >   <ServiceException>
      java.lang.IllegalStateException: Could not locate a layer or layer group with id LayerInfoImpl--4b1ecee6:150f6ca0b9d:-7ffa within GeoServer configuration, the GWC configuration seems to be out of synch
Could not locate a layer or layer group with id LayerInfoImpl--4b1ecee6:150f6ca0b9d:-7ffa within GeoServer configuration, the GWC configuration seems to be out of synch
</ServiceException></ServiceExceptionReport>
```

It looks like server misconfiguration of some sort.  GWC probably stands for GeoWebCache.

**Comment by kring** [comment]
In fact, even GetCapabilities returns an error we request it with `tiled=true`, so that points to a GeoWebCache misconfiguration:
http://maps.leylines.ch:8080/geoserver/baseMaps/wms?service=WMS&version=1.1.0&request=GetCapabilities&tiled=true

**Comment by leylines** [comment]
Sorry for the delay, you are absolutely right. My GWC had a problem with this particular layer. After clearing and rebuilding the GWC everything works fine. I just installed terriajs-server. You are doing a great job. It helps me really a lot with my research on www.leylines.ch.

Thank you all :-)

Jörg
