### ISSUE TITLE
Catalog item search provider should not default to regular expression search

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#1154]
I think it is unintuitive to have regular expression search as the default search mode. In order to search for layers about different types of parks from the PLM25 datasets, you have to search for `park \(plm25\)`.
![unintuitive search](https://cloud.githubusercontent.com/assets/13863530/11707362/8a29f0a0-9f57-11e5-9187-fecfff73525f.png)

The regular expression search is used to make the search case insensitive, but I think special characters should be escaped in the string before it is made into a regex string.

Regular expression functionality could possibly be kept by not escaping regex special characters when "searchtype:regex" or something like that is included in the search.

**Comment by stevage** [comment]
I noticed an elegant solution to this in Chrome's developer tools today:

![Screenshot 2019-03-28 10 27 20](https://user-images.githubusercontent.com/678344/55118987-42b07f80-5144-11e9-8291-997bbbe00206.png)

That is, if the user wants a regex search, they enclose it within `/`. Quite intuitive to programmers. :)

**Comment by zoran995** [comment]
This doesn't seem to be the case anymore
