### ISSUE TITLE
localisation / translation others languages support

### ISSUE THREAD

**Issue by jeanpul** [TerriaJS/terriajs#1156]
Hello,

Thanks for this great application ! I woukd like to contribute and I wonder if it would be possible to add multi languages (using po files). Maybe it's possible, in a first step, to put some special tags in every strings we want to translate and then use a gulp task to parse the compiled js files at the end ?

Best regards

Fabien

**Comment by hilarycinis** [comment]
Hi Fabien, interesting request, thanks! Are you interested in single or double byte languages?

**Comment by jeanpul** [comment]
Hi

Actually I've translated most of the text in French using po file that support UTF-8 encoding (even if for European languages Latin-1 is enough). I'm using specific tags characters around each strings I want to translate. For example, if I want to translate the string <div>Zoom in</div> then I replace it by <div>@<<Zoom in>>@</div>. It works both for javascript and html files. 
Have you already though about localisation support ?

**Comment by hilarycinis** [comment]
Thanks - I can't comment on the localisation support question but just wanted to check it a latin language as that would be very minimal impact on layout and interaction elements.

**Comment by kring** [comment]
@jeanpul I don't know much about best practices for localization of web apps, unfortunately.  But if you've already done something, I'd definitely be interesting in taking a look, and would be willing to merge a reasonable solution that doesn't add too much complexity to our development process.

**Comment by jeanpul** [comment]
@kring I've already done something but I'm not satisfied with it.
As described in my previous post, I've added some special tags for textual elements in the terriajs source files (js & html). The problem is that (correct me if I'm wrong) the source files are not copied into a "build" directory when we run the gulp command, so I cannot add a translation task without modying the original source files. Actually, my translation task is done on the application side ("nationalmap" for you) after all the js files are merged together. 
Here is my translation gulp module : https://github.com/Innovisite/gulp-gettext-static-tags

**Comment by jeanpul** [comment]
One example in favor of using string replacement :
In the SearchProviderViewModel classes, I've put '@<<NOLOC_FOUND>>@' instead of 'Sorry, no locations match your search query.' and the matching is done into po files :
msgid "NOLOC_FOUND"
msgstr "Sorry, no locations match your search query."
or
msgid "NOLOC_FOUND"
msgstr "Désolé, aucun lieu n\'a été trouvé."
for French, at the end it's easier to do this way especially if you need to correct or change the text sentence. Moreover, developpers do not have to worry about text messages.

**Comment by kring** [comment]
@jeanpul perhaps write it as a browserify transform?
https://github.com/substack/browserify-handbook#transforms

Again I can't really speak to what the best practice is for this sort of thing, but I imagine that will work.  Maybe there's even a browserify transform like this on npm already?

**Comment by jeanpul** [comment]
thanks @kring for the link, We cannot transform source files in place as they are in the git tree but we could assemble them into a single js file. I will take a look.

**Comment by kring** [comment]
Sorry, I'm not sure what you mean.  Browserify transforms never overwrite the original files, if that's your concern.

**Comment by jeanpul** [comment]
Sorry it's my fault I missed something into the gulpfile.

**Comment by owlfox** [comment]
Hi, I'm from Taiwan and interested in translating the terria React components into "traditional chinese mandarin", `zh-TW`.

I'm not familiar with l10n, but it looks like it's nice to support `.po` format which has a few open source editors available.
A framework/library [react.i18next](https://react.i18next.com/latest/trans-component) looks like has a better support of it. 
Also, I am trying the other one called [react-intl](https://github.com/formatjs/react-intl), which requires the root component in terriamap to be wrapped by its provider component and struggled a bit when dealing with string comes with  `p`, `strong` by the [FormattedMessage](https://github.com/formatjs/react-intl/blob/master/docs/Components.md#rich-text-formatting) component.

I am still have no idea which way is better, not sure how many strings and components has to be modified...

Lastly I found there's a working #3742 and if I didn't get it wrong, we can add different language translation strings into a file in lib/language like zh-TW.jsx ?

Just wondering how could we help on i18n/l10n.

**Comment by zoran995** [comment]
Some work on supporting internationalization is started with #3787, maybe we can track the work on this in #3785

**Comment by rowanwins** [comment]
Closing in favour of #3785
