### ISSUE TITLE
New Socrata URLs

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1159]
Our Socrata connector no longer works for data.melbourne.vic.gov.au. Their tile URLs are now like [this](https://data.melbourne.vic.gov.au/tiles/5vf3-qixi/the_geom/13/7394/5026.png?$limit=200000&$overscan=32&$mondara=true&$style=%23main%2C%20%23multipoint%2C%20%23point%20%7Bline-width%3A%202.0%3Bline-color%3A%20%23000%3Bline-opacity%3A0.85%3Bmarker-width%3A%208.0%3Bmarker-fill%3A%20%23fb5e2e%3Bmarker-line-color%3A%20%23000%3Bmarker-line-width%3A%202.0%3Bmarker-allow-overlap%3A%20true%3B%7D%23multipolygon%2C%20%23polygon%20%7Bpolygon-fill%3A%20%23AAAAAA%3Bpolygon-opacity%3A%200.5%3Bline-width%3A%201%3Bline-opacity%3A%200.5%3Bline-color%3A%20%23000000%3Bline-simplify%3A%202%7D%23multilinestring%2C%20%23linestring%20%7Bline-width%3A%202.0%3Bline-color%3A%20%230000ff%3Bline-opacity%3A%200.75%3Bline-simplify%3A%202%7D). The minimum we'd need to do to fix this would be:
- add a property to indicate that tiles should be accessed using `OpenStreetMapCatalogItem` instead of WMS
- add a property override the map endpoint (instead of using `geo.owsUrl`), with a variable to indicate where the dataset ID goes

Slightly nicer would be to have the URL query parameters constructed through a JSON object, like:
- tilesUrl: "https://data.melbourne.vic.gov.au/tiles/{id}/the_geom/{z}/{x}/{y}.png
- tilesParameters: {
  "$limit": 20000,
  "$overscan": 32,
  "$mondara": true,
  "$style": "insert CartoCSS here..."
  }

**Comment by stevage** [comment]
Addressed in a different way by #1210. Socrata say (unsurprisingly) that the tile URLs above are internal and subject to change.

**Comment by kring** [comment]
I'm inclined to stay we stick with the solution in #1210 and close this, given that the URLs in this issue are not meant for public use and no one has complained about the other solution in over two years.
