### ISSUE TITLE
Collapsed legend is expanded when switching back to Now Viewing tab

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1162]
When you collapse **all** the legends on the Now Viewing tab, switch away from the tab to for instance the Data Catalogue tab and then back to the Now Viewing tab, then the first of the legends is expanded again. If however one or more legends was left expanded then no additional legend will be expanded. 

For example, with the legend tab in this state:

<img width="349" alt="screen shot 2015-12-14 at 12 31 59" src="https://cloud.githubusercontent.com/assets/5283003/11771011/b9279fec-a25e-11e5-8c19-728bd5b2a1dd.png">

Switch to the Data Catalogue and then back to the Now Viewing tab, the result will be:

<img width="353" alt="screen shot 2015-12-14 at 12 33 02" src="https://cloud.githubusercontent.com/assets/5283003/11771020/d9228032-a25e-11e5-9e82-cf5d120393aa.png">

**Comment by kring** [comment]
Yeah, that's a feature. :)
