### ISSUE TITLE
Ability to show original key/value/data of templated feature info

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1171]
Now that we have the awesome new capability to template the feature info data, it would be useful to have the capability to show the original data - i.e. the untemplated version. In many cases the templates will not display all the data, so there could be more details in the raw data that is interesting to power users. 

The way I imagine it is we have a link/button on a templated view that would expand a panel with the raw data, something like:

<img width="639" alt="screen shot 2015-12-15 at 17 08 32" src="https://cloud.githubusercontent.com/assets/5283003/11803384/850203b0-a34e-11e5-88de-22c3e92e038a.png">

When clicked, this expands to show something like the original untemplated data, something like this:

<img width="633" alt="viewraw" src="https://cloud.githubusercontent.com/assets/5283003/11803490/9ac38c5e-a34f-11e5-910d-066d6f01a228.png">

**Comment by hilarycinis** [comment]
Thanks @meh9 - this certainly fits with the user needs from both testing and needs workshop in November. 

@chloeleichen or @AlexGilleran can you please align it to the right, the placement under the summar is great, and apply an appropriate button style. Please check with @philipgrimmett (or @chloeleichen ) for the style guide.

**Comment by AlexGilleran** [comment]
The style guide is for the new UI so the button styles don't really fit with the current UI. I'm currently implementing it like so:

![image](https://cloud.githubusercontent.com/assets/900555/12133484/daeadfc2-b479-11e5-95ae-94755bf58e4a.png)

Does that look reasonable?

**Comment by axman6** [comment]
Looks good to me, the buttons were merely a placeholder. I’m sure @meh9 will agree that’s fine too.

**Comment by meh9** [comment]
Yeah, we just put the button in by editing the HTML in the debugging console in order to show something, it wasn't a suggestion for the actual look and feel.

I would say that it doesn't look obvious to me at the moment that it's something that I can click, and that isn't part of the template rendered view. Is it a proper link that will change the cursor and get an unerline? In that case it's probably fine and you'll notice when exploring the interface.

**Comment by AlexGilleran** [comment]
Yeah it turns white when you hover over it. Possibly I could make it blue with an underline on hover like some of the links in the templated data?
