### ISSUE TITLE
Commas in numbers in the Feature Info panel

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1172]
In the Feature Info panel, if there is no template given, a large number is formatted with commas (eg. so `1234567` is shown as `1,234,567`). But if a template is given, the number is left as `1234567`. We should rationalise this.

**Comment by RacingTadpole** [comment]
I think the default should be the same as with no template, ie. numbers are formatted with commas.

One way we could do this is to define some new properties in the feature info panel, but only if a template is defined.  

E.g. if `amount` is a number (say 1234567), then we change it to the string `"1,234,567"`, and add a new property `"amount | noCommas"` = `1234567`.

Is that too much of a hack? I guess it immediately lends itself to adding more such, eg. "`| isArray`"...

**Comment by kring** [comment]
A less hacky (but more verbose) approach is to do something like this:

```
{{#nocommas}}{{amount}}{{/nocommas}}
```

Where `nocommas` is a mustache lambda function.  One nice thing about this is you can wrap it around your entire template and the entire thing will be rendered without commas.

**Comment by kring** [comment]
The folks at ABR would also like to see the ability to format numbers without commas (e.g. ABNs).  Also, they noted an inconsistency between how numbers are formatted on the feature info panel (commas are added) and how they're formatted when they appear in the legend (commas are not added).

**Comment by kring** [comment]
Oh, they also found a workaround for preventing TerriaJS from adding commas to numbers: suffix the value with `&nbsp;`.  Unfortunately, if the numbers do appear in the legend, the `&nbsp;` is visible, e.g:

![image](https://cloud.githubusercontent.com/assets/924374/13064341/ebba6c36-d4a5-11e5-8fc2-3c0121c3df02.png)

**Comment by RacingTadpole** [comment]
Interesting! Note in the current release there will be commas in the legend - although that's not the direction of consistency the ABR wants...
It should be easy enough to add the `{{#nocommas}}` syntax.

**Comment by kring** [comment]
My screen shot above was taking with the version of NM we released yesterday, for what it's worth.

**Comment by RacingTadpole** [comment]
Do you know if the ABR can set up a json file with `featureInfoTemplate`?

**Comment by kring** [comment]
@RacingTadpole I don't see why they couldn't...  I'll suggest that.
