### ISSUE TITLE
Download feature info data as CSV/JSON/XML or similar

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1173]
Some users have mentioned that it would be useful to be able to download or export the feature info data as a CSV. 

Since data can be other than CSV, it should probably be a copy of the original data received from the feature info http request, and so would probably be in whatever format was received from the server? Or we could just export the processed data from the feature info datastructure (which I guess could mean that it is structured data, so might need to be JSON or XML).

I imagine it would look something like:

<img width="656" alt="screen shot 2015-12-15 at 17 23 08" src="https://cloud.githubusercontent.com/assets/5283003/11803614/8fca633a-a350-11e5-912b-53ef1c851a02.png">

**Comment by AlexGilleran** [comment]
So what's the use case for this exactly? I would think processing the existing data into CSV would be more useful than the original data seeing as it allows for easy import into Excel? Or do users have some other applications that use the original XML/JSON?

**Comment by meh9** [comment]
I agree that CSV is probably better for the user.

However, I believe that there is the potential that the data is not two dimensional, but has some other structure. In those cases we probably want to be able to return the original data.

**Comment by AlexGilleran** [comment]
Can we give them a choice of formats maybe, then generate that from what we have for them?

I'm going through trying to figure out how to get the original data for all the million formats that feature data can come in (KML, KMZ, etc etc) and it'd be way simpler just to regenerate it.

**Comment by meh9** [comment]
Sure, that sounds ok - by now you know much more about the intricacies of getting the data out than me. :)

**Comment by AlexGilleran** [comment]
So I've got this working with CSV/XML/JSON - if the data is too hierarchical for CSV then it just doesn't show that option.

Right now I'm showing the links to do this under the raw data from https://github.com/TerriaJS/terriajs/issues/1171, as three different buttons. Does this make sense to you @cam-grant ?

![image](https://cloud.githubusercontent.com/assets/900555/12225970/f9ecad40-b868-11e5-8254-3b0f2b9e09ea.png)

**Comment by AlexGilleran** [comment]
The other problem is that in Safari the best I can do is open these in a new tab and have the user manually save them to the right extension. In IE I should be able to force a download but the name won't be right, in Chrome/FF I can give the download a nice name.

However Chrome blocks dynamic XML downloads as malicious, so I've made that always open in a new tab instead of try to automatically download.

**Comment by cam-grant** [comment]
Two possible use cases; 1) Give me the data I see here (as processed by Terria) or 2) Give me the original data. Both are probably valid.

It'd be best to provide a default option, so assuming most users will want what they see in an easily digestible format, we default to Terria's munged CSV and provide options for downloading original data / other formats.

A split button might work well here to provide a clear default option with access to a variable number of alternate options. I'll mock it up and post it.

**Comment by cam-grant** [comment]
![download data - feature info panel](https://cloud.githubusercontent.com/assets/10275015/12249331/1ae56758-b913-11e5-8c0b-bbb0aaef50bb.png)

**Comment by stevage** [comment]
What's the use case for downloading XML? Maybe we don't need it?

(And a user who desperately wants XML can always use a JSON->XML converter.)

IMHO NationalMap in particular is trying to foster data literacy and a data sharing ecosystem, and JSON is a better choice...

**Comment by meh9** [comment]
@stevage I'm happy to not have any other option than CSV, except when the data can not be presented as CSV because it's hierarchical or whatevs, in which case we have to do something different. :)

**Comment by stevage** [comment]
Yeah, to be clear I'm definitely in favour of keeping CSV and JSON.

**Comment by AlexGilleran** [comment]
Definitely happy to leave XML out seeing how it's so annoying to download.
