### ISSUE TITLE
Distance measuring tool

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1178]
Being able to measure the distance between two points or features is a simple but very useful feature that has been mentioned by users on several occasions.

If we don't want to complicate things with measuring a path, then two points is a good first step.

**Comment by rdengate** [comment]
This requires allowing the user to draw lines (and probably polygons, since that's going to be needed for other use cases). I am working on this in branch rd_newui_measure.

To go on this:
    \* UX/UI review and changes based on that, possibly several iterations of this if necessary
    \* Code review, ditto
    \* Bug fix: drawing wonky polygons creates terrible flickering polygon (how does leaflet do it? Also look at turf)
    \* Bug fix: overlapping entities looks bad, as lines over or under points (look at height or eyeOffset)
    \* Bug fix: needs to draw arc in Leaflet rather than straight line (look into how Cesium is subsampling the line and do the same, for consistency if nothing else).
    \* Bug fix: in leaflet, closing polygon doesn't work (#1517) Check if async issue, see github comment
    \* Bug fix: in leaflet, after finishing one polygon, can't start tool and draw another (#1516)
    \* Bug fix: in leaflet, zoom out causes polygon to fly to upper left temporarily (#1515)
    \* Bug fix: sometimes can't click on map (#1433)
    \* Feature: drag points around to adjust
    \* Feature: show area when polygon is created

**Comment by rdengate** [comment]
This is implemented and has been released in AREMI.
