### ISSUE TITLE
Leaflet  performance issue with large csv dataset

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#1183]
While testing #1069, I found that performance using Leaflet changes dramatically depending on the display variable chosen for the given dataset. When using one of the mineral sample variables (e.g. `Ag AR mg/kg 0.002`), even scrolling the "Now Viewing" tab up and down lags considerably well after the dataset has fully loaded and moving the map does so even more. This lag does not occur when plotting `SITEID`, or any of the other all caps display variables.

At first I though this may be because the mineral number are all slightly different and Leaflet couldn't cope with the number of different values, but `SITEID` also seems to be unique to each data point.

I tried profiling in Chrome with a mineral sample selected, and also with one of the all caps variables and the majority of the extra processing is done in "(program)" sections, which corresponds to native non-js code, so displaying the mineral samples is generating many more system calls (or more costly system calls).

Here is a link for [localhost:3001](http://localhost:3001/#map=2d&start=%7B%22version%22%3A%220.0.05%22%2C%22initSources%22%3A%5B%22init%2Fnm.json%22%2C%7B%22catalog%22%3A%5B%7B%22type%22%3A%22group%22%2C%22name%22%3A%22User-Added%20Data%22%2C%22description%22%3A%22The%20group%20for%20data%20that%20was%20added%20by%20the%20user%20via%20the%20Add%20Data%20panel.%22%2C%22info%22%3A%5B%5D%2C%22isUserSupplied%22%3Atrue%2C%22isPromoted%22%3Afalse%2C%22isHidden%22%3Afalse%2C%22forceProxy%22%3Afalse%2C%22customProperties%22%3A%7B%7D%2C%22isOpen%22%3Atrue%2C%22items%22%3A%5B%7B%22type%22%3A%22csv%22%2C%22name%22%3A%22Rec2011_020_110706_noheader.csv%22%2C%22description%22%3A%22%22%2C%22info%22%3A%5B%5D%2C%22isUserSupplied%22%3Atrue%2C%22isPromoted%22%3Afalse%2C%22isHidden%22%3Afalse%2C%22forceProxy%22%3Afalse%2C%22customProperties%22%3A%7B%7D%2C%22nowViewingIndex%22%3A0%2C%22rectangle%22%3A%5B113.80920000000002%2C-43.3302%2C153.33350000000002%2C-11.0346%5D%2C%22url%22%3A%22https%3A%2F%2Fgist.githubusercontent.com%2Fstevage%2Fb1c090d3c2ee8b414256%2Fraw%2F13f2bfd4bf746899eea8005c943c8258d1a7489d%2FRec2011_020_110706_noheader.csv%22%2C%22isEnabled%22%3Atrue%2C%22isShown%22%3Atrue%2C%22isLegendVisible%22%3Atrue%2C%22isLoading%22%3Afalse%2C%22isMappable%22%3Atrue%2C%22showsInfo%22%3Atrue%2C%22legendUrls%22%3A%5B%5D%2C%22opacity%22%3A0.6%2C%22keepOnTop%22%3Afalse%2C%22disableUserChanges%22%3Afalse%2C%22tableStyle%22%3A%7B%22dataVariable%22%3A%22SITEID%22%7D%7D%5D%2C%22preserveOrder%22%3Afalse%7D%5D%2C%22catalogIsUserSupplied%22%3Atrue%7D%2C%7B%22catalog%22%3A%5B%7B%22name%22%3A%22User-Added%20Data%22%2C%22isOpen%22%3Atrue%2C%22items%22%3A%5B%7B%22name%22%3A%22Rec2011_020_110706_noheader.csv%22%2C%22nowViewingIndex%22%3A0%2C%22isEnabled%22%3Atrue%2C%22isShown%22%3Atrue%2C%22isLegendVisible%22%3Atrue%2C%22opacity%22%3A0.6%2C%22keepOnTop%22%3Afalse%2C%22disableUserChanges%22%3Afalse%2C%22tableStyle%22%3A%7B%22dataVariable%22%3A%22SITEID%22%7D%7D%5D%7D%5D%2C%22catalogOnlyUpdatesExistingItems%22%3Atrue%7D%2C%7B%22initialCamera%22%3A%7B%22west%22%3A108.58800592647073%2C%22south%22%3A-39.20666663543463%2C%22east%22%3A158.55469408730278%2C%22north%22%3A-11.607043439169967%2C%22position%22%3A%7B%22x%22%3A-6339107.022024166%2C%22y%22%3A6663386.815978299%2C%22z%22%3A-4707195.109531058%7D%2C%22direction%22%3A%7B%22x%22%3A0.6127033456752334%2C%22y%22%3A-0.6440464534663358%2C%22z%22%3A0.4580379634657747%7D%2C%22up%22%3A%7B%22x%22%3A-0.3157060305770131%2C%22y%22%3A0.3318561107365471%2C%22z%22%3A0.888932631881753%7D%7D%2C%22homeCamera%22%3A%7B%22west%22%3A109%2C%22south%22%3A-45%2C%22east%22%3A158%2C%22north%22%3A-8%7D%2C%22baseMapName%22%3A%22Positron%20%28Light%29%22%2C%22viewerMode%22%3A%223d%22%7D%5D%7D) and [staging.nationalmap.nicta.com.au](http://staging.nationalmap.nicta.com.au/#map=2d&start=%7B%22version%22%3A%220.0.05%22%2C%22initSources%22%3A%5B%22init%2Fnm.json%22%2C%7B%22catalog%22%3A%5B%7B%22type%22%3A%22group%22%2C%22name%22%3A%22User-Added%20Data%22%2C%22description%22%3A%22The%20group%20for%20data%20that%20was%20added%20by%20the%20user%20via%20the%20Add%20Data%20panel.%22%2C%22info%22%3A%5B%5D%2C%22isUserSupplied%22%3Atrue%2C%22isPromoted%22%3Afalse%2C%22isHidden%22%3Afalse%2C%22forceProxy%22%3Afalse%2C%22customProperties%22%3A%7B%7D%2C%22isOpen%22%3Atrue%2C%22items%22%3A%5B%7B%22type%22%3A%22csv%22%2C%22name%22%3A%22Rec2011_020_110706_noheader.csv%22%2C%22description%22%3A%22%22%2C%22info%22%3A%5B%5D%2C%22isUserSupplied%22%3Atrue%2C%22isPromoted%22%3Afalse%2C%22isHidden%22%3Afalse%2C%22forceProxy%22%3Afalse%2C%22customProperties%22%3A%7B%7D%2C%22nowViewingIndex%22%3A0%2C%22rectangle%22%3A%5B113.80920000000002%2C-43.3302%2C153.33350000000002%2C-11.0346%5D%2C%22url%22%3A%22https%3A%2F%2Fgist.githubusercontent.com%2Fstevage%2Fb1c090d3c2ee8b414256%2Fraw%2F13f2bfd4bf746899eea8005c943c8258d1a7489d%2FRec2011_020_110706_noheader.csv%22%2C%22isEnabled%22%3Atrue%2C%22isShown%22%3Atrue%2C%22isLegendVisible%22%3Atrue%2C%22isLoading%22%3Afalse%2C%22isMappable%22%3Atrue%2C%22showsInfo%22%3Atrue%2C%22legendUrls%22%3A%5B%5D%2C%22opacity%22%3A0.6%2C%22keepOnTop%22%3Afalse%2C%22disableUserChanges%22%3Afalse%2C%22tableStyle%22%3A%7B%22dataVariable%22%3A%22SITEID%22%7D%7D%5D%2C%22preserveOrder%22%3Afalse%7D%5D%2C%22catalogIsUserSupplied%22%3Atrue%7D%2C%7B%22catalog%22%3A%5B%7B%22name%22%3A%22User-Added%20Data%22%2C%22isOpen%22%3Atrue%2C%22items%22%3A%5B%7B%22name%22%3A%22Rec2011_020_110706_noheader.csv%22%2C%22nowViewingIndex%22%3A0%2C%22isEnabled%22%3Atrue%2C%22isShown%22%3Atrue%2C%22isLegendVisible%22%3Atrue%2C%22opacity%22%3A0.6%2C%22keepOnTop%22%3Afalse%2C%22disableUserChanges%22%3Afalse%2C%22tableStyle%22%3A%7B%22dataVariable%22%3A%22SITEID%22%7D%7D%5D%7D%5D%2C%22catalogOnlyUpdatesExistingItems%22%3Atrue%7D%2C%7B%22initialCamera%22%3A%7B%22west%22%3A108.58800592647073%2C%22south%22%3A-39.20666663543463%2C%22east%22%3A158.55469408730278%2C%22north%22%3A-11.607043439169967%2C%22position%22%3A%7B%22x%22%3A-6339107.022024166%2C%22y%22%3A6663386.815978299%2C%22z%22%3A-4707195.109531058%7D%2C%22direction%22%3A%7B%22x%22%3A0.6127033456752334%2C%22y%22%3A-0.6440464534663358%2C%22z%22%3A0.4580379634657747%7D%2C%22up%22%3A%7B%22x%22%3A-0.3157060305770131%2C%22y%22%3A0.3318561107365471%2C%22z%22%3A0.888932631881753%7D%7D%2C%22homeCamera%22%3A%7B%22west%22%3A109%2C%22south%22%3A-45%2C%22east%22%3A158%2C%22north%22%3A-8%7D%2C%22baseMapName%22%3A%22Positron%20%28Light%29%22%2C%22viewerMode%22%3A%223d%22%7D%5D%7D). Both of the links download a ~5MB csv file with the data

**Comment by tephenavies** [comment]
@kring I found the performance problem. The style of a lot of the points is being updated each time because it checks whether the colour is equal to the last colour. Somehow the colour is `rgb(NaN, NaN, NaN)` and since `NaN !== NaN` the points are updated each time.

I guess the bug is in the code that sets the marker colour to NaN and not the code that compares the current and previous colours.

**Comment by kring** [comment]
Aah, good find!  Yes, I agree with your assessment of where the bug is.

**Comment by tephenavies** [comment]
The issue is in TableDataSource.js. If a point has a value that is not numeric (e.g. `<0.03`), `dataSource._mapValue2Color` returns `[undefined, undefined, undefined, undefined]`. This is passed to `colorArrayToColor`, which divides each `undefined` by 255, giving `color.red`, `blue`, `green` and `alpha` as `NaN`s.

What should happen if `dataSource._mapValue2Color` is given non-numeric data? It could:
- Attempt to make it numeric by:
  - Removing non-numeric characters from the beginning and end, or 
  - Regexing the first / longest numeric string it can find
- Continue drawing NaNs (which would require changes to the "colour has changed" code)
- Assign some default value
- Skip that point
- Error out and stop drawing the whole layer

In this particular case, it's best just to drop / regex out the leading `<` and use the value `0.03`, but there may be cases where this is not optimal.

**Comment by tephenavies** [comment]
Changes to the legend and colouring have nullified this issue (specifically, the column is now treated as an enum because the values can not all be treated as numeric).
