### ISSUE TITLE
Rounding feature info numbers to specified decimals

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1186]
Similarly to how we would like to insert commas in numbers in the feature info in issue #1172, we would also like to specify rounding of numbers.

For example, the GA LiDAR 25m DEM service returns elevations with 6 decimals, like 721.395935 metres. It would be very good to be able to specify to round that to one decimal, 721.4 metres.

http://services.ga.gov.au/gis/services/DEM_LiDAR_25m/MapServer/WMSServer?service=WMS&version=1.3.0&request=GetCapabilities

**Comment by stevage** [comment]
I think this was fixed by [this](https://github.com/TerriaJS/terriajs/pull/1320)? Reopen if not.
