### ISSUE TITLE
Disclaimer overlaps map credits in printed view in 2D / Chrome

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#1194]
![image](https://cloud.githubusercontent.com/assets/924374/11921420/bc83cf20-a7dc-11e5-954c-0c1ae3aca994.png)

**Comment by chloeleichen** [comment]
Which datasets should I turn on to reproduce this issue?

**Comment by kring** [comment]
You don't need to turn on any datasets.  Just switch to 2D and print from the Chrome hamburger menu.

**Comment by chloeleichen** [comment]
![screen shot 2016-01-12 at 8 56 20 pm](https://cloud.githubusercontent.com/assets/7508939/12260254/f8abca2c-b96e-11e5-9c64-2c5ed815ed7c.png)
What about this?

**Comment by chloeleichen** [comment]
With background colour: 
![bg-color](https://cloud.githubusercontent.com/assets/7508939/12260499/1eb01880-b970-11e5-9452-8448f9c51265.png)

Black text:
![black-text](https://cloud.githubusercontent.com/assets/7508939/12260557/7f874f02-b970-11e5-825a-48624cb8d72a.png)

**Comment by kring** [comment]
That looks great!  Whatever you think on the colors.  Does it still look OK in 3D too?

**Comment by chloeleichen** [comment]
@kring do we still need the smaller disclaimer on print? if so, should it come before or after the big one?

**Comment by kring** [comment]
No, we don't need it, but it might be hard to get rid of, particularly in 3D.  So it's fine to show both if that makes it easier.  It doesn't even matter if 2D and 3D are consistent as long as both show the long disclaimer.  It doesn't matter which one comes first.

**Comment by chloeleichen** [comment]
Removed small disclaimer

2D:
<img width="366" alt="2d" src="https://cloud.githubusercontent.com/assets/7508939/12279458/52aa4e38-b9db-11e5-960c-1040f4104298.png">

3D
<img width="435" alt="3d" src="https://cloud.githubusercontent.com/assets/7508939/12279469/69c34fc0-b9db-11e5-9d77-80a322f80c22.png">

**Comment by kring** [comment]
Doh I should have mentioned one important thing.  The "NationalMap must not be used for navigation or precise analysis" part is not important in the printed view (which is what I thought you meant by "short disclaimer"), but the other map credits (e.g. `Bing, Image courtesy of NASA, Earthstar Geographics SIO, © 2015 Microsoft Corporation, © 2010 NAVTEQ`) do need to show up.  I'm guessing that makes it much harder...

**Comment by chloeleichen** [comment]
What about this:

2D:
<img width="490" alt="2d" src="https://cloud.githubusercontent.com/assets/7508939/12280676/f88a4968-b9e3-11e5-9f10-4d222145c73c.png">

3D :
<img width="475" alt="3d" src="https://cloud.githubusercontent.com/assets/7508939/12280685/ff42b100-b9e3-11e5-98c8-6e66e5253bb2.png">

**Comment by kring** [comment]
That looks fine to me!
