### ISSUE TITLE
Search tab displays when Now Viewing is clicked

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#1197]
Sometimes the Search tab is displayed when Now Viewing is clicked:
![search tab](https://cloud.githubusercontent.com/assets/13863530/11923133/3f09cc5e-a7f3-11e5-852f-535df94d17bc.png)

I do not have a way to reproduce this problem, it just happens sometimes. Some observations:
- Only happened to me switching from Data Catalogue to Now Viewing
- Switching back again to Data Catalogue correctly shows the catalogue and then clicking Now Viewing again leads again to the Search tab
- I had this problem a couple of weeks ago aswell, but I couldn't reproduce it.

**Comment by kring** [comment]
We have a timer that sets the focus to the first element on the tab after the tab animation finishes.  I'm guessing if you switch tabs quickly enough, you can get a timer to trigger after you've already switched away from its tab.

**Comment by tephenavies** [comment]
I had not used the Search tab since navigating to the page, yet it showed up when clicking Now Viewing. 

I currently have 1 tab open that consistently shows this behaviour, however I have not been able to reproduce it in other tabs. No fast clicking is required.

**Comment by chloeleichen** [comment]
I'm having trouble reproducing it again, maybe it's a problem with browsers running in windows?

**Comment by tephenavies** [comment]
Fixed by new ui.
