### ISSUE TITLE
In 2D mode, should not tick datasets that can't show in 2D

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1199]
If you are in 2D, and a dataset doesn't show in 2D, it shows a message, eg.:

`"All Power Stations" cannot be shown in 2D because it does not support the standard Web Mercator (EPSG:3857) projection. Please switch to 3D if it is supported on your system, update the dataset to support the projection, or use a different dataset.`

It leaves the dataset (eg. "All Power Stations") ticked. If you then switch to 3D mode, it does not show the dataset, even though it is ticked.

Terriajs should not tick it in 2D mode.

**Comment by kring** [comment]
When an error occurs in a dataset, it sets the `isShown` property to false and leaves the `isEnabled` property true.  So the dataset stays on the Now Viewing / Legend tab, but the little eye icon has a cross through it.

Here's the rule.  If an error occurs during Load, we disable the layer.  If load succeeds but an error occurs while loading tiles (e.g. 404s), we hide the layer, but do not disable it.  This way it won't disappear from the Now Viewing.  The unsupported projection thing may sound like a load error, but we don't actually find out about it until later, so it's (currently, at least) more like a tile error.

**Comment by RacingTadpole** [comment]
Ah, I see. That makes sense.

Since I didn't realise the eye has been crossed out (I didn't go to the legends tab), I thought I had to untick the dataset and then retick it again in order to see it. Which felt like a bug.

So we could:
- not worry about it
- make a new flag which says that it's only invisible on 2D maps (so that when you go to 3D, it automatically makes it visible)
- set `isEnabled` to false

?

**Comment by kring** [comment]
Yeah, let's close this.  I think it will be a lot more obvious in the new UI because the Now Viewing is always visible.
