### ISSUE TITLE
Support layer style for GeoJSON

### ISSUE THREAD

**Issue by florianm** [TerriaJS/terriajs#1203]
So far, I've managed to style GeoJSON on feature level following [simplespec](https://github.com/mapbox/simplestyle-spec/tree/master/1.1.0). I had to include the styling as properties into each feature (since Quantum GIS offers, but [fails to export style](http://hub.qgis.org/issues/13688) (both feature level and layer level) when saving a layer to GeoJSON):

```
"features": [{ 
"type": "Feature", 
"properties": { 
"pkuid": 1, "title": "SOME TITLE", "longitude": null, "latitude": null, "altitude": null, 
"stroke": "#ff0000", "stroke-width": 2, "fill": "#000000", "fill-opacity": 0.500000, 
"established_by": "PERSON", "established_on": "2015-12-22" }, 
"geometry": { "type": "Polygon", "coordinates": [ [ [...] ] ] } }
]
```

Would it be possible for TerriaJS to support layer level style, e.g.

```
{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"style": {"stroke": "#ff0000", "stroke-width": 2, "fill": "#000000", "fill-opacity": 0.500000},                                                          
"features": [
{ "type": "Feature", 
"properties": { "pkuid": 1, "title": "SOME TITLE", 
"longitude": null, "latitude": null, "altitude": null, 
"established_by": "PERSON", "established_on": "2015-12-22" }, 
"geometry": { "type": "Polygon", "coordinates": [ [ [...] ] ] } }
]
}
```

This would allow to style one whole layer by simply adding one line to the GeoJSON.

**Comment by stevage** [comment]
Did you know that you can also put SimpleStyle in the catalog item? (It's overriden by styles in the file though.)

```
{ 
  "type": "geojson",
  "url": "foo.geojson",
  "style": {
     "stroke": "#ff0000"
  }
}
```

The SimpleStyle spec doesn't seem to mention putting styles at the top level...does anything else do this?

**Comment by florianm** [comment]
Hey that's neat!
My use case is a filtered search on a CKAN catalogue, e.g. "show me all geojson/kml/csv-geo-au resources within a certain CKAN group in a given CKAN instance" ([example](http://catalogue.beta.data.wa.gov.au/dataset/habitat-sampling-initiative/resource/e925914f-0172-4729-88c9-e13b99a56d4f)). Inserting a style into the CKAN item of the catalogue config does not cascade down to geojson layers ([example](http://nationalmap.research.nicta.com/#clean&start=%7B%22version%22%3A%220.0.05%22%2C%22initSources%22%3A%5B%7B%22catalog%22%3A%5B%7B%22name%22%3A%22Habitat%20Sampling%20Initiative%22%2C%22description%22%3A%22Marine%20benthic%20habitat%20data%22%2C%22type%22%3A%22ckan%22%2C%22url%22%3A%22http%3A%2F%2Fcatalogue.beta.data.wa.gov.au%22%2C%22groupBy%22%3A%22organization%22%2C%22filterQuery%22%3A%5B%22fq%3Dgroups%3Ahabitat-sampling-initiative%22%5D%2C%22style%22%3A%7B%22stroke%22%3A%22%23ff0000%22%2C%22stroke-width%22%3A10%7D%2C%22isOpen%22%3Atrue%2C%22includeGeoJson%22%3Atrue%2C%22includeWms%22%3Atrue%2C%22includeKml%22%3Atrue%2C%22includeCsv%22%3Atrue%2C%22includeEsriMapServer%22%3Atrue%7D%5D%7D%2C%7B%22homeCamera%22%3A%7B%22west%22%3A100%2C%22east%22%3A150%2C%22north%22%3A-10%2C%22south%22%3A-50%7D%7D%5D%7D)).

Is there a way to style the output of CKAN data sources, or only the geojson output of CKAN sources?

**Comment by stevage** [comment]
> Inserting a style into the CKAN item of the catalogue config does not cascade down to geojson layer

The way to do that is using the `itemProperties` property.

**Comment by florianm** [comment]
Thanks Steve, I'll give that a whirl!

**Comment by kring** [comment]
@florianm I'm closing this, but you can re-open it if you still have concerns.
