### ISSUE TITLE
Replace live calls to region mapping server in RegionProviderSpec and RegionProviderListSpec

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1205]
As suggested by @RacingTadpole [here](https://github.com/TerriaJS/terriajs/pull/1202#discussion_r48317988).

It would make the tests faster and more isolated.

**Comment by stevage** [comment]
This issue is somewhat mitigated by the fact that the tests that use regionmapping.json now use localised JSON files anyway. So live calls are only made for a couple of tests that follow all the way through to actually loading WMS tiles, or for tests that construct their own region provider.

**Comment by RacingTadpole** [comment]
See https://github.com/TerriaJS/terriajs/compare/ie9 for an example. Also relevant for `RegionProviderListSpec`.

**Comment by stevage** [comment]
I think I did this.

**Comment by RacingTadpole** [comment]
Cool, thanks. Yes, https://github.com/TerriaJS/terriajs/blob/master/test/Models/ArcGisMapServerCatalogItemSpec.js#L24 now fakes the server.
