### ISSUE TITLE
How to debug issues with WMS endpoints?

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#1206]
TerriaJS Gang, I'm trying to add this WMS endpoint:
http://planetarymaps.usgs.gov/cgi-bin/mapserv?map=/maps/jupiter/io_simp_cyl.map&service=WMS&request=GetCapabilities

and after I add usgs.gov to my proxy whitelist and try this:

http://comt.sura.org/proxy_3001/#https://raw.githubusercontent.com/rsignell-usgs/ehzrap/master/testing/astrogeo.json

I get `TypeError: Cannot set property '_parent' of undefined`.

See anything obviously wrong here?

**Comment by kring** [comment]
I was able to get this working using the following init file:

``` json
{
    "corsDomains": [
        "usgs.gov",
        "corsproxy.com",
        "programs.communications.gov.au",
        "www.asris.csiro.au"
    ],
    "initialCamera": {
        "west": -72.07692081488644,
        "south": 41.201720345027695,
        "east": -68.93917805338461,
        "north": 43.00426508306371
    },
    "catalog": [{
        "name": "AstroGeo Datasets",
        "isOpen": true,
        "type": "group",
        "items": [{
            "name": "Jupiter",
            "isEnabled": true,
            "type": "wms",
            "url": "http://planetarymaps.usgs.gov/cgi-bin/mapserv",
            "parameters": {
                "map": "/maps/jupiter/io_simp_cyl.map"
            },
            "metadataUrl": "http://planetarymaps.usgs.gov/cgi-bin/mapserv?map=/maps/jupiter/io_simp_cyl.map&service=WMS&version=1.3.0&request=GetCapabilities",
            "layers": "SSI_VGR_color",
            "tilingScheme": "geographic"
        }]
    }],
    "isOpen": true
}
```

The unusual thing about this server is the extra `map=/maps/jupiter/io_simp_cyl.map` parameter.  When building WMS URLs, TerriaJS strips off all query parameters (that way you can initially give it a GetCapabilities URL or even a GetMap URL and it will work).  But in this case that query parameter is required.  So we use the `parameters` property to add it to `GetMap` requests, and we supply a custom `metadataUrl` that includes the extra parameter.

Next, this server does not support the Web Mercator projection, which means it won't work in Leaflet.  But it does support EPSG:4326, which is good enough for Cesium.  However, for some reason, TerriaJS is not able to figure out what projection to use from the GetCapabilities document.  So it tries to use Web Mercator and fails.  The `"tilingScheme": "geographic"` line above overrides this.

**Comment by rsignell-usgs** [comment]
Kevin,
Woohoo!  Super cool!
http://comt.sura.org/proxy_3001/#https://raw.githubusercontent.com/rsignell-usgs/ehzrap/master/testing/astrogeo.json

BTW, this got me wondering: is there a way to actually map this on Jupiter instead of the Earth?

**Comment by kring** [comment]
@rsignell-usgs,

> is there a way to actually map this on Jupiter instead of the Earth?

AGI has a history of doing visualization of planets other than Earth, so we were definitely thinking about this when writing Cesium.  In theory, you should be able to provide an appropriate Jupiter `Ellipsoid` and `Projection` / `TilingScheme`, supply them in the right places (e.g. when constructing the Cesium Scene) and it will work.  In practice it's not well tested.  Also, TerriaJS is likely to need a bit of work because we never really intended it to be useful outside of Earth.

**Comment by rsignell-usgs** [comment]
@kring, okay, thanks for the info.  I'll pass that along to our astrogeology folks.
