### ISSUE TITLE
Progress on Mapbox vector tiles for region mapping

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#1211]
This issue is to help me and others keep track of my current progress with re-implementing region mapping using Mapbox vector tiles. I will keep it updated as I continue with the project.

Tasks:
- [x] Client:
  - [x] Query Mapbox server for tiles
  - [x] Process the data received and extract polygons
  - [x] Draw polygons in Mapbox vector tiles on a canvas
    - [x] Convert polygon coordinates from latitude and longitude to canvas coordinates
    - [x] Draw each polygon as a closed canvas path
  - [x] Colour the regions according to id
  - [x] Colour the regions according to a given colour function (like in `ImageryProviderHooks`)
  - [x] Integrate into `CsvCatalogItem`
  - [x] Add feature picking
  - [x] Add border to regions
  - [x] Verify that the id being used is the correct one
  - [x] Add error and exception handling
  - [x] Fix 404 errors where requests for tiles outside Australia are being requested (fix with bounding box)
  - [x] Improve Leaflet method:
    - [x] Fix exceptions
- [x] Server:
  - [x] Get vector tiles from shapefile
  - [x] Try cutting vector tiles on the fly
  - [x] Try pre-cut tiles
  - [x] Serve the vector tiles
  - [x] Get TerriaJS connecting to vector tile server
  - [x] Try a mix of pre-cut (levels 0 to 11 should take about 70MB of space) and cut on the fly for levels below that:
    - [x] Loop over tiles from tilelive-bridge and store them to node-mbtiles
    - [x] Set up Tessera (or maybe modify it) so that it can switch between sources at a certain level
- [ ] Sort out attributions:
  - [x] Update licence in `terriajs mapbox_vt_region_provider`
  - [ ] Work out licence for `TerriaJS/server-config`
  - [x] Fix licences in tilelive modules
- [x] Highlight clicked regions (see #1381)

Bug List:
- [x] Selecting a region which is fully enclosed by another region puts both regions in the feature info panel (should only put the inner region). E.g. ACT is fully enclosed by NSW
- [ ] Leaflet tries to retrieve tiles outside of the bounds rectangle with an x value of 0 (e.g. 4/0/8-10 and 3/0/4-5)'
- [x] The name shown in feature info isn't the right name. A nameProp needs to be added to `regionMapping.json` so that the correct name can be shown:
  - nameProp can be found using `find data2/ -name *.shp -print0 | xargs -0 -I {} sh -c "ogrinfo -al -so {} | egrep -i 'name|title' | head -2"`

[Server wiki page](https://github.com/NICTA/nationalmap/wiki/Using-a-vector-tile-source-for-region-mapping)

Decisions to make:
- Is Tessera the way to go? (with slow [~300ms] loading tiles at zoom level 12 and beyond)
  - Yes. Tessera is fine as long as a source with a spatial index is used.
- Maybe something other than a shapefile should be used:
  - Database of some kind (PostGIS db, mapbox/cardboard, ...)
- Could add a spatial index to the shapefiles if there is a command line utility that will generate them
  - There is: mapnik's `shapeindex`
- If Tessera and the current method is the way to go, how should tiles be generated?
  - Run the job on a local computer and let it take however long it wants to
  - Run it on a server (such as AWS)
  - Maybe run it as AWS Lambda function?
    - Would have to break the tile generation process into parts that take less than 5 minutes per query
  - The way that was chosen was to run it locally. Ubuntu seems to run the process much faster than Windows and doesn't have the memory leak issues.

Progress:
![sa4 regions](https://cloud.githubusercontent.com/assets/13863530/12083173/e535acca-b2f1-11e5-961d-4ba66a2923e5.png)

This is a screenshot of 20 canvasses (4 rows of 5) drawn from Mapbox vector tiles using code I've written on the `mapbox_vt_region_provider` branch. Each canvas corresponds to one vector tile from a Mapbox server I have set up using the online Mapbox Studio tool and an SA4 regions shapefile. This was a test to make sure that regions line up and that the polygons were being drawn correctly. Each region is coloured according to it's id.

**Comment by tephenavies** [comment]
An attempt to use the vector tiles for region mapped data:
![a couple of regions](https://cloud.githubusercontent.com/assets/13863530/12084190/1a877d10-b304-11e5-86ec-70e2c315112f.png)

These regions disappear when you zoom in.

No regions show using Leaflet.

**Comment by tephenavies** [comment]
Side-by-side comparison of my Mapbox vector tile region mapping and old method:

![side by side comparison](https://cloud.githubusercontent.com/assets/13863530/12084442/8164fe24-b307-11e5-8ca9-8d1991ec398c.png)

The colours are different, however the underlying `_colorFunc` seems to have changed so this could be a non-issue. Region mapping with vector tiles currently only works with Cesium and only for SA4 regions.

**Comment by stevage** [comment]
The choroplething method on more-color-art is definitely different to master, so you'd expect different results. If you want to do a side by side comparison, you could add `"colorBinMethod": "none"` to a relevant CSV item `tableStyle`.

**Comment by tephenavies** [comment]
Managed to get Leaflet redering working. Here's a side-by-side comparison of Leaflet rendering:
![leaflet side by side](https://cloud.githubusercontent.com/assets/13863530/12104227/83df788c-b39d-11e5-80cb-bda1dd3613a5.png)

**Comment by tephenavies** [comment]
Feature picking working in Cesium, not yet in Leaflet:
![vector tile feature selection](https://cloud.githubusercontent.com/assets/13863530/12109399/ad4ab26c-b3d5-11e5-91a7-cf8529408a45.png)

Testing with feature selection, I found that the ID associated with each region is 1 above the ID that CsvCatalogItem uses to identify the regions (not sure if this is a data or server issue. If the ID is defined in the data I gave to Mapbox, it's a data issue but if Mapbox assigned them all IDs according to their order in the file and ended up giving them IDs 1 greater than what they should then it's a server issue and could be fixed while changing servers)

**Comment by tephenavies** [comment]
Feature selection now working in Leaflet. Very fast! Quite noticeably faster than on current nationalmap. Looks like it may be possible to do highlighting as the cursor moves based on the picking features speed.

**Comment by stevage** [comment]
> I found that the ID associated with each region is 1 above the ID that CsvCatalogItem uses to identify the regions (not sure if this is a data or server issue.

Yeah, IDs are awkward and fragile. We freeze feature IDs (FIDs) in our shapefiles, which GeoServer serves up to us in the WMS. But there's nothing particularly special or sacred about them, so if Mapbox can't be made to use the same IDs, we'll just have to work around that somehow.

**Comment by tephenavies** [comment]
The Mapbox vector tiles are created from a shapefile downloaded from ABS. If we have our own shapefiles with FIDs, then we should be able to make vector tiles from them which will include the FID.

**Comment by stevage** [comment]
In case you didn't know, you can download our region boundaries as shapefile just by going to our geoserver: http://geoserver.nationalmap.nicta.com.au/region_map/web/;jsessionid=53CFA4EDD8C3DF1D2B89A22CF73252E7?wicket:bookmarkablePage=:org.geoserver.web.demo.MapPreviewPage

**Comment by tephenavies** [comment]
Progress since last comment:
- Set up a server on my computer that cuts vector tiles from shapefile and serves them
- Configured MapboxVectorTileImageryProvider to use the local server for loading region tiles
- Storing pre-generated tiles in an mbtiles database to speed up requests (substantially faster than generating the tiles on-the-fly)

**Comment by stevage** [comment]
What server are you using? PGrestAPI?

**Comment by tephenavies** [comment]
I'm using [tessera](https://github.com/mojodna/tessera).

**Comment by tephenavies** [comment]
I have published both [the server](https://github.com/steve9164/server-config) and the client (on [`terriajs/mapbox_vt_region_provider`](https://github.com/TerriaJS/terriajs/mapbox_vt_region_provider)). The server has some specific requirements on node version though because it use [mapnik](https://www.npmjs.com/package/mapnik) which uses binaries. The current list of supported linux and osx node versions can be found [here](https://github.com/mapnik/node-mapnik/blob/master/.travis.yml#L31-L59) and supported Windows node versions [here](https://github.com/mapnik/node-mapnik/blob/master/appveyor.yml#L9-L32).

**Comment by stevage** [comment]
Awesome work. Having weird server requirements for this isn't too bad as it will probably live on its own server, separate from Terria/NM.

**Comment by tephenavies** [comment]
Thanks. I'm not too worried about these requirements as they have a reasonable amount of binaries available, however I thought I'd document the requirements here as having an unsupported node version results in some fairly cryptic errors. I had this problem yesterday because I was using node 0.11 and mapnik (which was a dependency of a dependency) has binaries for 0.10 and 0.12. It took a couple of hours (and some help from @kring) to work that out...

**Comment by tephenavies** [comment]
[Here](https://tonicdev.com/568c9ee861bef80d0022c946/5695d92133b2840c007fee08) is a calculation of how many vector tiles need to be stored to serve pre-generated vector tiles for every zoom level from 0 to a certain level. I have tested generating levels 0 to 11 which took a few hours to run (using [save_tiles.js](https://github.com/steve9164/server-config/blob/master/save_tiles.js)) and made [store2.mbtiles](https://github.com/steve9164/server-config/blob/master/data/FID_SA4_2011_AUST/store2.mbtiles), which is around 9mb. I'm currently running a generation of level 0 to 14 tiles, which will take about 12 hours running time by the time it's finished and be about 150mb.

How big should pre-generated tiles for each region mapping system be? 150 mb seems reasonable, however 600 mb seems a bit high for the small advantage (only 1 extra pre-generated zoom level) that it gives.

**Comment by tephenavies** [comment]
### Progress so far

Client:
- Almost complete. When csv_refactor is ready, I can port the code across to that and modify RegionProvider to use the new server

Server:
- I have written scripts so that region maps listed in regionMapping can be automatically downloaded as shapefiles, unzipped, have tiles to a certain zoom level generated from them and generate all configuration files the server needs to be able to use them
- Server is working and will serve region maps at `http://server.ip/layerName` at zoom levels from 0 to 20 (or whatever I set it to). This includes switching from pre-generated tiles and tiles generated on demand at the server without the client knowing at around level 12-14 (haven't decided yet)
- The space requirements for serving all of the current region maps on the new server will be 3-10 GB including both pre-generated tiles and the shapefiles

Problems:
- Pre-generation of tiles takes ages (it could take a week to generate tiles for all region maps on this laptop)
- Still getting 404 errors within the bounding box (this should be fairly easy to fix. I'll probably fix this today)

**Comment by axman6** [comment]
@steve9164 Talk to @peterhassall (or @meh9) about running a batch job on AWS on a beefy machine with lots of CPU and/or RAM. We do it quite frequently for AREMI datasets which take several hours to process. Is it something that's easy to split into several processes and get a parallel speedup?

**Comment by tephenavies** [comment]
Thanks @axman6 for the suggestion. The scripts are parallelised, currently they run 5 processes in parallel. I'll look into the possibility of running a batch job like this when I have my client and server finalised so I don't have to do it twice.

**Comment by tephenavies** [comment]
[Optimising shapefiles](https://www.mapbox.com/tilemill/docs/guides/optimizing-shapefiles/)
- Convert to Spherical Mercator projection
- Add a spatial index with `shapeindex`

Additional information about shapeindex; https://developmentseed.org/blog/2011/mar/29/speed-optimizations-tilemill-shapefile-indexes/

Search for `shapeindex` on [this page](http://sourceforge.net/p/topomapcreator/wiki/TileMill/) for installation instructions

**Comment by tephenavies** [comment]
I did some testing with a spatial index generated by Mapnik's `shapeindex`.

Tests: 
- All tests performed using SA4 shapefile generating tiles from zoom level 0 to 8
- Test 1: No index. Time taken 1m20.654s
- Test 2: Indexed with `shapeindex`. Time taken: 0m23.481s
- Test 3: Index file deleted: Time taken 1m9.649s

Adding a spatial index for a shapefile (using `shapeindex`) before generating tiles makes tile generation 4 times faster.

**Comment by tephenavies** [comment]
After a lot more testing of `shapeindex` with other shapefiles and combinations of options, I have found that the command `shapeindex file.shp -d 30 --index-parts -r 0.85` is good for creating the spatial index. This reduced the time to generate tiles from an SA1 shapefile (the largest shapefile) of levels 0 to 8 from 5m34.982s to 0m17.889s. What's more, the index file is only 1.7MB for a 145MB shapefile.

Maybe after all this optimisation of the tile generation, tiles won't actually have to be pre-generated :smile:  (since the spatial index will speed up on-the-fly generation)

**Comment by axman6** [comment]
IF youre going to do it on the fly, is there any reason to not put the shapefile data into a faster format, such as Spatialite or even a PostGIS database?

**Comment by stevage** [comment]
Yeah, I'm happy to help with that if needed - used PostGIS quite a bit.

**Comment by tephenavies** [comment]
That would be a good idea. How would I go about putting the region maps into a PostGIS database? Should I start with the shapefiles?

**Comment by axman6** [comment]
`ogr2ogr` makes it quite easy to take a shape file and put it in PostGIS. Then you just need to add a GIST index on the geometry column to get the performance you want.

**Comment by axman6** [comment]
(Or gdal_translate actually, I can never remember which is raster and which is vector)

**Comment by tephenavies** [comment]
After a long (and painful) trial and error process I finally have a procedure to load all of the information from a shapefile into a PostGIS database:
1. Create the database using sql with a PostGIS spatial database as a template:
   `CREATE DATABASE <name> TEMPLATE postgis_template;`
2. Run the following command to store the shapefile in the database:
   `ogr2ogr -f PostgreSQL -t_srs EPSG:3857 PG:"user=postgres host=localhost dbname=test_a" data2\FID_SA4_2011_AUST\FID_SA4_2011_AUST.shp -preserve_fid -overwrite -skipfailures -fieldTypeToString Real -nlt MultiPolygon 2> out.txt`

Problems:
- Creating the template database requires reinstalling the PostGIS extension so you can click the "Create sample spatial database" (there's probably a different method, but none of the methods I found online worked)
- `ogr2ogr` needs to be run with the environment variables set up, so needs to be run through GDAL command prompt
- Mapnik doesn't like either the xml setting up the PostGIS connection, or the database itself and won't make tiles

**Comment by tephenavies** [comment]
@axman6 Thanks for the tip. The change from shapefile to PostGIS sped up normal request times from 150-350ms to around 80-120ms and maximum request processing time from 500ms to 300ms, which should mean that on-the-fly generation is acceptable.

**Comment by tephenavies** [comment]
I forgot to include a shape index in my last test. Including this index reduces tile generation time using a shapefile to virtually the same as using a PostGIS database with a spatial index.

Through further testing using `curl` to request tiles, I found that both methods have latencies within 5% of each other, and also that the large (300+ms) request times that I found when trying to load many tiles by dragging the map quickly while having a region-mapped layer on are caused more by CPU saturation because of the nationalmap application rather than the server not being able to keep up with requests.

Here's a graph of the different tile generation approaches:
![newplot 1](https://cloud.githubusercontent.com/assets/13863530/12632631/6d934f46-c5ad-11e5-9f26-2cd3a9905c15.png)

The 3 data set represent the request time in ms for ~800 requests for each tile generation approach: 
1. Shapefile with an index made using custom shapeindex command (see [comment above](https://github.com/TerriaJS/terriajs/issues/1211#issuecomment-173766968))
2. PostGIS database with default index
3. Shapefile using default (no parameters) shapeindex

Conclusions:
- Shapefile with index is just as fast as PostGIS database
- Generating tiles on-the-fly will be fast enough if the server is run on a different computer

**Comment by tephenavies** [comment]
Having issues with vector tiles of some states working and others not, which is very weird. Only tiles with polygons from NSW and Victoria work for some layers. Testing shapefiles using `ogrinfo` reveals that the polygons for other states exist, but Mapbox's tilelive-bridge module isn't giving me these.

#### `ogrinfo` tests using tile 6/55/36:

`ogrinfo -al -geom=NO -spat 14401959.121379767 -3130860.67856082 15028131.257091932 -2504688.542848654 FID_SA4_2011_AUST\new2\FID_SA4_2011_AUST.shp` gives:

> Layer name: FID_SA4_2011_AUST
> Geometry: Polygon
> Feature Count: 20
> Extent: (10777612.617701, -5425372.869126) - (17711957.240486, -1022048.471345)
> Layer SRS WKT:
> PROJCS["WGS_84_Pseudo_Mercator",
> ...

`ogrinfo -al -so -spat 129.375 -27.059125784374054 135 -21.943045533438166 FID_SA4_2011_AUST\FID_SA4_2011_AUST.shp` giives:

> Layer name: FID_SA4_2011_AUST
> Geometry: Polygon
> Feature Count: 20
> Extent: (96.816941, -43.740510) - (159.109219, -9.142176)
> Layer SRS WKT:
> GEOGCS["WGS 84",
> ...

The first `ogrinfo` is on a reprojected version of the second, made with the command `ogr2ogr -t_srs EPSG:3857 -overwrite -fieldTypeToString Real -f "ESRI Shapefile" new_folder original.shp`. Every attribute is a String (since Reals are converted to Strings).

**Comment by tephenavies** [comment]
The states error seems to be caused by the index file. I cannot find a way to fix this index file. Switching to PostGIS database in order to avoid `shapeindex`.

**Comment by tephenavies** [comment]
There is a bug with my feature picking code. Clicking on Canberra when viewing a dataset using the state region type pops up a feature info for both NSW and ACT.

**Comment by tephenavies** [comment]
Working on highlighting regions when they are clicked (like #1381). Progress so far: 
![highlight on click](https://cloud.githubusercontent.com/assets/13863530/13694969/815adaf8-e7ae-11e5-9321-f8738ef6965b.gif)

I need to work out how to redraw tiles that have a selected region. Currently it relies on changing zoom to cause the tiles to be redrawn.

Possible ways:
- Keep an object with keys as region ids and values as a list of the currently displayed tiles that have that region on them, and then tell Cesium to update those tiles (somehow)
- Get the vector tile server to also serve extents of features, and then tell Cesium to invalidate a certain rectangle so it is redrawn (this is probably something Cesium has built in?)
- Have a separate layer for highlight borders that fetches vector tiles within a feature extent (uses extent server from point 2) and draw just the border of the highlighted polygon (this would be extremely fast as the tiles will be cached by browser, you only have to draw 1 feature and you can filter out other features based on their properties before retrieving geometry from the vector tile – which is the slowest part of interpreting vector tiles)

Alternatively:
- Create a new MapboxVectorTileImageryProvider layer with a `styleFunction` that styles the selected region's polygons to have no fill and a highlighted border and an opacity of 100%. Adding another function `filter` passed into MapboxVectorTileImageryProvider could also be a useful to not fetch geometry or draw features that are rejected by the `filter` function.

**Comment by tephenavies** [comment]
Links for comparing changes for updating tilelive modules:
- ~~[`tilelive-bridge`](https://github.com/steve9164/tilelive-bridge/compare/master...mapbox:master)~~
- [`tessera`](https://github.com/steve9164/tessera/compare/master...mojodna:master)
- [`tilelive-cache`](https://github.com/steve9164/tilelive-cache/compare/master...mojodna:master)

**Comment by tephenavies** [comment]
Problem with Tippecanoe generated tiles:
![image](https://cloud.githubusercontent.com/assets/13863530/14169091/980bb862-f771-11e5-9fe8-4760851d052e.png)
They contain random vertical and horizontal lines that disappear when you change zoom. Haven't investigated whether the old style generated tiles also have these.

Update: This is caused by Tippecanoe splitting polygons with more than 700 vertices, and is solved by including the option: `-pp or --no-polygon-splitting: Don't split complex polygons (over 700 vertices after simplification) into multiple features.`

**Comment by tephenavies** [comment]
Found that my tilelive-bridge vector tiles were 9x as big as they needed to be as they have a "buffer" the size of the tile surrounding them. [Mapnik XML spec](https://github.com/mapnik/mapnik/wiki/XMLConfigReference) is wrong - you need to put `buffer-size="5"` on a `Layer`, not a `Map` to get a buffer of 5 pixels around the tile. When you leave that off, the default is a buffer the size of the tile (and not 0 as the spec says).
