### ISSUE TITLE
Square in space in Cesium 3D

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#1215]
There is a white square in space in the Cesium 3D model.
- Close up of the square: http://nationalmap.gov.au/#share=8lk0yC
- The square and the Earth in the same frame: http://nationalmap.gov.au/#share=IV1QS7

**Comment by tephenavies** [comment]
Here's both the close up and the square and Earth:

![white square](https://cloud.githubusercontent.com/assets/13863530/12108104/82de7d78-b3c7-11e5-8801-b3fef5419332.png)

**Comment by AlexGilleran** [comment]
The truth is out there...

![pacmanearth](https://cloud.githubusercontent.com/assets/900555/12108206/278f786c-b3c9-11e5-8726-b0e409aa3855.png)

**Comment by tephenavies** [comment]
Turns out the problem was that my computer was (on default settings) using integrated graphics for everything instead of the NVIDIA card it has (NVIDIA Optimus at it's best). Updating my drivers and switching to high performance graphics fixed the issue and my computer is now able to draw the sun.

My other performance issues with Cesium are fixed as well. No more waiting 12 seconds for the Earth to show up!
