### ISSUE TITLE
Add regionmapping.json to TerriaJS

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1227]
Might as well make it a Terria functionality, not just an NM one.

**Comment by kring** [comment]
The file exists in TerriaJS at this point, but I believe NationalMap and TerriaMap still use their own copy rather than the one included in TerriaJS.

**Comment by stevage** [comment]
Suggested plan:

- terriajs/wwwroot/data/regionmapping.json is the official source of truth
- instances of TerriaMap may override that with their own copies
- the TerriaMap build process (gulp) checks if there is a local copy already in wwwroot/data/regionmapping.json, and if not, copies the TerriaJS copy.

**Comment by stevage** [comment]
Actually turns out to be simpler to just access `build/terriajs/data/...` directly.

I'm not sure what the ramifications of updating TerriaJS's regionmapping.json to find regionids files in `build/terriajs/data/` rather than `data/` are though. For that matter, I'm actually not sure what the purpose of regionmapping.json in TerriaJS was, other than for unit tests?
