### ISSUE TITLE
Broken Data URL link shown for local file 

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#1229]
When you add a local GeoJSON file (using upload or drag and drop) and go to Info in the Now Viewing panel, a Data URL is given that points to http://localhost:3001/test.json (since my file was called test.json). This is a broken link as the file was local, not from the server.
![data url local file](https://cloud.githubusercontent.com/assets/13863530/12313655/a15598b6-babd-11e5-968d-53ef96c7ab35.png)

**Comment by stevage** [comment]
Hmm. To handle this properly I think we need to use JS to generate a fake file for download from the `.data` property.

Or, we could just not show a URL. Why does the user really need to download data they just added, anyway?

**Comment by stevage** [comment]
I went with the second option.

<img width="647" alt="screenshot 2016-03-16 11 00 51" src="https://cloud.githubusercontent.com/assets/678344/13798049/5f795386-eb66-11e5-94ef-d1cd03f360ae.png">

Any comment on the text, @hilarycinis ?
