### ISSUE TITLE
GeoJSON layers with the same filename are the same colour

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#1230]
If you add a local GeoJSON file `test.json`, then add a different file called `test.json`, the two layers that represent the 2 json files are drawn on the map in the same colour. However, if you add the same file twice with different names (say `test.json` and `test2.json`) the 2 layers have different colours.

**Comment by kring** [comment]
That's actually by design.  The colors are chosen randomly but using the dataset name as the seed.  That way they're consistent from run to run.
