### ISSUE TITLE
IE11 display issue with data catalogue

### ISSUE THREAD

**Issue by aherald** [TerriaJS/terriajs#1235]
On IE11, win 7, there is a display issue with the display of data catalogue.  A screen shot is attached

 Scenario
1.      User adds data from the catalogue
2.      Clicks on ‘Now Viewing’ and gets display as per screenshot

If the user then clicks on Search and back to ‘Now Viewing’, all displays as expected.

![datacataloguedisaplyissue](https://cloud.githubusercontent.com/assets/16713545/12344716/938444b2-bb94-11e5-9933-f0110cb7a43e.jpg)

**Comment by stevage** [comment]
Fyi @chloeleichen if you make the commit message "Fixes #1235" then the issue closes automatically.
