### ISSUE TITLE
Print/export button for NationalMap

### ISSUE THREAD

**Issue by aherald** [TerriaJS/terriajs#1239]
Currently to print a NationalMap, the user is required to use the browser print function, or where NationalMap is embedded in a webpage, have a button to print the iFrame.  If the user is looking to export the map to include in a report or other purpose, they have to screen capture.

It would be good to have a button within NationalMap that will print the Map and and export button to create a pdf/jpg etc of the map

**Comment by hilarycinis** [comment]
User story - a single click function (eg button) to print:
- map
- data in map
- feature info if opened
- legends

**Comment by chloeleichen** [comment]
Do we really need an extra button for this, or the browser default print button is enough, if we need a button what it looks like?

**Comment by hilarycinis** [comment]
Yep we need a clear call to action. Work with @philipgrimmett on how to resolve its placement? Also need to address what happens when the browser print action is called to ensure the content is adequately printed.
