### ISSUE TITLE
Get feature info doesn't respect current time

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1248]
Issue from @TobyBellwood:

> So creating the dataset with an ISO-8601 date YYYY-MM-DD creates the slider properly, and the csv reader interprets the min and max values for the scale correctly (ie max of all years).  The allowance of a year-only date makes sense (only where multiple years exist in the dataset – and  accepted as per https://github.com/NICTA/nationalmap/issues/192 )
> 
> What I did notice however is that the feature info box doesn’t update once the timeseries advances and updates the coloring for the polygons.  Even in 2011/2012 the infobox still displays the initial 2009 data.

![unnamed](https://cloud.githubusercontent.com/assets/678344/12543339/ba13ce9a-c382-11e5-996a-329b71630945.jpg)

**Comment by RacingTadpole** [comment]
This will require some work, as the picked feature changes each time interval. So when there's a change, we must make a new call to the Cesium object's internal `pickObject` function (or Leaflet's equivalent), using a cached position.
It needs to work for CSV (region-mapped and lat-lon) and WMS items.
It's also not obvious which object should hook up the event listener.

**Comment by RacingTadpole** [comment]
@kring suggested one solution involves making the description here https://github.com/TerriaJS/terriajs/blob/master/lib/Models/RegionMapping.js#L454 a CallbackProperty.
