### ISSUE TITLE
Get feature info doesn't show time part of date+time

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1249]
From @TobyBellwood:

> On a related issue with timesliders and infoboxes - we also discovered with another dataset (the Melbourne UV one attached) that although the data contains time information down to the minute (and displays correctly, the featureinfo box doesn’t display the time, only the day.

![unnamed](https://cloud.githubusercontent.com/assets/678344/12543388/2e7ceb0e-c383-11e5-8870-566f6581ca1f.png)

**Comment by tobybellwood** [comment]
ok - sample file at
[TerriaJS-1249.zip](https://github.com/TerriaJS/terriajs/files/104516/TerriaJS-1249.zip)
Just basic datetime + 3 vals
![pasted image at 2016_01_25 05_12 pm](https://cloud.githubusercontent.com/assets/4373945/12573979/93016228-c453-11e5-9499-4a4852462fee.png)
feature shows date only
![pasted image at 2016_01_25 05_12 pm 1](https://cloud.githubusercontent.com/assets/4373945/12573987/a771a7ae-c453-11e5-9d32-28822e74846c.png)
