### ISSUE TITLE
CZML properties show as a JSON string in feature info panel

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#1260]
- Drag `withProperties.czml` from TerriaJS's `wwwroot/test/CZML` directory onto the map.
- Click on the small polygon near Canberra.

The feature info looks like this:

![image](https://cloud.githubusercontent.com/assets/924374/12667946/cd0966a6-c6a5-11e5-8160-32aa62a6b70a.png)

The CZML has a `properties` property that looks like this:

``` json
"properties": {
    "Type": "ABC",
    "Name": "Test",
    "Support table": {
        "value": [
            {
                "Capacity": "14.4",
                "Year": 2010
            },
            {
                "Capacity": "22.8",
                "Year": 2011
            },
            {
                "Capacity": "10.7",
                "Year": 2012
            }
        ]
    }
},
```

So I would expect it to render as a nicely-formatted table.

**Comment by RacingTadpole** [comment]
In the new UI, the feature info panel for CZML is even worse. This example shows the text "undefined".

**Comment by kring** [comment]
Looks all good now:
![image](https://user-images.githubusercontent.com/924374/36364540-c766d15e-1598-11e8-82dc-30c56e5c3673.png)
