### ISSUE TITLE
Old share links overwrite catalog item name

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#1264]
- Run National Map, enable `Terrain -> Caves`, and click Share to get a share link.
- Edit the catalog init file to rename `Terrain` to `Mountains` and `Caves` to `Underground Fortresses`.
- Add a `shareKeys` property to the Caves / Underground Fortresses catalog item, i.e.:

``` json
"shareKeys": ["Root Group/National Data Sets/Terrain/Caves"],
```
- Visit the share link you generated in the first step above.

The map will look correct after visiting the share link (i.e. the Caves / Undeground Fortresses catalog item is enabled), so the backward compatibility is working.  However, notice that in the catalog, in the `Mountains` group, the catalog item is named `Caves` again instead of `Underground Fortresses` as intended.  TerriaJS has overwritten the `name` property of the catalog item with the version in the share link.

`name` should probably be treated specially (not overwritten) when matching based on share keys.

**Comment by AlexGilleran** [comment]
Sounds like there's no reason to serialize names for the purposes of sharing at all then? Should just be a matter of adding property filter to exclude it :)
