### ISSUE TITLE
Show "blank" values in CSV legends more nicely

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1265]
- Change caption to "(No value)" perhaps, instead of "blank"
- Make this value either first or last in the legend list.
- Make this value optionally hideable through `tableStyle`

**Comment by meh9** [comment]
One option if we are hiding the no value category would be to have unfilled circles or areas in that case, this way we show the location of the feature but without any colour it demonstrates it has no value.

**Comment by stevage** [comment]
Hmm, that contradicts #799 though.

**Comment by meh9** [comment]
Yeah, I was hoping that we could solve #799 in some way.
