### ISSUE TITLE
Ability to include/exclude CSV columns as data variables

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1266]
It would be useful to be able to specify a list of columns to exclude from the options presented on the Now Viewing tab when autogenerating a legend from e.g. a CSV file. As a bonus feature, it might also be useful to be able to specify the inverse where we just specify exactly which columns to include.

Most datasets will include a column with unique names or identifiers - it doesn't really add anything to be able to categorise these as each name will be its own category. There may also be other reasons why a column should be excluded.

In AREMI Current Power Generation layers we have `Station Name` and `DUID` columns which only clutters the interface, as it doesn't make sense to show those as categorised values on the map.

**Comment by stevage** [comment]
Probably would be handled by #1334.

Wait...I think what you mean is, you want to prevent certain columns being proposed as data variables? Nothing to do with legends, right?

**Comment by RacingTadpole** [comment]
I believe this is solved by #1534 - please reopen if not.
