### ISSUE TITLE
Layer hiding behaviour with region mapped data

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#1267]
There are a couple of bugs regarding layer hiding:
- [x] A layer hidden by clicking the eye can be re-shown by changing selected variables (most likely intended) but this doesn't change the eye icon
- [ ] A layer can with no variable selected still displays data (based on the last variable that was selected) but has no legend

**Comment by tephenavies** [comment]
The second problem seems to be a logic error in [`AbsIttCatalogItem.js: rebuildData`](https://github.com/TerriaJS/terriajs/blob/16caf395f0722f4729187705e653f222a09794a3/lib/Models/AbsIttCatalogItem.js#L440-L452). When there are no variables selected, `tableStructuresAndCombinations` is `undefined`. This means that `regionDetails` will also be `undefined`, so the imagery is not updated.

**Comment by tephenavies** [comment]
I think this is also related:

When I add [this file](https://github.com/TerriaJS/terriajs/files/147677/demo.txt) as a csv and deselect the `Statistic` column, the layer is redrawn with different colours.

**Comment by tephenavies** [comment]
What should the behaviour be when you try to deselect the only selected concept of a certain concept type? Should TerriaJS:
A. Disallow deselecting
B. Deselect the concept and hide the layer (meaning you would have to select a concept **and click the show button** to reshow it), or
C. Deselect it and not display the layer (probably the most obvious option UI-wise, but it would complicate the possible states that a layer could be in – i.e. shown, hidden by lack of concept selection but with attribute `isShown` still true, hidden by hide button/errors & basemap `isShown` false but not hidden)

**Comment by RacingTadpole** [comment]
Sorry - the second checkbox in your issue description might be covered by issue https://github.com/TerriaJS/terriajs/issues/791, which is solved via https://github.com/TerriaJS/terriajs/pull/1338 (an outstanding PR).

**Comment by stevage** [comment]
Or, as in that PR I think:

D. Deselect it, and now the layer displays, using a default color instead of choroplething.

**Comment by RacingTadpole** [comment]
Yep, good point - D is the current behaviour for region-mapped csvs when no column is active. Also no legend is displayed in that case. As I understand it, @steve9164 has uncovered two issues here:
- ABS items don't behave well when you have nothing selected for a particular concept type
- a region-mapped csv file with only a region column doesn't load.

I recommend we close this issue and open two separate issues for these.
