### ISSUE TITLE
Allow direct download of ABS data service data as csv

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1272]
While showing NM to some data journalism students this morning, one of them asked how she could download the data associated with a particular ABS view. It seems like a very reasonable request, but currently there's no mechanism available.

**Comment by RacingTadpole** [comment]
Yes, good idea.

**Comment by kring** [comment]
Related to NICTA/nationalmap#174?

**Comment by stevage** [comment]
Not exactly. That one is about providing direct links to existing files (with landing pages etc). The data here is provided through the ITT service, for which there may not be any other convenient interface for users.

**Comment by kring** [comment]
This was added for `SdmxJsonCatalogItem`, which is the basis for ABS data these days. See "Download the currently selected data in CSV format" at the bottom of the catalog item info/preview window.
![image](https://user-images.githubusercontent.com/924374/36364514-9239273e-1598-11e8-938c-b1435c802f9a.png)
