### ISSUE TITLE
Consider using DOMPurify instead of Caja for HTML sanitization

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#1274]
DOMPurify allows quite a lot more HTML features.
https://github.com/cure53/DOMPurify

The downside is that on IE9, it does nothing, leaving the input unsanitized.

**Comment by RacingTadpole** [comment]
I think I want to switch to DOMPurify so my new custom components survive sanitization: I can’t figure out a way to stop sanitize-caja from removing `<chart>`.

Would you be OK with the IE9 implications in production?

**Comment by kring** [comment]
I think the new UI is a good time to drop IE9 support, so yes.

**Comment by RacingTadpole** [comment]
Marvellous. This is now implemented in the `newui` branch.

**Comment by bsimyo** [comment]
Re IE9 support.... I realise that MS have stopped support and security updates for IE 8, 9 and 10 (https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support) but there will probably still be quite a few old browsers out there amongst the main TerriaJS user groups for a while (eg IE9 still is around 6% of desktop browsers according to https://www.netmarketshare.com/browser-market-share.aspx?qprid=2&qpcustomd=0 ).  We should recommend upgrade to old IE version users (given lack of MS security updates) but this will be out of control of users in some organisations and we need a reasonable fallback.  So I don't think we'll quite be dropping IE9 with the new UI but it may be OK to have reduced functionality.  Let's track the usage numbers over the next few months and see if the Jan MS announcement makes a fast impact on numbers of old IE users.

**Comment by kring** [comment]
We've switched to DOMPurify in newui, closing.
