### ISSUE TITLE
Charts with the new UI

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1278]
This is an issue to track progress towards minimal viable time-series charts (#662) in the new UI.

Tasks:
- Essential functionality
  - [x] Re-implement display variables ("concepts").
- Feature Info Panel
  - [x] Render custom components (eg. `<collapsible>`).
  - [x] Decide on `<chart>` syntax.
  - [x] Include x-column and y-column in `<chart>`.
  - [x] Style the preview charts.
  - [x] Implement expand (with optional `1d | 5d | 30d | 3m | 1y | 5y`).
  - [x] Expanding twice overwrites the original.
  - [x] Implement download (with same expand options).
  - [x] Add x-axis label, eg. "24 hours".
  - [x] Accept raw csv or json data in `<chart>` tag.
  - [x] Still look good even if the chart data is missing.
  - [x] No legend required.
  - [x] Allow download to have different options to expand.
- Charting basics
  - [x] Implement a basic D3 line chart in React.
- The Chart Panel
  - [x] Style and show a basic chart panel.
  - [x] Hover or click shows legend, circles on lines, and vertical line.
  - [x] If data have different units, show them with different y-axes on the left, and colours above. (Treat no units as different to any known units.) 
  - [x] Show data with the same units, but different scales, on the same chart.
  - [x] If new data has different x type (eg. number vs time), start chart panel afresh.
  - [x] Legend across the top (with an open question about how to handle if it's too long).
  - [x] A "tooltip" legend on the right is presented on hover/click/touch.
  - [x] Implement download.
  - [x] Improve location of x-axis when there are small negative y-values.
  - [x] Add x-axis label.
  - [x] Window resize needs to resize panel.
  - [x] Accept units in `<chart>`.
  - [x] Make the chart panel closable. Should unselect all the selected chart items.
  - [x] Grid lines.
  - [x] Intelligently choose labels to bring out the differences (eg. do not show the catalog item name if common to all lines, and similarly the column name).
  - [x] Improve speed of large data files (eg. 3 months of 5-min data was taking ~1 minute to load and combine with other chart data - now down to ~15 seconds).
- Interaction with the catalog
  - [x] From eg. power station data, add a link back to the CatalogItem where it came from.
  - [x] Color the checkbox with the line color.
  - [x] Option to override the raw column names using `<chart column-names='...'>`.
  - [x] Add an icon to identify the chart-based catalog items (eg. see screenshot below).
- Miscellaneous
  - [x] Properly remove chartable items.
  - [x] Sharing (currently a circularity error).
  - [x] Drag and drop non-spatial `csv` files.
- Issues
  - [x] Improve download button appearance.
  - [x] Improve downloaded time formatting (eg. use ISO8601 - requires overriding `formattedValues`).
  - [x] Stop dropdown items wrapping.
  - [x] Fix unnecessary chart refresh on expand.
  - [x] Show true min/max on feature info panel charts, not two arbitrary y-values.
- New issues
  - [x] Expand chart flickers and fails the first time.
  - [x] Animation has gone?
  - [x] Going between two star stations with no other difference, the feature info chart does not update, and therefore the wrong data is downloaded too.

And for the future:
- Sharing should also share the sourceCatalogItem.
- Error bars.
- Range selector (brush, cf #1425).
- Interaction with the map, eg.
  - If lines came from different features, when chart is clicked, color those features with the line color.
  - Decide how interaction with the timeline should work.
- Other sorts of charts (bar charts, pie charts, scatter plots etc).
- Showing all features at once.
- Other sorts of data (wind speeds, atmospheric balloons, histograms of count data).
- Auto-updating charts, eg. add `poll-seconds="60"` and `poll-url="http://example.com/api?latest"` to the `<chart>` tag, which would hit that URL every 60s and merge whatever is there with the existing data.
- Other formats (json, zip, thredds xml).
- A "Now Viewing" dropdown to see the chart legend directly.
- Do we need a [time-data-api](https://github.com/NICTA/nationalmap/wiki/time-data-api)?
- Extend charts to show time-varying raster or csv data at a location (cf. #1424)

**Comment by RacingTadpole** [comment]
Sample Feature Info Panel chart (from @philipgrimmett):
![image](https://cloud.githubusercontent.com/assets/1757858/12878599/a760d7b2-ce7b-11e5-81e9-d417f7f78396.png)

**Comment by RacingTadpole** [comment]
Some open questions:
- What should the chart panel’s legend look like, and where should it go?
- What should it look like when you hover over a chart datapoint in either the feature info panel or the chart panel? Some possibilities: a floating window something like http://c3js.org/samples/simple_multiple.html; or update a dedicated space in the chart panel. Should it show the values of each chart line at that vertical position?
- What should the title of the chart panel be?
- What to do when the user selects incompatible data to chart. Specifically, if the user has a few lines on their chart, and then tries to add:
  - data with a different sort of x-axis (eg. numbers vs time).
  - data over a completely different time interval.
  - data at a very different scale (eg. its max is 1% or 100x the current max).
  - perhaps: data with different units (e.g. all current plots are in megawatts and we try to add one in metres, or kilowatts. This could be very fragile though (eg. are “meters” and “metres” the same?), and often we won’t know the units anyway.
    For these cases, we could either:
- Clear the chart panel and only show the new line. To get back to the previous chart would require manually clicking those data items back on again.
- Have multiple chart panels, perhaps a bit like we have multiple features in the feature info panel now (eg. with a collapsible heading for each one).

**Comment by RacingTadpole** [comment]
Thanks @philipgrimmett: 
![image](https://cloud.githubusercontent.com/assets/1757858/13479014/3216833e-e128-11e5-840c-28d1a7f7f343.png)

**Comment by chloeleichen** [comment]
is the x-axis always time?

**Comment by RacingTadpole** [comment]
No.

**Comment by RacingTadpole** [comment]
Here's a suggestion to add an icon to the chart-based catalog items. ![image](https://cloud.githubusercontent.com/assets/1757858/13941768/2b0cf8f4-f03f-11e5-9d10-1c7a1a70a908.png)

**Comment by kring** [comment]
All the boxes are checked!  Time to close this?

**Comment by RacingTadpole** [comment]
Yay! I'll open a new issue with the future plans.
