### ISSUE TITLE
Can't add two files with the same name

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1284]
Manually loading two files with the same name causes `indexWithDescendents` in `CatalogGroup` to throw a RuntimeError `Duplicate sharekey`.

This is problematic because:
1. You can't even load the data, regardless of whether you want to share it.
2. If loading a file fails, but then you fix the file (and even if you "Remove all"), the error still gets thrown.
3. If you change a file, remove it, then re-add it, the error still gets thrown.

Part 2 and 3 may indicate a separate bug.

**Comment by RacingTadpole** [comment]
It also happens if you drag a `csv` file onto the map more than once.

**Comment by AlexGilleran** [comment]
Ideally it should be picking up that what you're dragging matches an existing shareKey and using that knowledge to update the existing one :/

**Comment by jeanpul** [comment]
Hello

It also happens with some WMS server (https://download.data.grandlyon.com/wms/grandlyon) where some layers have the same <Title> (but not the same <Name>). If I set "titleField" to "name" in the Catalog declaration then it's working but I don't want to change the catalog entries title. 

Regards

**Comment by stevage** [comment]
> Ideally it should be picking up that what you're dragging matches an existing shareKey and using that knowledge to update the existing one :/

Not necessarily. When I do this, I often want to compare the old version to the new version.

**Comment by AlexGilleran** [comment]
Kevin's idea of a best-effort solution where when a clash occurs the second layer is just appended with 2 (or 3 etc) seems best then.
