### ISSUE TITLE
Terria Server URLs Default to Absolute Paths

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/terriajs#1286]
E.g. `/proxy/` vs `proxy/`. Would be better to use `proxy/` in most cases.

**Comment by stevage** [comment]
You're referring to [this](https://github.com/terriajs/terriajs/blob/11c146768ce275afd373a15f0539d8a046bfec0f/lib/Models/Terria.js#L39)? Can you elaborate on why it would be better to change it?

I seem to recall having to change this for instances on natmap.research but that's a weird case I guess.

**Comment by kring** [comment]
Yeah research is weird because of the symlinks.  In pretty much all other cases, the proxy will be found in the same place as index.html because that's where `terriajs-server` puts it.

**Comment by AlexGilleran** [comment]
Yeah, what @kring said, in particular AREMI which runs from `/renewables/`
