### ISSUE TITLE
Some ABS items are measured in households and do not make sense as percent of region population

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1295]
Some ABS items are measured in households and do not make sense as a percent of region population, eg.
- "Type of internet connection" is measured in number of dwellings.
- "Rent (weekly)" - I haven't checked its units, but I wouldn't be surprised if they were households rather than people (if we select all types of rent, across Australia, the total is 2.3 million).

We should either remove the "display as percent of region population" option for these, or think about a way to divide by a more meaningful quantity (eg. percent of region households).

**Comment by stevage** [comment]
Nice catch. 

Looks like we could use the results of `GetCodeListValue&...concept=MEASURE` to distinguish the cases. If it doesn't contain "persons", we shouldn't show the per capita option.

(There's a lot of code I'm not familiar with here, not sure exactly where we ought to make that check.)

> I haven't checked its units, but I wouldn't be surprised if they were households rather than people (if we select all types of rent, across Australia, the total is 2.3 million).

Yeah, I wonder how you can find out definitively? I can see by going through ABS "[QuickStat](http://www.censusdata.abs.gov.au/census_services/getproduct/census/2011/quickstat/0?opendocument&navpos=220)" that the units must be "rented dwellings" (which also sum to 2297458), but there must be a direct way to access units.

Related issue: IMHO the checkbox and label "Display as percent of region population" could be improved. Maybe a two way option:

[x] Total value
[ ] Percentage of population

**Comment by stevage** [comment]
I think the main sources of confusion were:
- sometimes it doesn't make sense (single bedroom houses per population, median/mean figures)
- sometimes it doesn't make sense to not have it (ie, raw figures that are meaningless to compare directly)
- sometimes a different divisor would be better
- if the population is smaller than the numerator (for very small populations)
- legends that incorporated non-spatial regions (eg, no fixed address), leading to the previous problem, hence "150%" at the top of the legend

**Comment by RacingTadpole** [comment]
Solved with the new SDMX-JSON interface.
