### ISSUE TITLE
TerriaJS/National Map container on docker hub

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#1301]
There are Docker deployment instructions here
https://github.com/NICTA/nationalmap/wiki/Developers'-Handbook#docker

Are there also plans for a container on docker hub?
https://hub.docker.com/

**Comment by rsignell-usgs** [comment]
There is a terriajs container here https://hub.docker.com/r/sameli/terriajs/ but it doesn't look too up to date.

**Comment by kring** [comment]
Closing this in favor of #2803.
