### ISSUE TITLE
Large performance regression with SA1 region mapped csv since csv_refactor

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#1313]
There is a very large performance difference between changing variables for a large region mapped csv on [staging](http://staging.nationalmap.nicta.com/) (running `2016-02-15 terriajs: 2.0.1`) and [nationalmap live](http://nationalmap.gov.au/) (running `2016-01-19 terriajs: 1.0.54`).

Testing with [terriajs/wwwroot/test/csv/55k-SA1s.csv](https://github.com/TerriaJS/terriajs/blob/master/wwwroot/test/csv/55k-SA1s.csv), switching variables takes under a second to start reloading tiles and redrawing on nationalmap but over a minute on staging (and in master) – actually it took about 6 minutes to change variables.

I tried to run a `git bisect` to find the change, but wasn't able to, however I think the issue could be somewhere in csv_refactor.

**Comment by tephenavies** [comment]
It seems like every second variable change takes a very long time, but the other variable changes are relatively fast (still a little slower than live nationalmap).

**Comment by RacingTadpole** [comment]
Yes, it's also a lot slower dropping on a csv file with only the first 1000 lines of the csv file you mention (2s on the live site, and 8s on master).

**Comment by RacingTadpole** [comment]
I also tried a 1000 line csv file with Lat and Lon columns instead of regional columns. It was about 3s on the live site, and 4.5s on master.

**Comment by tephenavies** [comment]
Looks like the colour-binning function is the problem. Some of the variables use quantile, which is fast (according to comments in `LegendHelper.js:300`), but ckmeans is really slow for the 55k csv. I'm not sure if/how this can be fixed.

<img width="1241" alt="screen shot 2016-02-29 at 1 03 56 pm" src="https://cloud.githubusercontent.com/assets/13863530/13383996/0b4a8fc4-dee5-11e5-86e3-0771f5df2033.png">

**Comment by RacingTadpole** [comment]
Thanks Steve! That's interesting. Would you be up for repeating your test with the version immediately before the csv refactor (tag 1.0.54), where there is still a call to `ckmeans` https://github.com/TerriaJS/terriajs/blob/1.0.54/lib/Map/TableDataSource.js#L696 ? I'm curious if you can still see the slowdown there, and if not, what's different...

**Comment by tephenavies** [comment]
The difference is that terriajs-2.0.0 version is using `ckmeans`, but 1.0.54 is using `quantile`. This is because the new version uses a different condition:

``` javascript
// From LegendHelper.js:264
if (tableStyle.colorBinMethod === 'quantile' ||
        tableStyle.colorBinMethod === 'auto' && numericalValues.length > 1000 && (defined(tableColumn) && !tableColumn.usesIndicesIntoUniqueValues)) {
```

compared to the old condition:

``` javascript
// From TableDataSource.js:686
if (this.colorBinMethod === 'quantile' || this.colorBinMethod === 'auto' &&  vals.length > 1000) {
```

For most of the variables in the `55k-SA1s.csv`,`colorBinMethod` is `'auto'` and `tableColumn` is undefined, so `ckmeans` ends up being used (where `quantile` would have been used before).

**Comment by RacingTadpole** [comment]
That's fantastic sleuthing - thanks. I suspect it runs through here once with `tableColumn` undefined, then once csvCatalogItem decides which column to activate, it runs through again. So a good solution might be to stop that double up. I'll look into it now.

**Comment by RacingTadpole** [comment]
A second significant impact is coming from `formattedValues` in `TableColumn`, https://github.com/TerriaJS/terriajs/blob/master/lib/Map/TableColumn.js#L160 . When I replace this line with `this._formattedValues = this._values;`, the time taken by `TableStructure` to load the columns of 55k-SA1s drops from 36s to 7s on my machine.

**Comment by tephenavies** [comment]
I was going to ask you about the performance of formatting values as soon as you add a dataset. It's good that you found the same thing.

**Comment by stevage** [comment]
@steve9164 do you by chance still have an old version running? I don't seem to be able to get one going. I had thought the full 55k file loaded in something like 4-5 seconds, but maybe I'm misremembering. Would be nice to compare against the 1313_csvperf branch.

**Comment by tephenavies** [comment]
@stevage Just tested it with a new national map clone:

``` bash
git clone git@github.com:NICTA/nationalmap natmaptest
cd natmaptest
git checkout 2016-01-19
npm install
gulp
npm start
```

I did the following tests on TerriaJS 1.0.54, current master and 1313_csvperf:
1. Load time: dragged 55k-SA1s.csv onto the map and time until it popped into Now Viewing
2. Variable change: Once it had loaded and fully drawn, I switched from drawing SA1 code to `FirstLetter`

Results:

|  | 1.0.54 | Current | 1313_csvperf |
| --- | --- | --- | --- |
| Load time | 5 secs | 45 secs | 15 secs |
| Variable change | <1 sec | >3 mins | >70 secs |

**Comment by tephenavies** [comment]
Some differences that I've spotted between TerriaJS 1.0.54 & 1313_csvperf:
- 1313_csvperf uses ckmeans more (1.0.54 uses ckmeans only for GCCSA_CODE_2011)
- Even though 1.0.54 uses ckmeans for GCCSA_CODE_2011, it sends an array with 33 entries, where 1313_csvperf sends the full 54,805 (then again, the whole region mapping is one colour, so this could be a bug in 1.0.54)

**Comment by RacingTadpole** [comment]
Thanks @steve9164 - looks like there's still some way to go here!
Btw, in your test above, I notice that `FirstLetter` is by far the worst case, eg. if you change between the first two variables in the list, it only takes a few seconds to change variable in 1313_csvperf (not >70s as for `FirstLetter`). Still not as fast as <1s, but much better than 3 mins.
I think `FirstLetter` is so slow because it's calling `ckmeans` with 55,000 values.

**Comment by RacingTadpole** [comment]
The `FirstLetter` issue is that 
https://github.com/TerriaJS/terriajs/blob/1313_csvperf/lib/Models/LegendHelper.js#L302
specifically prevents ENUM columns from using the fast `quantile` method, since it would be meaningless; so instead it uses `ckmeans`, even if there are 1000s of rows - which is slow.

If the number of unique ENUM values is less than `binCount`, this gives you back the ENUM values, which is fine.

But for lots of ENUM values, I'm actually not sure how to interpret `ckmeans`'s legend and colouring. Eg. in the below, some regions have the first letter "W", which is not on the legend, and which are coloured the same as "Q":
![image](https://cloud.githubusercontent.com/assets/1757858/13512711/752f2662-e1f0-11e5-9c6f-0b23787458be.png)

So I am going to open a new issue describing this problem. Solving it should solve the `FirstLetter` part of the performance issue.

**Comment by RacingTadpole** [comment]
I think I've got to two root causes of the loading slow down now, and solved them both (now pushed to `1313_csvperf`). The new branch loads about as fast as 1.0.54 did, I think. (Phew!)
- the caching in `formatNumberForLocale` helps a ton, but even so, using `Intl.NumberFormat` is inherently slower than doing it yourself. So now I just use `Intl` once initially to get the thousand-separator.
- We don't need to calculate all the unique values of ENUM columns until we need them.

I thought about postponing the value formatting until we need it too, but actually we need it all straight away to set up all the feature infos (https://github.com/TerriaJS/terriajs/blob/1313_csvperf/lib/Models/RegionMapping.js#L454).

**Comment by tephenavies** [comment]
There's still some weird things going on. In a freshly pulled `1313_csvperf`, selecting Age from ABS, if you change region map types, `ckmeans` is run on both the old region map type and the new. 

For example changing from SA3 to Australia:
1. `ckmeans` is called with parameters `data = Array[351], nClusters = 9` but the array `data` is actually just [0, 1, 2, 3, ..., 350]
2. `ckmeans` is called again with parameters `data = [25.8], nClusters = 1`
3. New legend is drawn and debug message `Found region match based on aus` printed from console
4. `ckmeans` is called again with the same parameters as 2
5. New coloured region mapped layer drawn

Steps 1 & 2 should not be run.

**Comment by RacingTadpole** [comment]
Here's why that's happening:
- The legend is recalculated whenever the active items change.
- When you click an item, it first inactivates the old one (which counts as one change), then activates the new one (which counts as a second change).

Telling knockout not to trigger off the first change could be quite messy. The alternative is to make it really fast to update when no columns are active - then it won't matter.

We will show region-mapped csvs with no active tableColumn all in the same color when we solve #1356. That will stop the first change calling `ckmeans`, and make it fast, and so resolve the issue you've identified.

**Comment by kring** [comment]
FWIW, you can use rate-limited observables to avoid triggering expensive updates too early:
http://knockoutjs.com/documentation/rateLimit-observable.html

**Comment by tephenavies** [comment]
@RacingTadpole I think the issue you're looking for is #1356.
