### ISSUE TITLE
"TypeError: Cannot set property clock of [object Object] which has only a getter" (share URL for multi-date CSV)

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1321]
[This link](http://localhost:3001/#start=%7B%22version%22%3A%220.0.05%22%2C%22initSources%22%3A%5B%22init%2Fnm.json%22%2C%7B%22catalog%22%3A%5B%7B%22name%22%3A%22User-Added%20Data%22%2C%22description%22%3A%22The%20group%20for%20data%20that%20was%20added%20by%20the%20user%20via%20the%20Add%20Data%20panel.%22%2C%22info%22%3A%5B%5D%2C%22isUserSupplied%22%3Atrue%2C%22isPromoted%22%3Afalse%2C%22isHidden%22%3Afalse%2C%22forceProxy%22%3Afalse%2C%22customProperties%22%3A%7B%7D%2C%22id%22%3A%22Root%20Group%2FUser-Added%20Data%22%2C%22isOpen%22%3Atrue%2C%22items%22%3A%5B%7B%22name%22%3A%22SA3-Region-Innovation-Data-2009-14.csv%22%2C%22description%22%3A%22%22%2C%22info%22%3A%5B%5D%2C%22isUserSupplied%22%3Atrue%2C%22isPromoted%22%3Afalse%2C%22isHidden%22%3Afalse%2C%22forceProxy%22%3Afalse%2C%22customProperties%22%3A%7B%7D%2C%22id%22%3A%22Root%20Group%2FUser-Added%20Data%2FSA3-Region-Innovation-Data-2009-14.csv%20%281%29%22%2C%22nowViewingIndex%22%3A0%2C%22url%22%3A%22https%3A%2F%2Frawgit.com%2Fstevage%2F09b732ac17e23543a6a1%2Fraw%2F3fc6d6a18b4fd9b8f08a6ef799f75225e2e6a04b%2FSA3-Region-Innovation-Data-2009-14.csv%22%2C%22isEnabled%22%3Atrue%2C%22isShown%22%3Atrue%2C%22isLegendVisible%22%3Atrue%2C%22isLoading%22%3Afalse%2C%22isEnableable%22%3Atrue%2C%22isMappable%22%3Atrue%2C%22showsInfo%22%3Atrue%2C%22maximumShownFeatureInfos%22%3A100%2C%22opacity%22%3A0.6%2C%22keepOnTop%22%3Afalse%2C%22showWarnings%22%3Atrue%2C%22disableUserChanges%22%3Afalse%2C%22tableStyle%22%3A%7B%22scale%22%3A1%2C%22colorBins%22%3A7%2C%22colorBinMethod%22%3A%22auto%22%2C%22legendTicks%22%3A3%2C%22dataVariable%22%3A%22Trademarks%20%28total%29%22%7D%2C%22clock%22%3A%7B%22_startTime%22%3A%7B%22dayNumber%22%3A2454832%2C%22secondsOfDay%22%3A3633%7D%2C%22_stopTime%22%3A%7B%22dayNumber%22%3A2457023%2C%22secondsOfDay%22%3A20915.39999999851%7D%2C%22_currentTime%22%3A%7B%22dayNumber%22%3A2454832%2C%22secondsOfDay%22%3A3633%7D%2C%22_clockRange%22%3A2%2C%22_clockStep%22%3A1%2C%22_multiplier%22%3A1577664%2C%22_definitionChanged%22%3A%7B%22_listeners%22%3A%5B%5D%2C%22_scopes%22%3A%5B%5D%2C%22_toRemove%22%3A%5B%5D%2C%22_insideRaiseEvent%22%3Afalse%7D%7D%2C%22type%22%3A%22csv%22%2C%22parents%22%3A%5B%22Root%20Group%22%2C%22Root%20Group%2FUser-Added%20Data%22%5D%7D%5D%2C%22preserveOrder%22%3Afalse%2C%22type%22%3A%22group%22%2C%22parents%22%3A%5B%22Root%20Group%22%5D%7D%5D%7D%2C%7B%22sharedCatalogMembers%22%3A%7B%22Root%20Group%2FUser-Added%20Data%2FSA3-Region-Innovation-Data-2009-14.csv%20%281%29%22%3A%7B%22nowViewingIndex%22%3A0%2C%22isEnabled%22%3Atrue%2C%22isShown%22%3Atrue%2C%22isLegendVisible%22%3Atrue%2C%22opacity%22%3A0.6%2C%22keepOnTop%22%3Afalse%2C%22disableUserChanges%22%3Afalse%2C%22tableStyle%22%3A%7B%22scale%22%3A1%2C%22colorBins%22%3A7%2C%22colorBinMethod%22%3A%22auto%22%2C%22legendTicks%22%3A3%2C%22dataVariable%22%3A%22Trademarks%20%28total%29%22%7D%2C%22type%22%3A%22csv%22%2C%22id%22%3A%22Root%20Group%2FUser-Added%20Data%2FSA3-Region-Innovation-Data-2009-14.csv%20%281%29%22%2C%22parents%22%3A%5B%22Root%20Group%22%2C%22Root%20Group%2FUser-Added%20Data%22%5D%7D%7D%7D%2C%7B%22initialCamera%22%3A%7B%22west%22%3A122.87109375%2C%22south%22%3A-45.12005284153052%2C%22east%22%3A166.55273437499997%2C%22north%22%3A-15.24178985596171%7D%2C%22homeCamera%22%3A%7B%22west%22%3A109%2C%22south%22%3A-45%2C%22east%22%3A158%2C%22north%22%3A-8%7D%2C%22baseMapName%22%3A%22Positron%20%28Light%29%22%2C%22viewerMode%22%3A%222d%22%7D%5D%7D&activeTabId=NowViewing) reproduces the error message on your local machine.

**Comment by RacingTadpole** [comment]
I'm going to tack on a second issue to this one: sharing does not maintain currentTime.

**Comment by RacingTadpole** [comment]
OK, the issue seems to arise here: https://github.com/TerriaJS/terriajs/blob/master/lib/ViewModels/SharePopupViewModel.js#L97-L108

User-added catalog items don't use the standard `propertyFilters`, ie. https://github.com/TerriaJS/terriajs/blob/master/lib/Models/CatalogMember.js#L418-L425

As a result, it serializes everything, including `clock`, not just the properties in `propertiesForSharing`. 

Any ideas why we do this? (@kring or @AlexGilleran?)

**Comment by kring** [comment]
For user-added catalog items, we need to serialize the complete definition, not just the stuff that's changeable in the UI.  You can use the `defaultSerializers` stuff to prevent properties from being serialized when you know they shouldn't be.

**Comment by AlexGilleran** [comment]
I believe the idea is that if you import data from JSON, you might want to specify non-shareable properties in that JSON (like a custom template or something? AREMI uses tonnes of them). Shareable properties are what the user can actually change _after_ the import.

There's really not much of a reason to ever persist the clock though :/

**Comment by AlexGilleran** [comment]
Ahh beaten :(

I suspect what's brought this out of the woodwork is that a `DataSourceClock` is actually pretty simple and serializable, so setting it from JSON shouldn't be a problem, and it's actually legal to do so in `ImageryLayerCatalogItem` because `clock` has a setter, but not so in `CsvCatalogItem` (anymore?).

Anyway not serializing the clock seems like a reasonable way forward.

**Comment by RacingTadpole** [comment]
perfect, thanks.
