### ISSUE TITLE
UI forces map image on share panel to be square no matter the actual aspect ratio

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#1327]
To reproduce:
- Switch map view to 2D
- Collapse data panel
- Zoom in a few levels
- Click Share button to view cropped preview

![download](https://cloud.githubusercontent.com/assets/5292858/13272410/ec93cf9e-daef-11e5-9703-62db42f83c61.jpeg)

**Comment by kring** [comment]
The image itself isn't truncated.  If you click on it or right-click-and-save, you'll see the non-truncated version.  But the UI is forcing the image to fit in a neat little square, and truncating the sides to make it fit.

On share panel:
![image](https://user-images.githubusercontent.com/924374/36363992-5dec033c-1595-11e8-9bdc-0586f0f2c43b.png)

Full image:
![image](https://user-images.githubusercontent.com/924374/36363996-67988f40-1595-11e8-95c2-efa4c0402970.png)
