### ISSUE TITLE
Timeline does not appear on a shared CZML file

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1329]
Try opening http://localhost:3001/#build/terriajs/test/init/czml.json, clicking on the time-varying description item, and sharing it.  When you open the share URL, you'll see there is no timeline.

The share URL contains this json describing czml.json:

```
{"sharedCatalogMembers": {
    "Root Group/Test Advanced CZML/CZML with time-varying description": {
        "nowViewingIndex": 0,
        "isEnabled": true,
        "isShown": true,
        "isLegendVisible": true,
        "type": "czml",
        "id": "Root Group/Test Advanced CZML/CZML with time-varying description",
        "parents": ["Root Group", "Root Group/Test Advanced CZML"]
    }
}
```

Note no clock.

This is the flipside of https://github.com/TerriaJS/terriajs/issues/1321

**Comment by kring** [comment]
Not sure why `clock` would need to be included in the URL.  The clock property should get populated when the CZML is loaded.

**Comment by RacingTadpole** [comment]
My original thought was, the timeline isn't showing because there's no clock. But you're right, it's for a completely different reason.

As a related issue, I think share should also share `clock.currentTime`, which it doesn't now.

**Comment by kring** [comment]
Yeah, but that's `terria.clock.currentTime`, not `catalogItem.clock.currentTime`.

**Comment by kring** [comment]
(Confusingly, `terria.clock` is a `Clock`, `catalogItem.clock` is a `DataSourceClock`)

**Comment by RacingTadpole** [comment]
Ah yes, I have hit that naming issue before, but I'd forgotten - thanks.
