### ISSUE TITLE
Allow configurable legend options in catalog files

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1334]
[Sometimes](https://github.com/NICTA/nationalmap/pull/214/files#r53892783) it'd be nice to override properties of a legend from a catalog file. Maybe something like:

```
{
              "url": "http://services.ga.gov.au/gis/rest/services/NEXIS_Residential_Population_Density/MapServer",
              "type": "esri-mapServer",
              "legendOptions": {
                "title":"People per cell"
              }
}
```

The options would just be passed directly through to the `Legend` object, no need to invent anything new here.

**Comment by RacingTadpole** [comment]
I think this is fixed by the "name" option in "tableStyle.columns", from #1302.
