### ISSUE TITLE
Is running with nohup useful?

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#1336]
I've been running my terriajs instance by doing:

```
nohup npm start &
```

but I notice that the wiki instructions say 

```
npm start &
```

Is the `nohup` actually not doing anything useful here?

**Comment by stevage** [comment]
[nohup](https://en.wikipedia.org/wiki/Nohup) keeps it running it the background even if you close the terminal, disconnect from the server or whatever.

**Comment by rsignell-usgs** [comment]
And that's a good thing for running in production, right?

**Comment by stevage** [comment]
Well, yes. But also in development, depending on your personal setup and preferences.

**Comment by rsignell-usgs** [comment]
Okay, thanks.   Okay to close this issue, but possibly consider adding the `nohup` suggestion to:
https://github.com/TerriaJS/terriajs/wiki/Deploying-and-building-TerriaJS   ?
