### ISSUE TITLE
Updating to cesium 1.18

### ISSUE THREAD

**Issue by keattang** [TerriaJS/terriajs#1339]
Hey @kring, 

We're pretty keen over here to take advantage of some of the performance improvements that have been added to the latest versions of cesium. What can we do to help get the ball rolling on this? If its a fairly simple task I'm happy to do the relevant merging and testing.

**Comment by kring** [comment]
Sorry for the delay on this, I'll try to get to it this afternoon!

**Comment by keattang** [comment]
Awesome thanks!

**Comment by RacingTadpole** [comment]
Fixed by #1340 .
