### ISSUE TITLE
Implement alternative link sharing mechanism

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1342]
I have a share URL that is 5189 characters long which is causing the URL shortener to fail. I also have a goo.gl URL shortening extension in my browser, and it fails on the URL as well, which leads me to think that the goo.gl service has a maximum limit lower than that.

Something to note is that now that we have the stable ids for sharing, this means that we include all the parents in the share URL. These list of all the parents take up a fair amount of data, in my case I shared all the NA Land Tenure layers, and every single one of the 9 layers has this identical block:

```
                    "parents": [
                        "Root Group",
                        "Root Group/Boundaries",
                        "Root Group/Boundaries/Cadastre and Land Tenure",
                        "Root Group/Boundaries/Cadastre and Land Tenure/Northern Australia"
                    ],
```

Maybe we should re-evalutate having all the parents listed in the share URL?

**Comment by stevage** [comment]
An alternative solution is to use a different mechanism for generating share URLs. Currently we generate a short URL that resolves to a long URL, so we're limited by the longest URL that browsers will accept. A different solution is to store the view metadata somewhere else (eg, Gist), so it never becomes a URL at all.

**Comment by meh9** [comment]
I should add that copying and pasting the URL appears to work fine, so I don't think that this is a limitation in the browser - at least with regards to Google Chrome. 

I'm not against using Gist, but is that in the spirit of the service to use it as our WORM storage?

**Comment by kring** [comment]
I believe when we first implemented the shorting, we weren't able to find a hard limit on URL length with the Google URL shortener (tens of thousands of characters seemed to be fine).  I guess they've added a limit since... :disappointed:

**Comment by kring** [comment]
It's also worth noting that when using our shortening mechanism, the browser never actually sees a long URL, so browser URL length limits don't matter.  It's only the length limit of the shortener that causes us problems.

**Comment by stevage** [comment]
OIC, thanks.

**Comment by RacingTadpole** [comment]
FYI, I know someone trying to use NationalMap who is frequently running into this problem - from an email:

> is there any news on the ‘page can’t be found’ message from ‘shared NM’s’? I have to start from scratch each time I try to demonstrate or review.

**Comment by stevage** [comment]
So let's do this. My rant from Slack:

> I really feel like the whole "url shortener" thing is just the wrong approach. We don't actually want to "shorten a url". We want to save a whole bunch of state somewhere, and be able to refer to that by an unguessable unique ID. any hack that allows us to squeeze a bit more into that short URL is just going to be temporary, and constantly constrains how much state we can store. and there's absolutely no reason for it. we're literally not using the URL shortener service as a URL shortener anyway - we're never exposing `goo.gl` URLs to anyone. that is, we're treating the Google URL shortener service like a crippled version of Gist. why not just use Gist?

**Comment by tobybellwood** [comment]
I remember bringing this up very early on (whilst concerned that Google was storing the views it was shortening - we got over that IIRC) - but essentially all that is needed is a JSON-type store accessed via a unique hashed key or similar?

**Comment by stevage** [comment]
Yes. It doesn't even need to be JSON-specific, although possibly there's some benefit in such a thing (like IBM CloudAnt).

It would sort of be nice if we had some control over the stored data (ie, if we could retrospectively update the data while retaining the keys), although that has some privacy implications (because now we can see people's data - although in most cases that data has very little sensitivity).

**Comment by AlexGilleran** [comment]
If we went a more complicated route than gists this could also maybe enable exciting things like retaining uploaded CSVs for share links (with the user's consent of course).

**Comment by stevage** [comment]
Actually Gist would work pretty well for that. You can store multiple text files in a single Gist.

**Comment by AlexGilleran** [comment]
Oh cool

**Comment by stevage** [comment]
Ok, now that we have the backend for this (https://github.com/TerriaJS/terriajs-server/blob/master/lib/share.js) we should implement the front end.

In short:
- `#share=X` parameters should be sent to `/share/X` for resolution (instead of directly to Google Url shortener)
- New requests for short URLs should be POSTed to `/share`, and the ID transformed by the client.

**Comment by rsignell-usgs** [comment]
I'm not sure where best to point this out, but tinyurl.com seems to accept the very long URLS that both goo.gl and bit.ly reject, like this 4119 character one:  http://tinyurl.com/h9maegv
