### ISSUE TITLE
TerriaJS uses ArcGIS pre-cached map tiles even when explicit layers are specified

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#1345]
TerriaJS can access both the pre-cached map tiles of an ArcGIS MapServer (of which there is only one set per server), or it can access dynamic layers of the MapServer (of which there can be many).  However, whenever the server offers pre-cached tiles, we _always_ use them, even if asked to display specific layers which are different from the pre-cached ones.  This is a bug.  When a list of layers is specified, we should access those layers dynamically instead of using the pre-cached tiles.

**Comment by stevage** [comment]
Do you have any example URLs?

**Comment by kring** [comment]
This server can be used to reproduce the problem:
http://services.ga.gov.au/gis/rest/services/Northern_Australia_Land_Tenure/MapServer/

**Comment by stevage** [comment]
Oh thank god I'm off the hook.
