### ISSUE TITLE
WMS item fetches two legends, uses one

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1347]
When a WMS item refers to a GeoServer whose GetCapabilities contains a `Style.LegendURL` section, then it fetches both the legend specified there, plus its default `.legendUrl`. The first one wins.

I don't know exactly why this happens or how to stop it but I think:
- When the item gets instantiated, `NowViewingSectionViewModel` goes to construct a legend for it, and fetches the default URL.
- After the `GetCapabilities` arrives, the linked URL gets set as the `._legendUrl`, which triggers the regeneration of the `LegendViewSectionModel`.

No great drama, of course.

**Comment by kring** [comment]
I can't reproduce this anymore. We made significant changes to how WMS legends are built awhile ago, so there's a good chance it was fixed then.
