### ISSUE TITLE
csv file with one data line gives error

### ISSUE THREAD

**Issue by bsimyo** [TerriaJS/terriajs#1348]
Eg drag on csv file with 
Organisation, Lat, Lon
Test, -33.5055944, 151.3006284

Gives error:
"Data could not be added
The specified data could not be added because it is invalid or does not have the expected format."

**Comment by bsimyo** [comment]
Actually turns out it's also a problem if it's not lat/lon but a region code - eg this gives the same result:
Organisation, Poa_code
Test, 2000

(whereas adding another line: 
Test2, 2010
works fine)

**Comment by bsimyo** [comment]
so just renamed the issue to remove the "lat/lon"

**Comment by tephenavies** [comment]
The problem is in `ColorMap.js`:

``` javascript
// From ColorMap.js:57
        return {color: el, offset: index/(simpleArray.length - 1)};
```

This ends up dividing by zero and returning a `NaN` value.

No legend is displayed (even if the above problem is fixed), but this is by design:

``` javascript
// From LegendHelper.js:354
// No legend if fixed color for all points, or if no active tableColumn
    if (!defined(tableColumn) || (colorMap.length === 1)) {
        return undefined;
    }
```

**Comment by RacingTadpole** [comment]
FYI, this error occurs only when the active column is a string field, not a scalar; eg. this file works fine:

```
Value, Lat, Lon
10, -33.5055944, 151.3006284
```
