### ISSUE TITLE
Generate legend for GeoJSON files without styling

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1353]
Raised at #910 and #791.

There are a couple of difficulties here:
- first, if there is styling built into the GeoJSON, it could be pretty fiddly working out how to represent it in a legend. Eg, do we collect every single different style and draw a box for each?
- secondly, if we solve the first bit, how would we label each box? We don't know what the colours mean, if they have some deeper semantic significance (eg, all anchor symbols represent ports).

But in the basic case (unstyled points), it would be good to show at least label the dataset: green circles = myfile.geojson.

**Comment by kring** [comment]
It's a shame that simplestyles doesn't make any allowance for legends. Given that, a generated legend for a fully-styled GeoJSON is not realistic, but Steve's final suggestion of showing a simple legend in the default case (no styling) is pretty easy.

**Comment by kring** [comment]
If the styles are specified in the TerriaJS init file (rather than per-feature in the GeoJSON), the legend should reflect them, of course.

**Comment by nf-s** [comment]
This is now supported for new ProtomapsImageryProvider geojson items (https://github.com/TerriaJS/terriajs/pull/5900). To use this you will need to set `Terria.configParameters.enableGeojsonVt = true`

There is still no automatic legend for GeoJson items which use simple-style (inside Feature properties)

I'm going to close this issue, we can re-open later if needed
