### ISSUE TITLE
Error when loading Cesium map after update to 1.18

### ISSUE THREAD

**Issue by keattang** [TerriaJS/terriajs#1360]
I'm getting a silent error where the globe and base map don't load. As far as I can tell its unrelated to my build but it would be good to get someone else to confirm whether they have a successful build.

The error occurs here because `encoding` is undefined:
https://github.com/TerriaJS/cesium/blob/c1af4a31e0db438fc95564b43aa26994f70989dd/Source/Core/TerrainEncoding.js#L320

And originates here: https://github.com/TerriaJS/terriajs/blob/90e346fc3750e9c005633a8ec9feb8729676fde8/lib/Models/Cesium.js#L156

What seems to be happening is that the `createVerticesFromHeightmap` web worker is not attaching the `encoding` property to the result it returns. 

This is the stack trace I get when manually calling `encoding.quantization` from the developer console. You can reach this point by turning on `Pause on caught exceptions` and loading switching between `3D Terrain` and `3D Smooth`.

```
Uncaught TypeError: Cannot read property 'quantization' of undefined(…)
TerrainEncoding.clone @ TerrainEncoding.js:194
(anonymous function) @ HeightmapTerrainData.js:84
(anonymous function) @ when.js:196
(anonymous function) @ when.js:297
processQueue @ when.js:647
_resolve @ when.js:333
promiseResolve @ when.js:359
completeTask @ TaskProcessor.js:46
worker.onmessage @ TaskProcessor.js:91
_worker.onmessage @ Cesium.js:157
```

Anyone have an idea on what might be causing this?

**Comment by kring** [comment]
This is caused by running TerriaJS with `npm link`, while TerriaJS itself uses `terriajs-cesium` 1.18.0 while your main application uses `terriajs-cesium` 1.15.6 (or some other version).  Make sure your terriajs-cesium versions are in sync and it should work fine.

**Comment by keattang** [comment]
Still seem to be getting the same error :-/ I've got `"terriajs-cesium": "1.18.0",` in the `package.json` of both `terriajs` and my main application. I've cleared the `node_modules` folder and re-run `npm install` and `npm update` for good measure. 

Is there something else I could be missing? Is there some new config that needs to passed into terria when instantiating/starting it?

**Comment by RacingTadpole** [comment]
If you're using `npm link`, Kevin's advised me you may have to run `gulp terria-prepare-cesium` in your cesium directory, and `gulp prepare-cesium` for good measure in your terriajs directory too.

**Comment by keattang** [comment]
I'm not linking `terriajs-cesium` so I haven't run `gulp terria-prepare-cesium` but I did run `gulp prepare-cesium` and that fixed the issue which is awesome. Thanks!.

Another error that seems related has popped up though. When trying to load my own heightmap terrain I get the error:

```
An error occurred while rendering.  Rendering has stopped.
undefined
TypeError: Cannot read property 'getAttributes' of undefined
TypeError: Cannot read property 'getAttributes' of undefined
    at createResources (http://localhost:5000/static/propeller_viewer/propellerviewer.min.js:168110:47)
    at TileTerrain.processLoadStateMachine (http://localhost:5000/static/propeller_viewer/propellerviewer.min.js:168034:9)
    at processTerrainStateMachine (http://localhost:5000/static/propeller_viewer/propellerviewer.min.js:150320:16)
    at Function.GlobeSurfaceTile.processStateMachine (http://localhost:5000/static/propeller_viewer/propellerviewer.min.js:150258:9)
    at GlobeSurfaceTileProvider.loadTile (http://localhost:5000/static/propeller_viewer/propellerviewer.min.js:150731:22)
    at processTileLoadQueue (http://localhost:5000/static/propeller_viewer/propellerviewer.min.js:162747:22)
    at QuadtreePrimitive.update (http://localhost:5000/static/propeller_viewer/propellerviewer.min.js:162573:9)
    at Globe.update (http://localhost:5000/static/propeller_viewer/propellerviewer.min.js:149725:17)
    at updatePrimitives (http://localhost:5000/static/propeller_viewer/propellerviewer.min.js:163912:22)
    at render (http://localhost:5000/static/propeller_viewer/propellerviewer.min.js:164060:5)
```

From line:
https://github.com/TerriaJS/cesium/blob/c1af4a31e0db438fc95564b43aa26994f70989dd/Source/Scene/TileTerrain.js#L228

Where the `tileTerrain.mesh` doesn't have an `encoding` property.

Thoughts?

**Comment by kring** [comment]
What custom parts are you using to load your own heightmap?  Do you use CesiumTerrainProvider?  HeightmapTerrainData?  It looks like HeightmapTerrainData should be setting the encoding when creating the TerrainMesh, so as long as you're using that I don't know why your `encoding` property would be undefined.

**Comment by keattang** [comment]
Ah yep that's fixed it. Forgot that we were using our own fork of `CesiumTerrainProvider`. Thanks guys!
