### ISSUE TITLE
time slider limited to 1000 steps?

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#1365]
I was scratching my head about why TerriaJS was not showing the full time range for this WMS endpoint (http://sci-wms.whoi.edu/wms/datasets/adcirc_ike_2d_waves?REQUEST=GetCapabilities)
as shown here:
http://comt.sura.org/proxy_3001/#https://raw.githubusercontent.com/rsignell-usgs/ehzrap/master/testing/comt.json

The starting time is correct:  `05-Sep-2008 12:10:00`, but the end time on the slider is `12-Sep-2008 10:50:00` instead of `17-Sep-2008 12:00:00` as listed in the getCapabilities.   

I was wondering why that strange cutoff, until I realized that `12-Sep-2008 10:50:00` is time step 1000 !!!

So is `MAX_TIMESTEPS=1000` or something that can be changed somewhere?  

I looked and couldn't find it.

**Comment by kring** [comment]
Yes, there's a limit of 1000 intervals by default.  You can change it by setting the `maxRefreshIntervals` property on the WMS catalog item.

``` javascript
    /**
     * Gets or sets the maximum number of intervals that can be created by a single
     * date range, when specified in the form time/time/periodicity.
     * eg. 2015-04-27T16:15:00/2015-04-27T18:45:00/PT15M has 11 intervals
     * @type {Number}
     */
    this.maxRefreshIntervals = 1000;
```

**Comment by rsignell-usgs** [comment]
So in here:
https://github.com/rsignell-usgs/ehzrap/blob/master/testing/comt.json#L14-L26
just insert 

```
                {
                    "name": "ADCIRC Ike 2D Wave Water Levels",
                    "isEnabled": true,
                    "type": "wms",
                    "url": "http://sci-wms.whoi.edu/wms/datasets/adcirc_ike_2d_waves",
                    "maxRefreshIntervals":"1000",
                    "layers": "zeta",
                    "parameters": {
                        "COLORSCALERANGE": "0.00,5.00",
                        "NUMCONTOURS": "40",
                        "styles": "filledcontours_jet",
                        "VERSION": "1.1.1"
                    }
                },
```

**Comment by kring** [comment]
Yep, that should do it.

**Comment by rsignell-usgs** [comment]
Yep, worked!!  Thanks!

http://comt.sura.org/proxy_3001/#https://raw.githubusercontent.com/rsignell-usgs/ehzrap/master/testing/comt.json

**Comment by rsignell-usgs** [comment]
@kring, is there a way to set this as a default property for all WMS layers, so that I could set the default on my TerriaJS deployment to 10000 (instead of 1000)?

Then hopefully if someone drag-and-dropped an endpoint with more than 5000 layers, it would work...

**Comment by rsignell-usgs** [comment]
Or to enable WMS endpoints with more than 1000 time steps discovered dynamically via CSW or CKAN searches, for example: http://tinyurl.com/mhxxtoj

**Comment by kring** [comment]
There's no way to set the default (though adding a way wouldn't be hard), but you can at least set it in the CKAN/CSW case by using `itemProperties`.  Just add this to the CSW or CKAN catalog item:

```
"itemProperties": {
    "maxRefreshIntervals": 10000
}
```

**Comment by rsignell-usgs** [comment]
Like this?
https://github.com/USGS-CMG/terriajs-dive/blob/master/examples/ioos_csw.json#L19-L21
If this is correct, it didn't seem to have any effect:
http://tinyurl.com/mhbnf3k

**Comment by kring** [comment]
Ah I just looked at the code and apparently we don't currently support `itemProperties` for `CswCatalogGroup`.  It'll work for CKAN.  It's trivial to add so I'll try to do that today.

**Comment by rsignell-usgs** [comment]
@kring , okay, great!  
If you get a chance to toss in a uber alles default setting, that would be awesome too, but the CSW would be very useful.

**Comment by kring** [comment]
I just opened a PR to add `itemProperties` support to `CswCatalogGroup`: #2450

By the way, you may need to nest `itemProperties` if your `CswCatalogGroup` contains a `WebMapServiceCatalogGroup` that then contains the `WebMapServiceCatalogItem` that should have the `maxRefreshIntervals`.  For example:

```
"itemProperties": {
  "itemProperties": {
    "maxRefreshIntervals": 10000
  }
}
```
