### ISSUE TITLE
Improve legend and colouring of ENUM columns

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1374]
ENUM columns currently use the `ckmeans` method to find colour bins:
https://github.com/TerriaJS/terriajs/blob/1313_csvperf/lib/Models/LegendHelper.js#L302

If the number of unique ENUM values is less than `binCount`, this gives you back the ENUM values, which is fine.

However, there are two problems if there are lots of different ENUM values (ie. more than `binCount`):
- Speed: If there are 55,000 unique values, it can take over a minute to calculate.
- Interpretability:  Eg. in the below, the regions north of Sydney have the first letter "W", which is not on the legend, and which are coloured orange (the same as "Q"):
  ![image](https://cloud.githubusercontent.com/assets/1757858/13512711/752f2662-e1f0-11e5-9c6f-0b23787458be.png)

Originally identified in #1313 .

**Comment by stevage** [comment]
Let's lay out some options for the coloring bit:

1) Refuse to do anything
2) Color them all the same
3) Color the first 20 differently, color the rest the same
4) Cycle colors, so the 21st item is the same color as the first 
5) Generate a color palette which is big enough (woot, 55,000 unique colors)
6) Somehow force there to be only 20 bins (similar to 4, but different result)
Then, how do we generate a legend in each of the above cases?

1, 2: easy
3) Just add a "All others" label to the 21st
4) Could attempt to concatenate them, showing a legend like "Q, W", but need a fallback when there are very many ("Q, W + 21 others")
5) 8-|
6) Easy

**Comment by RacingTadpole** [comment]
Yes, that's an excellent list. I would slightly vary #3 to read:
3) Color the most common 20 differently, color the rest the same.

**Comment by stevage** [comment]
Good idea. I wonder if we should generally sort enums in order of frequency? Or is alphabetical better? If we switch from one to the other, there'll be a noticeable change when you go from 20 distinct values to 21. _shrug_

**Comment by RacingTadpole** [comment]
Yeah - or indeed the order they appear in the data file, which is what we do now.
![image](https://cloud.githubusercontent.com/assets/1757858/13515744/19de0d06-e208-11e5-89d0-0feea412dfdf.png)

In the long run it would be nice to have a `TableStyle` setting and let the user pick from the best of these options. 

For now - happy to pick a sensible default? My vote is for 3, ordered by frequency and then alphabetically (or perhaps order-of-appearance).

**Comment by stevage** [comment]
Yep, I like that: always order values by frequency then alphabetically, and only distinctively colour the first 20. (Or maybe the first 19.)

If you want to be cleverer, you could choose different palettes depending on the number of values.
