### ISSUE TITLE
Automatically geocode addresses in CSV files

### ISSUE THREAD

**Issue by rdengate** [TerriaJS/terriajs#1377]
Bill says "it would be fantastic if we could support CSV files with an address column (we’d update csv-geo-au to standardise this) and people could drag on csv files with address columns, the address would be mapped to a lat/lon by Rebecca’s server and we’d visualise the results as if the lat/lon was in the csv.  I think many govt agencies and companies would love that."

**Comment by rdengate** [comment]
Branch https://github.com/TerriaJS/terriajs/tree/rd_addresses_csv addresses this, with the slight drawback that there's no geocoder service yet.

I tested with mapzen: https://search.mapzen.com/v1/search, with a personal key. However I've now disabled the key, so I also disabled the automated test that relied on it. 

Mapzen has data for only some of Australia (for now; it's in the process of incorporating gnaf data, like everyone else). This was interesting as I have some addresses that are not in Tas/ACT/Vic (which are the areas it currently has). Its response is to provide lat long for mostly unrelated addresses, with a confidence value that's equivalent to some addresses that have matched correctly. For example, 13 Garden St Eveleigh NSW 2015 finds 5/12 Garden St Brunswick Victoria with a confidence level of 0.448 (another address matched perfectly with the same confidence). So there are still some problems there, but I think perhaps they should not be solved at the Terria level.

The URL and key for the geocoder are expected to be in the config.json file used to initialize Terria e.g.:
    "parameters": {
        "bingMapsKey": null,
        "googleUrlShortenerKey": null,
        "googleAnalyticsKey": null,
        "googleAnalyticsOptions": null,
        "geocoderUrl": "https://search.mapzen.com/v1/search",
        "geocoderKey": "somekey",
        etc

If the url or key are missing from the config, there's no attempt to geocode the addresses.

I will make a pull request for this (and make changes based on feedback), but perhaps not yet, as this isn't useful until we have a geocoder with full coverage of Australia. There are also some outstanding issues with it that need to be addressed.

**Comment by rdengate** [comment]
I've updated this to work with our gnaf geocoder, but the results from that aren't yet good enough to make this useful, i.e. a lot of addresses are geocoded to the wrong locations. I've logged this as a bug: https://github.com/data61/gnaf/issues/2.

Since Mapzen search (based on Pelias) now has all gnaf addresses, I've branched off my previous work and created rd_addresses_csv_pelias (data61 geocoder in rd_addresses_csv), but unfortunately it seems Mapzen are now rate-limiting access to 6 per second, which is exceeded when dropping an address file onto the map. We would probably have to set up our own instance to get around this.

**Comment by tobybellwood** [comment]
@rdengate if you do set up your own instance of GNAF via pelias, let me know - I'd be interested in seeing the reverse geocoding at work?

**Comment by rdengate** [comment]
@tobybellwood sure, will do!

Mapzen's search now has GNAF data, so if you wanted to experiment with that it's possible. For example, reverse geocoding a point in Hyde Park with:

https://search.mapzen.com/v1/reverse?api_key=search-TeXrSTX&point.lat=-33.875294&point.lon=151.211307

returns addresses along Elizabeth St, as well as the ANZAC War Memorial, etc (that api key is from the Mapzen docs, by the way, so if you end up using this in anything you might want to replace it with your own key).

**Comment by rdengate** [comment]
This is now in TerriaJS but not in any instances of National Map yet. The accuracy is pretty good but not perfect. We're working to make speed improvements to the GNAF API. We won't need a Pelias instance at this time.
