### ISSUE TITLE
User-added data gets loaded twice

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1378]
I don't know exactly what the "correct" behaviour is, but catalog items go through `._load()` twice. Well, at least GeoJsonCatalogItem does.

The tricky line seems to be in `addUserCatalogItem`:

```
        if (defaultValue(options.enable, true) && defined(newCatalogItem.isEnabled)) {
            newCatalogItem.isEnabled = true;
        }
```

By the time this line is hit:
- the `GeoJsonCatalogItem` has been loaded, and its `._loadingPromise` is undefined
- its `isEnabled` property is false
- it has an `isEnabledChanged` trigger which causes `.load()` to get called if `isEnabled()` is set true.
- `options` is `{}`

Something in that state is wrong.

Possibly the issue is in `CatalogItem.isEnabledChanged`:

```
        // Load this catalog item's data (if we haven't already) when it is enabled.
        //...
        if (!defined(catalogItem._loadForEnablePromise)) {
            var resolvedOrRejected = false;
            var loadPromise = when(catalogItem.load(), function() {
```

The comment suggests that the loading behaviour should only happen "if we haven't already", but the test is only testing if this particular piece of code was the thing that caused that load to happen (which would set `._loadForEnablePromise`).

I'm not sure where to go from here.

**Comment by kring** [comment]
Adding a GeoJSON by URL does indeed cause `_load` to be called multiple times, but it's only called once for the GeoJsonCatalogItem that you're adding.  The other invocations are for things like loading the User-Added Data Group and the GeoJSON catalog item that is used to display the bounding rectangle on the preview map.

It's possible that the GeoJSON was loaded multiple times when Steve wrote this, but it doesn't appear to be a problem anymore.
