### ISSUE TITLE
Start timeslider at specified time including 'Present'

### ISSUE THREAD

**Issue by rdengate** [TerriaJS/terriajs#1382]
This was discussed in https://github.com/TerriaJS/terriajs/issues/889. It recently came up in a GEOGLAM meeting as well.

The GEOGLAM clients want to show the latest data in the timeseries layer that they have when the map is first opened. That data will be updated regularly, so the definition of end will change.

In addition, we should allow as a parameter in the init file:
    \* Start (we already have, apparently)
    \* End (may be in the future, if the data series has forecasting)
    \* Present (nearest to current time)
    \* ISO8601 timestamp

**Comment by AlexGilleran** [comment]
Quite closely related (as both share links and init files are basically the same structure): https://github.com/TerriaJS/terriajs/issues/1333

**Comment by uwer** [comment]
Another issue: we had several request to allow stepping as well as stepping/progress at actual available time steps for data (naturally tis becomes difficult for more than one datasource)

**Comment by meh9** [comment]
@uwer, this is something that I think we have just put some code in yesterday to deal with, have a look at https://github.com/TerriaJS/terriajs/pull/1328 which is in response to https://github.com/TerriaJS/terriajs/issues/946.

We are working on a prototype of the NewUI with WPS functions, context, and the static layers to bring things together, but everything is in a state of flux at the moment...

**Comment by kring** [comment]
This was resolved in #1475 but we forgot to close the issue.
