### ISSUE TITLE
Replace _ with space in ArcGIS automagic legends

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1388]
When Terria makes one of the new awesome ArcGIS automatic legends we show the `_` character. This is very often included since all GIS systems appear to have problems with spaces. We should probably replace all `_` with a space - I believe we already do this in other places?

Example automatic legend:

<img width="221" alt="screen shot 2016-03-11 at 9 18 31" src="https://cloud.githubusercontent.com/assets/5283003/13686530/4030b1ae-e76a-11e5-9f56-f09aef8261a9.png">

**Comment by RacingTadpole** [comment]
Can you send me a link for that example @meh9 ? Thanks.

**Comment by meh9** [comment]
This one has a lot - both layer names and legend names (they appear to be separate strings).

http://www.ga.gov.au/gis/rest/services/topography/AusHydro/MapServer

Do we also want to consider replacing `_` in the catalogue tree as well?
