### ISSUE TITLE
Feature highlight and target cursor remains after layer removed

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1400]
I think we'd probably call this a bug?
![featureinfo](https://cloud.githubusercontent.com/assets/678344/13804720/6a8464cc-eba3-11e5-947e-6c314b831a04.png)
1. Enable a layer
2. Click a feature. (The area highlights)
3. Disable the layer
4. The feature remains highlighted.

**Comment by kring** [comment]
The target cursor and feature info panel section should probably go away too, right?

**Comment by stevage** [comment]
Yep.

**Comment by kring** [comment]
The feature info content disappears when you remove the layer, but the feature highlight and crosshairs don't.

**Comment by nf-s** [comment]
This is fixed now
