### ISSUE TITLE
Allow item-specific styling (including feature info template) for individual CKAN items

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1408]
It would be nice to be able to include a feature info template, and other styling information, for the [ABC photo stories](http://data.gov.au/dataset/abc-local-online-photo-stories-2009-2014), which are provided in the data.gov.au CKAN catalog entry.

**Comment by chloeleichen** [comment]
maybe we should allow inline css in feature info template?

**Comment by RacingTadpole** [comment]
That's a good idea - although not what I meant here. I meant we can't supply a `featureInfoTemplate` at all for an item inside a `ckan`-type catalog item, eg. in this file: https://github.com/NICTA/nationalmap/blob/master/datasources/01_Data.gov.au.json

**Comment by AlexGilleran** [comment]
Don't we allow inline css in the feature info template? (Ab)Used that in the ABC Photo Stories thing :)

**Comment by stevage** [comment]
Nice idea. Thoughts on how to specify it?

```
{
  "catalog": [
    {
      "url": "http://www.data.gov.au",
      "type": "ckan",
      "name": "Data.gov.au",
      "includeCsv": true,
      "featureInfoTemplates": {
          "resource": "abc-local-online-photo-stories-2009-2014"
          "featureInfoTemplate": "..."
      }
    }
  ]
}
```

That seems a bit overly specific. Could we do something maybe more like this:

```
{
  "catalog": [
    {
      "url": "http://www.data.gov.au",
      "type": "ckan",
      "name": "Data.gov.au",
      "includeCsv": true,
      "items": [
         {
           "type": "ckan-resource",
           "resourceId": "abc-local-online-photo-stories-2009-2014",
          "featureInfoTemplate": "..."
         }
      ]
    }
  ]
}
```

That is, explicitly point to certain items within the dynamic catalogue and provide specific attributes for them.

But really, all metadata (including presentation metadata?) should be managed within the CKAN itself so perhaps that's where we should be looking...

**Comment by stevage** [comment]
Another option might be to extend the `itemProperties` attribute somehow. Could get very complex for a real edge case problem though.

**Comment by ykiu** [comment]
I was trying to use CKAN to manage my dataset and ran across the same issue. Are there any updates regarding this?

> all metadata (including presentation metadata?) should be managed within the CKAN itself

This is the very thing that I hope to achieve.

**Comment by nf-s** [comment]
There is a hacky solution that works - but definitely agree we should support this properly

```json
{
  "id": "some-group",
  "excludeMembers": [
    "hidden-group"
  ],
  "members": [
    {
      "id": "hidden-group",
      "type": "group",
      "members": [
        {
          "id": "some-model",
          "type": "some-model-type",
          "someProperty": ""
        }
      ]
    }
  ]
}
```

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/6218
