### ISSUE TITLE
Processing large files like CSVs on load causes map to switch to 2D most times

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/terriajs#1409]
Right now if you have a map with a large, processing-intensive file like a CSV that loads on startup, Terria does this at the same time it's trying to load Cesium, finds that Cesium's loading too slowly (which makes sense) and switches to Leaflet, even though the computer might be more than capable of running Cesium once the data is processed.

Loading CSVs in general absolutely thrashes the CPU too, generally locking the whole UI for 10 seconds on long filese.

Some ideas:
- Make sure Cesium is fully loaded before we do any data loading/processing
- Find some way to reduce the load of data processing, even if it means taking longer to do it - maybe divide it up into chunks and keep yielding the CPU with `setTimeout`, or investigate a webworker?

**Comment by stevage** [comment]
> Loading CSVs in general absolutely thrashes the CPU too, generally locking the whole UI for 10 seconds on long files.

As someone who's spent quite a while on CSV performance issues, I'm going to have to ask you to be a bit more specific with your outrageous generalisations :) What file? What version of TerriaJS? Is the primary issue here the total time, or the lack of responsiveness during loading?

**Comment by pwalsh** [comment]
@stevage saw this in my GitHub feed. FYI PapaParse http://papaparse.com is a great solution for streaming read of CSV in the browser, and delegating CSV reading to web workers.

FYI :)

**Comment by AlexGilleran** [comment]
@stevage sorry I didn't see this when you made the comment. The issue isn't with how fast we actually process the CSV (which is good, but no matter how fast we make it there'll always be one with more lines), the problem is the lack of responsiveness, which is only one flow-on effect from locking up our one JS thread, the other one being that the code that switches to Leaflet gets triggered because it thinks the computer can't handle Cesium.

@pwalsh looks interesting, thanks :).

**Comment by AlexGilleran** [comment]
The example that triggered this was the ABC photo stories CSV, which is about 6500 lines once we've filtered it, but I see it quite often - the WA census information often triggers a downgrade, for instance. This was with whatever was on `master` two weeks ago.

**Comment by kring** [comment]
We fixed the "your system is too slow" logic awhile ago so that it is no longer triggered in this scenario. Large CSVs can still take time to load, but that's more acceptable than flipping to 2D (and bothering the user about it) for no reason.
