### ISSUE TITLE
`newui` UX Improvements

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1414]
Here are a bunch of things that would be great for our demo next week:
- [x] Improve feature info panel chart dropdowns, eg. ![image](https://cloud.githubusercontent.com/assets/1757858/14005248/96a4d98e-f1b5-11e5-8eb2-105adef574db.png) instead of  ![image](https://cloud.githubusercontent.com/assets/1757858/14005269/bbe640e8-f1b5-11e5-99cf-a57d31091201.png)
- [x] Fix the positioning and hover-underlining of the chart panel download button ![image](https://cloud.githubusercontent.com/assets/1757858/14005664/51ae518a-f1b9-11e5-8fb4-ec496f56c90c.png)
- [x] Fix the latest Aremi welcome page and logo.
- [x] Add the "ontop" class to all the panels, eg. the preview panel and the base map panel.
- [x] Fix the "unusually slow performance" appearance.
- [x] Review and merge #1412

Some less urgent ones if you have time -
- [x] ![image](https://cloud.githubusercontent.com/assets/1757858/14008753/f6842ae4-f1d8-11e5-8c81-66b6e23ff381.png)
- [x] In the old UI, opening the chart panel resized the map; in the new UI, it is just covering the map. Can we resize the map in the new UI too?

**Comment by chloeleichen** [comment]
![screen shot 2016-03-28 at 6 18 05 pm](https://cloud.githubusercontent.com/assets/7508939/14073052/8c646926-f511-11e5-8971-743c1e8a5334.png)
![screen shot 2016-03-28 at 6 18 12 pm](https://cloud.githubusercontent.com/assets/7508939/14073053/8c67468c-f511-11e5-8700-b2dff0b825b1.png)
![screen shot 2016-03-28 at 6 18 20 pm](https://cloud.githubusercontent.com/assets/7508939/14073054/8c6889b6-f511-11e5-8c88-558d15cda784.png)

**Comment by chloeleichen** [comment]
![screen shot 2016-03-28 at 10 22 46 pm](https://cloud.githubusercontent.com/assets/7508939/14077085/acb3643a-f533-11e5-938a-1a2585769d7a.png)

**Comment by RacingTadpole** [comment]
Awesome - thanks Chloe!
