### ISSUE TITLE
Enable hiding of layer URLs from the interface

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1416]
We have a requirement to be able to hide the layer source URLs from the interface for particular layers. From what I can tell we need to hide the source URL and the Metadata URL, but there may be others.

Suggest we have something you can set in e.g. the init file like `"hideSourceUrls": true`.

**Comment by stevage** [comment]
The requirement from GA was to hide:
- the data source URL
- the metadata URL
- the "Data Details"
- the "Service Details"

It'd be nice to implement this in a way which is slightly more general or flexible than just this one use case for WMS layers, but nothing's springing to mind.

Maybe `"dataUrlType": "hidden"`, which would imply hiding anything with the URL, which would include those three other sections? That avoids introducing a new property.

**Comment by stevage** [comment]
This was implemented as `"hideSource": true`
