### ISSUE TITLE
Feature selection of polygons in CZML is inconsistent with other datatypes

### ISSUE THREAD

**Issue by axman6** [TerriaJS/terriajs#1421]
Currently feature selection of CZML polygons isn't consistent with raster layers such as WMS - clicking a polygon colours the interior almost black (but only sometimes!), which means that if the colour was important it can’t be seen anymore. This has been brought up in out work with the institute of sustainable futures. This can be see on the ISD demo deployment (details shared on slack because this isn't public) then going to Electricity Infrastructure -> Networks Opportunities -> Available Capacity and clicking on a polygon.

Preferably the border would just be made thicker, but @kring has mentioned that this problematic on Windows so some other means of indication selection is needed. Some options which we've discussed include: 
- Making the polygon pulse its colour (possibly by just adjusting the opacity). This has the downside of needing constant render loop triggering leading to hot laptops.
- Somehow making the interior of the polygon striped - Apparently possible in Cesium but maybe not Leaflet

![czml feature selection 2](https://cloud.githubusercontent.com/assets/39567/14239587/805c8554-fa80-11e5-8dd1-db72d9824330.png)
![czml feature selection 1](https://cloud.githubusercontent.com/assets/39567/14239588/80a0c746-fa80-11e5-9a18-82d1917daac5.png)

**Comment by kring** [comment]
Vector polygin selection is not working at all at the moment. I'm going to close this, but have added a note to #2733 to consider this issue when fixing that one.
