### ISSUE TITLE
Allow zooming into chart control

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1425]
NEII Viewer wants the ability to zoom into a specific section of a time series chart. https://github.com/TerriaJS/neii-viewer/issues/8

**Comment by RacingTadpole** [comment]
Yes, this is high on the list once we have the new UI up and running.

**Comment by AnaBelgun** [comment]
Will close this one; duplicated here: https://github.com/terriajs/terriajs/issues/3639
