### ISSUE TITLE
Selection area persists in some cases where it shouldn't

### ISSUE THREAD

**Issue by rdengate** [TerriaJS/terriajs#1429]
When switching between map types, the old selection area hangs around. I have tested this in terria/newui and it also appears in http://nationalmap.research.nicta.com.au/newui/

To reproduce:
1. Select Data catalog > statistical boundaries > Indigenous Areas.
2. Select an area (white selection outline)
3. Select a different area
4. Go to Maps > 2D. Now you can't select areas, which is probably not implemented yet.
5. Maps > 3D. Your original selected area comes back.
6. Select a different area
7. The old area is not deselected. The white rectangle of the old selection hangs around while the new selection changes as expected.

Tested on Firefox only.

**Comment by tephenavies** [comment]
It looks like a couple of things are missing from newui:
- [ ] Opening the map selector :globe_with_meridians: doesn't close the feature info panel
- [x] The selection area isn't removed when the feature info panel is closed
- [x] Selection areas don't work in 2D

**Comment by tephenavies** [comment]
Testing in newui branch of TerriaJS, selection in 2D is working, and the map selector shows up above the feature info panel, so the things to fix are:
- [x] Remove selection area when the feature info panel is closed
- [x] Remove selection area when the map changes modes

**Comment by stevage** [comment]
Related to, but not duplicate of, #1400.

**Comment by kring** [comment]
> Opening the map selector :globe_with_meridians: doesn't close the feature info panel

The map selector now appears over the top of the feature info panel, which I think makes sense, except in a case covered by #1714.

**Comment by kring** [comment]
Fixed by #1715.
