### ISSUE TITLE
Clicking close to a previous click doesn't register in newui 3D

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#1433]
This bug doesn't affect the Leaflet 2D map.
Old UI:
![old ui feature selection](https://cloud.githubusercontent.com/assets/13863530/14374576/bab1e97a-fd9a-11e5-8406-6d6ca443f0fe.gif)

newui:
![cannot refine a feature selection](https://cloud.githubusercontent.com/assets/13863530/14374571/afcf1208-fd9a-11e5-8b65-b9121714f142.gif)

**Comment by tephenavies** [comment]
This is because the image is displayed on top of the map and the css is wrong (I think?) so you can't click through it. I tried adding a `pointer-events: none;` to the image, but then the clicks go to the page (still not the map :disappointed:).

@chloeleichen probably knows more about this.

**Comment by kring** [comment]
Fixed by #1715 (or maybe it was already fixed)
