### ISSUE TITLE
Incorrect map type is highlighted when changing maps in newui

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#1434]
The map changes correctly, but the current map type is incorrectly highlighted.
![incorrect map type highlighted](https://cloud.githubusercontent.com/assets/13863530/14374632/82d8817a-fd9b-11e5-93b4-7a262d8c928e.gif)

**Comment by tephenavies** [comment]
This is caused by the `state` of `SettingPanel` not changing when the viewer mode changes. The state only changes when a base map is clicked on or hovered over.

This bug affects more than just the viewing modes. If you change the base map without clicking or hovering over any of the base maps (for example through appending a json init file to the url), the panel will not update until you hover over or click on one of the base maps.

The way the panel updates probably needs to be rethought, because the properties that it uses as `state` to know when to update the panel can be changed within Terria without any user interaction with the panel. @kring, @chloeleichen Any thoughts?

**Comment by tephenavies** [comment]
An example of the state being out of date:
![state change on hover](https://cloud.githubusercontent.com/assets/13863530/14453206/b62d4ebe-00d6-11e6-87e2-bf862ce669ed.gif)

**Comment by chloeleichen** [comment]
I think @AlexGilleran broke it 😄😄😄😄😄😄

**Comment by AlexGilleran** [comment]
@AlexGilleran does not concur :unamused:

**Comment by kring** [comment]
I think this one was fixed somewhere along the way.  Closing.  Reopen it if you still see it.
