### ISSUE TITLE
Dragging a file onto the map without dropping in newui results in the "Drag & Drop" overlay persisting

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#1435]
Dropping the file onto the map removes the overlay correctly. Putting chrome in fullscreen and repeating this results in a full screen overlay that cannot be removed (you can't click the close button on the data finder since the overlay is on top of it and the escape button doesn't do anything either).

Also, the overlay doesn't look like it is in the right place.

![drag and drop newui](https://cloud.githubusercontent.com/assets/13863530/14374835/ef46ab0a-fd9d-11e5-9aaa-935506d4d11f.gif)

Tested on Chrome 50 Mac OS X 10.11

**Comment by chloeleichen** [comment]
@AlexGilleran did you fix this already?

**Comment by AlexGilleran** [comment]
No... and looking at my git I think I might even have lost the progress I made towards it when I got borgified :(

**Comment by chloeleichen** [comment]
ok i'm on it

**Comment by chloeleichen** [comment]
This is fixed
