### ISSUE TITLE
Leaflet preview draws ABS region mapped items differently the first time you preview them

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#1436]
![abs preview newui](https://cloud.githubusercontent.com/assets/13863530/14375497/12181c20-fda5-11e5-9126-3d6186358c83.gif)

When you first select the item, it displays data for the "AUS" region map, then when you select it again it displays using "SA4" (which is the default when the dataset is added to the main map).

**Comment by tephenavies** [comment]
Initial investigation:
In newui, clicking on an item (just to preview) prints to the console:
- Found region match based on sa4_code_2011
- (2x) Found region match based on aus

In the old UI, adding an item to the map prints to the console:
- Found region match based on sa4_code_2011

**Comment by tephenavies** [comment]
It seems that when `function rebuildData(item)` is called with an `item` that has an empty filter `[]`, the `AbsConcept` constructor sets the first as the active concept. From `AbsConcept.js:69`:

``` javascript
// If no codes were made active via the 'filter' parameter, activate the first one.
```

When it has a filter such as: `["MEASURE.3", "AGE.A04", "AGE.A10", "AGE.A15", "AGE.A59", "REGIONTYPE.SA4"]` the constructor sets `"SA4"` (the correct region type) as active

**Comment by tephenavies** [comment]
I think I have found the problem. `DataPreviewMap.jsx` clones an `AbsIttCatalogItem` by serialising and creating a new `CatalogItem` from the JSON. From `DataPreviewMap.jsx:63-70`:

``` javascript
if (previewed && defined(previewed.type) && previewed.isMappable) {
            const type = previewed.type;
            const serializedCatalogItem = previewed.serializeToJson();
            const catalogItem = createCatalogMemberFromType(type, this.terriaPreview);

            catalogItem.updateFromJson(serializedCatalogItem);
            catalogItem.isEnabled = true;
            this.catalogItem = catalogItem;
```

`serializeToJson()` calls the serialisers defined in `AbsIttCatalogItem.js`. From `AbsIttCatalogItem.js:330-338`

``` javascript
AbsIttCatalogItem.defaultSerializers.filter = function(item, json) {
    // Create the 'filter' that would start us off with the same active items as are currently shown.
    var nestedFilter = item._concepts.map(function(concept) {
        return concept.toFilter();
    });
    json.filter = nestedFilter.reduce(function(a, b) {
        return a.concat(b);
    }, []);
};
```

The `filter` serialiser above takes an item and generates a `filter` list from its concepts. **The problem is that this item doesn't have any concepts loaded yet** (so `item._concepts` is an empty list `[]`). The item has a filter `["MEASURE.3", "AGE.A04", "AGE.A10", "AGE.A15", "AGE.A59", "REGIONTYPE.SA4"]` that is from the `nm.json`, but since `loadConcepts`, called by `rebuildData` (`AbsIttCatalogItem.js:431`) which is in turn called by `_load`.

Possible fixes would be to:
- Call load on `previewed` in `DataPreviewMap.jsx` before serialising (could be potentially slow)
- Change the serialisers in `AbsIttCatalogItem.js` to:
  - Call `_load` on the item if it isn't loaded
  - Call `rebuildData`
  - Call relevant loading functions individually (like `loadConcepts` etc.)

@kring What do you think should be done?

**Comment by kring** [comment]
@steve9164 I'm pretty unhappy with the need to serialize catalog items for preview.  Maybe the correct solution to this problem is to find a better solution to that problem?

**Comment by RacingTadpole** [comment]
Some options, ranked in order of decreasing hackiness (from discussion with @kring and @AlexGilleran):
1. Temporarily swap out the `terria` on the `catalogItem`.
2. Temporarily swap the existing viewer out of `terria` to replace with the preview version.
3. Pass `terria` instance into `_enable` and `_show`.
4. Pull the map out of `terria`, so that `terria` is a singleton even if three maps are shown. Pass the map explicitly where needed.

Or, remove the preview map entirely - replacing it with either a pre-generated image, or nothing.

**Comment by AlexGilleran** [comment]
Also related to that idea I had that was so bad it didn't even make the list, possibly we could remove the preview map, then have a "PREVIEW ON MAP" button that when clicked makes the modal move over to the side and shows just that dataset on the main map, with a really obvious BACK button that puts the big map back into its previous state and puts the modal back in the middle.
