### ISSUE TITLE
Include Lat/Lon in data passed to templated feature info

### ISSUE THREAD

**Issue by axman6** [TerriaJS/terriajs#1438]
It'd be nice to always have access to the lat and lon Terria uses when making a GetFeatureInfo request. Our use case is providing a URL which includes the lat and lon to download data related to that location from another service. It might be worth prefixing this data wither with a key such as `terrialat` and `terrialon`, or as a key with this (and possible other metadata) under `"terria": {"lat":...,"lon":...}`. I think I like the latter because it's easier to extend with more metadata.

**Comment by AlexGilleran** [comment]
So just thinking about this again - the lat/long of the actual click could be (literally) miles away from the actual location - more at higher zoom levels. Would it be better to have the lat/long of the actual feature? If I can't get that would the lat/long of the pick still be desirable given that it might be a bit wrong?

**Comment by AlexGilleran** [comment]
Actually I'm pretty sure I can get the lat/long of the feature. Might be slightly off because of conversion from a position in Cesium coords back to lat/long.

**Comment by meh9** [comment]
So, there are probably a couple of different use cases:
- Click on a Feature - show the lat/lon of the feature
- Click on a Raster - provide the lat/lon to the template tags like <chart>

I guess if there is no layer data where the click is then we do nothing?

**Comment by AlexGilleran** [comment]
Well, yeah in that case it'll just be showing "There Are No Features Found" anyway.

OK cool - that makes sense re: the Raster, I'm thinking too much in Terria-land where everything Raster or Vector is an `Entity` with its own position.
