### ISSUE TITLE
Make Terria a more open OSS project

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/terriajs#1441]
Following on from a discussion with @stevage and @kring last week, Terria is an open-source project in the sense that all the code is open and can be read, forked etc, but a look at the contributors shows very few names that haven't worked at NICTA or Data61, and it'd be nice if we had more engagement with the community, in terms of better supporting users and encouraging external contributions.
- [x] Create an open chat outside the private Slack channels (https://gitter.im/TerriaJS/terriajs)
- [ ] Write a better contributors guide
- [x] Have a standard boilerplate to allow people to get started rather than simply cloning NationalMap
- [x] Write a getting started guide for people who don't want to develop Terria directly
- [x] Perhaps a bit more explanation of exactly what Terria does and why it's important - highlighting features like CSVs and graphs and stuff. A video maybe?
- [ ] Create an open version of the Data61+Live Awesome Terria Map and put a link to it in the README so people can see how awesome Terria is.
- [ ] Open, written roadmap on Github. Or at least one outside kring's head...

Any more suggestions are welcome :).

**Comment by rsignell-usgs** [comment]
Hopefully @jiwalker-usgs can contribute some ideas here as he explores what it's like to add an enhancement from outside the Data61 team.

**Comment by stevage** [comment]
TODO:
- [x] refresh/expand CONTRIBUTING.md (see [Cesium's](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md) for inspiration)
- [x] Make TerriaJS the starting point, with the README there etc, even though the user will be cloning TerriaMap to get started.
- [ ] Sketch a roadmap

-- improving build process so TerriaJS works better as a standalone library
-- make search not suck
-- Cesium performance
-- Cesium quality of imagery display (eg handling 3857 imagery without reprojecting twice)
-- Editor generation and schema validation

**Comment by kring** [comment]
http://cesiumjs.org/presentations/FOSS4GNA2016/Growing-an-Open-Source-Community-Lessons-Learned-from-Cesium.pdf

**Comment by rsignell-usgs** [comment]
@kring.  Very nice presentation. Thanks for sharing it.

I found this quote particularly interesting: 

> In the very early days of Cesium, I focused too much on “grow the contributor
> community”, when I should have focused on “grow the user community”, because the
> contributor community comes largely from the user community who need bug fixes,
> believe in the project, etc.

**Comment by stevage** [comment]
- [ ] Create a launchable AWS image
- [x] Create Google Group

**Comment by stevage** [comment]
Google Group: https://groups.google.com/forum/#!forum/terriajs

**Comment by rsignell-usgs** [comment]
@jiwalker-usgs , since you are a non Data61 developer who successfully got your PR merged (https://github.com/TerriaJS/terriajs/pull/1754) would you be willing to give feedback here on what you think could be improved from an external developer standpoint?

**Comment by jiwalker-usgs** [comment]
@rsignell-usgs yes, I'll definitely add my thoughts on this, thanks for pointing this out

**Comment by kring** [comment]
Time to close this.  Here's where we stand with the issues tracked here:

> Write a better contributors guide

It's not bad (https://github.com/TerriaJS/terriajs/blob/master/CONTRIBUTING.md). If anyone has specific ideas for improvement, write an issue to capture them.

> Create an open version of the Data61+Live Awesome Terria Map and put a link to it in the README so people can see how awesome Terria is.

Now captuerd in TerriaJS/saas#302.

> Open, written roadmap on Github. Or at least one outside kring's head...

Getting there!  I don't think we need an issue to track it though.

> Create a launchable AWS image

Similar to TerriaJS/terriajs#2803 and TerriaJS/terriajs#1301, but those are more cloud-provider-neutral. I think unless someone asks for it specifically, we can let this one go.

**Comment by kring** [comment]
By the way: by closing this, I don't mean to say that TerriaJS no longer cares about being a serious open source project, or that there's nothing left to do. Let's keep thinking about ways we can do better and either do them or open issues for them.
