### ISSUE TITLE
Support opacity/transparency in vector layers such as WFS, GeoJSON, CSV, CZML.

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#1442]
It seems there is no opacity control for WFS layers.   I tried adding this endpoint:
https://www.sciencebase.gov/catalogMaps/mapping/ows/5342c5fce4b0aa151574a8ed?service=WFS&version=1.1.0&request=GetCapabilities

and it worked fine when I selected the feature, but there is no `OPACITY` control when I go to the `Now Viewing` panel:
![2016-04-12_8-40-27](https://cloud.githubusercontent.com/assets/1872600/14460363/2e56bd5e-008b-11e6-8b07-2f8345d6ab43.jpg)
![2016-04-12_8-37-55](https://cloud.githubusercontent.com/assets/1872600/14460369/32ebd1b0-008b-11e6-90b5-bb8ac0e6abca.jpg)

**Comment by RacingTadpole** [comment]
When I tested this in the latest master (being released today as 2.3.0), it appears to work, though I'm not sure exactly what change fixed it! :-) Please re-open this if you still see it.

**Comment by kring** [comment]
@RacingTadpole are you sure?  AFAIK there's no code in TerriaJS to handle opacity for vector features, including GeoJSON, CZML, WFS, etc.  That's because Cesium has no layer-level opacity adjustment for vector layers.  We need to adjust the opacity of each primitive in each entity according to the layer's opacity.

**Comment by kring** [comment]
I think I see what's happening.  When I copy @rsignell-usgs's URL into Add Data, it currently gets added as WMS.  That may be a new-ish bug (it's supposed to see the WFS in the URL and try accessing it as WFS first, even though the `/ows` endpoint can serve both).  If you explicitly select WFS, you won't be able to adjust the opacity.  I'm going to reopen this.

**Comment by nf-s** [comment]
This is enabled for new ProtomapsImageryProvider geojson items. To use this you will need to set `Terria.configParameters.enableGeojsonVt = true`
