### ISSUE TITLE
Why isn't this WMS working (yes, I've got this in the proxy whitelist)

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#1443]
I'm getting errors when i try to add this WMS endpoint:
http://ecowatch.ncddc.noaa.gov/thredds/wms/ncom_amseas_agg_20091119_20130404/Amseas_May_2010_to_Apr_04_2013_best.ncd?service=WMS&version=1.3.0&request=GetCapabilities

Yet I've got this in my `./map/wwwroot/config.json` whitelist:

```
    "proxyDomains" : [
      "rutgers.edu",
      "neracoos.org",
      "unm.edu",
      "nicta.com.au",
      "data.gov",
      "usgs.gov",
      "noaa.gov",
      "sci-wms.whoi.edu",
      "ecowatch.ncddc.noaa.gov",
      "geoport-dev.whoi.edu",
      "www.smast.umassd.edu:7002",
      ...
```

but I'm still getting an error adding this as a WMS source.    

Is the getCaps size (2.7M) too big?

**Comment by meh9** [comment]
Hmm, it actually works for me. I added `noaa.gov` to my `proxyDomains`, used the Add Data button, selected WMS and pasted in your exact URL.

Have you had a look in the Dev Tools to check that the `GetCapabilities` request actually returns?

**Comment by meh9** [comment]
I added `noaa.gov` to our prototype, and it all works:

http://prototype.aremi.nicta.com.au/renewables/#https://gist.githubusercontent.com/meh9/fb99b7b5374e35a45a1c84e5a11777d5/raw/2d16cbfee808789721087dbd05a9d6e1a936a95f/NOAA-NAVO-NCOM.json

**Comment by rsignell-usgs** [comment]
@meh9, good idea checking Dev Tools.   Indeed, the `GetCapabilities` was failing with a CORS error.    

Since I had `noaa.gov` in the `ProxyDomains` list specified in `./map/wwwroot/config.json`, I then looked at the startup catalog `./map/wwwroot/init/nfwf.json` and discovered that I had `ecowatch.ncddc.noaa.gov` specified in `CorsDomains` list.   

After removing that and restarting, it works fine.   Thanks for the help!
![2016-04-13_6-32-41](https://cloud.githubusercontent.com/assets/1872600/14490717/7bec54b8-0142-11e6-8c74-93608f2a2dbb.jpg)
