### ISSUE TITLE
Email Address Undeliverable

### ISSUE THREAD

**Issue by mjturtora** [TerriaJS/terriajs#1444]
I tried sending mail to nationalmap@communications.gov.au as suggested by the error that pops up when trying to add a czml file but it bounced. What is a working address?

**Comment by x-Code-x** [comment]
Try data@pmc.gov.au

**Comment by kring** [comment]
Yes the correct address for [NationalMap](http://nationalmap.gov.au), at least, is data@pmc.gov.au.  @mjturtora which web site were you using when you ran into this problem?

**Comment by mjturtora** [comment]
@kring I was using http://comt.sura.org/proxy_3001/ which @rsignell-usgs uses. I think that instance is a fork of EHZRAP...

Interestingly, the original EHZRAP, http://dev.tampabaymap.org/ by @metanomy points to  aremi@nicta.com.au so I guess it's an artifact of the build?

I also tried sending my question to support@terria.io which I found by rooting around in the code. My question is probably more a terria question than a national map question so should the "support@..." address work? My original question is about getting feature info applied to point data through a czml file. Not sure it's a bug or missing feature or just my lack of understanding so I didn't want to make an issue of it.

Or the simple question might be: do you get emails sent to support@terria...?

**Comment by rsignell-usgs** [comment]
@mjturtora I've got an example script that adds "description" to a CZML file, which pops up when you click a point.  See:
https://github.com/TerriaJS/terriajs/issues/1275#issuecomment-191446544

**Comment by mjturtora** [comment]
Thanks Rich, I'll take a look.

I've tried description but haven't gotten it to work. Not sure if it
belongs in the main packet or attached to a point.

Actually, I just noticed that in your email to Helga (I think) you
mentioned clicking on a point to identify bird species. This is not working
for me on the COMT Terria instance (doubt it works on Metanomy's either).

Have you tried it recently and does it still work for you? I get "No
feature found." Of course, that's after turning off the temperature so the
temp data doesn't pop up instead.

**Comment by rsignell-usgs** [comment]
@mjturtora it works just fine for me.   Stop the movie and click over land and you can get both bird type and temperature (in Kelvin):
![2016-04-15_13-47-38](https://cloud.githubusercontent.com/assets/1872600/14570143/adeee2ee-0310-11e6-966f-9add457ab239.jpg)
![2016-04-15_13-46-42](https://cloud.githubusercontent.com/assets/1872600/14570145/b0338eb0-0310-11e6-97e1-96f28761e9c7.jpg)

**Comment by mjturtora** [comment]
@rsignell-usgs  Thanks for the input. 

but odd: Does not work for me. btw, the czml.py code I came up with on my own looks just like yours. So it is something screwy somewhere.

![image](https://cloud.githubusercontent.com/assets/17150655/14570332/c3dfe520-0311-11e6-8055-2508df857543.png)

**Comment by mjturtora** [comment]
ah HAHAHA! ... It works in firefox. I was using Chrome-Canary. So it's a compatibility issue with Chrome I guess.

![image](https://cloud.githubusercontent.com/assets/17150655/14570967/d5f420ac-0314-11e6-86aa-823bcc04beb6.png)

**Comment by rsignell-usgs** [comment]
It works fine for me in Chrome Version 49.0.2623.87 m on Windows.

**Comment by mjturtora** [comment]
Good to know. I am using Version 52.0.2709.0 canary (64-bit) because the last version of Chrome I used had a performance issue and Canary was recommended by Google. I've wondered if it's an AMD thing.

**Comment by mjturtora** [comment]
So I just upgraded my Chrome to the latest (Version 50.0.2661.75 m (64-bit))  and I get:

WebGL not supported
NationalMap works best with a web browser that supports WebGL, including the latest versions of Google Chrome, Mozilla Firefox, Apple Safari, and Microsoft Internet Explorer. Your web browser does not appear to support WebGL, so you will see a limited, 2D-only experience.

If I try to force it (by changing to 3D) I get:

WebGL not supported or too slow
Your web browser cannot display the map in 3D, either because it does not support WebGL or because your web browser has reported that WebGL will be extremely slow. Please try a different web browser, such as the latest version of Google Chrome, Mozilla Firefox, Apple Safari, or Microsoft Internet Explorer. In some cases, you may need to upgrade your computer's video driver or operating system in order to get the 3D view in NationalMap.

**Comment by kring** [comment]
@mjturtora I see you found our gitter channel.  That's a good way to reach the TerriaJS developers:
https://gitter.im/TerriaJS/terriajs

You can also email terriajs@lists.nicta.com.au.  I'm not sure if support@terria.io is actually valid, but if you emailed it I definitely never saw the email.  You can also email me directly at the address on the web site linked from my GitHub profile.

Regarding the lack of WebGL on Chrome 50...  Try visiting `about:gpu` in Chrome to learn what's going on.  It may be that Chrome has blacklisted your GPU/driver due to a security problem.  Upgrading the driver may help.
