### ISSUE TITLE
Geoserver legends not displaying

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1445]
Currently some (at least) of our Geoserver legends are not displaying: http://bit.ly/1SOzMZD

This is what should render: 
http://geofabric.bom.gov.au/simplefeatures/ows?service=WMS&version=1.3.0&request=GetLegendGraphic&format=image/png&layer=ahgf_gwc:AHGFAquiferBoundary

**Comment by kring** [comment]
This has been fixed, the link above now shows the legend.

**Comment by stevage** [comment]
Great! (I'm loving this bug-closing blitz of yours btw :))

**Comment by kring** [comment]
Yeah I'm very happy to have some time to focus on TerriaJS again. :)
