### ISSUE TITLE
Support ArcGIS ImageServer

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1458]
Eg http://data.actmapi.act.gov.au/arcgis/rest/services/actmapi/imagery2015mga/ImageServer

(Although I can't get that one to actually show anything in Esri's online viewer.)

**Comment by meh9** [comment]
Maybe this one as a test (although I don't know where or how to use the Esri online viewer to test):

http://www.ga.gov.au/gisimg/rest/services/energy/OZTemp_Interpreted_Temperature_at_5km_Depth_Image/ImageServer/

**Comment by stevage** [comment]
Oh, here's how to view the one I posted: http://data.actmapi.act.gov.au/arcgis/rest/services/actmapi/imagery2015mga/ImageServer?f=jsapi

**Comment by stevage** [comment]
Oh, this should save us some time. :)

https://cesiumjs.org/Cesium/Build/Documentation/ArcGisMapServerImageryProvider.html

**Comment by ethoms-usgs** [comment]
Just writing to upvote. I can't use any Arctic DEM raster function layers without this.
