### ISSUE TITLE
newui: Viewing data in the preview can stop it appearing on the 2D map

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1469]
Eg. With http://localhost:3001/#build/terriajs/test/init/charts.json, add two of the csv items at the bottom to the map, then switch to 2D. Only one of them appears on the main map.
This appears to be an issue with `LeafletGeomVisualizer`, which is storing data directly on the entity (eg. the `cleanEntity` function).

**Comment by RacingTadpole** [comment]
This appears to be solved.

**Comment by kring** [comment]
Fixed by this commit to newui:
https://github.com/TerriaJS/terriajs/commit/549f6f04abfeefc67a346d9d81edc7a35485f62a
