### ISSUE TITLE
Add `parameters` attribute support to WebFeatureServiceCatalogItem

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1473]
I've run into a couple of cases where a provider has a URL that requires extra parameters, something like:

`myserver/cgi-bin/mapserv?map=/data/mapfiles/mything.map&service=wfs&...`

Our WFS and WMS catalog types strip everything after the `?` then add different properties. In the process they lose, in this instance, the `map` property.

So, either we should:
- preserve (but potentially override) all parameters specified in the init file
- have an extra property, `additionalParameters`.

**Comment by kring** [comment]
We already have option 2, it's called `parameters`.

**Comment by kring** [comment]
One caveat is that the `parameters` are only applied to `GetMap` URLs, not `GetCapabilities`.  However, you can work around that but specifying the `getCapabilitiesUrl` explicitly to include the desired parameters.

**Comment by stevage** [comment]
WebFeatureServiceCatalogItem doesn't support `parameters`, and is the actual use case that motivated this.
