### ISSUE TITLE
Implement SOS (Sensor Observation Service)

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1474]
This is a requirement for NEII Viewer (https://github.com/TerriaJS/neii-viewer/issues/2).

The standard: http://www.opengeospatial.org/standards/sos

The target endpoint: http://www.bom.gov.au/waterdata/services?service=SOS&version=2.0&request=GetCapabilities

**Comment by stevage** [comment]
Taking some notes here:
- GetCapabilities returns list of sensors, so we have a SOSCatalogGroup and SOSCatalogItem
- DescribeSensor - maybe, like DescribeLayer
- GetObservation - the main way of getting data.

Optional:
- GetObservationById (not implemented by BOM)
- GetFeatureOfInterest  (is implemenetd by BOM)

This is almost a valid query: `http://www.bom.gov.au/waterdata/services?datasource=0&service=SOS&request=GetObservation&temporalFilter=phenomenonTime,2016-07-01/2016-07-02`

**Comment by stevage** [comment]
This is a valid query: http://www.bom.gov.au/waterdata/services?datasource=0&service=SOS&request=GetObservation&temporalFilter=phenomenonTime,2016-07-01/2016-07-02&offering=http://bom.gov.au/waterdata/services/tstypes/Year.Mean

The `offering` property corresponds to the `swes:identifier` attribute in `<swes:offering>`

**Comment by RacingTadpole** [comment]
Btw, the SDMX-JSON catalog item may be a useful reference.
A rough overview:
- [CsvCatalogItem](https://github.com/TerriaJS/terriajs/blob/master/lib/Models/CsvCatalogItem.js#L510) checks for lat/lon and regions, and if it finds none, adds its tableStructure to the chartableItems list
- [TableStructure actually extends Concept](https://github.com/TerriaJS/terriajs/blob/master/lib/Map/TableStructure.js#L45), so by default, when you see a csv catalog item, [the concepts match the columns](https://github.com/TerriaJS/terriajs/blob/master/lib/Models/CsvCatalogItem.js#L128-L136).
- SdmxJsonCatalogItem extends CsvCatalogItem, but changes the concepts it shows, and adjusts its tableStructure based on which concepts are selected.
- AbsItt does something similar but it’s more complicated because there’s a hierarchy of concepts.

But there’s no need to extend CsvCatalogItem if it doesn’t make sense. You can build a tableStructure from your own catalog item too.

**Comment by stevage** [comment]
I should have read this BOM documentation first:

You can now use Web Services for Water Data Online to access water data.

A Sensor Observation Service standard version 2 (SOS2) has been implemented; the service returns data in WaterML2 format. The SOS2 standard was developed by the Open Geospatial Consortium (OGC) as part of the OGC Sensor Web Enablement framework. The WaterML2 standard was also developed by the OGC with support from the Bureau of Meteorology and CSIRO though the WIRADA research alliance.

Access Point (URL)

SOS2 web services for Water Data Online can be accessed at www.bom.gov.au/waterdata/services?service=SOS&version=2.0&request=GetCapabilities

Workflow Example

This example describes how SOS2 requests can be used to retrieve observations (e.g. watercourse discharge time series values) for a location/area and time period. 

## Step 1-See what information the service can provide using the GetCapabilities request.

Example GetCapabilities request 
Example GetCapabilities response

When interpreting the response, note that:

Each swes:observableProperty corresponds to a Water Data Online parameter that you can access via SOS, for example Water Course Discharge.
Each sos:ObservationOffering contains a type of Water Data Online time series that you can access via SOS. These are listed under swes:procedure.

The procedure or time series type defines the method used to produce time series data. For example, a time series produced using the Day.Mean procedure contains values calculated as the daily mean of a station's measurements over a day. The day is defined as starting at 12am and ending at 12pm. A missing value is recorded for the daily mean if the period for which there are measurements covers less than 90% of the day.

## Step 2- Find stations using the GetFeatureOfInterest request

Example GetFeatureOfInterest request 
Example GetFeatureOfInterest response

You can specify a combination of (optional) filters to select the stations you require: 

Use sos:procedure to select stations that record measurements using a particular method.
Use sos:observedProperty to select stations that record measurements for a specific parameter.
Use sos:spatialFilter to select stations within a specified geographical area.

Take note of each station's gml:identifier, this is needed in the next step.

## Step 3- Retrieve time series data by performing a GetObservation request

Example GetObservation request 
Example GetObservation response

You can select time series data to return using a combination of (optional) filters: 

Use sos:procedure to select the time series type
Use sos:observedProperty to select the parameter.
Use any number of sos:featureOfInterest identifiers (see gml:identifier values from Step 2) to specify which stations you need the time series data for.
Use sos:temporalFilter to specify the time period for which data is to be provided.

**Comment by stevage** [comment]
So far I've implemented most of the "talk to SOS and navigate through the XML" part. Over to someone else to turn that into charts and maps :)

Test init file here: https://github.com/TerriaJS/terriajs/blob/sos/wwwroot/test/init/sos.json

Code here:

https://github.com/TerriaJS/terriajs/blob/sos/lib/Models/SensorObservationServiceCatalogGroup.js and https://github.com/TerriaJS/terriajs/blob/sos/lib/Models/SensorObservationServiceCatalogItem.js

More useful links:

https://wiki.52north.org/SensorWeb/SensorObservationServiceIVDocumentation
http://sensor-widgets.readthedocs.io/en/latest/sos.html
http://www.ogcnetwork.net/sos_2_0/tutorial/capabilities
http://www.ogcnetwork.net/SOS_Intro
http://specs.okfnlabs.org/reference/ogc/protocols/sos.html

**Comment by RacingTadpole** [comment]
Hmm. The URL http://www.bom.gov.au/waterdata/services seems to provide:
- `GetCapabilities`: contains a list of 148 "offerings", which are related collections of sensor observations. From the specs, "If two sensors are located on weather stations that are far apart in space or which report during non-overlapping time periods, then they should probably be factored into two distinct offerings." (You're showing these offerings as catalog items under the group, which seems like a good idea.)
- `GetFeatureOfInterest`: Returns [8052 features](http://www.bom.gov.au/waterdata/services?service=SOS&version=2.0&request=GetFeatureOfInterest), with their locations and identifiers (such as `http://bom.gov.au/waterdata/services/stations/000608`), but not the offering they come from. Adding an "offering" parameter to this has no effect on the result (eg. [with a non-existent offering](http://localhost:3003/proxy/_1d/http://www.bom.gov.au/waterdata/services?service=SOS&version=2.0&request=GetFeatureOfInterest&offering=rubbish)).
- `GetObservation`: For a given offering, returns a single time series of observations (example [here](http://www.bom.gov.au/waterdata/services?service=SOS&version=2.0&request=GetObservation&offering=http%3A%2F%2Fbom.gov.au%2Fwaterdata%2Fservices%2Ftstypes%2FMonth.Mean&procedure=http%3A%2F%2Fbom.gov.au%2Fwaterdata%2Fservices%2Ftstypes%2FMonth.Mean)). But - I cannot find what feature this corresponds to! And why is it only one? The `featureOfInterest`'s `xlink:href` is all it gives us, and that is a meaningless `http://bom.gov.au/waterdata/services/stations/system`. Alternatively, if I provide the request with a `featureOfInterest` parameter (which the specs say is ok), I get nothing (example [here](http://www.bom.gov.au/waterdata/services?service=SOS&version=2.0&request=GetObservation&offering=http%3A%2F%2Fbom.gov.au%2Fwaterdata%2Fservices%2Ftstypes%2FMonth.Mean&featureOfInterest=http%3A%2F%2Fbom.gov.au%2Fwaterdata%2Fservices%2Fstations%2F401229)).
- `GetDataAvailability`: For a given offering, returns "features of interest" (34 in the case of [Month.Mean](http://localhost:3003/proxy/_1d/http://www.bom.gov.au/waterdata/services?service=SOS&version=2.0&request=GetDataAvailability&offering=http%3A%2F%2Fbom.gov.au%2Fwaterdata%2Fservices%2Ftstypes%2FMonth.Mean&procedure=http%3A%2F%2Fbom.gov.au%2Fwaterdata%2Fservices%2Ftstypes%2FMonth.Mean)). It returns for each a time period that observations are available, but not the observations themselves.

I would like to create a simple table with these columns (for a given offering):
`FeatureId, Date, Lat, Lon, Value`.
(We could even add `offering` as another column and show them all at once.)

But I'm struggling to work out how to get the observation values for each feature!

**Comment by RacingTadpole** [comment]
@stevage: I can't find the original online of the BOM documentation you refer to above - can you point me to it? Maybe the examples it refers to (whose links have not survived above) would help. Thanks.

**Comment by stevage** [comment]
Yeah, annoyingly, BOM's site doesn't do URLs.
1. http://www.bom.gov.au/waterdata/
2. FAQ
3. Web Services for Water Data Online

**Comment by RacingTadpole** [comment]
@stevage: Do you have any thoughts on how we could grab the info to build a table with these columns:

`FeatureId, Date, Lat, Lon, Value.`

?

**Comment by RacingTadpole** [comment]
Murray Henderson at BoM has helped me out with this explanation:

> The SOS2.0 services uses the SOAP protocol, which means that you can't just visit a URL, you need to send a SOAP request to the server.
> SOAP requests are HTTP POST requests containing a SOAP document as the body of the request. You don't need special tools to send these requests, you can just use any old HTTP tool.
> For example, to get the example GetObservationRequest.xml document working, something like this should work:
> curl --header "Content-Type: text/xml;charset=UTF-8" --data @GetObservationRequest.xml http://www.bom.gov.au/waterdata/services?service=SOS
> 
> With comments:
> 
> curl                                                  # cURL is a command line HTTP tool: https://curl.haxx.se/download.html
> --header "Content-Type: text/xml;charset=UTF-8"       # Our HTTP request contains XML data
> --data @GetObservationRequest.xml                     # Our XML data is loaded from the file. Since we're sending data, cURL automatically uses the HTTP POST method (instead of the default HTTP GET method)
> http://www.bom.gov.au/waterdata/services?service=SOS  # The SOS2.0 endpoint URL -- this never changes, only the SOAP documents that we send to the server change
> 
> Then you tweak the contents of the GetObservationRequest.xml document to your needs (adding or removing filters as necessary).

There's an example GetObservationRequest.xml on that "Web Services for Water Data Online" link above.

**Comment by stevage** [comment]
Woot! :)
