### ISSUE TITLE
Criteria Selection Title

### ISSUE THREAD

**Issue by hilarycinis** [TerriaJS/terriajs#1480]
Please add a title to the legend that explains which of the criteria selected
Assists users digesting the data in context

(mock not supplied, image is context reference only)

![screen shot 2016-04-12 at 1 53 06 pm](https://cloud.githubusercontent.com/assets/6046521/14947521/2d6d6c74-1078-11e6-89f1-513468472742.png)

**Comment by kring** [comment]
Terria analytics are now demo-only.
