### ISSUE TITLE
Don't show an error when preview map fails in NewUI

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1481]
There are some instances where we fail to show a layer on the preview map but we can still show the layer in Cesium. In these cases we should not show an error message, just "No preview available". I seem to remember that this may already be available, maybe my case just needs to be added to that.

In AREMI NewUI, when trying to preview the layer Renewable Energy -> Geothermal -> "Temperature at 5k", and the layer "Thermal wells", we get an error message saying they don't support Web Mercator (EPSG:3857) projection.

**Comment by kring** [comment]
Fixed in 86f04aec86585783195bbc3055f3a96e9a931af7 and 6c130d7ce4a5c1208abefb448fc7d337b52976d7.
