### ISSUE TITLE
Not all layers show a preview in the NewUI

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1482]
In AREMI we have some layers that do not show up in the preview map even though they are large colourful raster layers that could be expected to show:

Renewable Energy -> Wave -> Bathymetry
Renewable Energy -> Wave -> Bathymetry
Renewable Energy -> Solar -> Annual climatology of daily exposure - *
Renewable Energy -> Wind -> *
Infrastructure -> Communications -> Broadband *

Interestingly, for the ones I've checked, we do get a tile which has the preview data, but it's not being displayed.

**Comment by kring** [comment]
I don't see any problem with these layers in Terrarium, so I'm closing this.  Reopen if you still see it.

**Comment by meh9** [comment]
They now show up! :)
