### ISSUE TITLE
Restrict data sets available for each analytic "story"

### ISSUE THREAD

**Issue by hilarycinis** [TerriaJS/terriajs#1485]
When the user activates an analytics "story" ensure the:
- Region Type
- Region
- a call to action to add Census only data 

are all tightly constrained in each of the three analytics selection modals. 

This solves the problems of
- identifying the right Region type and region
- locating the only data that will work

And will prevent errors and frustrations and will encourage use.

**Comment by kring** [comment]
I'm closing this becacuse the Terria analytics are "demo only" at this point.
