### ISSUE TITLE
Missing South Sudan in country boundary dataset

### ISSUE THREAD

**Issue by disruptivegeo** [TerriaJS/terriajs#1486]
The country boundaries file used in the global risk map application is missing the country of South Sudan. Visible when viewing the "GDP per Capita" dataset. 

http://globalriskmap.nicta.com.au/#start=%7B%22version%22%3A%220.0.05%22%2C%22initSources%22%3A%5B%22init%2Fun.json%22%2C%7B%22sharedCatalogMembers%22%3A%7B%22Root%20Group%2FNatural%20Hazard%22%3A%7B%22isOpen%22%3Atrue%2C%22type%22%3A%22group%22%2C%22parents%22%3A%5B%5D%7D%2C%22Root%20Group%2FNatural%20Hazard%2FPeril%20Exposure%22%3A%7B%22isOpen%22%3Atrue%2C%22type%22%3A%22group%22%2C%22parents%22%3A%5B%22Root%20Group%2FNatural%20Hazard%22%5D%7D%2C%22Root%20Group%2FNatural%20Hazard%2FPeril%20Exposure%2FSocial%20Exposure%22%3A%7B%22isOpen%22%3Atrue%2C%22type%22%3A%22group%22%2C%22parents%22%3A%5B%22Root%20Group%2FNatural%20Hazard%22%2C%22Root%20Group%2FNatural%20Hazard%2FPeril%20Exposure%22%5D%7D%2C%22Root%20Group%2FExposure%22%3A%7B%22isOpen%22%3Atrue%2C%22type%22%3A%22group%22%2C%22parents%22%3A%5B%5D%7D%2C%22Root%20Group%2FEconomic%20Vulnerability%22%3A%7B%22isOpen%22%3Atrue%2C%22type%22%3A%22group%22%2C%22parents%22%3A%5B%5D%7D%2C%22Root%20Group%2FEconomic%20Vulnerability%2FGDP%20per%20capita%22%3A%7B%22nowViewingIndex%22%3A0%2C%22isEnabled%22%3Atrue%2C%22isShown%22%3Atrue%2C%22isLegendVisible%22%3Atrue%2C%22opacity%22%3A0.4%2C%22keepOnTop%22%3Afalse%2C%22disableUserChanges%22%3Atrue%2C%22tableStyle%22%3A%7B%22maxDisplayValue%22%3A50000%2C%22scale%22%3A1%2C%22colorBins%22%3A7%2C%22colorBinMethod%22%3A%22auto%22%2C%22colorMap%22%3A%5B%7B%22offset%22%3A0%2C%22color%22%3A%22rgba(200%2C0%2C0%2C1.00)%22%7D%2C%7B%22offset%22%3A0.5%2C%22color%22%3A%22rgba(200%2C200%2C200%2C1.00)%22%7D%2C%7B%22offset%22%3A1%2C%22color%22%3A%22rgba(0%2C0%2C200%2C1.0)%22%7D%5D%2C%22legendTicks%22%3A3%2C%22regionVariable%22%3A%22ISO3%22%2C%22regionType%22%3A%22CNT3%22%2C%22dataVariable%22%3A%22GDP%20per%20capita%22%7D%2C%22type%22%3A%22csv%22%2C%22parents%22%3A%5B%22Root%20Group%2FEconomic%20Vulnerability%22%5D%7D%2C%22Root%20Group%2FSocial%20Vulnerability%22%3A%7B%22isOpen%22%3Atrue%2C%22type%22%3A%22group%22%2C%22parents%22%3A%5B%5D%7D%2C%22Root%20Group%2FResilience%22%3A%7B%22isOpen%22%3Atrue%2C%22type%22%3A%22group%22%2C%22parents%22%3A%5B%5D%7D%7D%7D%2C%7B%22initialCamera%22%3A%7B%22west%22%3A7.070308560064887%2C%22south%22%3A-6.422561496070782%2C%22east%22%3A71.46891860238672%2C%22north%22%3A21.923008777277513%2C%22position%22%3A%7B%22x%22%3A9875325.990827948%2C%22y%22%3A8077600.369884408%2C%22z%22%3A2066716.2586568596%7D%2C%22direction%22%3A%7B%22x%22%3A-0.7634704832054955%2C%22y%22%3A-0.6247491594275931%2C%22z%22%3A-0.1637110535923338%7D%2C%22up%22%3A%7B%22x%22%3A-0.15988158901780128%2C%22y%22%3A-0.06276634442155989%2C%22z%22%3A0.9851387026217749%7D%7D%2C%22homeCamera%22%3A%7B%22west%22%3A10%2C%22south%22%3A0%2C%22east%22%3A119.99999999999999%2C%22north%22%3A70%7D%2C%22baseMapName%22%3A%22Natural%20Earth%20II%22%2C%22viewerMode%22%3A%223d%22%7D%5D%7D&hideExplorerPanel=1&activeTabId=Search

**Comment by tephenavies** [comment]
The dataset that we get country border from [`TM_WORLD_BORDERS`](http://thematicmapping.org/downloads/world_borders.php) has not been updated since 2008. We could feasibly update these borders if we had the data (a Shapefile with current borders for each country along with country names and ISO codes), but this is unlikely to be a priority since AFAIK we don't have any current TerriaJS deployments that need world borders.

**Comment by kring** [comment]
I'm closing this because it's not a TerriaJS issue.
