### ISSUE TITLE
Can't get info about a polygon

### ISSUE THREAD

**Issue by pljplj** [TerriaJS/terriajs#1488]
I added CSV data with US States as the regions.  I can click on the a state exactly 2 times before it stops giving me information about the region on which I click on

**Comment by tephenavies** [comment]
Hi @pljplj. Which site is this on? I tried reproducing the problem with the csv:

```
US_state,Value
NC,6
WA,7
```

on http://nationalmap.research.nicta.com.au/terriamap/ but didn't have any problems with feature information after clicking different regions multiple times, or clicking the same region multiple times.

**Comment by stevage** [comment]
I think it was probably on the URL you gave. I did see this. From memory, it was Chrome. Not sure if Leaflet or Cesium.

**Comment by kring** [comment]
This is almost certainly caused by #1496, which was just fixed.  Please reopen if you still see it.
