### ISSUE TITLE
'Go to my location' broken in Chrome

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#1493]
'Go to my location' button is unresponsive when clicked (browser location permissions double checked in Google Maps) 

URL: http://newui.aremi.nicta.com.au/renewables/
Browser: Chrome 50.0.2661.86 (64-bit)

**Comment by meh9** [comment]
The console shows this:

`getCurrentPosition() and watchPosition() are deprecated on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.`

Apparently this is from Chrome v50.

**Comment by kring** [comment]
This is working fine for me on Chrome v50.0.2661.102 on Linux.  Is anyone still seeing a problem?  I did have to confirm that it's allowed to use my location.  If you previously denied it, it might not ask again.  I'm closing this, but reopen if you still see it.

**Comment by meh9** [comment]
Yeah, this is still a thing.

I'm now on Chrome Version 51.0.2704.54 beta (64-bit).

The link in the message has more info: https://goo.gl/rStTGz

**Comment by AlexGilleran** [comment]
So is the resolution for this hiding it unless you're on https?

**Comment by meh9** [comment]
I assume so, but I don't know why @kring isn't having this problem.

**Comment by kring** [comment]
I was testing on localhost.  So either that's considered a secure origin (more likely), or we've fixed something since the version on http://newui.aremi.nicta.com.au/renewables/ (less likely).

**Comment by stevage** [comment]
Ah, it looks like Chrome finally removed geolocation over HTTP in version 50. Damn.

https://bugs.chromium.org/p/chromium/issues/detail?id=561641

(And yes, localhost is considered secure)

Next question: what do we do about it? How hard is it to deploy as HTTPS?

**Comment by kring** [comment]
@chloeleichen let's just hide the "Go to my location" button on non-HTTPS connections.  If we can get the API to tell us whether it will work, rather than looking for https in the URL, that's even better.

**Comment by chloeleichen** [comment]
i'm on it
