### ISSUE TITLE
NewUI: Switch to 2D terrain causes the basemap to continually refresh.

### ISSUE THREAD

**Issue by ajbar7** [TerriaJS/terriajs#1495]
Not sure how to best describe this and I could only get this to fail once per machine I tested on but when I zoom in [rapidly on this map](http://newui.aremi.nicta.com.au/renewables/#share=RG4zLK) and manage to get the 'unresponsive terrain server' message it causes the basemap to go into an endless refresh loop.

**Comment by kring** [comment]
This was almost certainly a Cesium bug (AnalyticalGraphicsInc/cesium#3696) that was fixed in 1.20, which is now included in TerriaJS.  Let me know if you still see it.
