### ISSUE TITLE
Csv feature selection broken in Leaflet 0.7.7

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#1496]
Issue #1121 has reoccured because Leaflet has been updated from 0.7.3 to 0.7.7.

To reproduce, open any csv region mapped layer (such as `ABS -> 2011 Census -> Age` or `#test -> Region Mapped (CSV) -> 2011 Census AUST (SA4)`), switch to 2D mode and click on regions a few times. Only the first 2 clicks regiester.
![leaflet 0 7 7 feature selection](https://cloud.githubusercontent.com/assets/13863530/15008349/1139f53e-1223-11e6-9c05-b5ff34f88ce5.gif)

The previous fix #1151 was to downgrade Leaflet to 0.7.3, so to fix we could try either:
- Reverting to Leaflet 0.7.3 or 
- Fixing the underlying issue (if we need Leaflet 0.7.7)

**Comment by steve9164** [comment]
Here's a comparison between Leaflet 0.7.3:
![leaflet 0 7 3](https://cloud.githubusercontent.com/assets/13863530/15167958/636e8728-1770-11e6-89b6-e057eba4859b.gif)
And Leaflet 0.7.7:
![leaflet 0 7 7](https://cloud.githubusercontent.com/assets/13863530/15167959/642e01c0-1770-11e6-8fd4-642dcf4593d9.gif)
