### ISSUE TITLE
CSV does not ignore empty rows

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1504]
When a CSV file have some number of empty rows these are not ignored, causing "No Value" entries to appear in the legend even though all other rows have data for the display variable being used.

**Comment by RacingTadpole** [comment]
Ah, right. We have a test that runs on the file https://github.com/TerriaJS/terriajs/blob/master/wwwroot/test/csv/blank_line.csv. It only shows two dots on the map, but you're right, it shows "(No value)" in the legend. Is that what you mean?

**Comment by meh9** [comment]
Yeah, exactly that. We should just completely ignore empty rows if possible.
