### ISSUE TITLE
Feature Info: toggle between curated data and raw data

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#1506]
Currently users click 'show raw data' in the feature info panel and this will reveal all associated key-value pairs underneath the existing curated list. This results in unnecessary key/value and download duplication.

Proposed solution:
Show either curated feature info or raw feature, but not both at the same time. Provide a button to toggle between this view states. Always default to curated feature info.

**Comment by chloeleichen** [comment]
<img width="585" alt="screen shot 2016-07-25 at 10 49 10 am" src="https://cloud.githubusercontent.com/assets/7508939/17087819/8930d2de-5255-11e6-818d-51b5f11b3414.png">
<img width="797" alt="screen shot 2016-07-25 at 10 49 19 am" src="https://cloud.githubusercontent.com/assets/7508939/17087820/89329024-5255-11e6-91df-f827e9d5b497.png">
