### ISSUE TITLE
Allow users to select WMS ELEVATION and other dimensions

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#1512]
When WMS `getCapabilities` advertise a list of `ELEVATION` values, allow user to select from available `ELEVATION` values in a dropdown list.

**Comment by rsignell-usgs** [comment]
@kring or @stevage , please add this issue to the CDI milestone 
https://github.com/TerriaJS/terriajs/milestone/17

**Comment by rsignell-usgs** [comment]
BTW, this is a WMS standard, not a ncWMS extension -- the available values of Elevation are advertised via the `getCapabilities` request.   For example, in this request:
http://geoport-dev.whoi.edu/thredds/wms/coawst_4/use/fmrc/coawst_4_use_best.ncd?service=WMS&version=1.3.0&request=GetCapabilities
the available elevation values are shown as:

```
<Dimension name="elevation" units="" default="-0.03125">
-0.96875,-0.90625,-0.84375,-0.78125,-0.71875,-0.65625,-0.59375,-0.53125,-0.46875,-0.40625,-0.34375,-0.28125,-0.21875,-0.15625,-0.09375,-0.03125
</Dimension>
```

**Comment by rsignell-usgs** [comment]
@kring, this is the last issue that we would really like to get resolved before our CDI Proposal Final Report is due on Oct 21.    Do you think that is possible, or is that unrealistic?

**Comment by kring** [comment]
Definitely possible!  I'm working on it now.

**Comment by rsignell-usgs** [comment]
I'm testing the `selectWMSElevation` branch on my instance here:
http://gamone.whoi.edu/terriajs/#build/TerriaJS/test/init/wms.json
and I can select elevation, style from dropdowns, change the COLORSCALERANGE, change timestep using the dataset listed as `ncWMS with multiple dimensions, including time`.  Awesome!

However, when I select the dataset listed as `ncWMS2 with multiple styles`, I can select the style via dropdown, but I'm not seeing the color legend and not getting the `COLORSCALERANGE` widget so that I can change the colorscale.  
![2016-10-11_7-23-53](https://cloud.githubusercontent.com/assets/1872600/19268860/fb362926-8f84-11e6-8cc3-c5364bb1b819.jpg)

Is the COLORSCALERANGE perhaps not currently working for ncWMS2 endpoints?

Also, I'm only seeing a few of the available styles for this ncWMS2 endpoint.  Was this limited to just a few for testing or something?
![2016-10-11_7-24-33](https://cloud.githubusercontent.com/assets/1872600/19273889/32ad00b6-8f9c-11e6-9bed-1806b549fd5b.png)

**Comment by kring** [comment]
> Is the COLORSCALERANGE perhaps not currently working for ncWMS2 endpoints?

Yeah we're not currently detecting ncWMS2 as a thing that supports COLORSCALERANGE.  That's covered by #1976, and I'll try to fix it today.

> Also, I'm only seeing a few of the available styles for this ncWMS2 endpoint. Was this limited to just a few for testing or something?

I see 9 styles in the UI, and 9 in GetCapabilities for that layer:
http://www.smast.umassd.edu:8080/ncWMS2/wms?service=WMS&version=1.3.0&request=GetCapabilities

What styles are you expecting to see that are missing?

**Comment by rsignell-usgs** [comment]
Ugh.  I guess in ncWMS2 the palettes are not listed explicitly as styles in the getCaps.   They are instead listed in the style _abstract_, like `x-Occam, x-Occam-inv, x-Rainbow,...`   

Here's an example:
http://www.smast.umassd.edu:8080/ncWMS2/wms?FORMAT=image%2Fpng&TRANSPARENT=TRUE&STYLES=default-scalar%2Fx-Rainbow&LAYERS=FVCOM-NECOFS-GOM3%2Ftemp&TIME=2016-10-12T01%3A58%3A07.500Z&ELEVATION=0&COLORSCALERANGE=4.304%2C27.6&NUMCOLORBANDS=250&ABOVEMAXCOLOR=0x000000&BELOWMINCOLOR=0x000000&BGCOLOR=transparent&LOGSCALE=false&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG%3A4326&BBOX=-70.715234374995,38.570312500006,-64.286718749995,44.998828125006&WIDTH=256&HEIGHT=256

**Comment by rsignell-usgs** [comment]
Yet another WMS extension by ncWMS2, but one we need to handle, I guess by parsing the abstract, which kind of sucks.    But we can't just strand users with those horrible default palettes.  :disappointed:

**Comment by kring** [comment]
So only a subset of the available palettes are listed as actual styles?  That's so strange.  So yeah I guess we can parse the Abstract.  That seems pretty dodgy though!

**Comment by RacingTadpole** [comment]
Sorry - this closed automatically when I merged Kevin's PR. I'll reopen it for this extension.

**Comment by rsignell-usgs** [comment]
I'm going to close and reopen palette selection as a separate issue.
