### ISSUE TITLE
Implement SDMX-JSON catalog item

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1514]
SDMX is the standard used by the OECD and many statistical agencies, including the Australian Bureau of Statistics (ABS). The ABS is implementing SDMX-JSON.

Useful links include:
- [OECD API Documentation](https://data.oecd.org/api/sdmx-json-documentation/)
- [OECD query builder](http://stats.oecd.org/sdmx-json)
- [The Technical Standards Working Group's guide to SDMX-JSON, with examples](https://github.com/sdmx-twg/sdmx-json/blob/master/data-message/docs)
- [Official SDMX website](https://sdmx.org/)
- [ECB SDMX RESTful web service](https://sdw-wsrest.ecb.europa.eu/)
- [Introduction to SDMX-JSON (slides)](http://airosa.github.io/sdmx-prototype-json/sdmxjson-intro-slides/)

**Comment by RacingTadpole** [comment]
@sosna, @airosa: Hi, @tobybellwood suggested I get in contact with you. I'm implementing an SDMX-JSON reader in TerriaJS, which underlies nationalmap.gov.au, so that we can display statistical agencies' data - in particular Australian Bureau of Statistics data - on a map.

We currently use an unsupported API for the ABS data; you can see an example using this API at http://nationalmap.gov.au/#share=JBZ9pC.

The SDMX-JSON-reading code so far is at: https://github.com/TerriaJS/terriajs/blob/1514_sdmx/lib/Models/SdmxJsonCatalogItem.js

The idea is the reader can either handle a specific endpoint like `http://stats.oecd.org/sdmx-json/data/QNA/.B1_GE.VOBARSA.A/all`, or an open-ended one like `http://stats.oecd.org/sdmx-json/data/QNA`. In the latter case it uses `http://stats.oecd.org/sdmx-json/dataflow/QNA` to identify the structure of the data first.  It then identifies time and region concepts and treats those specially.

The main outstanding features I'd still like to implement are passing through `attributes` like units, handling potentially hierarchical dimensions, and knowing when the data can be meaningfully divided by regional population to show a %.

Do you have any advice or suggestions?

**Comment by sosna** [comment]
This project looks very interesting :)

Regarding attributes like unit, do you mean that you want to know which attribute contains, say, the unit information, regardless of how the attribute is actually called? If that's the use case, then something like the `concept role` would be useful (it's an property which can be attached to any component, i.e. dimension or attribute). Concept roles are maintained in a dedicated concept scheme and it's considered good practice to use the SDMX cross-domain concepts.

Regarding the hierarchies, you could either express simple hierarchies directly in the codelist. If you need something more complex (for example, where a child item can belong to several parents), you'd need to use a hierarchical codelist. However, it is currently not possible to use a hierarchical codelist directly in a DSD, which means that you would need to link the 2 using `annotations`.

Regarding your last point, the only option I can think of is again to use `annotations` but @airosa may have a better idea.

I hope this helps a bit.

**Comment by chris-beer** [comment]
cc @dosse @bertrand-riviere - Please do jump in and assist (as I'm not currently at liberty to directly contribute) - TerriaJS may well be a perfect drop in map replacement for https://github.com/cis-itn-oecd .Stat work, plus (@dosse ) - it's also an immediate potential in the wild implementation of either a full or .Stat SDMX-JSON API/service

**Comment by RacingTadpole** [comment]
Thanks @sosna and @chris-beer!

**Comment by airosa** [comment]
Hi Arthur,

Just to let you know that I have been busy preparing a sdmx-twg meeting and
did not yet have time to look into your question in detail.

For the background the current sdmx-json includes both the structure and
data for your request. The basic idea was that combining both in the same
message would be the best solution for data visualization. However your use
case may require more information than is currently supported directly in
the sdmx-json data message. Annotations is the general mechanism for adding
more information to the data message as Xavier mentioned.

We are also working on separate json structure messages but more for
supporting data discovery.

Cheers
Sami

**Comment by RacingTadpole** [comment]
Hi Sami,

To get at the structure without loading in all the data, I found replacing `/data/` in the path with `/dataflow/` works well enough. I haven't seen that path documented though - is it part of the spec?

I also tried adding `?detail=noData` to the `/data/` path (eg. http://stats.oecd.org/sdmx-json/data/QNA/.B1_GE.VOBARSA.Q/all?detail=noData), but that responds with all the data set to `null` (ie. the download size is similar to with all the data).

Thanks again!

**Comment by chris-beer** [comment]
Hi Arthur, all

Indeed it is part of the spec, and correct - the .Stat SDMX-JSON API
(@OECD) documentation does indeed make no mention of it - I'll raise this
as an issue at the OECD/.Stat end (since it's out of Sami's space when we
get to the .Stat implementation specifically)

Cheers

Chris

Chris Beer
Lead (Data Services & APIs) - Dissemination Enterprise Wide Services
Statistical Business Transformation Program  | Australian Bureau of
Statistics
  +61 2 6252 5614
  chris.beer@abs.gov.au     www.abs.gov.au

The Australian Bureau of Statistics acknowledges the traditional custodians
of country throughout Australia and recognises their continuing connection
to land, waters and community. We pay our respects to them and their
cultures, and elders, both past and present

**Comment by sosna** [comment]
Yes, it's part of the SDMX spec.

You can get data using the `data` resource, or the metadata using any of the supported metadata resources (like `dataflow`, `datastructure`, etc.).

For example:
- Get information about the BKN dataflow: http://sdw-wsrest.ecb.int/service/dataflow/ECB/BKN
- BKN dataflow along with the concepts and codelists it uses: http://sdw-wsrest.ecb.int/service/dataflow/ECB/BKN?references=descendants
- BKN dataflow along with the concepts and codelists it uses, and its constraints (expressed as cube regions): http://sdw-wsrest.ecb.int/service/dataflow/ECB/BKN?references=all. 

However, when faced with cube regions, you actually have no guarantee to have data for all possible combinations of dimension values.

To find exactly for which indicators there are data, you can use a `data` query along with the `detail` attribute: http://sdw-wsrest.ecb.int/service/data/BKN?detail=serieskeysonly. If you need the attributes as well, you can use `detail` with a value of `nodata`: http://sdw-wsrest.ecb.int/service/data/BKN?detail=nodata

This is what the SDMX spec says but there is no guarantee that it's supported by all implementers.

**Comment by RacingTadpole** [comment]
@airosa - am I right that https://github.com/airosa/sdmxjsonlib was last updated 2 years ago - can I ask your advice on whether you recommend using this library, given it's labelled "experimental"? :-)

Specifically, unfortunately I didn't see that library until after I had written the code to read in SDMX-JSON myself. And I only wrote it to handle the cases I knew about, ie. with data in `dataSets[0].series[key].observations[timeIndex][0]` and structure info in `structure.dimensions.series`.
I'm now discovering other sdmx-json files with data in `dataSets[0].observations[key]` (and differently formatted) and structure info in `structure.dimensions.observation`. Also the keys now include the time_period index, where earlier examples I'd looked at did not.  It looks like your library handles this.

Looking at your library, I could use something like:

```
sdmxJsonLib.response.prepare(json);
var components = sdmxJsonLib.response.mapComponentsToArray(json);
var dataSets = sdmxJsonLib.response.mapDataSetsToArray(json);
```

Thanks!

**Comment by RacingTadpole** [comment]
Also, @kalessine pointed me to his SDMX (the XML version) repo at https://github.com/kalessine/sdmx-js. You can see it live at https://rawgit.com/kalessine/sdmx-js/master/public_html/test.html.

**Comment by chris-beer** [comment]
FWIW - Some of us ABS peeps (me, plus esp our staff in WA) have been long time fans of @kalessine 's work - definitely a person you should do cool things with. :)
