### ISSUE TITLE
Entity behaviour during Leaflet zoom

### ISSUE THREAD

**Issue by rdengate** [TerriaJS/terriajs#1515]
If you zoom out with points/polygons/lines on screen in Leaflet, they fly to the upper left corner. When zooming in they disappear briefly which looks much more normal.

I will be putting up a demo and once this is up I will add steps to reproduce here, as it's not easy to reproduce without the measure tool.

**Comment by rdengate** [comment]
Ok, so after some changes (including to leaflet version?) the behaviour is now that the polygon goes from fillOpacity 0.25 to 1.0 during zoom. This doesn't happen during pan. It also doesn't happen with a geojson polygon dragged onto the map, or if the drawn polygon has hardcoded positions, so it's something to do with the CallbackProperty being used to define positions.

To reproduce:
- Use rd_newui_measure with commit dacc4a8f6554da0e95bbacfb08736715c2d75aaf with nationalmap commit 30cd4a789b61d2fdca2ecc4e32bcd4e4a8e37cbe.
- Switch to 2D mode.
- Draw a polygon
- Zoom out
- Notice how the opacity of the polygon changes while the zoom is in progress.

**Comment by rdengate** [comment]
This might be related: https://github.com/AnalyticalGraphicsInc/cesium/issues/3945

**Comment by kring** [comment]
I can't find a way to interactively draw polygons anymore. Is there a way to do it with the measure tool? I'm going to close this because there's no issue in other polygons cases.
