### ISSUE TITLE
Can't draw more points in Leaflet

### ISSUE THREAD

**Issue by rdengate** [TerriaJS/terriajs#1516]
Once the points/polygons/lines from the measuring tool are cleared from Leaflet, no more can be drawn. It seems like the events in Leaflet which handle the user clicking (map.on('click') and this.scene.featureClicked) stop firing. Possibly related to #1496/#1488.

Again, will provide link to a demo once this is up.

**Comment by kring** [comment]
It's very likely that this was fixed along with #1496 or #1469, which are both now fixed in `newui`.  Can you try it and let me know?  Because the fix for #1496 was a change in Leaflet version, do this from both TerriaJS and NM:

```
npm uninstall leaflet
npm install
```

Then do:

```
npm list leaflet
```

and make sure only 0.7.3 exists anywhere.

**Comment by rdengate** [comment]
Sorry for my late response. I've fixed up my Github email so my emails no longer go to a folder where I ignore them. 

This has changed the problem. After clearing the points/lines/polygons, I can restart the measuring tool and put down a single point. I can't draw any more points after that first point, but if I close the measuring tool and reopen it I can draw the single point again. Very strange. I will look into this more.

**Comment by rdengate** [comment]
Fixed in PR #1549
