### ISSUE TITLE
Can't pick existing Entity in Leaflet

### ISSUE THREAD

**Issue by rdengate** [TerriaJS/terriajs#1517]
When an existing Entity is clicked in Leaflet, pickedFeatures does not contain this entity. In the measuring tool this makes it impossible to close the polygon in Leaflet. It seems that 'click' (which calls pickFeatures) gets triggered first, but that looks in the datastructure populated by this.scene.featureClicked (a cesium event which calls featurePicked) which is called second. So the datastructure is empty until too late. Possibly relates to #1433 "Clicking close to a previous click doesn't register in newui 2D", but then again maybe not.

Will link to demo once this is up.

**Comment by kring** [comment]
Just in case it helps, feature picking is intended to be asynchronous.  You need to wait for `allFeaturesAvailablePromise` to resolve before you can count on all the entities being in the features array.

**Comment by rdengate** [comment]
Hmm, thanks. I will look at whether I'm doing that.

**Comment by rdengate** [comment]
Fixed in PR #1549
