### ISSUE TITLE
Terrain height is continually polled on high DPI displays

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#1523]
On my Windows laptop (which is not actually high DPI) with "Change the size of text, apps, and other items" set to 175% (so it acts like it is), the location bar at the bottom continually flips between showing an elevation +/- some number and a precise elevation.  Presumably it thinks the mouse is moving around?

**Comment by tephenavies** [comment]
Fixed by #1642.

**Comment by stevage** [comment]
Was this bug present in `master`? If so, maybe the issue should remain open till `newui` gets merged?

**Comment by kring** [comment]
No, it was new UI only.
