### ISSUE TITLE
EPSG:3577 support for ArcGIS

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1531]
I have an ArcGIS service that claims to be EPSG:3577 where Zoom To doesn't work. I was going to add support for it in `Proj4Definitions.js` only to find it's already in there:

https://github.com/TerriaJS/terriajs/blob/jsonTreeview-2016-04-22/lib/Map/Proj4Definitions.js#L22

The service I'm using is:

https://gisservices.information.qld.gov.au/arcgis/rest/services/AREMI/Sugarcane/MapServer

Maybe I got the wrong idea about how `Proj4Definitions.js` is supposed to work?

**Comment by stevage** [comment]
Very similar to #1447

**Comment by kring** [comment]
Looks like the service above has changed to EPSG:4283, so I can't be sure. But I suspect this was fixed by #1448. Closing.
