### ISSUE TITLE
Inconsistent Opacity slider operation in Firefox/iOS

### ISSUE THREAD

**Issue by tobybellwood** [TerriaJS/terriajs#1536]
With a layer selected, the opacity slider doesn't allow drag, and can be fiddly to position accurately.

Works ok in Chrome v50, Edge v25, IE 11.0.031.
Not working in desktop Firefox 46.0.1, Safari/601.1 on iPad iOS9

Present across most installs/releases of TerriaJS (AREMI, NEII, Aurin etc), but appears fixed in newui,

**Comment by RacingTadpole** [comment]
Thanks Toby! Is this the same as #1021?

**Comment by tobybellwood** [comment]
Yup, missed that somehow...
