### ISSUE TITLE
GeoJSON loading fails if fill-opacity is specified but not fill-color

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#1537]
In `GeoJsonDataSource.js`:

``` javascript
            opacity = properties['fill-opacity'];
            if (defined(opacity) && opacity !== material.color.alpha) {
                if (!defined(fillColor)) {
                    fillColor = material.color.clone();
                }
                fillColor.alpha = opacity;
            }
```

`material.color.clone()` throws because `material.color` is undefined.

**Comment by kring** [comment]
Unzip this geojson file and drag it onto the map to reproduce the problem:
[map.geojson.zip](https://github.com/TerriaJS/terriajs/files/265649/map.geojson.zip)

**Comment by kring** [comment]
I think this is technically a Cesium bug.

**Comment by nf-s** [comment]
Not relevant to v8
