### ISSUE TITLE
Return to data workbench when a new data set is added to the map

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#1540]
**To reproduce:** 
1. Run a search the primary search field _e.g. wind_
2. Go to the data catalogue, add a new data set to the map
3. Notice that search results remain in the left panel and data legends are not shown

**Suggested solution:**
- Preference workbench visibility over search results 
- Always return to the data workbench when a new data set is added

**Comment by kring** [comment]
Fixed by 10810cac923604218ffa0cedc685539aa8c10a08
