### ISSUE TITLE
Add support for WMS GetCapabilities <MetadataURL/> elements

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1545]
We have had some requests to expose `<MetadataURL/>` elements from the WMS `GetCapabilities` data. In most cases these link to sources of standards compliant metadata pages for the datasets in question. We should probably show these links on the layer Info page as sources of more information about the dataset.

Example `GetCapabilities` with `<MetadataURL/>` elements:

http://services.ga.gov.au/gis/services/Australian_Coastal_Sediment_Compartments/MapServer/WMSServer?request=GetCapabilities&service=WMS

**Comment by AlexGilleran** [comment]
@meh9 so this is mostly done, but I've just realised that we already show a "Metadata URL" field with the GetCapabilities XML URL. Should this be replaced with this? Added to? Should this nice metadata URL go in a different section with a different name?

**Comment by meh9** [comment]
All good questions!

The current `Metadata URL` appears to be for MapServers only though - for WMS we call it `GetCapabilities URL`.

If there are no other cases when we use `Metadata URL` than for MapServers, my vote would be to rename that, but all that I can think of would be to call it the same as the `Esri ArcGIS MapServer URL` in which case the question becomes why do we have two fields with same/similar names and the same data but one being a clickable URL?

Regardless, how about we make the new field `Data Metadata Links`, because it's concerned with the metadata of the data as opposed to the service.

**Comment by AlexGilleran** [comment]
Works for me!

**Comment by kring** [comment]
As mentioned in the linked PR, I think `Metadata Links` is a better name.  As far as the existing `Metadata URL`....  yeah, I think we can just get rid of that entirely for ArcGIS (probably in general).  For an ArcGIS layer, we should just make the `ESRI ArcGIS MapServer URL` clickable.  I'll write a separate issue.
