### ISSUE TITLE
Test / Ferry routes fails

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1547]
At http://nationalmap.gov.au/#test

if you choose GeoJson files -> Ferry Routes (GeoJson via WFS), we get the error:

`TypeError: Cannot read property 'documentElement' of null`

**Comment by stevage** [comment]
This WFS endpoint has gone away, but I'm not sure what the new one should be. This doesn't seem right:

http://www.ga.gov.au/gis/rest/services/topography/Australian_Topography_WM/MapServer/WFSServer

**Comment by meh9** [comment]
Looks like they don't expose the new services as WFS, so you may have to find something else:

http://services.ga.gov.au/gis/rest/services/NM_Transport_Infrastructure/MapServer
