### ISSUE TITLE
Allow explicit colorBins

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1551]
For "Places Like This" we know the display values are between 0 and 1. Often most regions across Australia have values between 0.7 and 0.8 (say), so both `colorBinMethod` = `quantile` and `ckmeans` put most color variation in that range. However, when viewing regions around the chosen one (eg. Strathfield), we are often interested in small variations from 1, which do not show up.

One solution would be to allow the user to explicitly define the color binning.

Thinking of ways to specify this - one idea is to overload the integer `colorBins` with an explicit array of values, eg.

```
"tableStyle": {
    "colorBins": [0, 0.25, 0.5, 0.75, 0.8, 0.9, 0.925, 0.95, 0.975, 1]
}
```

**Comment by stevage** [comment]
So yeah, we need this for ParlMap: they want colors to be applied consistently across datasets, so pale blue is always 48-50%, for instance. To be totally clear, we're specifying the _boundaries_ between the color bins. It would look like this:

```
tableStyle: {
  colorBins: [35, 40, 44, 46, 48, 50, 52, 54, 56, 60, 65]
}
```

![screenshot 2016-07-19 10 12 28](https://cloud.githubusercontent.com/assets/678344/16972075/05ba87a2-4e6c-11e6-94c8-6e5e0b1916b3.png)
