### ISSUE TITLE
Allow proxy for all ports of a domain

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1552]
Currently if `csiro.au` is present in `serverconfig.json`'s `allowProxyFor`, all domains ending in `csiro.au` can be proxied... but if an explicit port is appended (eg. `...csiro.au:80`), it is not.
Is there a reason for this?

**Comment by kring** [comment]
`csiro.au:80` won't match unless the port is explicitly included in the URL.  i.e. it's not smart, it doesn't know that 80 is the default.  But if the port is included, I believe it will match `*.csiro.au:80`.  Is that not what you're seeing?

**Comment by RacingTadpole** [comment]
Yes, but I'm suggesting we make `csiro.au` also match `csiro.au:*` (ie. not just 80 but also 8000, etc).

**Comment by kring** [comment]
Steve made the same suggestion the other day.  See discussion here:
https://github.com/TerriaJS/terriajs-server/issues/13

And perhaps close this issue in favor of that one, because this is really a server issue?
