### ISSUE TITLE
Support showing "description" for CatalogGroups

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1555]
We should support showing a `description` field specified in the catalogue for groups, so that you can click on groups and this description shows up on the right in the Info part of the Add Data panel. This is fine to be NewUI only.

**Comment by meh9** [comment]
We might even want to consider showing the `service description` that we get from things like WMS GetCapabilities requests here, but this is optional.

**Comment by kring** [comment]
Done in the `newui` branch:
![image](https://cloud.githubusercontent.com/assets/924374/15662534/f0abb498-2734-11e6-9a71-4a61563c148d.png)

Our metadata for groups is pretty sparse right now, but we'll improve that over time.
