### ISSUE TITLE
Add capability to enable another CatalogItem when using an item specified by WebProcessingServiceCatalogGroup

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1557]
WPS functions can sometimes only be used in particular geographical areas. In order to show the user where they can click for the WPS we should show another layer indicating where it is "safe to click".

Add support to `WebProcessingServiceCatalogGroup` so that another `CatalogItem` can be specified for this that will be turned on when a item in the group is clicked. This layer should then then be turned off at some point, possibly when any other thing in the catalog is clicked on or something similar.

**Comment by kring** [comment]
This was fixed by #1693.  @meh9 I'll let you close if you agree.

**Comment by meh9** [comment]
I concur! Thanks!
