### ISSUE TITLE
Clicking on CZML billboards with Firefox on Mac can fail

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1563]
Some Mac users do not get a Feature Info panel when they click on a CZML billboard (specifically OSX 10.10.1 Yosemite, Firefox 46.0.1 and 38.2.0 - note on my Mac OS 10.11.4 with Firefox 42.0, 43.04 and 46.01 I do not have this problem). 

It occurs on http://nationalmap.gov.au/#test with the  "Test Data" -> “CZML files” -> "Large feature info box (CZML)”, which shows a “vehicle” near Sydney. When they click on the vehicle icon, they don't get anything, but as soon as they click elsewhere i get the Feature Info panel.

There are no caught or uncaught exceptions, and no messages in the console.

**Comment by kring** [comment]
Is it possible that the people having trouble are using 2D?  If so, it could be this:
https://github.com/TerriaJS/terriajs/pull/1521

**Comment by RacingTadpole** [comment]
Ah, you're right! Nice.
