### ISSUE TITLE
Changing between time varying layers which use different time ranges causes Cesium errors constantly

### ISSUE THREAD

**Issue by axman6** [TerriaJS/terriajs#1568]
(See gif below) When showing two layers which have non-overlapping time ranges, switching back to the non CZML layer causes the CZML to remind visible, but is now relying to run at a time outside its valid period, which causes Cesium to have an exception on every render loop (I assume).
![ezgif com-optimize](https://cloud.githubusercontent.com/assets/39567/15464411/821a76a4-2112-11e6-8ff5-75b8c0ab3315.gif)

**Comment by kring** [comment]
~~Could be related to #1537~~, or not.  It's not.

**Comment by kring** [comment]
This appears to no longer be an issue. I tested it with bird_migration.czml and Chlorophyll concentration.
