### ISSUE TITLE
CSV fails on IE

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1569]
We get an error when loading a particular CSV in IE:

![image002](https://cloud.githubusercontent.com/assets/5283003/15493026/747c9f24-21c4-11e6-86e8-aa4304c91be1.jpg)

This comes up immediately when going to this share URL:

http://prototype.aremi.nicta.com.au/renewables/#share=p7JdY3

This is using Terrai 3.2.1.

**Comment by AlexGilleran** [comment]
@meh9 which version of IE?

**Comment by AlexGilleran** [comment]
Never mind, fails on IE11

**Comment by AlexGilleran** [comment]
Appears to be because of this shady character: 
![image](https://cloud.githubusercontent.com/assets/900555/16066389/18784406-32f6-11e6-927d-f75dc201afe6.png)

**Comment by AlexGilleran** [comment]
So after much ado:

The CSV file has quite a few invalid characters in it in random places - it appears to have suffered some corruption at some stage. The question mark above appears to be a Control-Z control character (ascii dec 26) which is ignored by most applications that open the CSV, but IE appears to interpret it as "skip the next character" - unfortunately the next character in this case is the `"` that tells where the end of the CSV cell is, so the CSV parser continues parsing the rest of the file as one big cell until it hits the end of the line and realises that it's broken, hence the invalid state error.

I've made a comment on data.sa.gov.au, beyond that I'm not sure how much more I can do. The thing is that this happens the second the string is interpreted by IE, so I can't even filter the dodgy character out.

The only alternative I can think of would be to have some kind of sanitisation proxy in terria-server :/

Any thoughts @meh9 ?

**Comment by meh9** [comment]
If there are actually problems with the data I think it's fair enough to pass that back to the data custodian and leave it at that - the error message is quite descriptive as it is and now that we know that this is IE's behaviour we can hopefully avoid having to go down this investigative path in the future.

@AlexGilleran is there anything you think we could do to make it even clearer to the user that the data is corrupt? Is there anything we can do to avoid somebody doing this amount of investigation again?

I'll contact the data custodian directly as well.

**Comment by AlexGilleran** [comment]
Not really unfortunately - given that IE isn't capable of seeing or testing for the problem, all we can discern from it is that the parser has gone haywire.
