### ISSUE TITLE
Black Marble basemap does not display around international dateline

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1571]
The NASA Black Marble basemap has problems displaying map tiles around the international dateline. As you zoom in and out the area where tiles are not being displayed shrinks and grows, but it never displays the tiles adjacent to the dateline.

**Comment by stevage** [comment]
Boy, that's kind of an understatement.

![blackmarble](https://cloud.githubusercontent.com/assets/678344/15813468/ace30f68-2c02-11e6-80bc-de0043b29a76.png)

For context, that layer is served by us from our GeoServer - it was loaded as a single TIF. Probably the bounds or projection are set wrong. But do we care? I'm not really sure why we even have this basemap. Seems like it was "vaguely cool" once upon a time but doesn't seem especially valuable now.

**Comment by kring** [comment]
Agreed, not real valuable.  Probably an easy fix too, though, FWIW.

**Comment by stevage** [comment]
What a beautiful GeoServer exception:

```
      Error rendering coverage on the fast path
javax.media.jai.util.ImagingException: All factories fail for the operation "VectorBinarize"
All factories fail for the operation "VectorBinarize"The specified dimensional parameter is non-positive.
```

**Comment by stevage** [comment]
Here's one of the bounding boxes in question

`bbox=-20037508.342789244,-4383204.9499851465,-19411336.20707708,-3757032.814272985`

**Comment by stevage** [comment]
Probably the issue goes away if we request EPSG:3857 instead of EPSG:4326, but I don't know how to do that.

**Comment by kring** [comment]
Not an issue anymore.  There's still a thin line at the IDL, but no missing tiles.
