### ISSUE TITLE
"Display as percent of region population" missing from new UI

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1576]
![screenshot 2016-05-30 17 15 21](https://cloud.githubusercontent.com/assets/678344/15642365/24b6b4aa-268a-11e6-86ff-53b22bd02539.png)

This option for ABS Data Service datasets isn't present, which makes many datasets not work properly.

**Comment by kring** [comment]
![image](https://cloud.githubusercontent.com/assets/924374/15663209/a8e5992e-273b-11e6-9eff-7d4f82061895.png)

@chloeleichen when you get a moment maybe you could try to make that word wrap (i.e. population on the next line) look nicer?

**Comment by chloeleichen** [comment]
<img width="342" alt="screen shot 2016-06-03 at 2 16 34 pm" src="https://cloud.githubusercontent.com/assets/7508939/15768623/ccbf8a38-2995-11e6-9fa4-b5b48aca95ec.png">

**Comment by kring** [comment]
:+1:

**Comment by kring** [comment]
ok to close this then?
