### ISSUE TITLE
CSV columns without value can not be ticked in the legend control

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1579]
When using a CSV file that has a column with no value, this column can not be selected/ticked as the data variable for the legend.

When attempting to select it instead the previous data variable (if any) is unselected. We should allow the column to be selected, and the legend should show the specified or default No Data string and colour.

[Blank.csv.txt](https://github.com/TerriaJS/terriajs/files/291051/Blank.csv.txt)

**Comment by kring** [comment]
This appears to no longer be an issue:
![image](https://user-images.githubusercontent.com/924374/36305900-aace40b2-1369-11e8-82c0-8a341867e113.png)
