### ISSUE TITLE
Features with null attributes can't generate CSV downloads

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1581]
If you have a layer (say, CED 2016) with null attributes (population in Lingiari, WA) then [this line](https://github.com/terriajs/terriajs/blob/d1f6118fe7eecb80051080be35b9cdf213edae03/lib/ViewModels/FeatureInfoPanelSectionViewModel.js#L272-L272) reports the null value as an object and CSV data generation fails. Whereas it should be possible to download as CSV in that case (null is just two consecutive commas...).

**Comment by kring** [comment]
Fixed by #1641.

**Comment by stevage** [comment]
Looks like my change didn't apply to the newUI branch.
