### ISSUE TITLE
Multiple selection of filters providing wrong numbers

### ISSUE THREAD

**Issue by hilarycinis** [TerriaJS/terriajs#1583]
Some of the percentages of selected persons out of a total population 
eg Country of birth / female in cooma

**Comment by hilarycinis** [comment]
Needs further investigation with client to reproduce.

**Comment by hilarycinis** [comment]
See https://github.com/TerriaJS/parlmap/issues/10

**Comment by kring** [comment]
There are some cases where the "total" we have for a region is smaller than the reported value for a region, which produces some wacky percentages.  It's a data problem, though, not something we can fix in TerriaJS. I'm closing this because I don't think there's anything to do on the TerriaJS side.
