### ISSUE TITLE
Continuous colour maps

### ISSUE THREAD

**Issue by AlistaiReid** [TerriaJS/terriajs#1585]
Rather than binning the area values, they could be mapped to a continuous interval. For example, we could:
- 'equalise' the value distribution through a non-linear mapping - eg compute (area rank)/(number of areas) to obtain a value between 0 and 1
- linearly map the values to the (0,1) interval by computing (y-y_min)/(y_max-y_min). This can be made more robust to data outliers by mapping between the nth and nth last percentiles, rather than the min and max.
- apply any other transforms such as truncated logarithm

We then apply the colour map function to each value to compute a RGB colour. There are many choices of such functions in the literature, but a perceptually linear colour map would be a principled choice - Matplotlib implements a bunch of (often piecewise-linear) functions that could be easily ported to javascript:
http://matplotlib.org/examples/color/colormaps_reference.html
https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/_cm.py

**Comment by nf-s** [comment]
For #3524

**Comment by nf-s** [comment]
Duplicate issue https://github.com/TerriaJS/terriajs/issues/3441
