### ISSUE TITLE
Add GNAF support to search

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#1588]

**Comment by kring** [comment]
@tobybellwood in the last NM planning meeting I think we discussed that it would be nice to show a pin at the location of GNAF (and also Bing and Gazetteer) search results.  I just wanted to make sure it's ok with you if that happens in the 15 July release instead of the 15 June?  That way we don't need to do it in both the new and old UIs.  We're on track to add GNAF search for the 15 June release, just without the pin marking its location.

**Comment by tobybellwood** [comment]
Agree, search for June, result pin for July.
