### ISSUE TITLE
Allow charts created inline to be added to workspace

### ISSUE THREAD

**Issue by axman6** [TerriaJS/terriajs#1589]
Currently it's not possible (AFAIK, @RacingTadpole can correct me on this) to add a chart to the workspace if it was created using an inline CSV - this is the easiest way to add data from inside a template which we'd like to use for the ISF data. Not being able to do this means we just get line charts without any useful labels and can't actually interrogate the data at all, so we're relying on tables at the moment.

**Comment by axman6** [comment]
This appears to be working now in the latest TerriaJS, @RacingTadpole is there anything more necessary before closing this?

**Comment by RacingTadpole** [comment]
Cool! No.
