### ISSUE TITLE
New UI: missing print disclaimer

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#1591]
The old UI had a special disclaimer it should show in the printed view.  We need that in the new UI too.  Ideally it would be configured in config.json like the regular disclaimer rather than hard-coded into index.html like it is in the old UI.

**Comment by chloeleichen** [comment]
hide on `@media screen` and display on `@media print`

**Comment by chloeleichen** [comment]
We need 

```
"printDisclaimer":{
            "text":"some disclaimer text",
            "url": "about.html"
        },
```

in config.json

**Comment by kring** [comment]
@chloeleichen is this already fixed?  Close it if so.

**Comment by chloeleichen** [comment]
fixed, though whoever responsible for the `config.json` needs to put the above lines in, should I do it in NM? @kring

**Comment by kring** [comment]
Yes, please!
