### ISSUE TITLE
URL sharing of timeseries layers is broken

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1592]
Creating a share URL (shortened or unshortened) of a timeseries layer and following the link results in a broken Terria instance with no catalogue or timeseries (i.e. JS has hit an error somewhere).

To test, go to http://nationalmap.gov.au/#test -> Test Data -> Temporal -> Chlorophyll

**Comment by stevage** [comment]
Reproduced: http://nationalmap.gov.au/#share=xcqTlO

**Comment by RacingTadpole** [comment]
The good news is I can't reproduce this either in the current master (f07f6d7), or in the `newui` branch.
I hope this means it has magically been fixed.
For reference, in case it is still a problem, the error seems to be that when you open the shared link, `animationViewModel.refreshTimeline` refers to `this.timeline`, which is `undefined`.

**Comment by kring** [comment]
No longer a problem, closing.
