### ISSUE TITLE
Parallax issue for selected Line geometries

### ISSUE THREAD

**Issue by rtaib** [TerriaJS/terriajs#1598]
When selecting a Line feature that is on ground level, the highlighted (white in colour) Line that appears is at a different elevation, resulting in a parallax issue.(Based on a discussions with @kring)

**Comment by meh9** [comment]
Dupe of #702.

**Comment by rtaib** [comment]
Sorry, didn't see this :( Closing this one now.

**Comment by meh9** [comment]
No worries, I actually left this one open because being more recent it has higher visibility at the top of the stack!

**Comment by rtaib** [comment]
Oops. Please feel free to re-open then :)
