### ISSUE TITLE
Quantile method of color binning produces bad results for very skewed datasets

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1599]
This dataset has 5000 rows, so Terria defaults to the `quantile` method. For the "V13: First Preference Vote to National" column, this produces really bad color binning and hence legend:

![screenshot 2016-06-07 15 34 03](https://cloud.githubusercontent.com/assets/678344/15846967/496cdd1a-2cc5-11e6-8c9d-c1fd43795321.png)

[VIC_TAS_Election2013_Votes_SA1.csv.zip](https://github.com/TerriaJS/terriajs/files/301896/VIC_TAS_Election2013_Votes_SA1.csv.zip)

**Comment by nf-s** [comment]
We don't use binning by default anymore
