### ISSUE TITLE
add OpenStreetMap layers?

### ISSUE THREAD

**Issue by juan-guerschman** [TerriaJS/terriajs#1605]
Is it possible to add overlays from OpenStreetMap? I'm particularly interested in being able to overlay coastlines, borders, labels and roads, particularly useful if the user wants to show raster layers in 100%  opacity.
I'm thinking about something like this: [http://go.nasa.gov/1ZwE10E](http://go.nasa.gov/1ZwE10E) 
@meh9 @rdengate

**Comment by meh9** [comment]
Moved issue to NICTA/geoglam-nm#1
