### ISSUE TITLE
add to docs on setting position, direction, etc of initial camera

### ISSUE THREAD

**Issue by DanielBaird** [TerriaJS/terriajs#1624]
I can't find any docs on what `position`, `direction`, and `up` do when specified inside `initialCamera`:

```
"initialCamera": {
    // ...west, south, east, north in degrees of lat/lng...
    "position": {
        "x": -5038556.291612258,
        "y": 3209047.904530921,
        "z": -2501693.764733501
    },
    "direction": {
        "x": -0.12410919344329185,
        "y": 0.15603178287613623,
        "z": 0.9799239719667361
    },
    "up": {
        "x": -0.8169419348214959,
        "y": 0.5444670255773952,
        "z": -0.19016186017452785
    }
},
```

I can specify them inside a URL-encoded start parameter (that I copy from nationalmap), and that works as expected, but I don't know what the numbers mean.

Have I missed a doc page somewhere?

Where do the x y and z axes point?

And how do I specify these in a JSON config so they apply on load?

---

(Added after some discussion about adding docs for this feature)
TODO for doc authoring:
- [ ] mention N/E/S/W always required as a fallback for the 2D map 
- [ ] be clearer about "fly the camera around a bit on nationalmap"

**Comment by DanielBaird** [comment]
Tagging @stevenvandervalk ..

**Comment by kring** [comment]
They're vectors in ECEF:
https://en.m.wikipedia.org/wiki/ECEF

`position` is the location of the camera in that coordinate system.  `direction` is a vector in the direction the center of the screen is looking, and `up` is a vector indicating which direction is toward top of the screen (ie how is the camera rotated about the direction vector ).

Also check out the `fromJson` function in this file:
https://github.com/TerriaJS/terriajs/blob/master/lib/Models/CameraView.js

It has some other ways of specifying the camera that may be more intuitive.

**Comment by kring** [comment]
In an init file, add an `initialCamera` or `homeCamera` property at the same level as `catalog` with anything that can be deserialized by that `fromJson` function.  `homeCamera` is where you go when you press the reset button on the right side of the map, and `initialCamera` is where you're looking when the init files first loads.

**Comment by DanielBaird** [comment]
Ah thanks for the `toJson` reference, that's what I needed.

I'll write an example and explanation about using the `lookAt` config key into my own docs.  I could also add that to Terria docs somewhere -- maybe in the TerriaMap repo...?

**Comment by kring** [comment]
Thanks @DanielBaird, we'd definitely appreciate that.  What do you think about adding it to the the `homeView` or `initialView` properties in `Terria.js`?  Something like "When specified in a JSON init file...".  Our current process is to document init file properties in the code then generate a JSON Schema from it.  The obvious next step is to generate documentation from the JSON Schema.  I don't think we currently pick up properties in `Terria` for the JSON Schema, but that can be fixed.

**Comment by DanielBaird** [comment]
sure, I'll work out somewhere for it in the code comments.  I've changed the title so this issue can stay open to remind me to do it..

**Comment by stevage** [comment]
These properties are in a small category of properties which are specified in init files, but aren't properties of catalog items. (Other properties in this category are `corsDomains` and the defunct `services` property.)

I think it's ok to just document these properties specifically in `Initialization-File.md`, even if it means a slight repetition of work.

**Comment by DanielBaird** [comment]
I've written up my informal description for my own project... it's unconventional but I might just post the content here.

If you want this kind of thing in [Initialization-File.md](/Documentation/CatalogManagement/Initialization-File.md), just say so here (with any corrections you notice) and I'll wrap it up in a PR.

---

### Positioning the map's viewing camera

You can start the map with the camera at whatever you like.

Maps have two camera positions, `homeCamera` and `initialCamera`,
which are specified identically.  The `initialCamera` is what you get
when the map first displays.  The `homeCamera` is what you get when
you click the "reload"-looking button between the zoom in and zoom
out buttons.

#### Option 1: specify bounds

The `homeCamera` example here specifies `north`, `east`,`south`, and
`west`, in lat/lng decimal degrees.  The camera will be positioned
in the centre point of those bounds, looking toward the Earth's
centre, zoomed back enough to see to the edges of the bounds.

#### Option 2: specify position in super-fixed coordinates

This overrides Option 1.

You can specify `position`, `direction`, and `up` (as well as
`north`, `east`,`south`, and `west`). `position` and `direction`
need `x`, `y` and `z` keys specifying locations in
[ECEF](https://en.wikipedia.org/wiki/ECEF) metre coordinates, which
means the origin is the centre of the Earth, positive Z points to
the north pole, positive X points toward
["Null Island"](https://en.wikipedia.org/wiki/Null_Island) where the
equator intersects with 0 degrees longitude, and positive Y points at
(0, 90E) -- which is in the Indian Ocean south of the Bay of Bengal.

For most purposed positioning this way is difficult for normal
humans. To see an example, fly the camera around a bit on
nationalmap, click the "share" button (and choose to not use the
URL shortner), then URL-decode the URL you get.

#### Option 3: locate the camera like a spaceship

This is useful for when you're showing a view from an aircraft or
satellite, and overrides Options 1 and 2.

You can specify:
- `positionHeadingPitchRoll.cameraLongitude`
- `positionHeadingPitchRoll.cameraLatitude`
- `positionHeadingPitchRoll.cameraHeight` probably in metres
- `positionHeadingPitchRoll.heading` in degrees clockwise from north
- `positionHeadingPitchRoll.pitch` in degrees down from horizontal
- `positionHeadingPitchRoll.roll` in degrees

...and get the viewpoint at the position you specify, pointing toward
the `heading` you gave, angled downward by `pitch` degrees (or
upward, if you supply a negative pitch value), and rolled (which
means tipped sideways) the specified degrees.

#### Option 4: look at a feature

This is probably the most useful one for showing a feature on the
map, and overrides Options 1, 2, and 3.
- `lookAt.targetLongitude`
- `lookAt.targetLatitude`
- `lookAt.targetHeight`, in metres from sealevel (positive is up)
- `lookAt.heading`, in degrees clockwise from north
- `lookAt.pitch`, in degrees down from horizontal (so negative values mean you're looking at the sky)
- `lookAt.range`, in metres from the thing you're looking at

The example below uses plain old bounds for the `homeCamera`, and
a `lookAt` key for the `initialCamera`.

```
{
    "homeCamera": {
        "north": -8,
        "east": 158,
        "south": -45,
        "west": 109
    },
    "initialCamera": {
        "lookAt": {
            "targetLongitude": 145,
            "targetLatitude": -17,
            "targetHeight": 100,
            "heading": 45,
            "pitch": 45,
            "range": 100000
        }
    },
    "baseMapName": "Bing Maps Aerial",
    "viewerMode": "3d"
}
```

**Comment by kring** [comment]
I'll let @stevage answer the question about the best place to put the doc.  But one quick note from me: the west/south/east/north coordinates should be considered required, because that's the only representation supported on the 2D map.

**Comment by kring** [comment]
Thanks for writing it up, @DanielBaird!
