### ISSUE TITLE
Cannot view GeoJSON Properties Table When Leaflet (2D) is Present and "marker-symbol" is used.

### ISSUE THREAD

**Issue by ismail44** [TerriaJS/terriajs#1627]
When the map is set to 2D mode (Leaflet) clicking on anything that's defined with a marker-symbol (or image) does not show the properties passed in with GeoJSON. 

If you add "Test overriding Styled and unstyled features" GeoJSON dataset to the map and toggle between 3D and 2D you'll see that on 3D the table with the properties is displayed. On 2D that table is not. 

I attempted to debug and it looks like the click event on the leaflet marker is gobbling up the event that attempts to find the features at that spot.

**Comment by kring** [comment]
@ismail44 thanks for the report.  Can you attach a GeoJSON file we can use to reproduce this?  Also, is this in the `newui` branch or in `master`?  Or both?

**Comment by ismail44** [comment]
It's on both... I actually switched to newui hoping it would be different... right now I'm just testing with some of the GeoJSON from the wwwroot/test

One of the files is: wwwroot/test/GeoJSON/test-styles.geojson

I'll keep having a look... but, on newui... what I can see is when an icon is used... and the point is clicked... inside of the featurePicked function of Leaflet.js (line 418) the leaflet variable doesn't have the _pickedFeatures property filled in. When no icon is used, this property has data in it. 

The weird thing is that the entity IS added to an empty collection, but it doesn't seem to matter. Or, I lose it in the debugging.

Thanks!

**Comment by ismail44** [comment]
A weird thing is... if I have some data sets both with icons as markers and not... if I first click an "icon marker"... nothing shows up... but, if I then click a "non-icon marker" the popup shows up with BOTH sets of data... super strange.

**Comment by stevage** [comment]
Thanks. There's definitely some pretty weird behaviour here.
1. http://nationalmap.gov.au/#test&map=2d, add "Test styled and unstyled features"
2. Click the pink rocket lots of times. It's "clickable" (mouse cursor changes) but nothing happens
3. Now, carefully click at the base of the speech bubble. 
4. Result: all those previous clicks suddenly get fulfilled at once.

![screenshot 2016-06-14 13 20 49](https://cloud.githubusercontent.com/assets/678344/16030260/d3a43b64-3232-11e6-9487-4bdda332701e.png)

**Comment by kring** [comment]
Fixed by #1680.
