### ISSUE TITLE
Deprecated NPM modules

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1628]
```
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
```

Probably everyone has noticed these. :)

**Comment by ChALkeR** [comment]
Hi. `terriajs` is currently `#120` in my [list of modules](https://gist.github.com/ChALkeR/d39b49642e02277d2292d66c2ea0bced) that would likely to be broken when https://github.com/nodejs/node/pull/6413 lands (which is anticipated to happen before v7.0).

Note that `graceful-fs@1` and `graceful-fs@4` are ok and would not be broken by this, but a `require()` on `graceful-fs@2` or `graceful-fs@3` would cause an error soon.

That is, runtime warning `fs: re-evaluating native module sources is not supported.` would be turned into a throw.

If you or your deps use `graceful-fs@2` or `graceful-fs@3` in runtime — you are affected. 

Tracking: https://github.com/nodejs/node/issues/5213.

**Comment by stevage** [comment]
Thanks @ChALkeR!

**Comment by florianm** [comment]
Just merged latest terriaJS master into my little [branch ](https://github.com/parksandwildlife/TerriaMap), which broke my supervisord script, but still works fine when run with `npm run`.

```
npm list graceful-fs
terriajs-map@0.0.1 /mnt/projects/dpawmap
├─┬ eslint@3.4.0
│ └─┬ file-entry-cache@2.0.0
│   └─┬ flat-cache@1.2.1
│     └── graceful-fs@4.1.6 
├─┬ fs-extra@0.30.0
│ └── graceful-fs@4.1.6 
├─┬ glob-all@3.0.3
│ └─┬ glob@4.0.6
│   └── graceful-fs@3.0.8 
├─┬ gulp@3.9.1
│ └─┬ vinyl-fs@0.3.14
│   └─┬ glob-watcher@0.0.6
│     └─┬ gaze@0.5.2
│       └─┬ globule@0.1.0
│         └─┬ glob@3.1.21
│           └── graceful-fs@1.2.3 
├─┬ gulp-less@3.1.0
│ └─┬ accord@0.23.0
│   └─┬ fobject@0.0.4
│     └── graceful-fs@4.1.4 
├─┬ gulp-sourcemaps@1.6.0
│ └── graceful-fs@4.1.4 
├─┬ less@2.7.1
│ └── graceful-fs@4.1.4 
├─┬ node-sass@3.8.0
│ └─┬ node-gyp@3.4.0
│   ├── graceful-fs@4.1.6 
│   └─┬ tar@2.2.1
│     └─┬ fstream@1.0.10
│       └── graceful-fs@4.1.6 
├─┬ webpack@1.13.1
│ ├─┬ enhanced-resolve@0.9.1
│ │ └── graceful-fs@4.1.4 
│ └─┬ watchpack@0.2.9
│   ├─┬ chokidar@1.6.0
│   │ └─┬ readdirp@2.0.1
│   │   └── graceful-fs@4.1.4 
│   └── graceful-fs@4.1.4 
└─┬ yargs@4.8.1
  └─┬ read-pkg-up@1.0.1
    └─┬ read-pkg@1.1.0
      ├─┬ load-json-file@1.1.0
      │ └── graceful-fs@4.1.4 
      └─┬ path-type@1.1.0
        └── graceful-fs@4.1.4 
```

Looks like latest gulp depends on graceful-fs@1.2.3. What can we do, @stevage?

**Comment by ChALkeR** [comment]
graceful-fs@1 isn't re-evaluating native modules, so it's not causing issues.

Moreover, graceful-fs@3.0.10 was released just recently that uses more hacks to evade the breakage on Node.js 7.x, so it's also not going to break on Node.js 7.0. It still does re-evaluation, though, and that's technically not supported. `graceful-fs@3.0.10` is still expected to cause _other_ runtime warnings due to that.

Only graceful-fs@`>= 2.0.0 < 3.0.10` is going to hard break in the next Node.js release.

And lastly: gulp@4 is supposed to be released in near future, that one wouldn't depend on old `graceful-fs` versions.

So what you should do here is perhaps to wait until `gulp@4` or not use gulp at all.

**Comment by kring** [comment]
Since Node 8 is out and things still work, presumably Gulp moved to a later `graceful-fs` version or stopped using it? In any case, I'm closing this because these aren't direct TerriaJS dependencies and so we can't just stop using them.
