### ISSUE TITLE
Mobile: Supporting links break - Android

### ISSUE THREAD

**Issue by hilarycinis** [TerriaJS/terriajs#1653]
About, Related and Support break the browser in both Chrome and Android Viewer

Set of error messages initiated when clicking through to About, Related and Support info pages

![screenshot_20160620-150225](https://cloud.githubusercontent.com/assets/6046521/16185096/b23872c0-3704-11e6-9611-c8db4aab9576.png)

**Comment by kring** [comment]
@hilarycinis that's a really weird error that seems to indicate something wrong with your phone?  Can I spend a few minutes with it sometime?  Anyway, there's definitely a bug in that About, Related maps, and Support don't actually go anywhere, they're just links to the same page again.  I'll write that as a separate issue.

**Comment by hilarycinis** [comment]
Sure thing, I'll pop over with it tomorrow, thanks. I agree it's weird... I tried it on 2 browsers to sanity check. Also I was accessing via my ISP, not wifi (if that is significant)

**Comment by kring** [comment]
About and Related Maps work fine in Chrome on Android on a Nexus 6P, at least. Hopefully this is no longer an issue.
