### ISSUE TITLE
Mobile: Data layers can't be removed - Android

### ISSUE THREAD

**Issue by hilarycinis** [TerriaJS/terriajs#1654]
No way to remove data layers once loaded in, only "hide"

**Comment by kring** [comment]
Not sure what you mean, there's a Remove button:
![image](https://cloud.githubusercontent.com/assets/924374/16186169/628a8062-370c-11e6-9a9e-c2c3be68b048.png)

(middle of the right-hand side in the screenshot above)

**Comment by kring** [comment]
You can also hit the minus in the catalog view.

**Comment by hilarycinis** [comment]
issue resolved itself, might have just been my phone being buggy.
