### ISSUE TITLE
Mobile: Branding broken in header - Android

### ISSUE THREAD

**Issue by hilarycinis** [TerriaJS/terriajs#1655]
Issue present in both Chrome and Android Launcher

![screenshot_20160620-145626](https://cloud.githubusercontent.com/assets/6046521/16185208/7ebecace-3705-11e6-8159-9654fb944975.png)

**Comment by kring** [comment]
This problem is specific to the AREMI branding, NM and Terria branding are fine.  I'll move the issue there.

**Comment by kring** [comment]
This issue was moved to NICTA/aremi-natmap#45
