### ISSUE TITLE
problem adding this WMS endpoint to newUI

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#1665]
I tried to add the WMS service endpoint
http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r-t.cgi
to the newUI instance at
http://nationalmap.research.nicta.com.au/newui/
by using the "Add data=>My Data=>Add Web Data", selecting "WMS", pasting the endpoint URL and selecting the 2nd layer for display (there are 2 layers).   

When I do this, I seem to get some view of the galaxy (with no Earth in sight) that I can't get out of:

http://tinyurl.com/juj2o9s

Any idea what is going on here?

It works okay with the old UI:
![2016-06-21_7-06-56](https://cloud.githubusercontent.com/assets/1872600/16230329/e751dcfa-378e-11e6-88e2-695efb8c965b.jpg)

**Comment by kring** [comment]
@rsignell-usgs the research server is pretty broken, use this instance instead:
http://preview.nationalmap.terria.io/

Adding those layers seems ok there, but let me know if you have trouble.  I did open a pull request to fix some related problems I found along the way, though.  See #1679.

**Comment by rsignell-usgs** [comment]
Indeed, working just fine in http://preview.nationalmap.terria.io/
![2016-06-27_9-55-08](https://cloud.githubusercontent.com/assets/1872600/16382065/4e70627c-3c4d-11e6-82f8-053ac9b3d5fd.jpg)
