### ISSUE TITLE
Only right 20% of preview is scrollable under Chrome + OSX + Retina

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/terriajs#1668]
![image](https://cloud.githubusercontent.com/assets/900555/16254407/fc7be5e0-3882-11e6-9923-bdb3d0c3d4b0.png)

The preview panel on the right only scrolls with the mousewheel if your cursor is in the right fifth of it. Still happens with all the maps out of the DOM, no matter how you position the two columns (relative+float/absolute/display inline block). This seems to be a bug in chrome although I can't find a report of it - it does work in Chrome Canary so presumably it'll go away by itself eventually, just thought I'd better keep track in case anyone else enters the same rabbit hole I did trying to work around it.

**Comment by chloeleichen** [comment]
this one has gone away hasn't it? @AlexGilleran

**Comment by AlexGilleran** [comment]
Still happens for me :/

**Comment by kring** [comment]
Certainly not a problem for me in Chrome + Windows + Retina. If it was already fixed in Canary in Jul 2016 it should be fixed everywhere by now.  Closing.
