### ISSUE TITLE
Mobile: Search results aren't displaying - Android

### ISSUE THREAD

**Issue by hilarycinis** [TerriaJS/terriajs#1669]
Initiating search from the icon works
Text enter works
**Search results displaying after tapping "go" in mobile keyboard fails**
Clear "x" search test works

Tested on Samsung Android, Chrome

**Comment by kring** [comment]
I can confirm this is broken on http://preview.nationalmap.terria.io, but is working in the latest version running locally, so there's a good chance it has already been fixed.  I'll retest after the next deployment.

**Comment by kring** [comment]
Still totally broken on updated http://preview.nationalmap.terria.io.

**Comment by kring** [comment]
Fixed by #1785.
