### ISSUE TITLE
Mobile: Opening a shared link fails to load data - Android

### ISSUE THREAD

**Issue by hilarycinis** [TerriaJS/terriajs#1670]
Use case:
- Data is loaded into the UI
- Link for sharing is created using the "share" functionality
- This could be then shared in social media or emailed as a link
- User taps the link to view the loaded data
  **- No data loads, just a blank map
- The map and data cataloge do work but it's failing in it's purpose

Snacking on data stories from social media is a use case we've observed before eg New mobile towers announced

Tested in Samsung Android, Chrome

**Comment by kring** [comment]
@hilarycinis it seems to be working ok for me.  Can you tell me which newui instance you were using, and what layers you enabled when it didn't work?

**Comment by kring** [comment]
FYI what I tried was the latest version built on my own system, and I enabled `Land -> Surface Geology`, changed the view a bit, and shared that.  The share link worked on both my desktop and on my Nexus 5 with Chrome 51.0.2704.81.

**Comment by hilarycinis** [comment]
Thanks @kring I think my original issue description was flawed - 

Data is loaded into the newui on desktop (http://newui.aremi.nicta.com.au/prototype/) then opened on a mobile. 

I loaded the same layers as you, sent the share link to myself on slack and tapped to open in mobile. 
Share link is: http://newui.aremi.nicta.com.au/prototype/#share=0jCJ1y
The selected datasets didn't load in the mobile
Samsung Galaxy S6 Edge running Chrome 50.0.2661.89

**Comment by hilarycinis** [comment]
Ok so I've just tried to do this also, desk top to desk top and it's failing so might not be specifically mobile. http://newui.aremi.nicta.com.au/prototype/#share=VyThBP 

MacBook Air OS X Yosemite 10.10.5 

Data loaded and shared from Chrome Version 50.0.2661.102 
Pasted into same Chrome and also Firefox 46.0

**Comment by kring** [comment]
This has been fixed.  Tested with:
http://preview.nationalmap.terria.io
by creating a share link on desktop and opening it both on desktop and mobile.  It works both long and short URLs.
