### ISSUE TITLE
Show number of selected features in the title bar of the feature info panel

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1674]
We've had a request for a scrollbar to be added to the feature info window. Technically, there is already a scrollbar:

![screenshot 2016-06-23 16 37 52](https://cloud.githubusercontent.com/assets/678344/16293936/d78d30b6-3960-11e6-91e2-6bf7c06ca05e.png)

But it's extremely subtle, so I take their point. They also suggested some other indicator that there is more information further down.

**Comment by kring** [comment]
Once upon a time, we had a design where all the feature info titles were visible, and the scroll bar was inside whichever one was opened.  Obviously this doesn't work well when there are _lots_ of features, or when the window doesn't have much height, but maybe we can do something clever where it works that way up to a number of features?  I can imagine that being pretty hard in CSS though.

**Comment by stevage** [comment]
Hmm. I was thinking something like a fade-out cut-off thing at the bottom, and a downward facing arrow, maybe with text like "More..."

@philipgrimmett ?

**Comment by chloeleichen** [comment]
lazy loading(load more when you scroll to bottom)? @stevage

**Comment by tephenavies** [comment]
Maybe just including the number of features in the Feature Information title would encourage users  to look for the feature information of other features?

**Comment by kring** [comment]
The scroll bar is much more obvious these days. We also have yellow text at the top now when there is a very large number of features (more than 100):
![image](https://user-images.githubusercontent.com/924374/36291511-7e772280-131f-11e8-8f4a-9b850ef80296.png)

But @steve9164's suggestion seems like an easy win, so I'm going to change the title of this issue to reflect that suggestion. Maybe do it along with #2000.

**Comment by nf-s** [comment]
This is done

<img width="460" alt="image" src="https://user-images.githubusercontent.com/6187649/182610211-13549944-433a-4d56-a0a4-fc69f09d33c9.png">
