### ISSUE TITLE
NewUI IE9 SuperKraken

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/terriajs#1682]
![image](https://cloud.githubusercontent.com/assets/900555/16367105/7443ec06-3c63-11e6-945e-18d578062c6a.png)

So right now tests never start in IE9 on Travis for NewUI, even though running exactly the same tests in saucelabs from the command line is fine (although different saucelabs accounts). Do we have some kind of IE9 instance that's stuck or has a caching problem? Is that even a possibility? Need to investigate because we really should have this working now newui is going primetime.

**Comment by kring** [comment]
Fixed by #1700.
