### ISSUE TITLE
Weird behavior when using Add Data for URLs

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#1684]
From #1679:

> When I try to add the URL http://data.gov.au, my localhost:3003 refreshes completely (I've tested in both Chrome and Firefox). Are you seeing that too?

For me it doesn't refresh, but it also doesn't display an error or present the user with the option to use the conversion service.

**Comment by RacingTadpole** [comment]
This looks like a wider issue, eg. http://data.gov.au/dataset/68856000-d224-4b48-a234-edb840eca941/resource/0bcf54d1-972d-454f-8309-6cc62c3f5826/download/2016.csv works in the old UI, but in the new does nothing. It can be downloaded and dragged on though.
