### ISSUE TITLE
Add specs for ReactViews (and check we haven't lost any key functionality)

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1686]
We need to make sure all the relevant ViewModel specs make it into `newui`.

**Comment by RacingTadpole** [comment]
## AnimationViewModel

This is now `Timeline`.
- [ ] on init, showAnimation should be false
- when a layer is added to the time series stack
  - [ ] should set showAnimation to true
  - [ ] should set layerName to the name of the topmost layer
- when the last layer is removed from the time series stack
  - [ ] should set showAnimation to false
- timelineTic format
  - [ ] should be used if provided
  - [ ] should not be used if not provided
- currentTime format
  - [x] should be used if provided
  - [x] should not be used if not provided
- scrubbing
  - [ ] should set the current time to the time in the event
  - with gap between intervals
    - [ ] should set time to time within an interval as usual
    - should change a time to the previous interval's end
      - [ ] just after the start
      - [ ] just before the midpoint
    - should change a time to the next interval's start
      - [ ] just before the end
      - [ ] at the exact midpoint

## BrandBarViewModel
- [ ] to allow no elements
- [ ] to add elements from options

**Comment by RacingTadpole** [comment]
## DisclaimerViewModel
- [ ] should allow an already-accepted disclaimer to go straight through without displaying
- for a non-confirmation disclaimer
  - [ ] should open a popup message
  - [ ] should immediately execute the success callback
  - [ ] should record the popup message as being shown in local storage
  - [ ] should pass the ui container straight through to the modal
- for a non-confirmation disclaimer
  - [ ] if no key is specified, opens a confirmation dialog with the correct success callback
  - [ ] should pass options from the catalogItem correctly
  - [ ] should pass the ui container straight through to the modal
  - if a key is specified
    - [ ] should not record the popup message as being accepted in local storage until after the success callback is executed
    - [ ] should only a modal once for a certain key
  - if multiple items with keys are specified
    - [ ] should open 2 modals for 2 different keys regardless of how many events for each are triggered
    - [ ] should trigger all callbacks for a key after that key's modal is dismissed

## ExplorerPanelViewModel
- on init
  - [ ] sets the initial tab to the value in terria.userProperties.activeTabId
  - [ ] selects the first tab if no value for terria.userProperties.activeTabId
  - [ ] selects the first tab if terria.userProperties.activeTabId doesn't match a tab id
  - [ ] avoids tab id collisions by modifying the ids of colliding tabs
- when adding a tab
  - [ ] avoids tab id collisions by modifying the ids of colliding tabs
- when activating tab
  - [ ] changes the activeTabId user property when tab is activated
  - [ ] opens a hidden explorer panel by default
  - [ ] does not open a hidden explorer panel if second argument is passed
- [ ] changes tabs on active tab id change
- [ ] keeps userProperties.hideExplorerPanel up to date when isOpen changes

**Comment by RacingTadpole** [comment]
## FeatureInfoPanelSectionViewModel
- ~~[ ] uses a white background for complete HTML documents only~~ (possibly obsolete)
- when template is provided
  - rawDataVisible
    - [x] should be false on init
    - ~~[ ] should be true once showRawData is called~~
    - ~~[ ] should be false once hideRawData is called~~
  - ~~[ ] rawData should still be available~~
  - ~~[ ] templatedInfo should be available~~
  - lat and long of the clicked point
    - [x] should be available to the template
    - [ ] should not be present in raw data _This will require either a refactor or simulating clicks_
    - [ ] should not stop CSVs from being available _This will require either a refactor or simulating clicks_
  - [ ] lat and long of the clicked point are available with time-varying properties
  - [ ] does not think a falsy property value is time-varying
  - when template is not provided
    - ~~[ ] templatedInfo should not be available~~
    - ~~[ ] rawData should be available~~ _We used to test the raw data was shown; now we test that it does not show the "show raw data" button_
  - download data _This will require either a refactor or simulating clicks_
    - on init
      - [ ] should generate data uris for json and csv for 2-dimensional data
      - [ ] should only generate data uris for json for hierarchical data
      - [ ] download options dropdown should be hidden
    - on dropdown click
      - [ ] should show the dropdown if it's currently hidden
      - [ ] should hide the dropdown if it's currently shown
      - [ ] should set the position of the dropdown to just below that of the parent of the event target
      - [ ] should stop the event from propagating
      - [ ] should hide the download options dropdown when the feature info panel scrolls
      - [ ] should unbind both the scroll and body click listeners when the feature info panel scrolls
      - [ ] should hide the download options dropdown when a click is registered on the body
      - [ ] should unbind both the scroll and body click listeners when a click is registered on the body
      - [ ] should only add click/scroll handlers when dropdown is changing to shown
    - when data uri anchor tag is clicked
      - [ ] should stop the event for incompatible browsers
      - [ ] should allow the event for compatible browsers
      - [ ] should raise an error for incompatible browsers

## FeatureInfoPanelViewModel
- [x] is initially not visible
- [x] is shown when terria.pickedFeatures is defined
- [x] is hidden when terria.pickedFeatures is set back to undefined
- [x] sanitizes HTML _now in Section_
- [x] displays a message while asychronously obtaining feature information
- ~~[ ] creates a temporary selected feature at the pick location while picking is in progress~~
- [x] removes all clock event listeners _now in Section_

## FeatureInfoPanelViewModel templating
- default
  - [x] exists
  - [x] formats large numbers without commas
- [x] uses and completes a string-form featureInfoTemplate if present
- [x] can use _ to refer to . and # in property keys in the featureInfoTemplate
- ~~[ ] must use triple braces to embed html in template~~
- [x] can use a json featureInfoTemplate with partials
- [x] sets the name from featureInfoTemplate
- [x] formats templated large numbers without commas
- [x] can format numbers with commas
- [x] can format numbers using terria.formatNumber
- [x] can format numbers using terria.formatNumber without quotes
- [x] handles non-numbers terria.formatNumber
- [x] can render a recursive featureInfoTemplate

## FeatureInfoPanelViewModel CZML templating
- [x] uses and completes a string-form featureInfoTemplate if present
- [x] uses and completes a time-varying, string-form featureInfoTemplate if present

**Comment by RacingTadpole** [comment]
## LegendSectionViewModel
- createForCatalogMember
  - [ ] returns undefined if CatalogGroup has no legendUrls
  - [ ] returns a LegendSectionViewModel if CatalogGroup has legendUrls
- for a single legend
  - [ ] correctly passes the url
  - [ ] correctly passes that the url is an image
  - [ ] correctly passes that the url is not an image
  - [ ] correctly reflects an image error
- for multiple legends
  - [ ] shows all urls correctly
  - [ ] correctly handles an error event on a single legend
- [ ] should generate urls with catalog item proxy
- [ ] should handle no legends as !proxiedLegendUrls

## LocationBarViewModel
- [ ] updates longitude and latitude on mouse movement in 2D

## MapProgressBarViewModel
- [ ] sets progress to the percentage of tiles not loaded
- [ ] always uses the floor percentage
- [ ] sets progress to 100 if remaining tiles === 0 for all values of max tiles
- [ ] resets progress to 100 on beforeViewerChanged

**Comment by RacingTadpole** [comment]
## SharePopupViewModel
- share url
  - [ ] includes whitelisted user properties
  - [ ] excludes non-whitelisted user properties
  - when sharing catalog members
    - [ ] serializes enabled items
    - [ ] serializes open groups
    - [ ] serializes an enabled item inside a closed group
    - [ ] serializes an open group and an enabled item in a flat map
    - [ ] filters out items with localData
    - [ ] indexes against id
    - [ ] indexes against path when id isn't available
    - [ ] filters out non-shareable properties
    - [ ] filters out name from the object
    - [ ] filters out id from the object
    - [ ] filters out non-enabled items
    - [ ] filters out open groups with a closed ancestor
  - when sharing picked features
    - [ ] should pass providerCoords as-is
    - [ ] should generate pickCoords from pickPosition
    - [ ] should include hash and name of picked vector features while excluding rasters
    - [ ] should include the hash and name of the selected feature
- embed url
  - [ ] includes whitelisted user properties
  - [ ] excludes non-whitelisted user properties
  - when sharing catalog members
    - [ ] serializes enabled items
    - [ ] serializes open groups
    - [ ] serializes an enabled item inside a closed group
    - [ ] serializes an open group and an enabled item in a flat map
    - [ ] filters out items with localData
    - [ ] indexes against id
    - [ ] indexes against path when id isn't available
    - [ ] filters out non-shareable properties
    - [ ] filters out name from the object
    - [ ] filters out id from the object
    - [ ] filters out non-enabled items
    - [ ] filters out open groups with a closed ancestor
  - when sharing picked features
    - [ ] should pass providerCoords as-is
    - [ ] should generate pickCoords from pickPosition
    - [ ] should include hash and name of picked vector features while excluding rasters
    - [ ] should include the hash and name of the selected feature

**Comment by RacingTadpole** [comment]
These ViewModels continue to exist in the New UI, so don't need any extra work:
- CatalogItemNameSearchProviderViewModel
- GNAFSearchProvider
- NominatimSearchProviderViewModel

**Comment by kring** [comment]
Pretty unlikely we'll see anything more happen on this.
