### ISSUE TITLE
Clicking on the chart panel should bring it in front of the feature info panel

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1691]
This used to work, but somewhere along the way it stopped. Extracted from #1427.

**Comment by kring** [comment]
Are you sure we want this?  The user can just close or collapse the feature info panel if it's in the way of the chart.  Having a dynamic z-order for our windows makes things a lot more complicated.

**Comment by AlexGilleran** [comment]
That ship has sailed, we already have dynamic z order 😬 . I think chloe did it, it's a pretty simple implementation in viewstate.

**Comment by kring** [comment]
...except for bugs like this and #1714.

**Comment by AlexGilleran** [comment]
Well, yeah, the chart hasn't implemented it (yet ?)

**Comment by AlexGilleran** [comment]
Although I would argue that the chart should always be below everything given that it's tiled, and floating stuff like feature info panels should always be over the top of it.

**Comment by kring** [comment]
Yep, exactly.  I just don't see the need for dynamically putting the chart on top.

**Comment by RacingTadpole** [comment]
That's a good argument. OK, I'll close this.
