### ISSUE TITLE
MapServer autolegend puts entries in wrong order

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1692]
When we let Terria create a legend automatically from an ArcGIS MapServer the entries in the legend come out in the wrong order:

<img width="322" alt="screen shot 2016-06-27 at 17 12 01" src="https://cloud.githubusercontent.com/assets/5283003/16371507/555eea58-3c8a-11e6-922b-8bd02db8da8d.png">

<img width="284" alt="screen shot 2016-06-27 at 17 12 11" src="https://cloud.githubusercontent.com/assets/5283003/16371517/59da9d5c-3c8a-11e6-88f4-ca0105c2a38a.png">

We should correct this so that it's at least in the same order in the Terria legend as the MapServer.

Bonus points if we can connect the continuous range somehow.

**Comment by stevage** [comment]
You mean not show a gap between those gradients? How do we know when to do that?

**Comment by meh9** [comment]
I don't know if we can, but when the MapServer also has a WMS for the same data it then seems to know that it's a range. I was hoping that there would be some way for us to recognise it as a range, but I don't know if it's possible. :)

**Comment by stevage** [comment]
Worst comes to worst, an optional config flag?

**Comment by meh9** [comment]
Yeah, I'm ok with a config flag.

There are a few GA layers that have ranges, and it would mean I could remove the WMS `legendUrl` specifically added in the config for those layers and use the much better looking TerriaJS MapServer autolegends.
