### ISSUE TITLE
NewUI: Make top right buttons configurable

### ISSUE THREAD

**Issue by rdengate** [TerriaJS/terriajs#1694]
There's no way for the user to choose which buttons on the top right (compass, locate me, zoom) should be present by changing config options. It would be great to have this, because for the measure tool we're about to have a button there which most maps won't want.

Currently the height of the buttons is hard coded which makes it doubly difficult to have one that's turned on and off.

@AlexGilleran has an idea of how this could be done.

**Comment by kring** [comment]
This was fixed in #1713.
