### ISSUE TITLE
Catalog add icon does a dance while loading

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#1703]
Open the catalog and click on a layer.  While the layer loads for the preview, the `(+)` icon turns into a loading icon and does a little dance to the right.

![out](https://cloud.githubusercontent.com/assets/924374/16408038/1c261998-3d5a-11e6-9a0b-6ad39eefcd8d.gif)

**Comment by chloeleichen** [comment]
This will be fixed when the new icons are in

**Comment by kring** [comment]
Fixed by #1710.
