### ISSUE TITLE
Add spec that fails on newest (bad) Leaflet version

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1704]
See discussion at https://github.com/TerriaJS/terriajs/pull/1701:

>  Ideally, we'd write tests that fail when  ... [leaflet is] upgraded, so greenkeeper can do its thing... That might be pretty tricky.

**Comment by stevage** [comment]
What would the test do? Why can't we use latest Leaflet?

**Comment by kring** [comment]
Totally busted on retina displays I believe.  e.g. the preview map doesn't work.

**Comment by RacingTadpole** [comment]
@steve9164 can we close this one now?

**Comment by kring** [comment]
Yep.
