### ISSUE TITLE
CZML Feature Info is broken in newui

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1705]
There are the three CZML examples under #test. In the New UI:
- Embedded CZML - just shows the feature info panel with the feature name and no content.
- Large feature info box - works (yay! but oh no - this fails in the old UI now.)
- Simple test - as for embedded CZML

Also (per #1260) if you drag in `withProperties.czml` it shows the text "undefined".

![image](https://cloud.githubusercontent.com/assets/1757858/16437521/085abf04-3deb-11e6-8497-18f4c3de4708.png)
![image](https://cloud.githubusercontent.com/assets/1757858/16437573/7530256a-3deb-11e6-8c58-0cea4b337370.png)

![image](https://cloud.githubusercontent.com/assets/1757858/16437528/1f0bb762-3deb-11e6-8bf9-3fb7eb4d0ebd.png)

Also, these seem to be treated as time-varying CZML, ie. they are updating every tick (with no change).

**Comment by kring** [comment]
Fixed by #1708.
