### ISSUE TITLE
Update Data Catalogue UI (layout, add/remove buttons)

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#1707]
See updated design here: https://invis.io/7D70K4VUZ#/151757718_4

Note: remove 'back to map' button (no longer required now that we auto-dismiss the catalogue when data is added)

Reference image: 
![data catalogue - selected 2x](https://cloud.githubusercontent.com/assets/5292858/16441231/18b1a1bc-3e0c-11e6-8672-5a8c80b22cda.jpg)

**Comment by kring** [comment]
Fixed by #1726.
