### ISSUE TITLE
Feature info / drop down panel z-order wrong after adding a chart

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#1714]
After #1713 (not that it was better before, necessarily):
1. Visit http://localhost:3001/#build/TerriaJS/test/init/charts.json
2. Add `Sheep Stations`
3. Click a station.
4. Click Expand (the chart at the bottom appears)
5. Click the Map button.

The Map settings will appear underneath the feature info.

**Comment by RacingTadpole** [comment]
Also see #1691.

**Comment by kring** [comment]
Fixed by #1774.
