### ISSUE TITLE
Add Data conversion service is no longer offered

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1723]
This guy never comes up in the new ui:
![image](https://cloud.githubusercontent.com/assets/1757858/16474926/f424cdd0-3ebd-11e6-878d-329c1818b4c1.png)

Eg. try typing in "bad" as the Add Data URL.

**Comment by RacingTadpole** [comment]
This is a tricky one. Master and newui have identical 
- `createCatalogMemberFromType`, 
- `createCatalogItemFromFileOrUrl` and 
- `createCatalogItemFromUrl` 

files, eg. `git diff newui lib/Models/createCatalogMemberFromType.js` when on master gives nothing.

And yet, this line in `createCatalogItemFromFileOrUrl`: 

`return when(createCatalogItemFromUrl(name, terria, isUrl)).then(function(newItem) {...`

triggers the `then` in master, but not in `newui`, when `createCatalogItemFromUrl` returns `undefined`.

Why?

**Comment by RacingTadpole** [comment]
Sorry @kring, I didn't see you'd self-assigned this... I'm going to happily hand it over to you then :-)

**Comment by kring** [comment]
hmm that's pretty dodgy.  I'm happy to look at it, but also don't mind if you continue to do so. ;)

**Comment by kring** [comment]
Looks like it's getting tripped up while trying to get confirmation for uploading the file to the conversion service:

``` js
    PopupMessageConfirmationViewModel.open('ui', {
        confirmText: 'Upload',
        title: 'Use conversion service?',
        message: message,
        confirmAction: function confirmAction() {
            d.resolve(true);
        },
        enableDeny: true,
        denyAction: function denyAction() {
            this.close();d.resolve(false);
        }
    });
```

That doesn't work anymore in the new UI.
