### ISSUE TITLE
Layers from ncWMS2 don't seem to display properly

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#1733]
I'm trying to visualize WMS layers from the new ncWMS2 service that comes with the Unidata THREDDS Data Server version 5.0. 

The getCapabilities seem okay:
http://thredds-jumbo.unidata.ucar.edu/thredds/wms/grib/NCEP/GFS/Global_2p5deg/Best?service=WMS&version=1.3.0&request=GetCapabilities

And getMap requests work:
http://thredds-jumbo.unidata.ucar.edu/thredds/wms/grib/NCEP/GFS/Global_2p5deg/Best?LAYERS=Best/Temperature_height_above_ground&ELEVATION=2&TIME=2016-06-30T00%3A00%3A00.000Z&TRANSPARENT=true&STYLES=default-scalar%2Fx-Rainbow&COLORSCALERANGE=200%2C310&NUMCOLORBANDS=20&LOGSCALE=false&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&FORMAT=image%2Fpng&SRS=EPSG%3A4326&BBOX=-180,-90,180,90&WIDTH=256&HEIGHT=256

But nothing seems to show up when I add this layer to the new UI instance at:
http://preview.nationalmap.terria.io/

![2016-06-30_8-04-16](https://cloud.githubusercontent.com/assets/1872600/16487506/59d322a0-3e99-11e6-8962-fb5a3a10134a.jpg)

**Comment by kring** [comment]
@rsignell-usgs it seems to be working ok here, but that server is _very_slow: tens of seconds per tile for the tiles in the vicinity of Australia.

![image](https://cloud.githubusercontent.com/assets/924374/16488554/6930caa6-3f14-11e6-9a70-4634ba5b7397.png)

You'll probably need to pause the animation, otherwise the clock will have moved on well before any tiles are loaded.

**Comment by kring** [comment]
I should mention, what I'm see on the globe is much less interesting then in your GetMap request above.  It's mostly all black.  I'm guessing that's because you've specified an elevation, style, colorscalerange, etc., and I haven't.

**Comment by rsignell-usgs** [comment]
@kring, my bad (again).   You are correct, of course.   I got confused by by an error that was actually a `DescribeLayer` request, not a `GetMap` request.  And yes, we need to set the `COLORSCALERANGE` to get something that looks decent.    Luckily, with your help, we have that in the works!  :smile_cat:  https://github.com/USGS-CMG/terriajs-dive/issues/10
