### ISSUE TITLE
Pin badge bar on top of workbench

### ISSUE THREAD

**Issue by chloeleichen** [TerriaJS/terriajs#1739]
<img width="354" alt="screen shot 2016-07-01 at 11 44 47 am" src="https://cloud.githubusercontent.com/assets/7508939/16509551/73ffb39e-3f81-11e6-993e-0d901652e296.png">

When scrolling the workbench, the highlighted area should not scroll with the rest of the workbench. So is the badge bar in the side panel search

**Comment by kring** [comment]
Fixed by #1740
