### ISSUE TITLE
ArcGIS MapServer unknown Spatial Reference prevents tiles loading

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1741]
When you enable a ArcGIS MapServer layer with an unknown `Spatial Reference` an error message is printed in the console after which all tile loading stops until the layer is disabled. The console error message reads:

`An error occurred in "x": Tile spatial reference WKID 28355 is not supported.`

The MapServer in question is:

http://data.actmapi.act.gov.au/arcgis/rest/services/actmapi/imagery2004mga/MapServer

If a layer has a fatal error like that we should disable it, show an error message to the user why, and go on our way and load all remaining tiles. No UI error message is shown either in the OldUI or NewUI.

For bonus points we should support EPSG:28355, http://epsg.io/28355

**Comment by meh9** [comment]
Share link with the problem:

http://nationalmap.gov.au/#share=rXMg5a

**Comment by meh9** [comment]
It's weird, because this other service from the same custodian works even though it also says it's 28355. It doesn't show the error message, and when we ask it for EPSG:3857 tiles it returns them fine.

http://data.actmapi.act.gov.au/arcgis/rest/services/actmapi/da/MapServer

http://nationalmap.gov.au/#share=c5xpss

**Comment by kring** [comment]
Hmm ok we probably can't reasonably support this server.  It has a precached map cache in a projection we don't support, and it has disabled dynamic requests, so we can't ask the server to reproject for us.  Reprojecting on the client would be extremely expensive.

But TerriaJS is supposed to just disable that layer and go on its way.  I'll look into why it's not.

**Comment by kring** [comment]
Your second server isn't precached, it just happens to present the bounding box in 28355, which we support.

**Comment by meh9** [comment]
Aha.

**Comment by kring** [comment]
Fixed by #1760.
