### ISSUE TITLE
Newui Mobile bugs

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#1749]
There are quite a few bugs with the mobile newui. I'll document each of them in the comments below.

**Comment by tephenavies** [comment]
![screenshot_2016-07-04-17-05-31](https://cloud.githubusercontent.com/assets/13863530/16570746/2be02f92-428f-11e6-9e19-bc9e8ce2231e.png)

Problem: The search button has been pressed, but the data explorer is showing with no way to hide it (done button missing)

Steps to reproduce on mobile android:
1. Press data
2. Select the first catalogue item in the first group
3. Add to map from preview
4. Press search button

**Comment by steve9164** [comment]
![screenshot_2016-07-04-17-08-13](https://cloud.githubusercontent.com/assets/13863530/16570787/29313f6a-4290-11e6-8f69-3afb37c4d48b.png)

**Comment by tephenavies** [comment]
![screenshot_2016-07-04-16-38-47](https://cloud.githubusercontent.com/assets/13863530/16570831/7afb2a58-4291-11e6-81bd-d5fb91d1bcbf.png)

Problem: Legend shows up when search button pushed and the "Done" button multiplies

Steps to reproduce on mobile android:
1. Add a dataset with a legend
2. Press the view legend button
3. Press the search button
4. Press "Done"
5. Press the search button again

By repeating steps 4 & 5, the bar at the top of the panel fills with "Done"s

**Comment by kring** [comment]
I believe these are no longer an issue.
