### ISSUE TITLE
Crosshair shown above sidebar

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1762]
At http://newui.aremi.nicta.com.au/prototype/, enable a layer, click (in Chrome) then pan the map, and see this:

![screenshot 2016-07-07 11 44 20](https://cloud.githubusercontent.com/assets/678344/16640161/09bf2d54-4439-11e6-8cab-089e235355e4.png)

**Comment by chloeleichen** [comment]
Can't replicate this, @stevage do you still have this issue?

**Comment by stevage** [comment]
Yes, I still see this as http://newui.aremi.nicta.com.au/renewables/. I see it in Firefox too. And on both my Retina and non-Retina screen.

![screenshot 2016-07-20 13 39 56](https://cloud.githubusercontent.com/assets/678344/16974395/79c6132e-4e7f-11e6-8c6c-7a4a5edf07ef.png)

**Comment by stevage** [comment]
And at staging.nationalmap.nicta.com.au:

![screenshot 2016-07-20 13 42 26](https://cloud.githubusercontent.com/assets/678344/16974430/d7c34c08-4e7f-11e6-9f32-bbf084718c68.png)
