### ISSUE TITLE
Nicer authentication screens

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1770]
When we use HTTP simple authentication to restrict access to sites, users get a page like this:

<img width="414" alt="screenshot 2016-07-08 11 46 32" src="https://cloud.githubusercontent.com/assets/678344/16675152/b71a6388-4501-11e6-9f97-53997236e7fe.png">

Is there anything we can do to make this nicer? In particular:
- It's a modal
- Chrome's password saving (and 1Password) don't seem to work
- It's ugly and not at all in the theme..

**Comment by kring** [comment]
Not to my knowledge, it's an automatic browser thing.

**Comment by kring** [comment]
The ultimate solution is to not use basic auth, because it has lots of problems far more serious than this one. ;)

**Comment by stevage** [comment]
Ok, if we can't do it just at the client end, what are the options server side?
