### ISSUE TITLE
Colours with low opacity vary with background, leading to low contrast in some cases

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#1772]
This currently applies to scrollbars and boxes with `background: $overlay` among others.

Scrollbars are fine on white, but hard to see on dark grey because they have low opacity:
![screen shot 2016-07-08 at 15 58 25](https://cloud.githubusercontent.com/assets/13863530/16678696/e69e7554-4524-11e6-95b4-6f23d240ed67.png) ![screen shot 2016-07-08 at 16 00 36](https://cloud.githubusercontent.com/assets/13863530/16678726/28cd9f4a-4525-11e6-8af6-9ebf5b650ece.png)

It also means that an `$overlay` coloured box on dark grey works, but doesn't work on white (e.g. in the mobile ui legend).

The fix would be to use `background: $overlay` only in places where the opacity is wanted, not for a specific colour and to repurpose or create a new variable for the second SidePanel colour.

**Comment by kring** [comment]
Good idea, but I think we can live with this for the 15 July release, so I'm moving it out of the milestone.

**Comment by chloeleichen** [comment]
@kring @steve9164 

what color should be used then? I think the dark scroll bar is quite nice.

Here is a lighter alternative, which is not as nice in my opinion
<img width="123" alt="screen shot 2016-07-21 at 2 48 46 pm" src="https://cloud.githubusercontent.com/assets/7508939/17011527/401238dc-4f52-11e6-8df5-32c15c51d387.png">

Or we can do blue?
<img width="92" alt="screen shot 2016-07-21 at 2 50 26 pm" src="https://cloud.githubusercontent.com/assets/7508939/17011554/8311a122-4f52-11e6-8c9c-2e773fe557e7.png">

**Comment by kring** [comment]
I don't have any problem with the color - I'm happy to leave that to you or Phil or whatever - but I think Steve makes a good point that the color should be specified as a color, not just as an opacity.

**Comment by kring** [comment]
I think this has been fixed.  The scrollbar on the workbench is lighter than the background now, instead of darker.
