### ISSUE TITLE
Feature Information popup is empty

### ISSUE THREAD

**Issue by leylines** [TerriaJS/terriajs#1776]
The "feature information popup" is empty in terriajs-versions > 3.2.1 for czml, kml and maybe other formats.
Attached a czml-file for testing purposes :-)

Thank you for your wonderful work,

Jörg

[test.txt](https://github.com/TerriaJS/terriajs/files/354153/test.txt)

**Comment by tephenavies** [comment]
I couldn't get the attached test file to work because of something in the description (perhaps that's another bug? It seems to be valid JSON), so I replaced the description with `"description":"text"`

Commit 427f5253b468 is the cause of the bug. Specifically if `result == {}`, then 

```
result.terria.coords = {...}
```

will throw.

**Comment by leylines** [comment]
With terriajs-versions > 4.0 the popup appears and has the czml-defined information. I close the ticket.

Thank you.

Jörg
