### ISSUE TITLE
CSW hierarchical catalogue problems

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1777]
It appears that sometime in the last couple of months, the code that parses a CSW catalogue and turns it into a hierarchical tree has changed.

The AREMI Wave Atlas categories now shop up as two long lists of layers instead of having subcategories like they used to. (There is one exception, the Wave Model subcategory of "Direction of Maximum Directionally Resolved Wave Power", I don't know what makes this different.) See this share which has two layers enabled, one in each long flat list:

http://nationalmap.gov.au/renewables/#share=MMbz3c

The Wave Atlas guys run their own frontend that loads the same catalogue in the exact same way we do but using older code, and they still have the layers in subcategories. Go to this URL and then see the categories in "Renewable Energy -> Wave -> Australian Wave Atlas (I couldn't get the sharing to work):

http://awavea.csiro.au/

(Note that this is using the OldUI, but the results are currently the same in the NewUI, the AREMI NewUI sharing doesn't work at the moment.)

**Comment by kring** [comment]
Fixed by #1777.
