### ISSUE TITLE
Poor performance adding WMS with lots of time intervals

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#1778]
Adding this WMS group using the Add Data feature takes ages (I haven't seen it complete yet) and locks up the UI in the process:
http://geoport.whoi.edu/thredds/wms/coawst_4/use/fmrc/coawst_4_use_best.ncd?service=WMS&version=1.3.0&request=GetCapabilities

The time is spent building time intervals.  We should be able to make this go much faster.

**Comment by meh9** [comment]
I believe that this is actually affecting AREMI as well - most of our timeseries layers now causes the browser to become completely unresponsive.

To test, build the latest aremi-natmap#newui, and try loading either of these two layers:

Renewable Energy -> Solar -> Solar Satellite DNI - 2014
Electricity Infrastructure -> Network Opportunities -> Available Capacity

It must have broken fairly recently - the current newui build we have in prototype is a week or two old, and these layers work fine there.

**Comment by kring** [comment]
I think that might be a separate problem, but in any case it sounds bad!  I'll take a look today.

**Comment by meh9** [comment]
Ok, thanks, let me know if you want me to log another issue, I just thought these sounded very similar.

**Comment by kring** [comment]
Yeah, they do sound similar.  The reason I say they're probably different is because the performance problem with the geoport WMS was very specific to the WMS interval handling.  No need to write a separate bug, at least until I investigate a bit more.

**Comment by kring** [comment]
Removed AREMI label because the problem described by @meh9 above was a separate problem and is now fixed.
Nahid to take a look at this.
