### ISSUE TITLE
Better Ckan resource type configuration

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1795]
@kring and I talked about the mess with all the resource-format properties on CkanCatalogGroup, and how you still have to manually specify a format query string that finds them.

A better way:

```
resourceFormats: [
{
   "type": "wms", // matches Terria item type string
   "formats": ["WMS", "wms"], // strings dependent on the Ckan configuration
   "alwaysInclude": true // always add any WMS layer in any dataset
},
{
  "type": "kml",
  "formats": ["kml", "KML", "kmz", "KMZ"],
  "alwaysInclude": false // only add KML layers if no layers defined earlier in this list are present
}
```

From this we can also generate the `fq=(res_format:wms OR ...)` URL string.

**Comment by nf-s** [comment]
Done - see https://github.com/TerriaJS/terriajs/pull/5987
