### ISSUE TITLE
Graphs come up using both square and round radio buttons

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/terriajs#1818]
![image](https://cloud.githubusercontent.com/assets/900555/16904032/befb1bec-4cd1-11e6-9ec4-97c5320675bb.png)

**Comment by chloeleichen** [comment]
Arthur says:

> the rationale is that it doesn’t know it’s a chart until it has checked for region mapping, and geo csvs have false, charts have true
> 
> maybe the solution is to track `allowMultiple`
> 
> (however, when you open a chart from a Feature Info preview chart, it does know it is a chart from the start, so it starts off true)
