### ISSUE TITLE
chart conflicts

### ISSUE THREAD

**Issue by chloeleichen** [TerriaJS/terriajs#1831]
if i turn on XY plot and Time Series, and check Capacity and Power in Time Series, then I can’t check X or Y in XY plot and I get this error: 

```
Warning: ChartPanel is accessing isMounted inside its render() function. render() should be a pure function of props and state. It should never access something that requires stale data from the previous render, such as refs. Move this logic to componentDidMount and componentDidUpdate instead.
```

@RacingTadpole

**Comment by RacingTadpole** [comment]
Thanks. The error happens when you try to switch the units of the x-axis in the chart panel.
