### ISSUE TITLE
Timeseries performance problem

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1832]
There appears to be a performance problem when previewing and the adding and playing a timeseries layer.
## Steps to see problem:
1. Open the catalogue and add click to preview the particular timeseries layer.
2. Add the layer to the map.
3. Press play on the timeseries.
   Observe how when the timeseries is playing through 2016 it progresses slowly, and one into 2017 it starts progressing very jerkily.
## Steps to show the layer without performance problem:
1. Do the steps above and then generate a share url.
2. Follow the share url which adds the layer to the map without going through the catalogue layer preview step.
3. Press play on the timeseries.
   Observe how the entire timeseries plays smoothly without performance problems.

**Comment by AlexGilleran** [comment]
Still can't reproduce it @meh9 - what browser are you using?

Not sure if this is why I can't reproduce it, but that layer (the secret one shared elsewhere) doesn't actually show anything for me either.
