### ISSUE TITLE
Difficult to select/copy URLs on preview page

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#1833]
![image](https://cloud.githubusercontent.com/assets/924374/16942221/41c95640-4dd8-11e6-8e88-7b54ed159868.png)

In the old UI, clicking in the URL textbox (like the one in the screenshot above) would select the whole thing so it was easy to copy.  In the new UI, there's no auto-select, no cursor, and selecting by clicking and dragging is error prone at best.

**Comment by chloeleichen** [comment]
we can do the same like the url in the share panel ? @kring
