### ISSUE TITLE
range slider resize not removed after unmount

### ISSUE THREAD

**Issue by chloeleichen** [TerriaJS/terriajs#1841]
This issue is just a record of the following issue that will be fixed with module updates:

When resize from big screen size to small size after adding a dataset, there is an error `index.js:77 Uncaught TypeError: Cannot read property 'offsetWidth' of null`, this is because the react-range-slider module version 1.0.3 does not remove event listener on unmount,  this is fixed in its repo, just waiting for a new release of the npm module.

**Comment by RacingTadpole** [comment]
Unfortunately they're still on 1.0.3...

**Comment by kring** [comment]
We're on 2.x now and I haven't seen this error in ages, so closing this.
