### ISSUE TITLE
Reduce disclaimer size in 2d (to match 3d)

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1865]
With a handful of items enabled, here is the disclaimer in 3D:

![image](https://cloud.githubusercontent.com/assets/1757858/17120652/1298cb38-5311-11e6-84e6-217d69b05dfc.png)

and just changing it to 2D increases its size enormously:

![image](https://cloud.githubusercontent.com/assets/1757858/17120659/274a07c2-5311-11e6-99cb-f374e352cf1a.png)

On a laptop screen, the disclaimer takes up 20% of the height of the map. Can we reduce it?

This example is taken from http://terria.io/embedded-natmap/ (but switched to use the new UI).

**Comment by kring** [comment]
Closing in favor of #2161.
