### ISSUE TITLE
Charts units can be mis-read

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1866]
When I add 3 or more charts to the Chart Panel, all with the same units (MW), sometimes the last one added appears without its units, eg:

![image](https://cloud.githubusercontent.com/assets/1757858/17121200/451be7e4-5315-11e6-89dc-3c3ab9321645.png)

**Comment by meh9** [comment]
Maybe related to #1849?

**Comment by RacingTadpole** [comment]
oh yes - that's the same thing.
