### ISSUE TITLE
Catalog UI does not show selected group after it's closed and re-opened

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#1868]
When you click a group in the catalog UI, the group is highlighted in blue and the name of the group, plus its description and other info, is displayed in the preview area.  If you then close the explorer window and re-open it, the group is still displayed in the preview panel but is no loner highlighted in blue on the left.

This came up as a minor issue in GA's testing of the new NationalMap release.

**Comment by RacingTadpole** [comment]
I'm just reviewing #1902 and I'm not sure I understand the problem. For me, master shows this, even after closing and re-opening the "Add Data" panel:
![image](https://cloud.githubusercontent.com/assets/1757858/17286337/4975937a-580c-11e6-9e62-326ab410e859.png)
Is that the highlighting in blue you mean?

**Comment by kring** [comment]
Yeah it works fine when an item is selected, but not when a group is selected.
