### ISSUE TITLE
Need consistent spelling: Catalogue versus Catalog

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#1872]
From GA's NationalMap test report:

![image](https://cloud.githubusercontent.com/assets/924374/17123748/1d7cc316-5329-11e6-9afa-4f6f783da885.png)

**Comment by chloeleichen** [comment]
Should we update all Catalog in the UI into Catalogue since we are in Australia? But `Catalog` is used other places, e.g, in `CHANGES.md`, should we change that too? And other spellings such as `color`? @kring

**Comment by kring** [comment]
The source code should all be American English (color, catalog).  The UI should be Australian English (colour, catalogue).

**Comment by kring** [comment]
(really we need a proper localization (localisation?) mechanism)

**Comment by RacingTadpole** [comment]
We actually use both catalogue and catalog in the UI currently, eg:
![image](https://cloud.githubusercontent.com/assets/1757858/20199664/4d55b2d8-a800-11e6-91c0-4c727310e1f3.png)
