### ISSUE TITLE
Support ArcGIS FeatureServer

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1877]
As described here http://resources.arcgis.com/en/help/rest/apiref/index.html?featureserver.html

Eg. 
https://sampleserver6.arcgisonline.com/arcgis/rest/services
https://sampleserver6.arcgisonline.com/arcgis/rest/services/Wildfire/FeatureServer
https://sampleserver6.arcgisonline.com/arcgis/rest/services/Wildfire/FeatureServer/0

It looks like to get actual geometry data you need a URL like this:
https://sampleserver6.arcgisonline.com/arcgis/rest/services/Wildfire/FeatureServer/query?f=json&layerDefs={0:"1=1"}

Note with MapServers, these are both ArcGisCatalogGroups:
- http://www.ga.gov.au/gis/rest/services/earth_observation/Landcover_WM/MapServer, which contains a single layer, land cover.
- http://www.ga.gov.au/gis/rest/services/, which contains a number of ArcGisCatalogGroups following the hierarchy below.

![image](https://cloud.githubusercontent.com/assets/1757858/17164204/4bdede98-5409-11e6-8bf3-ec1345083a8a.png)

```
{
   "sharedCatalogMembers":{
      "Root+Group/User-Added+Data/":{
         "isOpen":true,
         "type":"esri-mapServer-group",
         "parents":[
            "Root+Group/User-Added+Data"
         ]
      },
      "Root+Group/User-Added+Data//earth+observation":{
         "isOpen":true,
         "type":"esri-mapServer-group",
         "parents":[
            "Root+Group/User-Added+Data",
            "Root+Group/User-Added+Data/"
         ]
      },
      "Root+Group/User-Added+Data//earth+observation/Landcover+WM":{
         "isOpen":true,
         "type":"esri-mapServer-group",
         "parents":[
            "Root+Group/User-Added+Data",
            "Root+Group/User-Added+Data/",
            "Root+Group/User-Added+Data//earth+observation"
         ]
      }, ...
   }
}
```

**Comment by RacingTadpole** [comment]
There's relevant code to read ESRI features already in `featureDataToGeoJson.js`.

**Comment by tobybellwood** [comment]
there's also some clues possibly in https://github.com/Esri/esri-leaflet - they've got it in leaflet...

**Comment by RacingTadpole** [comment]
cool, thanks!
