### ISSUE TITLE
Always show Loading page for user-added data

### ISSUE THREAD

**Issue by rdengate** [TerriaJS/terriajs#1880]
When dragging and dropping a csv that takes a long time to load (e.g. one with addresses that will be geocoded), the User-Added Data seems only to show up sometimes for the first csv added. At other times, and for subsequent csvs, the User-Added Data panel appears listing the csv with a loading icon.

We want to make sure that it's clear the csv is loading even if the workbench isn't visible. In the screenshot below, for the first csv added you can see that the User-Added Data panel has not appeared (but a 'back' button has been added which will take you to it), whereas once the second csv is dragged and dropped it appears as loading in User-Added Data.

![spinner_in_my_data](https://cloud.githubusercontent.com/assets/3466267/17196067/4757e198-54a5-11e6-9da5-e88ce6dac6a6.png)

**Comment by chloeleichen** [comment]
Fixed in the new my data ui
