### ISSUE TITLE
Enhancing the min/max WMS request behaviour

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#1888]
The new ability to specify COLORSCALERANGE min/max (https://github.com/TerriaJS/terriajs/issues/774) is great, but I just discovered the hard way that if you reverse the min/max values you get a very cryptic error.   

Could we catch the case where the user inputs a max value that is less than the min value?

And could we also reverse the order of the widgets?  (max on top, min on bottom, so it matches the sense of the y axis on the legend)

Here's a screen grab of my error:
![2016-07-28_13-44-37](https://cloud.githubusercontent.com/assets/1872600/17223538/02387106-54cb-11e6-96ea-6df9986d5de4.png)

@jiwalker-usgs can you take a look at this?

**Comment by rsignell-usgs** [comment]
Here is the WMS endpoint I was using in the test above:
http://geoport-dev.whoi.edu/thredds/wms/clay/usgs/users/zdefne/run076/his/00_dir_roms_display.ncml?service=WMS&amp;version=1.3.0&amp;request=GetCapabilities

**Comment by rsignell-usgs** [comment]
@kring, can you please add this to the USGS CDI milestone
https://github.com/TerriaJS/terriajs/issues?q=is%3Aopen+is%3Aissue+milestone%3A%222016-08-31+USGS+CDI%22

**Comment by kring** [comment]
Yep, done.
