### ISSUE TITLE
GeoJSON shapes with a fill to them flash when another feature with background is picked

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/terriajs#1892]
To reproduce, add the "Test styled and unstyled features" layer from "TerriaJS test data / GeoJSON" with `#test` on the URL and click one of the triangles:

![image](https://cloud.githubusercontent.com/assets/900555/17238948/83ee3590-55a3-11e6-8668-c776f7c9b0f6.png)

The other shapes will flicker when the feature info box comes up.

This was rare before but it affects other layers that delegate to GeoJSON, like ESRI features.

**Comment by kring** [comment]
I can't reproduce this in 2D or 3D anymore, I think it's been fixed.
