### ISSUE TITLE
Thredds colour scale controls only appear on second add

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1904]
When adding a Thredds raster layer, the new colour scale controls only appear when if you remove and then add the layer a second time.

To test this, go to AREMI (http://nationalmap.gov.au/renewables/) and add Renewable Energy -> Solar -> Annual climatology.

However, if you specify a default colour scale range, then it _does_ appear on the first Add of the layer:

```
  "parameters": {
    "colorscalerange": "3.5,31"
  },
```

Below testing is performed without a default set. Note that AREMI is adding a default in the next release, so if testing after Aug 19 this will require that you remove the default to see the problem.

First time:

<img width="354" alt="screen shot 2016-08-01 at 11 27 14" src="https://cloud.githubusercontent.com/assets/5283003/17280955/f85e5d4a-57da-11e6-9ca4-24d49225dfde.png">

Removed the layer and added it a second time:

<img width="349" alt="screen shot 2016-08-01 at 11 27 29" src="https://cloud.githubusercontent.com/assets/5283003/17280962/09780c70-57db-11e6-9584-ea270545f528.png">

**Comment by kring** [comment]
This is no longer a problem.
