### ISSUE TITLE
Crosshair doesn't follow moving features in Leaflet

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1925]
In 3D (Cesium), when a moving feature is selected, the crosshairs move with it.

But in 2D (Leaflet) the crosshairs stay static, where the feature was when it was selected.

This happens with CZML files (eg. bird migrations) and with the new moving-feature csv files (once #1924 is merged, eg. http://localhost:3003/#build/terriajs/test/init/csv.json with "Moving feature (sampled)").

**Comment by kring** [comment]
This is still a problem (to my surprise).
