### ISSUE TITLE
Shift+drag to zoom rectangle no longer drawn with new Cesium

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#1928]
When upgrading to use terriajs-cesium 1.23 and trying to hold down the shift key and clicking and dragging with the mouse to select a rectangle to zoom to, the rectangle is no longer being drawn, so you are kinda zooming blind.

**Comment by rdengate** [comment]
I've tested this with GEOGLAM and it still seems to work with me. Latest Terria and TerriaMap, both using terriajs-cesium 1.23.2, and the rectangle is definitely visible when shift-click dragging.

**Comment by rdengate** [comment]
I just noticed it's missing in AREMI, though. Interesting...

**Comment by rdengate** [comment]
Now missing in NationalMap#master, and affecting also the rectangle that's drawn for WPS functions.

**Comment by rdengate** [comment]
See https://github.com/TerriaJS/terriajs/issues/2084

**Comment by rdengate** [comment]
Works with the later terriajs-cesium version we're using.
