### ISSUE TITLE
Share Links not usable unless shortening service available

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/terriajs#1934]
The problem is that the error pop up stops you from ever being able to uncheck the "use shortening service" box.

**Comment by chloeleichen** [comment]
is that the share panel? Where are you seeing this issue? http://nationalmap.gov.au/ is working fine for me and I don't get the checkbox on localhost @AlexGilleran

**Comment by AlexGilleran** [comment]
This is on localhost. Yeah the share panel, if you don't have a shortener configured.

**Comment by AlexGilleran** [comment]
(Sorry about the shitty description, I mainly made this so I wouldn't forget about it)
