### ISSUE TITLE
GeoJSON 'stroke-opacity' style options raises error

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1940]
If you try to set `"style": {"stroke-opacity": 0.8}` on a geojson data source, there is an error here: https://github.com/TerriaJS/terriajs/blob/master/lib/Models/GeoJsonCatalogItem.js#L420

It looks easy to fix - there is no `options.stroke` defined at that point.

**Comment by nf-s** [comment]
Not relevant to v8
