### ISSUE TITLE
WPS contextItem is not shown during location selection

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1942]
This was brought up in #1933 and still remains.

The analysis study area flickers but then disappears during the selection.

**Comment by rdengate** [comment]
@RacingTadpole what's the contextItem, sorry?

**Comment by RacingTadpole** [comment]
If you go to AREMI and add this data:

![image](https://cloud.githubusercontent.com/assets/1757858/18458264/0cede930-79a3-11e6-97e9-366c08ed022e.png)

Then choose an analysis, and hit "select location". You'll see the sea around Australia flash for a second then disappear - that's the `contextItem`. (It's actually the Analysis Study Area item.)

**Comment by rdengate** [comment]
aha, I see. Thanks!
