### ISSUE TITLE
Error message during `npm run deploy`

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1944]
Not sure how critical this is, but let's fix it:

`Potentially unhandled rejection [2] Error: Couldn't find 'inherits' line in .../nationalmap/node_modules/terriajs/lib/Models/AsyncFunctionResultCatalogItem.js`

**Comment by RacingTadpole** [comment]
This may be causing the doc build to fail.

**Comment by kring** [comment]
Fixed by #2049.
