### ISSUE TITLE
Custom font download

### ISSUE THREAD

**Issue by chloeleichen** [TerriaJS/terriajs#1945]
Since some government computers cannot download custom font, it seems that our google fonts fall back to `helvetica`.
'
I think it's worth a try loading font data inline using Base64 encoding. Here is an example of it: https://raw.githubusercontent.com/ustwo/ustwo.com-frontend/master/src/app/lib/font.css

**Comment by chloeleichen** [comment]
base64 encoding doesn't solve the problem

**Comment by kring** [comment]
Nothing more to do here, right?  I'm closing it.
