### ISSUE TITLE
Leaflet print is broken again

### ISSUE THREAD

**Issue by chloeleichen** [TerriaJS/terriajs#1949]
@nahidakbar ゴッド knows why

**Comment by nahidakbar** [comment]
???

**Comment by chloeleichen** [comment]
because you are ゴッド 😆

**Comment by AlexGilleran** [comment]
https://www.google.com.au/search?q=%E3%82%B4%E3%83%83%E3%83%89&source=lnms&tbm=isch&sa=X&ved=0ahUKEwis2NrR5cLOAhUBk5QKHQN_CrkQ_AUICCgB&biw=1280&bih=636

**Comment by kring** [comment]
Fixed by PR above.
