### ISSUE TITLE
Timeslider formatting in CKAN previewer truncated/overlapping

### ISSUE THREAD

**Issue by tobybellwood** [TerriaJS/terriajs#1961]
As seen on https://data.gov.au/dataset/sa3-region-innovation-data/resource/df576aff-c584-42c8-a590-1a8c24b7fccf?view_id=dd69dc2b-172d-4ea5-9e63-ac207a05ba3e

Timeslider starts under the control buttons, and doesn't appear until 40% across - I'm assuming it's a small screen issue too?

![image](https://cloud.githubusercontent.com/assets/4373945/17733812/c159e060-64bb-11e6-88fa-9dbc5958e2de.png)

**Comment by kring** [comment]
The link above looks ok to me now, I think this has been fixed.
