### ISSUE TITLE
Cannot share a map with a CompositeCatalogItem on the workbench

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1975]
I've added a `type: composite` item to the map in an iframe, and when I share it, it has an `items` array whose elements include a `nameSortKey` array. This seems to cause a problem when I try to open the share link: I get an error in `updateFromJson`:

`TypeError: Cannot set property nameSortKey of #<v> which has only a getter`

**Comment by nf-s** [comment]
Not relevant to v8
