### ISSUE TITLE
Vector tile based region mapping doesn't work in IE9

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#1979]
There are no warnings or errors that I see, the regions simply fail to appear.

**Comment by kring** [comment]
(From #1912)

**Comment by tephenavies** [comment]
How should I test IE9?

**Comment by kring** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by tephenavies** [comment]
Primary findings:
- `pbf` doesn't work with IE9 out-of-the-box (https://github.com/mapbox/pbf/issues/32)
- Cesium's `loadArrayBuffer` doesn't work (because `ArrayBuffer` doesn't exist in IE9)

**Comment by kring** [comment]
Yeah as far as I know there's no way to get `loadArrayBuffer` like functionality in IE9.  So that leaves us a few options;
1. Add a service to terriajs-server that transforms the binary data into something IE9 can deal with, like JSON.
2. Fall back to the old WMS-based region mapping on IE9.
3. Drop support for region mapping in IE9 entirely.  The app should inform users that it is not supported in their browser when they try to use it.  For reference, 95% of users accessing NationalMap with Internet Explorer are using IE11.  About 2% of users overall will be unable to use region mapping.

**Comment by kring** [comment]
We've ended up doing option 3:
![image](https://user-images.githubusercontent.com/924374/36080674-78386f86-0fe7-11e8-952a-3e8a8c934246.png)
And IE9 is even more hopelessly outdated now than it was when we did it, so I'm closing this.
