### ISSUE TITLE
Move preview map credits to a separate window

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#1983]
Should we be showing the full map disclaimer in the preview window? When it's long, the results are sometimes comical:

![screen shot 2016-08-25 at 11 23 04 am](https://cloud.githubusercontent.com/assets/678344/17953401/69149d90-6ab6-11e6-9f02-a1b72c794f48.png)

**Comment by kring** [comment]
I think it would be totally legit to move it to a separate panel invoked from a button on the preview page somewhere.  Certainly that's ok by CCBY, and IMO (considering what it's worth given I'm not a lawyer) it's ok by the Bing Maps terms of use as well.

**Comment by stevage** [comment]
Maybe even just a piece of text with hover-over? I mean, you can barely even see the layer in question. Would you expect a thumbnail to have visible credits?

**Comment by RacingTadpole** [comment]
This is a general leaflet problem - see #1865.

**Comment by zoran995** [comment]
Attribution/credits are no longer visible on v8 preview map
