### ISSUE TITLE
CompositeCatalogItem doesn't show FeatureInfo

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1989]
This might be intentional, given that we use CompositeCatalogItem for the base maps.
However I have a situation where two FeatureServer layers really make sense as one item, and so I'm combining them using a composite catalog item.

Then you cannot get FeatureInfo for the features any more.

**Comment by RacingTadpole** [comment]
It would also be great to pass through the "about this dataset" info about the subitems.

**Comment by nf-s** [comment]
Not relevant to v8
