### ISSUE TITLE
Consider drag-and-droppable moving point csvs

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#1998]
When you drag a csv file with columns `date,lat,lon,id` onto the map, it doesn't actually make it a moving point csv file, because `idColumns` is not specified, which requires json. (I think.)

By defaulting `idColumns` to `['id']` if it exists, we can drag-and-drop moving point files.

**Comment by stevage** [comment]
Interesting question. Another alternative is to look for a column that functions like ID: unique values for every row with the same time.
