### ISSUE TITLE
Make it more obvious that the feature info panel can be collapsed by clicking its title bar

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#2000]
Following feedback from SA Govt and other users (ABBA - Australian Biomass for Bio energy Assessment - project team).

They would like to be able to drag/move the feature info and data description panels. Users would like to have the freedom to position their information panels, so they don't obstruct the view of the data, but be on the screen at the same time.

**Comment by philipgrimmett** [comment]
This might be ok, provided we fix the feature info panel width. Making the panel draggable while allowing it take up 80% of map would be counter productive. On my Macbook 13' Retina screen 500px*600px seems like a decent compromise between readability and space efficiency (might need different break points for larger displays, though)

Concept below: 

![10 copy 4](https://cloud.githubusercontent.com/assets/5292858/18739376/86459d4c-80e6-11e6-9101-aba18e9be3d0.jpg)

**Comment by RacingTadpole** [comment]
@kring do we want to consider this?

**Comment by kring** [comment]
I'd argue against making the feature info panel draggable.  We should just make the collapse capability we already have more obvious.  I'm also ok with making the maximum size smaller.

**Comment by kring** [comment]
We've now made the maximum size smaller. So I think the remaining action on this issue is to make the the collapse feature more obvious. Phil's design above with the new icon next to the X works for me.

**Comment by tkeuneman** [comment]
Two cents: Google Hangouts (or any video chat, Facebook messenger etc) does a really good job of making things movable on the screen. You can flick things around with your mouse/finger, while still allowing the space for things to expand.

**Comment by kring** [comment]
The feature info panel is now draggable, and the collapsability is more obvious because we've added a button:
![image](https://user-images.githubusercontent.com/924374/53611609-4e7f5380-3c23-11e9-8052-59ca0c488af3.png)
So I don't think there's any more to do for this issue and I'm closing it.
