### ISSUE TITLE
Make FeatureInfo title controllable

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#2008]
See https://github.com/TerriaJS/parlmap/issues/60

Basically we always look for any column on the region mapping boundary with the word "name" in it, and sometimes that isn't a unique name - it refers to a greater boundary which this one is inside. Problematic in some circumstances.

**Comment by axman6** [comment]
the feature info titles can already be templates, does that help?

**Comment by RacingTadpole** [comment]
Yeah - here's an example: https://github.com/TerriaJS/terriajs/blob/c59c573c662827ae04738765bf4cf9dfc537730c/wwwroot/test/init/czml-with-template.json#L13

**Comment by stevage** [comment]
Oh, perfect, thanks.
