### ISSUE TITLE
Streamline UI for adding data from the web

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#2012]
To add a layer from the web currently requires:
1. Add Data
2. My Data tab
3. Add Web Data (subtle link, ignoring the two HUGE BUTTONS just below)
4. Paste the URL
5. Click Add
6. Click the `(+)` icon (again, ignoring the HUGE BUTTON just below), and the also very prominent "Go to the map" button to the right

I suggest we at least remove step 6.

**Comment by RacingTadpole** [comment]
I agree, let's streamline. I think step 3 could be made more obvious too - I often forget it.
Allan Barger also requested fewer steps too.

**Comment by kring** [comment]
Not going to happen for today.

**Comment by chloeleichen** [comment]
@philipgrimmett

**Comment by chloeleichen** [comment]
An idea from @philipgrimmett 

<img width="360" alt="screenshot_2016-09-21_10 29 14_720" src="https://cloud.githubusercontent.com/assets/7508939/18699108/75f5560a-8012-11e6-9f45-11c5dbe58411.png">

When click on the upload button, brings up myData tab?

**Comment by chloeleichen** [comment]
V2 from @philipgrimmett 
<img width="360" alt="screenshot_2016-09-21_16 26 25_720" src="https://cloud.githubusercontent.com/assets/7508939/18700042/535fa004-8018-11e6-99e0-bc0c7cd0b51e.png">

**Comment by RacingTadpole** [comment]
I like v1

**Comment by stevage** [comment]
Me too. "Upload" is a word we have to be a bit careful with, because the user is not really "uploading" anything anywhere, although that's a technicality that won't mean much to them. The V1 looks like a little white lie, but V2 is too much of a lie, IMHO.

**Comment by RacingTadpole** [comment]
Also @philipgrimmett - do you have any thoughts on how to reduce the number of clicks if you have a URL - re point 3 above? Currently you have to click on the small grey "Add Web Data" text:

![image](https://cloud.githubusercontent.com/assets/1757858/18771965/8af43448-8186-11e6-9ff8-3ba355b5c4de.png)

**Comment by stevage** [comment]
I'm not Phil, but I think I'd reorganise it like:

![2016-09-23 15 23 41](https://cloud.githubusercontent.com/assets/678344/18775022/1fdecc9c-81a2-11e6-94e8-5465ca97d1e6.jpg)

**Comment by philipgrimmett** [comment]
I'll work on getting an invision up, but here's a more detailed version of @stevage's sketch:

![10 copy 16](https://cloud.githubusercontent.com/assets/5292858/18861046/9e4864d2-84c5-11e6-8a40-bfea1a902eed.jpg)

**Comment by stevage** [comment]
Just capturing what I said before. You could put that preamble text as "here are the consequences of this choice" text under the first option:

**Add local data file**
_This data will not be uploaded and cannot be shared_

**Add hosted file or web service (URL)**
[eg http://.... Add ]

**Comment by philipgrimmett** [comment]
Revised prototype:
https://invis.io/WENV0U1FN3C#/299007617_terria_-_Empty_Workbench

@chloeleichen let me know when you're ready to start on this, I'll walk you through the design

**Comment by chloeleichen** [comment]
I'm ready now! I'm halfway implementing an older version :(

**Comment by AnaBelgun** [comment]
@philipgrimmett please review and give feedback to @chloeleichen
