### ISSUE TITLE
Drag-and-drop init files don't support JSON5

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#2014]
Ran into this while demoing. Tried to drop an init file in JSON5 format onto nationalmap.

**Comment by RacingTadpole** [comment]
As a possible extension to this @stevage - there are still lots of json-only places in the code (where Cesium's `loadJson` is used). Are any of these worth considering allowing json5 for:?
- `Core/ServerConfig.js`
- `Map/ColorMap.js`
- `Map/RegionProvider.js`
- `Map/RegionProviderList.js`

The other uses of `loadJson` tend to be for json-related formats such as ArcGisCatalogItemGroup/Item, CzmlCatalogItem, CkanCatalogGroup etc.

**Comment by stevage** [comment]
> Core/ServerConfig.js

No, because that JSON is generated by TerriaJS-Server.

> Map/ColorMap.js

For the ColorBrewer styles? Probably no, because that code came from a third party and is unlikely to change or be modified by user.

> Map/RegionProvider.js
> Map/RegionProviderList.js

Yes, IMHO. That's a user-managed JSON file that would certainly be simpler to deal with if it was JSON5.
