### ISSUE TITLE
Add ability to not render missing points in CSV

### ISSUE THREAD

**Issue by rdengate** [TerriaJS/terriajs#2019]
A column in a CSV with missing values is rendered with a grey colour. It would be great to have the option to hide points which are null, because for some datasets there are a lot of points and they drown out the non-null values as well as slow down rendering. While we could set the opacity of the null colour to 0, it seems that the points would still be rendered.

**Comment by RacingTadpole** [comment]
@steve9164 - would you be interested in taking a look at this once you've finished the legendHelper refactor? Should be pretty quick, I hope...

**Comment by rdengate** [comment]
@artstr points out there's a better way to deal with the case giving me problems, which is that a column controls position variable and there are not huge numbers of null values. This is fine for my use case.
