### ISSUE TITLE
Add support for HERE base maps

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#2020]

**Comment by nahidakbar** [comment]
@kring are there any sample servers we could use?

**Comment by kring** [comment]
Yeah the official HERE ones.  You'll need an API key.  I'll find you a link in a minute if you don't find it first.

**Comment by kring** [comment]
https://developer.here.com/rest-apis/documentation/enterprise-map-tile/topics/request-constructing.html

**Comment by kring** [comment]
Closing in favor of #2807.
