### ISSUE TITLE
Add metadata to data.gov.au data

### ISSUE THREAD

**Issue by rdengate** [TerriaJS/terriajs#2036]
Use an API that given a 'dataset name' from data.gov.au will return a list of the columns in the CSV, and any associated metadata about it to give some more context when viewing data.

**Comment by stevage** [comment]
By "data.gov.au" you mean CKAN, right? So it could probably work for data.sa.gov.au, http://data.brisbane.qld.gov.au/ etc

**Comment by rdengate** [comment]
@stevage: Currently the API only returns data for data.gov.au. I believe it's part of MAGDA. I'm not sure if there are plans to extend it, but I imagine if this is useful it might be something that we do.

**Comment by kring** [comment]
@stevage this is a prototype integration with [Aristotle](http://www.aristotlemetadata.com/).

**Comment by rdengate** [comment]
This is complete.
