### ISSUE TITLE
Automatically zoom to newly selected layers

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#2038]
Previously when you added a layer, Terria would automatically zoom to its extent. That doesn't seem to be happening now (for WMS anyway). You can still manually click "Zoom to extent", but I don't know if that wording will speak to most users.

**Comment by kring** [comment]
We haven't automatically zoomed to enabled layers in at least 18 months and two UI redesigns.  Unless I don't know what you mean?

**Comment by stevage** [comment]
Really? (goes and looks at an old version) Ok, it turns out that I had a habit I wasn't even aware of, always enabling the layer, then immediately clicking on its name to zoom to it.

What was the reason for not automatically zooming? Isn't that what most people would want? In many cases, there's nothing to see at the national scale, and you may not know where to go.

**Comment by kring** [comment]
(18 months later) We removed the auto-zoom on Bill's request ages ago. I think there's a reasonable case to be made that it's rude to move the user's view just because they enabled a layer (maybe they were planning to look at how this new layer applies to the particular suburb they've zoomed in to). I don't feel strongly about it though.

**Comment by stevage** [comment]
Hehe thanks for getting back to me :) You're probably right. But for the hell of it, some options that might be better than the current behaviour:

- Auto-zoom if a layer is added to an empty view.
- If the layer is within the current viewport, flash its bounding box. If it's not, flash an arrow pointing to where it is, perhaps with some text.
- Temporarily highlight the "zoom to extent" button.

Very not important, so I'll close this.
