### ISSUE TITLE
Https issue with posting to iframe

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#2046]
On http://terria.io/embedded-natmap/ (which is the gh-pages version of https://github.com/TerriaJS/embedded-natmap), some users are not seeing the POSTed data, with the console message:

```
Failed to execute 'postMessage' on 'DOMWindow': 
The target origin provided ('http://nationalmap.gov.au') does not match the 
recipient window's origin ('https://nationalmap.gov.au').
```

(Although the code only refers to `http:` in both places, the iframe `src` and the `postMessage`.)

**Comment by kring** [comment]
Perhaps these people are using a browser extension that forces sites to HTTPS when available?  e.g.
https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp?hl=en
https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/

If so, options are:
1) Purposely use HTTPS for the iframe.
2) Detect whether we actually ended up visiting the HTTPS site and post to that instead.  I'm not sure if this is possible or not.

**Comment by kring** [comment]
Either way I don't think this is a TerriaJS issue, so if you can confirm that it's a browser extension, please close this issue.

**Comment by RacingTadpole** [comment]
Agreed.
