### ISSUE TITLE
Disclaimer "I agree" text is black, not white, and other css issues

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#2048]
With the current terriajs master, when used with the current AREMI master, we get:

![image](https://cloud.githubusercontent.com/assets/1757858/18462749/6e0ea2f2-79c8-11e6-8c19-b5a3d220679a.png)

Also if you choose Renewables -> Wave -> Energy Atlas and "select location", the font of the popup is wrong:

![image](https://cloud.githubusercontent.com/assets/1757858/18462786/b5819fb8-79c8-11e6-898a-96a30cb633dc.png)

And the font and sizing of the location is wrong:

![image](https://cloud.githubusercontent.com/assets/1757858/18462799/ce8b1aca-79c8-11e6-9160-40f6d479c488.png)

And the output dropdown bar is too narrow:

![image](https://cloud.githubusercontent.com/assets/1757858/18462831/0a9da398-79c9-11e6-8bff-49b7ea4685f6.png)

**Comment by RacingTadpole** [comment]
@chloeleichen do you mind if I assign this to you?

**Comment by chloeleichen** [comment]
sure!

**Comment by RacingTadpole** [comment]
Thanks! One more thing - in the error message, there's no space before the horizontal scroll bar, eg. 
![image](https://cloud.githubusercontent.com/assets/1757858/18464514/e0b950a2-79d4-11e6-8a59-195cda5067b9.png)

**Comment by chloeleichen** [comment]
so the problems are: 
1: we didn't add global styles in Aremi
2. some styles for the Analytics stuff are missing

Two PRs are needed for this one: 
https://github.com/TerriaJS/terriajs/pull/2065 and 
https://github.com/TerriaJS/aremi-natmap/pull/54

**Comment by RacingTadpole** [comment]
I've just found one more css thing with AREMI - the chart panel's "Loading" indicator is black instead of white...

**Comment by chloeleichen** [comment]
@RacingTadpole this PR fix the chart panel loading color: https://github.com/TerriaJS/terriajs/pull/2081
