### ISSUE TITLE
Close the preview window after dragging-and-dropping a file

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#2057]
When I drag a file onto the map, the preview appears and covers the data on the map.  Because the added data is not selected, there isn't even a preview map to look at, just this:

![image](https://cloud.githubusercontent.com/assets/1757858/18496550/1b369bbe-7a6a-11e6-8ba7-5df5b73a40a6.png)

I find it an annoying extra click to then have to close the preview.  Can we automatically close it once the data is added (or even while it's being added)? Alternatively, if you think the preview is still useful in this case, perhaps we could select the added dataset so it appears in the preview?

@philipgrimmett - what do you think?

**Comment by AlexGilleran** [comment]
Until phil weighs in maybe I'll just make it select the dragged dataset? I'm pretty sure that's what it's _supposed_ to be doing...

**Comment by RacingTadpole** [comment]
Thanks. My two cents worth - when we add a dataset from the catalog, the preview map closes automatically. So it would make sense to me that adding a dataset by dragging has the same behaviour.  We could set it up so that "shift" keeps the preview panel open, just like for adding data from the catalog.

**Comment by AlexGilleran** [comment]
Yeah I guess... I do like the feedback you get with seeing the preview as soon as you drop it though - if you drop it onto a map that already has a few datasets you might not realise that your data is now amongst them.

**Comment by RacingTadpole** [comment]
Yeah, that's true. OK, I'm happy to go with your plan.
