### ISSUE TITLE
Chart legend tooltip goes in front of feature info panel

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#2079]
When both the chart panel and the feature info panel are open, we agreed the feature info panel goes in front.  But at the moment, the chart legend tooltip goes in front of feature info panel.

This looks a bit odd, but not sure what the right behaviour should be - any thoughts @philipgrimmett, @chloeleichen  ?

![image](https://cloud.githubusercontent.com/assets/1757858/18537506/4b4b5562-7b49-11e6-9123-edfe91a889d0.png)

**Comment by philipgrimmett** [comment]
If tooltips are children of the charts panel, then they should be obscured by a more recently focused element i.e. feature info. Clicking back on charts should bring it into focus (meaning feature info falls behind?). Sound ok @RacingTadpole @chloeleichen ?

**Comment by kring** [comment]
We don't have any click-to-bring-to-front in TerriaJS anymore, and I suggest we not bring it back without a very good reason.  But yeah, the tooltip should be under the feature info if the chart is under the feature info.

**Comment by chloeleichen** [comment]
done in https://github.com/TerriaJS/terriajs/pull/2101
