### ISSUE TITLE
Add a "close" button for lat/lon/elev box, and give it a constant width

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#2086]
As suggested by user feedback

> I find the lat/lon/elev box quite distracting - the changing size, as well as the fast flickering numbers. Could it have a close button?

**Comment by chloeleichen** [comment]
yeah we can have a consistent width for the two boxes, Phil has come up with an updated design:
![10_copy_5](https://cloud.githubusercontent.com/assets/7508939/18701104/1feaaf92-801e-11e6-8997-514b435809c3.jpg)

**Comment by RacingTadpole** [comment]
I like it @philipgrimmett !

**Comment by kring** [comment]
I'm going to close this because:
* It's _much_ less distracting after Chloe's changes above.
* Working out a nice way to let the user bring it back after closing it is kind of a UX nightmare.
* This hasn't come up in awhile.
