### ISSUE TITLE
Some users do not realise you can click on features

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#2087]
@philipgrimmett do you have any suggestions for how to let users know to click on features for more info?
Eg. when you first add a data set with feature info, if you've never clicked on a feature before, show a message somewhere?

**Comment by AlexGilleran** [comment]
It's embarassing, but I didn't actually realise you could do this until I'd be working on the project for a week and a half :(

**Comment by stevage** [comment]
I had a similar experience actually. The only thing I can think of is to pop open the feature info window, with text like "Click somewhere to learn more about it", and maybe change the "No results" text to something friendlier.

**Comment by chloeleichen** [comment]
we need some specifications about the behaviour, i assume the  "Click somewhere to learn more about it" only shows up when you first load the app and add the first dataset?

**Comment by RacingTadpole** [comment]
Yes, I think a flag in `localStorage` could work.

**Comment by chloeleichen** [comment]
I think we have three messages to show here:
1. when you add a dataset, it should say something like: "Click somewhere to learn more about it"
2. when you click on a place that doesn't have data, it should say : ‘try click elsewhere?"
3. when you click on the map without a dataset enabled, it should say: “add a dataset!"

**Comment by RacingTadpole** [comment]
Sounds good to me! Although (2) is sort of done already - with slightly different behaviour for lat/lon vs region-mapped datasets.
One other thing - could you review and merge https://github.com/TerriaJS/terriajs/pull/2097 in that case? It makes a change to one of the region-mapped messages too.
