### ISSUE TITLE
Unintuitive workbench button captions (zoom, about, remove)

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#2089]
Maybe I'm still stuck on the old UI, but I find that these button captions don't really speak to me:

![screenshot 2016-09-16 11 03 32](https://cloud.githubusercontent.com/assets/678344/18572302/754b5aa6-7bfd-11e6-80b1-54775b17dc1d.png)

Each of those three buttons does something I want to do fairly often, but I find myself kind of slowly hunting for them.
### Zoom to Extent

IMHO, "extent" is really a GIS term that doesn't mean much to most people. Better options:
- Go to
- Pan to
- View
- An icon, maybe something like a small white rectangle inside a much bigger unfilled rectangle
### About this Data Set

I think the (i) ℹ symbol worked really well. These four words somehow seem too much. Perhaps just "About..."?

Its placement also doesn't seem to be quite where I'm expecting to look, either.
### Remove ⊖ (-)

I'm never really convinced by the use of the minus symbol for deleting or removal. I think a X would be more intuitive and more quickly catch the eye. I always seem to go looking for it next to the ▼ minimise button, then have to wander downwards.

You might argue that that's not the typical semantics of the X (ie, close this view, but don't change anything), but I've noticed this kind of use popping up. For instance, VideoStream uses the X to mean "stop playing this video" and it's very intuitive.

**Comment by chloeleichen** [comment]
@philipgrimmett

**Comment by zoran995** [comment]
No longer relevant for v8
