### ISSUE TITLE
Error alert doesn't leave enough space for the scroll bar

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#2092]
I suspect this one may have snuck in as part of the fix for adding some extra spacing to this alert.

![image](https://cloud.githubusercontent.com/assets/1757858/18606314/f31fd31a-7cef-11e6-88d8-e8b383c0305c.png)

**Comment by chloeleichen** [comment]
I'm having trouble replicating this, which browser are you using ? @RacingTadpole

**Comment by chloeleichen** [comment]
<img width="506" alt="screen shot 2016-09-21 at 4 07 54 pm" src="https://cloud.githubusercontent.com/assets/7508939/18699584/9dfcd198-8015-11e6-9648-002c29317722.png">

**Comment by RacingTadpole** [comment]
Hi @chloeleichen - I get it on the current nationalmap website, eg. by turning off internet once it's loaded and then zooming in. I'm using Chrome 52.0.2743.82 on Mac OS.

**Comment by chloeleichen** [comment]
I think this is fixed? https://github.com/TerriaJS/terriajs/pull/2114

**Comment by RacingTadpole** [comment]
Yep. I guess github doesn't recognise "fixing #2092"...
