### ISSUE TITLE
Improve implicit end date calculation in csvs

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#2110]
If the date column is specified as just a year (eg. 2014), but only 2012, 2014 and 2016 are present in the file, should the 2014 data be displayed in 2015 too, or just for one year?

(And similarly for months - and maybe days too.)

See also #2109 and #2018.

**Comment by kring** [comment]
The current behavior is that we show the first row (2014) until the next row takes effect (2016). That makes sense to me. I don't think we should infer that the value only applies for one year just because there's a year in the date column. I'm going to close this, but re-open if you disagree.
