### ISSUE TITLE
CSS class missing in RegionMapping warning (super minor)

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#2121]
This alert uses html generated in the `RegionMapping.js` file, via:

`msg += 'These region names were <span class="warning-text">not recognised</span>: <br><br/>'`

![image](https://cloud.githubusercontent.com/assets/1757858/18772146/dd042a1c-8187-11e6-9de4-c9d0bf3c434d.png)

We used to have some css on the `warning-text` class.  What's the right way to do this with css modules?

**Comment by chloeleichen** [comment]
it probably has to go into global.scss: something like: 

```
.terria .warning-text{
   ...
}
```

What do you think @AlexGilleran ?

**Comment by kring** [comment]
I'm closing this because I doubt anyone even remembers how that warning text is supposed to be styled. But if we ever need it, the solution above is ok. We could also use semantic tags like `<em>` if appropriate rather than explicit class.
