### ISSUE TITLE
Fewer attributes from WMS layers shown in new UI

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#2132]
Since upgrading to the new UI, there is much less information shown for some Water Observations from Space layers, despite exactly the same catalog definition:

```
                            {
                              "layers": "WaterObservations",
                              "url": "http://geoserver.nci.org.au/geoserver/NFRIP-WOfS/wms",
                              "type": "wms",
                              "rectangle": [
                                111,
                                -45,
                                155,
                                -10
                              ],
                              "dataCustodian": "[Geoscience Australia](http://www.ga.gov.au/)\n\n[nfrip@ga.gov.au](mailto:nfrip@ga.gov.au)",
                              "name": "1 - Detections",
                              "dataUrlType": "direct",
                              "dataUrl": "http://www.ga.gov.au/scientific-topics/hazards/flood/wofs",
                              "info": [
                                {
                                  "name": "Licence",
                                  "content": "[Creative Commons Attribution 4.0 International (CC BY 4.0)](http://creativecommons.org/licenses/by/4.0/)"
                                }
                              ]
                            },
```

Previously "Data Description" and "Service Contact" sections were shown:

Before:

![screenshot 2016-09-28 16 00 56](https://cloud.githubusercontent.com/assets/678344/18902205/c4c2088c-8594-11e6-86e9-c910910cbc58.png)

![screenshot 2016-09-28 16 01 17](https://cloud.githubusercontent.com/assets/678344/18902223/de0f3788-8594-11e6-8a22-7304a6000e2a.png)

These are absent in the new UI:

![screenshot 2016-09-28 16 02 04](https://cloud.githubusercontent.com/assets/678344/18902226/eaefe43e-8594-11e6-97ae-b8f98c24436e.png)

**Comment by kring** [comment]
The catalog item will need to finish loading before those details are displayed.  Are you sure it had finished in that screenshot?

**Comment by stevage** [comment]
Yes, I see that in NationalMap, the attributes do display. 

Looks like something wrong with a network request, will investigate.

**Comment by stevage** [comment]
Ok, looks like it's a CORS problem. Nothing to see here.
