### ISSUE TITLE
Change default autoPlay to False?

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#2135]
Currently the default is `autoPlay: True`
https://github.com/TerriaJS/terriajs/blob/master/lib/ReactViews/BottomDock/Timeline/Timeline.jsx#L23
but in every instance of TerriaJS we have deployed, we always set `autoPlay: False`. 

In my experience, other GUIs that deal with geospatial information (e.g. Godiva2, Godiva3, IDV, Google Earth) require you to click the play button to animate.   I think this works well because most folks are interested in looking at information at specific time steps rather than watching an animation, and for many dynamic WMS source with time dependence, the loading is slow enough that animation is not very satisfying. 

What do other folks think?

**Comment by kring** [comment]
I've marked this "Next Major Version" because, while it's simple and almost certainly a good idea, it's also a breaking change.

**Comment by rsignell-usgs** [comment]
Okay!

**Comment by RacingTadpole** [comment]
Yes, this was also requested (and set to off) for the NEII viewer.

**Comment by kring** [comment]
At this point we've made this change in NationalMap, too. We should just go ahead and change the default in TerriaMap, no need to wait for the next major version.

**Comment by rsignell-usgs** [comment]
Nice!

**Comment by kring** [comment]
Fixed by #2886.
