### ISSUE TITLE
Lat/lon/elev box obscures disclaimer, text still jumps around

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#2143]
The lat/lon/elev box is now sitting on top of the disclaimer, eg.:
![image](https://cloud.githubusercontent.com/assets/1757858/19009631/373d2704-87b9-11e6-8fda-aa6064d448c1.png)

It can also spill over onto two lines sometimes (I'm having trouble catching this to screenshot it).

Also, while the box is no longer changing size, the words (Lat, Lon, Elev) still move around inside it. Can they be made fixed?

**Comment by chloeleichen** [comment]
@philipgrimmett says:

> re. covering the disclaimer: would could decide as a team to look past it, change if it ever gets questioned...

**Comment by kring** [comment]
Don't think that'll fly.  From the Bing Maps terms of use (https://www.microsoft.com/maps/product/terms.html):

> Change, obscure, or minimize any logo, trademark, copyright or other notice of Microsoft or its suppliers, or digital watermarks in the Content; except that we may make alternative logo, trademark and copyright attribution requirements available for use with small maps or on small devices; if available you will find them here.

We can possibly move the credits somewhere else, but leaving them there and obscuring them is bad news.
