### ISSUE TITLE
Legend width isn't capped to workbench width

### ISSUE THREAD

**Issue by axman6** [TerriaJS/terriajs#2150]
Seems this might have disappeared in the CSS refactor, there used to be something which (I assume) set the `max-width` of any legend to be just smaller than the workbench width. It'd be great to get this back.

**Comment by geoffrowland** [comment]
My workaround for this issue was to add an auto horizontal scroll bar to the workbench CSS, to give:

.tjs-workbench-list__workbench-content {
  position: relative;
  height: calc(100vh - 201px);
  overflow-x: auto;
  overflow-y: auto;
  padding: 0 5px;
}

**Comment by kring** [comment]
Fixed by #2178.
