### ISSUE TITLE
Move credits off the 2D map, make them look pretty

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#2161]
Sorry... I know we're all sick of this one ( #2143 )... but in 2D mode, the disclaimer is still obscured by the lat/lon box...

![image](https://cloud.githubusercontent.com/assets/1757858/19257669/37ce5e66-8fbd-11e6-8728-7d875be3f4be.png)

**Comment by kring** [comment]
As of our upgrade to Cesium 1.41, the credits have been moved off the 3D map and onto a popup. We should do the same for the 2D map.  And also style the credits popup better (it's currently created by Cesium itself).

**Comment by zoran995** [comment]
Done in #6340, @nf-s can you close this?
