### ISSUE TITLE
Use vector tiles for Terria Analytics

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#2171]
Update analytics to use vector tiles for displaying and selecting regions.

**Comment by tephenavies** [comment]
@kring Do I need to ensure compatibility with WMS regions? If not it will probably be easier to rewrite RegionParameterEditor.jsx in a way that makes more sense for vector tiles.

**Comment by kring** [comment]
No, that's fine by me.

**Comment by tephenavies** [comment]
Fixed in #2607. Replacing WMS completely was not an option as analytics requires geojson of a whole region for region based processing.
