### ISSUE TITLE
No labels on legend for ncWMS2 data layers

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#2172]
I think this issue is fixed: https://github.com/TerriaJS/terriajs/issues/1513 but there is still a legend issue with ncWMS2 services.    When I access data from a ncWMS2 endpoint, I get a colorlegend, but with no labels: 
![2016-10-13_9-54-37](https://cloud.githubusercontent.com/assets/1872600/19352066/720b613a-912c-11e6-94a8-b9c32e40606d.jpg)

This is because the legend is being requested as:
http://www.smast.umassd.edu:8080/ncWMS2/wms?REQUEST=GetLegendGraphic&PALETTE=default&COLORBARONLY=true&WIDTH=110&HEIGHT=264&colorscalerange=3%2C27

which is specifying `COLORBARONLY=true`.

Instead we need to drop the `COLORBARONLY=true` and request the style and layer in the legend like this:
http://www.smast.umassd.edu:8080/ncWMS2/wms?REQUEST=GetLegendGraphic&COLORBARONLY=false&WIDTH=30&HEIGHT=264&colorscalerange=3%2C27&styles=default-scalar%2Fseq-cubeYF&layers=FVCOM-NECOFS-GOM3%2Ftemp

which produces this:
![wms](https://cloud.githubusercontent.com/assets/1872600/19353031/190e9f44-9130-11e6-8783-9927f3d28741.png)

**Comment by kring** [comment]
TerriaJS is including `COLORBARONLY=true` because the GetCapabilities includes it in the LegendURL for the styles:
http://www.smast.umassd.edu:8080/ncWMS2/wms?REQUEST=GetCapabilities&service=WMS

 So, there are a few options, in order of my preference:
1. Change the server to advertise a LegendURL without that parameter.
2. Specify `"COLORBARONLY": "false"` in the `parameters` section of the TerriaJS init file, in order to override the server-provided value.
3. Teach TerriaJS about `COLORBARONLY` so that it can remove that parameter from the server-provided LegendURL when it sees it.

**Comment by rsignell-usgs** [comment]
It doesn't work to set `COLORBARONLY=false` (or to not set `COLORBARONLY`) with ncWMS2.

If you do that, for example:
http://www.smast.umassd.edu:8080/ncWMS2/wms?REQUEST=GetLegendGraphic&PALETTE=default&COLORBARONLY=false&WIDTH=110&HEIGHT=264
you get back a message that says:

```
<ServiceExceptionReport version="1.3.0" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wms/1.3.0/exceptions_1_3_0.xsd"><ServiceException>
        You must specify either SLD, SLD_BODY or LAYERS and STYLES for a full legend.  You may set COLORBARONLY=true to just generate a colour bar
    </ServiceException></ServiceExceptionReport>
```

so I think we need to provide the layer and style, as in: 
http://www.smast.umassd.edu:8080/ncWMS2/wms?REQUEST=GetLegendGraphic&COLORBARONLY=false&WIDTH=30&HEIGHT=264&colorscalerange=3%2C27&styles=default-scalar%2Fseq-cubeYF&layers=FVCOM-NECOFS-GOM3%2Ftemp

It's interesting that LAYER was specified in the [ncWMS GetCapabilities](http://geoport.whoi.edu/thredds/wms/coawst_4/use/fmrc/coawst_4_use_best.ncd?service=WMS&version=1.3.0&request=GetCapabilities) LegendURL

```
<LegendURL width="110" height="264">
<Format>image/png</Format>
<OnlineResource xlink:type="simple" 
xlink:href="http://geoport.whoi.edu/thredds/wms/coawst_4/use/fmrc/coawst_4_use_best.ncd?REQUEST=GetLegendGraphic&
LAYER=sandfrac_01&PALETTE=redblue"/>
</LegendURL>
```

but now the LAYER is _not_ specified in the [ncWMS2 GetCapabilities](http://www.smast.umassd.edu:8080/ncWMS2/wms?REQUEST=GetCapabilities&service=WMS) LegendURL

```
<LegendURL width="110" height="264">
<Format>image/png</Format>
<OnlineResource xlink:type="simple" 
xlink:href="http://www.smast.umassd.edu:8080/ncWMS2/wms?REQUEST=GetLegendGraphic&
PALETTE=default&COLORBARONLY=true&WIDTH=110&HEIGHT=264"/>
</LegendURL>
```

Do you see this as a bug in EDAL-Java LegendURL, that it should provide the layer as well?
https://github.com/Reading-eScience-Centre/edal-java/blob/master/wms/src/main/resources/templates/capabilities-1.3.0.vm#L274

**Comment by rsignell-usgs** [comment]
@guygriffiths, what was the rationale for removing the specification of `LAYER` from the `LegendURL` in the ncWMS2 getCaps?

**Comment by guygriffiths** [comment]
@rsignell-usgs I can't recall.  I'll put it back

**Comment by rsignell-usgs** [comment]
Sweet!   Can you also set COLORBARONLY to false?  
If you do that, we don't have to do anything then and this problem will fix itself (once we upgrade ncWMS2...)

**Comment by guygriffiths** [comment]
Yep, I've done that (actually I've just removed COLORBARONLY, since it defaults to false).  It's in the develop branch so it'll make it to the next release

**Comment by rsignell-usgs** [comment]
Okay, I think I've updated my ncWMS2 service to include these latest changes, but for some reason terriajs does not seem to like the getCaps.   This just kind of hangs TerriaMap:
http://geoport.whoi.edu/ncWMS2/wms?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0

@kring, can you try?

**Comment by kring** [comment]
It doesn't work for me either.  That `GetCapabilities` has 769 layers and 9458 styles.  It takes a very long time to parse, and eventually crashes the browser. I'll have to see what we can do to optimize it.

**Comment by rsignell-usgs** [comment]
Interesting.   The Godiva3 client reading that `GetCapabilities` 
http://geoport.whoi.edu/ncWMS2/Godiva3.html
comes up in just a few seconds, so I guess it's only parsing just the layer names initially, while TerriaJS is parsing all the info?

**Comment by guygriffiths** [comment]
Godiva3 doesn't use GetCapabilities at all.  It uses GetMetadata, which is an ncWMS-specific extension which returns snippets of metadata in JSON format, designed to get around the hassle of parsing a large capabilities document.

**Comment by rsignell-usgs** [comment]
@guygriffiths , is `GetMetadata` implemented the same in ncWMS and ncWMS2?
Is this reference here:
http://www.resc.rdg.ac.uk/trac/ncWMS/wiki/WmsExtensions#Metadataaccess
up to date?

**Comment by guygriffiths** [comment]
If there have been any changes, they are only very minor.  But that reference is outdated, the new ncWMS user guide is here:
https://reading-escience-centre.gitbooks.io/ncwms-user-guide/content/04-usage.html#extensions

**Comment by rsignell-usgs** [comment]
@kring, well, if we find a way to get some more developer cycles for TerriaJS development, we will want to implement some calls to `GetMetadata`.  In addition to more efficient management of the layer metadata, the `minmax` function really helps the user experience, allowing them to auto adjust the color range to the current window by clicking a button, which is super handy.   As we have it now in TerriaJS, we can change the `COLORSCALERANGE`, which is awesome, but to accomplish the same thing as auto adjust,  we have to try to determine the range by clicking on the map on a few points, and then typing those values into the controls and hit update.     

@guygriffiths , is anyone on your team working with the OGC to see if these enhancements could become part of a future version of WMS?

**Comment by guygriffiths** [comment]
@rsignell-usgs Not that I'm aware of.  I'm pretty much the only person actively working on ncWMS at the moment, so I'd be surprised if anyone else was...

**Comment by rsignell-usgs** [comment]
Okay, I paired down the number of datasets exposed in my updated ncWMS2 endpoint here
http://geoport.whoi.edu/ncWMS2/
to just one dataset so that TerriaJS doesn't choke,  and sure enough, the legend labels are now there!   Hurrah!  
![2016-10-27_7-27-08](https://cloud.githubusercontent.com/assets/1872600/19765522/db8a7ffc-9c16-11e6-98e0-c7051ad73b0c.png)
