### ISSUE TITLE
Document `viewerMode` init file option

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#2181]
I tried to set `"initialViewerMode":"2D"` in one of my configuration files, but it didn't seem to have any effect.   I might have made some mistake, but I'm wondering if this property perhaps has a different value in the new UI?

The reason I ask this is that I looked for `initialViewerMode` and I didn't find any occurrences in the current master Terriajs code:
https://github.com/TerriaJS/terriajs/search?utf8=%E2%9C%93&q=initialViewerMode

And I found only one reference in the latest master for TerriaMap, in a quite old configuration:
https://github.com/TerriaJS/TerriaMap/search?utf8=%E2%9C%93&q=initialViewerMode

**Comment by rdengate** [comment]
I believe it's now 'defaultTo2D', a Terria option, although that's not documented anywhere. For the GEOGLAM RAPP project, we're setting that in index.js like so:

`terria.start({
    applicationUrl: window.location,
    configUrl: 'config.json',
    defaultTo2D: true,
    shareDataService: new ShareDataService({
        terria: terria
    })
`

I will make sure that's documented somewhere.

**Comment by rsignell-usgs** [comment]
I would like to set this only on specific config files, so I tried just adding `"defaultTo2D": "true"` to the wms.json config:
https://github.com/USGS-CMG/terriajs-dive/blob/master/testing/wms.json#L2
and then tried loading it:

http://gamone.whoi.edu/terriajs/#https://raw.githubusercontent.com/USGS-CMG/terriajs-dive/master/testing/wms.json

But unfortunately it not seem to have any effect -- initial view is still 3D.

Is there a way to enable this in specific config files?

**Comment by rdengate** [comment]
Yeah, defaultTo2D would only work as a Terria option. I didn't realise we previously supported specifying viewer mode on a per config file basis. As far as I know that isn't supported currently.

**Comment by RacingTadpole** [comment]
In a similar vein, [the docs](https://github.com/TerriaJS/terriajs/blob/master/lib/Models/Terria.js#L233-L238) say http://nationalmap.gov.au/?map=2D should start the map in 2D mode, but it doesn't.

**Comment by kring** [comment]
The correct URL is: http://nationalmap.gov.au/#map=2d

**Comment by RacingTadpole** [comment]
Ah, of course - sorry! But let's improve those docs, as they refer to "URL parameters", and `?` is the way to pass parameters, not `#`.

**Comment by kring** [comment]
`map=2d` is documented here: http://terria.io/Documentation/guide/deploying/controlling-with-url-parameters/

It looks like you can set the viewer mode in a config file with `"viewerMode": "2d"`, but this is not documented.  It should be documented here: http://terria.io/Documentation/guide/customizing/client-side-config/

This is the only outstanding action for this issue.

**Comment by zdefne-usgs** [comment]
@kring Here is what I experience when I test this:  "viewerMode": "2d" does not work if only written in the config.json, TerriaMap does not respect it. It works if you send the entire file content in the url as in the ''Start Data'' example on that documentation webpage.
http://terria.io/Documentation/guide/deploying/controlling-with-url-parameters/

**Comment by kring** [comment]
@zdefne-usgs the `viewerMode` property should go in a catalog/init file, not in config.json.  For example, name this file `viewerMode-2d.json` and drag it onto TerriaMap:

```
{
    "catalog": [],
    "viewerMode": "2d"
}
```

And the application will switch to 2D.

The `catalog` property is necessary only so that TerriaJS knows this is an init file instead of (for example) a GeoJSON file.

**Comment by zdefne-usgs** [comment]
Ah! Thanks for clarifying it. Yes it works when using with an init (catalog) file.

**Comment by PeterTonoli** [comment]
Any chance this could be added as an option to config.json, rather than the documentation changed?
It's a little confusing, and inconsistent since "mobileDefaultViewerMode" is in config.json, but this isn't..

**Comment by yohannist** [comment]
Additional bit of information that may be useful, If at anytime a user chooses 2d or 3d using the user interface (via the map button), then that choice is saved in browser local storage. That choice overrides the url parameter(`map=2d`) so it might appear as if the feature is broken even though everything is working as expected. A quick way to check is to delete `<App Name>.viewermode` key/value from the browser local storage and refreshing. Upon refresh, the mode specified in the url parameter should be rendered.

**Comment by zoran995** [comment]
issue clean up; please open up a new issue if still relevant in the latest documentation
