### ISSUE TITLE
Add ESA boundaries for region mapping

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#2191]
These were just added to data.gov.au, and @ajbar7 has requested we add them to csv-geo-au and to our region mapping system.
http://data.gov.au/dataset/employment-regions

**Comment by tephenavies** [comment]
@kring The ESA boundaries seem to be a little broken. The shapefile I got had 4 self intersecting polygons (according to `ogr2ogr`). ~~There's a new vector tile server with the regions on it, and the branch `esa_regions` will allow you to preview it. Here are some test CSVs:
[test_csvs.zip](https://github.com/TerriaJS/terriajs/files/563881/test_csvs.zip)~~

~~You can see that some regions aren't working.~~
