### ISSUE TITLE
Bad GetLegendGraphic request on ncWMS2 endpoints 

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#2201]
There is a problem with the legend on ncWMS2 endpoints when the style is specified including the palette, like `"styles": "default-scalar/x-Sst",`:
https://github.com/USGS-CMG/terriajs-dive/blob/master/examples/forecast_models.json#L15

For this configuration:
http://gamone.whoi.edu/terriajs/#http://rawgit.com/USGS-CMG/terriajs-dive/master/examples/forecast_models.json

The GetMap image tiles are correct, but the legend is not:
![2016-11-04_18-19-46](https://cloud.githubusercontent.com/assets/1872600/20024453/2071684a-a2bd-11e6-9fad-74fbd60ab9ac.png)

The `GetLegendGraphic` request is:

http://geoport.whoi.edu/ncWMS2/wms?REQUEST=GetLegendGraphic&PALETTE=default&LAYERS=FVCOM-NECOFS-MassBay%2Ftemp&STYLES=default-scalar%2Fdefault&VERSION=1.1.1&colorscalerange=11%2C17

which has `STYLES=default-scalar/default` instead of `STYLES=default-scalar/x-Sst`.  

This legend request produces the correct legend:
http://geoport.whoi.edu/ncWMS2/wms?REQUEST=GetLegendGraphic&PALETTE=default&LAYERS=FVCOM-NECOFS-MassBay%2Ftemp&STYLES=default-scalar%2Fx-Sst&VERSION=1.1.1&colorscalerange=11%2C17

(ps. can this issue please be added to: https://github.com/TerriaJS/terriajs/milestone/22)

**Comment by kring** [comment]
I don't think this is a problem anymore.  The links above don't work for me anymore (geoport.whoi.edu has two CORS headers, which Chrome objects to).  But I modified the Chlorophyll layer in `#test` to remove `STYLES` and `PALETTE`. I can then change the style in the UI and the legend updates.  I can also set the `styles` property in the JSON and the legend both honors it initially and updates when I change the selected style in the UI. Please re-open if you still see a problem.
