### ISSUE TITLE
Oversized graphic returned from WPS call

### ISSUE THREAD

**Issue by rdengate** [TerriaJS/terriajs#2203]
To reproduce:
1. Go to http://nationalmap.gov.au/renewables/
2. Add Data > Renewable Energy > Wave > Australian Wave Energy Atlas > Analysis Tools > Annual Waverose
3. Select a location, and click run analysis
4. Note that the graphic returned is not scaled to the workbench, so it is clipped. See image below.

![oversized](https://cloud.githubusercontent.com/assets/3466267/20164070/bdfa85c8-a755-11e6-930d-c1edbff34a01.jpg)

This appears similar to the oversized legend issue that was fixed recently.

**Comment by chloeleichen** [comment]
@rdengate still can't seem to find a spot that successfully run the analysis for me. I picked somewhere near perth and selected between 2016-11-10 12:00 to 2016-11-11 12:00
