### ISSUE TITLE
Search doesn't return all matching results

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#2204]
Eg. A search on "water" returns the following 10 items.
![image](https://cloud.githubusercontent.com/assets/1757858/20199052/30c06342-a7fc-11e6-8916-c8fa13b203cf.png)
Under the "Available Water Capacity" item there are lots of other depths available too. Why are only some of them appearing in the search?

(Also it seems a bit strange to have results appear twice, in both the "Available Water Capacity" section and below it... assuming that's what's happening, but it's hard to tell, because of #2136... perhaps a "filter"-style result would be clearer.)

**Comment by kring** [comment]
Well the results show up twice because both the group title and the individual item titles contain the word "water".  I think that's reasonable.  I'm not sure why other depths wouldn't show up though, assuming they also contain the word "water".

**Comment by RacingTadpole** [comment]
Here's the reason for that:
`this.maxResults = defaultValue(options.maxResults, 10);`
in `CatalogItemNameSearchProviderViewModel`

**Comment by RacingTadpole** [comment]
Wow! You can override that when using it by typing `water show:20` or `water show:all`... Cool - but not very discoverable...
I think it's misleading to only show the first 10 results and not state that's what we're doing.  @philipgrimmett any thoughts?

**Comment by kring** [comment]
Ah hah!  yeah limiting to 10 sorta maybe almost made sense when we have one panel with 3 different sets of search results.  But now that the catalog search is separate we should either have no limit, or a much larger one.

**Comment by RacingTadpole** [comment]
well... my "water show:all" search is still "Loading", but it's found heaps of results I never suspected were there. And you can always cancel while it's still going.  So I'd suggest no limit makes sense. (Overrideable in config of course.)

**Comment by RacingTadpole** [comment]
As an aside... there remain some Aussie/American spelling inconsistencies (catalog vs. catalogue)...
![image](https://cloud.githubusercontent.com/assets/1757858/20199571/8086e0a6-a7ff-11e6-991a-245655312fbe.png)
