### ISSUE TITLE
Different behaviour for JSON catalog: URL vs "Add Data"

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#2222]
I have a wetlands_synthesis.json catalog that describes 3 items in a group: 
http://gamone.whoi.edu/terriajs/#https://raw.githubusercontent.com/USGS-CMG/terriajs-dive/master/examples/wetlands_synthesis.json  

When I use this via the URL syntax
http://gamone.whoi.edu/terriajs/#https://raw.githubusercontent.com/USGS-CMG/terriajs-dive/master/examples/wetlands_synthesis.json
I get just the 3 layers:
![2016-11-15_0738](https://cloud.githubusercontent.com/assets/1872600/20306252/531b7cfc-ab07-11e6-8cde-666e109f80c4.png)

When I drag-and-drop this catalog or browse to it using "Add Data", I get 4 items instead of 3, where the top item is a rather useless non-displayable item called "wetland_synthesis.json":
![2016-11-15_0733](https://cloud.githubusercontent.com/assets/1872600/20306261/5d4c4602-ab07-11e6-88a4-1508c18538d9.png)

Is this expected behaviour?

**Comment by tephenavies** [comment]
@kring The catalog item added seems to be a `ResultPendingCatalogItem`.

All drag and drop items start as a `ResultPendingCatalogItem` and then get replaced by the correct catalog item, but json catalogs are not catalog items, so the temporary catalog item isn't replaced or deleted.

What should happen to this temporary catalog item?

**Comment by kring** [comment]
> What should happen to this temporary catalog item?

It should just be removed after the load finishes, whether it gets replaced by a real catalog item or not.
