### ISSUE TITLE
Null data in charts

### ISSUE THREAD

**Issue by rdengate** [TerriaJS/terriajs#2230]
When a chart that has null values is displayed, the line is continuous, giving the impression that there is data where none exists.

To reproduce:
* Run National Map (after https://github.com/TerriaJS/nationalmap/pull/373 merged, or with branch rd_wps_test_update) with #test
* Go to Test Data > WPS > Point Input
* Select a point on the map (anywhere)
* Click "Run Analysis"
* If you look at what is returned, the csv data has gaps in it, e.g.:
...
2013-12-31,36.303381
2014-01-31,22.644827
2014-02-28,
2014-03-31,
2014-04-30,
2014-05-31,
2014-06-30,
2014-07-31,
2014-08-31,
2014-09-30,7.515737
2014-10-31,80.278065
...
* Click on the point on the map, then expand to see chart
* Mouse over the chart, especially around 2014, to see that there's a bunch of null data that's reported as null but looks like it's present. 

This is a problem as it's misleading.

**Comment by RacingTadpole** [comment]
Agreed - but same as https://github.com/TerriaJS/terriajs/issues/2113
