### ISSUE TITLE
Time-varying csvs in 2D mode can leave a trail behind

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#2299]
Eg. Save this and drag it onto the map in 2D mode.
```
date	lat	lon	value
1995	-35	140	22
1996	-36	140	20
1997	-37	140	19
1998	-38	140	18
1999	-39	140	17
1995	-35	145	20
1996	-36	145	19
1997	-37	145	18
1998	-38	145	17
1999	-39	145	15
```
Once the time slider has moved along enough you'll see all the points at once:
![image](https://cloud.githubusercontent.com/assets/1757858/21663752/3d6eb674-d336-11e6-9ca5-54139d4865a4.png)
This doesn't happen in 3D mode.
I checked this in 2D with the old UI, and it didn't happen then either.

**Comment by rsignell-usgs** [comment]
I tried saving this as `csv_demo.txt` and `csv_demo.csv` and neither one showed up when dragged onto 
http://nationalmap.gov.au.    Am I doing something wrong, or is the deployed version an older version, or some other problem?

I also found it interesting that the file extension apparently made a difference in the way the data is represented -- see screen grab below.   As a user I found that confusing. 
![2017-01-05_7-00-25](https://cloud.githubusercontent.com/assets/1872600/21680033/1ebcc3ea-d315-11e6-9559-b4dbaae3bb7f.jpg)

**Comment by RacingTadpole** [comment]
Ah, my bad. I pasted that out of Excel in tab-separated format, not comma-separated format. Here's the csv file:
```
date,lat,lon,value
1995,-35,140,22
1996,-36,140,20
1997,-37,140,19
1998,-38,140,18
1999,-39,140,17
1995,-35,145,20
1996,-36,145,19
1997,-37,145,18
1998,-38,145,17
1999,-39,145,15
```
Yes, TerriaJS does use the file extension to work out the file's type. We'd like to change this, but it's non-trivial: currently the catalog item is created _before_ the data is loaded, ie. Terria has to know its type before it looking at the contents of the file.

**Comment by rsignell-usgs** [comment]
Ah, okay.  I was wondering why the CSV file had no "C". 
I should have figured that out.  :grimacing:
