### ISSUE TITLE
Feedback window pops up behind other panels

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#2331]
Eg. The chart panel and the feature info panel:

![image](https://cloud.githubusercontent.com/assets/1757858/22004593/0e54c6ba-dcb1-11e6-8803-b5f7f483da9a.png)

**Comment by chloeleichen** [comment]
hmm we need a reorganising of what should be on top of what, things to consider are:

1. explorer window
2. feature info panel
3. chart panel and timeline panel
4. feedback form
5. map navigation (the zoom in zoom out buttons etc)

@philipgrimmett  can you give me a run down of the order of things?

**Comment by kring** [comment]
I think the order, from top to bottom, should be:
1. Explorer window
2. Feedback form
3. Feature info
4. Charts and timeline
5. Map (and map navigation)

1 is modal, so it goes above everything else, and clicking outside it closes it.  It might be sensible to make the feedback form behave the same way, but it's fine as-is too.

**Comment by zdefne-usgs** [comment]
Sorry to bump a closed post, but it seems like the feedback tool is functional for some people. Is there an example on how to use it? See https://github.com/TerriaJS/terriajs/issues/2911
