### ISSUE TITLE
Load init files into a group

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#2336]
Eg. the NEII viewer loads the NEMSR data from the init file [here](http://neii.bom.gov.au/cgi-bin/nemsr/get_viewer_config.json), which creates a group called "Environmental Monitoring Sites Register" at the root level.
It would be nice to be able to load that into other Terria-based maps in different parts of the catalog, eg. in this file https://github.com/TerriaJS/NationalMap-Catalog/blob/master/datasources/National_Datasets/Environment.ejs.

**Comment by RacingTadpole** [comment]
One way to do it might be to add it in to that file as another item, with a new `type`, eg. `init` or `json`. That's a pretty big change to our concept of types though. @kring - any thoughts? Would this be madness?

**Comment by meh9** [comment]
That doesn't sound crazy to me from a non-technical viewpoint - we already have other group types that load complete subtrees.

**Comment by kring** [comment]
Yeah a group that loads from an external init file would be quite easy and very compatible with our current paradigms.  If we instead want a group that is a combination of items specified inline _and_ items from an external catalog file, that'll take a bit more work.  It might be better to create a `CompositeCatalogGroup` or something like that, which has a list of sub-catalog-groups and its items are just the union of the set of items in each sub group.

When loading external catalogs from other maps, though, we need to be extra careful about compatibility.  New features of TerriaJS and new versions of a catalog that take advantage of those features might break when loaded in maps using an old version of TerriaJS.

**Comment by tobybellwood** [comment]
Would we need to add logic to only collect the catalog (and not the camera, proxies etc) from the JSON (should they be present)?

**Comment by kring** [comment]
Yep.  Some might be applicable, like the list of CORS hosts.  But it'll be difficult to make something like that applicable only within the group.  Not a huge problem I think.

**Comment by RacingTadpole** [comment]
This would also be handy for my new ABS catalog from the SDMX-JSON API. NationalMap-Catalog will produce a standalone ABS json file, and it would be nice to be able to read that in directly into the main NM catalog (although I realise you could do this with an ejs include) but also other maps, directly from `nationalmap.gov.au/init/abs.json` or equivalent.

**Comment by tobybellwood** [comment]
Similar to this - being able to do it directly in JSON would be advantageous for uptake?
```
"catalog":[  
   {  
      "name":"Remote Catalog Group",
      "type":"remote-catalog",
      "url":"http://www,somedomain.com/catalog.json"
   },
   {  
      "name":"Taxation Statistics 2011-2012",
      "type":"ckan-resource",
      "url":"https://data.gov.au",
      "datasetId":"taxation-statistics-2011-12",
      "resourceId":"205ef0d1-521b-4e3c-a26c-4e49e00f1a05"
   },

],
```

**Comment by nf-s** [comment]
Added to v8 through #5776
