### ISSUE TITLE
CSV "minDisplayValue" and "maxDisplayValue" do not work

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#2351]
The `minDisplayValue` and `maxDisplayValue` for CSV data doesn't work.

In the following screenshot I have a max of 250 and a min of 123, neither the max or the min stops higher and lower values from being shown, and the min value is also being displayed on the legend:

<img width="229" alt="screen shot 2017-02-01 at 14 31 58" src="https://cloud.githubusercontent.com/assets/5283003/22494482/00f0e508-e88c-11e6-9c94-3f4dc8092e6a.png">

Attaching an init file and the test CSV used.

[Postcode.csv.txt](https://github.com/TerriaJS/terriajs/files/743809/Postcode.csv.txt)

[Testing2.json.txt](https://github.com/TerriaJS/terriajs/files/743811/Testing2.json.txt)

**Comment by kring** [comment]
Looking at `LegendHelper.js`, particularly the `buildBinColors` function, it looks like `minDisplayValue` and `maxDisplayValue` are only used when color bins are explicitly provided, which doesn't make much sense.

**Comment by nf-s** [comment]
v7
