### ISSUE TITLE
Mark catalog item as load on startup? 

### ISSUE THREAD

**Issue by daumann** [TerriaJS/terriajs#2357]
Refering to the init file: 
http://terria.io/Documentation/guide/customizing/initialization-files/

Is there a property to mark it as 'add on startup'? If not, what is the suggested way to do this?

**Comment by kring** [comment]
Do you mean a property to add a particular catalog item to the Workbench (panel to the left of the map) immediately upon loading the catalog?  If so, you simply need to include:

```
"isEnabled": true
```

In the catalog item JSON.

**Comment by daumann** [comment]
Indeed, I just came across http://terria.io/Documentation/guide/connecting-to-data/catalog-type-details/geojson/. Thanks for the quick reply!

**Comment by kring** [comment]
Cool, glad you were able to figure it out.
