### ISSUE TITLE
Adding dataset does a feature info

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#2364]
When you add a dataset by clicking the (+) button the the data catalogue, the click is let through to the map and a GetFeatureInfo us performed:

![adddata](https://cloud.githubusercontent.com/assets/5283003/22868165/d983cf58-f1e6-11e6-9903-b7398ccf854a.gif)

**Comment by kring** [comment]
That's not a click through, it's a :feature:.  Added in #2112 to address #2087.
