### ISSUE TITLE
Are there interfaces to modify my connected data feature?

### ISSUE THREAD

**Issue by daumann** [TerriaJS/terriajs#2375]
After having connected a geojson feature to terriajs, how can I access that feature problematically and for example change the color of individual polygons?

**Comment by kring** [comment]
You can set styles for individual features prior to loading by specifying [simplestyles](https://github.com/mapbox/simplestyle-spec/tree/master/1.1.0).  You can also use the Cesium Entity API to configure things after loading.  The Cesium `DataSource` is available from the `GeoJsonCatalogItem` from the `dataSource` property, and you can access the entities at `geoJsonCatalogItem.dataSource.entities.values`.  Best place to learn about how to use Cesium Entities is here: https://cesiumjs.org/tutorials/Visualizing-Spatial-Data/
