### ISSUE TITLE
Allow different names for the Catalog and once added

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#2378]
Especially with the new ABS data, often the catalog item name winds up only making sense in context, eg:
![image](https://cloud.githubusercontent.com/assets/1757858/22962972/5d5b423e-f3a4-11e6-8d19-759095938ae9.png)

This is not ideal on the left of the screen, or for Feature info headings - especially if the sections are collapsed and there's more than one.
![image](https://cloud.githubusercontent.com/assets/1757858/22962947/46a90f62-f3a4-11e6-8aed-ae9343ec2224.png)

It would be nice if the name of the item in the now-viewing panel and feature info could be different to the catalog item name.

**Comment by tephenavies** [comment]
@RacingTadpole I'd be more inclined to use the catalog item name for the now viewing panel and feature info and add a title or something for the title shown in the catalog. Not sure how well that would work with catalog groups (other than just using the current method to set both title and name).
