### ISSUE TITLE
Monthly SDMX data appears/disappears too quickly

### ISSUE THREAD

**Issue by tobybellwood** [TerriaJS/terriajs#2393]
vis-a-vis http://nationalmap.gov.au/#share=s-xFuKjATQVRger0g7Ci25vBRAGax

The map paints and then repaints too quickly - obv a slow down fixes it, but can it be logicked?

**Comment by RacingTadpole** [comment]
Yes, I see this for Housing Finance too.

**Comment by RacingTadpole** [comment]
This will help: https://github.com/TerriaJS/nationalmap/pull/458 "Turn off the automatic animation of time-series data"

**Comment by kring** [comment]
Currently the clock multiplier (number of simulation seconds that pass per real second) for tabular layers is (arbitrarily?) computed as `(stop-start) / 120` in `TableStructure.js`.  A better heuristic might be along the lines of "the multiplier that has us viewing each interval for an average of 5 seconds", or something along that line.

**Comment by nf-s** [comment]
Added in v8 by #4986
