### ISSUE TITLE
Empty grey bar on small screens if no workbench

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#2421]
When the workbench is hidden on a small screen, you get an empty grey bar along the top.

![image](https://cloud.githubusercontent.com/assets/1757858/23929087/b5eb03ec-0977-11e7-8b48-801fb88f308b.png)

We could either always display the workbench menu bar for a small screen, or remove the grey bar.

@chloeleichen - any interest? :-)

**Comment by kring** [comment]
This is somewhat mitigated by the fact that you can't enter full-screen mode on mobile.  But it's still fairly serious if a link goes full screen using URL parameters and then it's viewed on mobile. And it's probably an easy fix (ignore the full screen mode on small screens).

**Comment by chloeleichen** [comment]
Fixed
