### ISSUE TITLE
Terria map about page has info for NationalMap, not Terria Map

### ISSUE THREAD

**Issue by bsimyo** [TerriaJS/terriajs#2429]
I'm not sure if this issue belongs with this repo but here goes... clicking on the "about" button or on the logo in the top left hand corner at http://map.terria.io goes to map.terria.io/about.html which is the same text as the National Map about page (and shouldn't be).

We should change the content of that page to be about Terria map rather than about National Map.  This would mean removing pretty much all of the current info on the page, adding a short description of the purpose of the Terria map (eg as a showcase for TerriaJS features) and the nature of the datasets on it and creating a link to http://terria.io for more info about TerriaJS.

**Comment by kring** [comment]
The About link on http://map.terria.io now goes directly to http://terria.io, which I think is ok.

But the About button in https://github.com/TerriaJS/TerriaMap goes to about.html, which still talks about NationalMap.  TerriaMap should have a proper about page, or at least link directly to http://terria.io like map.terria.io does.

**Comment by rowanwins** [comment]
Resolved - TerriaMap about page now goes directly to terria.io
