### ISSUE TITLE
How to debug CSW queries?

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#2431]
I constructed a CSW getrecords request in python, verified that it worked, returning 17 records, as seen in cell [6] here: https://gist.github.com/anonymous/8ca00c0386618a87062f9b8b490b3161
 
I then tried to implement the same query for TerriaJS only changing the  `startPosition` and `maxRecords` here: https://raw.githubusercontent.com/USGS-CMG/terriajs-dive/master/examples/csw_unidata.json

but when I open this in TerriaJS:

http://gamone.whoi.edu/terriajs/#clean&proxy/_60s/https://raw.githubusercontent.com/USGS-CMG/terriajs-dive/master/examples/csw_unidata.json

I get that the CSW group I created is empty:
![2017-03-16_14-43-31](https://cloud.githubusercontent.com/assets/1872600/24013200/0240cfa8-0a57-11e7-8ba6-6649993b5c49.png)

What is the best way to debug problems like this?

**Comment by rsignell-usgs** [comment]
Ah wait, perhaps the reason is that we didn't add a filter for WMS services only.

**Comment by rsignell-usgs** [comment]
Darn, that wasn't it.  I added WMS query and still an empty group.

**Comment by tephenavies** [comment]
The way I debug these issues is:
1. Check TerriaJS query to the server and response (using Chrome debugger Network tab)
2. Check TerriaJS' parsing of that response (using Chrome debugger breakpoints in loading code)

Looks like [here](https://github.com/TerriaJS/terriajs/blob/cdbe9c80b7/lib/Models/CswCatalogGroup.js#L320-L325) is where the problem is. TerriaJS expects records to be in `SearchResults.Record`, but the records are in `SearchResults.SummaryRecord`. I'll leave that to @kring to decide whether that's a problem with the server or with TerriaJS.

**Comment by kring** [comment]
I don't know the reason for the difference, but if it's a common situation we can easily teach TerriaJS to look for `SummaryRecord` too.  We just need to change these lines in `CswCatalogGroup.js`:

```
if (!defined(searchResults) || !defined(searchResults.Record)) {
    return;
}
```

to:

```
if (!defined(searchResults) || (!defined(searchResults.Record) && !defined(searchResults.SummaryRecord)) {
    return;
}
```

And this line:

```
var records = searchResults.Record;
```

to:

```
var records = searchResults.Record || searchResults.SummaryRecord;
```

To echo what @steve9164 just said, unfortunately the only way to debug this sort of problem is to step through the code in the debugger.    Specifically the `then` after `loadWithXhr` in `CswCatalogGroup.prototype._load`.

**Comment by rsignell-usgs** [comment]
Wow, thanks for the sleuthing and tips for debugging....

Isn't it strange that similar queries with the same CSW endpoint work just fine in TerriaJS, for example:
http://gamone.whoi.edu/terriajs/#clean&proxy/_60s/https://raw.githubusercontent.com/USGS-CMG/terriajs-dive/master/examples/ioos_csw.json
So I guess from this diagnosis, these must come back in `searchResults.Record`?    
I'll investigate...

**Comment by tobybellwood** [comment]
Not sure if this is helpful, but the original `csw_unidata.json` is *explictly* requesting a summary record,

<csw:ElementSetName>summary</csw:ElementSetName>

 whereas `ioos_csw.json` is requesting full records as per TerriaJS expectations

<csw:ElementSetName>full</csw:ElementSetName>

**Comment by rsignell-usgs** [comment]
@tobybellwood , woohoo!  Thanks so much!  That was it!
I just needed to change `<csw:ElementSetName>summary</csw:ElementSetName>` to `<csw:ElementSetName>full</csw:ElementSetName>` and it works!

This URL: http://gamone.whoi.edu/terriajs/#clean&proxy/_60s/https://raw.githubusercontent.com/USGS-CMG/terriajs-dive/master/examples/csw_unidata.json

now produces this:

![2017-03-17_13-07-29](https://cloud.githubusercontent.com/assets/1872600/24054604/36a99088-0b13-11e7-969a-92706aaa1f9d.png)

**Comment by kring** [comment]
Nice catch @tobybellwood!

**Comment by tobybellwood** [comment]
It's probably worth considering accepting SummaryRecords as a fallback as outlined above - as I understand, CSW provides them by default, or if a valid schema isn't presented.  They should still have enough detail to provide catalog items.
