### ISSUE TITLE
Enhancing ERDDAP's WMS to work better with TerriaJS

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#2437]
I'd like to help make the [ERDDAP](https://coastwatch.pfeg.noaa.gov/erddap/index.html) WMS service work more effectively with TerriaJS.    An example ERDDAP WMS GetCapabilities request is: 
http://coastwatch.pfeg.noaa.gov/erddap/wms/NWW3_Global_Best/request?service=WMS&request=GetCapabilities&version=1.3.0

A few things so far seem to be: 
* Including Web Mercator Projection (EPSG: 3857) so that it can work with TerriaJS in 2D. 
![2017-03-18_13-17-04](https://cloud.githubusercontent.com/assets/1872600/24074485/172804ba-0be0-11e7-8256-fcb243157eb8.png)
* Using interval time specification in the GetCapabilities to reduce the size instead of a list of all available times. 
* Including the ability to handle ncWMS `COLORSCALERANGE` parameters to control the color map extents. 
* Fixing a problem where only East Longitude is displayed (1/2 the world) on global datasets:

![2017-03-18_13-27-49](https://cloud.githubusercontent.com/assets/1872600/24074466/b2deae5a-0bdf-11e7-8d2c-3c9d4c66db03.jpg)

This last one I'm not sure is an ERDDAP bug, so I'm asking here before reporting.   Could this be a TerriaJS issue?   

Does anyone know why half the globe is showing no data in TerriaJS?

This URL should bring up the WMS in question in TerriaJS: http://tinyurl.com/l8pwcsh

**Comment by kring** [comment]
The problem with the layer showing on only half the world is caused by this bit in `GetCapabilities`:
```
        <EX_GeographicBoundingBox>
          <westBoundLongitude>0.0</westBoundLongitude>
          <eastBoundLongitude>359.5</eastBoundLongitude>
          <southBoundLatitude>-77.5</southBoundLatitude>
          <northBoundLatitude>77.5</northBoundLatitude>
        </EX_GeographicBoundingBox>
```

Notice that the `eastLongitude` is `359.5` instead of being in the usual -180 to 180 range.  I can't say after reading the WMS spec that this is _definitely_ invalid, but it's certainly unusual.  We could teach TerriaJS how to deal with it if necessary, though.

**Comment by rsignell-usgs** [comment]
@kring, I think TerriaJS needs to support longitude [0-360] as well.

This isn't exactly the spec, but on the OGC page  http://cite.opengeospatial.org/OGCTestData/wms/1.1.1/spec/wms1.1.1.html, it says: 

> In the particular case of longitude, the following behavior may apply regarding the anti-meridian at 180 degrees of longitude. There is a legitimate desire for maps that span the anti-meridian (for example, a map centered on the Pacific Ocean). However, a strict interpretation of the previous paragraph suggests that areas beyond 180 degrees should be shown as empty content; this corresponds to the STRICT constraint below. A server may choose to relax this behavior by instead applying the LOOSE constraint below. If minx is the west-most longitude in degrees and maxx is the east-most, then:
> 
> STRICT longitude constraint (default):
> -180 <= minx < maxx <= 180
> 
> LOOSE longitude constraint (optional):
> -180 <= minx < maxx < minx + 360 < 540
> 
> Example 1. Earth centered at Greenwich
> minx=-180, maxx=180
> 
> Example 2. Earth with Greenwich at left edge
> minx=0, maxx=360
> 
> Example 3. Pacific Ocean
> minx=120, maxx=250

**Comment by rsignell-usgs** [comment]
Closing this in favor of https://github.com/TerriaJS/terriajs/issues/2451
