### ISSUE TITLE
No pan/zoom to Search Result in 2D Map View

### ISSUE THREAD

**Issue by geoffrowland** [TerriaJS/terriajs#2479]
When a Search Result is selected in 2D Map View, Terria Map does not pan/zoom to the location, as it does in 3D Terrain or 3D Smooth Map View.

**Comment by kring** [comment]
@geoffrowland this was a bug awhile ago, but we fixed it and as far as I can tell it's still fixed.

For example, I visit http://nationalmap.gov.au/#map=2d then type "13 garden street" in the search box, press enter, click the first result, and the map changes to show that location.

If you're still having the problem, try opening your browser's debugger, set it to stop on all exceptions, and see where you end up.

**Comment by kring** [comment]
Or do you mean it doesn't fly smoothly to the location?

**Comment by geoffrowland** [comment]
@kring
Can confirm that this works fine for http://nationalmap.gov.au/#map=2d
But not, in my hands, for a fresh git pull, npm install and npm start of latest TerriaMap

**Comment by kring** [comment]
@geoffrowland I just tried a clean build of TerriaMap, and it seems to work ok there, too.  Can you try opening your browser's debugger, set it to stop on all exceptions, and see if anything comes up when you click on a search result?

**Comment by geoffrowland** [comment]
Just retried with fresh git pull, npm install, npm start and gulp and all now working ;-)
Must have had an older build. Apologies for the false alarm. Issue Closed
