### ISSUE TITLE
Error when adding a layer without first showing preview

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#2501]
Steps to reproduce:
1. Go to AREMI
2. Navigate catalogue to Topography -> Elevation, DO NOT click on the Contours layer
3. Add the Contours layer by clicking the `+` button without having first seen the preview

<img width="926" alt="screen shot 2017-05-03 at 11 54 10" src="https://cloud.githubusercontent.com/assets/5283003/25646054/a8177aec-2ff7-11e7-8229-a7bd09e7ddcd.png">

If you click on the layer name to preview it first then the error doesn't happen.

If you try to add the layer again, when you open the catalogue we automatically select the layer and show the preview, at which point adding the layer works fine.

**Comment by kring** [comment]
The crash is in `DimensionSelectorSection.jsx`.  It gets `const layerDimensions = item.availableDimensions[layerName]` and then dereferences that without first checking that it's defined.

**Comment by kring** [comment]
Fixed by 16e019ff6cc4ad9b01dbd97c775c212b7522615f
(a failure to use git resulted in it going directly to master)
