### ISSUE TITLE
Make hideExplorerPanel=1 work again.

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#2503]
@ajbar7 commented on [Thu Apr 20 2017](https://github.com/TerriaJS/nationalmap/issues/480)

Looks like this was dropped in the new UI - would be useful to have the functionality back.

**Comment by tephenavies** [comment]
Moved to terriajs repo as it applies to core terriajs.

A sensible rename of this option would be `/#hideWorkbench=1` since the side panel is now called the workbench.

**Comment by kring** [comment]
Makes sense, but let's support the old one too for backward compatibility.  There are a couple of sites using it.

**Comment by tephenavies** [comment]
Ok. The best place to put this logic seems to be here:
https://github.com/TerriaJS/terriajs/blob/master/lib/Models/Terria.js#L508-L512
Setting `viewState.isMapFullScreen` to `true` would (should ?) work, but you can't access `ViewState` from there (since it's above the `terria` object).

**Comment by kring** [comment]
You can make `ViewState` itself check `terria.userProperties`.  You can also subscribe to that property in the URL changing and update `isMapFullScreen`.
