### ISSUE TITLE
include lat/long in feature info download

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#2510]
When using the `Download this Table` function to download the raw feature info data, the default CSV file name is `Layer Name.csv`. To make it a little easier for the user to keep track of where the data came from, I think we should name the CSV file like `Layer Name - Lat 123.12345 Lon 123.12345.csv`.

This originated as a request from a user.

**Comment by a-stacey** [comment]
I can't assign (...presumably because I'm not currently a member), but just a note to indicate that I'm currently looking into this.

**Comment by meh9** [comment]
This has been merged and is in the latest AREMI release.
