### ISSUE TITLE
Quotes in csv files can break terria

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#2516]
Eg. try dragging this onto your map:

```
name,lat,lon,chart
A,-34.8,146.3,<chart src="http://example.com"></chart>
```

It will fail without explanation, but pausing on caught errors reveals it fails in `csv.js`.

**Comment by kring** [comment]
Well that's an invalid CSV, to be fair: https://tools.ietf.org/html/rfc4180 (section 2, points 5, 6, and 7).

But we should at least fail _with_ an explanation. :)

**Comment by RacingTadpole** [comment]
What! There's a standard for csv! I had no idea.
> If fields are not enclosed with double quotes, then double quotes may not appear inside the fields.

Well, in that case, when we write out csv files, we need to make sure we write a valid csv file. I'll add another issue for that.

**Comment by kring** [comment]
When loading this file, TerriaJS current fails with:
![image](https://user-images.githubusercontent.com/924374/35957759-5f9f33cc-0cf1-11e8-9a00-1b12528973b0.png)
Which I think is good enough to close this.
