### ISSUE TITLE
Clearing the location search does not repaint map

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#2524]
1. Make sure you're in 3D mode.
2. Search for a location and click one to show the map marker.
3. Wait a few seconds without moving the cursor over the map window.
4. Click the X next to the search box (again without moving the mouse over the map window).

The marker will not disappear until you move the mouse in the map window again.  This is caused by a missing call to  `notifyRepaintRequired`.

**Comment by tephenavies** [comment]
This bug is no longer present
