### ISSUE TITLE
Hide the CkanCatalogGroup "no group" group when it's empty.

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#2525]
In the data.gov.au group on NationalMap:

![image](https://cloud.githubusercontent.com/assets/924374/26040332/b9928536-3967-11e7-8a51-19656cecf43b.png)

**Comment by kennib** [comment]
Given this piece of the code https://github.com/TerriaJS/terriajs/blob/3e5009e77e306456750963efd3f3d8ece719736a/lib/Models/CkanCatalogGroup.js#L662-L668 it seems that it's not possible for a the "No group" to exist without an item inside of it. I also wasn't able to find any examples of empty "No group"s in national map.

**Comment by kring** [comment]
Yeah agree it seems to no longer be an issue, thanks @kennib.
