### ISSUE TITLE
Make Zoom To work with KML

### ISSUE THREAD

**Issue by juan-guerschman** [TerriaJS/terriajs#2547]
"zoom to extent" not working with kml.
I have also tried it in the past with other upload formats and I think I had the same problem. 
I have just tried with the file below. 

[MurrayLLS VegMachine 30_May_2017.zip](https://github.com/TerriaJS/terriajs/files/1051173/MurrayLLS.VegMachine.30_May_2017.zip)

**Comment by kring** [comment]
KML can define initial camera parameters, and we even have some support in TerriaJS for interpreting them (see `CameraView.fromLookAt` and `CameraView.fromPositionHeadingPitchRoll`). I think Cesium also allows you to zoom to the `KmlDataSource`.  We just need to hook this all up.
