### ISSUE TITLE
Lots of cancelled request issued when "flying" into a selected destination

### ISSUE THREAD

**Issue by prl900** [TerriaJS/terriajs#2552]
When the name of a city is entered in the search box, terriajs gets in flight mode, zooms out travels to the destination and zooms in, all in milliseconds. The behaviour of browsers (at least chrome) is to issue all the intermediate requests by cancelling previous ones after issuing them. This floods any WMS server with sometimes hundreds of cancelled requests that still need to be processed on the server side.

This might not be exclusive of the "flight mode" when entering a new location in the search field of the National Map and might be the default behaviour for all the cases that require scrolling though space and time.

A possible solution might be in the lines of applying a kind of delayed firing of request: ie when zooming, it could start tile requests in javascript using up to N setTimeout calls with a short delay, say 100ms. Each step of the zoom cancels the previous calls with N cancelTimeout calls, and N new setTimout calls. If the zoom steps are <100ms apart, only the last step is actually requested.

**Comment by kring** [comment]
@prl900 web browsers will only issue 6 requests simultaneously per hostname, so we certainly shouldn't see the server get flooded with hundreds of simultaneous requests that are then canceled.  Yes, hundreds of requests may be created in the browser (in 2D that is, 3D won't even do this) but most of those requests won't actually be sent to the server before they're canceled.

By the way, with most web frameworks, it's also possible to detect when the client disconnects.  The server should stop processing when it detects this.

I don't think we want to insert a tile download delay.  Even 100ms would have a noticeable affect on the responsiveness of the map.

**Comment by prl900** [comment]
Thanks for looking at this @kring. After looking at the WMS server logs and the browser requests, we can see that all the intermediate requests are effectively sent to the server.

What I think it's happening here is that although a single browser cannot issue more than 6 concurrent requests they can cancel pending requests and send new ones. Servers will receive all these requests and naively try to process them all.

It would be really helpful if you could verify that cancellations happen after submitting the requests. It would also be good to know if this is the intended behaviour for the client. Also, any ideas that you have on how to handle this situation on the server side will be highly appreciated.

**Comment by kring** [comment]
Yes, you're right.  The browser will cancel requests, in some cases after already sending them to the server, and then issue new ones.

The cancellation seems to be working ok, at least according to the Chrome debugger:
![image](https://user-images.githubusercontent.com/924374/26958180-850851de-4d0c-11e7-8979-04bb43b22db1.png)

These are base map requests in my screenshot, but it should be the same for any layer.

What sort of server/server-side framework are you using to handle web requests?  The mechanics of checking for a disconnected client will be different depending on what you're using.

**Comment by seanpringle** [comment]
The service is Golang.

All incoming connections from our perspective come from a TerriaJS proxy IP (I assume that means this: http://nationalmap.gov.au/build/TerriaJS/doc/reference/CorsProxy.html)

Testing with a single user, we see steady load with connection concurrency of ~6 for most normal activity, until the described flight mode kicks in when we quickly get 6 then 12 then 18 ... etc, spiking to hundreds of nigh-simultaneous connections arriving with progressively larger bounding polygons.

Obviously hundreds of connections is no real problem, but it's strange that this can be caused by a single client. Since the IP is always the that of the Proxy, we can't really apply any anti-DoS strategy without affecting everyone.

Do we know whether the cancellation of connections on the client-side reliably propagates through the TerriaJS proxy to the backing WMS service?

**Comment by kring** [comment]
@seanpringle I'm _fairly_ sure the proxy should do this correctly, but it'll take me a bit to work out a reliable way to verify it.  FWIW, here is the code in the proxy that is meant to take care of it:
https://github.com/TerriaJS/terriajs-server/blob/master/lib/controllers/proxy.js#L141

**Comment by seanpringle** [comment]
Fair enough.

@prl900, time to sniff some network traffic and verify we understand how the WMS end is handling aborted connections.

**Comment by prl900** [comment]
Thank you @kring for the suggestions on how to handle http cancellations. Our system is now handling cancellations and propagating them internally. 

This is no longer an issue from our side so feel free to close it if you think this is the correct behaviour for your client.
