### ISSUE TITLE
Track `terriajs` tag on stackexchange?

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#2556]
Does someone from the team track the tag `terriajs` on stackexchange?
You can use "my filter" to create a daily e-mail with `terriajs` questions:
![screenshot from 2017-06-13 11-25-13](https://user-images.githubusercontent.com/1872600/27075693-3b63d63a-502b-11e7-9c8f-0afbba637c1c.png)

**Comment by kring** [comment]
I wasn't, but now I am,  Thanks!
