### ISSUE TITLE
New workbench items replace existing ones with identical names

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#2561]
When a process adds a new workbench item that has the same name as an existing workbench item, the original one is replaced.

1. Use GEOGLAM: http://map.geo-rapp.org/ 
2. Use the Query Data function at the top of the Data Catalogue
3. Use the Polygon feature and draw a polygon about the size of the ACT, and click Run Analysis
4. You should get a chart with data, and two new workbench items, `Precipitation` and `Veg. Frac.`
5. Do another polygon and Run Analysis
6. When the workbench items come through they replace the existing two items

<img width="350" alt="screen shot 2017-06-14 at 17 40 05" src="https://user-images.githubusercontent.com/5283003/27120893-8f737a52-5128-11e7-9bb0-78ce2b421337.png">

A way to solve this might be to dynamically name new items in a way that shows they are connected to the (in this case) WPS request item in the workbench that shows the result of the WPS request, i.e. `Query Data <timestamp>`.

**Comment by kring** [comment]
I'm not sure what's going on here.  The catalog tends to do this sort of name-based merging, but the workbench shouldn't.  Definitely seems like a bug.
