### ISSUE TITLE
Why do csv bird migrations disappear briefly at the end?

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#2567]
When you show the [bird migration csv](https://gist.githubusercontent.com/RacingTadpole/f308c8d01630b3d0b15d946e259b0cff/raw/266b62cab3716d76fe4c24f9788489ebfd8c7efa/bird_migration.csv), there is a period at the end of the timeline when all the birds disappear. Contrast the seamless repeat in the czml version on map.terria.io.

Why? Can we set a final time to show? Or a default time step (`"displayDuration": 10080` helps, but there's still a week at the end with no birds)?
Also, can we change the animation speed in csv, like you can in czml?

**Comment by RacingTadpole** [comment]
Here's a sample csv file that keeps things simple:
```
date,lat,lon,value,enum,id
2015-01-01T00:00:00Z,-35,140,2,foo,1
2015-01-01T00:30:00Z,-36,141,2.7,bar,1
2015-01-01T01:00:00Z,-37,140,3.2,eel,1
2015-01-01T01:30:00Z,-38,141,2.9,abc,1
```
There is a final half-hour appended where the point disappears. For non-moving-point csvs that's typically what you want, otherwise the last time only exists for an instant.

Q: Do we always want this final period for non-moving-point csvs, and never want it for moving-point csvs?

If the answer is yes, then it's clear what to do. Otherwise, I think we just need a new option to skip the final period, so the animation play loop can go back to the first datetime immediately.

**Comment by kring** [comment]
Yes, the timeline for your example CSV should end at `2015-01-01T01:30:00Z` rather than continuing for another 30 minutes without any data. But for a non-moving point, as you said, we should extend the final time, just as we do for all other times.

**Comment by AnaBelgun** [comment]
This is needed to be fixed for ACT CSD project showing migration of housing IDs.
