### ISSUE TITLE
`json` files appear in workbench

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#2574]
If I drag a json catalog file onto the map, the json file itself appears on the left hand side, as well as having its contents appear in the catalog. Eg. (here I have also enabled an item from the json file called "Bird migration"):
![image](https://user-images.githubusercontent.com/1757858/27465767-eab95ba6-5818-11e7-9912-d75719c502d0.png)
Clicking "Remove" on the json item has no impact on the catalog.

Is there a reason we want that json file to appear there?  I think it's confusing and unnecessary.

**Comment by kring** [comment]
No reason, it's a bug.

**Comment by RacingTadpole** [comment]
Weird. I can't reproduce it now.

**Comment by kring** [comment]
Yeah this was fixed awhile ago.  It still appears while loading, but disappears afterward.
