### ISSUE TITLE
"Zoom to extent" doesn't work for SDMX-JSON

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#2579]
See https://github.com/TerriaJS/nationalmap/issues/520

**Comment by RacingTadpole** [comment]
@kring you said this should at least zoom to the default extent - are you suggesting we include that default extent in the catalog item json, and pull it from there?
That shouldn't require any code changes, right - just an `extent` property in the json?

**Comment by kring** [comment]
It used to be the case - I think it still is - that if there's no extent defined, Zoom To goes to the map's default extent.  But SDMX catalog items don't seem to do that for some reason.

Adding an extent to the catalog item is a good workaround, and also a good idea if we can provide a more specific extent than the map's default one (but probably not true in this case).

**Comment by RacingTadpole** [comment]
Seems to be true of any region-mapped csv file, right?

**Comment by kring** [comment]
Yeah could be.

**Comment by RacingTadpole** [comment]
um... https://github.com/TerriaJS/terriajs/blob/master/lib/Models/CatalogItem.js#L737-L739 suggests that if `rectangle` is not defined on an item, then `zoomTo` does nothing... have I misunderstood?
