### ISSUE TITLE
Validate a time/date column before using it

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#2589]
The time/date regex is quite permissive, and occasionally it tries to interpret columns that are not time columns. Since TerriaJS [already sorts by the time column](https://github.com/TerriaJS/terriajs/blob/bde847c34/lib/Map/TableStructure.js#L162), it shouldn't be a performance burden to check each row to make sure the column is a time column.

Test csv ([nationalmap link](https://nationalmap.gov.au/#start=%7B%22version%22%3A%220.0.05%22%2C%22initSources%22%3A%5B%7B%0A%22catalog%22%3A%20%5B%7B%20%0A%20%20%22name%22%3A%20%22test%22%2C%0A%20%20%22type%22%3A%20%22csv%22%2C%0A%20%20%22data%22%3A%20%22column%20that%20is%20not%20time%2Cvalue%2Csa4%5Cngreen%2C6%2C101%5Cnblue%2C3%2C102%22%0A%7D%5D%0A%7D%5D%7D)):
```
column that is not time,value,sa4
green,6,101
blue,3,102
```

What happens:
- Column is interpreted as time
- Timeline shown with NaNs because times could not be parsed
- No visualisation shown

What should happen:
- Time column identified
- Time column validation fails
- Visualisation drawn as a region mapped layer with no timeline (and with that column as a potential data variable)

**Comment by meh9** [comment]
Yeah, I help a fair number of people with problems caused by over eager time columns. It'd be great if we could make this better.

**Comment by tobybellwood** [comment]
I'm guessing this is a similar issue to #2354 ?

**Comment by meh9** [comment]
@tobybellwood yeah I think it's pretty much the same issue.

**Comment by tephenavies** [comment]
Closed in favour of #2354.
