### ISSUE TITLE
"isShown": "True" causes error on load

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#2596]
This JSON file causes an error when dragged into a TerriaJS map:

```json
{
	"homeCamera": {
		"north": -8,
		"east": 158,
		"south": -45,
		"west": 109
	},
	"catalog": [
		{
			"name": "Test Smart Cities Performance Dashboard Data",
			"cacheDuration": "60s",
			"type": "csv",
			"isEnabled": "True",
			"isShown": "True",
			"url": "https://raw.githubusercontent.com/ajbar7/super-duper-adventure/master/nm_cities.csv",
			"tableStyle": {
				"colorPalette": "5-class YlGnBu",
				"timeColumn": null,
				"scale": 2
			}
		}
	]
}
```

![image](https://user-images.githubusercontent.com/924374/28154806-f38d59fe-67ee-11e7-8ff5-b94b68722dcf.png)

Really the values of `isEnabled` and `isShown` should be `true` (without quotes and lowercase first letter) instead of `"True"`, but we can probably handle this better.

**Comment by zoran995** [comment]
`isShown` is no longer used in v8
