### ISSUE TITLE
Clicking Expand on preview chart with no data results in error

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#2615]
If a user Expands multiple preview charts, and one of them has no data, and error will result.

Steps to reproduce:
1. Try using an AREMI power station generation layer: http://nationalmap.gov.au/renewables/#share=s-gJauD6FB1JUJM2NF
2. Expand 1d a power station that will have data, i.e. the point has some colour.
3. Expand 1d a station that does not have data, i.e. an empty/clear point.

You can also reverse the order, i.e. empty first and then data, and the same thing happens.

You should now see this:

<img width="861" alt="screen shot 2017-08-03 at 2 37 56 pm" src="https://user-images.githubusercontent.com/5283003/28919173-ab5cd694-788f-11e7-8766-7864c59e5cc1.png">

**Comment by zoran995** [comment]
error doesn't occur in v8
