### ISSUE TITLE
Default on layer error prevents additional init file from loading

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#2618]
On GEOGLAM we have layers that are default on when you first arrive at the site. However, this morning one of them is returning an error. It appears that the erroring layer is preventing an additional init file from loading:

https://map.geo-rapp.org/#australia

This usually causes the view to centre on Australia and a number of additional layers to be added to the catalogue, but because of the error this doesn't happen.

**Comment by tephenavies** [comment]
The above no longer shows the error. Can be reproduced at `http://localhost:3001/#secondary` with  TerriaJS/nationalmap@55d3993.

**Comment by zoran995** [comment]
this seems to work correctly in v8
