### ISSUE TITLE
Warn the user before loading large vector data files

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#2638]
As reported in TerriaJS/nationalmap#564, large vector data files can cause the browser to hang or crash.  The web platform doesn't give us great tools for defending against this, but we can at least set a conservative size limit, above which we warn the user before trying to load and display the file.

**Comment by AnaBelgun** [comment]
@philipgrimmett @nf-s shall we have a unified approach / warning message for uploading or downloading/exporting large files?

Even if we only settle on the warning system with this ticket, that's good progress for now.

**Comment by nf-s** [comment]
There is a PR in progress for this feature https://github.com/TerriaJS/terriajs/pull/6038
