### ISSUE TITLE
Pull up/reproduce `initialTimeSource` functionality so it can be used by CSV timeseries data

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#2640]
`ImageryLayerCatalogItem` supports the `initialTimeSource` property that can be used to control what the default state of the timeline should be in, `start`, `present`, `end`. We would like to be able to use this functionality for CSV timeseries data as well, so that we can set the timeline to start at the end, or present time, on the timeline.

**Comment by RacingTadpole** [comment]
Here's the offending line: https://github.com/TerriaJS/terriajs/blob/master/lib/Map/TableStructure.js#L551

**Comment by a-stacey** [comment]
Example catalog entry `"initialTimeSource": "end",`
