### ISSUE TITLE
Rationalise region-mapped `TableCatalogItem`s and `ImageryLayerCatalogItem`s

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#2642]
Noted as an issue in https://github.com/TerriaJS/terriajs/pull/2641.

Region-mapped data (from csvs, SDMX-JSON, SOS2 etc) is a TableCatalogItem, with a RegionMapping property (`_regionMapping`).
RegionMapping is very similar to ImageryCatalogItem. It even calls some of ImageryCatalogItem's functions, which are awkwardly defined on the class (with first argument being the instance) rather than the prototype.

It would be great to either:
- Pull out the essential "imageLayer" code into a separate class/mixin. And perhaps separate the essential "time-varying" code too, if that makes sense.  Then both `ImageryCatalogItem` and `RegionMapping` could extend from them.
Or:
- Instead of `TableCatalogItem` having `_regionMapping` and `_dataSource` (for lat/lon tables) properties, make it _be_ both, so that it is in fact an ImageryCatalogItem - but one that doesn't always have an imagery layer.

Not sure if this is worth doing, or which path is better.  @kring?

This would also be useful for some work @steve9164 is doing too, and would neatly solve #2640 too.

We could take it even further with a "splittable" mix-in too.

**Comment by nf-s** [comment]
v7
