### ISSUE TITLE
WMTS imagery rendered in wrong location

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#2657]
These WMTS layers have the imagery rendered in the wrong location in the world - everything appears moved up and right:

[test2.json.txt](https://github.com/TerriaJS/terriajs/files/1279781/test2.json.txt)

Note that they are rendered correctly on NASA Worldview: https://worldview.earthdata.nasa.gov/?p=geographic&l=Landsat_WELD_CorrectedReflectance_TrueColor_Global_Annual,Coastlines&t=2009-09-18&z=2&v=-211.73187661444342,-114.03876606641082,186.15114793304582,114.19135773652398&ab=off&as=2010-01-18&ae=2011-11-21&av=3&al=true

<img width="1440" alt="screen shot 2017-09-06 at 14 39 59" src="https://user-images.githubusercontent.com/5283003/30094752-78c464e4-9311-11e7-8acd-6b4274cd8d85.png">

**Comment by tephenavies** [comment]
That layer is only available in EPSG 4326, which is not supported in TerriaJS.
