### ISSUE TITLE
Add ability to get and format the current timeline time in feature info template

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#2658]
Since we update the values in the feature info when the time changes on the timeline, it would be very useful to be able to show at which time we are actually showing the values for. We should add access to the current time of the timeline (or the current time of the actual data from the layer if possible?) as well as a formatting function for it similar to the mustacheFormatNumberFunction or mustacheURLEncodeTextComponent.

It's been suggested it should be relatively easy to add the data in here:

https://github.com/TerriaJS/terriajs/blob/master/lib/ReactViews/FeatureInfo/FeatureInfoSection.jsx#L76-L95

**Comment by a-stacey** [comment]
>  Since we update the values in the feature info when the time changes on the timeline, it would be very useful to be able to show at which time we are actually showing the values for.

Talking this through with @axman6 and we realised that the value only updates with the date when you select a new point after you have updated the position on the time line. For now I will just assume that we want to show the time for the info shown.

**Comment by a-stacey** [comment]
Update to the above the FeatureInfo also updates when you hit play on the timeline. So it just doesn't update when you manually select a new time...maybe it should?

**Comment by a-stacey** [comment]
@meh9 check out  PR #2782 and see if it meets your requirements in terms of formatting. It should be effectively formatting as per https://www.npmjs.com/package/dateformat and the format for the mustache feature info section will look like: `{{#terria.formatDateTime}}{"dateFormatString": "dd-mm-yyyy HH:MM:ss"}{{terria.currentTime}}{{/terria.formatDateTime}}`.

**Comment by a-stacey** [comment]
This was fixed and merged as part of this PR: https://github.com/TerriaJS/terriajs/pull/2782
