### ISSUE TITLE
New workbench timeseries date picker does not work with timeseries CSV's

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#2701]
E.g. working with the TerriaJS test CSV's:

http://terria-cube.terria.io/#share=s-b93n9Kgmk1A8fAIvvhwjE5Gh5iI

The timeline works to select a time, and drag, play, pause etc, but the new workbench date picker for the splitter work never updates, and is always stuck on the same date, with no other dates available:

<img width="348" alt="screen shot 2017-10-23 at 16 05 28" src="https://user-images.githubusercontent.com/5283003/31873026-3848b13e-b80c-11e7-841c-3635e6d56c23.png">

Maybe at this point it makes sense to be able to disable the new date picker and splitter work for timeseries data so that it doesn't hold up a release?

**Comment by RacingTadpole** [comment]
A potentially related problem is #2723
