### ISSUE TITLE
Sharing a point from the Search

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#2706]
It doesn't seem to be possible to share a location you've found in the Search - it's there in the mini screenshot we show in the Share URL function, but when you go to the link the Search is empty and we don't show a marker on the map.

E.g. search for Canberra, click on one of the results to zoom to the location and show a marker, click Share and go to the new Share URL produced. Note the lack of Search results and no marker.

This is also related to https://github.com/TerriaJS/terriajs/issues/2697

**Comment by a-stacey** [comment]
This was resolved via 620d35e326941251c1fe7155cd21707f1ecad638.
