### ISSUE TITLE
Tools: count function isn't stable

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#2713]
I used the tools to count datasets and I get different counts.

The first time I went to the site and started the Count straight away, on another tab I went to the site, opened the catalogue and searched for something, and only once the Loading finished did I exit and start the Count. The second count got significantly higher number of datasets.

<img width="1440" alt="screen shot 2017-10-27 at 14 17 05" src="https://user-images.githubusercontent.com/5283003/32090091-6669052a-bb39-11e7-901f-fb346679ebdf.png">
<img width="1440" alt="screen shot 2017-10-27 at 14 16 52" src="https://user-images.githubusercontent.com/5283003/32090092-66a20a46-bb39-11e7-8311-72eb47b44150.png">

**Comment by zoran995** [comment]
Closing as the issue is for v7, which is no longer supported. Added a comment to v8 feature ticket
