### ISSUE TITLE
error when loading MrVBF layer from http://www.asris.csiro.au/arcgis/rest/services/TERN/SRTM_attributes_3s_ACLEP_AU/MapServer

### ISSUE THREAD

**Issue by juan-guerschman** [TerriaJS/terriajs#2714]
message is:

Error accessing catalogue item

An error occurred while attempting to download tiles for catalogue item MrVBF. This may indicate that there is a problem with your internet connection, that the catalogue item is temporarily unavailable, or that the catalogue item is invalid. The catalogue item has been hidden from the map. You may re-show it in the Now Viewing panel to try again. Further technical details may be found below.

TileProviderError: Failed to obtain image tile X: 3 Y: 2 Level: 2.

link to reproduce problem: 
http://nationalmap.gov.au/#share=s-mgVs22HvAMs71eGnIndMwkSTlKm

**Comment by kring** [comment]
That link seems to be working fine.  Maybe the server was temporarily having trouble?
