### ISSUE TITLE
'Download this table' dropdown options clipped on iOS portrait

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#2720]
![img_7622](https://user-images.githubusercontent.com/5292858/32254943-5c9bf21a-bef8-11e7-8d2a-ee5bf22485a9.PNG)

**Comment by chloeleichen** [comment]
This problem will go away after the new release, because we have an extra bottom area: 
<img width="390" alt="screen shot 2018-03-05 at 10 39 44 am" src="https://user-images.githubusercontent.com/7508939/36952270-ad38d420-2061-11e8-8d2c-a2d90f9e329e.png">
Closing
