### ISSUE TITLE
New Splitter Datepicker month layout problem

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#2724]
A problem with the layout in the month view of the new splitter date picker has occurred:

<img width="368" alt="screen shot 2017-11-03 at 15 53 21" src="https://user-images.githubusercontent.com/5283003/32360976-4a00389c-c0af-11e7-9ccd-e1c43f53c165.png">

**Comment by a-stacey** [comment]
Also this:
![image](https://user-images.githubusercontent.com/4453477/32361061-67d034ca-c0b0-11e7-8b23-de582478a73f.png)

Under Chrome / Unbutntu 16.04.

**Comment by kring** [comment]
This issue was closed incorrectly.

**Comment by kring** [comment]
But it's not an issue anymore, so closing again. :)
