### ISSUE TITLE
Add loading indicator for catalog tabs

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#2727]
#2692 added support for presenting top-level catalog groups as tabs.  However, if one of the tabs/groups needs loading (i.e. it's not just a `CatalogGroup`), there's nothing in the UI to indicate that this is happening. So the tab will appear blank for the duration of the load.  We should add a loading indicator for tabs.

**Comment by tephenavies** [comment]
Also:
  - [x] Add docs for multiple catalog tabs `config.json` option

**Comment by kring** [comment]
I wrote a separate issue for @steve9164's comment, #2813.

**Comment by nf-s** [comment]
We do have this now, but tabs aren't loading by default - see https://github.com/TerriaJS/terriajs/issues/6489

![image](https://user-images.githubusercontent.com/6187649/183343509-9158f971-9410-49af-9e4f-60411e9e29e0.png)
