### ISSUE TITLE
Splitter does not show correctly in share image for leaflet.

### ISSUE THREAD

**Issue by a-stacey** [TerriaJS/terriajs#2728]
Splitter does not show correctly in share image for leaflet.
Steps to reproduce:
1) Set map to 2D.
2) Enable layer with share visible.
3) Select Share.

![image](https://user-images.githubusercontent.com/4453477/32425620-c4044b50-c308-11e7-9ed1-a50748647674.png)

**Comment by kring** [comment]
This is because html2canvas, which is used to create the screenshot in Leaflet, doesn't properly support the `clip` CSS style.  I looked into fixing this but couldn't find an easy solution.

**Comment by kring** [comment]
A possible workaround - if fixing `clip` is too hard - is to generate separate images with the left and right layers enabled and then stitch them together on a single canvas.
