### ISSUE TITLE
Disclaimer has bad spacing before "Data61"

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#2732]
Can we add a space in before the word "Data61"?

![image](https://user-images.githubusercontent.com/1757858/32476535-0a825928-c3cc-11e7-94a7-c424c606747c.png)

**Comment by kring** [comment]
Where do you see this @RacingTadpole?  Here's what I see on nationalmap.gov.au in Chrome:
![image](https://user-images.githubusercontent.com/924374/35949232-8c1e3dee-0cc4-11e8-89d0-c19568412ce9.png)

**Comment by rowanwins** [comment]
Appears to be resolved
