### ISSUE TITLE
Region type mapping for SdmxCatalogItem

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#2735]
`SdmxCatalogItem` has a `regionNameTemplate` field that can be used to turn an SDMX-provided region name into a csv-geo-au compliant column name.  But templating is not really the right approach; it forces us to add some dodgy column aliases to our regionMapping.json file to accomodate column name choices made by SDMX providers.

A better approach would be a column name mapping.  For example:
```json
"regionNameMapping": {
    "AUS": "AUS",
    "SA4": "SA4_code_2016",
    "FED": "com_elb_2016_with_abs_modifications"
}
```

Consider deprecating `regionNameTemplate`.

**Comment by nf-s** [comment]
v7
