### ISSUE TITLE
Repeated SDMX "multiple values" popups get annoying

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#2747]
#2745 introduced some new behavior and popup when selecting multiple values where those values can't correctly be summed.
![image](https://user-images.githubusercontent.com/924374/32873349-aee062f2-cadf-11e7-9e34-9ebd0c793721.png)
This popup reappears each time you make a change to your active concepts, so it can get annoying quick.  It would be better to show a message like this in the workbench (maybe next to the problematic concept itself?) instead of as a popup.

**Comment by nf-s** [comment]
v7
