### ISSUE TITLE
Vector tiles union feature info popups even where there is no data

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#2750]
The new union of the data from the vector tiles layer together with the data from the CSV being region mapped feature is making the feature info popup appear when clicking on areas with no data. 

As demonstrated here, I've clicked somewhere where there is no mapped region data, but we still get a feature info popup from the two layers - the one with a feature info template has failed to interpolate any data, and the Statistical Area layer shows all of its code data:

http://nationalmap.gov.au/renewables/#share=s-5eoQOh1QntpFzDvG

A solution to this may be to only show the feature info data for regions that have some data from the CSV file mapped to them, and not show anything in the feature info popup for regions that do not have CSV data mapped.

**Comment by AnaBelgun** [comment]
to discuss how long will take to fix
