### ISSUE TITLE
Date display incorrect on newly split layers (Terria-cube).

### ISSUE THREAD

**Issue by SpacemanPaul** [TerriaJS/terriajs#2761]
Possibly related to #2760.    On http://terria-cube.terria.io/ :

1. Add new layer, it defaults to latest available date A.
2. Set date to B with the date picker.
3. Press the "split" button to duplicate the layer and go to split-screen swipey mode.
4. The date picker for the duplicate layer reads date A (the default) but actually displays date B (the same as the original layer).

**Comment by a-stacey** [comment]
Able to reproduce, using layer "Landsat 8 Water Observations from Space (WOfS)" on terria-cube using the date picker on the layer in the workbench. Will look into this.

**Comment by a-stacey** [comment]
This fix has now been merged in master and should be available in the next release cff7affcb636a84fe6ad11974634d8352ac13f7a.
