### ISSUE TITLE
does Terriajs Support KML Vector Super-Overlays from GeoServer?

### ISSUE THREAD

**Issue by geospatialmapmashup** [TerriaJS/terriajs#2778]
Since Terriajs does not support MapBox Vector Tiles (GZipped PBF) I was thinking of sending a network link KML SuperOverlay from GeoServer.

**Comment by tephenavies** [comment]
TerriaJS does support limited rendering of Mapbox Vector Tiles as part of the region mapping implementation: https://github.com/TerriaJS/terriajs/blob/d655082b75da099eca61413adb471b9b435b8f5b/lib/Map/MapboxVectorTileImageryProvider.js#L229-L277

The support is currently:
- polygons only
- styling done by TableCatalogItem

but it should be fairly easy to extend to many different types of geometries and add support for more styling.

We'd love to hear opinions and/or receive contributions to extend MVT support within TerriaJS.

**Comment by kring** [comment]
I'm closing this since it is a question rather than a feature request or bug report. @geospatialmapmashup considering asking your question in our [Gitter channel](http://gitter.im/TerriaJS/terriajs) or [Google Groups forum](https://groups.google.com/forum/#!forum/terriajs).
