### ISSUE TITLE
Opacity has zero displayed whilest selected at 100%

### ISSUE THREAD

**Issue by a-stacey** [TerriaJS/terriajs#2781]
See Image below (Chrome + Ubuntu):
![image](https://user-images.githubusercontent.com/4453477/34473747-9ac64588-efca-11e7-958d-c4da141cfeb6.png)

Steps to reproduce:
1) Load nationalmap.gov.au.
2) Turn on any layer (e.g. broadband quality).
3) Click and drag the opacity to 100% position and notice that a zero appears next to the slide toggle. (Once released the zero will disappear).

Note: Its probably fine to just drop this issue as it is very minor, but since I noticed it I just thought that I would report.

**Comment by QuadTog** [comment]
Furthermore, the Opacity slider does not fully reach zero.
![nationalmap opacity](https://user-images.githubusercontent.com/20583588/38967960-c486f20e-43cc-11e8-9f44-f742779a7046.png)

**Comment by chloeleichen** [comment]
This will be fixed in https://github.com/TerriaJS/terriajs/pull/3164
