### ISSUE TITLE
Include full catalog item path in Google Analytics events

### ISSUE THREAD

**Issue by axman6** [TerriaJS/terriajs#2795]
For AREMI, we pretty regularly have people asking us for specific usage numbers for their layers or layer groups. At the moment, it's very hard or impossible to provide these with any certainty of their accuracy. It would be helpful if the event labels for catalog items were more descriptive so we can better filter events. One way to improve this would be to make the labels for each event include the catalog path as a prefix.

I'm not familiar with what's possible with GA, so there might be reasons for not doing it this way, and  am open to alternatives which achieve the result we want.

**Comment by kring** [comment]
We already include the name of the catalog item.  Are you saying you have multiple catalog items with the same name in different parts of the catalog, and want to be able to tell them apart?

**Comment by meh9** [comment]
@kring yes, we do have some of those, but that isn't really the problem.

We have data custodians who control various subgroups of the catalogue, and they often want to know how often their layers are being used. However, at the moment we would have to create a custom search/report that enumerates all their layers. If the entire "path" of the layer including parent group names was included in the analytics data, then we could easily filter for entire subgroups.

Just including the parent names is a bit of a quick hack, and there may be smarter ways of doing the same thing.

@axman6 any further comments?

**Comment by axman6** [comment]
For the particular issue which has brought us to ask for this is the `Renewable Energy/Bioenergy` group on AREMI which contains hundreds of layers and the custodians responsible for them would like to know on aggregate what's being used.

**Comment by kring** [comment]
Ah ok, so including the full path to the catalog item would be easy, assuming Google Analytics doesn't have a small limit on the length of those things.  The Google Analytics UI still wouldn't let you filter by the path prefix, though. You'd have to write some code to process the results. Is that ok?

**Comment by axman6** [comment]
I might be wrong but I thought I saw a filter for `begins with` or something, but may have imagined that! but either way, having the path would help a lot.

**Comment by kring** [comment]
Ok, sounds good.
