### ISSUE TITLE
Using terrajs without building terriamap.js

### ISSUE THREAD

**Issue by risoms** [TerriaJS/terriajs#2798]
I’m attempting to use terriajs having an issue that I don’t know if I can resolve this issue. Currently I’m using both leaflet and cesium without problems. Finding a package that offers both, with a nice ui to boot, would be amazing. However using a built version of terriamap.js is incredibly slow to load and messy to modify the file (large and cluttered file after using gulp). Is it possible to use terriajs without building all required libraries to one file? For example, I’d rather load d3 and leaflet as separate script files. I’m hoping to do the same with a ‘lean’ version of terriajs. Ultimately this will be for client-side access.

**Comment by kring** [comment]
Hi @risoms, currently there is not a way to load TerriaJS in the way you describe.  I'd argue that you might not really want it even if it were possible. TerriaJS's build process only incorporates the parts of other libraries (and even TerriaJS itself) that are actually needed.  It also defers loading parts of Cesium until they're needed (i.e. if you're using 2D only a mobile device, all the code that supports 3D rendering is not loaded).  If you included all of Cesium and Leaflet and other dependencies, it would actually be quite a bit bigger (not to mention more files for the browser to download). In the past, it has been popular to load standard versions of third-party libraries from a CDN with the idea that, even if they're big, they're also more likely to already be cached by the user's web browser. But in my opinion, this idea has fallen out of favor in recent years, for good reasons.

I think the real question here is, "how can I improve my cycle times in development?"  Are you using `npm run gulp watch`?  That will do a build as normal, but then watch for any changes and perform an incremental build when they're detected.  Incremental build times are usually 3-5 seconds.  You certainly shouldn't be editing the built file directly.

If the build times are still too slow, you can try webpack hot reloading by running `npm run hot`.  This will do even faster builds.
