### ISSUE TITLE
Zero to Terria on Docker / Kubernetes

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#2803]
Would be cool to have a documentation page that explains how to deploy a TerriaJS application on Kubernetes.    I'm thinking of something like this [Zero-to_JuptyterHub page](https://zero-to-jupyterhub.readthedocs.io/en/v0.5-doc/) that talks about how to get Kubernetes going and provides a Helm chart.

**Comment by kring** [comment]
Cool idea!  This probably makes most sense when combined with something like https://github.com/TerriaJS/TerriaMap/compare/modify-brandBarElements, which allows the logos in the top-left to specified in an init file. That way a "generic" TerriaMap build can be provided as a docker image, and customized (logos and catalog at least) externally.

**Comment by kring** [comment]
Or maybe better yet, the generic TerriaMap could load config.json from a Kubernetes configmap.

**Comment by AlexGilleran** [comment]
Done including dynamic config changes from within configmaps :) https://github.com/TerriaJS/terriajs/blob/master/doc/deploying/deploying-with-kubernetes.md
