### ISSUE TITLE
column names with white space break featureInfoTemplate  chart functionality

### ISSUE THREAD

**Issue by zdefne-usgs** [TerriaJS/terriajs#2818]
Following the example given in the documentation for tableStyle and columns withCSV data sets (shown below), 
```
"tableStyle": {
  "columns": {
    "original name": {
      "name": "better name",
      "format": {
        "maximumFractionDigits": 0
      }
    },
    "bad": {
        "type": "hidden"
    }
  }
},
```
the use of "better name" with **white spaces** is problematic with the feature InfoTemplate.             
```
"featureInfoTemplate" : {
                "template" : "<h2>{{terria.timeSeries.title}}<h2><chart x-column={{terria.timeSeries.xName}} y-column={{terria.timeSeries.yName}} id={{terria.timeSeries.id}} column-units={{terria.timeSeries.units}}>{{terria.timeSeries.data}}</chart>",
            },
```
The chart does not display properly and switching between the display variables in the NowShowing box does not refresh the chart in the featureInfoTemplate. If no **white space** it works as expected.

**Comment by kring** [comment]
Thanks for the report @zdefne-usgs. I was able to reproduce this using `bird_migration.csv` linked from #2567 and the following init file:

```
{
    "catalog": [
        {
            "name": "Bird Migration",
            "type": "csv",
            "url": "/bird_migration.csv",
            "tableStyle": {
                "columns": {
                    "speed": {
                        "name": "super velocity",
                        "format": {
                            "maximumFractionDigits": 0
                        }
                    },
                    "bad": {
                        "type": "hidden"
                    }
                }
            },
            "featureInfoTemplate": {
                "template": "<h2>{{terria.timeSeries.title}}<h2><chart x-column={{terria.timeSeries.xName}} y-column={{terria.timeSeries.yName}} id={{terria.timeSeries.id}} column-units={{terria.timeSeries.units}}>{{terria.timeSeries.data}}</chart>",
            }
        }
    ]
}
```

The immediate cause is an exception in `TableStructure.js`:
![image](https://user-images.githubusercontent.com/924374/36234756-eef745d8-1240-11e8-8d10-a29220fe4cee.png)

**Comment by t83714** [comment]
This should be considered as `user error` as any tag attributes should be surrounded by double-quotes. 
Create a PR https://github.com/TerriaJS/terriajs/pull/2885 to update the document to highlight this point.
