### ISSUE TITLE
strange behaviour of a wms layer

### ISSUE THREAD

**Issue by juan-guerschman** [TerriaJS/terriajs#2822]
Not sure if this is Terria related or the problem is somewhere else. 

The Catchment Scale Land Use 2016 doesn't show proper colours at low zoom levels. (https://data.gov.au/geoserver/catchment-scale-land-use-of-australia-update-may-2016/wms?service=WMS&version=1.3.0&request=GetCapabilities) 
seems to be ok at high zoom levels. 
direct link to Nat Map with layer loaded: 
http://nationalmap.gov.au/#share=s-s0pfFj5OefvfPZaqoIAJHfXeLmr

**Comment by AnaBelgun** [comment]
@juan-guerschman Hi, unfortunately there are currently some layers harvested from data.gov.au which do not work. For the CLUM data specifically, we'll be adding the 2017 in this month's release from a separate source. It will be part of National Datasets - Land - Agriculture and Mining catalogue group.

**Comment by kring** [comment]
Not something we can fix, other than the workaround Ana mentioned. Closing.
