### ISSUE TITLE
Share URL does not retain layer order

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#2824]
When you do a share URL with multiple layers in some particular order (e.g. so that small features are not obscured by a base level raster), the order is not retained when the share URL is loaded.

I started with this:

<img width="350" alt="screen shot 2018-02-15 at 14 37 56" src="https://user-images.githubusercontent.com/5283003/36239450-de24bdae-125d-11e8-9855-2a902c2199da.png">

And after loading the share URL I get this:

<img width="352" alt="screen shot 2018-02-15 at 14 38 43" src="https://user-images.githubusercontent.com/5283003/36239471-f91caa36-125d-11e8-8643-8123127dfb19.png">

If I was to now turn on the Roads layer, the NSW Satellite Imagery layer would obscure it.

**Comment by meh9** [comment]
New example:

Original:
<img width="350" alt="orig_order" src="https://user-images.githubusercontent.com/5283003/36952263-895196be-2061-11e8-814a-13b67e005053.png">

Reordered:
<img width="349" alt="reordered" src="https://user-images.githubusercontent.com/5283003/36952265-95d9057a-2061-11e8-9850-248bcb4a014e.png">

This is the serialised init data from the share URL:
[reordering_share_init.json.txt](https://github.com/TerriaJS/terriajs/files/1779100/reordering_share_init.json.txt)

This is the share URL:
https://nationalmap.gov.au/renewables/#share=s-fxgKgglB9jxabE3b

**Comment by meh9** [comment]
Note that the CSV layer `All generation types` may be put at the top because it doesn't make sense to reorder CSV points?

**Comment by kring** [comment]
Fixed by #3023.
