### ISSUE TITLE
Text not sharp

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#2841]
User feedback: 

Text is not sharp. It appears rasterised rather than vector - almost as if ArcGIS has been used to create it. Arc produces second rate text as a general rule.

Share URL: http://nationalmap.gov.au/northernaustralia/#share=s-izyyWSrdCWY8UEUB192HvPKTQdw

**Comment by kring** [comment]
Well, the Australian Topography base map was most likely created using ArcGIS. But more likely the user is seeing the usual Cesium bluriness. Either way, this is not something we can fix in TerriaJS. The Cesium issue tracking the problem is here: AnalyticalGraphicsInc/cesium#3279.
