### ISSUE TITLE
No way to differentiate 2 region types when selected at the same time

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#2842]
could you please enable colour coding of different datasets?

Share URL: http://nationalmap.gov.au/#share=s-r2Go6OsRX7P1JS4jKYHj9xw2bEa

When user selects SA 3 regions and LGAs (from ABS) at the same time, there's no way to differentiate them on the map:
![image](https://user-images.githubusercontent.com/18452161/36655809-0d8f50d6-1b19-11e8-88f8-970137869ddd.png)

**Comment by kring** [comment]
These layers come from an ArcGIS MapServer. There's no way TerriaJS can ask for different styling, the styling has to be changed by the ABS on their server.
