### ISSUE TITLE
Download data for multiple point/area selection

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#2854]
User feedback:

Good day Sir/Madam,

What a great product!!!

I was trying to download data from multiple datapoint. Does the National Map supports multiple point/group selection data download?

Share URL: http://nationalmap.gov.au/#share=s-ueP4bSIamsPvfBm5mMXBL4Ku0Xk

**Comment by AnaBelgun** [comment]
I think we might have covered this; currently not possible

**Comment by kring** [comment]
Duplicate of #1306 and/or #1158.
