### ISSUE TITLE
Saved views, "Back to previous view", "Forward to next view"

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#2856]
User feedback:

One thing I use NationalMap for a lot is trying to identify topographic features (mostly mountains) in photos I have taken. This requires zooming in and tilting to simulate the view in the photo (worm's eye view), then zooming out and returning to a bird's eye view to read the names of features from a topographic map layer. It would be really useful to have 'back to previous view' and 'forward to next view' buttons to allow quick and easy shifting between perspectives.

Share URL: https://nationalmap.gov.au/#share=s-zMD4AF8ymd0yjvSes4LaZP484y2

**Comment by rowanwins** [comment]
Consensus to move this to a plugin in #3863
