### ISSUE TITLE
Make clear what "search" is for

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#2857]
User feedback:

Hi I am unable to locate the address bar to locate the broadband exchange. Please help.

**Comment by AnaBelgun** [comment]
reading instructions for Search and Add data, there's no mention what search actually does (search for location/address). Maybe I'm missing something @philipgrimmett 
Maybe just adding a simple instruction on the existing list of instructions, will clarify. Easy fix.

**Comment by tephenavies** [comment]
Fixed in #2883 and #2902.
