### ISSUE TITLE
Customize value ranges and colors for CSV data

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#2860]
User feedback:

It would be a great feature if either

Map Key's could be adjusted (position and colour)
or
We could group values directly on the National Map
I encountered issues when the range of values was too great and the results were not displayed in a comprehensive manner. To counter this I created custom grouping (i.e. Average Salary - $0-$20,000, $20,001-$30,000 etc). This took some work and adjustment to the CSV files prior to upload, and afterwards the key was not in the correct order for some of the variables. For example the key would display as:

Red 0-20
Blue 21-40
-Green 80-100 *the out of place value
Purple 40-60
Orange 60-80
This would positively adjust readability.

Share URL: Not shared

**Comment by AnaBelgun** [comment]
Interesting idea but not sure if possible
Underlying issue might be poor display/breakdown and colouring of ranges

**Comment by nf-s** [comment]
We have the new "Edit style" feature 

![image](https://user-images.githubusercontent.com/6187649/179465526-44a68a5c-46c7-47c4-b02c-95b40d649376.png)
