### ISSUE TITLE
Pin a location

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#2862]
from user feedback

I am trying to pinpoint the location of the base station to be at Anglers Reach NSW. 
Share URL: http://nationalmap.gov.au/#share=s-kxMZg3U18tIx4NGmYDMnoixX41M

**Comment by AnaBelgun** [comment]
Not sure if I identified correctly what user wants

**Comment by kring** [comment]
Probably the only actionable idea here was already implemented in #2722.
