### ISSUE TITLE
Overall UI feedback: zoom, print/export, wokbench slider

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#2864]
User feedback: 

A great start - when all data listed is available for its full extent this will be a very useful web map.

1) User-added data isn't able to be selected and zoomed from the layer list (ibid Google Earth), e.g. KML attributes, like a feature ID, could be used for selection, but have to be manually panned / zoomed to find/step through them and click map pin to see the attributes.

2) Also: imagery dates are deceiving - e.g. the latest of all imagery covering Bendigo VIC, is at least 6 years old, yet all dates on the bottom info strip indicate 2016 for contributors like Earthstar, MS, GeoEye, DigitalGlobe etc.

3) Also: not all data available via "Add Data" actually appears, e.g. MINERALS_SHALLD100_POLYGON - this only loads for Dunolly area, yet exists for the entire state.

4) A clip and save image (with georef info) would be a great addition, otherwise its only a viewer.

**Comment by AnaBelgun** [comment]
4) https://github.com/TerriaJS/terriajs/issues/2820

**Comment by AnaBelgun** [comment]
User feedback: 

I like the changes in the panel to add data. Looks cleaner and simple, but most importantly, easy to use. Data has been organized in a way that you can access every detail. 

1) I might probably leave more space between the National map logo and the search field. As soon as data sets are being added, space can shrink in order to leave more space when adding more
I am assuming, you have already think about this, but the panel gets lost when changing to full-screen view, might be nice to use one those slide panels that hide when not in use. Similar to the sliding panels for mobile devices.

2) In data sets like the country of birth where there's a number of options, might be easier to use dropdown menus with multiple selection lists or a range slider in the case pf the Age data set.

3) Lastly, the total selected percentage legend is not very clear with the relations between percentages and colors.
Hope this is helpful. It looks wonderful.

**Comment by kring** [comment]
> User-added data isn't able to be selected and zoomed from the layer list (ibid Google Earth), e.g. KML attributes, like a feature ID, could be used for selection, but have to be manually panned / zoomed to find/step through them and click map pin to see the attributes.

Covered by #1342 

> Also: imagery dates are deceiving - e.g. the latest of all imagery covering Bendigo VIC, is at least 6 years old, yet all dates on the bottom info strip indicate 2016 for contributors like Earthstar, MS, GeoEye, DigitalGlobe etc.

Created #2875

> Also: not all data available via "Add Data" actually appears, e.g. MINERALS_SHALLD100_POLYGON - this only loads for Dunolly area, yet exists for the entire state.

Not sure what to make of this one.

> A clip and save image (with georef info) would be a great addition, otherwise its only a viewer.

Covered by #2820, as Ana mentioned.

> I like the changes in the panel to add data. Looks cleaner and simple, but most importantly, easy to use. Data has been organized in a way that you can access every detail.

I put these three UX suggestions in a separate issue, #2876.
