### ISSUE TITLE
Add recommended searches / featured data

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#2865]
User feedback: 

National Map, Thank you for this initiative. it is very useful and I love it. Wouldn't be nice if you provide a list let's say 10 most important(may be most searched locations) for each region? for example let's say I am looking for recreational areas in Gold Coast. I will get a nice map with recreational areas highlighted in green plus a list on the left side of a few most visited recreational place in that specific region.

In my view the National Map website can become the most visited website in Australia if you can just add a few machine learning algorithms such as recommendation systems. Learning what most people like to search on the website can give you a clear picture of what needed to be improved.

Thank you once again.

**Comment by kring** [comment]
We can create a group for featured datasets in the catalog, no TerriaJS feature required. I don't think the rest of this is really actionable.
