### ISSUE TITLE
Data aggregation + draw/select random area 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#2868]
User feedback:

I love it!

I love the interface. It is very intuitive, and easy to navigate.

I wonder if it makes sense to be able aggregate statistics (power generation for example) across regions. The geomap makes me want to draw a circle around Sydney and see what is going on there. Perhaps you could have live stats on consumption/ supply from regions. I don’t know if this is actually a sensible use case, but just thinking about how to leverage the geospatial aspect of the work.

It seems to have pretty good speed too. However, when I loaded some other views, it slowed down a bit. I think that is something to work on.

**Comment by AnaBelgun** [comment]
probably 2 issues here and pretty sure they exist in terriaJS but can't find them now

**Comment by kring** [comment]
The aggregation is covered by #1158. Can't see much else actionable here.
