### ISSUE TITLE
Text font choice & consistency

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#2870]
Some old user feedback and comments on this: 

Use of courier(?) font in legend and Featured Information is a bit 'old style' along with using multiple fonts in the one section. Can a more modern font be used and be consistent in use on the screen

Suggestions for ATO user: 

Everson Mono
Inconsolata
PragmataPro
Terminus

**Comment by kring** [comment]
I don't think we're using a monospaced font for the feature info at all anymore.
