### ISSUE TITLE
Workbench time controls disappear when time is invalid

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#2874]
1. Load `#test` and enable Pacific Earthquakes and Chlorophyll-a concentration (both in `Test Data -> Temporal`).
2. Click `Zoom to Extent` on Pacific Earthquakes
3. Click a time early on the timeline, say before 1995 or so.
4. The `Time` controls on the Workbench under Chlorophyll-a concentration disppear.

The Chlorophyll-a layer is not available in the 1990's, so something should happen.  But it's not intuitive that the time controls would disappear entirely.  I'd suggest either displaying "No data available for this time" or using the closest time that _is_ available.

**Comment by a-stacey** [comment]
This was fixed and merged in: https://github.com/TerriaJS/terriajs/pull/2900
