### ISSUE TITLE
Support Shapefile in browser natively

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#2907]
It should be possible, using Mike Bostock's [Shapefile](https://github.com/mbostock/shapefile) library and an unzip library like [unzip](https://www.npmjs.com/package/unzip), to open a zip file containing a Shapefile directly in the browser - without using Terria-Server. That would make it much faster, remove the need for the server, and remove the crippling 1MB limit.

**Comment by stevage** [comment]
Calvin Metcalf's [Shapefile library](https://github.com/calvinmetcalf/shapefile-js) supports projections and zip files.

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/5080
