### ISSUE TITLE
Add a way to remove user data from catalogue list

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#2908]
Based on a user comment.

When adding local data to the catalogue and further display it on the map, users can remove it from the workbench but not from the catalogue. If users make changes to the data and try to add it back to the map, it creates a messy view. 

<img width="649" alt="image" src="https://user-images.githubusercontent.com/18452161/37436503-4ff69b98-283c-11e8-91b6-e02581f4380e.png">

**Comment by philipgrimmett** [comment]
Possible solution: add an 'option' button to My Data list item (on hover for desktop, persistent for mobile)

Concept sketch:
![terria-removemydata](https://user-images.githubusercontent.com/5292858/38787563-16a6c526-4172-11e8-90c7-6818c08f3e9f.gif)
