### ISSUE TITLE
Default timeline to off

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#2918]
At the moment when you enable a timeseries layer, such as the new Landsat imagery, it defaults to having the timeline at the bottom of the screen on, and the Use Timeline button is toggled on. If you now add a second timeseries layer it also defaults to on, and from that point the times of both layers is controlled by either time controllers or the timeline at the bottom, i.e. all the times are controlled in lock-step.

This is very confusing for the user because if they now turn on the splitter and attempt to compare different dates by selecting e.g. winter on the left and summer on the right, they are unable to control the layers individually without discovering that they have to disable the timeline on one or both layers. It is not intuitive how to turn that off.

However, if we had the opposite behaviour that the timeline defaults to off, then they can do the first usecase of controlling the layers in lock-step manually, and if they want to compare different times they can without figuring out how to first disable the timeline.

**Comment by kring** [comment]
You should be able to control this for individual catalog items by adding `"useOwnClock": true` to each entry in the init file.

**Comment by philipgrimmett** [comment]
@meh9 agreed, the current timeline behaviour is super confusing ([issue #3012](https://github.com/TerriaJS/terriajs/issues/3012) doesn't help, either). Are you happy to remove the 'Needs Discussion' label @kring?

**Comment by kring** [comment]
I definitely agree this is super confusing, but I'm not sure changing the default is the best way to address it. What about automatically disabling the timeline on one or both layers when the user hits the split button? The problem with changing the default is that it changes the behavior of existing applications in potentially surprising ways.

**Comment by meh9** [comment]
> What about automatically disabling the timeline on one or both layers when the user hits the split button?

It sounds reasonable to me that we disable the the timeline connection for the new "copy" of the layer the user created by clicking split.
