### ISSUE TITLE
Trying to create a list of checkboxes

### ISSUE THREAD

**Issue by Jason-DNetto** [TerriaJS/terriajs#2932]
Currently, every checkbox has a title
![checkboxes_with_titles](https://user-images.githubusercontent.com/24259173/38347529-6386cd3c-38df-11e8-8847-3a5d96f006b4.JPG)

Would like it to look like this
![checkboxes_without_titles](https://user-images.githubusercontent.com/24259173/38347536-673095ee-38df-11e8-937a-f033aced0170.JPG)

had some code for terriajs 5.5.0 that worked, it doesn't work now.

**Comment by rowanwins** [comment]
Now doable via #3135
