### ISSUE TITLE
Add support for WCS "clip and ship"

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#2937]
GSKY and the OpenDataCube are in the process of adding WCS support. As part of that TerriaJS will also need to support using WCS for "clip and ship", i.e. select an area and issue a WCS request to download it with the browser.

The workflow might look like:

1. User enables a WMS layer and TerriaJS detects or has set in the CatalogItem that WCS is supported.

2. Display some tool like `Extract data`, `Clip and ship`, or other suitable wording:

<img width="426" alt="screen shot 2018-04-13 at 17 30 28" src="https://user-images.githubusercontent.com/5283003/38722174-64e8a602-3f40-11e8-98ee-13efadfaf095.png">

3. WCS seems to only support rectangular bounding boxes so we can probably initially use the rectangular zoom tool in EPSG:3857 projection to select an area (if multiple formats are supported may need a drop down to select e.g. GeoTIFF or NetCDF):

<img width="418" alt="screen shot 2018-04-13 at 17 33 52" src="https://user-images.githubusercontent.com/5283003/38722320-ee38ac18-3f40-11e8-94ff-f5e34f64ede6.png">

4. When the user has selected an area start a download of the synthesised WCS URL:

<img width="722" alt="foo" src="https://user-images.githubusercontent.com/5283003/38722978-11e5be4c-3f43-11e8-9093-ac87ad36a865.png">

**Comment by meh9** [comment]
@philipgrimmett lets discuss!

**Comment by philipgrimmett** [comment]
@meh9 we'll probably need to discuss ways to flag this functionality for users when they turn on a compatible dataset for the first time (+reminders), but this should be fine for v1: 

video: https://drive.google.com/open?id=11MVXRdmAwVqPb2awbwJ9MFw753EO_gBu
invision: https://invis.io/5PHJI26764R#/293104394_1

Note that the extraction rectangle is automatically drawn onto the map when the 'extract data' button is clicked, and can be quickly moved by single clicking on a new location while in selection mode.

**Comment by meh9** [comment]
@philipgrimmett that's awesome!

**Comment by tephenavies** [comment]
See progress on prototype site here: http://wcs-clip-and-ship.terria.io/
Use the export button to get to WCS functionality:
![image](https://user-images.githubusercontent.com/13863530/43295362-cc8e0132-9187-11e8-8366-3dea4783952e.png)

To build a TerriaMap instance against a WCS-enabled TerriaJS use branch `wcs-clip-and-ship` and add WCS details to WMS catalog items as in [test-wcs.json](http://wcs-clip-and-ship.terria.io/init/test-wcs.json)

**Comment by edisonguo** [comment]
@steve9164 I tested the prototype and the functionality is working fine. But I think there might be an UI issue. Essentially I can't release the rectangle after drawing it and downloading the data. To reproduce this issue:
1) click on `export` 
2) hold SHIFT and click left mouse button for top-left point
3) move mouse to another location and click for bottom-right point
4) data file automatically gets downloaded. 

But now the rectangle drawing continues whenever I move mouse. Please see the attached screenshot.
![wcs_clip_n_ship_issue](https://user-images.githubusercontent.com/4906167/43556599-e9127d2c-9643-11e8-95d9-9e2a9d6e776f.png)

**Comment by tephenavies** [comment]
Thanks for the feedback. I can replicate that issue in the 2D view. The problem is not there in 3D view (which happened to be the view I was using mostly while testing it).

Issues to fix:
- [x] Options in workbench spill over to 2 lines
- [x] Rectangle is sticky in 2D
- [ ] Doesn't work in mobile or on a tablet (no SHIFT key). Should decide either to hide export or to make it work

**Comment by tephenavies** [comment]
Sticky rectangle fixed on http://wcs-clip-and-ship.terria.io

**Comment by AnaBelgun** [comment]
- [x] spacing of the text buttons in the worksapce

**Comment by AnaBelgun** [comment]
Some feedback received 10 Sep 2018 from DEA: 
Feedback for the layers/features are as follows:
•	LS8 NBART WCS – this feature appears to function within the “Terria Clip and Ship” prototype (http://wcs-clip-and-ship.terria.io/), this combination has the following workflow: 
1.	When a WMS layer is associated with a WCS service, an additional “Export” option is associated with the layer;
2.	Clicking the “Export” button, the user holds the shift button, then draws a rectangular bounding box;
3.	This generates a WCS request with the following parameters:
	service:WCS
	request:GetCoverage
	version:1.0.0
	format:GeoTIFF
	crs:EPSG:4326
	width:1024 determined by the drawn rectangle in pixels
	height:603 determined by the drawn rectangle in pixels
	coverage:LS8:NBART:TRUE
	bbox:125.78006744384767,-32.2310992451779,126.07395172119143,-32.05813639064348 translated from the drawn rectangle in Lat/Lon
	time:2016-11-20T00:00:00.000Z determined by the selected date in the Layer date picker
o	The parameters width and height determine the output grid of the resulting coverage, this means that the resulting coverage is not native resolution.
o	The resulting GeoTIFF only includes the bands associated with the active band (Red, Blue, Green for this example).
o	Our belief is that our stakeholders will expect to be able to acquire native resolution and all bands associated with a given product. ACTION: to validate this assumption

**Comment by AnaBelgun** [comment]
@meh9 reminder to send @steve9164 the layers for configuration so we can merge/close this one; will open a new ticket just with native res and other feedback we get from users/testers

**Comment by AnaBelgun** [comment]
@steve9164 reminder to check  http://wcs-clip-and-ship.terria.io; it looks like not working atm

**Comment by meh9** [comment]
@AnaBelgun @steve9164: I have put WCS layers on terria-cube now, so suggest that http://wcs-clip-and-ship.terria.io is removed and this can now be closed.
