### ISSUE TITLE
goo.gl URL shortener end of life March 30 2019

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#2938]
Sometime around that time we should remove support from TerriaJS for using goo.gl for share URL's.

**Comment by kring** [comment]
https://9to5google.com/2018/03/30/google-url-shortener-shut-down/

**Comment by stevage** [comment]
Done. I considered leaving the resolution part in, but:

1) I'm skeptical there's any value there.
2) I couldn't test it without an API key
3) I suspect that API itself is gone
4) Any one with such a URL can still directly resolve it if they really need.
