### ISSUE TITLE
sharing CSV data is buggy

### ISSUE THREAD

**Issue by zdefne-usgs** [TerriaJS/terriajs#2943]
If a variable other than the default `dataVariable` is selected from the list the shared map does not work as desired. It displays the `defaultvariable` instead of the selected. 

Additionally, if the original map is created with an init file on the same server (instead of a drag-n-drop init file) the map hangs up while loading the variables list. 

Original map view that is shared:
![image](https://user-images.githubusercontent.com/4505315/39155223-1d3dfe6a-471f-11e8-8a86-ddc82f69e0b1.png)

How it looks:
![image](https://user-images.githubusercontent.com/4505315/39155161-df00dbe0-471e-11e8-8713-9e832c9e6f04.png)

**Comment by kring** [comment]
@zdefne-usgs I can't reproduce the first problem. I created an init file like this:

```
{
  "catalog": [
    {
      "name": "NEXIS NSW 2012 (LGA)",
      "type": "csv",
      "url": "test/NSW_LGA_NEXIS_201212.csv",
      "tableStyle": {
        "dataVariable": "TOTAL NUMBER OF DWELLINGS"
      }
    }
  ]
}
```

Then dragged it onto the map (Tried both nationalmap.gov.au and http://ci.terria.io/master/), changed to a different varilable and hit share. When I visit the share link the new data variable is selected.

I also tried http://nationalmap.gov.au/#test, enabled Test Data -> Region Mapping (CSV) -> NEXIS NSW 2012 (LGA), changed the data variable, and hit share. I didn't see any hanging, and the correct data variable came up.

Can you provide any more information that would help reproduce these problems?

**Comment by zdefne-usgs** [comment]
Okay I see that in my version the url is shortened. I wonder if it has got anything to do with it. The shared link with  http://ci.terria.io/master/ gives a " cannot resolve url" error in IE11 but works as expected with in Chrome. The url might be getting truncated. I tested my csv file with the National Map and it works as expected. Your json example works as expected on our map. So the first problem was maybe related to caching, I could not reproduce it either. Although your json example doesn't have a time dimension. 

But the second issue is still there. Link to my csv file is [here](https://github.com/zdefne-usgs/sweet_slr/blob/master/sweet_major.json). I tested with National Map and it works as expected. But our server has the `init` file on the same server and maybe that is the problem. When shared the view of the same dataset, the issue is reproducible. The server is [here](https://js-169-194.jetstream-cloud.org/terriamap/). Do you think you can do a similar test on your server? Thanks!
