### ISSUE TITLE
WMTS in 3D mode appears to be broken

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#2946]
When loading a WMTS layer in 3D mode, i.e. using Cesium, the requests get a bit weird and we start requesting the same URL's over and over forever.

1. Go to https://map.geo-rapp.org/
2. Select 3D mode
3. Observe that the globe never loads until you disable one of the two Area layers.

If you look at the network requests happening then you will see an this request over and over with the two parameters `tilerow` and `tilecol` being set to the values 0 and 1 over and over forever.

https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/wmts.cgi?service=WMTS&version=1.0.0&request=GetTile&tilematrix=1&layer=Reference_Labels&style=default&tilerow=1&tilecol=0&tilematrixset=GoogleMapsCompatible_Level9&format=image%2Fpng

**Comment by kring** [comment]
Duplicate of #2928?

**Comment by meh9** [comment]
Yes, dupe.
