### ISSUE TITLE
Upgrade cesiumjs to version1.43 or later

### ISSUE THREAD

**Issue by geoffrowland** [TerriaJS/terriajs#2950]
STK World Terrain is deprecated and will no longer be available after 1 September 2018.
It has been replaced by the higher resolution Cesium World Terrain hosted on the Cesium Ion platform.

Connection to the new Cesium World Terrain requires an upgrade of terriajs cesiumjs from 1.41 to 1.43 or later.

See: https://cesium.com/blog/2018/03/01/introducing-cesium-world-terrain/

**Comment by meh9** [comment]
Cesium was upgraded to 1.48.0 in https://github.com/TerriaJS/terriajs/commit/02cab0af83ed169e835f0c9b4170a60e776c666b!
