### ISSUE TITLE
Changing the colour of the splitter icon via CSS

### ISSUE THREAD

**Issue by michaeladams** [TerriaJS/terriajs#2957]
Customising the look and feel of TerriaJS, I would like to be able to change the colour of the slider icon.

This isn't possible via a 'fill' css rule because of the hard-coded fill attribute in the icon SVG.

Similar to other icons eg (https://raw.githubusercontent.com/TerriaJS/terriajs/master/wwwroot/images/icons/geolocation.svg) the fill attribute should not be present.

**Comment by kring** [comment]
This was fixed by #2958.
