### ISSUE TITLE
Investigate architectural improvements to the Model layer

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#2959]
Some problems in the current architecture:
* After loading, we can't tell what user actually set versus what came from e.g. GetCapabilities. This is slightly annoying currently, but will cause bigger problems as we move to in-app catalog editing.
* Observable spaghetti and side effects everywhere. It's sometimes hard to keep track of what's going on.
* All code for all catalog item types needs to be loaded before we can do anything.
* We're using Knockout in a React app, which is weird.
* No type safety.

To that end, I've been experimenting with some significant changes to the Model layer, such as switching from Knockout to MobX, changing the way we do many operations (like adding things to the map) so make them far less side effect ridden, using TypeScript, and separating model properties into separate layers (I call them strata, cause the term layer is already used in mapping).

This issue is simply to track this work.

**Comment by nf-s** [comment]
I'm still waiting @steve9164

**Comment by nf-s** [comment]
TIL:
> I call them strata, cause the term layer is already used in mapping
