### ISSUE TITLE
Create an export/download functionality

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#2969]
- Initiator of this issue is the NA Map
- Customer initially suggested we create a functionality which assists users in drafting a report targeted at presenting investment opportunities
- one of the issues users encountered: when using the print screen functionality, the images were not consistent and time was wasted trialling out different sizes and shapes to fit into report pages

Comments from user:
The Opportunity Analysis section is the part of the report that is generated from the map. We would like to be extract map pages into the report in a consistent style/format (as opposed to copying snapshots into a word document as I have document as I have done) with fields/spaces to include text. This would include consistent way to show legends without having to show all the stuff that is currently in the workbench. Where time series data is used we would also like to be a be able to drop in charts that can be generated."

User story example: 
**As an** employee of X department,
**I would like to** easily copy map images and other information included in the map views (feature info, legends, timeline) and data descriptions 
**So that I can** quickly create high quality reports and presentations.

**Comment by tephenavies** [comment]
@AnaBelgun Can this be closed?

**Comment by AnaBelgun** [comment]
The requirement hasn't been updated by  the client and no other users have requested it, hence will close and re-open in the future if necessary.
