### ISSUE TITLE
Add `parameters` property to ArcGisMapServerCatalogItem/Group

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#2973]
We recently came across a situation where the data custodian (service provider) wants to show only some data from the service due to privacy/licensing/other constraints.

**Comment by meh9** [comment]
You can pass a filter to MapServers to show only matching features:

http://services.ga.gov.au/site_3/rest/services/Geological_Provinces_2013/MapServer/export?bbox=103.30346102375006%2C-80.29712900874997%2C175.14665995125006%2C39.80942972075001&bboxSR=&layers=show%3A20&layerDefs=20%3ANAME+LIKE+%27Bonaparte+Basin%27+OR+NAME+LIKE+%27Browse+Basin%27+OR+NAME+LIKE+%27Northern+Carnarvon+Basin%27+OR+NAME+LIKE+%27Southern+Carnarvon+Basin%27+OR+NAME+LIKE+%27Perth+Basin%27+OR+NAME+LIKE+%27Otway+Basin%27+OR+NAME+LIKE+%27Bass+Basin%27+OR+NAME+LIKE+%27Gippsland+Basin%27+OR+NAME+LIKE+%27Sydney+Basin%27+OR+NAME+LIKE+%27Clarence-Moreton+Basin%27+OR+NAME+LIKE+%27Surat+Basin%27+OR+NAME+LIKE+%27Bowen+Basin%27+OR+NAME+LIKE+%27Eromanga+Basin%27+OR+NAME+LIKE+%27Cooper+Basin%27+OR+NAME+LIKE+%27Amadeus+Basin%27+OR+NAME+LIKE+%27Canning+Basin%27&size=&imageSR=&format=png&transparent=false&dpi=&time=&layerTimeOptions=&dynamicLayers=&gdbVersion=&mapScale=&f=image

**Comment by meh9** [comment]
WFS supports similar things:

http://docs.geoserver.org/latest/en/user/filter/function.html

**Comment by meh9** [comment]
This is also related to these issues:

https://github.com/TerriaJS/terriajs/issues/1324
https://github.com/TerriaJS/terriajs/issues/1196

**Comment by kring** [comment]
`WebMapServiceCatalogGroup`, `WebFeatureServiceCatalogGroup`, and `ArcGisMapServerCatalogGroup` all have a `blacklist` property that can be used for this purpose.  Can we close this?
