### ISSUE TITLE
Add zoom icon to "zoom in to view this layer" tile placeholder

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#2980]
Adding a zoom in icon to the placeholder will help to reinforce the required action when a dataset is loaded outside of its required zoom range.

Design reference:
![1 copy.png](https://images.zenhubusercontent.com/5a5ee53e4b5806bc2bc30c26/72e12e93-ea02-4c85-ac12-3ea6b16753fc)
![1](https://user-images.githubusercontent.com/5292858/40341555-3bd37a38-5dc9-11e8-87e7-830615216410.png)

Icon asset:
https://drive.google.com/file/d/1DYf71fUbH-Dftx0Bfs8ekRkMd0lUczDd/view?usp=sharing

**Comment by kring** [comment]
The text is added by the server, so this isn't something we can do in TerriaJS. @meh9 would have a better idea what it would take to add it to GSKY.

**Comment by edisonguo** [comment]
GSKY now only shows the "zoom in to view" placeholders in area which has data. https://github.com/nci/gsky/issues/196
@philipgrimmett The icon asset is nice. Can we use your icon for GSKY?

**Comment by philipgrimmett** [comment]
[zoomIn-20.svg.zip](https://github.com/TerriaJS/terriajs/files/2790290/zoomIn-20.svg.zip)

**Comment by edisonguo** [comment]
Thanks @philipgrimmett

**Comment by rowanwins** [comment]
Nothing to action on our end
