### ISSUE TITLE
Attach 'hide workbench' button to workbench element

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#2983]
**Problem**
Currently the 'hide workbench' button has poor discoverability and is separated from the UI element it controls, making the relationship a little confusing.

**Proposed solution**
Remove the current 'Hide workbench' button and add a tab to the side of the workbench itself. Once the workbench has been hidden display a 'Show workbench' button is the top left corner of the screen (motion/easing is important here to draw the eye)

Video: https://drive.google.com/file/d/1NktvZT4D7AXbjaL_aIBcMyuSXwIW590o/view?usp=sharing
Invision: https://invis.io/KCJLA4W98DW#/299580428_1

Note: in the actual build the map should recenter based on the previous view

**Comment by kring** [comment]
Implemented in PR above.
