### ISSUE TITLE
Disable the "Run Analysis" button for WPS queries untill all fields validate correctly

### ISSUE THREAD

**Issue by a-stacey** [TerriaJS/terriajs#2985]
From @philipgrimmett 

For WPS Queries: 
    - Disable the 'Run Analysis button' until all required fields are valid, or throw a helpful error listing required fields that have invalid input.

Related:
    - Set default start time to day before current date, 12 am
    - Set default end time to current date, 12am

Splitting out this sub issue to stop this issue blocking up the higher level issue:
https://github.com/TerriaJS/aremi-natmap/issues/136

See also: https://github.com/TerriaJS/aremi-natmap/issues/136#issuecomment-390559383

**Comment by a-stacey** [comment]
NB: On the related note, its not quite clear to me what @philipgrimmett means by default start / end time, does this mean placeholder text or does this mean values and does it mean for this query or in general. As these are generated and not mandatory its not exactly clear that "defaulting" the values in this way makes sense (i.e. it not clear that there are constraints which would make it sensible to default for the general case and also it not clear that the default shouldn't be to supply not date when its not mandatory).

**Comment by kring** [comment]
Fixed by #2988.

**Comment by philipgrimmett** [comment]
@a-stacey my intention was to minimise the risk of a doomed analysis/fail state, in the absence of more strict form validation, by setting default start/end time values (eg. start:yesterday, end:today). Probably not important now that I know start/end times aren't required to run a successful analysis.
