### ISSUE TITLE
improve Count Tool to show hierarchical counts

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#2991]
It would be really useful if the count tool was hierarchical with the possibility of digging down the see counts for subtrees. Something like:

```
The catalog contains 674 items in 182 groups.
Electricity Infrastructure: 57 items / 15 groups
- Generation: 12 items / 5 groups
-- Current Power Generation: 6 items / 0 groups
-- [...]
- Transmission: 5 items / 3 groups
[...]
Renewable Energy: 415 items / 128 groups
[...]
```

**Comment by zoran995** [comment]
Closing as the issue is for v7, which is no longer supported. Added a comment to v8 feature ticket
