### ISSUE TITLE
inconsistent X-Forwarded-Proto header causes www.agric.wa.gov.au to enter redirect loop

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#2995]
The WA bioenergy host www.agric.wa.gov.au insists on HTTPS, and it will always redirect to try to force HTTPS to be used. However, it also checks to see that HTTPS was used for all connections upstream by checking the value of the `X-Forwarded-Proto` HTTP header, and if this is not set to `https` then it will redirect even if www.agric.wa.gov.au was itself actually accessed over HTTPS. This results in a redirect loop as this doesn't change any of the upstream connections.

The cause of this is that the Cloudfront to ELB connection step is using HTTP, and Cloudfront is what sets the `X-Forwarded-Proto` header.

There are two fixes that should be done:
1. Fix www.agric.wa.gov.au to reject the connection with a suitable error message pointing at the `X-Forwarded-Proto` instead of doing a redirect, since a redirect will never fix it. This will help people in the future to see what is wrong instead of doing the significant investigation we had to do.
2. Change to ensure that any system that sets the `X-Forwarded-Proto` HTTP header is using HTTPS for its connection and therefore setting the header to HTTPS.

**Comment by AnaBelgun** [comment]
@meh9 would you please expand on this

**Comment by meh9** [comment]
GA are prototyping a new stack where Cloudfront is using HTTPS.

**Comment by meh9** [comment]
This has been solved by us.
