### ISSUE TITLE
opacity works in geojson but not in kml

### ISSUE THREAD

**Issue by juan-guerschman** [TerriaJS/terriajs#2997]
drag and drop a geojson with fill opacity set to zero and displayed correctly. 
Same polygon as kml and Terria doesn't read the opacity correctly. 

geojson: 
`
{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"stroke":"#ffffff","stroke-width":3,"stroke-opacity":1,"fill":"#ffff80","fill-opacity":0},"geometry":{"type":"Polygon","coordinates":[[[130,-35],[150,-35],[150,-15],[130,-15],[130,-35]]]}}]}
`

kml: 
`<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document><Placemark><ExtendedData><Data name="stroke"><value>#ffffff</value></Data><Data name="stroke-width"><value>3</value></Data><Data name="stroke-opacity"><value>1</value></Data><Data name="fill"><value>#ffff80</value></Data><Data name="fill-opacity"><value>0</value></Data></ExtendedData><Polygon><outerBoundaryIs><LinearRing><coordinates>130,-35 150,-35 150,-15 130,-15 130,-35</coordinates></LinearRing></outerBoundaryIs></Polygon></Placemark></Document></kml>`

geojson: 
![image](https://user-images.githubusercontent.com/8801702/41445505-63e2cba6-708d-11e8-9ec2-4e31011586a5.png)

kml: 
![image](https://user-images.githubusercontent.com/8801702/41445512-71419444-708d-11e8-9187-21a65d996bd1.png)

**Comment by kring** [comment]
Cesium does not (and probably should not) interpret [ExtendedData](https://developers.google.com/kml/documentation/kmlreference#extendeddata) as styles. The correct way to style polygons is with a [PolyStyle](https://developers.google.com/kml/documentation/kmlreference#polystyle). Closing.
