### ISSUE TITLE
User wants to make Feature Info Panel movable

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3000]
AREMI ABBA project team would like to have the freedom of moving the feature info panel, so it doesn't obstruct the map view. 

Below is their case: 

**Feature Information window:**
I have a 17" monitor on my laptop so it is pretty wide. When I click on an object in the map and the feature information is returned, I am left with very little map space to visualise what I have selected and to make further selections. I would like to see the Feature Information window become either: a floating window that can be moved around the screen; or an adjustable size window; or incorporated into the Table of Contents (TOC) where the datasets menu is; or locked in at the bottom of the screen; or the font size reduced in which case the Feature Information window size could be reduced (the font is much larger than that used in the TOC). For incorporation into the TOC, perhaps a tab could be included where the layer tabs are [Zoom To Extent, About This Data, Split, Remove]. Shorten these names to make room [Zoom Extent, About Data, Split, Attributes, Remove].

AREMI interface (feature information window takes up most of the screen and window size is not adjustable or movable, map visibility is now poor). 
![pic 1](https://user-images.githubusercontent.com/18452161/41514454-7bc3395e-72ea-11e8-8089-227e3cb669e3.png)

**Comment by AnaBelgun** [comment]
@philipgrimmett @kring @meh9 @steve9164 we need to discuss :)

**Comment by kring** [comment]
Fixed in #3189.
