### ISSUE TITLE
Design and develop functionality to show satellite imagery and SOS water data at gauges (points) - v1

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3009]
The new functionality will allow users to visualise satellite imagery and water discharge levels (for example) at a selected point on a watercourse (gauge). 

Here are few examples of (general) user stories: 
As a cotton farmer, I want to see the watercourse levels, so that I can self-monitor how much water I pump (in addition to existing measurement tools) and not over-pump; so that I can increase the efficiency of my farm. 
As a community member, I want to see the evidence backing authorities' decisions on restricting water usage for farming purposes. 
As a compliance officer, I want to monitor the watercourse levels and check changes if/when reported, so that I can assist authorities and farmers in following regulations and better manage the area.

An example here or how the functionality could look like: https://docs.google.com/presentation/d/1GmuIaZLKy4LqxbiTsc35OnniQlxdY9WpG-NYluWlOq0/edit#slide=id.g3a000d6f8d_0_19 

More context here: https://docs.google.com/presentation/d/1I-xhCiHRd3-qsiwgS-hcJBI4rAS-862wvsFsp_WEHVc/edit#slide=id.g3d0e2d09d8_0_8

**Comment by AnaBelgun** [comment]
This is just the start of discussions on how best to represent satellite imagery and gauge data. It will be broken down into more specific issues.

**Comment by AnaBelgun** [comment]
We need to start designing this (roughly).

**Comment by AnaBelgun** [comment]
Starting point for prototype:  
- dismiss the timeline, separate it from the chart
- build a chart showing the selected datasets (gauge obs and satellite)

**Comment by philipgrimmett** [comment]
@AnaBelgun Invision prototype v3: 
https://invis.io/BFNERGSN584#/313250106_terria_-_Charts_Concept_V3

**Comment by AnaBelgun** [comment]
![connect satellite and obs feature_v1 design](https://user-images.githubusercontent.com/18452161/44064449-53a86882-9fa8-11e8-85a5-e6797f67565f.JPG)

Version for initiating development

**Comment by stevage** [comment]
My understanding of the user's workflow:

User adds this special layer of water level and imagery.
- Water gauge points are shown as dots.
- Imagery is shown at current time?
User clicks a point:
- Graph of water level over time for the given gauge is shown. 
- Overlaid (new functionality) are vertical lines representing moments in time when imagery is available.
  - Only imagery in that location? Or imagery anywhere for that imagery layer?
  - Is imagery really "moment in time" or it is a time range?
User can hover over moment in chart to read off water level at that time.
User can click on moment in chart to see imagery at that time
- Do they have to click an exact vertical line?
- If not, do we select the nearest imagery (forwards or backwards)
- Imagery is now updated with that time.

Do I have that right?

**Comment by stevage** [comment]
My branch for this is https://github.com/TerriaJS/terriajs/tree/3009-sos-imagery

**Comment by stevage** [comment]
Progress:

- [x] When time-dynamic ImageryLayerCatalogItem added, display availability in chart.
- [x] When clicking said chart, set Terria's clock to that time.
- [x] When clicking chart, snap to nearest availability.
- [ ] Highlight nearest availability when mouseover.
- [x] Make this behaviour configurable through `showOnChart` layer option.
- [ ] Only add to chart if chart already exists?
- [ ] Show useful hover-over info.
- [x] Don't expand chart X domain to suit this type of vis.

**Comment by stevage** [comment]
Summarising discussion:

The imagery availability chart (MomentChart) should be a kind of second-class chart layer.
- don't take its horizontal scale into account when choosing how big to make the chart.
- if there are no other layers, don't show a chart.
- put it behind all "first-class" imagery layers.

User has to manually select an imagery layer, don't automatically enable one.

Multiple imageries is desirable, but low priority.
- multiple sentinels
- different colors?

**Comment by AnaBelgun** [comment]
What: prototype terria demo instance 
When: 31 Oct 2018
To whom: to send url of the demo to GA DEA team led by David Gavin



Use the following combination for the demo:
•	After an SOS gauge is selected, execute a WMS getFeatureInfo against the daily WOfS development server [here](https://ows.services.devkube.dea.ga.gov.au/?time=2018-04-10&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&feature_count=101&service=WMS&version=1.1.1&request=GetFeatureInfo&layers=wofs_albers&bbox=12836528.782099359%2C-3287403.71248886%2C12993071.8160274%2C-3130860.6785608195&width=256&height=256&query_layers=wofs_albers&x=201&y=241&info_format=application%2Fjson):  to retrieve the “data_available_for_dates” list that can be overlayed in the stream gauge graph.
•	When a user clicks a date:
o	Set terria to split mode;
o	Add the GSKY LS7 NBART Daily True Colour service to the left hand pane. WMS endpoint http://130.56.242.16/ows/dea/daily Layer name: LS7:NBART:TRUE
o	Add the GSKY LS8 NBART Daily True Colour service to the left hand pane. WMS endpoint http://130.56.242.16/ows/dea/daily Layer name: LS8:NBART:TRUE
o	Add the GSKY Daily Water Observation Feature layer to the right hand pane. WMS endpoint https://gsky.nci.org.au/ows Layer name: wofs

**Comment by AnaBelgun** [comment]
2018-11-12_To note the following issues

1. visualisation of "concepts" - dataseries of a data set
Proposed workflow: 
- Add dataset
- Click on a feature
- Feature info > Expand chart
- Default "concept" is displayed in chart element (checked), alongside all other available (chartable) concepts for the parent dataset (unchecked) 

2. "nearest date" - before and after 
when a user clicks on a certain point of the chart, the "nearest" (not nearest-after) imagery should be shown. So, options for achieving that:
- The current code I implemented, where clicking on the chart sets the time to a place other than exactly where you clicked.
- An option so that this kind of layer behaves differently always (it's always nearest, instead of nearest-after)
- Some combination of the above so that clicking in a chart triggers different behaviour from clicking on the timeline or other ways the time might get set
- other ???
 this definition of `useOwnClock`:

```/**
     * Gets or sets a flag indicating whether imagery should be displayed using this item's own clock (currentTime, multiplier),
     * or, if false, the terria clock (whose current time is shown in the timeline UI). Default false.
     * This property is observable.
     * @type {Boolean}
     */
    this.useOwnClock = false;```

**Comment by AnaBelgun** [comment]
Next steps: 
- to merge v1 into TerriaJS master
- to include it in the NEII viewer or TerriaCube instance
- to circulate to users and record feedback as specific tickets
- in v2: to include feedback, + issue of before-and-after for multiple layers selected + issue of showing concepts in the chart space
- v2 requirements to be confirmed by DEA team

**Comment by AnaBelgun** [comment]
Current prototype: http://neii-viewer-2018-11-08-demo.neiiviewer.nicta.com.au/ 
Design has been revised: https://www.youtube.com/watch?v=uv5prWmyzxA&feature=youtu.be
@philipgrimmett to update the designs
@chloeleichen to change the UI
@kring to finalise v1 and prepare for review
@stevage to review

**Comment by AnaBelgun** [comment]
Designs updated: https://projects.invisionapp.com/share/DNQ9KNA6FC2#/screens/344062186
@kring and @chloeleichen please have a look and comment if we can finalise this in next sprint

**Comment by kring** [comment]
Closing because this is done (for now).
