### ISSUE TITLE
Display loading state for Terria UI & Cesium

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#3015]
**Problem**
Attempting to load a Terria map on mobile: currently there is a ~10 second delay before anything is displayed on screen, and in many cases this could be reasonably be perceived by visitors as a failed loading state, increasing our bounce(?) rate.

**Proposed solution**
- Display an animating 'Loading the Map' message and graphic (centred to map view)
- Block out placeholders for UI components for a smoother loading transition
- Fade in globe once basic geometry has loaded
- Fade in UI when loading is complete

Animation:
![terria-loading-mobile](https://user-images.githubusercontent.com/5292858/42261775-9b7a499e-7fac-11e8-8c6f-af7222383839.gif)

Desktop video:
https://drive.google.com/open?id=1PiFQoWY-BXg8MK2YRBynVK9yOBD7L70S

**Comment by AnaBelgun** [comment]
tickets for all apps to update to the terria map / include the loading gif
