### ISSUE TITLE
click on group open wrong group in catalogue

### ISSUE THREAD

**Issue by chloeleichen** [TerriaJS/terriajs#3020]
in Catalogue, if you click on "National Datasets" to close it, then you click on the title of another group, the National Datasets opens rather than the clicked group.

![image](https://media.giphy.com/media/2eKfKWs9jJ4v3fpAVs/giphy.gif)

**Comment by kring** [comment]
@chloeleichen I can't reproduce this one. Is it browser specific or something maybe?

**Comment by chloeleichen** [comment]
I can't reproduce this anymore either 💃
