### ISSUE TITLE
Model architecture: Flesh out WMSCatalogItem and WMSCatalogGroup

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#3026]
There's a start of this in the `mobx` branch, but these classes need to be finished. In particular, the the `mapItems` property needs to return actual `ImageryLayer` instances.

**Comment by AnaBelgun** [comment]
@steve9164 please add comments on current progress and next steps for this sprint

**Comment by tephenavies** [comment]
WMSCatalogItem now returns ImageryLayers and makes legends available for the workbench. Further work to do on WMSCatalogItem is:
- [x] Change the return type of `mapItems` to some object that gives enough information for either a Cesium or Leaflet to be able to create a native layer. This is probably a Cesium ImageryProvider together with an `alpha` and some other properties
- [ ] Add support for timeseries WMS (now tracked in issue #3331)

**Comment by AnaBelgun** [comment]
principles: https://github.com/TerriaJS/terriajs/blob/mobx/doc/contributing/model-layer.md

**Comment by tephenavies** [comment]
Replaced by more specific issues
