### ISSUE TITLE
Can't abandon drag-drop CSV

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#3036]
1. In OSX, drag a CSV file from Finder over nationalmap.gov.au, then drop it back in Finder.
2. You're stuck with the "Drag and drop a CSV" instructions.

Pressing Esc half clears the screen, then a bit of random clicking and waiting seems to eventually clear it up.

**Comment by kring** [comment]
On Windows I can't get this to happen in Chrome, but it happens consistently in IE11 and sometimes in Firefox (apparently depending on what the mouse cursor is over when it leaves the Terria window. Dragging from FF to Explorer=fine, FF to VS Code=broken).

**Comment by stevage** [comment]
Oh yeah - should have mentioned. Firefox on OSX Sierra here.

**Comment by chloeleichen** [comment]
related issue fixed
