### ISSUE TITLE
Crash in IE11/3D when drawing a rectangle

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#3078]
On Internet Explorer 11 in 3D mode, hold down SHIFT, left click on the globe, and move the mouse. Terria will crash and switch to 2D:
![image](https://user-images.githubusercontent.com/924374/45550238-a4c32a80-b86d-11e8-9e9b-87be5c0c26a7.png)

**Comment by kring** [comment]
This also prevents clip-and-ship from working because it uses the same mechanism.

**Comment by soyarsauce** [comment]
@kring are you still able to reproduce this on IE11? It seems to work well in both terriajs master & current version of nationalmap

**Comment by kring** [comment]
@soyarsauce I can't! It's working fine now. We add a polyfill suite somewhere along the line, maybe that fixed it. Or maybe something changed in Cesium. In any case, I'm closing this.
