### ISSUE TITLE
Drag and drop shapefiles turn into vector tiles in the browser

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#3082]

**Comment by meh9** [comment]
@philipgrimmett @stevage

**Comment by stevage** [comment]
Is this the same as #2907? Why "turn into vector tiles" exactly? Tell me more? :)

**Comment by meh9** [comment]
@stevage oh right, yes, very related. One of the problems we have is that e.g large GeoJSON files (and I theorise the same is true for detailed Shapefiles) will "hang" the browser because it takes too long to draw, "my" idea (already prototyped by @steve9164 I think) was to turn it into VT's for speed of display.

**Comment by stevage** [comment]
Ah. Yeah, that's what Mapbox-GL-JS does, with https://github.com/mapbox/geojson-vt

IMHO those two things should be separated though. Even without the vector tile thing, files of say 20MB are probably totally fine.

**Comment by tephenavies** [comment]
Above a couple of megabytes you need level of detail simplification to draw vector data in a browser without lag while panning in Cesium

**Comment by nf-s** [comment]
I have had a few people ask for this (namely DELWP for PPBCHA), and I have had a good experience with [shapefile](https://www.npmjs.com/package/shapefile) - https://observablehq.com/@mbostock/streaming-shapefiles

**Comment by nf-s** [comment]
🥳

**Comment by nf-s** [comment]
This is available now for new ProtomapsImageryProvider geojson items. To use this you will need to set `Terria.configParameters.enableGeojsonVt = true`
