### ISSUE TITLE
Keep name of existing polygon/region when processing a query via WPS

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3088]
Currently this is the behaviour on Geoglam http://map.geo-rapp.org/: 
1) Select total vegetation cover 
2) Select under Australia tab - Boundaries - Natural resource management regions 2017
3) Select Analysis tab - select Existing Polygon and Run Analysis
4) Click on any polygon 
5) Return to Run Analysis
6) Name of the polygon is displayed
7) Run analysis and wait
8) A map view with the highlighted polygon and a chart at the bottom will appear 
9) Name of the polygon in the legend and in the chart is some random number, not the actual name which appeared when analysis was run 

http://map.geo-rapp.org/#share=s-A3RNNto4fioCpM5xT0mtxZF4PkL

How name appears in Analysis workbench: 
![image](https://user-images.githubusercontent.com/18452161/45795991-afecdf00-bce1-11e8-90a9-bade42a300d7.png)

Name appears in the legend and chart as _0766_ not as South Australian Arid Lands
![image](https://user-images.githubusercontent.com/18452161/45796016-ce52da80-bce1-11e8-9d50-642912bf8a2a.png)

**Comment by kring** [comment]
@AnaBelgun based on what @edisonguo said above, I don't think there's anything to do on the TerriaJS side.

**Comment by AnaBelgun** [comment]
@edisonguo are you happy to do the implementation on the server (adding another text field to the polygon name)

**Comment by edisonguo** [comment]
@AnaBelgun We had internal discussions and we decided to implement this feature on the server side. If there is anything that can't be done on the server side, I'll create a ticket and let you know.

**Comment by AnaBelgun** [comment]
I'll close this for now and re-open if anything needs to be done at our end.
