### ISSUE TITLE
Include terria logo by default on TerriaMaps

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3094]
Currently the terriaMaps do not display Terria logo or attribution at all. 
some options:

1. To include terria logo next/before Cesium ION logo, at the bottom on the map (in line with attributions etc)

**Comment by philipgrimmett** [comment]
Monochrome options:
![terria - brand](https://user-images.githubusercontent.com/5292858/46126255-e42b4700-c26f-11e8-9a42-f6093626b411.png)
![terria-watermark-dark 2x](https://user-images.githubusercontent.com/5292858/46126440-a11da380-c270-11e8-83b6-40adeecda94c.png)
![terria-watermark-light 2x](https://user-images.githubusercontent.com/5292858/46126441-a11da380-c270-11e8-924b-eed994f43e4b.png)

**Comment by chloeleichen** [comment]
@philipgrimmett can you send me the svg plz

**Comment by philipgrimmett** [comment]
@chloeleichen I've included a dark and light version, but I think we should use terria-watermark-onLight.svg by default.

[terria-watermarks-SVG.zip](https://github.com/TerriaJS/terriajs/files/2436129/terria-watermarks-SVG.zip)

**Comment by chloeleichen** [comment]
@kring this was fixed in https://github.com/TerriaJS/terriajs/pull/3070, would you like me to pull that out and make a separate PR?
