### ISSUE TITLE
Workbench collapse button is on top of the catalog UI

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#3096]
![image](https://user-images.githubusercontent.com/924374/46329045-6d66c300-c64e-11e8-87e4-018730ab0947.png)

**Comment by chloeleichen** [comment]
@kring this was fixed in https://github.com/TerriaJS/terriajs/pull/3070, would you like me to pull that out and make a separate PR?

**Comment by kring** [comment]
> @kring this was fixed in #3070, would you like me to pull that out and make a separate PR?

No that's ok, just add `Fixes #3096` to the original text in that PR so this one will close when it is merged.
