### ISSUE TITLE
Automatically detect WCS using WMS DescribeLayer calls

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#3108]
Instead of always having to manually set WCS properties for WMS layers we should use the response from the `DescribeLayer` to automatically detect that there is a WCS for the layer.

E.g. using http://geoserver.nci.org.au/geoserver/NFRIP-WOfS/wms, a `DescribeLayer` looks like:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE WMS_DescribeLayerResponse
  SYSTEM 'http://geoserver.nci.org.au:80/geoserver/schemas/wms/1.1.1/WMS_DescribeLayerResponse.dtd'>
<WMS_DescribeLayerResponse version="1.1.1">
  <LayerDescription name="ClearObservations" owsType="WCS" owsURL="http://geoserver.nci.org.au:80/geoserver/NFRIP-WOfS/wcs?">
    <Query typeName="NFRIP-WOfS:ClearObservations"/>
  </LayerDescription>
</WMS_DescribeLayerResponse>
```

**Comment by nf-s** [comment]
I believe this isn't possible.

See https://github.com/TerriaJS/terriajs/pull/6108 for alternative solution
