### ISSUE TITLE
Vector legends not displaying in Safari

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#3111]
### Problem reproduction steps
Tested in Safari Version 12.0 (14606.1.36.1.9)
https://nationalmap.gov.au/#share=s-eO9J2gy8hwCquMyqizvq1OQmHKq

### Screenshot / Design / File reference
![screen shot 2018-10-09 at 5 42 30 pm](https://user-images.githubusercontent.com/5292858/46651223-1c754280-cbeb-11e8-93a6-ec6eb1248cd4.png)

**Comment by kring** [comment]
@chloeleichen can you take a look at this one?
