### ISSUE TITLE
TerriaJS modifies the legend URL to try to make it an image which ends up breaking it

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#3117]
A WMS layer has a legend in the GetCaps, however the URL doesn't end with an image extension, so it looks like we try to put one on?
```
<LegendURL width="20" height="20">
<Format>image/png</Format>
<OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple" xlink:href="http://oa-gis.it.csiro.au/geoserver/ows?service=WMS&request=GetLegendGraphic&format=image%2Fpng&width=20&height=20&layer=awavea%3Aww3.aus_4m.te_avg"/>
```

Chrome says:

> GET https://nationalmap.gov.au/renewables/proxy/http://oa-gis.csiro.au/images/layers/cb_ww3.aus_4m.te_avg.png 404

The layer is `awavea:ww3.aus_4m.te_avg` on this service:

http://oa-gis.csiro.au/geoserver/wms?service=WMS&version=1.3.0&request=GetCapabilities

**Comment by kring** [comment]
This does not appear to be an issue anymore. We now get a legend from the server and layer above. It's not a useful legend, but it's the legend the server provides.
