### ISSUE TITLE
Add support for THREDDS catalogs

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#3127]
We should add support so that we can use any THREDDS `catalog.html` (or maybe an actual API is exposed that could be used?) and load the hierarchy and any exposed WMS/WCS services, e.g.:

http://neii.bom.gov.au/services/solarclim/catalog.html

http://portal.sf.utas.edu.au/thredds/catalog.html

**Comment by nf-s** [comment]
done - https://github.com/TerriaJS/terriajs/pull/4724
