### ISSUE TITLE
Terria logo in attribution overlay is too clickable

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#3141]
<img width="822" alt="screenshot 2018-11-05 16 38 34" src="https://user-images.githubusercontent.com/678344/47979885-5f0e3a00-e119-11e8-9abe-62b52d48bfd4.png">

There is an invisible clickable zone extending from the terria logo all the way to the right, ending above the "CC-BY 3.0". It's very annoying, because if you're trying to click on a feature near the bottom of the map, you suddenly lose your entire browser tab, replaced with the Terria home page.

**Comment by AnaBelgun** [comment]
@chloeleichen would you mind having a look at this please?
