### ISSUE TITLE
My Data bin icons misaligned with Group+Item

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#3143]
![image](https://user-images.githubusercontent.com/924374/48046047-e9709f80-e1e6-11e8-884f-be3af6c9e9b1.png)

The positions of the bin and the expand/collapse button should probably be swapped, unless @philipgrimmett disagrees.

**Comment by philipgrimmett** [comment]
I can’t think of any usability issues, so it’s probably fine to swap them.
