### ISSUE TITLE
Merge new functionality development connecting timeseries data to satellite imagery

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3149]
Prepare and merge into TerriaJS master the new functionality developed (initially) for the NEII, connecting the SOS gauge data (water regulations) with Satellite Imagery (WOFLS from DEA).

**Comment by stevage** [comment]
Here's the PR btw https://github.com/TerriaJS/terriajs/pull/3151

And the base issue: #3009
