### ISSUE TITLE
Develop v2 of functionality to connect dataseries data with satellite imagery

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3150]
To develop v2 of the functionality of connecting timeseries data with satellite imagery, initially developed for the NEII (connecting the water regulations SOS point data to the DEA's WOFLS). 

Following v1 release in NEII/TerriaCube, v2 will include:
- user feedback
- issue of before-and-after for multiple layers selected
- issue of showing concepts in the chart space
- other requirements to be confirmed by DEA team

**Comment by AnaBelgun** [comment]
related to #3009

**Comment by stevage** [comment]
Summary of possible areas of improvement, from discussion with DEA today:

* Find why there are not many sensors with many years of daily data. (Possibly liaise with BoM).
* Support zooming in on the chart so long data series can be better explored.
* Highlight the currently selected time slice (not just mouseover)
* Highlight the selected location
* Show daily discharge, not just average waterlevel.
* Figure out why some points don't have data. Can we generate a (semi-static) dataset of gauges that have functional data associated with them?
 * Maybe use different colors to highlight those that are HRS (hydrological reference stations)

In the list of things that would be great but are probably out of our control or scope:

* A single imagery layer that merges Landsat 5,7, 8, and Sentinel
* Having imagery and "hydrograph" (chart) more closely tied, so the imagery slices would be linked to a line chart, share a colour etc. But mostly that's to support multiple selected sensors, which is a low priority use case.

**Comment by rowanwins** [comment]
Most of these items are now done. Closing in favour of more specific tickets
