### ISSUE TITLE
Update My Data workbench button title text

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#3153]
The 'My Data' button title text should read "Load local/web data" (it currently reads "Upload data", which implies that potentially sensitive data will be uploaded to a server). The title text also contradicts our catalogue help text: 

> Drag and drop a file here to view it locally on the map (it won’t be saved or uploaded to the internet) 

Small point, but important for building trust.

**Comment by AnaBelgun** [comment]
good point @philipgrimmett thanks
