### ISSUE TITLE
Error adding WMS server - login details and SRS issue

### ISSUE THREAD

**Issue by ldodds** [TerriaJS/terriajs#3159]
I'm trying to configure a WMS server. The url is:

https://feeds.getmapping.com/33188.wmsx?service=wms&version=1.3.0&request=getcapabilities&login=c1387c7d-7660-47c4-95da-457bc2631cf4&password=sk64k5k0

Adding as `wms-getCapabilities` allows me to see the layer. But it won't add. I think there are two separate problems:

Firstly, the endpoint includes a username/password. This is passed into the first call, but not subsequent requests. Is there a way to add them? I tried adding `customProperties` but didn't seem to work

Testing a URL in the error message I see in the browser, ([for example](https://feeds.getmapping.com/33188.wmsx?srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&feature_count=101&service=WMS&version=1.1.1&request=GetMap&layers=AIR_QUALITY_MONITORI&bbox=-265389.3622061312%2C6690380.211744906%2C-264777.8659798503%2C6690991.707971189&width=256&height=256) and adding login and password url parameters means I get a response.

However this tells me that there is an invalid SRS. If I change EPSG:3857 in the url to EPSG:27700 as advertised in the `getCapabilities` call, I can get an image.

So:

* is there a way to get terriajs to pass through additional parameters to authenticate
* any idea how to change/force/configure the SRS?

**Comment by kring** [comment]
@ldodds You can pass arbitrary parameters in `GetMap` requests by using the `parameters` property. Something like:

```
{
  "name": "WMS with username/password",
  "type": "wms-getCapabilities",
  "url": "https://feeds.getmapping.com/33188.wmsx?service=wms&version=1.3.0&request=getcapabilities&login=c1387c7d-7660-47c4-95da-457bc2631cf4&password=sk64k5k0",
  "itemProperties": {
    "parameters": {
      "login": "c1387c7d-7660-47c4-95da-457bc2631cf4",
      "password": "sk64k5k0"
    }
  }
}

As for the SRS, TerriaJS requires EPSG:3857 or a similar projection (like 900913). If you don't need 2D support, the 3D view can use EPSG:4326, too. Most WMS servers are able to reproject to one or both of these, so it it's not usually a problem. It's strange that this WMS server is returning an error for a projection that is so pervasive on the web.

**Comment by ldodds** [comment]
@kring thanks for responding. The `itemProperties` configuration has resolved the first problem, the login details are being passed through.

The WMS server seems to be MapServer, but I can't see any obvious additional parameters to ask it to reproject - I assume the `srs` parameter should do that. I will try contacting the server admin.

As an aside, where you say "the 3D view can use EPSG:4326", how is this configured? I tried switching between 2D/3D background layers and didn't see any change in requested projection. Is there a configuration option?

**Comment by kring** [comment]
The 3D view when fully rendered is "unprojected". Or, you might say it's using a perpsective projection. Unlike 2D maps, there's no map projection employed to render the view, it's a perspective view of the 3D world.

The source data usually comes in a projection, though, so the 3D view has to unproject it, and it only knows how to do that for 4326 and 3857.

In the WMS case, if the server were advertising 4326 as supported in the GetCapabilities, TerriaJS would use it automatically, no configuration required. But because the server isn't advertising any compatible projections, TerriaJS requests 3857 and hopes for the best. You should be able to override this by adding a line to your `itemProperties`:

```
  "tilingScheme": "geographic"
```

This will force it to request 4326 instead of 3857.

**Comment by ldodds** [comment]
Great, thanks for the info!
