### ISSUE TITLE
Update My Data UI (panel beating)

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#3177]
Comments for tightening up the My Data UI available here: https://invis.io/WENV0U1FN3C#/299021353_my_Data_-_Empty

@chloeleichen you might need to be logged into lei.chen.1@data61.csiro.au to view comments

**Comment by kring** [comment]
Fixed by #3182. @philipgrimmett re-open or open a new issue if there's something more from the invision that should happen.
