### ISSUE TITLE
GeoJSON sources added twice when drag-dropped

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#3193]
Drag and drop a GeoJSON file from your desktop to nationalmap.gov.au

It appears twice in the workbench. The second entry lacks a "zoom to extent" button, and doesn't appear to do anything.

**Comment by chloeleichen** [comment]
@stevage which file are you having the issue with? I am trying `bike_racks.geojson` and `cemeteries.geojson` and could not replicate the issue.

**Comment by rowanwins** [comment]
Also could not replicate. Closing for the timebeing.

**Comment by rowanwins** [comment]
Turns out this happens when things have the `.json` extension rather than `.geojson`
