### ISSUE TITLE
Reconcile regionMapping.json in NationalMap and TerriaMap

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#3198]
Once #3178 is merged, NationalMap will start using the version of regionMapping.json copied from TerriaMap. But there are some differences between that file in TerriaMap and NationalMap that look important. So, we need to compare these two files:

https://github.com/TerriaJS/terriajs/blob/1227-regionmapping-json/wwwroot/data/regionMapping.json
https://github.com/TerriaJS/nationalmap/blob/master/wwwroot/data/regionMapping.json

And update the `1227-regionmapping-json` branch's version to include anything important from the NationalMap version. It will take some detective work to figure out the reason for the changes in the NationalMap version, no doubt.

**Comment by stevage** [comment]
The differences were basically three missing region mapping types, and some minor alias updates.
