### ISSUE TITLE
Flickering screen on Macbook using Chrome

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3204]
The screen flickers for Macbook using Chrome, at certain screen sizes.

**Comment by PeterTonoli** [comment]
Bump.

This issue seems to be exacerbated by the timeline being visible.

**Comment by kring** [comment]
@PeterTonoli this was a bug in Chrome, but we implemented a workaround in TerriaJS v7.6.11. The PR with some more details is here: https://github.com/TerriaJS/terriajs/pull/3686
If you've already upgraded and are still seeing the issue, please re-open this issue and provide some more details so we can investigate.

**Comment by PeterTonoli** [comment]
@kring Brilliant - we've merged the changes from #3686 into our development train, and it now works perfectly - thanks for the quick response.
