### ISSUE TITLE
Make possible sharing url associated with a catalogue group/category

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3208]
Some users pointed out that they'd like to share the url pointing to the catalogue group they have opened. 
For example, on AREMI, under renewable energy, bioenergy, data is organised by State. The States' reps would like to promote their data by pointing people to the exact catalogue group, instead of one or few layers (which currently can be done by using the Share feature). 
If they can share catalogue group, then custodians will be incentivised to populate their landing pages, making the app richer and more user friendly.

**Comment by philipgrimmett** [comment]
@soyarsauce 

![catalogue-share-v2](https://user-images.githubusercontent.com/5292858/56109913-e21fa000-5f95-11e9-9eb6-5401c2ccb3d4.png)

Invision Studio isn't playing nice, so I'm having trouble exporting an inspectable reference screen (sorry!). Switching back to Sketch now. Happy to tweak CSS after your first pass at the attached screenshot.

**Comment by soyarsauce** [comment]
@philipgrimmett the escape behaviour on that ci link has been updated now too 🙂

**Comment by philipgrimmett** [comment]
@soyarsauce latest Invision prototype here: 
https://invis.io/SFRCADN6KA9#/355876858_group_-_No_Body_Content_-_Share_Link

Let me know if you have any trouble with Invision inspect, icon export etc.

Change log:
- Style tweak to better match modal

**Comment by soyarsauce** [comment]
Hi @philipgrimmett - I can't export the X icon, it isn't part of the list of assets. Everything else should be ready, although we're in this weird transitional state of the catalog editor invision-prototype being out of sync with the current catalog. We should create an issue for updating all that once it's ready?

So, again please check http://ci.terria.io/3208-share-from-catalog/ for
- hover states are what you expect (I improvised)
- terria-blue matches what you expect (that is the one global-to-terria-thing I updated that wasn't part of the modal-specific-updates)
&
- send X icon so I can swap it in

**Comment by philipgrimmett** [comment]
@soyarsauce 

[Terria icons - April 19.zip](https://github.com/TerriaJS/terriajs/files/3125678/Terria.icons.-.April.19.zip)

**Comment by AnaBelgun** [comment]
I think @chloeleichen said she's happy to review; please let her know when you're done @soyarsauce thanks

**Comment by soyarsauce** [comment]
Yes I just need to fix a bug that Phil found and update w/ latest icon
