### ISSUE TITLE
Can't use style: percent for nested properties in featureInfoTemplate

### ISSUE THREAD

**Issue by andrewdhicks** [TerriaJS/terriajs#3218]
I'm trying to format a number as a percentage from a `WMSGetFeatureInfo` call.  When specifying a nested property in `featureInfoTemplate`, I can't use the `"style": "percent"` option.
```                      
"featureInfoTemplate": {
    "formats": {
        "bands.wofs_filtered_summary": {
            "type": "number",
            "style": "percent"
        },
    },
    "template": "Percentage observed as water: {bands.wofs_filtered_summary}"
}
...
```
The number gets rendered, but not as a percentage.  If I try to format non-nested properties, it works.

I have also tried: 
```
"template": "{{#terria.formatNumber}}{style:'percent'}{{bands.wofs_filtered_summary}}{{/terria.formatNumber}}"
```
which results in a white screen.

**Comment by kring** [comment]
Can you try replacing `bands.wofs_filtered_summary` with `bands_wofs_filtered_summary`? I think the properties from a WMS are not considered nested even if they contain dots.

**Comment by andrewdhicks** [comment]
Replacing the . with an underscore didn't help, either in the `formats` section or in the template.

The raw data look like this:
```{
  "lon": 137.0874023437495,
  "lat": -28.20760859532745,
  "time": "1970-01-01 00:00:00 UTC",
  "bands": {
    "confidence": 1,
    "wofs_filtered_summary": 0.1327102780342102
  },
  "data_available_for_dates": [
    "1970-01-01"
  ],
  "data_links": [
    "http://dea-public-data.s3-website-ap-southeast-2.amazonaws.com/?prefix=WOfS/filtered_summary/v2.1.0/combined/x_4/y_-31"
  ]
}
```

I've just found that using the inline method works for `maximumFractionDigits` but not for `style: percent`:
```
"template": "{{#terria.formatNumber}}{maximumFractionDigits:2}{{bands.wofs_filtered_summary}}{{/terria.formatNumber}}"
```

**Comment by andrewdhicks** [comment]
If I use escaped double quotes instead of single quotes for `"percent"`, it works!
```
{\"style\":\"percent\"}
```
I only noticed when I did a cut-and-paste on the date format docs, and the escape slashes were there!
