### ISSUE TITLE
Add a Black and White Base map imagery option

### ISSUE THREAD

**Issue by Meeena** [TerriaJS/terriajs#322]
A lot of the data is easier to see against a map that is stripped of colour. Groundwater aquifer contours are a good example. It would be ideal to see black and white terrain imagery, but I have seen a black and white toner map from Stamen in the early iterations of the National Map.

It would be good to use this version to get something up quickly:
http://maps.stamen.com/toner-lite/

**Comment by kring** [comment]
Closing this because it's the same as #493, and there's more conversation in that issue.
