### ISSUE TITLE
My Data: apply min-height to dragDrop box

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#3223]
### Problem
Currently the dragDrop box that appears in the My Data catalogue scales in height according to how many datasets have been added, but does not have a set min-height. Without a min-height the entire box collapses, providing limited functional value.

### Steps to recreate
1. nationalmap.gov.au > My Data > Add web data > https://ows.services.dea.ga.gov.au/
2. Note squished dragDrop element

### Screenshot
![screen shot 2019-02-25 at 2 10 18 pm](https://user-images.githubusercontent.com/5292858/53312249-71022b80-3908-11e9-8d7d-24a04d42007f.png)

**Comment by soyarsauce** [comment]
@philipgrimmett this doesn't seem to be an issue anymore?
Was it a specific browser?

<img width="827" alt="image" src="https://user-images.githubusercontent.com/9134432/69300800-693da080-0c68-11ea-8d54-ab83316c45f5.png">

**Comment by soyarsauce** [comment]
Found it - visual problem in Safari, can replicate on master.

**Comment by soyarsauce** [comment]
(Also noting that this is purely a visual problem, drag and drop gets captured anywhere you drop onto)
