### ISSUE TITLE
My Data: parent list item squashed

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#3224]
### Steps to reproduce
1. My Data catalogue > Add web data
2. Add 'https://ows.services.dea.ga.gov.au/'
3. View untitled(?) parent list item/folder

### Screenshot
![screen shot 2019-02-25 at 2 28 21 pm](https://user-images.githubusercontent.com/5292858/53312576-b541fb80-3909-11e9-972d-68d21825bbc6.png)

**Comment by kring** [comment]
Yeah, the problem is the group has no name. Just need to figure out why, and maybe also adjust the CSS so that it looks ok even with no name.
