### ISSUE TITLE
Add web data: URL placeholder looks like a pre-fill value

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#3226]
### Problem
Currently input placeholder text is too dark and looks like a pre-fill value. This makes it difficult for users to quickly determine which fields still require input.

### Screenshot
![screen shot 2019-02-25 at 3 21 01 pm](https://user-images.githubusercontent.com/5292858/53314638-98aac100-3913-11e9-9f7b-9852c6852171.png)

### Proposed solution
Body text: #606D80
Placeholder text: 0.5 opacity

**Comment by kring** [comment]
Good early issue for Emma.
