### ISSUE TITLE
When the timeline has a date format, apply it to date picker and time control as well

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#3235]
When the timeline has a date format, apply it to date picker and time control as well.

E.g. this: https://github.com/TerriaJS/aremi-natmap/blob/master/datasources/aremi/custodian/Institute_for_Sustainable_Futures/DANCE3/aremi-isf/constraints/ejs/constraints.ejs#L25

Shows up as this:

<img width="688" alt="screen shot 2019-03-04 at 09 30 24" src="https://user-images.githubusercontent.com/5283003/53702985-aeaf0900-3e60-11e9-8ff9-15c891dc1b48.png">

And we should apply the templated date `currentTime` to the date picker and time control as well - or alternatively a new format property in the init file so that we can exclude the `Year: ` part of it.

**Comment by philipgrimmett** [comment]
Looks good. Are we planning to show the full list of years in a single view (edge case eg. 1900-2022?) or can they still be bundled into groups? Also, when a year is selected from the date picker, do we currently zoom/scale the timeline to the extent of that year or to the full temporal extent of the dataset?

**Comment by philipgrimmett** [comment]
@kring I'm guessing this change won't affect your work on the date picker for NEII?

**Comment by meh9** [comment]
@philipgrimmett at the moment the only change I'm proposing is to apply the date format to the other two places we show it - everything else stays the same.

I don't think we do any zooming/scaling of the timeline when selecting times at the moment.

**Comment by meh9** [comment]
Duplicate of https://github.com/TerriaJS/terriajs/issues/2752
