### ISSUE TITLE
Loading share data doesn't update time of a currently added layer

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#3239]
Can be reproduced with 2 share URLs. Navigate the the first, then copy and paste the second into the URL bar to go to the second:
- http://ci.terria.io/master/#share=s-80TUGBkAJdzKKGrZKjvaysjJb5v
- http://ci.terria.io/master/#share=s-rJgPc0qmUDWMR3DeKxx93boIb6h

Note the date doesn't change to 19/02/2019 even though the second share link goes to that date when freshly loaded.

**Comment by kring** [comment]
Is this fixed in #3151? I think it might be.

**Comment by tephenavies** [comment]
It is

**Comment by steve9164** [comment]
Fixed by #3151.
