### ISSUE TITLE
Charts - sharing doesn't work

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3263]
Currently users can't share charts using the sharing url

test with AREMI https://www.nationalmap.gov.au/renewables/ 
1. Add Electricity - Generation - All generation types https://www.nationalmap.gov.au/renewables/#share=s-foZLkriqhpjoG3sm  
2. Select one of the generation points 
3. Expand the graph to either 1 or 7 days
4. Go to share/print, copy the url into another tab 
the chart is not visible in the shared page

**Comment by kring** [comment]
Fixing this would be good for sharing, but great for stories.
