### ISSUE TITLE
Story v3.0 - Timestamp and authorship

### ISSUE THREAD

**Issue by chloeleichen** [TerriaJS/terriajs#3279]
The following issues that won't be addressed in v1 will (hopefully) be addressed in v2:

- [ ] feedback from client: 
>It would be useful to have a time-stamp reference on when the story is created and for each scene, and who the author/contact is. Data sources may change over time and story may lose context as what is in description may no longer correspond to what user sees on screen. Similarly, author may want to provide his/her contact details.

**Comment by philipgrimmett** [comment]
- [ ] Remove auto-suggest from scene title field

**Comment by AnaBelgun** [comment]
Feedback -  it is not intuitive to click on Story button again to close the story workbench.
All top menu buttons have the X for closing them.

**Comment by AnaBelgun** [comment]
Feedback - it's not intuitive that once you leave the app, if users haven't shared the story they created, they will loose the story.

**Comment by AnaBelgun** [comment]
Suggestion: to create and save multiple stories in the story workbench

**Comment by AnaBelgun** [comment]
Feedback: New story feature is awesome, I'd also like the ability to automatically cycle through the story. This could be used in conference booths and presentations.

**Comment by AnaBelgun** [comment]
Feedback: Just some feedback on usability: when I first tried the tool out, I couldn't find any way to save or share the "story", and assumed that the tool was simply in progress and sharing functionality would be added later. It was then pointed out to me that you can indeed share a "story" using the standard "Share / print" button.

While this is great, I feel that in time it might be valuable to include an obvious "Share story" button at the bottom of the "story" panel, or at the end of the "Play Story" sequence, even if the button effectively did the same thing as the current "Share / Print" button. This would make the tool a lot more intuitive to use!
