### ISSUE TITLE
Generate test catalog items for vector tile layers

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#3281]
TerriaJS/BoundaryTiles should

* Generate a MapboxMapCatalogItem showing the boundaries for each process tileset. (Perhaps with a random colour)
* Generate a Region-mapped CsvCatalogItem for each region type (possibly multiple per tileset).

It's already generating a CSV file per region type. 

(Thanks @steve9164 for the suggestion)

**Comment by nf-s** [comment]
I added a `previewInTerria` gulp task to https://github.com/TerriaJS/boundary-tiles

in this commit https://github.com/TerriaJS/boundary-tiles/commit/e21766556e4cc726e0ac7fd2b5ec7e4dc9beb615
