### ISSUE TITLE
Why don't these CORS-compliant NASA WMS endpoints work?

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#3282]
I'm not sure why [these NASA WMS endpoints](https://wiki.earthdata.nasa.gov/display/GIBS/GIBS+API+for+Developers#GIBSAPIforDevelopers-OGCWebMapService(WMS)) are not working.

I tested CORS compliance at https://www.test-cors.org/ and they pass, but the 1.1 get caps gives "Group is not available", and the 1.3 get caps returns "Use Conversion service?".

**Comment by rowanwins** [comment]
Hi @rsignell-usgs 

Thanks for the report.

I noticed something very curious on those services, if the params are uppercase then the request for the `GetCapabilities` works, however if they are lowercase then the request fails

eg 
this works [https://gibs.earthdata.nasa.gov/wms/epsg3857/best/wms.cgi?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0](https://gibs.earthdata.nasa.gov/wms/epsg3857/best/wms.cgi?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0)

however this does not 
[https://gibs.earthdata.nasa.gov/wms/epsg3857/best/wms.cgi?service=WMS&request=GetCapabilities&version=1.3.0](https://gibs.earthdata.nasa.gov/wms/epsg3857/best/wms.cgi?service=WMS&request=GetCapabilities&version=1.3.0)

Narrowing it down even further it appears that it's only the param `SERVICE` that needs to be uppercase...

I'm not super familiar yet with how Terria handles WMS but from my initial look we're sending the getCapabilities requests with lowercase params.

I'm not sure if this behaviour is specific to the GIBS MapServer implementation, or if it's more general to MapServer in general.

Cheers,
Rowan

**Comment by rowanwins** [comment]
There is also some [notes here](https://mapserver.org/ogc/wms_server.html#changing-the-online-resource-url) about the `map` parameter that MapServer sometimes expects.

**Comment by rowanwins** [comment]
Just to followup this is indeed to do with the casing of the `service` parameter

Changing `service` to `SERVICE` in the  `WebMapServiceCatalogGroup.prototype._load` resolves the initial issue and allows the user to see the list of layers, eg
````
WebMapServiceCatalogGroup.prototype._load = function() {
    var url = cleanAndProxyUrl(this, this.url) + '?SERVICE=WMS&request=GetCapabilities&version=1.3.0&tiled=true';
````
However the layer still won't actually load because the `Cesium.WebMapServiceImageryProvider` default parameters are lowercase...

So any fix would require a bit of more thought.

**Comment by rsignell-usgs** [comment]
We informed the provider and they fixed the WMS endpoints!
Try this out:
https://maps.usgs.gov/map/#https://raw.githubusercontent.com/USGS-CMG/terriajs-dive/master/examples/NASA-GIBS.json
(I'm referencing a user-generated catalog here to change the default max time steps from 1,000 to 10,000.)
![2019-04-25_9-56-55](https://user-images.githubusercontent.com/1872600/56744438-88159c00-6746-11e9-88df-44058e734e09.jpg)
