### ISSUE TITLE
Layers errors breaks story initialisation

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#3283]
When a shared story includes a layer that errors when you go to the shared story URL, this breaks the initialisation of the story, and once you have acknowledged the error popup you get an "initialisation has failed" error. After that you don't get the "want to see the story" question, and if you manually click into story mode none of the story is there.

At the moment this is happening quite often with the digitwin stories because the NSW base layer is currently very flaky.

**Comment by chloeleichen** [comment]
Fixed in https://github.com/TerriaJS/terriajs/pull/3228
