### ISSUE TITLE
Clicking next/prev in story mode has significant delay before action

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#3284]
There is a relatively significant delay before anything happens when you click next/previous in story mode. As it turns out it looks like it makes 4 http requests every time you click:

<img width="619" alt="Screen Shot 2019-04-09 at 21 01 55" src="https://user-images.githubusercontent.com/5283003/55858181-bbcbb180-5b0a-11e9-9847-4cb5f0a08cd1.png">

If we can solve that to avoid some or all of them the responsiveness should be better.

**Comment by chloeleichen** [comment]
Fixed in https://github.com/TerriaJS/terriajs/pull/3228
