### ISSUE TITLE
Model architecture: Hook up Add Data tab

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#3297]

**Comment by na9da** [comment]
@philipgrimmett What should ideally happen when a user adds a data source twice from the MyData tab?

1) It should be shown twice under MyData tab and Workbench 
2) It should be shown once in MyData tab but twice in the Workbench 
3) It should be shown once in both MyData tab and the Workbench.

Current behavior is 1.

**Comment by philipgrimmett** [comment]
@na9da I guess it depends on whether you're adding local data or a web service:

**Local:** if we can detect that the user has re-added exactly the same file, option 3. If not, option 1 (prepended with "copy #")
 
**Web service:** option 3. 

@kring is there ever a need to manually refresh(?) web services? If so, should adding the same URL twice overwrite the previous listing?

**Comment by AnaBelgun** [comment]
Whatever we do, the users shouldn't see a list of all the additions if they have the same name or if they do, they should have the option to delete them
