### ISSUE TITLE
Model architecture: Enable eslint for .ts files

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#3303]

**Comment by kring** [comment]
https://github.com/Microsoft/TypeScript/issues/30553
https://github.com/typescript-eslint/typescript-eslint

**Comment by tephenavies** [comment]
Our current eslint config is really outdated. Now `prettier` fills a lot of the requirements we used `eslint` for. We should maybe consider cutting it down a lot, starting with something like:
```json
{
  "extends": [
    "eslint:recommended",
    "prettier"
  ]
}
```
And add config to make it work with TypeScript etc.

We'll probably need some `react` rules too, e.g. see #4565.

**Comment by soyarsauce** [comment]
Related https://github.com/TerriaJS/terriajs/pull/4519 & https://github.com/TerriaJS/terriajs/issues/4565

**Comment by ljowen** [comment]
Blocked by #6991

**Comment by ljowen** [comment]
PR: https://github.com/TerriaJS/terriajs/pull/6985
