### ISSUE TITLE
Story feature: make video, add to terria.io

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3325]
- [x] user guide video 

- [ ] add feature and video to terria.io website

- [x] make a story about NatMap history (5 year anniversary on 9 July 2014) - unrelated to the development of the story feature

**Comment by AnaBelgun** [comment]
PR on Guide needs to be finalised and merged https://github.com/TerriaJS/terriajs/pull/3458

**Comment by philipgrimmett** [comment]
Video link (unlisted):
https://youtu.be/fbiQawV8IYY
