### ISSUE TITLE
Investigate - WMS with many layers/sub-layers causes browser to crash

### ISSUE THREAD

**Issue by rowanwins** [TerriaJS/terriajs#3329]
## Issue
Currently using NationalMap if a user attempts to load a WMS with a large GetCapabilities document the browser crashes. 
- For example https://geo.weather.gc.ca/geomet/?service=WMS&request=GetCapabilities which is 9MB

## Options
~~1. Handle the parsing of XML files in [terriajs-server](https://github.com/TerriaJS/terriajs-server)~~
~~2. Improving the browser parsing~~
    ~~- There are 1001 XML parsing libs. One option may be a lib like [parse-xml](https://github.com/rgrove/parse-xml), I've picked this because it's small and browser friendly. Here is [an example](https://gist.github.com/rowanwins/7fcfc9ac41e5e00f111c62e7fa9c0dba) parsing the problematic GetCapabilities doc listed above in the browser which works fine. parse-xml weighs 9kb minified so it adds a bit of overhead compared to the current approach but it doesn't crash so that's the big plus.~~

~~My preference would be to keep the parsing browser side.~~

~~Any other thoughts from anyone?~~

Note: See additional diagnosis [below](https://github.com/TerriaJS/terriajs/issues/3329#issuecomment-485650776)

**Comment by kring** [comment]
Wow, I didn't expect the browser's XML parsing to be the problem. I definitely agree with keeping it in-browser, though. `parse-xml` looks promising!

**Comment by kring** [comment]
This bit in the `parse-xml` docs might cause us some grief, though:

> Note that since parse-xml doesn't implement XML Namespaces, no special treatment is given to namespace prefixes in element and attribute names.

> In other words, <foo:bar foo:baz="quux" /> will result in the element name "foo:bar" and the attribute name "foo:baz".

Not all WMS implementations, for example, agree on the namespace prefixes they use. It would probably be fine if the library ignored namespaces entirely (i.e. removed them), but because it includes them as part of the name, we need to be careful not to key off them.

**Comment by rowanwins** [comment]
So to provide an update on this issue, it's not so much the XML parsing that this the problem, but more  the creation of all the subsequent `WebMapServiceCatalogItem`'s. 

If I attempt to add the WMS listed above it is trying to create several hundred WMS layers. As it stands we have the [`addLayersRecursively`](https://github.com/TerriaJS/terriajs/blob/master/lib/Models/WebMapServiceCatalogGroup.js#L228-L234) function for the `WebMapServiceCatalogGroup` which basically loops through everything. 

One option would be to do a brute force length check, something like
````
    if (layers.length > 25) {
        console.log(`Provider Feedback: There are ${layers.length} layers/sub-layers in the WMS.`);
        return
    }
````
Which spits out the following in my console
````
Provider Feedback: There are 28 layers/sub-layers in the WMS.
Provider Feedback: There are 50 layers/sub-layers in the WMS.
Provider Feedback: There are 28 layers/sub-layers in the WMS.
Provider Feedback: There are 111 layers/sub-layers in the WMS.
Provider Feedback: There are 124 layers/sub-layers in the WMS.
Provider Feedback: There are 191 layers/sub-layers in the WMS.
Provider Feedback: There are 38 layers/sub-layers in the WMS.
````
This sort of approach works in that at least Terria now doesn't break with memory problems. 

The other approach might be to have a more streamlined `WebMapServiceCatalogItem` just for that initial browsing of capabilities before it gets added to the map...

Any thoughts @kring ?

**Comment by kring** [comment]
Ah yeah that's what I was afraid of. I think in this case the WMS has over 2500 layers, which is a lot but ideally still wouldn't use so much memory that the browser tab crashes. It might be worth investigating if there's any low-hanging fruit for reducing memory usage, but there may not be.

I think this particular WMS is also quite nested, so another option is to avoid creating all catalog items on load and instead just create the first level, and then create subsequent layers as they're opened. That would require a new `WebMapServiceSubCatalogGroup` or somesuch to manage the delayed loading.

In the new MobX-based architecture I've thought about having a general purpose light weight version of a catalog item that basically just tracks the definitional bits and rehydrates itself into a real catalog item when it's accessed, so maybe the ultimate solution is to wait for that.

**Comment by kring** [comment]
I guess an artificial layer count limit is better than crashing if none of the above pan out. It would have to be more like 300 rather than 25 though.

**Comment by rowanwins** [comment]
I tried bumping up the count and it crashes with the threshold set to 50. I'm trying to see if it's failing anywhere consistently but I'm not sure yet...

I was thinking something along the lines of your suggested 'light weight version of a catalog item', the main draw back I can see is that you might have to implement that for many layer types / Catalog Items (still learning the lingo!), rather than just being a WMS specific fix for a WMS specific problem...

**Comment by kring** [comment]
> I tried bumping up the count and it crashes with the threshold set to 50

I'm guessing that's because you're only counting the top-level groups, each of which have heaps of groups and items in them. I think if you count all things created across all levels of the hierarchy, you should be able to get to a couple hundred at least before running into problems.

**Comment by AnaBelgun** [comment]
@rowanwins @kring when investigation is complete we should decide if/when we fix it
