### ISSUE TITLE
Unclear desired behavior when some WMS styles don't define an LegendURL

### ISSUE THREAD

**Issue by andrewdhicks** [TerriaJS/terriajs#3330]
There is some undesirable interaction between `TerriaJS` and `datacube-ows` when a layer has styles where only some styles have LegendURL defined. (I think it stems from both packages trying to support a variety of clients or servers that don't always follow the specs.)

`datacube-ows` has a WMS layer with several styles, some of them have legends, some of them do not. When a style is selected in Terria that has `LegendURL` defined, that legend is displayed. When a style without a LegendURL is selected, Terria makes a call to `GetLegendGraphic`, (without the `&styles=...` parameter set).
Although `datacube-ows` doesn't advertise in its `GetCaps` that is supports `GetLegendGraphic`, it returns with an image combining all the available styles for the layer.  Terria shows this image as the legend, which is not relevant to the selected style.

Example: https://terria-cube.terria.io/#share=s-hwhdgBTgp5pAPDHWJxqQtJ4d49R

I'm not sure what the best path forward is maintain support for all the non-standard?

Possible solutions for `datacube-ows`:
 * set `Style.LegendURL` to `''`: this results in the desired behavior, but breaks OGC compliance checks (Example: https://terria-cube.terria.io/#share=s-q8euAv8waNCWmFaEpg8yV74ePNV )
* set `Style.LegendURL` to a transparent 1x1 pixel: Terria displays it, but with a white background
* don't return `GetLegendGraphic` when some layers don't have legends: Not ideal for WMS clients that make no use of `Style.LegendURL` and rely on `GetLegendGraphic`. **Not sure what these other WMS clients are, or what we are assuming**

Ideas for possible solutions for `TerriaJS`:
* call `GetLegendGraphic` with `&styles=...`: does this break ncWMS support etc?
* don't call `GetLegendGraphic` if some styles have `LegendURL`: very edge-case specific solution?
* ?

**Comment by kring** [comment]
> call GetLegendGraphic with &styles=...: does this break ncWMS support etc?

I don't know of anything this would break. AFAIK it's just an oversight that we're not doing this.

> don't call GetLegendGraphic if some styles have LegendURL: very edge-case specific solution?

That could be ok too, but the impact is harder to predict, so maybe just stick to the first solution if it solves the problem.
