### ISSUE TITLE
Add example CSVs 

### ISSUE THREAD

**Issue by nahidakbar** [TerriaJS/terriajs#334]
Would it be possible to add some examples of the different csv files and columns it supports and put them in the FAQ page or even in the github repository. e.g. how should I format things if I wanted a time varying item or if I wanted a point cloud.

**Comment by hilarycinis** [comment]
I love this idea!

**Comment by stevage** [comment]
Yep, why don't I make this part of the forthcoming Data Provider's Handbook?

**Comment by kring** [comment]
I believe this is well covered by the csv-geo-au docs:
https://github.com/NICTA/nationalmap/wiki/csv-geo-au
