### ISSUE TITLE
Mouse is offset with certain layers enabled

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#3345]
Reproduce (with Safari 12.0.3, also seen in 12.1):

1. Load nationalmap.gov.au (or a terriamap with below dataset in catalog, doesn't reproduce if you use the URL as a web data source)
2. Click "Add data" to bring up the catalogue
3. Browse to:
National Datasets -> Communications -> ABC Photo Stories (2009-2014) -> Add to the map
Click "Add data" to bring up the data catalogue again

Observe that your mouse is offset when trying to interact with the data catalogue

![mouse-offset-bug](https://user-images.githubusercontent.com/9134432/56935677-faff8800-6b35-11e9-9bda-29d31915337d.gif)

**Comment by zoran995** [comment]
Tested on a bunch of national map datasets and ci.terria.io and can't reproduce it anymore.
