### ISSUE TITLE
User help tutorial - bring back to life from SoE

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3362]
State of Environment (https://github.com/TerriaJS/soe) instance had a help guide for users/prompts which is not available anymore in the app. 
This ticket is to:
- find the guide development in the https://github.com/TerriaJS/soe code base
- improve it and implement it in TerriaJS master to be available as part of the story feature

**Comment by soyarsauce** [comment]
At least for SoE, the broken SoE help tutorial will be fixed if this gets merged:
https://github.com/TerriaJS/soe/pull/8

@philipgrimmett wants to tidy some stuff up but I think that can happen concurrently to the help-currently-unavailable-state of SoE

**Comment by AnaBelgun** [comment]
we need to re-release

**Comment by AnaBelgun** [comment]
release approval pending; issue resolved
