### ISSUE TITLE
App crashes when switching layers in census data

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#3379]
1. In NationalMap, add the `Social and Economic > Projections > Population Projections, 2011 to 2036, by Living Arrangements by Age` layer
2. Click a region, bringing up feature info.
3. Under Ages, click a different age.
4. Boom. White screen of death. (On Firefox, MacOS anyway)

This doesn't happen if step 2 is skipped. I suspect it's much more general than this specific scenario.

**Comment by rowanwins** [comment]
Replicated on chrome. Also replicated on other SDMX region-mapped datasets with the feature info open and changing a parameter on the workbench.

**Comment by nf-s** [comment]
v7
