### ISSUE TITLE
Improve 'clickability' of workbench action bar

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#3381]
**Currently action bar**
![Screen Shot 2019-05-10 at 2 49 31 pm](https://user-images.githubusercontent.com/5292858/57503633-48e56e80-7334-11e9-9a95-1253904f8459.png)
![Screen Shot 2019-05-10 at 2 57 53 pm](https://user-images.githubusercontent.com/5292858/57503635-4aaf3200-7334-11e9-9ecd-a4c5704ca517.png)

**Proposed changes** 
_See Invision comments for additional detail_
https://invis.io/8GRY63FNZ9J#/362575982_terria_-_Empty_Workbench

**Screenshot**
![terria - expanded and hidden - v2](https://user-images.githubusercontent.com/5292858/57674952-f83b8180-7663-11e9-8c5d-da9885babec4.png)

**Comment by rowanwins** [comment]
Hi @philipgrimmett 

Some comments about the proposed design changes
- Really like the message in the workbench when your workbench is empty
- I like shortening the tool names (eg "Zoom To Extent" becoming "Zoom"). I think in most cases the tools are obvious enough to drop the verbose description
  - One question mark here might be whether you hide buttons for tools that aren't available (eg split), or whether you simply disable them and make them not clickable.
- Moving the collapse button to the second row is potentially a smidge confusing because it kind of almost looks like a dropdown for "More tools" or something like that. 
  - This could also be a hindrance on smaller devices where we needed to introduce a dropdown to house all the tools
- I'm not 100% sold on the idea of collapsing all the content and disabling buttons when you toggle a layer off
  - For instance I can imagine circumstances where I'd want to zoom to a layer even if it wasn't turned on.
  - And sometimes still seeing a legend is helpful when you are toggling layers on and off.

Some other areas that haven't been touched but could be candidates
- The 'Next data update' bit feels quite prominent
  - I wonder if changing the icon size to the same as the icons in the row above would help?
  - Or could you move it to the row above and just show the icon and then on hover show the actual time value?
- The opacity slider also takes up a lot of realestate, in most other web map apps it is either given far less prominence (eg [geocortex](http://app.actmapi.act.gov.au/actmapi/index.html?viewer=basic)) or exposed via button (eg [keplergl](https://kepler.gl/))

Anyway in general I think it's heading in the right direction, feels cleaner and fresher!

**Comment by philipgrimmett** [comment]
Thanks again @rowanwins! Some notes/updates:

**Updated invision:** 
https://invis.io/8GRY63FNZ9J#/362575982_terria_-_Empty_Workbench

>Really like the message in the workbench when your workbench is empty

I'd love to prompt users to click the blue 'Add button' in the first instance, but figured the 'Browse the data catalogue' link is a reasonable failsafe. If we revive the help/tour system from SoE we can replace it with something like "take a quick tour".

>I like shortening the tool names (eg "Zoom To Extent" becoming "Zoom"). I think in most cases the tools are obvious enough to drop the verbose description

Mm, hopefully! Definitely a candidate for usability testing.

>One question mark here might be whether you hide buttons for tools that aren't available (eg split), or whether you simply disable them and make them not clickable.

Here's my thinking:

_Hide action button if:_
- The user isn't authorised to perform that action
- There is no clear way for the user to enable that action
- The action is not critical (ie. can be placed in a contextual menu without significantly impacting core tasks)

_Disable action button if:_
- Discoverability is key to performing core tasks
- Hiding/revealing is too distracting visually (ie. significantly affects the position of other UI elements)

We'll run out of horizontal space eventually, but I'd like hold off on adding an overflow menu until we really need one.

>Moving the collapse button to the second row is potentially a smidge confusing because it kind of almost looks like a dropdown for "More tools" or something like that.

Yep, agree. It's a bit of a compromise:

- Existing pattens throughout the map lead users to expect a close/done button in the immediate top-right corner (feature info, charts, data catalogue)
- Placing the 'collapse/expand' action in the workbench action bar brings it a bit closer to the actual fold. 

If there was enough horizontal space we could position 'collapse/expand' to the left of 'remove', but that introduces other issues: less space for dataset titles, and a slightly higher risk of users trying to collapse a workbench item and accidentally removing it in the process.

>This could also be a hindrance on smaller devices where we needed to introduce a dropdown to house all the tools

I've updated the prototype so that the collapse/expand icons look less like menus, and I've included a menu icon for reference in the first dataset (using the same icon as Story menus). If we want all accordion styles to be consistent we may need to update the data catalogue as well. 

>I'm not 100% sold on the idea of collapsing all the content and disabling buttons when you toggle a layer off. For instance I can imagine circumstances where I'd want to zoom to a layer even if it wasn't turned on, and sometimes still seeing a legend is helpful when you are toggling layers on and off.

It's not essential behaviour, but I think it might be worth testing. If we can do workbench cleanup without getting in the way of users it might help to mitigate some of the novelty-sized legends that appear in our catalogues. 

On being able to reference legends while toggling datasets: that's a good point, but is seeing a legend for an inactive dataset more helpful than seeing the legend for an active dataset it pushes below the fold?
 
>The 'Next data update' bit feels quite prominent; I wonder if changing the icon size to the same as the icons in the row above would help?

Done!

>Or could you move it to the row above and just show the icon and then on hover show the actual time value?

This is what I had for the initial design, but after speaking with Emma we decided it might better for discoverability to include text for the countdown as well.

>The opacity slider also takes up a lot of realestate, in most other web map apps it is either given far less prominence (eg [geocortex](http://app.actmapi.act.gov.au/actmapi/index.html?viewer=basic)) or exposed via button (eg [keplergl](https://kepler.gl/))

Good point. I've shortened the opacity slider to 100px, which give us space to include one or two related actions (maybe blending modes?). Or we could just leave it as zen whitespace :)

**Comment by soyarsauce** [comment]
Hey @philipgrimmett  - some notes on v4
How do you see the overflow menu working? Would it be a dropdown or another "toggle" to expand the area for actions onto extra rows as required?

Is the "Export" a design-only-placeholder for another modal in download/export options down the track?

>On being able to reference legends while toggling datasets: that's a good point, but is seeing a legend for an inactive dataset more helpful than seeing the legend for an active dataset it pushes below the fold?

I agree that seeing legends for active datasets would be more helpful, however your new expand/collapse in v4 allows for both now - perhaps disabling will also simultaneously collapse the legend/opacity etc, but can be expanded again while disabled if needed?

Looks amazing!!

**Comment by AnaBelgun** [comment]
to dev in mobx branch

**Comment by philipgrimmett** [comment]
Thanks @soyarsauce! Response to feedback below: 

> Workbench overflow: temp dropdown menu or accordion?

I think putting an accordion (workbench actions) within an accordion (workbench item) is probably a bad idea, so where required I think we should have a temp dropdown menu, similar to what we have for stories scenes (screenshot below)

<img width="482" alt="Screen Shot 2019-08-05 at 10 51 41 am" src="https://user-images.githubusercontent.com/5292858/62431892-15698300-b76f-11e9-9fa7-7f105d72ed3d.png">

> Is the "Export" a design-only-placeholder for another modal in download/export options down the track?

Currently 'Export' only applies to clip&ship functionality, but may eventually launch more generic export functionality (modal with export options is one possibility)

> Legend visibility when item is hidden

Yep, the invision prototype hides legends when an item is hidden, but it should be still be possible to make the legend visible without unhiding the parent item (screenshot below). I'll update the prototype now.

<img width="339" alt="Screen Shot 2019-08-05 at 11 19 54 am" src="https://user-images.githubusercontent.com/5292858/62432428-008eee80-b773-11e9-9318-b70315ceae6e.png">

**Comment by rowanwins** [comment]
overtaken by events
