### ISSUE TITLE
Consolidate/refactor catalog management and reuse

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#3384]
There are a few issues around how we manage catalogs for various projects which have gotten messy and are worth tidying up.

### Sub-catalog reuse

We often want to reuse parts of a catalog between different projects. If possible, we'd like to define the catalog items once, then easily incorporate them in other projects as desired. Two common patterns:

* Catalog items are created for a specific project (eg, NEII Viewer, AREMI) then we want to also add them to National Map.
* A particular project (Eg, InvestorMap) has some custom layers, but then also wants lots of contextual layers added that already exist in National Map.

### Automatic catalogue construction

We often want to partially generate a catalogue, rather than simply manage the whole thing as a single JSON file. Some specific use cases:

* Repeating elements such as data attribution, featureInfo templates or region-mapping parameters, across many catalogue items.
* Incorporating layers whose primary definition is elsewhere (ie, the subcatalogue reuse use case)
* (Others?)

## Current approach

We currently use a few different techniques in different places but don't have a coherent strategy.

* terriajs/nationalmap-catalog is the only example where the catalog itself is managed in its own repo.
* AREMI and NationalMap use EJS templates, with a [gulp task](https://github.com/TerriaJS/NationalMap-Catalog/blob/master/gulpfile.js#L122) to assemble them into a final built file.
* InvestorMap uses [copies of other catalogs](https://github.com/TerriaJS/InvestorMap/tree/master/datasources/investormap/shared) saved into its repo, then a [regular JS script](https://github.com/TerriaJS/InvestorMap/blob/master/datasources/investormap/root.js) to assemble lots of pieces together.
* DroughtMap uses a [similar approach](https://github.com/TerriaJS/drought-map/tree/master/datasources), apparently including duplicating some code.
* NEII Viewer uses all hand-maintained files, including some out of date NM layers in a "[contextual layers](https://github.com/TerriaJS/neii-viewer/blob/master/wwwroot/init/neii-contextual.json)" file.
* GeoGLAM seems to use a [single hand-maintained file](https://github.com/TerriaJS/geoglam-nm/blob/master/wwwroot/init/geoglam.json)

## Proposed approach

Not sure. It would certainly be nice if each project used the same approach for constructing its catalogue. And ideally, the machinery of how that happens would be shared code. It should be flexible enough to handle:

* Simply combining JSON files if that's how they're defined.
* Pulling in pieces of catalogs defined elsewhere (including other repos).
* Custom JS code wherever wanted.

Thoughts @kring @steve9164 ?

**Comment by AnaBelgun** [comment]
will start this sprint but continue beyond

**Comment by kring** [comment]
My preference is to make shared parts of catalogs into separate repos on github, published on npm, and following semver (e.g. changing a URL of an existing layer might be a minor version, but reorganizing it would be major). Then apps reference catalog packages using package.json and import and manipulate them (if necessary) using javascript running at compile time to assemble the app's catalog JSON file.

**Comment by stevage** [comment]
Yeah, that sounds great. And possibly making some of the catalog manipulation logic (like the "import item X from catalog Y" and "remove duplicates" logic) itself a separate library too.

**Comment by nf-s** [comment]
I think we have reached a good point with this

- Everything is JSON, we don't use templating, or JS to generate catalogs anymore
- `TerriaReference` allows you to construct catalogs using other catalogs (and you can specify `path` to partially load catalog)
  - See [NationalMap root catalog example](https://terria-catalogs-public.storage.googleapis.com/nationalmap/prod.json) 
- `itemProperties` / `itemPropertiesByType` / `itemPropertiesByIds` allows setting properties at a group-level, and then they are applied to items
- `includeMembersRegex` / `excludeMembers` allows filtering/including members for each group
