### ISSUE TITLE
TerriaMap Switching between 2D & 3D

### ISSUE THREAD

**Issue by urbanows** [TerriaJS/terriajs#3389]
When running TerriaMap without CesiumIon, it gets stuck in 3d mode.

If I disable (set to null or remove key/value) CesiumIon in the config.json file, the '3D Terrain' option disappears from the Map View options.  This is not unexpected.  The unexpected behavior is that if I click on '3D Smooth' or '2D', I enter 3D mode and am  stuck there even after clicking on '2D'  again.   Although we are planning to use CesiumIon,   I'd like for our master branch to not include the CesiumIon license key and still have the 2D and 3D modes function.  Is there a specific configuration that I should use to enable 2d/3d switching?

    "useCesiumIonTerrain": false,
    "useCesiumIonBingImagery": false,
    "cesiumIonAccessToken": null,

The bingMapsKey is not set.

Th same behavior is encountered regardless of whether the viewerMode is set to 2d in the initialization file:
"viewerMode": "2d",

The following also yield a 3d map:
http://127.0.0.1:3002/#usgs&map=2d

**Comment by tephenavies** [comment]
The bug with picking '2D' in map settings when '3D Terrain' is not available has been fixed in #3321. I have not seen any bugs with setting the viewer mode in initialisation files or with a `map=2d` in the url, and I couldn't reproduce in the latest terriajs.
