### ISSUE TITLE
DragDrop CSVs appear as 'unnamed item'

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#3399]
**Steps to reproduce**
1. Navigate to http://ci.terria.io/master/
2. Drag CSV onto map (eg. "Population Estimates 2017-18.csv")
3. See "unnamed item" in workbench

**Comment by rowanwins** [comment]
The same thing occurs with geojson files that get dropped on.

If this were to be fixed @philipgrimmett do you think we should display the filename with or without the extension?

![Filename](https://user-images.githubusercontent.com/6735870/60552745-6f8fb680-9d73-11e9-9a47-1c4e82b092cd.png)

**Comment by philipgrimmett** [comment]
@rowanwins Hmm. Not sure. My feeling is that extensions should be shown where the user might reasonably expect to re-export/download their file after drag-dropping it into Terria. Where Terria is the endpoint for that data, I'd be less concerned about displaying file extensions.

That said: I think we should retain them for the time being, if only for the edge case where a user drags the same dataset in two different formats onto the map and has to distinguish between the two (eg. _publicParks.csv_ and _publicParks.geojson_)
