### ISSUE TITLE
Model architecture: Create GetLegendGraphic legend for WMS catalog items without one

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#3426]
The old `WebMapServiceCatalogItem` would create a legend URL based on the `GetLegendGraphic` service if a suitable legend URL could not be found in a `<Style>`. We need to add the same feature to the new model architecture.

**Comment by kring** [comment]
Don't forget to include the `style` as added in #3343.

**Comment by rowanwins** [comment]
Done in #4756
