### ISSUE TITLE
Measuring tool line faded in 3d, IE11

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3428]
User spotted bug

1) open NatMap in IE, 3d, use measuring tool
the line is very faded

![image](https://user-images.githubusercontent.com/18452161/58389232-edbdb680-806b-11e9-8713-6f5786422767.png)

2) open NatMap, in IE, 2D, use measuring tool: 
the line is clear
![image](https://user-images.githubusercontent.com/18452161/58389242-0fb73900-806c-11e9-943d-dae47fca82d3.png)

3) open NatMap in Chrome, 3D, use measuring tool:
line is clear and start and end points are marked:
![image](https://user-images.githubusercontent.com/18452161/58389265-455c2200-806c-11e9-9b83-cd26fa20da90.png)

4) Open NatMap in Chrome, 2D, use measuring tool: 
line is clear, start - end points are marked: 
![image](https://user-images.githubusercontent.com/18452161/58389277-645ab400-806c-11e9-83ef-182075faeda3.png)

**Comment by AnaBelgun** [comment]
will discuss this sprint

**Comment by zoran995** [comment]
IE is not supported anymore
