### ISSUE TITLE
Charts: x-axis label is pushed off bottom of screen 

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#3437]
### Steps to reproduce
1. http://terria-cube.terria.io/#share=s-lGoZMmb5B4eBG7ZjE6LtG9A63Ru
2. Click on watercourse level feature, expand chart
3. Toggle on/off chart for Near Real-Time Surface Reflectance (Sentinel 2A)
4. Note x-axis visibility/position

![terria-chartHeight-640](https://user-images.githubusercontent.com/5292858/58399165-9e42af00-809a-11e9-9a20-0fc1b22afc7a.gif)

**Comment by nf-s** [comment]
No longer the case in v8

**Note** link may take a long time too load

https://maps.dea.ga.gov.au/#share=s-mUic636pTcljdwlluUmTBEhZv4u

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/6187649/179470891-89541251-cfc0-4712-b78d-f75b0496817c.png">
