### ISSUE TITLE
Model architecture: Charts

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#3466]

**Comment by na9da** [comment]
TODOs for feature parity with current `master`:
- [ ] Colors
- [ ] Chart highlight & tooltips
- [ ] x,y grid lines
- [ ] y Axis
- [ ] Legends
- [ ] Replicate enabling/disabling of chart lines (implemented using `concepts` in master).

**Comment by AnaBelgun** [comment]
@na9da would you please update where you are with this one. I think mostly done...

**Comment by na9da** [comment]
I think we can close this. There is more pending work, which we can track separately.
