### ISSUE TITLE
Model architecture: Catalog functions

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#3478]
i.e. WPS

**Comment by na9da** [comment]
- [x] Get a simple WPS service working (eg. geoglam) with GeoJsonParameter  and with user drawing stubbed.
- [x] Converters for more parameters: Line, Point, Polygon, DateTime etc.
- [x] Support `executeWithHttpGet`.
- [x] Poll for result when `statusLocation` is set in `Execute` response.
- [x] WPS catalog item should be able to load response from `wpsResponseUrl`
- [x] Handle `mimeType=csv`
- [x] Fix user drawing, requires mapInteraction, decide on how to handle mappables that are not catalog items.
- [x] More tests for parameter to input converters.
- [ ] More tests for parameter classes.

**Comment by na9da** [comment]
Fixed by https://github.com/TerriaJS/terriajs/pull/3592
