### ISSUE TITLE
More descriptive data field title

### ISSUE THREAD

**Issue by mikewu98** [TerriaJS/terriajs#348]
Data field names could be too terse to be understood. For example, in NICTA Household Travel Survey dataset, there is a field named "av_n_h_wd". It means "Average number of trips per household in a weekday". It would be more user friendly when the more descriptive title is displayed on mouse over "av_n_h_wd".

**Comment by kring** [comment]
We now have the ability to define an HTML template to use in the feature info panel, which I believe covers this use case.
