### ISSUE TITLE
Model architecture: Fix region mapping in Leaflet

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#3496]
Currently the construction of a Leaflet layer using a Ceisum ImageryProvider assumes that imagery will be fetched as image tiles from a remote server. MapboxVectorTileImageryProvider renders imagery locally using canvas so it currently doesn't work in Leaflet. We should be able to use something like GridLayer to make images available to Leaflet or add the separate Leaflet tile layer solution for MVTs from `master`.

**Comment by tephenavies** [comment]
This should be solvable in a general way ImageryProvider -> Leaflet TileLayer.

**Comment by AnaBelgun** [comment]
@steve9164 would you please close this one if done (= reviewed and merged)?

**Comment by tephenavies** [comment]
Solved specifically for mvt layers in Leaflet
