### ISSUE TITLE
Clicking on map in 2D mode across anti-meridian can miss features

### ISSUE THREAD

**Issue by rowanwins** [TerriaJS/terriajs#3505]
Working with a region mapped csv whose regions cross the anti-meridian we're noticing some issues picking features when in 2D mode when zoomed out.

If I click on the left (east) of the anti-meridian I can successfully pick features
![Working](https://user-images.githubusercontent.com/6735870/59570694-9c8b6a80-90df-11e9-8348-f1a3c750005e.png)

If I click on the right (west) of the anti-meridian things I'm unable to pick features
![AntiMeridian](https://user-images.githubusercontent.com/6735870/59570732-1885b280-90e0-11e9-8c68-4e279eff0f41.png)

If I zoom in a few zoom levels and pan across the anti-meridian then clicking works again.

Clicking appears to work fine in 3D mode.

**Comment by soyarsauce** [comment]
FYI to reproduce this,

Add this to your regionMapping.json as a key under `regionWmsMap`
```
        "SPC_EEC_NAME": {
          "layerName": "SPC_EEC",
          "server": "https://tile-test.terria.io/SPC_EEC/{z}/{x}/{y}.pbf",
          "serverType": "MVT",
          "serverMaxNativeZoom": 12,
          "serverMinZoom": 0,
          "serverMaxZoom": 28,
          "regionIdsFile": "/data/regionids/region_map-SPC_EEC_NAME_SPC_EEC.json",
          "regionProp": "country",
          "nameProp": "country",
          "aliases": [
            "coname",
            "CO_NAME",
            "country_name",
            "COUNTRY_NAME",
            "COUNTRY",
            "SPC_COUNTRY",
            "SPC_COUNTRY_NAME"
          ],
          "description": "SPC EEC by name",
          "bbox": [
            -179.9975,
            -30.930209,
            179.992727,
            23.774728
          ]
        }
```

Then the referenced file in `regionids` via `/data/regionids/region_map-SPC_EEC_NAME_SPC_EEC.json`:
```
{"layer":"SPC_EEC","property":"country","values":["American Samoa","Cook Islands","Fiji","Federated States of Micronesia","Guam","Kiribati (Gilbert)","Marshall Islands","Northern Mariana","New Caledonia","Nauru","Niue","French Polynesia","Papua New Guinea","Pitcairn","Palau","Solomon Islands","Tokelau","Tonga","Tuvalu","Vanuatu","Wallis and Futuna","Samoa"]}
```

Finally a CSV like below
```
SPC_COUNTRY_NAME,Value
Cook Islands,100
Vanuatu,200
```
