### ISSUE TITLE
Story: v1.1 - shortening url - error when sharing

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3510]
When a user tried to add 8 scenes to a story and share it, he got the following error: 
![short url error](https://user-images.githubusercontent.com/18452161/59645832-56a1d580-91b7-11e9-8813-7f095f1629a3.png)
 
upon investigation, it seems there is a bit of outstanding configuration that needs to be done for the URL shortening to work

**Comment by kring** [comment]
This is a guess, but I suspect we've hit the max size limit on the POST of the sharing data.

**Comment by kring** [comment]
We shouldn't remove the limit entirely, but we can e.g. double it.

**Comment by rowanwins** [comment]
Requires updating `terriajs` to using `terriajs-server@3.0.1`
