### ISSUE TITLE
Fix padding around preview map and "Add to the map" button on preview map

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#3516]
![image](https://user-images.githubusercontent.com/13863530/59729750-2f183f00-9283-11e9-8218-9737532ca460.png)

The button needs padding to the edge of the preview map. Consult with @philipgrimmett for exact amounts. The preview map should also potentially be full width, as it was before:
![image](https://user-images.githubusercontent.com/13863530/59729803-73a3da80-9283-11e9-80aa-197c06383554.png)

**Comment by philipgrimmett** [comment]
@steve9164 when in doubt, default to multiples of 8px. In this case it should probably have a margin mirroring 'data preview', so `margin: 8px, 8px, 0, 0`.

Re. map margin: I'll post an update layout soon that has similar spacing to your first screenshot, so probably fine to leave as is for the moment.

**Comment by rowanwins** [comment]
Now resolved in mobx

![Resolved](https://user-images.githubusercontent.com/6735870/71793712-1d1cb300-3092-11ea-9297-3e23d1c1774d.png)
