### ISSUE TITLE
Story: v2.0 - error preserving the style when story is shared

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3535]
User feedback: with the way layers are being rendered in stories:
I've just set up a story with a Sentinel 2 NRT image as the underlay in true colour, and another copy of the layer overlaid on top with a water index style (MNDWI). When I view these layers in National Map, I as expected get blue water visualised on top of the true colour imagery.
However, when I click "view story", the resulting layers are rendered only in true colour, with the top MNDWI layer either not being rendered, or being rendered in the incorrect order (i.e. under the true colour layer). 
Here's the story I have been producing:
https://nationalmap.gov.au/#share=s-hfVtOJn7WoZVz057CEPJKEKvPkc

Observations: 
- when initially clicking on share / story, the blue styling (Index style MNDVI) is available, as pictured below: 
![image](https://user-images.githubusercontent.com/18452161/60070055-a1dc5b00-9758-11e9-963d-8b9b7e911bb2.png)

- when you click to accept viewing the story, and the first scene appears, the blue styling is again available:
![image](https://user-images.githubusercontent.com/18452161/60070161-fda6e400-9758-11e9-9e35-473b9da2d459.png)

- when you click on the story play, and come back to initial scene, the blue styling disappears, and the Sentinel data is viewed in a true colour styling; while changing the scenes, the blue styling appears shortly and dissapears again 
![image](https://user-images.githubusercontent.com/18452161/60070120-dbad6180-9758-11e9-91a0-03fe96363ba4.png)

**Comment by kring** [comment]
The work in `mobx` will definitely fix this "for free", but it's worth a bit of investigation to see what's going on here. It may be a simple fix.

**Comment by chloeleichen** [comment]
Issues: 
1. There are some inconsistency between nowviewingIndex and what's shown on the map.
2. When activate story the viewer always gets updated even when it shouldn't.

**Comment by na9da** [comment]
I think we can close this issue as it is mostly a v7 bug. v8 works differently and does not have a `nowViewingIndex` state. The original share link is also not working as intended.

I tried to partially re-create the original story for v8 and couldn't repro the bug - https://beta.nationalmap.terria.io/#share=s-jACSBdLxQEV6n0vrpHf5oIA8SsR
