### ISSUE TITLE
Story v2.0 - Saving by sharing

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#3539]
**Feedback 1**
> it's not intuitive that once you leave the app, if users haven't shared the story they created, they will loose the story.

**Feedback 2**
> Just some feedback on usability: when I first tried the tool out, I couldn't find any way to save or share the "story", and assumed that the tool was simply in progress and sharing functionality would be added later. It was then pointed out to me that you can indeed share a "story" using the standard "Share / print" button.
>
> While this is great, I feel that in time it might be valuable to include an obvious "Share story" button at the bottom of the "story" panel, or at the end of the "Play Story" sequence, even if the button effectively did the same thing as the current "Share / Print" button. This would make the tool a lot more intuitive to use!

Sharing is the critical path for Stories. We should be proactive in nudging story authors to share their work, firstly to ensure share links are documented somewhere  and secondly to promote the Story feature itself.

**Comment by AnaBelgun** [comment]
another recent user comment: it is not very clear that you have to use the share function to "save" the story; there is no prompt / warning that you might lose the story /draft scenes if you don't save by sharing it to yourself (saving the share url by emailing etc.)

**Comment by philipgrimmett** [comment]
To review/critique:
https://invis.io/43RSPX2U5JD#/351585925_story_Prompt
