### ISSUE TITLE
Crash when changing SDMX concepts with feature info open

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#3543]
1. In NationalMap, add National Datasets -> Social and Economic -> Census -> Dwelling -> Number of Persons and Number of Bedrooms -> Over time -> By Local Government Area (NationalMap share link: https://nationalmap.gov.au/#share=s-wihg1AcmOflI1O5OQhACsA8VHQV, ci.terria.io share link: http://ci.terria.io/master/#share=s-agBb4XneJOcTQULqEQXoiivoj0V)
2. Click a region to bring up the feature info.
3. Expand "Number of Persons Usually Resident" on the workbench and choose any option.

Terria will crash with a white screen.

![image](https://user-images.githubusercontent.com/924374/60140170-229c6500-97f4-11e9-8b73-36a1c3a6177e.png)

**Comment by nf-s** [comment]
v7
