### ISSUE TITLE
Add support for time from Esri Map Services

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#3553]
Two ArGIS services that we don't seem to support any more/ever:

https://sampleserver5.arcgisonline.com/arcgis/rest/services/ScientificData/MODIS_Landcover/ImageServer

https://sampleserver3.arcgisonline.com/ArcGIS/rest/services/Petroleum/KSWells/MapServer

I believe both have the rarity of being ArcGIS services with a time dimension.

Since nobody else has complained this is probably low priority.

**Comment by rowanwins** [comment]
I can confirm that the first service doesn't work for me, it's an ImageServer, which is kind of a variant on a MapServer, specifically designed for raster data. Would be nice to add support for them, it may be that we can just add some tweaks to the existing `ArcGisMapServerCatalogItem` to get that to work, from memory the Esri API's are very similar.

The second service did work for me, it shows up some points over Kansas in the US. However the Terria interface didn't show anything about the time dimension.

**Comment by rowanwins** [comment]
Renaming this issue and focussing this issue on adding time support to Esri map services.

A map service has a `timeInfo` property, eg here
https://sampleserver3.arcgisonline.com/ArcGIS/rest/services/Petroleum/KSWells/MapServer?f=json&pretty=true
````
"timeInfo": {
    "timeExtent": [
          -2556057600000,
          1245283200000
      ],
      "timeReference": {
            "timeZone": "UTC",
            "respectsDaylightSaving": true
    }
}
````

See #1458 for supporting Esri Image Services

**Comment by rowanwins** [comment]
And the actual layer in the service also contains time info
https://sampleserver3.arcgisonline.com/ArcGIS/rest/services/Petroleum/KSWells/MapServer/0?f=json&pretty=true
````
timeInfo": {
       "startTimeField": "COMPLETION",
       "endTimeField": null,
       "trackIdField": null,
       "timeExtent": [
              -2556057600000,
               1245283200000
         ],
        "timeReference": null,
        "timeInterval": 3,
        "timeIntervalUnits": "esriTimeUnitsYears",
        "exportOptions": {
               "useTime": true,
               "timeDataCumulative": false,
               "timeOffset": null,
               "timeOffsetUnits": null
         }
},
````
