### ISSUE TITLE
Strange behaviour with chart button

### ISSUE THREAD

**Issue by rowanwins** [TerriaJS/terriajs#3565]
A user has noticed that if you have a time-enabled layer with region mapping some strange things can happen with the chart button in the workbench item.

In the initial state you're not able to click the chart button. However if you click a region and then bring up it's chart and then start clicking around on the time and chart buttons the chart button will toggle, even if you close the chart.

![ChartButton](https://user-images.githubusercontent.com/6735870/60567453-66234000-9dad-11e9-98c9-6728b609ea4a.png)

![ChartActive](https://user-images.githubusercontent.com/6735870/60567459-691e3080-9dad-11e9-8219-f088987ca93a.png)

I tried setting `isCsvForCharting: false` for the relevant catalog item however the button still appeared.

I'm not sure what the expected behaviour is.

**Comment by rowanwins** [comment]
From what I can tell the charting functionality is never relevant to the entire dataset, it is only relevant to a subset of data.  

For example when dealing with raster data (eg imagery) then a chart can only be generated for a particular pixel. To give a specific example - if we wanted to plot presence of water over years then a chart that can only be shown for given pixel as every pixel has a different history.

Similarly when dealing with vector data a chart is only relevant to particular features/geometries. In the current workflow when a chart is added for a feature then a new item is added to the workbench which allows toggling of the chart
![FeatureBased](https://user-images.githubusercontent.com/6735870/62014492-eab68200-b1e4-11e9-9ba5-0fb93b72bfc1.png)

I can't actually find a dataset which uses the chart button in a functional way.

So my proposal
1.  Remove the chart button from the workbench item
2. Investigate adding charts to the feature information panel for relevant imagery layers, specifically those that are derived products (eg the water index layer - NDWI)

What do you think @philipgrimmett ?

**Comment by LeoLym** [comment]
The 'show available times on chart' functionality was/is crucial for navigating temporally dense stacks of satellite imagery (especially now that the calendar date picker has been removed).

A bit distressing that this has propagated out onto NM rather than being caught in Terria sand box?

**Comment by AnaBelgun** [comment]
@LeoLym we need to better understand the problem here:
- the show available times on chart is and will still be available; this issue is related to the button on the workbench not in the feature info panel; the relationship between the two buttons needs to be fixed but there are no plans to remove the functionality
- the calendar date picker has not been removed and there are no plans to do so
- "propagated out onto NM rather than being caught in Terria sand box" - does that mean the bug with the chart button is now in NationalMap? if yes, NationalMap has been updated with latest version of TerriaJS (which may include bugs, such as this); when if fixed, it will be included in the regular app update

**Comment by rowanwins** [comment]
Have chatted a bit further with @philipgrimmett and he supplied the original design concept for why the button was there

https://invis.io/GHTBH7SWZMQ#/342726501_6

Basic summary is that it was designed to assist in showing which imagery was available at a given lat/lon

**Comment by rowanwins** [comment]
Okie dokie so some more digging on this
- On NationalMap I'm unable to get the desired behaviour to work (running TerriaJS v7.6.6)
- On TerriaCube it seems to work (running TerriaJS v7.6.2)

I've tried pulling in the same catalog config to both and the same result so I don't think it's a config thing.

![TerriaCube](https://user-images.githubusercontent.com/6735870/62665302-1a724080-b9c2-11e9-8a0c-af5df862568c.png)

There's nothing immediately obvious in the CHANGELOG.md so I'll need to do some digging

**Comment by rowanwins** [comment]
Actually having looked further the same thing can be achieved via NationalMap. The confusing thing is the workflow. 

The chart button against a time-enabled WMS only triggers if there is another layer which has a `tableStructure` - that seems to be the [critical component](https://github.com/TerriaJS/terriajs/blob/master/lib/ReactViewModels/ViewState.js#L138-L149)
