### ISSUE TITLE
Re-enable AR (developed initially for AREMI)

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3578]

**Comment by AnaBelgun** [comment]
@na9da it seems it was added in this version: https://github.com/TerriaJS/terriajs/blob/master/CHANGES.md#520

**Comment by na9da** [comment]
So I checked on map.terria.io & the aremi map and it seems to be working on both (on mobile devices). This feature works only in 3d mode, so you need to switch to 3d if the default mode is 2d. Then you will see the AR button at the bottom. 

This feature also requires the `experimentalFeatures` flag to be turned on in the config. This is off for some maps like nationalmap, so you wont find it there.

**Comment by na9da** [comment]
I had tested on Firefox mobile, which shows everything correctly. On Chrome for mobile, I just found, the whole row of tool buttons are outside the visible area. You also cannot scroll to it, because the map captures the scrolling. I'll look for a fix!

**Comment by na9da** [comment]
Related issue: #3595

**Comment by rowanwins** [comment]
Resolved
