### ISSUE TITLE
Workbench: 'style' select field is missing icon

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#3603]
https://nationalmap.gov.au/#share=s-nTd73y3vEAippJL2b4pTVWF0e0M

<img width="346" alt="Screen Shot 2019-07-18 at 3 44 44 pm" src="https://user-images.githubusercontent.com/5292858/61433444-a5898900-a976-11e9-949b-84321d1a13d4.png">

The style field also has inconsistent styling. See invision link below for corrections:
https://invis.io/CASND0RE5YT#/370254676_Delta_1

**Comment by rowanwins** [comment]
Closing in favour of #3709
