### ISSUE TITLE
Upgrade all maps to remove Data61 GNAF geocoder, then stop the service

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#3608]
See: #3607 

Maps to be upgraded (please expand list):

- [ ] NationalMap 

- [ ] AREMI staging

- [ ] AREMI

- [ ] InvestorMap staging

- [ ] InvestorMap

- [ ] DroughtMap

- [ ] pamthguord

- [ ] NSW digital twin

- [ ] NSDI 

- [ ] DE Australia

- [ ] DE Africa

- [ ] NEII

- [ ] ParlMap (need Pete)

- [ ] SoE

- [ ] TerriaCube

- [ ] map.terria.io

- [ ] ci.terria.io 

- [ ] Geoglam

- [ ] Global Risk Map - IAG (need Pete)

And finally:

- [ ] Stop the Data61 GNAF geocoder service

**Comment by meh9** [comment]
@AnaBelgun my list of maps to be upgraded is probably not complete?

**Comment by stevage** [comment]
What's the difference between this and #3607? They seem to say the same thing?

Also, what is the geocoder being replaced with in those maps?

**Comment by AnaBelgun** [comment]
Good question. It hasn't been actioned yet, since we haven't decided on a replacement.

**Comment by soyarsauce** [comment]
Thoughts are to keep it running till Dec
- don't support it in v8
- use some commercial option as a replacement - not a rush given we have bing+gazeteer


Things we lose if we remove gnaf geocoder
- csvs with addresses

**Comment by AnaBelgun** [comment]
@meh9 see the comment in this; we'll move it to product backlog until Dec 2020
