### ISSUE TITLE
Share - opening a shared url from a tab, throws an error message

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3614]
to replicate: 
- go to InvestorMap https://www.nationalmap.gov.au/investormap/
- go to Agriculture & Food tab, click on Share, and copy the link
![image](https://user-images.githubusercontent.com/18452161/61676410-25c93900-ad3f-11e9-96a5-ef387f07f319.png)
- open new tab and past the share link; error message below; once you click on ok, it will just work:
![image](https://user-images.githubusercontent.com/18452161/61676395-15b15980-ad3f-11e9-9b94-698a91b947ce.png)

No error messages shown when sharing from groups, subgroups, datasets.

**Comment by LeoLym** [comment]
This has a different manifestation when you share a 'split' service
![image](https://user-images.githubusercontent.com/37321366/62338870-66823880-b51d-11e9-9ad5-7df16bc6f486.png)

**Comment by tephenavies** [comment]
Hi @LeoLym. That sharing bug should be fixed in TerriaJS v7.6.7
