### ISSUE TITLE
Share - error message when sharing a web service (not in catalogue) link

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3629]
Steps to reproduce: 

- [ ] go to NationalMap

- [ ] click add my data button

- [ ] add this url: https://www.environment.gov.au/mapping/services/ogc_services/Natural_Resource_Management_Regions/MapServer/WMSServer
or this one: 
http://gaservices.ga.gov.au/site_1/services/Geomorphology_Environment_WM/MapServer/WMSServer?request=GetCapabilities&service=WMS

- [ ] go to share

- [ ] user gets this error message: 
![image](https://user-images.githubusercontent.com/18452161/62346942-55482480-b53b-11e9-8f7e-8270df15adbb.png)

**Comment by lpinner** [comment]
I ignored the warning message and tried a shared link and it works as expected.  e.g [https://www.nationalmap.gov.au/#share=s-layn3ASZwALPtoFEFoPUb089zLg](https://www.nationalmap.gov.au/#share=s-layn3ASZwALPtoFEFoPUb089zLg)

**Comment by AnaBelgun** [comment]
This is fixed by this pr: https://github.com/TerriaJS/terriajs/pull/3634
