### ISSUE TITLE
zoom to extent of all loaded data sets

### ISSUE THREAD

**Issue by bsimyo** [TerriaJS/terriajs#363]
At the moment, you can zoom to the extent of a specific dataset by clicking on the name.  Sometimes I have multiple data sets loaded and want to zoom to the extent of the full set of data sets loaded.  This would be useful.

**Comment by stevage** [comment]
Do we still want to do this? @kring ?

**Comment by kring** [comment]
I'm ok with closing it.  @bsimyo can reopen if he still thinks it would be valuable.
