### ISSUE TITLE
Charts - zoom into chart

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3639]
Users are frustrated when a chart is showing multiple lines representing satellite imagery availability and they cannot expand/zoom into a particular date range. 
Steps for https://terria-cube.terria.io/#share=s-vxcphiELlJ5rPOpmUxWeveuvILS: 
- go to https://terria-cube.terria.io/
- add water data: Water regulations data (BoM) - Hydrologic Reference Stations - Watercourse Discharge
- add satellite imagery: DEA Production - Sentinel-2 Definitive - Definitive Surface Reflectance (Sentinel 2A)
- select a water gauge - Cooper/CullyamurraWH (search in location) and a graph should be presented
- click Expand and new chart should be available 
- click "Show Definitive Surface reflectance (Sentinel2A)" button 
- in the workbench click the small chart button to show the lines when satellite imagery is available
- the lines are appearing clustered together at end of the chart 
- no way for the user to focus only on time range when the satellite images are available

![NEII fetaure issue chart](https://user-images.githubusercontent.com/18452161/62677089-5f14d080-b9f0-11e9-9180-bdd9721e54b8.png)

**Comment by AnaBelgun** [comment]
@philipgrimmett - design phase

**Comment by rowanwins** [comment]
Resolved by  #3645
