### ISSUE TITLE
Charts - difficulty to locate and understand point of intersection between chart and lines showing sat imagery

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3640]
Currently users have difficulty locating the exact point of intersection between chart and satellite imagery lines showing availability, and cannot understand the date range or exact date and time when a particular value was reached (in the case of water course level for example). 

Steps to reproduce:
https://terria-cube.terria.io/#share=s-frt2CLdnL3Wyv2FMUMWhNxFDMfT

- go to https://terria-cube.terria.io/
- add water data: Water regulations data (BoM) - Hydrologic Reference Stations - Watercourse Levels 
- add satellite imagery: DEA Production - Sentinel-2 Definitive - Definitive Surface Reflectance (Sentinel 2A and 2B combined)
- select a water gauge - Paroo_R Caiwarro (search in location) and a graph should be presented
- click Expand and new chart should be available
- click "Show Definitive Surface reflectance (Sentinel2A and 2B combined)" button
- in the workbench click the small chart button to show the lines when satellite imagery is available
- the lines are appearing clustered together at end of the chart
no way for the user to select the time/date when the chart appeared to have picked
- also, no way for the user to understand which line they have clicked (what time) 
![NEII feature issue chart dots](https://user-images.githubusercontent.com/18452161/62679620-6c35bd80-b9f8-11e9-9ca7-fc51e48c7a6f.png)

**Comment by AnaBelgun** [comment]
@philipgrimmett - design phase

**Comment by rowanwins** [comment]
If you click on a line representing the imagery date you should see the date of the imagery and have some way of indicating on the chart which imagery is selected (eg the line is highlighted)

**Comment by rowanwins** [comment]
Resolved by  #3645
