### ISSUE TITLE
Charts - labelling 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3641]
During user testing, when presented with a single expanded chart, participants were able to identify the parent feature title (Diamantina / Birdsville) but not the charted variable itself (Water course level daily average). 

Chart users should be able to identify at a glance where their data was captured (feature title) and what that data actually represents (feature variable). This information should be displayed directly above the chart to ensure a strong visual association is maintained. 

![NEII feature issue labels](https://user-images.githubusercontent.com/18452161/62680469-a7d18700-b9fa-11e9-82e9-6e633d25de19.png)

**Comment by AnaBelgun** [comment]
@philipgrimmett - design phase

**Comment by rowanwins** [comment]
Worth noting that this behaviour only happened when a single item was being charted, when a second item was charted the additional information was added.


![ChartItems](https://user-images.githubusercontent.com/6735870/62907120-12951080-bdb5-11e9-8d4f-8c21dba96cf5.png)

Resolved in #3645
