### ISSUE TITLE
Display 'export' on UI without having to specify `linkedWcsUrl`

### ISSUE THREAD

**Issue by rowanwins** [TerriaJS/terriajs#3643]
Currently to display the export button (via a WCS request) someone needs to have specified a `linkedWcsUrl` on their `WebMapServiceCatalogItem` - however it looks like we're pulling back that information via the `DescribeLayer` request anyway, so perhaps we can do away with that config and just offer the export whenever we find the linked WCS?

**Comment by hardreddata** [comment]
At the risk of complicating things, there is an interesting new GeoServer extension which offers similar functionality to WCS.

http://geoserver.org/announcements/2021/03/04/geoserver-2-19-rc-released.html

https://docs.geoserver.org/latest/en/user/extensions/wps-download/index.html

My note would probably be better in https://github.com/TerriaJS/terriajs/issues/3597 but it was closed. Also https://github.com/TerriaJS/terriajs/issues/4843 on topic.

I get that requiring a GeoServer extension isn't very _standard_ but I think probably more mainstream than a bespoke PyWPS process. I also get you are busy rolling out v8.

**Comment by nf-s** [comment]
We now have `WebMapServiceCatalogGroup.perLayerLinkedWcs` - added in https://github.com/TerriaJS/terriajs/pull/6108

Add `WebMapServiceCatalogGroup.perLayerLinkedWcs`, this can be used to enable `ExportWebCoverageService` for **all** WMS layers. `item.linkedWcsCoverage` will be set to the WMS layer `Name`

I'm going to close this. At some point we may investigate adding WCS `GetCapaiblities` to match WMS layers with WCS coverages
