### ISSUE TITLE
Design and develop generic login UI

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3644]
To prepare for integration the authentication & authorisation work, we need a login in terria ui.

**Comment by philipgrimmett** [comment]
Invision prototype:
https://invis.io/PRTEOSJTAKG#/378489622_login-Default

Note:
- Form validation behaviour
- Password 'show/hide' toggle
- Password reset option (needs investigation, @AnaBelgun we can write the ticket together?)
- Example OAuth login options (Google, ESRI)

**Comment by rowanwins** [comment]
@philipgrimmett 

Here is what an Esri OAuth powered page looks like - basically you click the "Sign In" button and it throws another window which we have next to no styling control over.
https://esri.github.io/esri-leaflet/examples/arcgis-online-auth.html

So in its most minimal implementation we just need a button to throw a window.

Hope that helps :)

**Comment by philipgrimmett** [comment]
@rowanwins ah, thanks. In the prototype posted above I included oath buttons for google and Esri, but now I see that the Esri login UI also has oath buttons (FB, Google). Will they still lead users back to the Terrace editor?

**Comment by soyarsauce** [comment]
FWIW I'm also leaving this till the end - right now we have super basic auth going by logging into google (without the UI)

**Comment by soyarsauce** [comment]
https://github.com/TerriaJS/terrace/issues/50

**Comment by rowanwins** [comment]
Hey @philipgrimmett 

So I was coming at this from the Terria side rather than the Terrace side. I'm thinking of the average user of the digital twin who has no interest in Terrace. So perhaps I was coming from a different angle.

**Comment by techdragon** [comment]
While I’m not exactly a core stakeholder as I’ve only just started to use Terria, I was surprised by the lack of any auth beyond basic auth.

Looking at this ticket, I’d like to point out the broader utility of OpenID Connect over directly using OAuth. Supporting OIDC would make user auth a _nearly_ plug and play experience for people who’s infrastructure supports it already. The OIDC components of Terria would just need to be configured to use their OIDC provider much like how they would configure the Cesium Ion API Token.

**Comment by rowanwins** [comment]
I think this can be closed - overtaken by events

**Comment by davidedelerma** [comment]
@rowanwins  could you explain more what overtaken by events mean? Will Terria have the capability of having a login page and eventually RBAC any time soon? Thanks
If there is already some form of auth could you point me to the doc as I cannot find it ?

**Comment by rowanwins** [comment]
Hi @davidedelerma ,

So far we've only implemented this in a private clone of TerriaMap (eg the code is not available), although the app is available here
https://nsw.digitaltwin.terria.io/

I suspect it's going to be hard to have a generic login provider within TerriaJS or TerriaMap, but in terms of the UI idea you're free to steal it.

Hope that helps
