### ISSUE TITLE
Change detection functionality - design prototype 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3668]

**Comment by AnaBelgun** [comment]
Any invision prototype available @philipgrimmett

**Comment by philipgrimmett** [comment]
### Invision prototype
https://invis.io/UBUCV5J2QDX#/388439447_Delta_1

### To discuss
- The current workflow requires users to manually select a location of interest (lat/lon) to see available imagery dates (dates that intersect with the selected lat/lon). It may not be entirely clear to users why this input is required.
- Displaying NDVI difference maps with the same colour ramp as a standard NDVI snapshot may be confusing for users (testing required)

**Comment by AnaBelgun** [comment]
done
