### ISSUE TITLE
Change detection - new parameters

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3669]
investigate what parameters will be passed by the newly developed delta service (GSKY)

**Comment by na9da** [comment]
From Edison on slack:
> the input parameters are the same wms parameters sent from WebMapServiceCatalogItem except that the time parameter will become datetime1,datetime2 (i.e. comma separated datetime values). The response is just a png image for each tile request.

**Comment by na9da** [comment]
Closing.
