### ISSUE TITLE
Model Architecture: WMS CatalogGroup - nested wms group layers don't show up

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#3674]
If you set up a catalog with the two WMS servers:
https://programs.communications.gov.au/geoserver/ows
https://ows.services.dea.ga.gov.au/

The first will load, the second will load but not show the nested layers
![image](https://user-images.githubusercontent.com/9134432/63919670-907a3c80-ca82-11e9-98a4-ebf9b8048db5.png)

**Comment by nf-s** [comment]
~I am able to load multiple `wms-group` items, but I am unable to load `https://ows.services.dea.ga.gov.au/`.~

~Either there is something wrong with `https://ows.services.dea.ga.gov.au/` or we aren't loading their `GetCapabilities` correctly~

I misunderstood the problem, it only has **nested** `wms-group` items...

**Comment by AnaBelgun** [comment]
is this the same problem https://github.com/TerriaJS/de-australia-map/issues/53

**Comment by nf-s** [comment]
Yep #4555  should fix that
