### ISSUE TITLE
Model Architecture: Feature highlighting shouldn't require direct changes to Cesium/Leaflet state

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#3684]
Currently feature highlights are implemented by directly accessing and modifying internal Cesium and Leaflet properties from GlobeOrMap. While those are public, it would be better to implement feature highlighting in the Cesium and Leaflet classes using observables.

**Comment by kring** [comment]
The changes _may_ be getting overwritten when the state changes later, e.g. when a new imagery layer is added.

**Comment by nf-s** [comment]
I don't believe this is the case anymore
