### ISSUE TITLE
Weird text wrapping in Now Viewing

### ISSUE THREAD

**Issue by hilarycinis** [TerriaJS/terriajs#369]
During testing there was a reoccuring bug, where the text moves under the check box.

more than 1 data set loaded
user toggling data sets on and off to help understand layered data sets

See example

![screen shot 2014-09-26 at 3 57 11 pm](https://cloud.githubusercontent.com/assets/6046521/4416469/0db88aa6-4542-11e4-872d-73423c98f2d6.png)

**Comment by kring** [comment]
Fixed in new UI.
