### ISSUE TITLE
Carrying over a filtered list to a split window

### ISSUE THREAD

**Issue by LeoLym** [TerriaJS/terriajs#3698]
When you've filtered a sparse dataset like Landsat or Sentinel using the 'filter by location' button and then 'split' the window so that you can compare to different periods in time for that location, the split window doesn't 'remember' the filtered list and you have to repeat the filtering process

**Comment by rowanwins** [comment]
Thanks @LeoLym , we've already got an issue listed for this over at #3596 so I'm going to close this but will assign it to myself for the next sprint
