### ISSUE TITLE
Add data panel needs to be revealed when activated

### ISSUE THREAD

**Issue by hilarycinis** [TerriaJS/terriajs#370]
When "Add data" panel opened, panel needs to auto scroll or reset to the bottom so this functionality is revealed. 

Data set panel is open 
User opens "Add data"
Screen doesn't show as open as scroll bar stays in place.

During testing users didnt see the panel was opened and overlooked the capacity to add a data set in this component.

This is the view that is returned when initially opened.

![screen shot 2014-09-26 at 4 03 52 pm](https://cloud.githubusercontent.com/assets/6046521/4416515/f01551d6-4542-11e4-92ee-0370bedb13ea.png)

**Comment by kring** [comment]
N/A in new UI.
