### ISSUE TITLE
Time-varying CSV errors if date does not vary

### ISSUE THREAD

**Issue by maxious** [TerriaJS/terriajs#3701]
Trying to load Time-varying CSV errors out `TypeError: Cannot read property 'dayNumber' of undefined` and the map is not displayed if the date value does not vary throughout the file:
![image](https://user-images.githubusercontent.com/81432/65293639-437c1880-db9f-11e9-92b9-62ce8a9fc81f.png)

Working CSV (these electorates are in south-west Sydney if you need to zoom in):
```csv
date,ced_code_2018,metric
2019-03,101,1
2019-03,102,2
2019-02,103,3
```
Not working CSV:
```csv
date,ced_code_2018,metric
2019-03,101,1
2019-03,102,2
2019-03,103,3
```

**Comment by rowanwins** [comment]
Thanks for the report @maxious - will investigate

**Comment by yohannist** [comment]
> Thanks for the report @maxious - will investigate

Any progress on this?

**Comment by nf-s** [comment]
Fixed in version 8 

http://ci.terria.io/main/#clean&https://gist.githubusercontent.com/nf-s/6d9dcfae0017425363a812cca23cbab6/raw/1cfe143241028ea5aded80e1d264e92707aa682a/csv-single-date.json&share=s-tLo5kF3GHCFPpCBdAj0o43ix39S
