### ISSUE TITLE
"Add data" reworded to "Explore data" 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3707]
Based on discussions here: https://docs.google.com/document/d/1Y7Z1EwwkzuBrOgrqowxauJ0-p4v70oVGyoDztOSwoUY/edit and previous user feedback, we should consider changing 
Add Data to Explore Data and reflect that in the workbench tip text: 

_Click 'Explore data' above to:_

- _browse the Data Catalogue_

- _add your data to the map_

TIP: All your selected data sets will be listed here

**Comment by AnaBelgun** [comment]
@kring The wording change when done needs to go into master so all apps will have it when a new version is released

**Comment by AnaBelgun** [comment]
to start with DE Africa and DE australia

**Comment by AnaBelgun** [comment]
rewording of the workbench underneath Explore data: 
![workbench rewording](https://user-images.githubusercontent.com/18452161/67356357-a6e5d580-f5a5-11e9-817c-a139e6b69eb9.jpg)

**Comment by rowanwins** [comment]
@kring - what's your thoughts on implementing some sort of basic language file approach where we provide sensible defaults but allow overriding through configuration? We could start with very lightweight implementation for just a few key spots in the app and slow expand it out?

**Comment by rowanwins** [comment]
Done in #3742
