### ISSUE TITLE
Improve user workbench guidance/interaction when selecting Satellite Imagery data 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3708]
It has been observed that users needs more help when working with timeseries data, especially with satellite imagery. 
Some options discussed (after data is selected and in the workbench): 
- have a tool guide flag similar to the story pop up, which can be disabled once users are comfortable
- stepping the user through the process - have numbered tool tips for each of the steps (e.g. 1.filter by location; 2. click here to select time/date; 3. zoom in etc etc)

**Comment by philipgrimmett** [comment]
### Invision prototype
https://invis.io/VBU3RMCRCSP#/385611997_Tour_1

### Steps for QA (updated 22 Oct)
1. Click centre of screen to launch intro modal (should launch automatically once the map UI has loaded)
2. Click 'Explore data'
3. Click 'Satellite Imagery' > 'Add to map'
4. Click button centre link to launch satellite guide modal (should launch automatically after satellite imagery is added for the first time)
5. Click through guide, then click 'Got it, thanks' to dismiss modal

**Note**
When the satellite guide is dismissed for the first time, show a popover near the 'Help' button with the following text:

>You can access map guides at any time by looking in the **help menu**.

### Screenshot
<img width="515" alt="Screen Shot 2019-10-22 at 11 45 41 am" src="https://user-images.githubusercontent.com/5292858/67253092-af64e000-f4c1-11e9-8fc9-0f2ddd9ccbd9.png">

**Comment by AnaBelgun** [comment]
First implementation of the user guide will be done (in this priority order):

- [x] DE Africa

- [x] DE Australia

- [ ] TerriaCube

- [ ] NationalMap

**Comment by AnaBelgun** [comment]
added to DE aus and DE afr
