### ISSUE TITLE
Fix selecting style - add drop down

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3709]
Currently when a dataset with different styles is selected, it is not intuitive that multiple styles are available. Only when you click on the text in the Style box, users are presented with the list. 
Users could be presented with a drop/down arrow/other tool to understand there is a selection. 

Check this example: https://nationalmap.gov.au/#share=s-hxVJI9RUbTD7d9nRL1POGSmst6U
![image](https://user-images.githubusercontent.com/18452161/65576865-16bc6c80-dfb6-11e9-9de9-9ae24b7ea15b.png)

**Comment by philipgrimmett** [comment]
Screenshot for reference:
<img width="536" alt="Screen Shot 2019-09-30 at 12 02 13 pm" src="https://user-images.githubusercontent.com/5292858/65844581-39fe6780-e37a-11e9-8625-a1ff6921e549.png">

**Comment by rowanwins** [comment]
Can you design an open state for us @philipgrimmett ? 

We should be able to hook into the dropdown component that we use for the add data panel (and in one or two other places).

**Comment by AnaBelgun** [comment]
@philipgrimmett
