### ISSUE TITLE
Error modal hidden by catalog explorer panel

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#3716]
This is especially bad when there's an error adding data by URL. The error message is hidden behind the explorer panel, which shows that the added data item is still loading:
![](https://media.giphy.com/media/SYdjYmRa9vw7E57b6J/giphy.gif)

Possibly broken by dynamic Z index changes. The error modal should be above any other elements.

**Comment by nf-s** [comment]
Fixed

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/6187649/175280963-2a283454-6463-4759-b7ab-e5ca8a7679b5.png">
