### ISSUE TITLE
Model architecture: ShareDataService doesn't use config.json's shareUrl

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#3723]
As in #2323, this is caused by ShareDataService being created before config.json is read.

**Comment by mgcsls** [comment]
@steve9164 I can't seem to reproduce the issue, can you check if it has possibly already been fixed? I'm not sure if I am misinterpreting something.

**Comment by tephenavies** [comment]
Hmm, looks like this was fixed in https://github.com/TerriaJS/terriajs/pull/3523. I must have come across this bug just before Kevin fixed it, then only posted the bug a few months afterwards.
