### ISSUE TITLE
Splitter to allow comparison between 2 datasets at different zoom levels

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3732]
Currently the splitter allows comparisons between (timeseries) datasets at the same zoom level. 
Some users would like to compare same or different datasets at different zoom levels. 
For example in the case of [PacificMap](http://pacificmap.terria.io/) where users can access boundaries for all the islands in the region, due to different methods for visualising those boundaries (e.g. with or without buffers), it will be useful to allow to visualise the same region /country zoomed in at the lowest possible admin boundary while having the whole region/group of islands/island visibility.

**Comment by rowanwins** [comment]
I'm not sure this is so much about the spitter as about having two maps side-by-side that can be moved independently.

**Comment by rowanwins** [comment]
Going to close because I can't see this ever happening
