### ISSUE TITLE
Terria whitescreens when changing concepts while feature info with a chart is open

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#3738]
* Visit https://nationalmap.gov.au
* Add National Datasets -> Social and Economic -> Census -> Dwelling -> Household Composition -> Over time -> By Local Government Area
* Click a region with data to bring up feature info (make sure there's a chart shown on the feature info panel)
* In the workbench, click "Dwelling Structure", then click "Separate House".

After loading for a moment, Terria will crash with a whitescreen.

**Comment by kring** [comment]
![image](https://user-images.githubusercontent.com/924374/67272459-50768980-f508-11e9-952e-16abf6fe4d6d.png)

**Comment by kring** [comment]
Use http://ci.terria.io/master/#clean&http://static.nationalmap.nicta.com.au/init/2019-08-14.json instead of nationalmap.gov.au for debugging.

**Comment by nf-s** [comment]
v7
