### ISSUE TITLE
Cloudfront - Chrome SPDY error

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3744]
This bug ticket is ported from TerriaCube where it was first discovered. 

Error message: ERR_SPDY_SERVER_REFUSED_STREAM 

to test: 
- go to terria cube app https://terria-cube.terria.io/
- go to DEA Production, Near real time, Sentinel 2A - https://terria-cube.terria.io/#share=s-2fAVZ6zGV3KUus4DPSyPonNERPK
- error message 
![image](https://user-images.githubusercontent.com/18452161/65005836-98702280-d944-11e9-8681-7d1f7b70a38e.png)
- and in console: 
![image](https://user-images.githubusercontent.com/18452161/65005854-aaea5c00-d944-11e9-9a8b-7157242c3cb6.png)

- terriaCube has Cloudfront
- same data services (https://nationalmap.gov.au/#share=s-7J1ezmmIYhns1wF1tWdlfrzN7Hr), from same stack (https://ows.services.dea.ga.gov.au), do not present this error in NationalMap, where Cloudfront is not applied (to double check because at the time of filing this bug, this is what the console had: 
![image](https://user-images.githubusercontent.com/18452161/65006083-67442200-d945-11e9-8b5a-3a0f21dbb144.png)

**Comment by AnaBelgun** [comment]
PR for handling the error (which doesn't solve the underlying problem): https://github.com/TerriaJS/terriajs/pull/3706

**Comment by AnaBelgun** [comment]
response from Cloudfront: 
The client browser is observing error "ERR_HTTP2_SERVER_REFUSED_STREAM" for the application hosted in CloudFront "https://terria-cube.terria.io/#share=s-zVC2mGEZCdM4icB2lA86tV8YZVg".
Upon investigation and as per RFC,A peer can limit the number of concurrently active streams using the SETTINGS_MAX_CONCURRENT_STREAMS parameter within a SETTINGS frame. Here server specified the maximum number of concurrent streams the client can initiate. Client MUST NOT exceed the limit set by their peer. An endpoint that receives a HEADERS frame that causes its advertised concurrent stream limit to be exceeded MUST treat this as a stream error of type PROTOCOL_ERROR or REFUSED_STREAM.
https://tools.ietf.org/html/rfc7540#page-22
Here, I believe by initiating multiple request from Chrome will initiates multiple HTTP streams which exceeds the allowed limit.
However to confirm this behaviour and to check if CloudFront Edge server has set any Hard limit for "maximum allowed HTTP2 stream" per TCP connection, this has been escalated to another CloudFront team.

**Comment by AnaBelgun** [comment]
Comment from Terria:
We investigated that the server isn't setting a SETTINGS_MAX_CONCURRENT_STREAMS so it's staying at the default (infinite). If it were setting such a limit and that was the cause of the problem, it would imply that both Chrome and Firefox have a bug causing them to not honor that limit. Not very likely.

**Comment by rowanwins** [comment]
We've made a number of changes to try and get around this...

- #3740 provided an option to set an updateInterval property for ImageryLayerCatalogItems which helps when rapidly changing dates on a WMS, basically it's a debounce style redrawing now.

- #3706 rejigged the handling of tileError counts to include the time param which makes the service a little less sensitive.

**Comment by AnaBelgun** [comment]
reopening this issue
