### ISSUE TITLE
kml raster tiles

### ISSUE THREAD

**Issue by DSpada** [TerriaJS/terriajs#3753]
Hi, I'm trying to import KML raster tiles generated with gdal2tiles.py, but it seem that TerriaMap doesn't supprt this tiles.
Are you going to develop in this matter or have you any advice for import these tiles?
Thank you,

**Comment by rowanwins** [comment]
Hi @DSpada 

What do you mean import? I gather gdal2tiles.py will give you a directory of tiles which you then need to serve via some mechanism. Do you have them available via any endpoint that we can look at?

Thanks

**Comment by DSpada** [comment]
Hi @rowanwins,

with Import I mean load local data. 
Because I don't have web service to share this tiles and I thought that if TerriaJS can upload local kml vectorial files it could also load and manage local raster tiles in kml format.

**Comment by rowanwins** [comment]
Hi @DSpada 

Cesium doesn't support KML SuperOverlays, which is what I think gdal2tiles is generating. Unfortunately the KML spec is very extensive and so supporting every corner of it is quite a difficult task, there is a [ticket here](https://github.com/AnalyticalGraphicsInc/cesium/issues/873) where the Cesium team list what parts of the KML spec is supported.

Hope that helps

**Comment by DSpada** [comment]
Hi @rowanwins,
I understand. I'll read the documentation.
Thank you for your help in this matter.
