### ISSUE TITLE
Add support for retrieve high resolution exports from WCS

### ISSUE THREAD

**Issue by rowanwins** [TerriaJS/terriajs#3765]
Currently WCS exports are done based on the width and height of the current map (eg 1000px by 600px )and resulting images don't represent the full resolution.

Instead of passing `width` and `height` parameters to the `GetCoverage` request we can send `resx` and `resy` specifying the required resolution, this is sent in decimal degrees. 
````
https://ows.dea.ga.gov.au/?service=WCS
&request=GetCoverage
&version=1.0.0
&format=GeoTIFF
&crs=EPSG%3A4326
&resx=0.0001&resy=0.0001
&coverage=s2_ard_granule_nbar_t
&bbox=121.89074847916314,-17.99554269281186,122.57921195492706,-17.629104173950257&time=2019-10-06T00%3A00%3A00.000Z&styles=infrared_green
````

Alternatively you can swap things across to Web Mercator 
````
https://ows.dea.ga.gov.au/?service=WCS
&request=GetCoverage
&version=1.0.0
&format=GeoTIFF
&crs=EPSG:3857      <---- set me to web mercator
&resx=10&resy=10    <---- set me a sensible resolution
&coverage=s2_ard_granule_nbar_t
&bbox=13568816.053,-2037026.831,13645455.457,-1994181.130 <---- set bbox to web mercator
&time=2019-10-06T00%3A00%3A00.000Z
&styles=infrared_green
````

I think the later is preferable

**Comment by rowanwins** [comment]
Also noted here
https://github.com/TerriaJS/terriajs/issues/3109#issuecomment-427740526

**Comment by nf-s** [comment]
No longer relevant
