### ISSUE TITLE
Triage Google Analytics event trackers

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#3770]
@AnaBelgun @marietruelove @alyce @soyarsauce 

To better understand how users are interacting (or not interacting) with Terria maps (outside of usability testing), it's probably worth taking some time to review/update our product goals, signals, and measures (https://www.atlassian.com/team-playbook/plays/goals-signals-measures)

As prep, I've put together a rough (incomplete) list of trackable click events in Terria:

_*% typically means 'percentage of total sessions where user clicked on [component]'_

### Data panel
- [ ] % Brand image / link
- [ ] % Explore data button
- [ ] % My Data button
- [ ] % Hide workbench
- [ ] % Reveal workbench

### Data panel: search
- [ ] % Search field focus
  - [ ] % Text entered into search field  (value not captured)
  - [ ] % Clear button
- [ ] % done button (exiting search)

### Data panel: empty
- [ ] % explore data link
- [ ] % tour the map link

### Data panel: workbench items
- [ ] % DragDrop reorder
- [ ] % remove all
- [ ] % disable item
- [ ] % action: about this data
- [ ] % action: zoom to
- [ ] % action: split
- [ ] % action: export
- [ ] % action: remove

### Data catalogue
- [ ] Bounce rate (exit modal before accessing dataset preview)
- [ ] % dataset share link

### Data catalogue: search
- [ ] % search field focus
  - [ ] % text entered into search field  (value not captured)
  - [ ] % clear button

### My Data
- [ ] % My Data tab from data catalogue
- [ ] % drag drop a file (successful vs unsuccessful?)

### Map settings / navigation buttons
 - [ ] % map settings button
  - [ ] % change default map view (3D terrain, 3D smooth, 2D)
  - [ ] % change default base map
  - [ ] % change default raster map quality
- [ ] % share / print button **!!!**
  - [ ]  % share URL: copy button
  - [ ]  % print button
  - [ ]  % print preview button
- [ ] % related maps button
- [ ] % about button

### Map controls
- [ ] % Compass (outer ring)
- [ ] % Gyroscope (inner button/control)
- [ ] % Zoom in/out
- [ ] % Zoom reset
- [ ] % Geolocation
- [ ] % Splitter
  - [ ] % splitter disabled
- [ ] % Mr. Mustachio (measure)
- [ ] % Lat/Lon - zone S, E, N

### Charts
- [ ] chartable items: % expand/open chart from feature info
  - [ ] % zoom in/out on chart
  - [ ] % download button

### Story panel
- [ ] % Story button
  - [ ] % Bounce rate
  - [ ] % 'Getting started' video
  - [ ] # capture >0 scenes + share
  - [ ] % remove all
  - [ ] % capture >0 scenes
    - [ ] % play story button
    - [ ] % launch scene menu
      - [ ] % Edit scene 
  - [ ] Avg. # scenes captured per session

### Feedback
- [ ] % feedback pop-up triggered
  - [ ] % 'share my map view with MapTitle developers' disabled
  - [ ] % send button
  - [ ] % cancel button

### Errors thrown
- [ ] Total # errors thrown
- [ ] % sessions where >0 error thrown
- [ ] Avg. # errors thrown per session
- [ ] Errors thrown by type

**Comment by AnaBelgun** [comment]
replaced by https://github.com/TerriaJS/product/issues/232
