### ISSUE TITLE
Internationalization of terria

### ISSUE THREAD

**Issue by zoran995** [TerriaJS/terriajs#3785]
Starting this so we can track work on internationalization of app, hope it is ok

**Comment by zoran995** [comment]
@rowanwins and @soyarsauce How we should proceed with data in `defaults.jsx`? I am not sure is it possible to keep it as it is with `i18next`

**Comment by soyarsauce** [comment]
We should continue the rest of the internationalisation efforts in the work done through https://github.com/TerriaJS/terriajs/pull/3787, and stop using `defaults.jsx` for i18n - however it could still be useful for defining other ways to extend terria (see https://github.com/TerriaJS/de-australia-map/pull/29/files#diff-e7c237f2b6a10131a063f7b5740c39aaR5)

**Comment by zoran995** [comment]
I will post some questions:
- language switch:

    - Where should we put a button for users to switch languages of the map in the `TerriaMap` or `TerriaJS`? The user should have an option to define languages that he want to enable. The switcher should not be visible by default if there is only one language in the `Language` folder.
    - From the design perspective dropdown or something else, and where to position it? 
    - Should we show the country flag next to language name (if yes then user should also have option to choose that)? 
- should we split `translation.json` file to multiple parts to separate ReactViews translation from the rest (`core`, `models` and `map` which are biger groups in the `translation.json`)
