### ISSUE TITLE
v7.9 clicking on empty map should prompt to explore data

### ISSUE THREAD

**Issue by hardreddata** [TerriaJS/terriajs#3803]
When clicking on an empty map the pop up says

Feature Information
Click 'Add Data' to add data to the map.

But the button down the left side is now 'explore data'.

**Comment by zoran995** [comment]
Name of the button should be pulled from `defaults.jsx`, but it will be removed with extended support for `i18next` (I hope all `ReactViews` elements will be translated during next week) check the #3785#issuecomment-557305148

**Comment by hardreddata** [comment]
Closed because I think dupe https://github.com/TerriaJS/terriajs/issues/3914
