### ISSUE TITLE
Ability to resize images in Story text

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#3828]
At the moment we have no control of the size of images in Story text. We should enable control of the size of the image.

**Comment by philipgrimmett** [comment]
Before introducing manual resizing we should probably set a default height for story images no larger than the max viewing height of the story panel body ie. visitors should be able to see the whole picture without scrolling. Less ideal for portrait images, so I think should we also treat story images like workbench legends and allow users to open them in a new tab at their original size. Happy to weigh in on WYSIWYG editors if that helps.

**Comment by staffordsmith83** [comment]
Hi @philipgrimmett, after trying out a few Ive settled on using TinyMCE https://github.com/tinymce/tinymce-react, thoughts on that? I initially wanted to use Quill but had some compatibility issues.  
![image](https://user-images.githubusercontent.com/7980991/169240237-cef2a4b2-f1f6-40c1-99d5-ec02c870c038.png)
 This will allow user to specify dimensions on load, or manually resize with drag handles.
 Ill see about customising it to set a max image height. Perhaps something like [this](https://stackoverflow.com/questions/49301891/tinymce-image-plugin-default-dimensions).

**Comment by philipgrimmett** [comment]
Hmm, I think asking users to manually specify width/height before actually seeing the embedded image kinda defeats the purpose of a WYSIWYG editor. Is it possible to hide the width/height option, embed at a default height, then drag to scale up/down?

**Comment by staffordsmith83** [comment]
Yes thats possible! The width and height boxes are prefilled when you specify an image URL, so it makes a bit more sense when you see that in action. But Ill try to implement your suggestion!
