### ISSUE TITLE
Add point and polyline support for mapbox vector tile items using a library

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#3846]
Currently Terria only supports Polygons through `MapboxVectorTileImageryProvider.js` but now that we allow adding a catalog item with type "mvt" we should expand support.

**Comment by AnaBelgun** [comment]
to discuss complexity in sprint

**Comment by tephenavies** [comment]
I've prototyped this for points:
![image](https://user-images.githubusercontent.com/13863530/107468247-c0a49500-6bbb-11eb-9807-b6c395d60921.png)

Unfortunately my approach has drawbacks for points. E.g. zooming in leads to artifacts (see to the left and below the point):
![image](https://user-images.githubusercontent.com/13863530/107468335-e2058100-6bbb-11eb-8db7-b098a17242a6.png)

Although I think this is also a problem with the current polygon rendering, it just doesn't show up as much.

It'd be trivial to do render polylines too (and shouldn't lead to other problems)

**Comment by wibily** [comment]
Nick: this will be replaced by a library at some point.

**Comment by nf-s** [comment]
This is the lib I have my eye on https://github.com/protomaps/protomaps.js

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/5736
