### ISSUE TITLE
Can't draw more points after point movement

### ISSUE THREAD

**Issue by zoran995** [TerriaJS/terriajs#3851]
Once the user move point during measuring distance no more points can be drawn, only move of points is possible.
Even if the user close the measure tool panel, there is no way to start drawing again, unless the page is refreshed.
Any thoughts/info on this?

**Comment by zoran995** [comment]
Just checked on official master branch deployment and National map, it works fine, there is probably some problem with my local deployment

**Comment by zoran995** [comment]
This is reproducible in **firefox** on master branch, in chrome everything works fine

**Comment by tephenavies** [comment]
In 2D mode:
- Confirmed that you can't add points in firefox after dragging a point
- Also dragging points doesn't work well in firefox
    + The points appear to fly from a position they were not originally in when first dragging them
- In Safari points added in 2D mode show as black squares, not the intended points

**Comment by zoran995** [comment]
The original issue is resolved
