### ISSUE TITLE
Need Data Providers Guidelines

### ISSUE THREAD

**Issue by kgrochow** [TerriaJS/terriajs#386]
We've talked about this before, so I just wanted to make sure we have an issue for it for R1.

We need to provide a set of guidelines for data providers with:
- Data architecture
- Minimal Compliance
- Best Practices
- Examples of 'good' data providers

**Comment by kring** [comment]
This should cover it:
https://github.com/NICTA/nationalmap/wiki/Data-Providers-Guide

If there's anything missing we can write separate issues.
