### ISSUE TITLE
Zooming out too far in leaflet throws error

### ISSUE THREAD

**Issue by KeyboardSounds** [TerriaJS/terriajs#3864]
![image](https://user-images.githubusercontent.com/3796838/70281296-d166b780-180e-11ea-8e1c-639d5447f1f8.png)

@zoran995 spotted an issue with the 2D map where if you zoom out too far you get that error message.

I can reproduce it in the master branch.

**Comment by rowanwins** [comment]
Only appears to happen with bing basemaps, appears we might need to override the `this.minimumLevel` in `BingMapsCatalogItem.js`.

**Comment by zoran995** [comment]
this seems to be resolved
