### ISSUE TITLE
Splitter doesn't work in mobx

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#3872]
In the current nsw.dt release, adding the "Penrith Cadastre (over time)" layer and hitting the `Split` link freezes the browser window and continuously prints out a mobx trace message in the console:

<img width="658" alt="Screen Shot 2019-12-10 at 11 36 43" src="https://user-images.githubusercontent.com/5283003/70487557-db0f5880-1b49-11ea-8c68-1c1350eac3bc.png">

**Comment by kring** [comment]
Fixed by PR above.
