### ISSUE TITLE
mobx layer legend wont hide or fold

### ISSUE THREAD

**Issue by hardreddata** [TerriaJS/terriajs#3874]
http://ci.terria.io/mobx/

Add surface geology.

Attempt to hide giant legend using "down arrow" button on layer.

Nothing.

If you are managing these mobx things elsewhere and prefer to be left alone please let me know! I am looking forward to the new architecture.

**Comment by hardreddata** [comment]
Also the links in the feature information (for the geology layer) aren't recognised as such

**Comment by rowanwins** [comment]
Closing this issue and opening a new one for the feature info issue
