### ISSUE TITLE
Use clipping planes to carve out one model to make space for another

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#3887]
For example, cut a hole in a reality mesh and put a BIM there. This can be done with cesium's clippingPlanes feature as shown in this Sandcastle example:
https://sandcastle.cesium.com/#c=zRkLb9u4+a9wHXCWV4W28+h1dtItr0MDXC5Z47Y4NEVBS4zNiyRqFOXEN+S/7+NDFCXLabK2wAIkkciP3/vFT4MBOoxjRFCUsDxn2RzlCcloCCv6Ac0pT6kUKyQ5Khb8DskFRYLmghY0k0QyniF+o1avs8HAnc5iFPFMCp7oAymZZ0yWMbWwFnnMCkmyiKI7JhcGkJcFxdfZdbYkAi0ZvaMCHaCM3qFjWrAyxR/0WtCL9OsxECEso6IXov9cZwh+WHbDj/j9GN2QpKChWSxoQiPF7FkWs4hILpr7kgoBeC4FX7KYwqalFglKJP3IRRJPDUjQv84e+hPDYBFREOPAMor166TiXqn0YvYH0C0A5FPv6OwcuOxdcpZJdJzwMlavZ5nRgX455zFNep8ntfh6BY5b4WI6K+dHvAQpsvkHnpQpLU4zMktojJoS0XhOr+QqAbgaQIrS7d+TNE/odJXTAnY8Zi1AVAoBJj6t4Zpgn4afQRNOWknEnMrfgdWtvSEeWhG0nU8zySSjWguVbMYgNL5UAJNaYcoH9VqhMYNLXWlI6zF3C5oZJ0Exv7Ok1dNbcLmk7StXYD6aXeUkoqdLkMUCBb65cEQASaEs6uHBBZVnWV7KQ+01wU2ZmYeUL2kKqPqVRbSULLqlsdELcGDwqkUHjnNeMIVA0dFeeoMCy2VMb8CD48DH0kc//WQAq59HgDGLnwuPtTr7Too6RqxJQIzOI5MN8DiFOBGMKF+1pI95wgX++PZseopVgB8m+YIE4Bt7/Y1YeCnBY6k+2onJP6nVXNQ2PiYpFeTY5B1lRKodX9tROZ8OD4vgAXw33OQnytnxr6e/TL+cXHz8rV954jtglRRV8uKVI5a5ccMy/x5O6LBsdEFntA4famjzEfM+w1yj72StlndBCjM81waxqfq5ZlVJbfI0c76/dMZ8n8eggrYtVbwaa6qn72FPD8/Tk8rzLKtzIE0kUdnXZRwoK0Je2rSDV2ir3qJZXG94Nqpy+MsDi+/JwXJ+8f7q9Mv5xYdTo+BKNGQKqGbaaPyXSmiTgSo5BJWlyJA7FzQk1LDYtQsHFace7xaBn6RUcXpw9Ykl0LLIicdbwkk8NctBKRJHsVmHmtY/9veOlT8aadrMqpr6qZmRN2EJ/A2wGTyRbCdAIzwMERqqv/CnH6Kt0XCon74J79YPwmswGq6/P96tDrw12s8eCdX4fGQxNJTjuoPCHe3QPxSvAASorL8Y39WRYNyi1drhXLAUwmZJC0ziuMGw/rdzUvmT5w/gWkAF/npMtlxs3Fqo+FljCOsG8Aoa8WYTaBk1sj7SJE4a0VYhhRiNV9D7pgyab2jDu4pNlWhmFu9VvqBCh6JF0tyYNE8JErNShVITCpt1J6UGNwr/k/N0ygOLPfS95i2wq1TFZLR4R7I5hSq1B24xxNthRelvaBc8pN/ArLLqXyyOcyIFu9/F9N8ldAWB0wTnEktBsuKGi9TlvAr67OT0t+nZ9Pdm/lU/UFGmcH9pXqMQK+A6Ag5DkmSFqhYQXI9IfduxVHsFUnSRo4vXcB/mOWAgGQK300igcqeaKXUxA9+Eaq5RthiALKdWK62jwljNHGiR0VmyYuHYoDxoawCy7lTBJPrqt1Fv3aHc91uJiuSCsvlCeu2Dg3cJP2ixFW5wOmzkalNpxhZOVZAYedblu4Eo8AXsFqRKnqHlviHYg+9zwDQKlJgMaA0n8G+/zU9Cs7lcTNDLl2zNrdwdCk63joElAtal0PrOtarzF7V3MJ23WkR00bLOCamoU6dhxxHN1xh1YNNXVQa9RgEoVXrrUuN24GJ1W8Wv/9YPu5G6tnX89bZ1A4qK7QZLSTIj0S2kwJwKuQq+1rWE5i6xiYTti5sX7g1ApnnuEmf92ENz6aGZ3pxw1X0b52WxCDx3aHlpq3WqOySDHHNIHeIOakJdDqgQXDS8NAID84TihM/t7sSrpg+NZlA1XLpE/R+2W3VIq1ajb3qNH9hh6Eitgq4r+alMdELn0GwX0LNt7+Dhz7u7r0Z/D9EulLa94c7Pw1ch2tGd0KTGuTDFsZHZFljyd7AMaS0Y7ew1D+SqjKrkpIc2rmCDrtcWF3nrLtSoxHAisNRDgzXUaHxiXDA3NnQcTqvsXuBFC+G/ShXwmY48q6xQseHjpE9MdRncI9caMS/vOQL1rs/u2H/zYHQ5WU+DpWBrxMz1liSKjdet9RQahbRML9k9Ta7YnwpkpGwbPlbLNjSOXnz7HmfUA7VUzXVcgTDqc1DfULCeU6z+p0L1uLG+UpOeUI90MFUx1ZG2v7H6/ODK89Wq88yK41WIVqV5WpV5sOkf2tdLrub4SiqJYiA7z2zY5GbgHqPZCh2B6RO6QlerQtK0MNf2GUvfC29Kdcazd7TgpYiozpCHhRqqxMHrvVe71VQ+VxN2PWB/0tHRq93tUXWWVeN4c7SH8eBKD8BPiCSDxi1v4Eb39dNFnSIGVY/6R8Gz3qSaKoHUnaj1TmEpHDJhn77AI54ns542gD+xMJpx86ypCmvz4UW7kOn7me7kCh3VakEFmWHCTkU4B/9TWT3mUamHQxCqp4meEx2tQDs9C9JTlKwmbzMe3YI3mVwSuBrYBULUzeXI8lGDhhVpI0D7FDBxMSuoWKpC6p/qrX+W6PVxUc6KSLCZ16lAkH0gSelPmJTWakdWt8EKCB0cHLS+bTQyW7fetZMjsBp9HNloM7KGqz4H5/ZmnL4L+ylXx6FNoMoXHJybdpAZX9LqW5g3FrSO3Lw4eVnseZen0Z7usvZeY+hf9ob49fZevyV6SzLTM1ax4+eX53rPI6ORbjdaNnyoYy5rldOcCDxhWqPwfoMg693mU/jX7ZLrXi0XfpvqoqNVv/1D7nni+HYdvg0yR69V0wVVM+hDaBRdA7dhvGYgnXYtdOfnRH9y7Xes9QzP/9agS9KL8MV+AdqjbwzoP1macyFVuxZAWobyA5TAXwezEnoliaOiqFj4a5UyPXOrCj4XysRjJOYzEuxuQ5duf8HB/SjM1QQnm4/Rbn7vLc+4iKnYMndgf/OhRZapDwiNrgv6BgZN5RZJoK6OoZGM44SuU9ySPB+j7QbVamvGpeSpv9smqztz2pD6hmdy607PP9TQIPG+5OwPKu3ux2yJWHxw/aL1wf76BfgYKQrYuSkT3fJev3izPwD4xjEV/8DiBYiZkJUCWYze/GoWMcb7A3hdP2XZBnDD0775fIKgoyJbqioCDM+Vy4Ky/U/hoYmJccfnb82ewVNhNcaQsKkEXNDodsbvQTKNQ0mmejV498lqMAqe8kguslyYDnCMeppODxhAKpnU47ylPvVEZlRXuImX9XSymQUDoI+gwpxRFjcmuM7+Cw

The way it works is that you provide Cesium with a list of planes, specified as a direction (a normal sticking out of the plane) and the shortest distance from the model's origin to the plane. Anything outside of the volume formed by the planes is not drawn. The edge where the model intersects the plane can optionally be outlined.

This can be used to clip out a polygon, with the main limitation that the polygon must be convex. It must be convex because any part of the model that is on the wrong side of _any_ clipping plane will not be drawn. In a concave polygon, there may be parts of a model inside the polygon that are outside the plane formed by one of the edges.

**Comment by nf-s** [comment]
Done by https://github.com/TerriaJS/terriajs/pull/6147
