### ISSUE TITLE
Compass doesn't work in mobx

### ISSUE THREAD

**Issue by rowanwins** [TerriaJS/terriajs#3889]
No errors thrown but it doesn't rotate

**Comment by kring** [comment]
Clicking and dragging it moves the map as expected, but the "North" indicator doesn't move.

**Comment by rowanwins** [comment]
Looks like a race condition, `viewModel.props.terria.cesium` isn't defined when the app starts
https://github.com/TerriaJS/terriajs/blob/master/lib/ReactViews/Map/Navigation/Compass.jsx#L454

**Comment by rowanwins** [comment]
Possibly also related to `afterViewerChanged` event not really being hooked up, see https://github.com/TerriaJS/terriajs/blob/mobx/lib/ReactViews/Map/Navigation/Compass.jsx#L36
and
https://github.com/TerriaJS/terriajs/blob/mobx/lib/ViewModels/TerriaViewer.ts#L57-L59

**Comment by rowanwins** [comment]
resolved
