### ISSUE TITLE
Competitor UX benchmark/review

### ISSUE THREAD

**Issue by alyce** [TerriaJS/terriajs#3893]
**Applications:**
Mapbox
KeplerGL
GoogleEarth
Carto

**Libraries**

**Comment by rowanwins** [comment]
I think we should distinguish between libraries vs applications 

I would say GeoCortex is probably one of the more significant competitors for our target audience (which I'd consider to be data custodians rather than developers)
https://www.geocortex.com/products/gxw/

GeoCortex is primarily targeted at Esri customers and is used by a significant number of state gov depts, eg
https://www.seed.nsw.gov.au/ has a [map](https://geo.seed.nsw.gov.au/Public_Viewer/index.html?viewer=Public_Viewer&locale=en-AU) powered by GeoCortex
[ActMapi](http://www.actmapi.act.gov.au/)
[MapShareVic]( https://mapshare.vic.gov.au/MapShareVic/index.html?viewer=MapShareVic.PublicSite&locale=en-AU )

**Comment by hardreddata** [comment]
Perhaps also https://mapstore2.geo-solutions.it/

**Comment by hardreddata** [comment]
I think useful to consider competitors as other government services who do their own map. Three strong examples include

https://maps.six.nsw.gov.au/

https://minview.geoscience.nsw.gov.au/

https://elevation.fsdf.org.au/

We run a TerriaMap at work and I get a lot of sixmaps comparisons (coordinate tool, draw polygons etc) from people. It looks like parts of this may be gaining traction https://github.com/TerriaJS/terriajs/issues/3845

The spatial search in Minview, or the Elvis box draw is another fun comparison, somewhat known about https://github.com/TerriaJS/terriajs/issues/3385

When I discovered TerriaMap I also discovered https://bootleaf.xyz/ though one can argue you address somewhat different problems with Terria providing a more complete solution.

Mago3D is interesting, and I think some of the D61 team may have attended this talk ~ https://www.youtube.com/watch?v=otX2KgViFmA ~ I was surprised what he could do with 3D CAD navigation in the browser. Cesium demo is http://www.mago3d.net/homepage/demo.do

I span up Mapstore the other day, and similarly, looking at ActMapi one thing I like about Terria is having just one map with a consistent, simple, user interface. In my workplace Terria is of interest for people who find the complexity of QGIS intimidating. 

I hope this helps.

**Comment by AnaBelgun** [comment]
Thank you @RussellGrew. Very useful. 

We'll close and break down this epic into smaller issues depending on the features we want to implement.

**Comment by zoran995** [comment]
[Germany geoportal](https://www.geoportal.de/portal/main/#) is available open-source as [master portal](https://www.masterportal.org/), the git repo is available on [bitbucket ](https://bitbucket.org/geowerkstatt-hamburg/masterportal/src/dev/) and it has some nice features

**Comment by AnaBelgun** [comment]
Thanks you @zoran995 nice find indeed!

**Comment by zoran995** [comment]
[Geoportal of Luxembourg](https://map.geoportail.lu/theme/main?lang=en&version=3&zoom=10.048409397023182&X=695705&Y=6415448&layers=302-329-349&opacities=1-1-1&bgLayer=basemap_2015_global&crosshair=false&rotation=0) is using vector tiles as a base map - available under MIT licence https://github.com/Geoportail-Luxembourg/geoportailv3

**Comment by hardreddata** [comment]
https://github.com/kalisio/kano

Together with their wider offering. I cannot build it. Or used it.

See https://kalisio.github.io/kdk/

**Comment by zoran995** [comment]
Nice implementation of the latest cesium features (underground visualisation) - https://beta.swissgeol.ch/. A really interesting feature is the slice 3D scene (scissors on the right) - something like that would be really interesting for 3D tiles objects. (source code available - https://github.com/swissgeol/ngm)
