### ISSUE TITLE
TerriaJS UI Audit

### ISSUE THREAD

**Issue by vicborgy** [TerriaJS/terriajs#3894]
Audit and review of all UI assets across the TerriaJS network

**Comment by soyarsauce** [comment]
Hey @vicborgy - what are you aiming for/tracking in this issue? Should this be the one for the sketch overhaul, or https://github.com/TerriaJS/terriajs/issues/3895?

**Comment by vicborgy** [comment]
Good question. Maybe the #3895 is best.

**Comment by AnaBelgun** [comment]
superseded by other tickets
