### ISSUE TITLE
Model Architecture: Migrate Sensor Observation Services catalog item

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#3896]

**Comment by na9da** [comment]
Sample catalog definitions for testing:

https://github.com/TerriaJS/neii-viewer/blob/master/wwwroot/init/neii-water.json#L626-L675
and
https://github.com/TerriaJS/terria-cube/blob/master/wwwroot/init/terria-cube.json#L139-L150

**Comment by AnaBelgun** [comment]
Hi @na9da would you please comment a bit on this ticket (e.g. approaches, version of SOS, challenges etc)

**Comment by AnaBelgun** [comment]
merged
