### ISSUE TITLE
Model architecture: Move TerriaCube to mobx

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#3900]
TerriaCube has the following catalogue member types:
- `group`
- `wms`
- `wms-getCapabilities`
- `wps`
- `geojson`
- `csv`
- `sos`

All of these except `sos` are already ported, and `sos` is slated to be ported by end of March.

Some additional features for `wms` built for DEA will also require porting such as:
- [x] Date filtering
- [ ] Linked WCS - https://github.com/TerriaJS/terriajs/issues/4268 
- [ ] Connection to SOS graps

**Comment by AnaBelgun** [comment]
- set up TerriaCube on Mobx (without magda clusters/backend) to start developing and testing the functionalities for DE Australia and DE Africa

**Comment by AnaBelgun** [comment]
superseded by specific DEAU and DE Af mobx releases: 
- https://github.com/TerriaJS/de-australia-map/issues/47
- https://github.com/TerriaJS/de-africa-map/issues/44
