### ISSUE TITLE
Legends: long titles are partially clipped on the right edge

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#3908]
<img width="469" alt="Screenshot 2019-12-23 10 42 31" src="https://user-images.githubusercontent.com/5292858/71328833-799bb080-2571-11ea-963a-be8c212b8d9b.png">

Also: legend titles and values are currently displayed in a mono font, unlike the rest of the UI (excluding feature info). For consistency it may be better to display legend text in the default Terria font.

**Comment by rowanwins** [comment]
Had a look, it's pretty hard to replicate and only occurs with some legend text (the above being a good example). Also challenging because they are SVG text elements rather than HTML,[ see here](https://github.com/TerriaJS/terriajs/blob/master/lib/Map/Legend.js#L216-L247)

**Comment by rowanwins** [comment]
So I think this is caused when the item was added and there was a scrollbar present on the workbench. The legend width has a [width property](https://github.com/TerriaJS/terriajs/blob/master/lib/Map/Legend.js#L104) which if we tweak it down a smidge it seems happy.

![screenshot-localhost_3001-2020 01 13-16_28_02](https://user-images.githubusercontent.com/6735870/72234552-b400e680-3621-11ea-8585-2672afe0a168.png)

**Comment by philipgrimmett** [comment]
@rowanwins hmm, does that fix mean the legend width will always be out of visual alignment with the other workbench item controls? eg. display variables

**Comment by rowanwins** [comment]
Take a look at https://github.com/TerriaJS/terriajs/pull/3925 @philipgrimmett - I think I've got it sorted
