### ISSUE TITLE
Cesium not honouring url template layer minimumLevel

### ISSUE THREAD

**Issue by hardreddata** [TerriaJS/terriajs#3910]
The title is my best guess at what is happening.

Consider

```
{
   "catalog":[
      {
         "type":"group",
         "name":"My group",
         "items":[
            {
               "name":"Maptiler Positron 256",
               "type":"url-template",
               "minimumLevel": 2,
               "isRequiredForRendering": "true",
               "url":"https://api.maptiler.com/maps/positron/256/{z}/{x}/{y}.png?key=XXX"
            }
         ]
      }
   ]
}
```
which I can crash (Request has failed. Status Code: 400) in 3D by zooming in sufficiently far. I cannot crash 2D. This issue may be mostly academic if we assume the end user doesn't zoom into the individual houses. Or it might reflect a feature of the maptiler API?

I can provide the *key* in a message if needed. 

I understand https://www.maptiler.com/ is free for personal use. I was going to https://openmaptiles.com/server/ but it seemed like an easier way. Their website also includes (leaflet, openlayers, cesium) code examples, and they do advise on constraining the resolution.

The openlayers example

```
      var map = new ol.Map({
        layers: [
          new ol.layer.Tile({
            source: source
          })
        ],
        target: 'map',
        view: new ol.View({
          constrainResolution: true,
          center: ol.proj.fromLonLat([0, 0]),
          zoom: 2
        })
      });
```

Advice welcome.

**Comment by rowanwins** [comment]
Hi @RussellGrew 

In regards to crashing from zooming in it looks like the tiles are only available until level 22 so adding `"maximumLevel": 22,` to your config will help that issue

Higher zoom levels are closer in. By setting ` "minimumLevel": 2,` you are impacting what tiles are requested when zoomed out so you can see the whole earth.

Hopefully that makes :)

**Comment by hardreddata** [comment]
Great success!

As a matter of interest how did you determine to what level the tiles are available? Presumably without the access key.

I think I can build a full WMS request using URL templates? 

Cheers.

**Comment by rowanwins** [comment]
> As a matter of interest how did you determine to what level the tiles are available? Presumably without the access key.

I got myself an access key. And then just tried for some valid tiles, [this site](https://www.maptiler.com/google-maps-coordinates-tile-bounds-projection/) is quite handy for getting quick x,y,z references.

Building a full WMS request using URL templates is probably doable although it depends on what you're trying to achieve, I'd would've thought the WebMapServiceCatalogItem is a better starting point, if there is something you are stuck on there perhaps open a new ticket :)

**Comment by hardreddata** [comment]
Thanks.

I am not proposing the WMS URL template thing. It was my guess at how you determined the zoom levels (presumably in some WMS query response) without API credentials. I see now you signed up.

On Maptiler it would be good to have the vector tiles as a possibility in TerriaMap. I did look at this when I was raising these tickets but decided Terria (Cesium) wasn't equipped to style them.
