### ISSUE TITLE
url template tiles fixed to 256 x 256 pixels

### ISSUE THREAD

**Issue by hardreddata** [TerriaJS/terriajs#3911]
Cesium supports tile dimensions as an argument https://cesium.com/docs/cesiumjs-ref-doc/UrlTemplateImageryProvider.html

I am on the verge of a pull request with https://github.com/RussellGrew/terriajs/blob/url-template-tile-size/lib/Models/UrlTemplateCatalogItem.js where I have included tileWidth and tileHeight as configurable parameters.

The problem I have is that it isn't working properly in 2D. I am using tiles from https://www.maptiler.com/ and without the correct tileWidth and tileHeight set the street names are tiny (and this is how I know it isn't working in 2D).

I can use their 256 pixel tiles in the meantime. It seems the 512 pixel tiles are also in use with ESRI https://openlayers.org/en/latest/examples/xyz-esri-4326-512.html

I am guessing the full fix might be in the Cesium codebase and so outside the proposed pull request. It is also outside my skills. Advice on how to best proceed is invited.

Thanks.

**Comment by rowanwins** [comment]
Can you share the url of tile endpoint @RussellGrew ?

**Comment by rowanwins** [comment]
That said your modification to `UrlTemplateCatalogItem.js` look fine

**Comment by hardreddata** [comment]
Thanks. I sent you a message in gitter with the url template.

**Comment by rowanwins** [comment]
Hi @RussellGrew - I took a look at the services you posted and yeah I dont see any reason why your pull request won't work so put it in and we'll take it from there. The only suggested changes to your file would be adding the property description above both `width` and height` as they'll flow through to the documentation properly that way.
https://github.com/RussellGrew/terriajs/blob/url-template-tile-size/lib/Models/UrlTemplateCatalogItem.js#L41-L47

And don't forget to add something to the CHANGES.md :)

**Comment by nf-s** [comment]
https://github.com/TerriaJS/terriajs/pull/6231 adds `UrlTemplateImageryCatalogItem` with `tileWidth` and `tileHeight` traits
