### ISSUE TITLE
gltf catalog type undocumented

### ISSUE THREAD

**Issue by hardreddata** [TerriaJS/terriajs#3928]
I think

https://github.com/TerriaJS/terriajs/blob/0aac25567268b6856b3597a6112f9c5cf88fdd0c/lib/Models/GltfCatalogItem.js

should appear here

https://docs.terria.io/guide/connecting-to-data/catalog-items/

Or not. I have used it a few times for various experiments. 

I think useful to share that one can load these models without ion hosting.

**Comment by nf-s** [comment]
Now in https://docs.terria.io/guide/connecting-to-data/catalog-type-details/gltf/
