### ISSUE TITLE
Model architecture: implement Search catalogue 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#3933]
Currently the apps on mobx branch have lost the "search in catalogue" functionality. 
It needs to be re-instated. 

![image](https://user-images.githubusercontent.com/18452161/72481924-10494d80-3850-11ea-9586-2117b8dc36f6.png)

**Comment by soyarsauce** [comment]
@AnaBelgun search has been implemented via a client side method to https://github.com/TerriaJS/nsw-digital-twin/pull/220

A more generalised search should be added back to terriajs, but in fact thinking about it now, we could just add https://github.com/TerriaJS/nsw-digital-twin/blob/76223f6c6ee92bd3f36dd37bd50d1b8eef8d75e5/lib/Models/MagdaSearchProvider.ts in its entirety into terriajs, perhaps with a slight tweak through config to enable or disable search calling `loadMembers()`* as part of its client-side-searching. @steve9164 @KeyboardSounds any thoughts?

**Comment by soyarsauce** [comment]
I don't think we can get much more done for this unless we deprioritise something else, if really needed we can speed up the client side search even further, by force loading any references even before a user searches (perhaps upon opening the catalogue)

**Comment by tephenavies** [comment]
What about it is specific to magda? It looks like it could be generalised pretty easily by using References and Groups, but maybe there's something specifically magda there.

**Comment by soyarsauce** [comment]
Yes that's what i mean by adding it in its entirety, and renaming a few things - can be used for any references and groups, however we'd need to consider if the default should be also calling loadMembers() on groups - that would slow things down considerably if there are slow remote services in a given map.

**Comment by soyarsauce** [comment]
And not "getting much more done" was speaking to implementing any server side search at this point in time.

**Comment by AnaBelgun** [comment]
will put in the product backlog atm, until we start the server side (magda) implementation

**Comment by soyarsauce** [comment]
https://github.com/TerriaJS/terriajs/issues/3657
