### ISSUE TITLE
GeoRSS Support

### ISSUE THREAD

**Issue by gordongrace** [TerriaJS/terriajs#3943]
Several Australian government data custodians publish incident data using the GeoRSS format:

Examples:
http://esa.act.gov.au/feeds/currentincidents.xml
https://www.qfes.qld.gov.au/data/alerts/bushfireAlert.xml
http://emergency.vic.gov.au/public/atom-cap.xml

This geospatial format is non-proprietary, well-documented and well-established. I'd like to propose it's inclusion in the list of supported formats when adding Web Data.

**Comment by rowanwins** [comment]
Thanks for raising this @gordongrace 

The challenge with GeoRSS is that is standardises how the geometries are transmitted but many of the other fields are not

eg ACT
````
<item>
    <title>ELECTRICAL THREAT OR POWER LINES DOWN - BELCONNEN</title>
    <link>http://esa.act.gov.au/feeds/currentincidents.xml</link>
    <description>
        Incident: ELECTRICAL THREAT OR POWER LINES DOWN - BELCONNEN<br />Location: MIRAMAR, CHANDLER STREET, BELCONNEN, 2617<br />Status: Resource Allocation Pending<br />Suburb: BELCONNEN<br />Type: ELECTRICAL THREAT OR POWER LINES DOWN<br />Agency: Fire<br />Incident Number: 001729-20012020<br />Updated: 20 Jan 2020 15:02:59<br />Time of Call: 20 Jan 2020 13:05:00
    </description>
    <guid>001729-20012020</guid>
    <pubDate>22 Jan 2020 13:36:30 EST</pubDate>
    <georss:point>-35.23685081 149.06891403</georss:point>
</item>
````
vs QLD
````
<entry>
    <category term="Notification"/>
    <content>
        Alert Level: Notification Reported: 2020-01-20T01:11:30+10:00 Current Status: Patrolled Details: <div>Canoona (north-west of Rockhampton) – vegetation fire as at 3.40pm Mon 20 Jan </div><div></div><div>Queensland Fire and Emergency Services (QFES) crews are on scene at a vegetation fire burning in the vicinity of Kunwarara Road and Hams Road, Canoona. This fire broke out earlier today and is posing no threat to property at this time. Firefighters are working to control the blaze. Nearby residents may be affected by smoke and are asked to close windows and doors and if suffering from a respiratory condition, keep medications close by. Smoke is also affecting the Bruce Highway so motorists should drive with caution and to conditions. If residents are concerned their property is under threat, they are advised to call Triple Zero (000) immediately.</div> Vehicles on Scene:0 Vehicles on Route:0
    </content>
    <id>QF2-20-007639</id>
    <published>2020-01-20T01:11:30+10:00</published>
    <title>Kunwarara Rd & Hams Rd, Canoona</title>
    <updated>2020-01-21T20:56:12+10:00</updated>
    <georss:point>-23.049144 150.259867</georss:point>
</entry>
````

The other option in this space is the [Common Alerting Protocol](http://www.bom.gov.au/metadata/CAP-AU/Spec.shtml) which I think goes further in standardising content and I gather there is movement towards most states providing these services.
> The Common Alerting Protocol (CAP) is an international standard for the construction of emergency alert and warning messages, which facilitates reliable information exchange between various systems and networks.

Anyway we'll add it to our investigations and see where it leads

**Comment by zoran995** [comment]
@rowanwins I already looked at GeoRSS format in the past, so I will drop some notes about it. 
There is an ogr2ogr implementation of conversion service for GeoRSS format.
This format was developed for use inside RSS specification so it doesn't standardize anything but geometry. I think that support should be targetted towards to 3 general implementations of GeoRSS:
- Atom - QLD
- RSS 2.0 - ACT
- RSS 1.0 (or RSS RDF), maybe even check if there is any implementation existing.

That is why you noticed that they doesn't look standardized. 
All files @gordongrace shared are using GeoRSS [simple geometry](http://www.georss.org/simple.html), we should note that also [GML](http://www.georss.org/gml.html) and [W3C geometry](http://www.georss.org/w3c.html) format are possible. 
IMO the easiest implementation is parsing GeoRSS converting it to geojson.
