### ISSUE TITLE
Model Architecture: Auto-detect issue for esri-mapServer

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#3944]
You can't auto-detect this layer when adding web data:
http://services.ga.gov.au/gis/rest/services/NEXIS_Agricultural_Exposure/MapServer

But you can add it if you manually select Esri ArcGIS MapServer

Repro:
1. Visit http://ci.terria.io/mobx/
2. Click add data -> my data -> add web data -> http://services.ga.gov.au/gis/rest/services/NEXIS_Agricultural_Exposure/MapServer with auto-detect as file type
3. Observe "Use conversion service?" error message underneath(separate issue!) the explorer window

**Comment by soyarsauce** [comment]
Possibly sliverly-related https://github.com/TerriaJS/nsw-digital-twin/issues/213

**Comment by rowanwins** [comment]
Don't think it is related to the above
