### ISSUE TITLE
Model architecture: Re-implement overrides and fix WelcomeMessage

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#3966]
`WelcomeMessage` is currently commented out in `mobx` because terria.overrides doesn't exist in `mobx`. Related to https://github.com/TerriaJS/terriajs/issues/3948.

**Comment by rowanwins** [comment]
Think is probably superceded and can be closed @steve9164 ?

**Comment by nf-s** [comment]
Is this still relevant?

**Comment by tephenavies** [comment]
I don't think so
