### ISSUE TITLE
Model Architecture: DimensionSelectorSection doesn't work with WMS

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#3970]
Style and Dimensions selector not wired for WMS catalog item in Mobx branch.

Example WMS layer - https://ppbcha.duckdns.org/geoserver/ows?service=WMS&version=1.3.0&request=GetCapabilities&

Then pick **PPB Inundation - 25m whole bay** layer.

## Mobx

![mobx](https://user-images.githubusercontent.com/6187649/73512920-a92abc00-443f-11ea-808d-0854c1c04bba.jpg)

## National Map

https://nationalmap.gov.au/#share=s-xRvpLL5Cl9ep3cAEWUGFfOL7wFb

![natmap](https://user-images.githubusercontent.com/6187649/73512921-a9c35280-443f-11ea-9294-a7c4a5929683.jpg)

**Comment by rowanwins** [comment]
StyleSelectorSection now works. But still no DimensionSelectorSection

**Comment by nf-s** [comment]
Closed by #4219
