### ISSUE TITLE
CSV / region mapping issue

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4006]
Repro:
1. visit terria / nationalmap
2. explore data > my data > add web data
3. use https://portals.agriculture.gov.au/Documents/Socio-Economic_Indicators/Age_profile.csv
4. observe `TypeError: t is undefined`

Share link: https://www.nationalmap.gov.au/#share=s-y0tlWt5ynyRvD7qgU4pgNnWTINU
http://ci.terria.io/master/#share=s-vhVorjEYMNUXvfNcVatDAMhfCFG

**Comment by nf-s** [comment]
URL is broken https://portals.agriculture.gov.au/Documents/Socio-Economic_Indicators/Age_profile.csv
