### ISSUE TITLE
Model Architecture: Splitting csv and other items

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4007]
See:
https://www.nationalmap.gov.au/#share=s-wykdO0p8YTA8WxpcmZZt3j1wmpF
vs
http://ci.terria.io/mobx/#start=%7B%22version%22%3A%228.0.0%22%2C%22initSources%22%3A%5B%7B%22stratum%22%3A%22user%22%2C%22models%22%3A%7B%22__User-Added_Data__%22%3A%7B%22isOpen%22%3Atrue%2C%22members%22%3A%5B%22%2Fhttps%3A%2F%2Fportals.agriculture.gov.au%2FDocuments%2FSocio-Economic_Indicators%2FAge_profile.csv%281%29%22%5D%2C%22knownContainerUniqueIds%22%3A%5B%22%2F%22%5D%2C%22type%22%3A%22group%22%7D%2C%22%2Fhttps%3A%2F%2Fportals.agriculture.gov.au%2FDocuments%2FSocio-Economic_Indicators%2FAge_profile.csv%281%29%22%3A%7B%22url%22%3A%22https%3A%2F%2Fportals.agriculture.gov.au%2FDocuments%2FSocio-Economic_Indicators%2FAge_profile.csv%22%2C%22knownContainerUniqueIds%22%3A%5B%22__User-Added_Data__%22%5D%2C%22type%22%3A%22csv%22%7D%7D%2C%22workbench%22%3A%5B%22%2Fhttps%3A%2F%2Fportals.agriculture.gov.au%2FDocuments%2FSocio-Economic_Indicators%2FAge_profile.csv%281%29%22%5D%2C%22timeline%22%3A%5B%5D%2C%22initialCamera%22%3A%7B%22west%22%3A108.62763300970809%2C%22south%22%3A-43.70728609589825%2C%22east%22%3A158.3723673869064%2C%22north%22%3A-6.109957777468237%2C%22position%22%3A%7B%22x%22%3A-6399054.073546263%2C%22y%22%3A6743196.003301235%2C%22z%22%3A-4620509.9563363865%7D%2C%22direction%22%3A%7B%22x%22%3A0.6155884585069561%2C%22y%22%3A-0.6486948829269784%2C%22z%22%3A0.4474883223251568%7D%2C%22up%22%3A%7B%22x%22%3A-0.30803063424204336%2C%22y%22%3A0.32459656034195455%2C%22z%22%3A0.8942897748395743%7D%7D%2C%22homeCamera%22%3A%7B%22west%22%3A109%2C%22south%22%3A-45%2C%22east%22%3A158%2C%22north%22%3A-8%7D%2C%22baseMapName%22%3A%22Bing+Maps+Aerial+with+Labels%22%2C%22viewerMode%22%3A%223d%22%2C%22currentTime%22%3A%7B%22dayNumber%22%3A2458890%2C%22secondsOfDay%22%3A53524.051%7D%2C%22showSplitter%22%3Afalse%2C%22splitPosition%22%3A0.5%2C%22stories%22%3A%5B%5D%7D%5D%7D

**Comment by rowanwins** [comment]
Resolved by #4114
