### ISSUE TITLE
UI Gyro help tightening

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4046]
- [x] - 1px "jump" observed on hover, on chrome (not ff) - hover on gyro for hover state
- [x] - outer ring needs to use the larger svg when hovered
- [x] - jumping button needs to be resolved - to be a separate issue
- [x] - help button needs to be linked up directly to the gyro guide

(From Vic)
Updates still outstanding from work completed since UX testing

- [x] When in active mode, the out ring should have a larger outing as per my designs - Ive done this so the draggable area is larger and easier to ‘grab'
- [x] When clicking on ‘Controls’, the button should stay active/open and not minimise
- [x] The ‘Gyroscope controls’ overlay should have an opaque black background, not blue
- [x] When clicking ‘menu’ we need to open the RHS menu with information on using the navigation controls active. (This is missing from the menu and is something that needs to be created)
- [x] Help icon needs updating to the new one - has been made thicker to align with other items

**Comment by soyarsauce** [comment]
- create extra themed colour/options to actually match the design (black instead of primary colour?)

**Comment by soyarsauce** [comment]
https://github.com/TerriaJS/nsw-digital-twin/issues/242

**Comment by zoran995** [comment]
Jump is happening on focus, it is coming from user agent stylesheet in google chrome
```
:focus {
    outline: -webkit-focus-ring-color auto 1px;
}
```

it can be solved by adding the same `outline` on compass outer ring or possibly doing some  normalization, to remove chrome default outline on focus

**Comment by soyarsauce** [comment]
I'd like this to be wrapped up in https://github.com/TerriaJS/terriajs/pull/4213 and we pull the `- jumping button needs to be resolved` problem to a separate issue

**Comment by soyarsauce** [comment]
Resolved via https://github.com/TerriaJS/terriajs/issues/4046

`- jumping button needs to be resolved` is also resolved with above
