### ISSUE TITLE
Model Architecture: story location button 

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4070]
Right now button removes layers. Needs #fixed-in-mobx

**Comment by mgcsls** [comment]
Pressing the story location button seems to also cause the catalog to duplicate itself:
<img width="526" alt="image" src="https://user-images.githubusercontent.com/40459355/75502091-ed50b280-5a25-11ea-9110-9dec5a132eb9.png">

**Comment by rowanwins** [comment]
Right now the location button appears to do nothing - at least it's not deleting or replicating items! Although I'm not sure what it's supposed to do... and it doesn't seem to do anything in master so I'm going to close

**Comment by soyarsauce** [comment]
@rowanwins I was still able to replicate this

**Comment by soyarsauce** [comment]
Duplicate catalog after clicking the story location button
![image](https://user-images.githubusercontent.com/9134432/83831634-26867600-a72b-11ea-8929-b357fdc16463.png)
