### ISSUE TITLE
AR mode no longer works on iOS

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#4073]
The AR button no longer does anything on iOS. There are reports of changes, maybe it's related?

https://forum.ggnome.com/viewtopic.php?t=13965

**Comment by Techmaven-geospatial** [comment]
I have same issue in Earth Explorer 3D map mobile app (iOS or Android )which is based on terriajs we also see iPad button stopped appearing but iPhone button does nothing

**Comment by soyarsauce** [comment]
Should be working on mobx - will double check
