### ISSUE TITLE
Mobx: share URL can't share split "copy" datasets

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#4078]
When Splitting/comparing a dataset and then generating a Share URL, the "copy" dataset doesn't appear to have a source URL.

**Comment by soyarsauce** [comment]
Maybe there's an error about URL specified.
Crispy: almost definitely in the wrong stratum.

The copied dataset needs to have their definition data on user, so that it gets shared (or somehow referencing the original catalog item)

**Comment by rowanwins** [comment]
Resolved by #4135
