### ISSUE TITLE
Mobx: split screen mode terrain position buttons bug

### ISSUE THREAD

**Issue by mgcsls** [TerriaJS/terriajs#4080]
1. go to http://ci.terria.io/mobx/
2. add some data to workbench
3. open "split screen mode" in workbench by pressing "compare" (near top right of map)

If you now change map view to 3D smooth or 2D, the left/both/right buttons don't appear to work as intended. Possibly they should be hidden since the same settings are hidden in the Map Settings panel?

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/40459355/75208397-a5d0e900-57cf-11ea-8217-4b902f9df95b.png">

**Comment by rowanwins** [comment]
Resolved by #4096
