### ISSUE TITLE
Mobx/Digital twin UI issues on small screen - Tools menu

### ISSUE THREAD

**Issue by zoran995** [TerriaJS/terriajs#4085]
When a user resizes the browser window there are a few edge cases that he can see

- related maps get moved to the second row when the user is logged, and there are three rows (first image), in my case between 768px and 797px (on longer names it will happen even earlier)
- before switching to mobile view there is a possibility to see something like on the second image (blue line around logo)
- on a screen with a width less than 1000px related buttons get out the window (user can't see the close button)
![first image](https://user-images.githubusercontent.com/19208948/75198688-81d6be80-5761-11ea-902a-173c084aa5cf.png)
![blue line](https://user-images.githubusercontent.com/19208948/75198697-89966300-5761-11ea-9850-fffef3b7bfbd.png)
![related maps](https://user-images.githubusercontent.com/19208948/75198707-8dc28080-5761-11ea-8d01-84ad87566811.png)

**Comment by zoran995** [comment]
Iphone X in landscape mode provides few edge cases for phones. Buttons help and feedback go out of the screen. Also, scale graph overlaps with a disclaimer, lat/lon info shows on the map although they don't have any function. Related maps close button goes out of the screen.
![iphonex](https://user-images.githubusercontent.com/19208948/75424866-d59ffe00-5941-11ea-90f4-524e47c22f6f.png)

**Comment by zoran995** [comment]
Also, help UI is not responsive on screen size change so it doesn't get a scroll bar on smaller screens. The same thing is happening with the help panel. The help menu doesn't work on a mobile phone.
![help-ui](https://user-images.githubusercontent.com/19208948/75696010-2f3e5a80-5cab-11ea-905f-88c1859bfc47.png)

Helpful hints in workbench get cut off on a smaller screen.
![hints](https://user-images.githubusercontent.com/19208948/75696856-84c73700-5cac-11ea-99bd-d85e931c3f5b.png)

**Comment by AnaBelgun** [comment]
Another example of Mobile/small screen issues with top menu bar. 
On v8 based DE Africa the top menu bar completely disappears; there is no menu visible 

![image](https://user-images.githubusercontent.com/18452161/92430731-f8f11300-f1d8-11ea-846a-0d25f3def702.png)

**Comment by soyarsauce** [comment]
@reginapramesti this one please 🙂

**Comment by soyarsauce** [comment]
@reginapramesti to highlight remaining edge case things

**Comment by reginapramesti** [comment]
Edge cases that still need addressing:
* Left menu bar overflows to a 2nd row when logged in and screen width is between 768px and 797px
* Related maps gets cut off on smaller widths, and close button isn't visible
* Some `MapIconButton` overflows on smaller heights, so help and give feedback is inaccessible

**Comment by zoran995** [comment]
@reginapramesti Any thoughts on the fixing the `MapNavigation` overflow? I am thinking about something similar to the vscode sidebar overflow (composite side bar) which will group items into 3 dots icon on overflow, it will require a rewrite of `MapNavigation`

**Comment by AnaBelgun** [comment]
we'll need to discuss with @philipgrimmett when he starts next week

**Comment by zoran995** [comment]
I implemented the approach mentioned above, and here are the photos how it currently looks (there are some additional tools we are using in our implementation - might not be perfect with less amount of tools). I can export it and create a PR if you are interested into it.
![image](https://user-images.githubusercontent.com/19208948/99952606-300aa580-2d80-11eb-84c2-ac367cbd1d82.png)
![image](https://user-images.githubusercontent.com/19208948/99952623-3731b380-2d80-11eb-8a07-2d8d98133b17.png)

@AnaBelgun if it will be useful I can forward you a link to our dev implementation so you can directly check it.

**Comment by AnaBelgun** [comment]
HI @zoran995 yes, yes, that would be really good (i.e to export and create a PR and send us the dev env. link to test; it would be much easier to check from design perspective and review the PR). Thank you again for all your hard work 👍

**Comment by zoran995** [comment]
I believe this is in a pretty good state now, will do a review later and create a new issue if necessary
