### ISSUE TITLE
AR buttons not properly aligned in Chrome

### ISSUE THREAD

**Issue by na9da** [TerriaJS/terriajs#4090]
We probably need to convert them to new `MapIconButton` component.

![image](https://user-images.githubusercontent.com/1430/75401585-ae9ff700-5956-11ea-93fc-07a5e0f464a1.png)

**Comment by zoran995** [comment]
On the Huawei P20 Lite, the augmented reality button is cut in half. There is a way to move them but the disclaimer stays cut. If I hide the address bar in google chrome compass button gets overlapped with the user location button (see image).

![overlap](https://user-images.githubusercontent.com/19208948/75424450-ec922080-5940-11ea-9323-2cf9c8d94259.png)
