### ISSUE TITLE
Mobx: feature highlighting not working for imagery layers

### ISSUE THREAD

**Issue by mgcsls** [TerriaJS/terriajs#4093]
Add http://services.ga.gov.au/gis/rest/services/GA_Surface_Geology/MapServer and click somewhere.

On master there is a white highlight around the picked region:
<img width="257" alt="image" src="https://user-images.githubusercontent.com/40459355/75412709-70ff9600-5977-11ea-96ee-a210e77c9d8f.png">

On mobx there is only the location marker:
<img width="242" alt="image" src="https://user-images.githubusercontent.com/40459355/75412678-54635e00-5977-11ea-9a8b-a2c824d3b65e.png">

**Comment by nf-s** [comment]
Merged into https://github.com/TerriaJS/terriajs/issues/4983
