### ISSUE TITLE
Model Architecture: AR Buttons in portrait

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4097]
Until mobile works well, fix this:

>I couldn't see the AR buttons on Safari (iOS version 13.3.1). Same with Chrome on iOS (80.0.3) but works well in Firefox iOS.

from https://github.com/TerriaJS/terriajs/pull/4088

**Comment by zoran995** [comment]
Just tested, and AR buttons work correctly on iOS
