### ISSUE TITLE
Model Architecture: Drag and drop

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4102]
UI for drag and drop is either broken or not yet ported to mobx.

**Comment by soyarsauce** [comment]
Remove the text if we don't actually support it, or even just implement it if it's quicker

**Comment by nf-s** [comment]
I fixed this today, but haven't created a pull request yet.

**Comment by nf-s** [comment]
Also there is an issue with creating the Catalog item based on the file extension. I'll look into this too

**Comment by nf-s** [comment]
Can I close this?

**Comment by soyarsauce** [comment]
If it's fixed-in-mobx, then yes 🤷 
thanks for fixing it!
