### ISSUE TITLE
Mobx: CSV loading should trim column names before trying to render

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#4103]
Mobx currently doesn't trim whitespace off the column names of CSV files. This causes problems, e.g. a CVS with column headers like `Col1, Col2, Lat, Lon` doesn't work due to the leading spaces on the column names.

[LatLong.csv.txt](https://github.com/TerriaJS/terriajs/files/4272943/LatLong.csv.txt)

**Comment by soyarsauce** [comment]
It's low: a corner case.

**Comment by rowanwins** [comment]
Done in #4117
