### ISSUE TITLE
Model Architecture: "Download"-looking like button on Upload

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4107]
<img width="135" alt="image" src="https://user-images.githubusercontent.com/9134432/75645734-35c4d600-5c9b-11ea-8a82-2f93df585295.png">

@vicborgy could you pretty please provide an icon that represents uploading? Right now it looks like a download icon 🙂

**Comment by reginapramesti** [comment]
Resolved by #4111
