### ISSUE TITLE
Handle updating help & about pages content more efficiently

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#4124]
Currently a Terriajs app / apps owner would have to change the content in a doc (or not) and transfer to static HTML pages of the app. 
We'd like to make that process simpler, especially when owning several applications and customising the pages for each of them. 

Some suggestions from the team:

- 'about pages' - just a static site generator, backed with either static markdown + image files (dead simple), or something like netlify cms - then developers can change about pages in their editors if they wish, or have the easy-cms to update, and it's all stored in git

**Comment by soyarsauce** [comment]
A bit more about the above:

>if steve B has done something similar to this before, i'm sure he can get it going super easily.

>suggested using a static site generator, but @steve9164 and I were worried that might be too annoying for people who aren't developers to update

>yeah the "non-developers updating" is what the cms part should, at least in theory, address. then content updates can happen without touching code or git (yet it still saves to source via a git repo! :tada: )

**Comment by nf-s** [comment]
No longer relevant
