### ISSUE TITLE
Story: if a story includes a data layer with disclaimer, you can't close it

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#4127]
Came across this bug checking a story in AREMI which includes a disclaimer for specific data layers (NoM). Steps to reproduce: 
- check this story link: https://nationalmap.gov.au/renewables/#share=s-vsQZ37L6dq1FTeMH
- click until you get to page 4
- you can't get rid of the disclaimer, even after closing the story page 4

![image](https://user-images.githubusercontent.com/18452161/76047224-2b198200-5fb6-11ea-9154-368ced485f86.png)

**Comment by nf-s** [comment]
Not in v8

https://www.nationalmap.gov.au/#share=s-9NnX1r3q9QWvuuCev7NGXQF3f7h
