### ISSUE TITLE
Mobx: analytics launch url still empty

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4134]
Labels are still not being set on the `launch` event(?!): https://github.com/TerriaJS/terriajs/blob/mobx/test/Core/uriHelpersSpec.ts#L12

Regressed from gibberish(stringified-function as label), to a blank label, so slightly better. But still a problem.!

(keywords: story analytics category action label ga google analytics)

**Comment by soyarsauce** [comment]
https://github.com/TerriaJS/terriajs/pull/4084
https://github.com/TerriaJS/nsw-digital-twin/issues/356

**Comment by AnaBelgun** [comment]
If PR #4184 merged, can this be closed?

**Comment by soyarsauce** [comment]
Resolved in https://github.com/TerriaJS/terriajs/pull/4184
