### ISSUE TITLE
Product design contributions?

### ISSUE THREAD

**Issue by devinhalladay** [TerriaJS/terriajs#4147]
Hi everyone! Just popping in to ask if there's any need for software/product design thinking or work on this project. I left Palantir Technologies a few months ago, where I spent close to a year designing high-scale geo-data analysis platforms, and learned to really love cartography and the workflows built around it. Would be very interested in lending a hand if there's a way I can help out. You can find some of my work at https://devinhalladay.com/ if interested.

**Comment by rowanwins** [comment]
Hi @devinhalladay 

Thanks for reaching out. Unfortunately our UX team aren't in a position to onboard people at the moment and don't have any particular tasks they need assistance.

Thanks
