### ISSUE TITLE
WMS catalog group not using user specified parameters

### ISSUE THREAD

**Issue by zoran995** [TerriaJS/terriajs#4148]
WMS catalog group is not using the parameters specified in the catalog file. Recently @RussellGrew tried to filter WMS get capabilities request by namespace which led to the discovery of this bug. The documentation for this part says: 
`The additional parameters to pass to the WMS server when requesting images. All parameter names must be entered in lowercase in order to be consistent with references in the TerriaJS code. If this property is undefined, WebMapServiceCatalogItem.defaultParameters is used.`

If we check the actual implementation of the WMS group we can notice that the parameters group is set to undefined and actual parameters specified by the user are not used at all. Also, the same thing should probably be addressed for end user-added data. Currently, all request parameters are cleaned and replaced with generic WMS getCapabilities request (not sure if it is meant to be done this way but IMO it limits users)

The same thing is happening with a WMTS group. On the other hand, a WFS catalog group doesn't even specify parameters as an option.

Steps to reproduce,
1) add this to catalog init file
```
{
	"name": "WMS group parameters",
	"type": "wms-getCapabilities",
	"url": "https://cida.usgs.gov/nwc/geoserver/ows",
	"parameters": {
		"namespace": "BioData"
	}
}
```
2) Check the group content in terriamap, there are over 20 layers, while the [actual request](https://cida.usgs.gov/nwc/geoserver/ows?service=wms&version=1.3.0&request=GetCapabilities&namespace=BioData) to the server returns only one layer
3) Also, check the network request sent by terria it is without namespace parameter (http://localhost:8080/geoserver/ows?service=WMS&request=GetCapabilities&version=1.3.0&tiled=true)

**Comment by hardreddata** [comment]
Thanks @zoran995 for documenting this.

I have worked out I can do the equivalent of
```
https://cida.usgs.gov/nwc/geoserver/BioData/ows?service=wms&version=1.3.0&request=GetCapabilities
```
putting the namespace after `geoserver`

per https://docs.geoserver.org/latest/en/user/configuration/virtual-services.html

**Comment by magneticsoil** [comment]
For anyone looking for a solution to this, it can be found here in issue: #3159

"parameters" must be specified under "itemProperties", like so:

```
  "itemProperties": {
    "parameters": {
      "login": "c1387c7d-7660-47c4-95da-457bc2631cf4",
      "password": "sk64k5k0"
    }
  }
```

**Comment by nf-s** [comment]
I'm going to close this issue, as @magneticsoil provided a solution for version 8
