### ISSUE TITLE
Search for data as well as location

### ISSUE THREAD

**Issue by hilarycinis** [TerriaJS/terriajs#415]
CKAN investigation for possibilies?

Wireframes and interaction directions are currently in design stage

**Comment by hilarycinis** [comment]
@kring Can you please increase the font size in the search text entry field as its very small? 

Please match the font size in the rest of the navigation pane. 

![screen shot 2015-01-19 at 4 20 14 pm](https://cloud.githubusercontent.com/assets/6046521/5796262/b843fefe-9ff8-11e4-9548-8ee787a5869d.png)

**Comment by kring** [comment]
@philipgrimmett do you want to do this one while you're making the other changes to the CSS?

**Comment by kring** [comment]
This has been addressed.
