### ISSUE TITLE
Mobx: Location search result missing "no results message"

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4150]
Due to the excellent work done in https://github.com/TerriaJS/terriajs/pull/3979, we now filter out results if a `locationSearchBoundingBox` is provided in parameters - however the "no results found" message is set at the individual search provider level.

Reproduce:
1. https://nsw.digitaltwin.terria.io/ (bounding box set to Australia)
2. Location search for "pe"
3. Observe empty results once loaded
4. Change location search term to 
5. Observe "Sorry, no locations match your search query." (as you should have expected in #3)

And more simply
1. http://ci.terria.io/mobx/ (no bounding box set)
2. Observe steps 2-3 from NSW DT show the results that got filtered out

(This has a flow on usability effect from the new UI which will appear from the work done at https://github.com/TerriaJS/nsw-digital-twin/issues/248 but will be temporarily hot-fixed to improve the usability from there)

**Comment by rowanwins** [comment]
Appears to be resolved in http://ci.terria.io/mobx/

**Comment by soyarsauce** [comment]
This is not resolved

**Comment by soyarsauce** [comment]
Actually it got resolved "for free" by showing the number of filtered results in the heading, instead of a message. Guess we roll with this
