### ISSUE TITLE
Story: Data layer display order is not preserved

### ISSUE THREAD

**Issue by zdefne-usgs** [TerriaJS/terriajs#4168]
While under Coronavirus lockdown I gave the Terria Story a shot and really enjoyed how simple it is to create a narrative!
https://map.terria.io/#share=s-2BjhXyjg7nL1kHT9fsmLWoVJVDq

However, I believe I also discovered a bug. When I open the story in Opera everything seems to work fine, but with Chrome not so much. Here's what happens: 

After proceeding to the second page of the story (titled "The epidemic travels across continents") after one loop of the animation the map stops displaying the top layer (the inner circles).

I tried `"keepOnTop": true` but, it did not make any difference. 

Is it related to "some inconsistency between nowviewingIndex" mentioned in https://github.com/TerriaJS/terriajs/issues/3535 or the issue in https://github.com/TerriaJS/terriajs/issues/3789 I don't know. I am just reporting. Maybe someone else who is also bored of being lockdown like me may have spare time to kill. Thanks!

**Comment by tephenavies** [comment]
Hi @zdefne-usgs. I'm glad you enjoyed using stories. The team and I really like the story you've made.

I couldn't reproduce the bug that you reported on any browser (including Chrome Version 80.0.3987.149).

**Comment by zdefne-usgs** [comment]
I tried it again today and it seems to be working as expected. Caching in Chrome can be sticky sometimes so I wonder if that was the issue. Thanks for looking into it!
