### ISSUE TITLE
Data search result breadcrumbs

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4169]
As a map user, I want to see the hierarchy of where my data catalogue search results sit so I can find it again in the tree

![image.png](https://images.zenhubusercontent.com/5ca14bcde8443113da47c346/6bdd8634-5767-4ccb-a78b-61e7aa8acda7)

**Acceptance criteria:**
- [x] Clicking a search result of a catalog item shows the "breadcrumbs" of the selected catalog item at the bottom of the data catalogue
- [x] Breadcrumb has a globe icon
- [x] Breadcrumb background uses `$grey` from theme
- [x] Breadcrumb text uses `$dark` from theme
- [x] Clicking any of the parents of those breadcrumbs brings you out of search results, into the catalog with that group selected

(? To clarify with Vic) what does it mean to have a search result of a group like "Transport" or "NSW Digital Twin Secured"

![image.png](https://images.zenhubusercontent.com/5ca14bcde8443113da47c346/62c73cb0-8c9b-4f37-b945-7a813b4a1e2d)

**Comment by reginapramesti** [comment]
For reference 
https://projects.invisionapp.com/share/6GVY8M6WJ89#/screens/404322663

**Comment by soyarsauce** [comment]
Btw @reginapramesti I briefly looked at the branch you had on this a while back and it seemed good, is it in a PR-able state?

**Comment by reginapramesti** [comment]
Yup, I think it might be, just completely slipped my mind when I got busy with onboarding. I'll create a PR for this

**Comment by soyarsauce** [comment]
@vicborgy I had a bit of a play around with regina's PR and it made me want breadcrumbs always - what do you think?

**Comment by reginapramesti** [comment]
I second this, I quite like having it all the time actually

**Comment by vicborgy** [comment]
@soyarsauce sorry a few Github messages have slipped through the cracks. Where is the link to se it live? Sorry I've forgotten how to get it lol

**Comment by soyarsauce** [comment]
@vicborgy no problems - it's currently only on maps that have data search enabled, try a search on QLD - https://qld.digitaltwin.terria.io/

**Comment by vicborgy** [comment]
Looks good. 👍

**Comment by soyarsauce** [comment]
@vicborgy great! However the current question is now whether there are any downsides to having the breadcrumbs always showing rather than only when searching - I can't see any (other than "clutter" but it feels so nice to be able to see breadcrumbs all the time)

**Comment by vicborgy** [comment]
Right ok. I don't see the breadcrumbs until I perform a search. I dont mind it always appearing as I think it will help to have it there especially when there is a large list of items and the folder is out of view.

**Comment by rowanwins** [comment]
Resolved by #4429 and #4589
