### ISSUE TITLE
Merge Getting Started with How it works, genericise

### ISSUE THREAD

**Issue by alyce** [TerriaJS/terriajs#4173]
The 'How it works' content is valuable in addition to Help videos as it provides multi-modal delivery of help information and also helps us with accessibility requirements (providing a text summary of visual content). 
To minimise the initial onboarding options we are going to consolidate 'How it works' with the 'Getting Started' help option.

We need:
- Designs that incorporate some 'how it works' text as bullet points to appear underneath the Getting Started video
- Generic 'how it works' content
- Vanilla 'Getting started' video

**Comment by soyarsauce** [comment]
The "welcome message" ("Let's get you started") - is the video in this supposed to be the vanilla 'getting started' video?
@vicborgy @alyce 

(and an aside, I guess it will have to be OK that the colours in the provided default video* may not necessarily match a themed map if any modifications are made to the theming at all.)

![image](https://user-images.githubusercontent.com/9134432/77982716-b50bff00-7358-11ea-8a87-c022c95d14ae.png)

**Comment by alyce** [comment]
> The "welcome message" ("Let's get you started") - is the video in this supposed to be the vanilla 'getting started' video?
> @vicborgy @alyce
> 

Yes I guess that is a good place for it!

**Comment by alyce** [comment]
The first cut of the vanilla video lives in here: https://drive.google.com/drive/u/1/folders/1Xg_-1IDUtatz_mSgkTDOCRfVpsUA02-6

**Comment by alyce** [comment]
@vicborgy has designed the two panel layout for the text underneath the video: https://projects.invisionapp.com/share/VQWC0P9FC3D#/screens/408368057_Onboarding_4a_1

![Screen Shot 2020-04-08 at 8 56 42 am](https://user-images.githubusercontent.com/40975814/78727043-ebf49d00-7976-11ea-868c-1aa856e52aa8.png)

**Comment by alyce** [comment]
Text content for panel:

**Getting started with a map**
If you're new to the map or using spatial data, our Getting Started video quickly covers the basic functionality you'll need to use to add and interrogate data sets.

If you don't have time to watch the video, we suggest exploring the following areas:

1. Search for a location to quickly find an area of interest
2. Use 'Explore map data' to view the catalogue of available data sets and add them to the map
3. Interact with the data layer, including opacity and toggling on and off on the left in your workbench
4. Click on the data on the map to view more detailed data, including the raw data
5. Change your basemap using options in 'Map Settings' to help make some data sets more visible
6. Zoom and change your view, including tilting the view angle using the controls on the right-hand side of the screen

**Comment by AnaBelgun** [comment]
Getting started video link: https://youtu.be/NTtSM70rIvI
Embed: <iframe width="560" height="315" src="https://www.youtube.com/embed/NTtSM70rIvI" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by soyarsauce** [comment]
Hey @alyce @vicborgy 

Will you want any more help panel contents in addition to the below two for terria-cube testing?

Is it decided that the only "generic" piece is getting started for all maps (and I realise also, controls/navigation https://github.com/terriajs/terriajs/issues/4189), and we tack on satellite imagery for terriacube+DEA maps?

<img width="184" alt="image" src="https://user-images.githubusercontent.com/9134432/81627514-b2b1c000-9441-11ea-973a-7314ac8f897b.png">

**Comment by alyce** [comment]
@soyarsauce Could we also add the time series one? Ta

**Comment by soyarsauce** [comment]
@alyce sure - where can I find the generic* time series content/video? Or take it straight from NSW?

**Comment by alyce** [comment]
@soyarsauce just take it straight from NSW for now, it's just to show the example :)

**Comment by soyarsauce** [comment]
Heya @alyce what's outstanding from this ticket?

**Comment by alyce** [comment]
@soyarsauce just updating the video to be less speedy!

**Comment by soyarsauce** [comment]
Captured in https://github.com/TerriaJS/terriajs/issues/4368
