### ISSUE TITLE
Mobx (Design): Location search UI for multiple `locationSearchProviders`s

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4178]
With the new change of location search provided by:
https://github.com/TerriaJS/nsw-digital-twin/issues/248
https://github.com/TerriaJS/terriajs/pull/4162

Some relevant info
>if we have more than 5 results, in master you are able to expand the search results to see more. But not in the new design. How long should the search results get? Do we take 3?5? from each of the three categories
>- Locations
>- Official Place Names
>- Addresses

>Meaning a location search result list possibly spanning 15 results?

@vicborgy has said he will get a design together to address this.

Maybe a quick way forward is an expanded search results "view" in some way to restore the lost functionality in master.

### We've lost the following functionality from master:

- Ability to "view more results" for a given location search provider (up to 10)
- Ability to see what results come from what provider

![image](https://user-images.githubusercontent.com/9134432/76832226-0b6b3f00-687d-11ea-8be9-f57db81da876.png)

### Here's an example of our current search provider duplicated three times, in the absence of an implemented GazetteerSearchProviderViewModel && GnafSearchProviderViewModel in mobx:
<img width="352" alt="image" src="https://user-images.githubusercontent.com/9134432/77975082-c3e8b680-7344-11ea-841c-7b8c636d122b.png">

@steve9164 do you have any other things to add?

**Comment by soyarsauce** [comment]
anyway, terriajs#4178 re: multiple search providers - 2.5 options.
1: @borgy thinks up something revolutionary
2: we just sploosh all search provider results together so that there's 15 results instead of 5
2.5: show ~6 results, do "show more results" and that expands the rest in line

**Comment by vicborgy** [comment]
@soyarsauce here are my designs for location search. Any issues let me know
https://invis.io/H4XI8PTUVCA

**Comment by vicborgy** [comment]
https://invis.io/H4XI8PTUVCA

**Comment by AnaBelgun** [comment]
assigned 2 more epics, because it's important for both: Delta v3 and Onboarding v3, but especially for delta

**Comment by soyarsauce** [comment]
@AnaBelgun which part of this is relevant for delta/onboarding? This ticket is the "UI support" for multiple providers (and is merged now), but we don't have one tracking the actual port of gazetteer & gnaf searches - if you want to track those I'll close this and raise separate ticket for that?

**Comment by AnaBelgun** [comment]
Thanks @soyarsauce I thought it would be important because this is one of the 1st actions a user / new user would do: search for his location of interest. We can disconnect from the epic or leave as is, especially if done. I understand it doesn't come from this last testing, therefore I'll disconnect from that epic for clarity :)

**Comment by soyarsauce** [comment]
Thanks @AnaBelgun - all UI is done for this, including support for multiple search providers. Mobx will need to port the actual support for gnaf+gazetteer - tracked in https://github.com/TerriaJS/terriajs/issues/4424
