### ISSUE TITLE
Onboarding v2 - Welcome Message

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4180]
As a new map user,
I want to see a welcome message the first time I visit,
so I have some guidance on how to get started

**Design file**: `terria-onboarding.sketch` in https://drive.google.com/open?id=1ihNj5hr9pXnJxhsP9S9sRqvxntd4RVbz

**Invision**: https://projects.invisionapp.com/share/VQWC0P9FC3D#/screens/408368058

Other notes from Vic:
>Welcome message - I’ve focused new designs on what people see when they load Terria for the first time, making it more about us wanting to help them. So, there is room for discussion about what links we show. It should really offer support from the get go and not just a brief intro

Currently we have a welcome message that can be repurposed for this (`<WelcomeMessage />`)

![image.png](https://images.zenhubusercontent.com/5ca14bcde8443113da47c346/f8e69abd-6478-4dbe-9dd7-5bce0c94f10e)

The new one is more like:
![image.png](https://images.zenhubusercontent.com/5ca14bcde8443113da47c346/798f1f86-2ae1-4c4c-9921-1018e23da596)

### DoD:
- [ ] Unit test written (if applicable)
- [x] Works on mobile (or deliberately disabled for mobile)
- [x] Code/peer reviewed (if didn't pair)
- [ ] Relevant docs are updated
- [x] Previewable/deployed to dev (see separation of deployments)
- [x] Previewable/deployed to test (see separation of deployments)
- [ ] (If a map-specific ticket) Issue linked to a release ticket

### Acceptance Criteria:
- [x] Welcome message is OPT-IN, for the map owner. (e.g. configured at runtime/per terriamap, whether to show the welcome message for the map's users)
- [x] WelcomeMessage.jsx is repurposed into this new design
- [x] message fades in/out on open/close
- [x] message has a video and placeholder thumbnail (reuse old thumbnails/video links until we have the generic one)
- [x] message has (a `disabled`?) "take the tour" button that does nothing (placeholder for starting non-existent tour)
- [x] message has "I'll need some help" button that opens to help menu
- [x] message has "explore map data" button which opens the data catalog
- [x] message buttons have new relevant icons
- [x] buttons are using the tjs `Button.jsx` component framework

- [x] modal can be closed with "close message and don't show me this again"
- [x] modal can be closed with "X"
- [x] modal can be closed with escape key
- [x] modal doesn't open when map is embedded
- [x] bit of padding for the invisible box, click outside that will close 

- [ ] when modal is dismissed, save user preference to never show again **regardless of closure method** (dismissed from button action or explicit user close action) via `WELCOME_MESSAGE_NAME` (local key compiled down to welcomeMessagePrompt)

**Comment by soyarsauce** [comment]
Some other notes, @reginapramesti you'll have to remove the ObserveModelMixin & any other knockout related features of WelcomeMessage.jsx so that it can be used in mobx. Right now it's disabled.

**Comment by soyarsauce** [comment]
Clarification of video to be used: https://github.com/TerriaJS/terriajs/issues/4173#issuecomment-606371365

**Comment by soyarsauce** [comment]
I've just written ` message fades in/out on open/close` as one of the AC as there aren't any transitions defined in invision, but @vicborgy let me know if you had other ideas, otherwise it'll be a fade.

**Comment by soyarsauce** [comment]
Finally, mobile idea for you @reginapramesti is just to wrap the components as I've done for DEA in http://de-africa.terria.io/
<img width="393" alt="image" src="https://user-images.githubusercontent.com/9134432/77983663-4b412480-735b-11ea-81cb-02eb94ab599d.png">

**Comment by vicborgy** [comment]
@soyarsauce its cutting off for me at the top so i cant test the fade you're talking about.
Can we force a return after 'data' so we have 2 words on each line?
Also can we try and vertically align in too?


![de-africa](https://user-images.githubusercontent.com/51101555/77984463-572de600-735d-11ea-91e1-ce4a7e681d2e.png)

**Comment by soyarsauce** [comment]
@vicborgy see https://terria.slack.com/files/U5EQGEABB/F010RPZS3FD/trigger-welcome.mov

**Comment by soyarsauce** [comment]
Hide take a tour for mobile
hide video for mobile
stack buttons for mobile

**Comment by soyarsauce** [comment]
close forever - same text size as paragraph text

**Comment by soyarsauce** [comment]
@AnaBelgun to write the copy below "let's get you started"

**Comment by AnaBelgun** [comment]
Let's get you started!
"Interested in data discovery and exploration?
Dive right in and get started or check the following help guide options."

**Comment by soyarsauce** [comment]
bit of padding for the invisible box, click outside that will close  (30px)

**Comment by soyarsauce** [comment]
all AC passes except for contended
>when modal is dismissed, save user preference to never show again regardless of closure method (dismissed from button action or explicit user close action) via WELCOME_MESSAGE_NAME (local key compiled down to welcomeMessagePrompt)

compromise is having the welcome message opt in at this stage

**Comment by soyarsauce** [comment]
https://github.com/TerriaJS/terriajs/issues/4354
