### ISSUE TITLE
Mobx menu buttons styles changes to inactive

### ISSUE THREAD

**Issue by zoran995** [TerriaJS/terriajs#4186]
In the mobx branch, menu buttons doesn't keep the active style. For me personally it looks a bit odd that the opened menu button doesn't indicate that it is currently open. I am not sure if this is intentionally done with new design concepts. There was a similar issue on the master that was addressed in #3850 

![2020-03-31 141215](https://user-images.githubusercontent.com/19208948/78025117-bf7ac880-7359-11ea-884a-043f95acbedd.png)

![2020-03-31 141033](https://user-images.githubusercontent.com/19208948/78025098-b7bb2400-7359-11ea-8d5c-dd329435d63c.png)

**Comment by soyarsauce** [comment]
Hey @zoran995 - this is certainly unintended from my point of view - @vicborgy ?

**Comment by vicborgy** [comment]
Hi @zoran995 this is currently in my lap for review and I agree that this isn't how it should work. This will be on my list of updates we need complete so I will ensure this is addressed.

**Comment by zoran995** [comment]
this seems to be fixed, if someone knows which PR fixed it would be nice to link it for reference
