### ISSUE TITLE
Update 'Helpful hints' content in workbench to be helpful

### ISSUE THREAD

**Issue by alyce** [TerriaJS/terriajs#4188]
Since we're not covering the Workbench in the Tour feature, it's worth us updating the 'Helpful hints' content that appears in the workbench to be more helpful and clarify some of the Workbench functionality (since this is a point of confusion).

**Comment by alyce** [comment]
Some thoughts:

> Current:
> Helpful hints
> All your active data sets will be listed here.
> Click 'Explore map data' above to browse the Data Catalogue or click 'Upload' to load your own data onto the map.


Proposed:

-  Browse available data by selecting ‘Explore map data’ or click ‘Upload’ to add your own data to the map

- Once you’ve added data to the map, your active data sets are listed here in your workbench. The workbench will help you to interact with the data

- In the workbench you can toggle data sets on and off, change their opacity, activate the split screen comparison, change styles, and navigate through dates and times, if the data supports this functionality

**Comment by alyce** [comment]
Take the tour introduction text @vicborgy ; 

![Screenshot 2020-04-07 11 36 35](https://user-images.githubusercontent.com/40975814/78620811-54367680-78c4-11ea-8625-da6178153c62.png)

Maybe it could say:
Unsure of where to begin? Take a quick tour of the six main features of our software, and learn about some of the key functions to help you get on your way.

**Comment by alyce** [comment]
> Some thoughts:
> 
> > Current:
> > Helpful hints
> > All your active data sets will be listed here.
> > Click 'Explore map data' above to browse the Data Catalogue or click 'Upload' to load your own data onto the map.
> 
> Proposed:
> 
> * Browse available data by selecting ‘Explore map data’ or click ‘Upload’ to add your own data to the map
> * Once you’ve added data to the map, your active data sets are listed here in your workbench. The workbench will help you to interact with the data
> * In the workbench you can toggle data sets on and off, change their opacity, activate the split screen comparison, change styles, and navigate through dates and times, if the data supports this functionality

@reginapramesti here's the proposed new Helpful Hints copy :)

**Comment by reginapramesti** [comment]
Helpful hints updated as part of #4332
