### ISSUE TITLE
Create a generic controls/navigation video for the Help section

### ISSUE THREAD

**Issue by alyce** [TerriaJS/terriajs#4189]
Navigation issues aren't solely for the Digital Twin so having a generic controls/navigation video will mean we can always link to this type of content from the Help menu regardless of the map it appears on.

The Digital Twin video can be used as a template, but the generic video will also have to show how the controls change for 3D and 2D maps.

**Comment by soyarsauce** [comment]
Eventually when all onboarding gets pushed to all the maps

Show in the video, show the change between a 2d / 3d dataset

**Comment by soyarsauce** [comment]
@AnaBelgun to point to NM 3d dataset to test

**Comment by soyarsauce** [comment]
@AnaBelgun can you show a NM 3d dataset that Alyce+Vic can use for the generic controls/navigation video?

@alyce when you put this together, could you also do the "text summary" content below for the video? 🙏

**Comment by AnaBelgun** [comment]
@soyarsauce @alyce I couldn't find the Melb one on NatMap anylonger 
But if generic, we could use the ones on our TerriaMap: https://map.terria.io/#share=s-dJOOnE4Zs9NfDdTsIU0EiAas4pu
There are 3 models from Aerometrex

**Comment by alyce** [comment]
Great, thank you @AnaBelgun :)

**Comment by AnaBelgun** [comment]
to refine if we still need this as part of onboarding v3 https://github.com/TerriaJS/terriajs/issues/4391

**Comment by soyarsauce** [comment]
Do you want to backlog this @alyce ?

**Comment by soyarsauce** [comment]
Or still want generic navigation content?

**Comment by alyce** [comment]
@soyarsauce I think it's important but we can backlog for now - it's very hard to film videos with mobx not always behaving super well and juggling CI instances.

**Comment by soyarsauce** [comment]
A QLD one exists at https://www.youtube.com/watch?v=9RVpLjxoCXo

Marie; leave it in the backlog

**Comment by AnaBelgun** [comment]
Not to be done atm.
