### ISSUE TITLE
Update TerriaMap & related for hardcoded colours

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4193]
These colours are hardcoded (due to the NSW push) - now bringing them back to use theme colours
<img width="563" alt="image" src="https://user-images.githubusercontent.com/9134432/78204555-8c654000-74e5-11ea-8829-0b9ac72e73b8.png">
<img width="187" alt="image" src="https://user-images.githubusercontent.com/9134432/78204560-8ec79a00-74e5-11ea-96d0-b613f8bcafb2.png">

**Comment by AnaBelgun** [comment]
If PR #4194 merged, can this be closed?
