### ISSUE TITLE
Mobx: arcgis/esri mapserver layer/name resolution

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4195]
Given the mapserver
http://services.ga.gov.au/gis/rest/services/NM_Culture_and_Infrastructure/MapServer

and the catalog item

```
{
            "url": "http://services.ga.gov.au/gis/rest/services/NM_Culture_and_Infrastructure/MapServer",
            "layers": "Powerlines,No_Data",
            "name": "Powerlines",
            "type": "esri-mapServer",
            "info": [
                {
                    "name": "Licence",
                    "content": "[Creative Commons Attribution 4.0 International (CC BY 4.0)](http://creativecommons.org/licenses/by/4.0/)"
                }
            ]
}
```

It shows different things in master and mobx:
- master successfully knows it should use the powerlines layer
- mobx defaults to the "Storage Tanks" layer, and is also missing a legend

Master: http://ci.terria.io/master/#share=s-gWAp544KBSRbHXFt6FPVqlLG9Fb
Mobx: http://ci.terria.io/mobx/#https://gist.githubusercontent.com/soyarsauce/3c6db28419dac2e9009e5d44da778d21/raw/fb7ab2f73377e18a5489fbe2fb7c451def448a20/infrastructure.json

**Comment by nf-s** [comment]
This is fixed http://ci.terria.io/main/#https://gist.githubusercontent.com/soyarsauce/3c6db28419dac2e9009e5d44da778d21/raw/fb7ab2f73377e18a5489fbe2fb7c451def448a20/infrastructure.json&share=s-9qECqwoht2zMHe72LkpsHg3QeeF
