### ISSUE TITLE
Mobx: sharing broken when you add a catalog with hash param

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4196]
Steps to reproduce:
1. visit http://ci.terria.io/mobx/#https://gist.githubusercontent.com/soyarsauce/3c6db28419dac2e9009e5d44da778d21/raw/fb7ab2f73377e18a5489fbe2fb7c451def448a20/infrastructure.json
2. add powerlines through data catalog
3. generate share link
4. observe error
`Unable to load MapServer`

`Could not load the ArcGis MapServer endpoint because the catalog item does not have a url.`

**Comment by soyarsauce** [comment]
Leave for week of may 18 for good2do

**Comment by nf-s** [comment]
Happy to look into this if time permits this sprint

**Comment by nf-s** [comment]
Fixed by #5687
