### ISSUE TITLE
Update terriajs-cesium to v1.68.0

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#4198]
To do a terriajs-cesium release:
- Set up a TerriaMap on master with yarn workspaces
- Clone both terriajs and terriajs-cesium into the "packages" directory
- In `packages/terriajs-cesium`:
    * Checkout `terriajs` branch
    * Merge from upstream (https://github.com/CesiumGS/cesium) using the `1.68` tag
- Test it in TerriaMap using yarn workspaces (you'll need a clone of terriajs as well as a terriajs-cesium in "packages" folder so you can set the `terriajs-cesium` version in terriajs and TerriaMap)
- Built terriajs-cesium with `npm run build`
- Publish terriajs-cesium to npm with `npm publish`
- Update package.json in terriajs master branch to use new version
- Test again
- Prepare for publishing new terriajs version to npm:
     * Follow instructions here https://github.com/TerriaJS/nationalmap/wiki/Releasing-NationalMap-and-InvestorMap#release-terriajs-nm-only
    * Publish a new version of terriajs to npm 
- Update TerriaMap master branch to use new published versions of terriajs and terriajs-cesium

After that there might be a little bit more to get `mobx` on terriajs-cesium 1.68.0.

**Comment by soyarsauce** [comment]
sounds like a good handbook entry to https://github.com/TerriaJS/handbook as well

**Comment by soyarsauce** [comment]
Probably change the steps around so that you set up TerriaMap with yarn workspaces first, e.g.
1. terriamap+workspace
2. clone terriajs-cesium into `packages/terriajs-cesium`
3. checkout terriajs branch
4. merge upstream
...etc

**Comment by kring** [comment]
I think you do need to run `npm run build` in Cesium to compile the glsl shaders to javascript. The prepublish script might do that automatically, though.

**Comment by tephenavies** [comment]
@kring I thought you shouldn't run `npm run build` because it will include a `Build` directory in the package. E.g. `terriajs-cesium@1.64.1` has no Build directory, but `terriajs-cesium@1.66.0` does (accidentally). The other thing that could cause that is something got merged from an upstream npmignore file, but this compare doesn't show that https://github.com/TerriaJS/cesium/compare/terriajs-1.64.1...TerriaJS:terriajs-1.66.0.

**Comment by kring** [comment]
I don't think `npm run build` will create the Build directory, it just creates some new .js files in the Source/Shaders directory. And I'm pretty sure nothing will work if they're not there.

**Comment by tephenavies** [comment]
Ahh ok. I probably ran some gulp task that created the build directory. I'll add `npm run build` to the instructions
