### ISSUE TITLE
Splitter left/right not working in Story

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#4200]
In this Story, in the last scene there are two raster layers shown using the Splitter. As can be seen they have Left and Right set, but on the map they are both shown on both sides of the splitter:

https://nsw.digitaltwin.terria.io/#share=s-44bg0FSI4NvlSAGiIqgUa7lRK7c

<img width="1680" alt="Screen Shot 2020-04-03 at 14 08 06" src="https://user-images.githubusercontent.com/5283003/78320208-a6ba1f00-75b4-11ea-81cc-581350597c53.png">

**Comment by rowanwins** [comment]
Appears to be resolved
![Screen_2020_09_25](https://user-images.githubusercontent.com/6735870/94226531-2957e180-ff3b-11ea-8624-25262f108ed5.jpg)
