### ISSUE TITLE
Remove pancake and gov-au as dependencies of TerriaJS mobx

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#4214]
`@gov.au/page-alerts` is used in NSWDT for one alert. We should decide either to use `@gov.au` design system more widely or remake this alert with simple divs.

Another solution would be to remove the NSWDT-custom things in TerriaJS and replace them with places where apps can inject their own views.

**Comment by soyarsauce** [comment]
@gov.au design system is build time - and yes the alert should have been done in NSWDT with whatever updates needed in terriajs to allow more TerriaMap<->terriajs.. "plug-ability" let's say.

**Comment by hardreddata** [comment]
I shall miss the mixing of the batter. It made me smile. Though I have no idea what it meant, if anything. 

As a non-government Terria builder, trying to maintain an independent map, the build chatter did seem very AU Govt heavy.

**Comment by tephenavies** [comment]
Closed by #4605.

@RussellGrew That's an interesting perspective on the prominence of AU Govt in the build messages. I hadn't thought of that. The design components are really good. The reason I decided to remove the dependency is because we were only using 1 component, and the pancake build system is a bit heavy for only 1 component.
