### ISSUE TITLE
Mobx: WFS and WMTS support

### ISSUE THREAD

**Issue by zoran995** [TerriaJS/terriajs#4218]
Are WFS and WMTS supported on the mobx branch, can't find them? If not do you plan to add them?

**Comment by nf-s** [comment]
Hey @zoran995
I'm looking into adding WFS support over the next week or so. Is there anything specific that you are after? 
Eg tiling, mvt support, filter query support
Thanks!

**Comment by zoran995** [comment]
Hi @nf-s thanks for working on this
Haven't thought much about specific stuff, just looking for basic implementation (never got enough time to implement it). All the features you mentioned in PR would be nice but it won't be easy to implement them especially styling (sld to cesium). 
Are you going with WFS 1.1.0 or 1.3.0? 
If you need some help in implementing this I can try to find some spare time to help.

**Comment by nf-s** [comment]
No problem!
Yeah sld to cesium would be a bit of work!
I am using 1.1.0 at the moment. 
There is a checklist of possible features in the [PR](https://github.com/TerriaJS/terriajs/pull/4591) , currently it is looking like I will just add the clip and ship (export layer by selecting an extent) for the first PR, and then we can discuss further development.

**Comment by soyarsauce** [comment]
Blocks https://github.com/TerriaJS/de-africa-map/issues/54 - required for wmts basemaps in de-africa

**Comment by nf-s** [comment]
Closed by #4720
