### ISSUE TITLE
Examples for CatalogItems

### ISSUE THREAD

**Issue by zoran995** [TerriaJS/terriajs#4220]
It would be nice to have examples for each Catalog item, so the user can quickly set up his catalogue resources without reading the entire documentation for that catalogue type, or even going to source code. This is handled very well in Cesium. 
This will also require changes in how docs are generated to include examples, there are already some examples in the code, but they are not visible on doc pages.

One example I just had to go to source code to check the names of attributes that are needed when setting MapBoxCatalogItem, mapId and accessToken are not even listed as possible parameters.

This is related for both master and mobx.

**Comment by rowanwins** [comment]
Underway in #4666 

![91124751-4bafd280-e6e3-11ea-9196-af8b902f80d1](https://user-images.githubusercontent.com/6735870/91126246-e78f0d80-e6e6-11ea-98a4-d55f4e24c9fe.jpg)

**Comment by KeyboardSounds** [comment]
Closing in favour of #4937
