### ISSUE TITLE
WMS parameter name can be converted to uppercase

### ISSUE THREAD

**Issue by martin-bom** [TerriaJS/terriajs#4223]
Hi,
I encounter a WMS request which only recognizes parameter names in uppercase.
e.g. SERVICE=wms&BBOX=...

using the default "bbox" parameter name returns the following error:
**_<ServiceException code="MissingOrInvalidParameter">Missing valid BBOX parameter</ServiceException>_**

Is it possible for these parameter names be configured to switch to uppercase?
Thank you.

**Comment by rowanwins** [comment]
Closing in favour on fixing on the serverside
