### ISSUE TITLE
Mobx 2D view - Coordinates and disclaimer

### ISSUE THREAD

**Issue by zoran995** [TerriaJS/terriajs#4225]
In cesium 2D viewer footer section (disclaimer and coordinates/scale bar) has lost its colour from master instance and become practically invisible on light background maps (for example Positron)
![Beleška 2020-04-15 211523](https://user-images.githubusercontent.com/19208948/79378827-45a02d00-7f5e-11ea-846a-f59423cfbb09.png)

**Comment by rowanwins** [comment]
Resolved by some PR or other
http://ci.terria.io/next/#share=s-okKq8QRYDs1wEKBcxZpqc2XffE4

**Comment by zoran995** [comment]
resolved by #4758
