### ISSUE TITLE
Mobx ArcGis Feature Server polygon outline color

### ISSUE THREAD

**Issue by zoran995** [TerriaJS/terriajs#4231]
I really love the work done by @mgcsls on implementation of `ArcGisFeatureServerCatalogItem`, but there is an issue with the implementation of polyline outline color when the entity is actually a polygon. 

In some cases, it can happen that polygon has both polyline and polygon graphics, which is described in GeoJsonCatalogItem ([those lines](https://github.com/TerriaJS/terriajs/blob/mobx/lib/Models/GeoJsonCatalogItem.ts#L332-L350)). 

In the implementation of FeatureServer catalog item, [first](https://github.com/TerriaJS/terriajs/blob/mobx/lib/Models/ArcGisFeatureServerCatalogItem.ts#L549-L557) is color of polyline set to `symbol.color` and [then](https://github.com/TerriaJS/terriajs/blob/mobx/lib/Models/ArcGisFeatureServerCatalogItem.ts#L574-L591) color of polygon outline to `symbol.outline.color`.

This is only issue in 3D, because it seems that 2D renderer knows about this case and uses only properties from polygon graphics. The first image is 2D, second is 3D view, polygons are defined with black outlines. 
![2D](https://user-images.githubusercontent.com/19208948/79591704-309bd900-80d9-11ea-9082-bad86d86de05.png) ![3D](https://user-images.githubusercontent.com/19208948/79591707-31cd0600-80d9-11ea-98ed-df7c2a8d237e.png)

**Comment by rowanwins** [comment]
Done in #4412
