### ISSUE TITLE
App crashes when clicking the timeline datepicker

### ISSUE THREAD

**Issue by na9da** [TerriaJS/terriajs#4238]
Steps to reproduce:

* Open this link http://ci.terria.io/mobx/#share=s-idLs8FCnMqudADXJYgbupYBmjpr
* Click on the date picker on the timeline at the bottom
* App crashes

**Comment by rowanwins** [comment]
No longer occurring

**Comment by soyarsauce** [comment]
Can still replicate this

**Comment by rowanwins** [comment]
Ah the datepicker - missed the critical part
![Screen_2020_06_05](https://user-images.githubusercontent.com/6735870/83833576-a4e51700-a72f-11ea-85b9-dafaa49d8298.jpg)

**Comment by reginapramesti** [comment]
Fixed by #4417
