### ISSUE TITLE
Create a catalogue converter to convert catalogue JSON files from TerriaJS v7 compatible to TerriaJS v8 compatible

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#4239]
Create a converter in JavaScript to convert a TerriaJS v7 catalogue to a TerriaJS v8 catalogue. This converter should provide functions to convert the following config:
* A single catalogue item of any type
* A whole catalogue
* Share data

It should run in the following environments:
- Node.js v10
- Browser (IE11+)

This is needed first for TerriaCube, but we will use it for many of our other maps as we migrate them. We'll also make it available to open source Terria users for migrating their own map catalogues.

**Comment by soyarsauce** [comment]
Have it available in some (browser)client-side tool via/linked-from terria.io as well

**Comment by soyarsauce** [comment]
Couple of problems so far,
- won't work with 
  * chart disclaimer, as it's changed from an old property to an attribute on a chart tag in a featureInfoTemplate - this is the only manual process in the DEA conversion so far

Just read source for what catalog items are currently supported
there's some types-map-esque in source.

**Comment by soyarsauce** [comment]
code is here 
https://github.com/TerriaJS/catalog-converter

there's a UI here
https://github.com/TerriaJS/catalog-converter-ui

**Comment by soyarsauce** [comment]
Related https://github.com/TerriaJS/terriajs/pull/4688

**Comment by rowanwins** [comment]
Notes on GeoGlam migration
https://github.com/TerriaJS/RaPPMap/issues/92

**Comment by rowanwins** [comment]
Notes on NEII migration
https://github.com/TerriaJS/neii-viewer/issues/157

**Comment by tephenavies** [comment]
Done. Both at https://catalog-converter.terria.io/ and used in terriajs v8 in some circumstances
