### ISSUE TITLE
IE-mobx: Show Workbench button shows even when workbench is showing

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#4241]
There are some issues with the NSW DT/mobx CSS where the Show Workbench button shows even when the workbench is showing.

There are also some alignment messiness that I've highlighted in the screenshot, but they aren't serious.

Using CSIRO Citrix BOE provided IE11.

<img width="1606" alt="Screen Shot 2020-04-22 at 12 59 35" src="https://user-images.githubusercontent.com/5283003/79935908-6c4bef80-8499-11ea-854a-f8904a712b96.png">

<img width="384" alt="Screen Shot 2020-04-22 at 13 00 46" src="https://user-images.githubusercontent.com/5283003/79935945-7d94fc00-8499-11ea-8022-374d64384a2c.png">

**Comment by tephenavies** [comment]
IE11 support removed from v8.
