### ISSUE TITLE
IE: Drought Map Add Data button is maaaassive, and compass controls are missing

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#4242]
When going to the Drought Map using IE11 the Add Data button is massive, and the compass controls are missing:

<img width="1605" alt="Screen Shot 2020-04-22 at 13 05 27" src="https://user-images.githubusercontent.com/5283003/79936151-001dbb80-849a-11ea-9a1a-9729c4982b7d.png">

<img width="384" alt="Screen Shot 2020-04-22 at 13 00 46" src="https://user-images.githubusercontent.com/5283003/79936160-07dd6000-849a-11ea-9d0a-cf99c93c4512.png">

**Comment by meh9** [comment]
Tested in NatMap and Add Data button is fine there, but compass controls are still missing.

**Comment by soyarsauce** [comment]
@meh9 add data is a css problem yes, but the compass control is because you are on 2d mode and not 3d

**Comment by meh9** [comment]
> 2d mode and not 3d

Hahaha, user error indeed!

**Comment by zoran995** [comment]
IE is not supported anymore
