### ISSUE TITLE
MS Edge white screen of death on Drought Map

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#4243]
@marietruelove reported getting a white screen of death when loading the Drought Map in MS Edge, but that NationalMap and NSW DT both work.

![ezgif-3-26a1dd109a4a](https://user-images.githubusercontent.com/5283003/79936594-3445ac00-849b-11ea-8d8a-1583a8692bd3.gif)

**Comment by soyarsauce** [comment]
I cannot white screen of death on edge 81.0.416, @marietruelove are you able to confirm what version you saw this?

**Comment by soyarsauce** [comment]
Couldn't white screen on edge 44 either

**Comment by marietruelove** [comment]
yes I can its Microsoft Edge 44.17763.831.0, but interestingly since I got back from lunch it is now working - no white screen !

**Comment by marietruelove** [comment]
some more testing, not occuring, will close

**Comment by soyarsauce** [comment]
Really strange given we haven't updated droughtmap around your lunchtime - so please ping again if you see it again!
