### ISSUE TITLE
Region mapped CSV with just region column should have a legend in mobx

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#4245]
http://ci.terria.io/mobx/#share=s-t6fWlUD2GehsK0vHHVm6kmxEOJ4 should have a legend showing that this layer is blue: 
![image](https://user-images.githubusercontent.com/13863530/79997504-05f8b880-84fd-11ea-9c9d-a694430a37d7.png)

See http://ci.terria.io/master/#share=s-7i1ZgiQUzWB51Gf0PQUozhVWMPk (which colours the regions white, hence white legend):
![image](https://user-images.githubusercontent.com/13863530/79997645-23c61d80-84fd-11ea-8ec7-1d536e9bb211.png)

**Comment by nf-s** [comment]
I'm happy to take this on!
It is definitely relevant to YDYR

**Comment by rowanwins** [comment]
@nf-s you might want to check what happens in this PR
https://github.com/TerriaJS/terriajs/pull/4120

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/4393
