### ISSUE TITLE
Support for 2D polygons with holes

### ISSUE THREAD

**Issue by bwyss** [TerriaJS/terriajs#4255]
When importing a vector polygon that has holes in it, all holes are rendered correctly in 3D modes, but are disregarded in 2D mode because the hierarchyToLatLngs function (https://github.com/TerriaJS/terriajs/blob/master/lib/Map/LeafletVisualizer.js#L530) does not handle polygons with holes. 
[example-holes-geojson.zip](https://github.com/TerriaJS/terriajs/files/4530278/example-holes-geojson.zip)

![Screenshot from 2020-04-24 10-51-59](https://user-images.githubusercontent.com/340159/80237353-d5f30780-8619-11ea-9ed2-07579250aba1.png)
![Screenshot from 2020-04-24 10-52-17](https://user-images.githubusercontent.com/340159/80237359-d8556180-8619-11ea-9683-8c16efefc935.png)

Desired 2D rendering: 
![Screenshot from 2020-04-24 10-56-28](https://user-images.githubusercontent.com/340159/80237634-4b5ed800-861a-11ea-84e6-18030b6677ba.png)

PR on its way:
```
function hierarchyToLatLngs(hierarchy) {
  let holes = [];
  var positions = Array.isArray(hierarchy) ? hierarchy : hierarchy.positions;

  // Manage polygons with holes
  if (hierarchy.holes.length > 0) {
    hierarchy.holes.forEach((hole) => {
      holes.push(convertEntityPositionsToLatLons(hole.positions));
    });
    return [convertEntityPositionsToLatLons(positions), holes];
  } else {
    return convertEntityPositionsToLatLons(positions);
  }
}

**Comment by rowanwins** [comment]
Solved in v8  by #4838
