### ISSUE TITLE
Mobx UI: compass is not aligned in chrome

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4261]
from @vicborgy 
![Screenshot 2020-04-29 13 27 07](https://user-images.githubusercontent.com/9134432/80563157-9408fd80-8a2d-11ea-8bf2-db2d565448ef.png)

![Screenshot 2020-04-29 13 25 55](https://user-images.githubusercontent.com/9134432/80563154-923f3a00-8a2d-11ea-96bc-e462683df6e3.png)

from @alyce : Mmmm it seems to only happen at 100% zoom on mine?

**Comment by vicborgy** [comment]
Looks good @soyarsauce happy to approve this

**Comment by soyarsauce** [comment]
Thanks Vic - this one is the issue though, the PR is at https://github.com/TerriaJS/terriajs/pull/4262 😛 anyway have noted your comment on the PR
