### ISSUE TITLE
MobX - Antimeridian issues in LeafletJS

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#4266]
This ticket is to record porting of antimeridian issue fixed in TerriaJS master (https://github.com/TerriaJS/terriajs/pull/4185/commits/f70534550cf7976094451f3b5f5a6b2c51824aff) 

https://github.com/TerriaJS/terriajs/pull/4185

in MobX Terria branch

**Comment by rowanwins** [comment]
resolved by #4339
