### ISSUE TITLE
MobX: add support for WCS 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#4268]
- placeholder for porting support of WCS in MobX
- linking previous issues related to current implementation of WCS in master: 

- [ ] improvements to v1 WCS - https://github.com/TerriaJS/terriajs/issues/3109

- [ ] support high res exports https://github.com/TerriaJS/terriajs/issues/3765

- [ ] automatically detect https://github.com/TerriaJS/terriajs/issues/3108 

This was v1 implementation https://github.com/TerriaJS/terriajs/issues/2937

**Comment by rowanwins** [comment]
Done in #4482 and #4461
