### ISSUE TITLE
MobX - Performance - Catalogue items & attribution

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#4271]
Catalog items & attribution updates(?) - @na9da please clarify this bit
to fix this - go through catalog items,
find the cesium APIs where we can update a given catalog item
and use that instead of re-creating them each time some attribute changes

**Comment by soyarsauce** [comment]
@na9da to give @steve9164 debug/profiling tips

**Comment by soyarsauce** [comment]
objectarraytraits were checking through entire array to see if it's been removed (via parent)
