### ISSUE TITLE
Latest mobx release can't be built with certain repos

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4276]
Running nsw-digital-twin against mobx 27 results in a build error

**Comment by rowanwins** [comment]
Superceded

**Comment by soyarsauce** [comment]
@rowanwins superceded by which ticket?

**Comment by soyarsauce** [comment]
(FWIW turns out #4277 only partially fixes something tangentially related to this, we still observed problems in both nsw and qld maps)

**Comment by AnaBelgun** [comment]
to fix if is impacting QLD DT releases by end of June

**Comment by tephenavies** [comment]
Is this still a problem?

**Comment by soyarsauce** [comment]
Shouldn't be as long as the problematic maps are regularly merging terriamap#next

**Comment by soyarsauce** [comment]
Fixed in https://github.com/TerriaJS/TerriaMap/pull/459/files
