### ISSUE TITLE
[EPIC] MobX UI i18n blockers

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4280]
We have a few things that we are adding to the mobx ui that will affect i18n-ability, namely:
### Map icon button
PR:
https://github.com/TerriaJS/terriajs/pull/4165#discussion_r401348748

Fix:
https://github.com/TerriaJS/terriajs/issues/4281

### Help menu items/panels
https://github.com/TerriaJS/terriajs/issues/4161
https://github.com/TerriaJS/terriajs/issues/4278

Unfortunately we need to ship these, but we also want to make things like this work with the new i18n translation files - and don't want to lose sight of them.

Also, we don't actually have a mechanism right now to swap languages in the UI itself, a TerriaMap consumer would need to do the overrides by forking terriajs which is an extremely unideal situation (might as well call it unsupported right now, even though all the framework is in place to i18n)

**Comment by zoran995** [comment]
There is some initial work on changes of i18next configuration started in #4227. 
To avoid users having to override translations by forking terriajs and updating directly it is necessary to support loading of translation from the backend (second point in draft PR), and for that, it is necessary to pass translation files during build so they are accessible. My experiments with this were to manually copy of `Language` folder to `TerriaMap/wwwroot` and it worked. This way user can edit translation file directly and changes will be visible the same way as for configuration files. It would be much better to keep translation files as default values and providing users with a possibility to override those value from TerriaMap, but have to look if this can be done and how. This way user would end with much smaller `.json` file to edit on his end and also easier upgrade between versions. 

Without this, I don't think it will be possible to i18n-ify help menu items. I have some ideas for it but have to do some testing.

I would like to hear other opinions on this, and if @vicborgy have/make a position for swap languages mechanism in his UI designs I would be happy to finish it.
