### ISSUE TITLE
My Data: Clicking a dataset changes tabs and clicking the add to map button deletes the dataset

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#4285]
![My Data screen recording](https://user-images.githubusercontent.com/13863530/81246214-49edd080-905a-11ea-8779-196617102588.gif)

Recorded on http://ci.terria.io/mobx/

This happens with any datasest added to My Data. Try for example URL `build/TerriaJS/test/csv/postcode_year_value.csv`

**Comment by soyarsauce** [comment]
Some more information - seems like a possible cause being that you add data with a url that already belongs in the provided catalog

**Comment by nf-s** [comment]
This seems to happen with "Auto-detected" datasets, when I specify WMS group I don't have this issue.
Eg - http://marine.ga.gov.au/geoserver/marine/wms?request=GetCapabilities
This behaviour happens regardless of whether that layer already exists in the Data Catalog.

Also the `DataDescription` is not showing in MyData

**Comment by nf-s** [comment]
Closed by #4747
