### ISSUE TITLE
Empty item is added to workbench when adding an incorrect URL.

### ISSUE THREAD

**Issue by na9da** [TerriaJS/terriajs#4295]
Steps to reproduce:

1) http://ci.terria.io/mobx/
2) Go to My Data > Add Web Data
3) Select a file type eg: csv
4) Paste an incorrect URL (eg: https://raw.githubusercontent.com/TerriaJS/terriajs/mobx-timeseries/wwwroot/test/csv/lat_lon_enum_date_id)
5) Click add

An empty item gets added to the workbench although the URL 404s. `master` however pops an error and nothing is added to the workbench.

**Comment by reginapramesti** [comment]
I tried to reproduce this on http://ci.terria.io/next/ and it's not happening, can you confirm this please @na9da? If it's fixed on `next` we should probably close this 😄

**Comment by na9da** [comment]
You are right, it no longer adds the empty item to the workbench. But I think we can still show the error to the user? Currently it just shows an uncaught exception in the console.

**Comment by nf-s** [comment]
We show an error now 

<img width="1274" alt="image" src="https://github.com/TerriaJS/terriajs/assets/6187649/467a776f-f56b-4089-a3ae-f02820c42e11">
