### ISSUE TITLE
Unlock rollbar when type issue resolved

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4303]
npm ERR! prepareGitDep node_modules/rollbar/index.d.ts(37,18): error TS2304: Cannot find name 'Context'.

npm ERR! prepareGitDep node_modules/rollbar/index.d.ts(38,19): error TS2315: Type 'Callback' is not generic.

**Comment by zoran995** [comment]
Error service is generic now, see #7264.
