### ISSUE TITLE
Onboarding v2 - Satellite imagery guide "slider-in-help-panel"

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4306]
The amazing help panel framework needs to be modified to allow "slider" mode, where you supply an array of slides and it shows that in the panel instead of the video+content.

The content can be found in `lib/ReactViews/Guide/satelliteGuideData.js`

<img width="382" alt="image" src="https://user-images.githubusercontent.com/9134432/81885913-b9296e80-95de-11ea-9598-4f22826e4baa.png">

**Comment by soyarsauce** [comment]
(@reginapramesti I'm thinking you can just make the help panel switch on some key, like "paneMode: slider" or "paneMode: videoAndContent" as a really basic example, that way you can split up the panel render rather than trying to force it all in the same render block)

**Comment by reginapramesti** [comment]
Note: we still need to do it the configurable/non-hacky way

**Comment by soyarsauce** [comment]
@reginapramesti do you still want to address the `Note: we still need to do it the configurable/non-hacky way` part?

**Comment by reginapramesti** [comment]
I think ideally we should but I imagine it's not so much of a priority, so I'm not sure if we should keep this issue or just open up a new one as a TODO

**Comment by AnaBelgun** [comment]
@reginapramesti please open a new issue
I'm closing all v2 issues to avoid confusion with post testing tickets which will be under new epic Onboarding v3 https://github.com/TerriaJS/terriajs/issues/4391
