### ISSUE TITLE
"Difference" - close button interaction w/ splitter

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4307]
as noted in 
> i just realised this - left/first file is delta in development, right side is designs
![image](https://user-images.githubusercontent.com/9134432/81892543-b20a5c80-95ee-11ea-800d-37d71098df68.png)

given difference utilises splitter, we'll hide the splitter when using the difference tool, and explore edge cases later

**Comment by soyarsauce** [comment]
Let's have a "disabled splitter button" when delta is on, e.g. continue to display the splitter button on the right hand side, rather than hiding it and thus making the difference tool seem like it's toggled from the side

**Comment by rowanwins** [comment]
Done in #4643
