### ISSUE TITLE
Post testing delta fixes

### ISSUE THREAD

**Issue by na9da** [TerriaJS/terriajs#4311]
Some issues for post-delta/testing

- [ ]  removing the delta source item from workbench keeps the diff tool open, should probably close it if it isn't referenced in workbench anymore
- [ ]  bottom date pickers cover up the timeline + logo area
- [x] The output diff item in workbench should hide the menu option to invoke Difference tool again
- [x] #4309 
- [x] Left/right items loose the split direction sense when the tool is reset
- [ ] The output item should show legend

**Comment by rowanwins** [comment]
Can this be closed @na9da with the latest delta changes?
