### ISSUE TITLE
Certain `helpContent` formats leads to crashing upon load

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4316]
Seems like the `helpContent` `markdownText` key needs to parse to more than 1 react component so that it doesn't crash when trying to render. Repro:
1. load up a terriamap with parameters.helpContent set to something like:
```
            {
                "itemName": "placeholder",
                "title": "placeholder",
                "paneMode": "videoAndContent",
                "markdownText": "# Placeholder content",
                "icon": "video"
            }
```
2. observe crash on load `index.js:188 TypeError: this.props.content.map is not a function`

3. change `                "markdownText": "# Placeholder content",` to `"markdownText": "# Placeholder content\nparsed to two react objects",`
4. observe app loads now

**Comment by reginapramesti** [comment]
I believe this is fixed, can't replicate anymore. If someone else can confirm, let's close this issue 😄

**Comment by soyarsauce** [comment]
Yep! It handles it fine with the new changes to markdown now
