### ISSUE TITLE
Quick tweaks - Change detection (delta/difference)

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4320]
- [x] location picker - doesn't carry over location into delta, reuse locataion marker if it exists.
- [x] make location marker orange once in difference mode.
- [x] once a location is detected, update copy (title) to reflect your selected lat+lng point is blah.
- [x] show disabled "generate change detection" button. + orange button.
- [x] show legend image for output item

**Comment by soyarsauce** [comment]
For copy when location is detected, could we use something like: "You've selected the location (lat, long)"

**Comment by soyarsauce** [comment]
>location picker - doesn't carry over location into delta, reuse locataion marker if it exists.

this one is https://github.com/TerriaJS/terriajs/pull/4329

**Comment by AnaBelgun** [comment]
location picker moved to separate ticket and merged as well https://github.com/TerriaJS/terriajs/pull/4329
