### ISSUE TITLE
Mobx: Sometimes scalar legends on table data have more bins than values

### ISSUE THREAD

**Issue by rowanwins** [TerriaJS/terriajs#4325]
If the number of unique values in a dataset is very low and there in no `numberOfBins` set in `TableColorStyleTraits` then you can end up with some funky presentation, eg

![ScalarBins](https://user-images.githubusercontent.com/6735870/82213711-f6338f00-9957-11ea-8de7-91815b8b9992.jpg)

**Comment by soyarsauce** [comment]
Related https://github.com/TerriaJS/terriajs/issues/4263

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/4326
