### ISSUE TITLE
MVT Layer:  Unexpected geometry type: 2 in region map on tile 6/11/25

### ISSUE THREAD

**Issue by electricsam** [TerriaJS/terriajs#4327]
I am trying to display a ship cruise using MVT.  When zoomed out, a polygon outline of the cruise should displayed.  When zoomed in, the path of the cruise should [be](url) displayed.

When zoomed out, it works as expected.  However, once I zoom in the following error is printed in the console:

```
Unexpected geometry type: 2 in region map on tile 6/11/25
```

Using the same tileset works as expected in a simple OpenLayers application.

Here is my catalog configuration:

```
        {
          "name": "EchoFish",
          "type": "mvt",
          "url": "/tiles/{z}/{x}/{y}.pbf",
          "description": "EchoFish",
          "layer": "echofish",
          "treat404AsError": false,
          "lineColor": "yellow",
          "fillColor": "yellow",
          "isEnabled": true
        },
```

Attached is the MVT tileset and the GeoJson that was used to generate it.  This cruise is on the west coast of the U.S.

[cruise.zip](https://github.com/TerriaJS/terriajs/files/4645758/cruise.zip)

**Comment by rowanwins** [comment]
Thanks for the bug report @electricsam 

Our MVT support is somewhat limited at the moment - I don't think we support LineString geometries yet. But it's on our roadmap to improve.

**Comment by nf-s** [comment]
Should be fixed with new protomaps support https://github.com/TerriaJS/terriajs/pull/5736
