### ISSUE TITLE
Don't show filter by location buttons for WMS layers that don't support it

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#4330]
These buttons should only show up for datasets that support filtering imagery dates by location.

![image](https://user-images.githubusercontent.com/13863530/82179281-45120200-9921-11ea-9587-339d287bd75a.png)

Check `Workbench.hasTimeWMS` to see if implementing a similar check is appropriate here.

**Comment by rowanwins** [comment]
I believe this is resolved in `mobx` branch already?

http://ci.terria.io/mobx/#share=s-i0127ylWtXzi1Cg4gMHXxBQrj0p

I remember seeing the issue but can't replicate any more, and can't find a PR which dealt with it.

**Comment by tephenavies** [comment]
Looks like it's fixed. Thanks for updating this.
