### ISSUE TITLE
User drawing CallbackProperty running forever

### ISSUE THREAD

**Issue by zoran995** [TerriaJS/terriajs#4333]
In the `UserDrawing` component CallbackProperty for polyline and polygon entity stays running even after the user finished using the function. A quick fix is to replace `CallbackProperty` with `ConstantProperty` during the cleanup, does anyone have some other suggestion?

p.s. I am not sure if this affect performance in general and should it be connected with #4263

**Comment by nf-s** [comment]
Hi @zoran995 I couldn't recreate this, is this happening with all of the latest `UserDrawing` changes?
