### ISSUE TITLE
Mobx: timeline datepicker crashes UI

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4335]
repro:
1. load ci.terria.io/mobx/#https://gist.githubusercontent.com/soyarsauce/427583294a53dfbd13e35d820ac66467/raw/688a57e9d5f184c2b6ddb32b892493a4c567aa6d/delta-mobx.json
2. add delta blended service from data catalog
3. click calendar icon in timeline
4. observe ui crash

**Comment by reginapramesti** [comment]
I think this is fixed by https://github.com/TerriaJS/terriajs/pull/4417
