### ISSUE TITLE
Mobx: Clip and ship

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4340]
Port master's clip and ship to mobx
For: https://github.com/TerriaJS/terria-cube/issues/48

Similar: https://github.com/TerriaJS/terriajs/issues/3109

**Comment by soyarsauce** [comment]
"Download" is a high level problem that DEA want fixed in next FY - want different ways for accessing data incl. download.
One easy way is a high res image
Second is actual data

**Comment by soyarsauce** [comment]
Required for June30

**Comment by nf-s** [comment]
Sorry I'm doing this now
