### ISSUE TITLE
Add URL Parameter for WMS GetCapabilities Request

### ISSUE THREAD

**Issue by alexgleith** [TerriaJS/terriajs#435]
Hi There

We can add our WMS getCapability URL, here: https://maps.gcc.tas.gov.au/geoserver/GCC_cc/gwc/service/wms?version=1.1.1&request=GetCapabilities easily to the National Map. But there are some concerns that this is a little obscure for the average punter.

I thought that there might be a way to form a url with a parameter, like you do with the data_url parameter for embedding in data.gov.au, to pre-load an external getCapabilities list of WMS layers in national map. Now, I tried, and I looked here: https://github.com/NICTA/nationalmap/blob/8aee06d98e050399d795cab357861362f5456c6a/src/GeoDataCollection.js and found how to wrangle URL parameters, and I now know that you don’t support this now. So.

Feature request: support adding a WMS GetCapabilities Request as a URL parameter, and add those layers identified to the user interface in some form for users to turn layers on and off.

I think it should be fairly straight forward, seeing as you already wrangle the request. It’s just a matter of looking for and grabbing a URL parameter.

I hope you can implement it for us!

**Comment by kgrochow** [comment]
This has been resolved with the new #start url mechanism which allows everything possible in the init file to be passed into NM via the url.  Documentation is still coming, but you can get an idea if you look at the share url when you have the items selected you want.

**Comment by alexgleith** [comment]
Very nice! Well done and thanks. The new interface on the national map looks great.
