### ISSUE TITLE
DEA User testing: Videos missing X to close

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4359]
We have a generic "video overlay" from both
- welcome message
- help panes

Just need a close button, @vicborgy are you happy if we just use a white-bg-close-in-top-right-corner?

**Comment by vicborgy** [comment]
Link to new onboarding project with change:
https://invis.io/UHXI971XJ2T

**Comment by reginapramesti** [comment]
Resolved by #4384
