### ISSUE TITLE
Ensure clampToGround property of polygons is passed to holes in GeoJsonCatalogItem

### ISSUE THREAD

**Issue by rowanwins** [TerriaJS/terriajs#4360]
If a GeoJsonCatalogItem has a trait of `clampToGround` set to true but has holes, the holes will float around in space.

![BrokenBehaviour](https://user-images.githubusercontent.com/6735870/83093973-e4828200-a0e3-11ea-898d-19e49d6b43e7.jpg)

**Comment by nf-s** [comment]
I also need this too! Thanks

**Comment by rowanwins** [comment]
If you reckon it looks good @nf-s feel free to merge it :)

**Comment by rowanwins** [comment]
Resolved by #4361
