### ISSUE TITLE
Mobx: sometimes dropdown/select icon is in a weird spot

### ISSUE THREAD

**Issue by rowanwins** [TerriaJS/terriajs#4364]
![DropdownIcon](https://user-images.githubusercontent.com/6735870/83095998-e4848100-a0e7-11ea-8002-49a49957898a.jpg)

**Comment by nf-s** [comment]
Is this using @soyarsauce 's new Select styled component? That has been flawless for me.
https://github.com/TerriaJS/terriajs/pull/4288

**Comment by rowanwins** [comment]
Closing in favour of #4513
