### ISSUE TITLE
DE UX Testing: Onboarding tour/help tweaks for novice users

### ISSUE THREAD

**Issue by alyce** [TerriaJS/terriajs#4365]
Covering issues no. 1 and 7 of [spreadsheet](https://docs.google.com/spreadsheets/d/10eWTU44vUEk-NKm2UcUPEK7qeHSDnRzrXUbMV6nDuBE/edit#gid=0) (high priority):

**Issues**
> 1: A static tour and help pages were not the ideal path for novice users. Most wanted the ability to try the features as they were suggested, and indicated without the context of use it's not overly valuable. Some sort of guided wizard/interactive path would be a more ideal option.
> _"I would want to search for a location now!" (P01)_

> 7: I'll need some help content was not as granular or helpful as novice users expected. They wanted specific instructions and a walkthrough example in the more detailed help section. There is too much reliance on a person's memory and no ability to learn by doing.
> _"I think it needs to be far more particular" (P01)_

**Fixes**
Vic to design:
- Short term interim tweaks to I'll Need Some Help content utilising existing patterns of Help content. 
- To include more step by step content and images so users can read and 'do' at the same time. 
- No smarts in moving between steps- just 'next'. 
- Possibly need to remove index of Help panel to take up less real estate so people can read and 'do' at the same time without losing a lot of real estate. 
- Specifically start with instructions for adding satellite imagery to the map (see [https://github.com/TerriaJS/terriajs/issues/4381](https://github.com/TerriaJS/terriajs/issues/4381))
- Also reference some overarching concepts and basemap issue in satellite imagery help.

- Longer term solution parked but involves Terry the Wizard idea to create a much more interactive help solution

**Comment by vicborgy** [comment]
Hey team, here are my designs for a simple step by step walkthrough guide. I haven't finalised the items located in the 2nd level of the help menu but will be updating this soon.
https://invis.io/X6XK52ZRJ5D

**Comment by soyarsauce** [comment]
Great thanks @vicborgy - so mainly a in-place text guide to get us going, looks like it will do the trick!

 re this bit, what does the greyed out line represent? Is it a hover/active state or something else? (it's "active state" looks like item #2 but #1 has the 50% opacity on it) - could also use lots of contrast love 
 (Also 
![image](https://user-images.githubusercontent.com/9134432/83712437-232ab600-a669-11ea-8fc2-7eb25d3b6851.png)

@alyce + @vicborgy are you able to help coordinate/supply the various "step by step" items for each of the guides?

**Comment by vicborgy** [comment]
Oops, sorry I was meant to change that. It should actually be on the No.2 item, But just do them all 100% white for now. Will update designs.

**Comment by alyce** [comment]
Yes @soyarsauce I will be doing the content creation/writing next week :)

**Comment by rowanwins** [comment]
I'm struggling a little to see how this will help users at the moment ... 

- More fleshed out example content in the designs may help make it clearer
  - eg how many steps are can there be to an "Add data" flow?
  - And if all the top bar does is say 'click the explore map data button' in smaller text than the real 'Explore map data' button is that really going to help?

- There is nothing indicating that the top bar is a help/guide bar, it's just kinda appeared after they clicked something in the sidebar, and if they've never visited the app before it may not be terribly obvious that it wasn't there earlier.

- Having the primary button in the top bar as the task changer perhaps seems unintuitive, the user is there to progress through a particular task so shouldn't that should be the primary?

- Is the intention that the bar along the top is kept in sync with the actions of the user?
  - Eg if a step is to click the 'explore map data', and the user then completes the task, does the state of the help bar move to the next step? 
  - What if the user completes a couple of steps without referring to the guide? Do they then click through the guide steps manually to catchup and see if they've missed anything?


I'm not completely against the designs or approach, perhaps just needs a bit of refinement. And I think seeing some sample content/steps for a task would help make things clearer in my mind. 

And is it also possible to put the designs in front of someone from the user testing and getting a rough feel for whether it would've hit the mark?

**Comment by alyce** [comment]
@rowanwins the key problem we're trying to solve here is instructions that are shown out of context. This was a massive massive issue - relying on people's memory to remember instructions and tips is just unrealistic. Especially for novice users.

So this is a short term solution to fix that by having persistent instructions. It's not intended to be 'smart' at the moment, so the user would need to move through the steps manually - we have bigger plans for more of a smart, step by step wizard down the track but for now before EOFY deadlines are looking for something to make the help/guidance content available while the user does the task.

I have to write up the content and steps next week but hopefully that will make the concept more understandable!

We don't have time for any more user testing this FY but we're confident this is a massive improvement on the help content we currently have, that is a major pain point for us, users and the client.

**Comment by vicborgy** [comment]
@rowanwins I appreciate your concerns about this but this is why we test the product to get feedback. If we designed a product based on what 'we' think, novice users would have no idea what to do.
This step by step wizard is a short term fix designed to aid not solve the issue. I literally designed this in 1 day. As Alyce said we have a more detailed long terms solution that will solve the issue for novice users.
Also, the need to make this a primary colour 'is definitely' the right thing to do. Remember this doesn't appear by default. This is initiated from the 'Help' menu for users 'that need help', so it becomes the primary hero action/need.
We are happy to look at options outside of this if we think it could be better, but I would be hesitant to take direction from anyone that wasn't involved in user testing, doesn't have a solid understanding of the UT findings and/or wasn't in the refinement meeting discussing best steps forward.

**Comment by soyarsauce** [comment]
It seems Rowan's input is coming from a place of how it helps new users - his points are still valid even not having much involvement with the user testing from the lens of actual implementation of this concept. And I want us to avoid putting anyone down for comments and feedback on concepts, we should feel free to express our thoughts!

I think the missing context is that it isn't the ultimate-novice-help-solution, just yet another bandage and stopgap for the new-and-improved "interactive help" described in this design ticket 🙂

**Comment by vicborgy** [comment]
@soyarsauce I agree with that. We just need to all make sure we know why Alyce and I are making the decisions we are making, and that they are based on actually feedback not just our opinion. I also made assumptions in my designs and we just cant expect novice users to get it like we do.  And yes if this wasn't a bandaid due to time restrictions, we would probably be on the mark with a better way forward.

**Comment by soyarsauce** [comment]
Yep @vicborgy I think we all understand that and are just trying to improve on things 😀 

@steve9164 do you have anything to add before we progress with this?

@rowanwins for this concept I look at it and it should be quite simple to build out - then that way we can see it in context and refine from there. I'm quite ok with just building this out as a way of going through the refinement. It's quite 'static' - no smarts, nothing complex, quick-to-build, exactly what we said we'd aim for in our testing refinement meeting.

Admittedly having it more refined in invision can help but given we don't have the content, we might as well build out the core of it, and fit the content in once it's ready (and I can just take a quick stab at writing one for a complex terria-flow).

Are you happy for us to progress based on this and knowing it's a somewhat stopgap of addressing one of the user testing findings we saw come through, or do you want us to try and get a case for informing GA that waiting for the fully-fledged-Terry would be better? Personally I think while not perfect, this feels better than nothing and light on development effort - the copywriting will take most of the load for thinking on this.

**Comment by alyce** [comment]
@soyarsauce a good complex flow to start with would just be adding satellite imagery as quite a complex path since it's our highest used dataset across all maps. I'll be picking this up from Wednesday next week but if you need temp content that's something I'll be writing up anyway so will give me a head start.
But if you're cool to wait I will have content written up by end of next week.

I personally don't think we should go back to DEA with fully-fledged Terry just yet - they are getting us to do more general user testing next FY (at least once, possibly more) and I would like to test this version in that session before we go too far down the garden path. Then based on the results of that testing we can go to GA with a proposal for Terry if we still think that's the right thing to do.

**Comment by soyarsauce** [comment]
@alyce great! I'm also interested to see how this fares with the next round, it feels like discoverability will still be a problem but maybe all the little fixes like the help-icon-to-question-mark and the copy coming out of this static guide may add up to enough to perform much better. I'm just a little focused on getting something usable for DEA as part of this June 30 delivery and if you think we should hold off (for presenting+proposing full-terry-idea) then we should.

And yeah I will try one for satellite imagery then, focus on the other stuff until you get to this come Wed 👍

**Comment by soyarsauce** [comment]
@alyce track content completion here

**Comment by soyarsauce** [comment]
https://docs.google.com/document/d/1KkXFAP8an4XliLQed8260xm2sjsxpxTwZVDxoMyq1D8/edit

**Comment by soyarsauce** [comment]
@soyarsauce to preview any content updates on ci

**Comment by soyarsauce** [comment]
@soyarsauce t o update TerriaMap with default onboarding content

**Comment by soyarsauce** [comment]
DEA saas maps have the content already

Defaults resolved via
https://github.com/TerriaJS/terriajs/pull/4509
https://github.com/TerriaJS/TerriaMap/pull/464
