### ISSUE TITLE
Leaflet 2d in safari

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4366]
>Hey folks,
Couldn't find an issue for this on github, not sure if fixed in mobx (or which channel to post in): I'm consistently getting this error on NationalMap when I change my 2D zoom level in Safari. 3D seems fine.

**Comment by soyarsauce** [comment]
>Same experience across all 2D basemaps

**Comment by soyarsauce** [comment]
Reproducible on https://map.terria.io as well

**Comment by soyarsauce** [comment]
Reproduce steps:
1. load https://map.terria.io
2. ensure map settings have map view set to 2d
3. zoom in
4. observe 
```
Error accessing base map

An error occurred while attempting to download tiles for base map:

Positron (Light)
This may indicate that there is a problem with your internet connection, that the base map is temporarily unavailable, or that the base map is invalid. Please select a different base map using the Map button in the top-right corner. Further technical details may be found below.

Tile Error: The tile with the URL:
https://cartodb-basemaps-a.global.ssl.fastly.net/light_all/5/29/18.png
succeeded when loaded with XMLHttpRequest but failed multiple times when loaded directly by Cesium or Leaflet.
This may indicate that the server is very sensitive to the request headers provided or is simply unreliable.
```

**Comment by rowanwins** [comment]
~~Zoom in by drawing a box~~ ANY ZOOM IN TYPE!

**Comment by nf-s** [comment]
ci.terria.io/main/ working in Safari `Version 15.3 (17612.4.9.1.8`

**Comment by irbian** [comment]
We are getting the "Tile Error: Got a 200 (OK) response from URL: domain.com/... but it could not be loaded as an image" on Safari 17.x on 2d

**Comment by irbian** [comment]
Reproducible in map.terria.io

![image](https://github.com/user-attachments/assets/6982bff0-cce9-4817-a2b5-1bbbe785d68e)

**Comment by zoran995** [comment]
Hi @irbian can you create a new issue describing your problem

**Comment by irbian** [comment]
Yeah, no problem, there you go, #7384
