### ISSUE TITLE
DE UX Testing: Onboarding v3 language and concept help (tooltips)

### ISSUE THREAD

**Issue by alyce** [TerriaJS/terriajs#4367]
Covering issue no. 8 of [spreadsheet](https://docs.google.com/spreadsheets/d/10eWTU44vUEk-NKm2UcUPEK7qeHSDnRzrXUbMV6nDuBE/edit#gid=0) (high priority):

Issue

> 8: This content assumes some level of knowledge already, especially through language. For example, time series data isn't a term they're familiar with. it's missing guidance on the overall concept of satellite imagery for novices and also some language issues - passes, imagery not always available, clouds etc, false colour VS true colour, "daily".
> This lack of general conceptual understanding also led to issues when trying to add imagery to the map.
> _"I don't wanna view false color imagery. I've no idea what that means. So now this is where I'm completely lost. I don't know what this means" (P01)_
> _"For a novice, taking a step back... really super basic stuff would be really handy" (P04)_

**Fixes**
Short term Vic to design:
- Tooltip or contextual help (ie. dotted underline) for problematic terms within Help content

Short term Alyce to determine:
- Terms that need clarifying
- Appropriate beginners content to link out to for short term

Longer term: create a satellite imagery guide in collab with GA

**Comment by soyarsauce** [comment]
https://invis.io/QTXQ28AUD8S

**Comment by soyarsauce** [comment]
@alyce & @AnaBelgun  to define the list of things that need tooltipping

**Comment by soyarsauce** [comment]
@soyarsauce to add the tooltip content config to https://github.com/TerriaJS/TerriaMap/blob/mobx/wwwroot/config.json as it is broad and generic enough for all TerriaMap users to start off with as defaults.

**Comment by soyarsauce** [comment]
Defaults added via https://github.com/TerriaJS/TerriaMap/pull/464
