### ISSUE TITLE
DE UX Testing: Onboarding videos are too fast

### ISSUE THREAD

**Issue by alyce** [TerriaJS/terriajs#4368]
Covering issue no. 10 of [spreadsheet](https://docs.google.com/spreadsheets/d/10eWTU44vUEk-NKm2UcUPEK7qeHSDnRzrXUbMV6nDuBE/edit#gid=0) (high priority):

**Issue**
> 10: Videos are far too fast, need to be slower and potentially need an audio track so the user can listen and focus on watching the movements.
>_"Whirlwind... I'd say that was like less than, less than half the time than it should have been like, like it was nearly impossible" (P03)_
> _"Too quick, not what I need right now" (P04)_

**Fixes**
Short term: Alyce to slow down video content

Longer term: can we just pay someone to do some nice videos!

**Comment by soyarsauce** [comment]
Is there a slowed down video now that I've missed somewhere?

**Comment by alyce** [comment]
Yes @soyarsauce I think Ana was supposed to put it on our YouTube account the other day? It's here: https://drive.google.com/file/d/1PuALkWjWgwQZurcoiUMnHWFbwvinsUZz/view?usp=sharing

**Comment by soyarsauce** [comment]
@AnaBelgun could you put that video linked above onto youtube, then reassign back to me so we can update the generic video with the slower one,thanks

**Comment by AnaBelgun** [comment]
Youtube link: https://youtu.be/FjSxaviSLhc
Embed: <iframe width="560" height="315" src="https://www.youtube.com/embed/FjSxaviSLhc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by soyarsauce** [comment]
Thanks @AnaBelgun !
Resolved on DEAsaas maps,

Defaults resolved via
https://github.com/TerriaJS/terriajs/pull/4509
https://github.com/TerriaJS/TerriaMap/pull/464
