### ISSUE TITLE
DE UX Testing: Lifesaver help icon doesn't resonate

### ISSUE THREAD

**Issue by alyce** [TerriaJS/terriajs#4369]
Covering issue no. 12 of [spreadsheet](https://docs.google.com/spreadsheets/d/10eWTU44vUEk-NKm2UcUPEK7qeHSDnRzrXUbMV6nDuBE/edit#gid=0) (high priority):

**Issue**
> 12: The Help buttons were generally not visible. Some participants didn't understand the reference to a life-saver for help, some thought it was a soccer ball / football (especially African users)
> _"What I'm looking for is a Help button, which I can't see" (P04)_

**Fixes**
- Change icon back to standard ? help icon

**Comment by vicborgy** [comment]
Link to new onboarding project with change:
https://invis.io/UHXI971XJ2T

**Comment by rowanwins** [comment]
resolved by #4400
