### ISSUE TITLE
DE UX Testing: Delta flow isn't clear

### ISSUE THREAD

**Issue by alyce** [TerriaJS/terriajs#4371]
Covering issue no. 29 of [spreadsheet](https://docs.google.com/spreadsheets/d/10eWTU44vUEk-NKm2UcUPEK7qeHSDnRzrXUbMV6nDuBE/edit#gid=0) (high priority):

**Issue**
> 29: The process and order of steps to take was not obvious to most users. The UI needs to provide more guidance on what should be done, and in what order. 

**Fixes**
Vic to design:
- Short term interim tweaks to Delta UI, including clearer prompts

**Comment by vicborgy** [comment]
Updates based on UT results https://invis.io/BXXRFD48YJ5

**Comment by soyarsauce** [comment]
The flow is much clearer now, revised in all of https://app.zenhub.com/workspaces/terria-frontend-ui-ux-5d802feb6b3dcf00019b6380/issues/terriajs/terriajs/4515 https://app.zenhub.com/workspaces/terria-frontend-ui-ux-5d802feb6b3dcf00019b6380/issues/terriajs/terriajs/4531 https://app.zenhub.com/workspaces/terria-frontend-ui-ux-5d802feb6b3dcf00019b6380/issues/terriajs/terriajs/4533
