### ISSUE TITLE
DE UX Testing: Delta style selection drop downs missing labels, unclear purpose

### ISSUE THREAD

**Issue by alyce** [TerriaJS/terriajs#4372]
Covering issue no. 30 of [spreadsheet](https://docs.google.com/spreadsheets/d/10eWTU44vUEk-NKm2UcUPEK7qeHSDnRzrXUbMV6nDuBE/edit#gid=0) (high priority):

**Issue**
> 30: The lack of labels of the style picker drop downs meant the meaning and difference between these functions was not clear. Participants weren't sure what and why they were changing options and the impact it would have.
>_"I don't know why there are these two options. I find that a bit confusing" (P06)_

**Fixes**
Add distinct and clear labels to each drop down: top to preview imagery and select cloud free images, bottom is to select what change detection function is run.

**Comment by soyarsauce** [comment]
Highlight the fact that this will now use the new tooltip system and will need to pull in those tooltip definitions on the labels

**Comment by soyarsauce** [comment]
Labels exist now
