### ISSUE TITLE
DE UX Testing: Delta select a precise location was confusing

### ISSUE THREAD

**Issue by alyce** [TerriaJS/terriajs#4375]
Covering issues no. 32, 33 and 36 of [spreadsheet](https://docs.google.com/spreadsheets/d/10eWTU44vUEk-NKm2UcUPEK7qeHSDnRzrXUbMV6nDuBE/edit#gid=0) (high priority):

**Issues**
> 32: Being asked to select a precise location was confusing as for most participants they would be examining the change detection on an area; a polygon they define or a region. A precise location is misleading as it implies it will only be for that point, and it is not clear that whole satellite pass will be analysed. No participants realised this was purely to filter the dates of the imagery shown.
> _"You have to select a precise location in order to do the change analysis... I'd always want to be doing this on a polygon or an area of interest" (P03)_

> 33: Having to click to filter the imagery by location seemed redundant if a location was already searched for or the participant had zoomed into their region of choice. All expected in this scenario that the imagery would be filtered automatically; especially if they've selected a location previously. 

> 36: The accuracy of the location used to filter and return imagery was again problematic, as it often appeared as a swath offscreen, which then left the participant confused as nothing had appeared onscreen once both when selecting imagery and also generating change

**Fixes**
Nanda/Wing to explore:
- If location has been previously searched for, carry this over location over to auto filter dates (re-use marker)
- If zoomed to a certain region (zoom level TBC), trigger auto filter dates based on marker in centre of that region
- If no location or zoom selected, then trigger to select a location
- Need to review filter as it isn't accurate, communicate issue back to DEA team

Vic/Alyce:
- Update select location prompt to clarify it is to filter imagery
- Move prompt down closer to dates so it is more clearly related, remove confusion

**Comment by vicborgy** [comment]
Updates based on UT results https://invis.io/BXXRFD48YJ5

**Comment by vicborgy** [comment]
Updates based on UT results https://invis.io/BXXRFD48YJ5

**Comment by soyarsauce** [comment]
@vicborgy is this satisfied now? (check via http://de-australia.saas.terria.io/ there are delta datasets there)
I think the only item that isn't happening is
>If zoomed to a certain region (zoom level TBC), trigger auto filter dates based on marker in centre of that region

Do we still want that?

**Comment by soyarsauce** [comment]
Hey @vicborgy just pinging again for this one

**Comment by vicborgy** [comment]
All looks good. And yes I think we should do that trigger auto filter you mentioned.

**Comment by soyarsauce** [comment]
Behaviour would be, if zoomed in to a certain level, auto pick the location to center of region

**Comment by AnaBelgun** [comment]
Superseded by Delta v3 development done in July 2020.
