### ISSUE TITLE
DE UX Testing: Delta date picker not obvious

### ISSUE THREAD

**Issue by alyce** [TerriaJS/terriajs#4376]
Covering issue no. 37 of [spreadsheet](https://docs.google.com/spreadsheets/d/10eWTU44vUEk-NKm2UcUPEK7qeHSDnRzrXUbMV6nDuBE/edit#gid=0) (high priority):

**Issue**
> Many participants struggled to find the dates at the bottom of the screen. This may have to do with size and contrast impairing visibility. The date pickers also have no labels, so participants didn't realise immediately that they should change them, and if it mattered what image/date is on the left VS the right. 
> _"I don't know how to select the dates" (P06)_

**Fixes**
Vic to review dates, address:
- size, contrast
- labels

**Comment by vicborgy** [comment]
Updates based on UT results https://invis.io/BXXRFD48YJ5

**Comment by rowanwins** [comment]
Think we can close this @vicborgy now that Delta v3 is merged?

**Comment by soyarsauce** [comment]
Hey @vicborgy just pinging again for this one

**Comment by soyarsauce** [comment]
Actually I can close this one - size contrast labels & flow including dates is all addressed now.
