### ISSUE TITLE
DE UX Testing: Sat imagery and basemap confusion

### ISSUE THREAD

**Issue by alyce** [TerriaJS/terriajs#4379]
Covering issue no. 15 of [spreadsheet](https://docs.google.com/spreadsheets/d/10eWTU44vUEk-NKm2UcUPEK7qeHSDnRzrXUbMV6nDuBE/edit#gid=0) (high priority):

**Issue**
> 15: Novice users think the default Bing basemap is the satellite imagery and don't move to add any imagery to the map when prompted. This is a common issue that happens regularly in user testing.

**Fixes**
- Help content to address
- Vic to design some simple feedback cue on map to show data isn't loaded

**Comment by soyarsauce** [comment]
https://invis.io/X6XQ2BZJPZ5

@vicborgy thanks for the sketch+invision. I thought we were going to have something along the lines of an indicator for number of datasets active?

**Comment by soyarsauce** [comment]
development ticket: https://github.com/TerriaJS/terriajs/issues/4450

**Comment by vicborgy** [comment]
@soyarsauce yep we will insert an indicator but it's fine to be just text. Ive updated Invision and g-drive anyway.
https://invis.io/NXXQS03SG83

**Comment by vicborgy** [comment]
Also, am thinking not we'll leave the live data state for now as I think it needs a little more thought

**Comment by soyarsauce** [comment]
Yeah no problem - will only do it without the live dataset state

**Comment by soyarsauce** [comment]
http://ci.terria.io/mobx-map-state/ has this now - @vicborgy @Alyce Lythall all seem ok?
I also made it only enabled datasets, so the copy could be improved to reflect that , e.g.
<img width="522" alt="image" src="https://user-images.githubusercontent.com/9134432/85109551-da702100-b254-11ea-9776-775b25c1c0f5.png">
It says "no map data added" - but there's 3 datasets "added" to the workbench, just not "shown" on the map. So maybe "No map data enabled" when nothing added, or even both?

**Comment by alyce** [comment]
Ohhhhhh - I didn't think of this. That's confusing. Especially if people accidentally toggle it on and off (I see that a lot). No map data enabled might be better for both scenarios.

**Comment by soyarsauce** [comment]
Exists on http://de-africa.saas.terria.io/ & http://de-australia.saas.terria.io/ now
