### ISSUE TITLE
DE UX Testing: Sat imagery filter by location is hard to use

### ISSUE THREAD

**Issue by alyce** [TerriaJS/terriajs#4380]
Covering issue no. 20 of [spreadsheet](https://docs.google.com/spreadsheets/d/10eWTU44vUEk-NKm2UcUPEK7qeHSDnRzrXUbMV6nDuBE/edit#gid=0) (high priority):

**Issue**
> 20: Participants often ended up in a loop with the 'Filter by location' function. It wasn't clear to activate this feature they first had to select 'Filter by location', and then select a location. 
This was especially annoying when they had already searched for and found their location on the map, as the location doesn't seem to carry over. Even expert participants were giving up with this feature, which was problematic as they then weren't able to quickly find imagery at a certain location.
Due to the satellite image background, it's also harder to accurately locate satellite imagery when participants aren't entirely sure what they're looking for, especially without the filter by location function enabled. 

**Fixes**
- filter by location remains as individual function on each relevant layer
- filter by location to carry over any existing search that has been made
- if zoomed in to TBC zoom level, automatically filter image based on that region
- add a confirmation (are you sure?) if you accidentally click off
- make this function consistent with Delta pick location function

**Comment by soyarsauce** [comment]
>filter by location to carry over any existing search that has been made

@na9da will you progress this one? Especially the point above - I wonder how long to persist the linkage of a location search to location-picker-relevant actions, I guess for as long as a location search is still in the input and hasn't been cleared (this is how we currently clear the marker), all location pick things will default to that searched spot as a starter?

But then there's the possibility that a user pans away from the location marker to the actual spot of interest..

& it feels like filter by location will need some copy changes to this bit to have some indicator of user-picked-spot or automatically-carried-over-from-location-search:

<img width="453" alt="image" src="https://user-images.githubusercontent.com/9134432/84967876-71a37e80-b158-11ea-8412-b5e7cfdc6291.png">

Maybe the flow can look like
1. click "Filter by location"
<img width="428" alt="image" src="https://user-images.githubusercontent.com/9134432/84968254-66048780-b159-11ea-9e08-af08606c476f.png">

either:

2. get select point if no search location is active
<img width="291" alt="image" src="https://user-images.githubusercontent.com/9134432/84968265-6c92ff00-b159-11ea-8c44-fae454f1b408.png">


2b. OR workbench immediately turns into this state, & clicking new location will allow you to pick location as usual from step 2 (draft text to get the idea across)

<img width="425" alt="image" src="https://user-images.githubusercontent.com/9134432/84968591-3609b400-b15a-11ea-91b0-e5267d25c53e.png">


(cc @alyce @vicborgy)

**Comment by soyarsauce** [comment]
And to be extra clear - we can only show "queensland" as the label in this particular instance because it's one of the search results for a search term "qld" - we can't reverse it by picking a lat+lng and getting a label out of that as we previously imagined for delta, same applies here

**Comment by alyce** [comment]
Sounds good @soyarsauce - can we tweak the copy slightly?
For no location perhaps "Select a point on the map to filter by this location"

And for an active location detected, can we replace the word 'capture' with 'image'?

**Comment by AnaBelgun** [comment]
Improved by #4329 
will close for now
