### ISSUE TITLE
DE UX Testing: Sat imagery How Do I guide needs more steps/detail

### ISSUE THREAD

**Issue by alyce** [TerriaJS/terriajs#4381]
Covering issue no. 24 of [spreadsheet](https://docs.google.com/spreadsheets/d/10eWTU44vUEk-NKm2UcUPEK7qeHSDnRzrXUbMV6nDuBE/edit#gid=0) (high priority):

**Issue**
> 24: As noted above, both the tour, I'll Need Some Help and Satellite Imagery: How Do I guide assumes a lot of pre-existing knowledge, and less experienced participants would benefit from more granular information for satellite imagery

**Fixes**
Alyce to review content and add to sat imagery 'How do I' guide with clearer steps, include some confusing concepts

Longer term: work with GA to create specific content

**Comment by soyarsauce** [comment]
@alyce we now have the terry trainer for adding satellite imagery - is this meant to replace the guide-with-images, or to supplement them?

![image.png](https://images.zenhubusercontent.com/5ca14bcde8443113da47c346/5e2a3d5b-3859-4a3c-866a-35ab595007cb)

Given Regina has added the guide to the side bar, if we simply update the copy/images used in there, we can have both?

**Comment by alyce** [comment]
@soyarsauce if you want to duplicate it in here and replace the old satellite how to guide I think that's fine - I was originally thinking replace but I'm also happy with it being duplicated if it's not too much effort. The key point is just getting rid of that satellite imagery how to guide!

**Comment by soyarsauce** [comment]
@alyce sorry I'm confused here - and I didn't realise my image didn't get uploaded above.

>The key point is just getting rid of that satellite imagery how to guide!

This suggests you want it removed, but then you also OK with duplicated? (I can go and update the guide-with-images with some copy borrowed from the trainer steps)

Currently:

This is the popup that appears when you add satellite imagery to the map and have configured it to prompt for in-app guides
![image](https://user-images.githubusercontent.com/9134432/86688164-32769800-c049-11ea-9eb7-4d3a99783a15.png)

Then clicking "view guide" will open up to the satellite imagery how to guide in the help sidebar:
![image](https://user-images.githubusercontent.com/9134432/86688479-79648d80-c049-11ea-9b0b-5b608fa5a603.png)

**Comment by alyce** [comment]
Sorry @soyarsauce let me try and clarify - I want the old Satellite Imagery how to guide either removed (and remove the popup as well) or have the content and images within the How to guide replaced with those from Terry (and keep the popup as you've described). I'm fine with either. Does that make more sense?

**Comment by soyarsauce** [comment]
Yes thanks that makes a lot more sense - after looking at the content, I'm struggling to map the trainer content (a workflow) to some "random tips surrounding satellite imagery" from the "guide with images". The prompt appears when you've already added the satellite imagery, and half of the trainer content (steps 1+2) from satellite imagery is assuming you haven't gotten there yet.

I'm going to icebox this one in favour of whatever direction the trainer takes next, and we'll keep the satellite imagery guides disabled as it's a very hardcoded guide compared to the rest of the help content.

**Comment by AnaBelgun** [comment]
superseded by newly developed Help menu
