### ISSUE TITLE
MobX Onboarding v3 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#4391]
This epic will record all tickets submitted post user testing undertaken 19-21/05/2020. 
Should any tickets remain post June 2020, they will be moved under a new generic User Onboarding epic.

**Comment by soyarsauce** [comment]
Nanda
- show "number of datasets in workbench" for the 'active map data' button

**Comment by soyarsauce** [comment]
All tickets under this are either done or iceboxed, will keep the epic iceboxed as well for ease of reference to the iceboxed items

**Comment by AnaBelgun** [comment]
Epic is superseded by specific Onboarding issues.
