### ISSUE TITLE
Need PopupMessage with buttons

### ISSUE THREAD

**Issue by kgrochow** [TerriaJS/terriajs#441]
Right now we have no way in the UI to ask the user to make a decision.  We could either add other fields to popup or create a new class based on popupMessage.  This will replace where ever we are still using alerts in the code

**Comment by hilarycinis** [comment]
@kgrochow is the problem you're describing a generic dialogue box with some rules around how to interact with the messages held within? eg a general solution for errors, confirmations, loading etc with relative activities described?

**Comment by kring** [comment]
@arrayjam implemented this in #823.  We can close it.
