### ISSUE TITLE
Onboarding v3: "Terry the trainer" v1

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4421]
As a new map user,
I want an always-in-view, step by step guide,
so I have follow along without relying on my memory

**Design file**: `terry-task-trainer.sketch` in https://drive.google.com/drive/u/0/folders/14c-UE2Cmn3zivZr25Sw8eQv_o_wfc88u

**Design ticket**: https://github.com/TerriaJS/terriajs/issues/4365

**Invision**: https://projects.invisionapp.com/share/X6XK52ZRJ5D

Other notes:
- very quick inline, "no smarts" - aka manual back/next

### DoD:
- [x] Unit test written (if applicable)
- [x] Works on mobile (or deliberately disabled for mobile)
- [x] Code/peer reviewed (if didn't pair)
- [x] Relevant docs are updated - docs at https://github.com/TerriaJS/terriajs/issues/4421#issue-635052382
- [x] Previewable/deployed to dev (see separation of deployments)
- [x] Previewable/deployed to test (see separation of deployments)
- [ ] (If a map-specific ticket) Issue linked to a release ticket

### Acceptance Criteria:
- [x] Step by step guide is available as an item in help panel through config
- [x] Opening an item (e.g. "adding satellite imagery" / "adding data to the map") from the help pane, loads inline-guide at top
- [x] Inline-guide has a dropdown to swap between different guides
- [x] Inline-guide has instructions
- [x] Inline-guide has back / next

**Comment by soyarsauce** [comment]
@vicborgy a few detail things here - still not entirely sure on your intended interaction. Let's call it 3 states

### State 1. (we'll call it "collapsed")
![image.png](https://images.zenhubusercontent.com/5ca14bcde8443113da47c346/c3a13916-97fb-49e6-a3dd-2cd8ea6e6db5)

### State 2. (we'll call it "peeking")
![image.png](https://images.zenhubusercontent.com/5ca14bcde8443113da47c346/5daab91e-ea04-4960-9ae7-53efe911543a)

### State 3. (we'll call it "expanded")
![image.png](https://images.zenhubusercontent.com/5ca14bcde8443113da47c346/585cbc44-95e6-4636-a7e3-fb497baa9427)

- when does it peek?
- when does it expand?
- and how does it work with keyboard nav?

I'm thinking use the expand/collapse icon as the focus target when doing peeking, but then once it's expanded..

- will it stay expanded until you close it? is your intention the current invision interaction of "closing on mouseaway"?
- what should happen if you click Click next/back?

**Comment by vicborgy** [comment]
Mouse interactions:
- Peek - On hover he description of the active step will appear only
- Expand on click - Will stay expanded until they press collapse

Keyboard interactions:
- No peeking, we only use expand and collapse. So will stay expanded until they close

Clicking back and next would cycle through the title of the steps

**Comment by soyarsauce** [comment]
@vicborgy ok I'll give that a whirl!

For back/next I meant does anything happen to peeking/expanding when you click back/next

**Comment by soyarsauce** [comment]
(I guess it can be left in whatever state it was - the current interaction I have it closing the expanded state back to collapsed)

**Comment by soyarsauce** [comment]
<img width="861" alt="image" src="https://user-images.githubusercontent.com/9134432/84874752-686ad100-b0c8-11ea-8aae-f44698e875ba.png">

Also - can this "footnote" appear multiple times (e.g. have a footnote for step 3 and 5), or just once at the end of a set of steps? I'm gonna lean to just one for now

**Comment by soyarsauce** [comment]
@vicborgy it's been updated now with the above behaviour on http://ci.terria.io/mobx-trainer/ but the more I try and actually use it, the more I want a way to keep the "peeking" state on (aka something that acts as a second toggle almost) - the expanded view is too much, and when I'm trying to use the UI itself to follow along, I lose the detailed information when I mouse away. What do you think?

**Comment by vicborgy** [comment]
@soyarsauce yep you got it right with the 'Important note' section, per task not per step.
Have looked at the link and I see what you mean. Ill have a think about how we might be able to solve this. Its looking good though, nice work!

**Comment by vicborgy** [comment]
yep happy with going back to the collapsed state

**Comment by soyarsauce** [comment]
https://github.com/TerriaJS/terriajs/issues/4451
