### ISSUE TITLE
Mobx: Gazetteer / Gnaf port

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4424]
Couldn't find a mobx issue for this.

 steve9164 commented on Mar 18
>We will be porting the remaining 2 search providers.

**Comment by soyarsauce** [comment]
The UI now supports multiple search providers, just need to port over gazetteer + gnaf
Stemming from
https://github.com/TerriaJS/nsw-digital-twin/issues/248
https://github.com/TerriaJS/terriajs/issues/4178

**Comment by soyarsauce** [comment]
Needed for https://github.com/terriajs/drought-map/issues/196

**Comment by soyarsauce** [comment]
See https://github.com/TerriaJS/terriajs/issues/3608 for GNAF

**Comment by steve9164** [comment]
Our gnaf search & geocoder will not be ported. The data is out of date.

**Comment by KeyboardSounds** [comment]
The [old Gazetteer search provider](https://github.com/TerriaJS/terriajs/blob/e4758fdcb21b9da89beab4c3e547d69be87dded2/lib/ViewModels/GazetteerSearchProviderViewModel.js) is using an undocumented GA API and does all the scoring and sorting on the client side. I've decided to replace it with a WFS search provider instead, which is no better or worse from an implementation point of view, but more flexible and uses an official, maintained WFS service.

**Comment by nf-s** [comment]
Closed by #4749 (assuming GNAF will not be supported in v8)
