### ISSUE TITLE
Story v2.0 - Improving handling slow loading of stories

### ISSUE THREAD

**Issue by rowanwins** [TerriaJS/terriajs#4432]
Taken from https://github.com/TerriaJS/nsw-digital-twin/issues/417

Depending on the story loading them can take a while, this could be the result of lots of layers, or a layer being really slow to respond.

Our handling could be improved by
1.  show loading state of a story/share/layers, or
2. parse the share/story/catalog state without blocking the UI

**Comment by hardreddata** [comment]
This is an interesting ticket.

We run starting pages for our office branches whereby frequently used layers are pre-added and listed down the left side. The users access terria#branchpage for this. 

Historically we had problems with big .csv files or slow WMS query returns.

Famously there was 1.5 minutes of spinner for our Sydney page. In part this was solved by upgrading to newer versions of WMS servers.

I like the non-blocking idea. Or the idea that somehow the layers don't need loading simply to appear in this helpful _side panel catalogue_.

**Comment by wibily** [comment]
created https://github.com/TerriaJS/simple-cors-server to simulate a slow geojson server
