### ISSUE TITLE
Share of user-added data using auto-detect doesn't work

### ISSUE THREAD

**Issue by zoran995** [TerriaJS/terriajs#4441]
ArcGIS feature server layers are share as chart layer (not sure how to call them)
steps to reproduce

- add feature server layer ([example](https://services5.arcgis.com/vZHHXdueMZ3er5Xc/arcgis/rest/services/test_geojson/FeatureServer/2))
- share the map
- open the share link ([example](http://ci.terria.io/mobx/#share=s-8djx4XoibVKbkWxVbohVQYAyWRn))

**Comment by rowanwins** [comment]
Selected "Esri ArcGIS FeatureServer (single layer)" from the dropdown seems to work with sharing
![ShareFS](https://user-images.githubusercontent.com/6735870/84727733-067c6f80-afd3-11ea-9109-57f2103dc0aa.jpg)
http://ci.terria.io/mobx/#share=s-ixNGJKNRZk6pdCBwkc3Ig8iNTuZ

However I could replicate with 'Auto-detect' selected

**Comment by rowanwins** [comment]
It's something in [this sequence](https://github.com/TerriaJS/terriajs/blob/mobx/lib/ReactViews/Map/Panels/SharePanel/BuildShareLink.js#L108-L151) I think but I haven't quite narrowed down to what

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/5580/
