### ISSUE TITLE
Mobx: Workbench doesn't show WMS style legend

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4446]
Repro:
1. https://tc-user-testing.terria.io/
2. add `Expedited Sentinel 2 satellite images` to workbench
3. pick a style that should show a legend (e.g. NDVI - Red, NIR)
4. observe no legend showing in workbench

As opposed to http://ci.terria.io/master/#share=s-fq2GU7OtW3619Z7uRmSEiA1opML with 
<img width="342" alt="image" src="https://user-images.githubusercontent.com/9134432/84858947-81b35380-b0af-11ea-975f-5d372dcdbfd8.png">

**Comment by soyarsauce** [comment]
Affects https://github.com/TerriaJS/terriajs/issues/4390

**Comment by nf-s** [comment]
This will be rolled into #4219

**Comment by soyarsauce** [comment]
Still waiting https://github.com/TerriaJS/terriajs/pull/4219

**Comment by soyarsauce** [comment]
Resolved via https://github.com/TerriaJS/terriajs/pull/4219

<img width="350" alt="image" src="https://user-images.githubusercontent.com/9134432/91928096-7f5fad80-ed1e-11ea-9b95-5b0954584bfb.png">
