### ISSUE TITLE
i18n problem with wms data preview panel

### ISSUE THREAD

**Issue by hardreddata** [TerriaJS/terriajs#4469]
Consider this group WMS group catalog item

http://ci.terria.io/master/#https://gist.githubusercontent.com/RussellGrew/2295ae5dd44634b83ce22af12f6e2664/raw/f6d9af8ca0f61e729c93df3c65e861a77ce93ac4/nrmap.json

![image](https://user-images.githubusercontent.com/42530666/85808289-be5e0980-b797-11ea-8dea-abda8cc6db1c.png)

I think introduced as part of https://github.com/TerriaJS/terriajs/commit/1128c72048cb12af2ffa8e8ddfc2d224e635a09a as http://map.terria.io running an older version is fine.

I think some combination of

https://github.com/TerriaJS/terriajs/blob/0aac25567268b6856b3597a6112f9c5cf88fdd0c/lib/ReactViews/Preview/DataPreviewUrl.jsx#L30-L41

and

https://github.com/TerriaJS/terriajs/blob/master/lib/Language/en/translation.json

I was on the verge of contemplating a pull request but I am out of my depth with the i18n.

**Comment by tephenavies** [comment]
Hi @RussellGrew. Thanks for reporting that. I think this is caused by having the index `<0>` in the translation strings but it should be a `<1>`. It's a little bit complicated, but the opening string "This is a" will be element 0, so the `<a>` is element 1.

We fixed this on the mobx branch, but forgot to backport it. I'll PR a fix.

**Comment by tephenavies** [comment]
From [18next Trans docs](https://react.i18next.com/latest/trans-component). Using this Trans component:
```
<Trans i18nKey="userMessagesUnread" count={count}>
    Hello <strong title={t('nameTitle')}>{{name}}</strong>, you have {{count}} unread message. <Link to="/msgs">Go to messages</Link>.
</Trans>
```
you should have a translation string like:
```
"Hello <1>{{name}}</1>, you have {{count}} unread message. <5>Go to message</5>."
```

Here is the React node tree of that Trans component that gives rise to those indices
```
Trans.children = [
  'Hello ',                           // index 0: only a string
  { children: [{ name: 'Jan'  }] },   // index 1: element strong -> child object for interpolation
  ', you have',                       // index 2: only a string
  { count: 10 },                      // index 3: just object for interpolation
  ' unread messages. ',               // index 4
  { children: [ 'Go to messages' ] }, // index 5: element link -> child just a string
  '.'
]
```
