### ISSUE TITLE
Mobx: workbench upload ui button does nothing

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4498]
1. http://ci.terria.io/mobx/
2. click "upload"
3. observe catalog explorer doesn't open

(sidepanel.jsx related?
```
SidePanel.jsx:145 Uncaught TypeError: Cannot read property 'stopPropagation' of undefined
    at Object.onAddLocalDataClicked (SidePanel.jsx:145)
    at onClick (SidePanel.jsx:190)
```
)

**Comment by reginapramesti** [comment]
I take it that this has been fixed on `next` by your commit @soyarsauce? It's working fine on ci.terria.io/next/

**Comment by soyarsauce** [comment]
Yeah thanks @reginapramesti this is fixed on next
