### ISSUE TITLE
Make auto-generated docs for TerriaJS version 8

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#4502]
I have a half-auto generated docs process for TerriaJS version 8. It's roughly:
- Build and run TerriaMap running the [`mobx-generate-docs` TerriaMap branch](https://github.com/TerriaJS/TerriaMap/blob/mobx-generate-docs/index.js)
- Copy the downloaded zip of markdown files and unzip them into a clone of terriajs running the [`mobx-generate-docs` terriajs branch](https://github.com/TerriaJS/terriajs/blob/mobx-generate-docs)
- Run `gulp docs` (with a Python environment that has correct installed dependencies)
- Deploy to static hosting site

But I haven't run this for about 6 months. It's time to automate this fully. There is some work on https://github.com/TerriaJS/TerriaMap/blob/mobx-generate-docs/index.js to generate markdown from the Trait system. This has been integrated into the old docs and deployed here: https://mobx-terria-docs.surge.sh/connecting-to-data/catalog-items/ (with the help of some terriajs changes [here](https://github.com/TerriaJS/terriajs/blob/mobx-generate-docs).

The docs generation should now be able to run in node (and without TerriaMap) now that the model & traits system can be built for and run in node (as of ~6 months ago).

Rough task list:
- [x] Move markdown generation code from TerriaMap's index.js to somewhere in terriajs and use terriajs running on node
- [x] Change from using a list of model types to using all registered catalog items/groups/references. Or something
- [x] Make the command `gulp docs` runnable again. It should probably build terriajs using the terriajs-node (`tsc -b tsconfig-node.json`) and then generate markdown files from models & traits.
- [x] Add `gulp docs` back into CI

**Comment by soyarsauce** [comment]
Once this is ready, we should have a v8 version of docs.terria.io (in parallel)

Or option 2 - swap docs with dropdown

**Comment by soyarsauce** [comment]
Don't need decision now - but things to consider:

- seo / multiple versions of duplicate content / confusing versioning
- popular ways of dealing with this? e.g. kubernetes

**Comment by soyarsauce** [comment]
Once we are closer to the v8 release, we make the v8 docs the main docs, and host v7 docs elsewhere with a link saying if you need old docs, go here - robots meta noindex meta tags to not be indexed.

Host the v8 docs somewhere - @steve9164 to speak w/ @soyarsauce & look into auto hosting v8 docs so we can get it out

**Comment by soyarsauce** [comment]
Unsure if this will make the oct communications

**Comment by tephenavies** [comment]
Closed as there's other tickets tracking this work. See especially #4666.
