### ISSUE TITLE
MobX: display all filled fields of WMS 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#4506]
There are cases when WMS fields are missing from data description/metadata even when they are filled by the data custodian. 
To add the following fields as part of metadata for a WMS: 

- GetCapabilties url 
- Service Contact

Example: 
- go to NSW Digital Twin - National Datasets - Drought -  Vegetation cover - https://nsw.digitaltwin.terria.io/#share=s-3VxqdKGRz51QdG8nUB7U8kgJ7wQ 

![image](https://user-images.githubusercontent.com/18452161/86692517-2db3e300-c04d-11ea-8024-19e5a7210511.png)

- same data tested on a non-MobX app map.terria.io, https://map.terria.io/#share=s-kwABt9PyYPCbNtVIsZjgQsVf7J0 produces metadata with Service Contact, Get Capabilities URL; the Service Description has a different title but the information is there:

![image](https://user-images.githubusercontent.com/18452161/86693292-e417c800-c04d-11ea-9588-9cd7ec410fd5.png)

**Comment by nf-s** [comment]
I'm happy to fix this. I'll bundle it with #4446

**Comment by AnaBelgun** [comment]
That would be great @nf-s :)
