### ISSUE TITLE
Mobx:  Style selectors aren't consistent

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4513]
Style selectors aren't consistent

when `renderMultipleStyleSelectors()` is invoked, some old scss overrides are applied and we get the below:

<img width="352" alt="image" src="https://user-images.githubusercontent.com/9134432/86730738-34088600-c072-11ea-8d9a-08d50c074682.png">

**Comment by rowanwins** [comment]
Related to #4364

**Comment by soyarsauce** [comment]
It will be fixed once https://github.com/TerriaJS/terriajs/pull/4514 is merged

**Comment by nf-s** [comment]
This is also related to https://github.com/TerriaJS/terriajs/pull/4219
I am working on this today

**Comment by nf-s** [comment]
This is pretty much done, the only thing left is the `ShadowSelector`
![image](https://user-images.githubusercontent.com/6187649/92061692-438a1e00-edda-11ea-8d74-291cd9cc6a5a.png)

**Comment by nf-s** [comment]
Closed by #4710
