### ISSUE TITLE
Date picker crash when current date is outside the available dates

### ISSUE THREAD

**Issue by na9da** [TerriaJS/terriajs#4518]
Steps to repro:

* Load this url - http://ci.terria.io/mobx/#share=s-Ah4VveRY2x9E4wCRjXwhEbq4iz1
* Open the date picker for the item and select the earliest date possible
* Zoom in to some region and filter dates by location
* Click on the date picker again
* App crashes

**Comment by rowanwins** [comment]
Struggled to replicate?

**Comment by na9da** [comment]
It happened a lot when I was testing delta.
Basically it is triggered when the date you have currently selected is outside the range of filtered dates.
You might have to zoom in quite a bit to trigger it correctly.

**Comment by rowanwins** [comment]
Critical bit is clicking on the datepicker with the filter applied

**Comment by nf-s** [comment]
Closed by #4576
