### ISSUE TITLE
Review properties isMappable and isChartable on AsyncMappableMixin and AsyncChartableMixin (and many items)

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#4522]
The properties `isMappable`, which is defined on many catalog items, and the type guard `Mappable.is` are too similar and we should review whether both are needed & whether we can rename one or both to reduce confusion between them.

At the moment it looks like [`model.isMappable` is used widely](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/TerriaJS/terriajs%24%40next+isMappable&patternType=literal) as a(n) (occasionally dynamic) property set on CatalogItems that have map items. [`Mappable.is` is an type guard](https://github.com/TerriaJS/terriajs/blob/next/lib/Models/Mappable.ts#L37) to determine if a model follows interface Mappable.

`model.IsMappable` comes from `master` and is used in the UI to.:
* Select which icon to use in the workbench
* Determine if a preview map can be shown, or if a preview can and should be shown instead
* Filter items to include legends and "details" in print view
* \+ a couple more things

It was added to `next` to make it quick to prototype the first models without changing the UI much, but I think it should be replaced in some places with `Mappable.is` and if there are other places that require explicit hints to the UI about whether a model should be represented as a map or chart we should find a different way to do that.

Also, we should not use `isMappable` in the type guard for AsyncMappableMixin. Currently this: https://github.com/TerriaJS/terriajs/blob/11920b7afb8e63d90964cbfc88844cce2cc4e5d0/lib/ModelMixins/AsyncMappableMixin.ts#L56-L58
will be true in many cases where AsyncMappableMixin is not mixed into the model being checked so our models will be incorrectly assumed to have AsyncMappableMixin properties and methods.

**Comment by tephenavies** [comment]
@nf-s What are your thoughts?

**Comment by nf-s** [comment]
yeah totally agree, I shouldn't have used isMappable/isChartable in the type guards.
I'm all for replace isMappable/isChartable with isMixtedInto/is if possible

**Comment by nf-s** [comment]
closed by https://github.com/TerriaJS/terriajs/pull/5022
