### ISSUE TITLE
Mobx: "Quick zoom" aka "shift+drag" to zoom

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4524]
@philipgrimmett has raised that we don't have quick zoom in mobx and I can't find a ticket surrounding this.
We have quick zoom in knockout terria but not mobx yet,

http://ci.terria.io/next/
vs
http://ci.terria.io/master/

hold shift + drag a rectangle on master to zoom there, can't do the same in mobx

**Comment by nf-s** [comment]
I can take this on, it is related to how I implemented rectangle drawing for https://github.com/TerriaJS/terriajs/issues/4268
