### ISSUE TITLE
Don't load cesium if requesting leaflet 2d, mode   

### ISSUE THREAD

**Issue by nlacey** [TerriaJS/terriajs#4528]
If I load https://nationalmap.gov.au/#test&map=2d (leaflet) or https://nationalmap.gov.au/#test&map=3d (cesium)
The downloaded file-size doesn't change.
Is it possible to get a light-weight minimized leaflet only download when using 2d mode that  nationalmap.gov.au just isn't taking advantage of?

Or is this a new feature that could be added.

**Comment by tephenavies** [comment]
Hi @nlacey. There are 4 JS bundles related to 3D rendering that aren't loaded when the map starts in Leaflet mode, which adds up to almost 2MB of minified javascript (~500KB gzipped).

**Comment by nlacey** [comment]
ok, thanks!
