### ISSUE TITLE
Fix slow search on docs.terria.io due to indexing of aggregated licences

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#4534]
The large markdown file (I think it's `doc/attributions.md` in this repo) with aggregated licences gets indexed by mkdocs during the docs build causing the docs.terria.io site to freeze when you try to start searching for something for multiple seconds (downloading + parsing the large index). We should find some way to not index that file.

**Comment by rowanwins** [comment]
There is a `prebuild_index` option on https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/. 

Although I just tried searching on the new docs locally and didn't hit any issues....

**Comment by tephenavies** [comment]
Fixed by upgrading mkdocs and mkdocs material. The new version of docs is available as of earlier this week at the standard https://docs.terria.io/guide/
