### ISSUE TITLE
Mobx: Chart sharing bugs

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4540]
Charts don't get shared

repro:
1. hit http://de-australia.prod.saas.terria.io/#share=s-hBfNhIPkB5I3ydWiL0eiaiRKqzr
2. click a waterbody
3. within the feature info that pops up, click `expand` to expand the chart
4. observe a chart in dock
5. create a share link
6. view share link

expect to see (with chart in dock):
<img width="2279" alt="image" src="https://user-images.githubusercontent.com/9134432/87395292-7db61b00-c5f4-11ea-9e63-60cc34dfb268.png">

actual:
<img width="2295" alt="image" src="https://user-images.githubusercontent.com/9134432/87395304-8149a200-c5f4-11ea-9049-4d6738013e52.png">

**Comment by na9da** [comment]
Fixed by https://github.com/TerriaJS/terriajs/pull/4757

eg: https://de-australia.prod.saas.terria.io/#share=s-eLduOF6eDAhrWDfhjlEUHC9BwHD
