### ISSUE TITLE
GeoJSON feature info only top feature, 2D

### ISSUE THREAD

**Issue by zoran995** [TerriaJS/terriajs#4542]
In the 2D viewer, when having multiple overlapping elements in GeoJSON the GetFeatureInfo tool will select only the top element and the underlying elements won't be selectable. 

[example layer](https://gist.githubusercontent.com/zoran995/42ba2355a38099a93de58be4352fe1f4/raw/9b8d0aca5046f1146bb298abc0be8398c6361a56/tiger_landmarks.json)

[Map share](http://ci.terria.io/next/#share=s-hNbifgzA51tKIdbXZZeDFg3Gg6j)

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/5660
