### ISSUE TITLE
Mobx (UI): Remove sass(scss) from version 8

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4545]
There was an effort to make at least the (colour) portion of themeing terriajs at runtime - this has been completed for the majority of the UI, there may be a few leftover components which still use the buildtime-theme.

The next step is to entirely remove scss, this will add more benefits in terms of themed spacing when adjusting scale/look/feel of a given theme, and also ultimately help us with a better responsive UI.

Helps to mature our saas platform

**Comment by soyarsauce** [comment]
Raised from https://github.com/TerriaJS/product/issues/25

**Comment by soyarsauce** [comment]
One point is that we've now consolidated the colours in https://github.com/TerriaJS/terriajs/issues/4545 in sketch.

But we need to
1. within the code itself, consolidate the colours to match
2. generate some sort of living documentation on this, so that it can be referred to by anyone in the team.

**Comment by soyarsauce** [comment]
To break down into immediate needs (themeing) + future needs

**Comment by soyarsauce** [comment]
Is now an epic - will link / scope as needed

**Comment by KeyboardSounds** [comment]
Closed in favour of #6067.
