### ISSUE TITLE
Mobx: Investigate browser support and future plans

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4546]
Investigate what direction we should take for browser support.
To look at microsoft plans/supports for current platforms,
To look at data from NM + anywhere else we can source on terriajs use

(ff 52 should work, 78 is latest)

Bit more background information at https://github.com/TerriaJS/product/issues/25
@marietruelove

**Comment by nf-s** [comment]
# :hocho:  **[DEATH TO IE](https://death-to-ie11.com/)** :hocho:

**Comment by soyarsauce** [comment]
https://death-to-ie11.com/

Another point is Youtube has stopped support for IE11, which would affect the help content that we use to deliver them.

**Comment by zoran995** [comment]
Is there any decision regarding IE11, I see `next` is not working on it anymore (throwing error only IE can understand 🤣)

**Comment by soyarsauce** [comment]
@marietruelove any update on this front?

**Comment by soyarsauce** [comment]
Related
https://github.com/TerriaJS/terriajs/issues/4418
https://github.com/TerriaJS/product/issues/25
https://github.com/TerriaJS/product/issues/27

**Comment by soyarsauce** [comment]
Via @steve9164 

So we have a few options:
- Drop IE11 completely with no view of ever going back on that decision. We upgrade to latest MobX, add service workers, use WASM, etc.
- Continue the status quo. I.e. mostly ignore how TerriaJS v8 works on IE11. Everything that runs in tests will run on IE11 VMs so the functionality works, but the presentation is broken. We can (within a week) reinstate IE11 as a supported browser if we decide so in the future. Until we make the decision to completely drop support we can't add newer technologies to TerriaJS.
- Support IE11. We spend a week before the next TerriaJS v8 release to work on all the layout problems and ensure it looks nice in IE11 before each subsequent release.

**Comment by soyarsauce** [comment]
We are leaning to #1, but I might add the few examples noted in #1 can be done progressively - meaning it's a hybrid of #1 & #2 - stance being dropping official support for it with an avenue for fixing it up for IE11 if a PR comes in for it

**Comment by soyarsauce** [comment]
I'll give it until end of week and if nobody objects to this unmarriage I'll write up the ADR for it to solidify it all

**Comment by soyarsauce** [comment]
Actually the ADR can come at any time in `proposal` status - so end of week is to get the proposal out
