### ISSUE TITLE
MobX: support for WFS

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#4549]
This epic is to consolidate work for enabling support for WFS and ~~Esri Feature Server/Service~~.

**Comment by rowanwins** [comment]
Esri Feature Server already supported in mobx

**Comment by nf-s** [comment]
Related - https://github.com/TerriaJS/terriajs/issues/3661

**Comment by nf-s** [comment]
Related to https://github.com/TerriaJS/terriajs/issues/4218
