### ISSUE TITLE
Review data point marker design

### ISSUE THREAD

**Issue by kgrochow** [TerriaJS/terriajs#455]
The generic marker for data points in geojson is the Cesium default one and among other things is quite large.  We should decide if we like it or want to do something NM specific.

**Comment by hilarycinis** [comment]
This came up in usability testing and needs resolving. 
- The area captured in the square created by the data point marker is too large to be a useful reference indications
- the participants indicated an expectation of more standard devices like a "pin" as well as a "cross hair"
