### ISSUE TITLE
Mobx: arraytrait & objectArrayTrait ordering across strata

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4559]
from @steve9164 re: array traits

>- Think more about some JSON-Patch-like method of modifying an array in levels of strata
	* An array trait in a strata can currently add elements to an array present in a higher strata (and possibly remove using id 
+ null for object array trait?) but can’t override the entire array or reorder elements of the trait in a higher strata

Ran into this issue at https://github.com/TerriaJS/terriajs/pull/4516#issuecomment-654775411 and it won't be the last

**Comment by soyarsauce** [comment]
via @nf-s 
The order of items in an objectArrayTrait change as values change across different strata.
For example, an objectArrayTrait is provided by a LoadableStratum, and then a value is added to the user stratum.

**Comment by nf-s** [comment]
Example - 
![2020-08-24-22-28-14](https://user-images.githubusercontent.com/6187649/91258229-3b652980-e7af-11ea-91bd-96b7b5ba2532.gif)

**Comment by nf-s** [comment]
Example 
![2020-08-26-15-15-40](https://user-images.githubusercontent.com/6187649/91258347-7a937a80-e7af-11ea-8519-e0d414bff36e.gif)

**Comment by soyarsauce** [comment]
I can't immediately think of a good solution without going to using either or both of IDs (similar to `infoSectionOrder`) and assigning some numbered order priority (similar to `StratumOrder`) which would quickly get out of hand, I'll revisit when I can think about this properly

**Comment by nf-s** [comment]
At the moment I'm looking into adding some sort of property to the `ObjectArrayTrait` class itself. It wouldn't be too hard to keep track of ids as objects are added - and you could include a `sortByProperty` similar to `idProperty`.
But I'm not sure how you could change that `sortByProperty` in a nice way (through a catalog item for example):
```ts
(this.traits.dimensions as ObjectArrayTrait<any>).sortProperty = 'what?'
```

**Comment by nf-s** [comment]
One way to make this easier would be to sort out types for `traits` here :
```ts
export interface ModelInterface<T extends ModelTraits> {
  readonly traits: {
    [id: string]: Trait;
  };
```
So it can infer the actual `Traits` class from `T[P]` - something like
```ts
export interface ModelInterface<T extends ModelTraits> {
  readonly traits: {
    [P in keyof T]: SomeMagicalType<T[P]>;
  };
```

**Comment by nf-s** [comment]
I would love if we could handle all of this within `ObjectArrayTrait` and not have to use things like `infoSectionOrder`

**Comment by nf-s** [comment]
This is fixed by https://github.com/TerriaJS/terriajs/issues/4559
