### ISSUE TITLE
Add `eslint-plugin-react-hooks` linting rule

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4565]
We should use eslint to help us with the usage of react hooks via `eslint-plugin-react-hooks`

React already does this for us at runtime, but this would be nice to lint for.

**Comment by nf-s** [comment]
@ljowen to check if this is still needed

**Comment by ljowen** [comment]
Still recommended and treated separately by the react team see: https://www.npmjs.com/package/eslint-plugin-react 

Closing as this plugin will be added as part of #6985
