### ISSUE TITLE
DE UX Testing: Improve compass interactivity

### ISSUE THREAD

**Issue by vicborgy** [TerriaJS/terriajs#4582]
Covering issue no. 31 of [spreadsheet](https://docs.google.com/spreadsheets/d/10eWTU44vUEk-NKm2UcUPEK7qeHSDnRzrXUbMV6nDuBE/edit#gid=0) (medium priority):

**Issue**
> The new compass was annoying some participants, it opens too quickly and they kept accidentally opening it. There's no delay on hover over to prevent accidental opening

**Fixes**
Vic to improve:
- Buttons & styling
- Interaction with compass

**Comment by soyarsauce** [comment]
@vicborgy to attach new solution design

**Comment by vicborgy** [comment]
Here are the designs for the revised compass interaction - https://invis.io/GDYDNTW2UTQ

- Hover state of compass shows a chevron that pops out from behind the compass - rolling away from the compass will deactivate the hover state of the compass
- Clicking the chevron will activate the compass hover info modal
- Closing the modal will close the modal and the open state of the compass

**Comment by soyarsauce** [comment]
Thanks for this @vicborgy - this should really improve things for the compass. Bar the compass not actually working for tablets, what do you think the interaction there should be (for touch devices that are large enough to load the "non mobile UI"?)

Semi related, are you able to progress https://github.com/TerriaJS/terriajs/issues/4189 (& subsequently https://github.com/TerriaJS/terriajs/issues/4673)?

**Comment by vicborgy** [comment]
For touch devices the action to make it expand and show the chevron (and expand compass) would be clicking on the compass or a click + hold.

I will check out those issues you sent.

**Comment by rowanwins** [comment]
Resolved by #4849
