### ISSUE TITLE
Delta: 'Change dates' in difference panel missing underline

### ISSUE THREAD

**Issue by vicborgy** [TerriaJS/terriajs#4598]
After a user has selected their dates in the difference panel, the ‘Change dates’ link should be underlined to match our underlined link style.

**Comment by soyarsauce** [comment]
<img width="131" alt="image" src="https://user-images.githubusercontent.com/9134432/89144844-3cc97a80-d592-11ea-8d47-3f7e16802aba.png">

Needs to be underlined

**Comment by soyarsauce** [comment]
@reginapramesti this one if you feel like it

**Comment by soyarsauce** [comment]
Resolved by https://github.com/TerriaJS/terriajs/pull/4638
