### ISSUE TITLE
Delta: Update close button to latest look

### ISSUE THREAD

**Issue by vicborgy** [TerriaJS/terriajs#4599]
The ‘close button on the difference result image needs to be updated as per 'Delta v3; in Invision - https://invis.io/4BY8M655MGP

**Comment by soyarsauce** [comment]
<img width="106" alt="image" src="https://user-images.githubusercontent.com/9134432/89144525-646c1300-d591-11ea-97d0-91130de7c53b.png">

Currently it's a close button at the bottom
