### ISSUE TITLE
Delta: Date comparison states shifting on location selection

### ISSUE THREAD

**Issue by vicborgy** [TerriaJS/terriajs#4600]
When a location selection is being performed on the image and the lat/long is being queried, the date comparison states shift left to right.

**Comment by soyarsauce** [comment]
Needs min width on lat lng "Area filter selection" section

**Comment by soyarsauce** [comment]
@reginapramesti & this one - to clarify a bit more, the UI around the bottom dock jumps around when you are querying due to the resizing of the lat/lng text

**Comment by soyarsauce** [comment]
Resolved by https://github.com/TerriaJS/terriajs/pull/4638
