### ISSUE TITLE
Set limit on number of legend items

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#4607]
Some layers show way too many legend items:

```json
 {
      "type": "csv",
      "url": "test/localphotostories20092014.csv",
      "name": "ABC Photo Stories"
    },
```

![Kazam_screencast_00011](https://user-images.githubusercontent.com/6187649/88987959-e0a8f100-d31a-11ea-9492-5a2b3b176dff.gif)

Add a limit to number of items shown (and maybe a toggle collapse thing)

**Comment by KeyboardSounds** [comment]
Having too many legend items also makes things take ages to load, like this CSV file: https://drive.google.com/file/d/1Vi3RC940j9C0KpZBY-ubRd4yXcZ9Qrq5/view?usp=sharing

**Comment by nf-s** [comment]
This is fixed by https://github.com/TerriaJS/terriajs/pull/5426 and https://github.com/TerriaJS/terriajs/pull/5507
