### ISSUE TITLE
Request transparent background from WMS servers

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#461]
Geoserver supports a bunch of options to control legend styling:
http://docs.geoserver.org/stable/en/user/services/wms/get_legend_graphic/legendgraphic.html#controlling-legend-appearance-with-legend-options

Other WMS servers (Esri for sure) don't support `legend_options`.

Both Geoserver and Esri support an additional parameter, `transparent=true`, that gives the legend a transparent background instead of a white one.  This doesn't go well when we put the transparent image on a dark background, though, because there doesn't appear to be any way to tell the Esri server to make the label text anything other than black.  In a geoserver, it works great, because we can also tell the geoserver to use white text.

Esri servers also support `width` and `height`.  By specifying the width to be the width of the legend window, we get much better results from Esri servers.  For example (from `Social and Economic -> Population Estimates`), this:

![Without Width](http://www.ga.gov.au/gis/services/hazards/NEXIS_2012_WMS/MapServer/WMSServer?service=WMS&version=1.3.0&request=GetLegendGraphic&format=image/png&layer=7)

becomes this:

![With Width](http://www.ga.gov.au/gis/services/hazards/NEXIS_2012_WMS/MapServer/WMSServer?service=WMS&version=1.3.0&request=GetLegendGraphic&format=image/png&layer=7&width=350)

But Geoserver interprets `width` differently, so we get terrible results if we pass `width=350` to a geoserver.

The upshot of all this is that, for best results, we need to do detection of the WMS server vendor, and tailor our `GetLegendGraphic` requests accordingly.

**Comment by kring** [comment]
[WMS 1.3.0 spec](http://portal.opengeospatial.org/files/?artifact_id=14416) section 7.3.3.4:

> If the server advertises several styles for a layer, and the client sends a request for the default style, the choice of which style to use as default is at the discretion of the server. The ordering of styles in the service metadata does not indicate which is the default

**Comment by stevage** [comment]
Ok, I see two relevant issues remaining (given the recent Legend refactor and MapServer Legend support):
1. We could send parameters to GeoServer to generate a slightly nicer legend. I'm not sure what we'd really change though? Different background?
2. We could generate our own legend, using GetStyles. I didn't know this was possible. Should we?

**Comment by kring** [comment]
> We could send parameters to GeoServer to generate a slightly nicer legend. I'm not sure what we'd really change though? Different background?

Yep, that's the main improvement I can think of.

> We could generate our own legend, using GetStyles. I didn't know this was possible. Should we?

That'd be super cool, but probably not especially high priority.

**Comment by stevage** [comment]
To restate your original issue, we should:
- [Somehow detect](http://gis.stackexchange.com/questions/182627/how-to-programmatically-determine-if-a-wms-endpoint-belongs-to-a-geoserver) whether a given WMS service is GeoServer, Esri, or Other.
- If GeoServer, we should:
  -  request a transparent legend *`&Transparent=True`
  - request white text (`&LEGEND_OPTIONS=fontColor:0xdddddd`)
  - possibly set other parameters to style the legend more consistently with our own (`;fontSize:14`)
  - possibly request a high DPI legend (`;dpi:182`)
  - possibly request that item boxes be the same size as the ones we draw (`&width=30&height=30`)

[For example](https://programs.communications.gov.au/geoserver/ows?service=WMS&request=GetLegendGraphic&format=image%2Fpng&width=30&height=30&layer=mybroadband%3AMyBroadband_ADSL_Availability&Transparent=True&LEGEND_OPTIONS=fontColor:0xdddddd;dpi:182)

![geoserver-getlegendgraphic](https://cloud.githubusercontent.com/assets/678344/13386966/42fd5ef8-df06-11e5-853e-c0ba73ad5c3f.png)

To actually implement this probably means intercepting the `Style.LegendURL` return in `GetCapabilities` and munging the URL:
- replace `1.3.0` with `1.1.0`
- add parameters as above.

If the server [is Esri](http://www.environment.gov.au/mapping/services/ogc_services/EPBC_Referrals/MapServer/WMSServer?service=WMS&request=GetCapabilities&version=1.3.0&tiled=true), we should:
- request a wider and taller legend: `&width=350&height=350`
- cry

**Comment by stevage** [comment]
Oh, intriguingly it's actually [possible to pass an external SLD file to an ArcGis server](http://webhelp.esri.com/arcgisserver/9.3/java/index.htm#wms_sld_samples.htm).

**Comment by stevage** [comment]
See [work in progress](https://github.com/TerriaJS/terriajs/compare/wms-transparent-legend?expand=1).

**Comment by stevage** [comment]
Links to three GetCapabilities:
- [Comms GeoServer](https://programs.communications.gov.au/geoserver/ows?service=WMS&request=GetCapabilities)
- [Environment ArcGIS](http://www.environment.gov.au/mapping/services/ogc_services/EPBC_Referrals/MapServer/WMSServer?service=WMS&request=GetCapabilities&version=1.3.0&tiled=true)
- [GA ArcGIS](http://services.ga.gov.au/gis/services/DEM_SRTM_1Second/MapServer/WMSServer?service=WMS&version=1.3.0&request=GetCapabilities)
