### ISSUE TITLE
Mobx bug: auto-detect for certain urls

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4615]
1. visit http://ci.terria.io/next/
2.  click upload
3. click add web data
4. enter `https://services.aremi.data61.io/aemo/v6/csv/all` into step 2, leave on "auto-detect"
5. click add
observe `Use conversion service?` message 
<img width="533" alt="image" src="https://user-images.githubusercontent.com/9134432/89379851-e303b480-d739-11ea-9176-ea726cb242d2.png">

~(trying again by selecting csv and observe it loads fine)~
~trying again by manually selecting csv, will load it into the workbench but it doesn't actually load and throws an error:~
Final note - adding it manually will work if configured correctly, just doing it on CI won't because of cors

**Comment by soyarsauce** [comment]
Also noting this isn't affected by all csvs, e.g. http://ci.terria.io/next/test/incidents_notime.csv will be OK

**Comment by soyarsauce** [comment]
Final note - adding it manually will work if configured correctly, just doing it on CI won't because of cors

**Comment by nf-s** [comment]
I think we need to create an "auto detect" master ticket or something - there are so many issues

**Comment by nf-s** [comment]
Manually selecting CSV works for https://services.aremi.data61.io/aemo/v6/csv/all

Conversion service doesn't exist anymore - so closing
