### ISSUE TITLE
Auto-detected WMS/WFS group URLs will flick between My Data and Data Catalog

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#4619]
Also, the `DataDescription` isn't showing in MyData

![Kazam_screencast_00013](https://user-images.githubusercontent.com/6187649/89485045-3847d080-d7e3-11ea-913d-f4f93c58a932.gif)

**Comment by hardreddata** [comment]
I think also https://github.com/TerriaJS/terriajs/issues/4468

**Comment by nf-s** [comment]
Thanks @RussellGrew I should have searched more thoroughly for existing tickets!
