### ISSUE TITLE
Story v2.0 - Save map settings 

### ISSUE THREAD

**Issue by KeyboardSounds** [TerriaJS/terriajs#4620]
From watching @meh9 demo, he often wants to show a catalog item with a specific basemap. Rather than him manually having to switch as he flicks through a story, we should store which basemap to use.

Update 02/07/2021: 
- stories should save all map settings: 
1) base maps
2) terrain settings especially "terrain hides underground features" 
3) opacity
4) quality slider

**Comment by hardreddata** [comment]
I might have discussed similar with Kevin before re: terrain. 

Suppose I share something which requires realistic terrain and the user is either in 2D, or smooth globe and so my share is floating. 

There may have been a case for not doing it.

Here I am thinking that sharing and stories are somehow linked.

**Comment by wibily** [comment]
crispy available to pair

**Comment by wibily** [comment]
Ana: decision made to save all map settings into share urls

**Comment by wibily** [comment]
base map settings should be saved per scene
