### ISSUE TITLE
When pre-loading a WMS with time dimension, do not "wrap" and pre-load the first time

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#4627]
We pre-load WMS data that has a time dimension. 

E.g. we have a WMS with the following times:

2010-01-01
2010-02-01
2010-03-01
2010-04-01
2010-05-01

When you view the 2010-03-01 time, Terria will also load the image tiles for 2010-04-01 so that when we to switch to that time the tiles are already available and will switch quickly.

Similarly, when you view 2010-05-01 it will "wrap" around and pre-load the image tiles for 2010-01-01. By far the most common case is that the user will land on the most recent date, in this case 2010-05-01, and then will in most cases not want to see the first, or 2010-01-01, time. In this case loading 2010-01-01 is a waste, and slows down loading 2010-05-01.

As a special case, we should not wrap around and pre-load the "first" time when we are viewing the "last" time.

**Comment by nf-s** [comment]
Related: #4272

**Comment by rowanwins** [comment]
I believe this is already resolved in `next` branch

If you look at this share
https://tc-user-testing.terria.io/#share=s-mew5Duk51mA84eXzN8BJ37jrfGi
Only the current dates images are requested as it's the last date.
