### ISSUE TITLE
Update outdated readme.md of terriajs repo

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4641]
Update outdated readme.md of terriajs repo
https://github.com/TerriaJS/terriajs/

- quick pass on master readme (remove things like IE9 support)
- link to v8 readme from v7 readme
- then focus on making v8 readme accurate

**Comment by soyarsauce** [comment]
@steve9164 to update this when more of the v8 docs are done

**Comment by soyarsauce** [comment]
Above still relevant

**Comment by nf-s** [comment]
done
