### ISSUE TITLE
Chart mouse hover is slow

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#4663]
![2020-08-24-22-28-14](https://user-images.githubusercontent.com/6187649/91044777-2e362680-e659-11ea-8b09-59d608ddaea1.gif)

**Comment by na9da** [comment]
I have made a small improvement by preventing re-rendering of xAxis during mouse moves (https://github.com/TerriaJS/terriajs/pull/4696)

We should see higher performance for small data sets. However for larger data sets, there will still be the bottle neck of mapping mouse point to its nearest domain value. This is already optimized to a certain extent by using binary search. For more optimization we will have to look at tricks like domain clipping.

**Comment by na9da** [comment]
Closing as the problem appears to be fixed for now by https://github.com/TerriaJS/terriajs/pull/4696
