### ISSUE TITLE
Mobx: iOS safari is white screen

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4670]
Repro:
1. visit http://ci.terria.io/next/
2. observe loading gif
3. observe loading gif fading out into a white screeen

**Comment by soyarsauce** [comment]
https://nsw.digitaltwin.terria.io/ is OK so it may point to a problem between
8.0.0-alpha.43 && the current latest

**Comment by zoran995** [comment]
Just tried to run on iOS using BrowserStack, and here is a screen of the thrown error. Oddly, https://nationalmap.prod.saas.terria.io/ runs just fine, and it seems to be using one of the latest version of terriajs
![image](https://user-images.githubusercontent.com/19208948/113839373-eb603380-978f-11eb-8ae4-107fd2c74ed3.png)

**Comment by na9da** [comment]
Fixed by #5807.
