### ISSUE TITLE
Mobx: UI branding is offset

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4671]
The latest changes in https://github.com/TerriaJS/terriajs/blob/next/lib/ReactViews/SidePanel/branding.scss have thrown off the branding centering defaults (this was done so that overrides from TerriaMap were more possible), now that we are ditching IE11 we can overhaul the whole section

![image](https://user-images.githubusercontent.com/9134432/91247101-da305c80-e794-11ea-9393-ad0021dc56ba.png)
![image](https://user-images.githubusercontent.com/9134432/91247110-de5c7a00-e794-11ea-929b-29dd833fdd4d.png)

**Comment by zoran995** [comment]
This section is rewritten to typescript, so assume no longer relevant
