### ISSUE TITLE
Port csw model to v8

### ISSUE THREAD

**Issue by rowanwins** [TerriaJS/terriajs#4693]
https://github.com/TerriaJS/terriajs/blob/master/lib/Models/CswCatalogGroup.js
About 700 lines of code

It's used in AREMI
https://github.com/TerriaJS/aremi-natmap/blob/5907595275355be599da038f3119dc5016c33e16/datasources/aremi/custodian/CSIRO_OandA/WaveAtlas.ejs
Not sure if anywhere else...

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/5291
