### ISSUE TITLE
Warn community PR submitters that Travis will fail for them

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#4703]
It's my understanding that Travis fails for external committers due to some issue with API keys for SauceLabs ¯\_(ツ)_/¯

We need to either fix that issue, or notify them to expect this so they don't spend time trying to address an issue not their fault that they cannot fix.

E.g. https://github.com/TerriaJS/terriajs/pull/4702

**Comment by tephenavies** [comment]
Currently we default to an old config file built to run tests inside Electron for external PRs. The config doesn't work though. We should instead add a new config file to run the tests in a local Firefox, [Travis docs here](http://karma-runner.github.io/4.0/plus/travis.html).

- [x] Make a new karma config file for local Firefox
- [x] Change Travis .yml file to enable running Firefox and change gulpfile to use the new firefox config file
- [x] Merge to `master`
- [x] Merge to `next`

**Comment by tephenavies** [comment]
This should now be fixed!
