### ISSUE TITLE
Story v2.0 - Feature Info window not being closed correctly in story maps

### ISSUE THREAD

**Issue by robbibt** [TerriaJS/terriajs#4709]
Example story map here:
http://maps.dea.ga.gov.au/#share=s-1O2xJdIvNDg4JJa89HpDb0iCNwO

**Current result**
There seems to be a potential bug/limitation of the story functionality where if one scene brings up a Feature Info window, the window persists despite the next scene being captured with the window closed (see transition between Scene 2 and 3; the chart panel should disappear but it doesn't). 

**Expected result**
If a scene is captured after the Feature Info window is closed, I would expect the Feature Info window to disappear when the user navigates to this scene. Otherwise, the Feature Info window will persist for the entire remainder of the story map, which is confusing to users.

**Comment by rowanwins** [comment]
Note the feature info popup doesnt work v8, see #4837

**Comment by na9da** [comment]
I think we can close this as it is fixed in v8 by - https://github.com/TerriaJS/terriajs/pull/4846

Here is a similar store I captured that demonstrates the fix - https://maps.dea.ga.gov.au/#share=s-2lpycbhvjV0gLstad4HMwBRlKoV
