### ISSUE TITLE
Feedback on story map functionality

### ISSUE THREAD

**Issue by robbibt** [TerriaJS/terriajs#4711]
Hi all, I've done some work with the Story Map functionality in Terria to produce a story for an upcoming product release. The functionality is fantastic, but I had some minor issues that I think could improve the user experience:

1. Once formatted text is pasted into the body of the scene text editor, it was very difficult to revert to the original default formatting (e.g. font and font colour). I was pasting content from a word document and accidentally forgot to paste as plain text, resulting in non-matching formatting. To make the text consistent with my other scenes, I had to copy existing text from another scene, then plain text paste my new text into that to restore the default formatting (simply clearing the badly formatted text then pasting as plain text still retained the incorrect formatting).  **Proposed solution:** include a "restore default formatting"/"convert to raw text"/"remove formatting" button that would restore all formatting to the defaults.

2. Email links don't currently seem to be supported. I tried both "dea@ga.gov.au" (which was converted into a relative link), and "mailto:dea@ga.gov.au" (which was converted to plain text)

3. In addition to Header 1 and Header 2 options, I would have liked an option for smaller caption-style text too. This would allow us to include a figure caption or reference below any included images in a less distracting/obvious way

Points 1-3 superseded by: https://github.com/TerriaJS/terriajs/issues/5595

4. This may be more of a Terria issue than a Story Map specific issue, but one frustration I had was that once I had clicked on the map at any point, the blue placemark symbol was impossible to remove. This meant that it was included in my subsequent scenes even though I would prefer that it did not appear in the story map at all. Perhaps I am missing a simple way/place to click to remove this symbol from the map?

![image](https://user-images.githubusercontent.com/17680388/92074545-aa6aff80-edf9-11ea-8d2b-01443373bda7.png)

Point 4 superseded by: https://github.com/TerriaJS/terriajs/issues/5596 

5. Being able to demonstrate to users on how to click on a feature to view the Feature Info is really fantastic. However, this potential bug meant that once a Feature Info box was shown in the story, it persisted until the user manually closed that pop-up even if future scenes no longer relate to that Feature Info: https://github.com/TerriaJS/terriajs/issues/4709

**Comment by robbibt** [comment]
6. Finally, if scene is at full zoom and you transition to another full zoom at another location on the other side of the country, the transition is so fast that the basemap imagery has no time to load, and the overall result is a disorienting hard-cut to the next scene without a good impression of where you have zoomed to. I think a slightly slower transition from full zoom > continental view > full zoom would make this experience a bit more user friendly and less disorienting. (Google Earth does a quite nice job of zooming out then in again smoothly)

For example: https://www.loom.com/share/0231ade1796a4523a208bbb6aef61417

**Comment by AnaBelgun** [comment]
Thank you @robbibt this feedback will go into Story v2 which is planned for this FY.

**Comment by AnaBelgun** [comment]
Closing because superseded by other smaller tickets. 
https://github.com/TerriaJS/terriajs/issues/5597 
https://github.com/TerriaJS/terriajs/issues/4709
https://github.com/TerriaJS/terriajs/issues/5596
https://github.com/TerriaJS/terriajs/issues/5595
