### ISSUE TITLE
Adding items to workbench isn't consistent across code-base

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#4719]
Maybe we should replace all instances of `workbench.add` with `addToWorkbench` as this function includes all loading of mappable/chartable...
Or we could combine `addToWorkbench` with `workbench.add`.

**Why**:
- It is confusing
- We seem to run into loading issues every now and then, for example drag-dropping files wasn't triggering `loadMetadata` or `loadMapItems`. Similar issue with splitting items.
- Some catalog items recreate functionality of `addToWorkbench` -  eg WPS
- If we want to change how loading catalog items works in the future, it is difficult because there are calls scattered around, whereas most could be removed if we moved everything into `workbench.add`

Also - we need feedback if catalog member is loading. For example, when you Add a catalog item to the workbench, the data catalog panel will stay visible until it has finished loading.

**Comment by soyarsauce** [comment]
As discussed,
Given that we couldn't think of a scenario where you would add something to workbench and not want to load it.

- break / remove / shift `addToWorkbench` into `Workbench.ts` actions, and merge it with `workbench.add`

**Comment by nf-s** [comment]
`addToWorkbench` has been replaced with `workbench.add` - https://github.com/TerriaJS/terriajs/pull/4919
