### ISSUE TITLE
Update to new NEXIS server

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#472]
@philipgrimmett noticed that the National Exposure Informatiom System 2012 has a layer called "Warning".  When enabled, you get this:
![image](https://cloud.githubusercontent.com/assets/924374/5370492/f49410fc-8076-11e4-9cff-c923fe8c48e4.png)
As far as I can tell, the map referenced in the URL in the screenshot doesn't actually exist.  Here's the ArcGIS services directory for the server, though:
http://www.ga.gov.au/gis/rest/services/hazards

We should figure out what we should actually be using and switch over to it.  Assuming the service will actually be shut down in December 2014 like the image says, this needs to happen soon.

**Comment by kgrochow** [comment]
I'm having all kinds of problems trying to do anything with their nexis server replacement.  I think we need to pull for now.
