### ISSUE TITLE
Mobx: drag and drop of shapefiles

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4721]
2 problems:
1. Currently drag & dropping shapefiles into a v8 map won't even attempt to convert it - the UI suggests uploading, but clicking "upload" does nothing.
2. drag and dropping a zip file does not get rid of the overlay as if it's stuck in a drag over event and the "convert/upload" path hasn't been considered/realised for v8

Related:
https://github.com/TerriaJS/terriajs/issues/4633

https://github.com/TerriaJS/terriajs/issues/3082

https://github.com/TerriaJS/terriajs/issues/2907

**Comment by nf-s** [comment]
We should just do it client-side, there are libs which do a pretty good job.
We only support small shapefiles/geojson anyway, so we won't get caught by performance issues of converting in the browser

**Comment by nf-s** [comment]
I'm happy to take this on - i've used a few shapefile js libs before

**Comment by soyarsauce** [comment]
"will be addressed as part of TerriaJS/terriajs#4721 - will do it as part of Oct regular release"

**Comment by soyarsauce** [comment]
Client side this to remove the terriajs-server convert dependency

**Comment by zoran995** [comment]
@nf-s @soyarsauce anyone started to work on this? If not, I could take out the initial work during this week. Do you have a preferred library to use or at least suggestion?

**Comment by KeyboardSounds** [comment]
thanks for offering @zoran995, but I've already started. :) I'll be sure to update this issue when I've got progress worth showing!

**Comment by soyarsauce** [comment]
Emma WIP

**Comment by tephenavies** [comment]
Client side support added in #5080.
