### ISSUE TITLE
update terriajs-cesium to 1.73

### ISSUE THREAD

**Issue by KeyboardSounds** [TerriaJS/terriajs#4722]
(putting the issue here because since the terriajs-cesium repo is forked, we can't make issues in it)

This will give us:
- an updated default ion key— the old one is broken, so any maps using it won't work
- anti-aliasing (once we've merged https://github.com/TerriaJS/terriajs/pull/4651)

**This merge needs to be done very carefully, because changes we made in our fork were accidentally merged upstream and reverted. If we merge the reversion commits in, they'll revert the changes in our fork. Each change will need to be merged manually.**

**Comment by soyarsauce** [comment]
@KeyboardSounds & @reginapramesti will work together on it.

@reginapramesti will give it a whirl first
