### ISSUE TITLE
Stratum choice

### ISSUE THREAD

**Issue by zoran995** [TerriaJS/terriajs#4723]
Are there more extensive any information around the decisions on CommonStrata choices and when to use which? 

I am working on the implementation of more generalised data search (search in the data catalog) and the usage of `CommonStrata.underride` for all layer data obtained from capabilities seems little wrong to me. Currently, in wms and wfs there are `isOpenInWorkbench` and layer `name` on the same stratum level

**Comment by nf-s** [comment]
Yep totally agree, and we should add some JSDoc strings to the CommonStrata enum

**Comment by zoran995** [comment]
I solved the search part by adding `CommonStrata.search` locally and updating some catalog items to use it, but something like `CommonStrata.catalogItem` is maybe better naming for it to store information about catalog item. 
If you want I can create a pull request with the change mentioned above?
