### ISSUE TITLE
Using createStratumInstance with traits which have nested objectTraits

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#4727]
We can't `createStratumInstance` with traits which have nested `objectTraits` (or arrays...)

**From slack:**
... in WMS catalog item we have `LegendTraits` and `WebMapServiceAvailableLayerStylesTraits` which also includes `LegendTraits`

We copy `LegendTraits` from `availableStyles` in `@computed get legends()...` - https://github.com/TerriaJS/terriajs/blob/next/lib/Models/WebMapServiceCatalogItem.ts#L163-L166

```ts
if (layerStyle !== undefined && layerStyle.legend !== undefined) {
  result.push(
    <StratumFromTraits<LegendTraits>>(<unknown>layerStyle.legend)
  );
}
```

Is there a nice way of copying all traits across instead of having to use `createStratumInstance` for each `LegendTraits` (and then `createStratumInstance` for each `LegendItemTraits` )?

For example

```ts
const legend = createStratumInstance(LegendTraits, layerStyle.legend)
legend.url = 'change the url to something...'
result.push(legend)
```

**Comment by wibily** [comment]
Not needed/wrong
