### ISSUE TITLE
dataCustodian on wms Group to propagate into layers?

### ISSUE THREAD

**Issue by hardreddata** [TerriaJS/terriajs#4743]
This may be a bad idea but it is something I have been wondering about.

Presently in v7 I can do 

```
{
   "name":"Some group of layers",
   "type":"wms-getCapabilities",
   "url":"http://some/ows",
   "dataCustodian":"© Some State (Some Dept)",
   "description":"Some description"
}
```

but the individual layers loaded from this do not contain the necessary attribution text set at the group level. For the end user to see this attribution they need to click on the group heading in the catalogue. With the convenience of the `getCapabilities` I have no way of editing the various layers within.

Could it (should it?) propagate into the layers themselves?

I see this as being useful for connecting to government sources but also internal services where our GeoServer workspaces are typically organised by vendor.

Somewhat on topic I think the GeoServer --> Layer, Publishing, WMS Attribution, Attribution Text field doesn't find its way into the Cesium Credit field and so Terria? And attribution must be set at the catalogue level?

Thanks.

**Comment by hardreddata** [comment]
Related to this is that the GeoServer attribution text returned in the WMS getCapabilities query doesn't find its way into the Terria catalogue.

```
<Layer queryable="1" opaque="0">
<Attribution>
<Title>
The attribution text
</Title>
</Attribution>
</Layer>
```

https://docs.geoserver.org/stable/en/user/data/webadmin/layers.html#wms-attribution

**Comment by nf-s** [comment]
This should be able to be done with `itemProperties`

```
{
  "name": "Some group of layers",
  "type": "wms-group",
  "url": "http://some/ows",
  "itemProperties": {
    "dataCustodian": "© Some State (Some Dept)"
  },
  "description": "Some description"
}
```
