### ISSUE TITLE
Mobx: About pages

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4744]
Roll efforts to streamline about pages for both saas, and TerriaMap, into one:

**quoted below via slack**

i looked over several about pages (nsw, qld, de-aust/africa, drought map, nationalmap to name a few) and they all look pretty stock standard. as part of the saas effort - i'll be doing the about pages makeover zupaquik prototype today that looks something like

- about+help+faq+(optional privacy) templates
- basic data structures to support supplying the content via json(+values parsed as md like we do for the in-app help stuff)
content for this will be either stored on map config aspect for about pages or a static json blob for non-magda, open source maps
- looking to try this out with nextjs routed on a subpath
- will figure out prerender/SSR afterwards

i'll aim to have something out tomoz, if not end of today. lemme know if you have anything to add or stuff i should be mindful of.

**Comment by soyarsauce** [comment]
https://github.com/TerriaJS/prototype-about-pages

**Comment by soyarsauce** [comment]
Show in meeting next week how it works

**Comment by soyarsauce** [comment]
@soyarsauce to roll this in the ("release tutorial")/platform demo

**Comment by soyarsauce** [comment]
This is now become a high priority to open source the prototype and tie it back to upstream TerriaMap

**Comment by nf-s** [comment]
No longer relevant - we are decommissioning https://github.com/TerriaJS/prototype-about-pages
