### ISSUE TITLE
Request: set getFeatureInfo request URL in json file

### ISSUE THREAD

**Issue by martin-bom** [TerriaJS/terriajs#4751]
Hi,

Is it possible to set the getFeatureInfo request URL in the json file for a specific WMS layer?
Reason:
I want to load a WMS layer provided by ALA, the WMS layer and the Feature Info URL are not the same:

WMS Layer URL (GetCapabilities):
https://biocache-ws.ala.org.au/ws/ogc/ows

Get Feature Info URL:
https://biocache-ws.ala.org.au/ws/ogc/getFeatureInfo

Thank you.

Cheers,
Martin

**Comment by hardreddata** [comment]
Try the `dataUrl` option from https://docs.terria.io/guide/connecting-to-data/catalog-type-details/wms/

**Comment by martin-bom** [comment]
Hi @RussellGrew 

Thank you for the reply. The following is my setup:

`
				  "dataUrl": "https://biocache-ws.ala.org.au/ws/ogc/getFeatureInfo",
				  "metadataUrl": "https://biocache-ws.ala.org.au/ws/ogc/ows",
				  "url": "https://biocache-ws.ala.org.au/ws/ogc/wms/reflect",
`

But when I click on the map trying to trigger the getFeatureInfo, the underlying request submitted is the `url` option instead of the `dataUrl` option.

Thank you.

Cheers,
Martin

**Comment by hardreddata** [comment]
Ah.

I misunderstood your question.

I am not sure if what you are asking is possible. Someone else will know.

Cheers.

**Comment by martin-bom** [comment]
@RussellGrew It's alright, I am happy you had responded to my request and joined the discussion. Thanks.

Cheers, Martin.

**Comment by soyarsauce** [comment]
@KeyboardSounds to talk to ala on whether it will be addressed

**Comment by KeyboardSounds** [comment]
This is supported by the WMS spec: http://portal.opengeospatial.org/files/?artifact_id=14416 (see page 11)
> The URL may be different for each operation, or the same, at the discretion of the service provider.

Therefore, we should support this in v8 of Terria.

**Comment by KeyboardSounds** [comment]
When implementing this, use the url specified in `OnlineResource` in `Capability` for GetFeatureInfo returned by GetCapabilities as well as adding a trait to specify it manually.

**Comment by martin-bom** [comment]
Hi @KeyboardSounds , I have emailed you with a sample of the JSON configuration to simulate the issue. Thank you very much.

**Comment by soyarsauce** [comment]
w/ @KeyboardSounds  - as it's in line w/ ogc spec

**Comment by rsignell-usgs** [comment]
@AnaBelgun (or other Terria Gurus) , what is the status of this issue?  

I see this issue has a `Version 8` tag but is still open. 
 
Was this feature perhaps included in Version 8, and the issue just not closed here? (he asked hopefully 😸 )

**Comment by AnaBelgun** [comment]
hi @rsignell-usgs we see @martin-bom has submitted a PR in Cesium to fix it: https://github.com/CesiumGS/cesium/pull/9563

@martin-bom are you still involved / continuing that PR?

**Comment by martin-bom** [comment]
@AnaBelgun I stopped for a while on that PR. I can check on that later but not sure if it is compatible with TerriaJS v8 (I was using v7 at that moment).

**Comment by rsignell-usgs** [comment]
@AnaBelgun , thanks for the update, and thanks @martin-bom for revisiting this issue!

**Comment by urbanows** [comment]
@AnaBelgun I'm glad to see activity on this issue as we have a core use case that requires this capability. I appreciate you and the team looking at it.

**Comment by lilleyse** [comment]
The CesiumJS PR was merged and will be released in CesiumJS 1.89 on January 3rd. https://github.com/CesiumGS/cesium/pull/9563

**Comment by rsignell-usgs** [comment]
@urbanows Does https://github.com/CesiumGS/cesium/releases/tag/1.89 resolve your issue?

**Comment by urbanows** [comment]
@lilleyse Thanks for the work, this is what I was looking for!
