### ISSUE TITLE
Move away from using jsx-control-statements

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#4759]
Using jsx-control-statements allows us to write JSX like:

https://github.com/TerriaJS/terriajs/blob/e4758fdcb21b9da89beab4c3e547d69be87dded2/lib/ReactViews/Preview/MetadataTable.jsx#L32-L46

(and `<For>`).

These are neat and might make JSX slightly more readable (esp. for programmers familiar with templating libraries), however with our migration of .jsx files to .tsx we cannot continue using jsx-control-statements without additional effort in tooling. I see ~~3~~ 4 options:
- Try to use jsx-control-statements as is
    * AFAIK without writing a [TypeScript language service plugin](https://www.typescriptlang.org/tsconfig#plugins) we would need to use `// @ts-ignore` and/or deal with large parts of our jsx not being type-checked
- Rewrite `<If>`, `<Choose>`, `<For>` etc. as "proper components"
    * We can't do this without changing the syntax slightly otherwise errors will occur due to the loss of short-circuiting.
E.g. `<If condition={isDefined(foo)>{renderSomething(foo.bar)}</If>`  will throw if `foo` is `undefined`
    * We could support the following, where the child of any `<If>`, `<Choose>`, `<For>` etc. is a function (and in the case of `<For.` the function would take the usual 3 arguments of `[].map`):
`<If condition={isDefined(foo)>{() => renderOtherStuff(foo.bar)}</If>`
    * (Or something similar to that passing the function as a prop)
- Replace jsx-control-statements with js/ts
    * `<If>` can be replaced with a ternary operator
`{isDefined(foo) ? renderSomething(foo.bar): null}`
    * `<For>` can be replaced with `[].map`
`{myItems.map(item => renderSomething(item.foo))}`
    * In many cases `<Choose>` doesn't have a great one-line alternative. It can be represented as many nested ternaries, but please don't. I'd recommend replacing with a new function. That function can have an `if`, `else if`, `else` structure to deal with all the different cases
- Convert `<Choose>`, `<When>` and `<Otherwise>` to proper components but ditch `<If>` and `<For>`
    * `<Choose>` et al. don't have great alternatives in plain js/ts without splitting code into functions, which makes jsx more convoluted

**I vote for replacing jsx-control-statements with JS/TS!**

Related to #3501, #4470, #4656.

- [x] Write any decision made in to the [frontend style guide](https://github.com/TerriaJS/terriajs/blob/next/doc/contributing/frontend-style-guide.md)

**Comment by rowanwins** [comment]
I had to ask what those bits were when I started working on the Terria team, I'd worked with jsx but I'd never seen these magical `<If>` elements before. I support the proposal to use regular ol' js/ts

**Comment by tephenavies** [comment]
Added a hybrid 4th option

**Comment by nf-s** [comment]
I support "Replace jsx-control-statements with js/ts" - which is what I have been doing up to now anyway!

**Comment by tephenavies** [comment]
Due to lack of support of any other option we're going with removal of jsx-control-statements!
