### ISSUE TITLE
Stop automatically updating autoupdating layers when the layer is disabled in the workbench

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#4766]
For compute intensive layers like Live Buses that reload themselves every 5 seconds, for performance and other reasons we sometimes want to include them in Share/Stories as added to the workbench but not actually enabled. However, in this state the timer is still running and the reloading of the data still occurs, even though we are not displaying the data.

<img width="351" alt="Screen Shot 2020-09-22 at 17 48 31" src="https://user-images.githubusercontent.com/5283003/93856111-d6441b80-fcfb-11ea-97a0-85743d830582.png">

When autoupdating layers like Live Buses, Current Power Generation etc have been added to the workbench but disabled, we should no longer display/run the timer, and we should no longer perform the data update in the background.

**Comment by rowanwins** [comment]
Resolved by #4781
