### ISSUE TITLE
When we add an additional terrain surface but disable it in the workbench, it's still enabled

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#4767]
When viewing underground infrastructure it can be useful to add an additional more accurate terrain surface to more accurately hide underground data. However, once added, this additional terrain surface is always displayed even if it is disabled in the workbench. The only way to not show it is to actually remove it. This is misleading to the user.

Share URL for the area used to take the screenshots below - note you need to be authorised to see the data:

https://nsw.digitaltwin.terria.io/#share=s-2NivngSkBAd5ri3MxTzqur3G1Bh

Without additional terrain:

<img width="756" alt="Screen Shot 2020-09-22 at 17 57 44" src="https://user-images.githubusercontent.com/5283003/93856926-1f489f80-fcfd-11ea-96ae-6cd029c412be.png">

With additional terrain:

<img width="755" alt="Screen Shot 2020-09-22 at 17 58 20" src="https://user-images.githubusercontent.com/5283003/93856971-35566000-fcfd-11ea-9ff4-0165bf4f3b03.png">

With additional terrain but disabled (i.e. should show the same as the "without additional terrain" at top above):

<img width="757" alt="Screen Shot 2020-09-22 at 17 58 48" src="https://user-images.githubusercontent.com/5283003/93857019-4606d600-fcfd-11ea-9fe5-15f3a9940cf4.png">

**Comment by zoran995** [comment]
Fixed in #6460
