### ISSUE TITLE
Autoupdating layers unselects features on reload

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#4768]
When viewing an autoupdating layer like Current Power Generation, if you have clicked one of the features to bring up the Feature Info, when the reload happens the feature is unselected, meaning the Feature Info popup "minimises". This is very infuriating.

Here is a gif demonstrating the problem:

![Hnet-image](https://user-images.githubusercontent.com/5283003/93858482-92531580-fcff-11ea-8fbe-19b2d800566c.gif)

**Comment by soyarsauce** [comment]
@na9da : this needs some rewriting of the csv? / table? catalog item to sort out, to make it in line w/ GTFS

**Comment by soyarsauce** [comment]
Will be needed by AREMI as well

**Comment by nf-s** [comment]
A good temporary fix - increase refresh time to 5 minutes.

@KeyboardSounds to do DigitalTwin catalog items
@nf-s to do SaaS catalog items

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/6441
