### ISSUE TITLE
Onboarding: Terry Trainer - "Get Started with the map" workflow

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#4770]
**Context:**
Currently the Terry Trainer functionality only works for these apps: 
https://de-australia.dev.saas.terria.io/ and https://de-africa.dev.saas.terria.io/

The Workflow is triggered from Help menu, under "Step by Step Guide" 

![image](https://user-images.githubusercontent.com/18452161/93950124-00422000-fd86-11ea-9fbc-9dac84f84b63.png)

Once the user selects one of the workflows, it opens in a separate top screen tab: 

![image](https://user-images.githubusercontent.com/18452161/93950177-29fb4700-fd86-11ea-9974-f8d2ae248865.png)

Because these examples of workflows are quite specific to Satellite Imagery interaction, we need a basic "Get started with a map" version, which will be included in all maps by default going forward. 

**This ticket spells out the steps and the wording for this basic workflow.** 

**Getting started with the map**

1: Search for a location to find an area of interest
2: Use "Explore map data" to view data catalogue
3: Search for data or browse catalogue
4: Add data to map by clicking on + sign or "Add to map" button in preview window
5: Interact with data, including opacity and toggling on & off on the left in your workbench
6: Click on data on the map to view more details by triggering Feature Information panel 
7: Change you basemap using options in "Map Settings" to improve contrast
8: Zoom and change view using the controls on the right-hand side of the screen

**Comment by soyarsauce** [comment]
terriajs: https://github.com/TerriaJS/terriajs/pull/4798

content provided as plain string in TerriaMap to be i18nified: https://github.com/TerriaJS/TerriaMap/issues/484

**Comment by soyarsauce** [comment]
Can be closed when https://github.com/TerriaJS/TerriaMap/issues/484 is resolved

**Comment by AnaBelgun** [comment]
TerriaJS/TerriaMap#484  resolved
