### ISSUE TITLE
Model architecture: "Alias IDs" or shareKeys

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4774]
Expanding on https://github.com/TerriaJS/terriajs/issues/3654#issuecomment-697124260,

@nf-s : >It should be easy to add some sort of id map if needed though

@soyarsauce:
>yeah id map is easy but we should do it at terriajs level as a trait.

>for magda - when i put a v7 catalog into https://github.com/TerriaJS/init-to-magda it will generate UUIDs to avoid name clashes. so in the DEA prod v7 catalog right now, there exists a layer with ID dea_coastlines but it gets created into something that looks like https://dev.saas.terria.io/api/v0/registry-auth/records/b7dc3bcc-0a96-4d76-a190-dec7c42e132f?optionalAspect=terria

>maybe just simplifying it down, all we need is a way to store that b7dc3bcc-0a96-4d76-a190-dec7c42e132f used to have IDs (or ID generated from name) that included dea_coastlines, so that share/story links have a way to reference back and it'll "just work"

and via @nf-s 
>I think that might sort out my user added data nested group id problem also - as I would just need to convert id for the top level group - and it could have some reference to its old id, so all nested items can still refer to it

Let's get a minimal implementation of this, while being careful that it doesn't break actual normal ID usage, ie `getModelById` should always return a model that actually has a uniqueId `foo1` over a model that has uniqueId `bar2` but with `aliasIds: ["foo1"]`

**Comment by nf-s** [comment]
I think `shareKeys` from master may be relevant - https://github.com/TerriaJS/terriajs/blob/b58c4bd314d24c4f9b9afd7237c373343432d0d2/lib/Models/CatalogMember.js#L128-L134

**Comment by soyarsauce** [comment]
On @steve9164 Sprint64Top10, to reach out to team if run into things

**Comment by soyarsauce** [comment]
Crispy to start implementation and we take it from there


(brief discussion)
//nfs: problem: going from catalog based maps, to magda based maps.
- magda will add "random IDs" to everything
- IDs do not match the automatically generated ID (from a json based catalog)
- share keys added in catalog-converter - perhaps generate IDs in catalog converter
- [init-to-magda](https://github.com/TerriaJS/init-to-magda) to carry the rest of the load of (v8 json catalog -> magda)

**Comment by tephenavies** [comment]
- [x] Implement `shareKeys` for JSON catalogs (see #4975)
    - [x] Add `shareKeys` when a JSON catalog is loaded
    - [x] Try to match ids in share data by registered share keys (if an id doesn't resolve to a model) for:
        - [x] Share data model strata
        - [x] Share data such as `workbench` & `timeline`
- [ ] Generalise `shareKeys` to work with Magda catalogs:
    - [ ] Decide whether `shareKeys` should be registered for a MagdaReference or for it's target
        - [ ] Check some things for a catalog made of MagdaReferences:
            - [x] Are ids shared between Reference and target?
            - [ ] If not check which id is serialised for models & workbench
            - [ ] Is every node in the tree represented with a MagdaReference pointing at an item. And is this guaranteed somehow?
        - [ ] Try implementing for targets
        - [ ] Add some simple unit tests for this method
        - [ ] Test against a real magda
    - [ ] Add tests for Magda catalogs that share keys are registered

----
### UPDATE 11/11/2020:

* I've fixed the tests for shareKeys and spent ages debugging some other tests that I broke
    * That problem is fixed too
* Test JSON catalogs with http://ci.terria.io/share-keys/#https://gist.githubusercontent.com/steve9164/1cd25818891e37ec959fb2ba7e3b3203/raw/0336847cf8543039ead47cdbe4351b1ec19abf80/new-catalog.json&share=s-gf20jkHmg1D5MUdklkeKPa0kfZY
    * That share link was made with `old-catalog.json` from https://gist.github.com/steve9164/1cd25818891e37ec959fb2ba7e3b3203 and then it's applied using `new-catalog.json`, where the CSV has moved in the catalog
* Turns out I forgot about all the other places that getModelById is used from share data
    * Serialised workbench
    * Serialised timeline
* Extra thought needed for MagdaReference. I think I can register `shareKeys` for MagdaReferences
    * It should be sufficient to do it for MagdaReference targets I think. 
    * This problem touches on other problems of the strict ordering of loading parents then members throughout the tree I think
        * For that problem we will need to add an API to magda to fetch a deep catalog item (and probably just enough detail about each of it's ancestors to keep the UI & model layer working)
----
### UPDATE 17/11/2020:
* Working on shareKeys in Magda catalog + tests

**Comment by nf-s** [comment]
Finalising sharekeys effort:

- [x] ~TerriaJS - Revert magda config ID patch + add shareKey  - https://github.com/TerriaJS/terriajs/pull/5042~
- [x] ~TerriaJS - add v7 catalog support through v7initializationUrls - https://github.com/TerriaJS/terriajs/pull/5054~ 
- [ ] TerriaJS - contains previous two PRs + dynamic group `shareKeys` fix - https://github.com/TerriaJS/terriajs/pull/5055
- [x] Terrace - Move v7 catalog handling to terriaJS - https://github.com/TerriaJS/terrace/pull/158
- [ ] Catalog converter sharekeys - https://github.com/TerriaJS/catalog-converter/pull/32
- [x] Document SaaS handling of sharekeys in magda records - see ADRs

**Comment by nf-s** [comment]
Closing!
