### ISSUE TITLE
WMS case sensitive URL parameters being included in GetMap requests

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#4777]
...it tries to call this for GetMap requests
https://gibs.earthdata.nasa.gov/wms/epsg3857/best/wms.cgi?transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&time=2005-05-23&SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0&service=WMS&version=1.1.1&request=GetMap&layers=AIRS_L2_Methane_400hPa_Volume_Mixing_Ratio_Night&bbox=-8140237.7642581295%2C-626172.1357121654%2C-7514065.628545966%2C0&width=256&height=256&srs=EPSG%3A3857

Note the REQUEST=GetCapabilities&VERSION=1.3.0 and version=1.1.1&request=GetMap

Which results in terria trying to download 1MB of getCapabilities for every tile - so like 100s of times

My guess is this has something to do with clearing URI query params

**Comment by rowanwins** [comment]
How to replicate? I added https://gibs.earthdata.nasa.gov/wms/epsg3857/best/wms.cgi via the Add Data panel and selected Web Map Service and it seems happy enough

http://ci.terria.io/next/#share=s-hrI2cMP8WF1s1qiECeH762yxM5U

**Comment by nf-s** [comment]
To replicate you need to add https://gibs.earthdata.nasa.gov/wms/epsg3857/best/wms.cgi?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0

**Comment by nf-s** [comment]
Fixed by https://github.com/TerriaJS/terriajs/pull/6173
