### ISSUE TITLE
Share links don't include point markers or "zoom to" buttons

### ISSUE THREAD

**Issue by MatthewJA** [TerriaJS/terriajs#4784]
Replicating on http://maps.dea.ga.gov.au/:

1. Add a polygon dataset with time series, like DEA Waterbodies. (http://maps.dea.ga.gov.au/#share=s-cjZyN3WgSMrg7nAzcypG5yGlWE1)
2. Select and expand a waterbody. It appears in the data sets:
![data sets](https://user-images.githubusercontent.com/2681312/94224213-2659f280-ff35-11ea-9a29-152a2b152654.png)
A point marker appears on the map:
![image](https://user-images.githubusercontent.com/2681312/94224249-38d42c00-ff35-11ea-95ea-3287963b9c50.png)
3. Get a share link. For this particular example: http://maps.dea.ga.gov.au/#share=s-l5ASlmXD0aaytPP43UmSM4xKzvU
4. The share link does not include the point marker or the zoom to button: 
![image](https://user-images.githubusercontent.com/2681312/94224326-5c977200-ff35-11ea-9102-0c2b72538172.png)
![image](https://user-images.githubusercontent.com/2681312/94224332-602af900-ff35-11ea-847f-0a3094d11cdc.png)
The expanded time series appears OK.

**Comment by rowanwins** [comment]
To anyone in the terria team following on it's related to this code

https://github.com/TerriaJS/terriajs/pull/3645/files#diff-3b2307bc9bc16d201567285491cea1cb

It should be a fair bit simpler to get this working properly in v8
