### ISSUE TITLE
Internationalize tour points

### ISSUE THREAD

**Issue by zoran995** [TerriaJS/terriajs#4789]
I am going to drop tour points into i18next system do we have an option to override `defaultTourPoints`.
Tagging @soyarsauce since he is author of tour option.

**Comment by soyarsauce** [comment]
Hi @zoran995 no built in override yet

**Comment by zoran995** [comment]
the #4790 is then ready for shipping :shipit: 😃

**Comment by zoran995** [comment]
fixed in #4790
