### ISSUE TITLE
Mobx bug: Waterbodies WMS

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4795]
Repro
1. http://ci.terria.io/next/#clean&https://gist.githubusercontent.com/soyarsauce/6d83dfbd930cd825c5fd3be1d8a8baf6/raw/d04b7fcd501472f632b1cbb66e7dd46ab103185e/2020-09-28-dea-maps-v8.json

2. explore map data -> surface water -> Digital Earth Australia Waterbodies -> Digital Earth Australia Waterbodies

3. add to map

4. observe no layer

Conversely, v7 DEAust can load the same WMS
https://maps.dea.ga.gov.au/#share=s-jp5T7rIieSeekWmNcc4vc1ADaIS

**Comment by rowanwins** [comment]
Resolved by #4797
