### ISSUE TITLE
Share links - warning message and user help

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#4796]
Context: 
- as part of the transition of apps from v7 to v8, for some product owners the persistence of share links (i.e. the same links being available after the switch to v8) is very important due to embedding in web pages, guides, social media posts etc
- since the preservation of links is a very difficult problem, the team is working on a non-ID dependant solution by converting on-the-fly the v7 based maps catalogue; when the conversion does not 100% work due to some parts of data visualisations/features not yet transferred to v8, there is a warning message alerting the 1) users of share links; 2) creators of the share links 

**Warning message:** 
Flow and text: 
- User opens a share link (based on a v7 supported Terria app)
- Prompts message: 

"_This share link is based on an older version of TerriaJS - the software powering this web map. While best efforts are made to preserve the link, you might encounter issues with visualising the data. If you're a user of the share link, click OK to make the warning message disappear and continue with accessing the data. If you have created the share link, check the Help menu to see tips on updating the share link. For questions or feedback, click here._"

Warning message details (link to expand to list of issues)

**Help menu** 

- Add in the Help menu, a default item: "Guide on updating share links, including stories" 
Step 1: Identification of share links based on TerriaJS v7.0 (e.g. you may know where they are embedded, or come across them accidentally) 
Step 2: Open v7 based share links in your browser
Step 3: Copy the share link and open in the v8 based map application 
Step 4: Update the share link by clicking the Share/Print button and copy the new link 
Step 5: If distribution of share link is known, update the url in your web page (if embedded) or sending the new link to users

**Comment by soyarsauce** [comment]
@nf-s I will take the help menu and you can focus on warning message tidying up

**Comment by soyarsauce** [comment]
Latest copy

```
## Share & Story Migration

### Guide on updating share links, including stories

If you've received a warning telling you that a share link was based off an older version (v7) of TerriaJS, you'll want to do a few things to recreate them in the latest version of Terria!

#### Creators

1. Identify the share URL which causes a notification of share preservation effort when loading them into Terria. e.g. you may know where they are embedded, or come across them accidentally
2. Open them in the newer (v8) based map application 
3. Check that everything is sharing as you expect, tweak the layers to fit if some are missing or not behaving correctly.
4. Update the share link by clicking the Share/Print button and copy the new link
5. If distribution of share link is known, update the url in your web page (if embedded), or send the new link to users 

#### Consumers
1. Load the share URL
2. If it doesn't quite look right, notify the provider so they can follow the above steps to recreate it in the latest version of Terria
```

```
          {
            "icon": "story",
            "itemName": "storymigration",
            "markdownText": "## Share & Story Migration\n\n### Guide on updating share links, including stories\n\nIf you've received a warning telling you that a share link was based off an older version of TerriaJS, you'll want to do a few things to recreate them in the latest version of Terria!\n\n#### Creators\n\n1. Identify the share URL which causes a notification of share preservation effort when loading them into Terria. e.g. you may know where they are embedded, or come across them accidentally\n2. Open them in the newer (v8) based map application \n3. Check that everything is sharing as you expect, tweak the layers to fit if some are missing or not behaving correctly.\n4. Update the share link by clicking the Share/Print button and copy the new link\n5. If distribution of share link is known, update the url in your web page (if embedded), or send the new link to users \n\n#### Consumers\n1. Load the share URL\n2. If it doesn't quite look right, notify the provider so they can follow the above steps to recreate it in the latest version of Terria",
            "title": "Share & Story migration"
          }
```

**Comment by nf-s** [comment]
<img src="https://user-images.githubusercontent.com/6187649/94540485-ddce6c00-0289-11eb-8f50-b799111da3c6.png " width="500px"/>

**Comment by soyarsauce** [comment]
This can be previewed via https://de-australia.prod.saas.terria.io/#share=s-DEACoastlines

**Comment by soyarsauce** [comment]
Content is in CI for terriajs now

Terriamap default content will be resolveed at https://github.com/TerriaJS/TerriaMap/pull/486
