### ISSUE TITLE
Support a pixel drill chart for WMS coming from THREDDS

### ISSUE THREAD

**Issue by rowanwins** [TerriaJS/terriajs#4802]
It's possible to generate a chart providing a pixel drill through time or another dimension using NetCDF Subset Service.

Currently someone needs to manually configure the featureInfoTemplate parameter but conceivably we can autogenerate the url required for the chart.

![Screen_2020_09_23](https://user-images.githubusercontent.com/6735870/94516846-18c0a780-026a-11eb-911d-b7786d1e3879.jpg)

**Comment by nf-s** [comment]
Duplicate of 

- https://github.com/TerriaJS/terriajs/issues/1424
