### ISSUE TITLE
Auto deploy v7 & v8 docs

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#4811]
- [x] Merge auto deploy `master` docs https://github.com/TerriaJS/terriajs/pull/4810
- [x] Update Netlify configuration to release off `master` instead of `mkdocs-update`
- [x] Take down GH Pages docs.terria.io and replace with a Netlify deployment
- [x] Merge `master` into `next`
- [x] Merge `next` into #4666 (generate docs from Traits/JSDoc on `next` )
- [x] Ensure that #4666 fully covers original v8 docs generation issue https://github.com/TerriaJS/terriajs/issues/4502
- [x] Merge #4666
- [x] Create another Netlify deploy of `next` to docs-v8.terria.io (or similar)
- [x] :tada:

**Comment by soyarsauce** [comment]
Sprint64Top10(11)
