### ISSUE TITLE
Chart download button in featureinfo

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4836]
a download button appears in feature info but it doesn't do anything:

http://ci.terria.io/next/#clean&https://gist.githubusercontent.com/soyarsauce/6d83dfbd930cd825c5fd3be1d8a8baf6/raw/d04b7fcd501472f632b1cbb66e7dd46ab103185e/2020-09-28-dea-maps-v8.json

1. coastal -> digital earth australia coastlines -> digital earth australia coastlines (beta)
2. add to map
3. zoom in enough to the points
4. open feature info
5. see download button
6. try clicking it

<img width="613" alt="image" src="https://user-images.githubusercontent.com/9134432/95143977-35596400-07c3-11eb-9465-3d2ef0e8b12f.png">

**Comment by rowanwins** [comment]
Resolved by #4840
