### ISSUE TITLE
Feature info not captured in story scenes

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4837]
via @robbibt

>Something I've just found when trying to convert a Terria V7 story to a V8 story: V8 no longer captures the feature info popup box. Compare scene 10 ("DEA Coastlines: Time series charts of coastal change") in the original V7 story:

>https://maps.dea.ga.gov.au/#share=s-DEACoastlines&playStory=1

>With scene 10 in the V8 story:

>https://de-australia.prod.saas.terria.io/#share=s-5CAbn9hvyF0LBI4nSeqNXBC7RLi&playStory=1

>The V7 brings up the feature info pop up box as part of the story, but the V8 story does not. I've tried re-capturing the scene in the V8 version and re-creating the share link, but it doesn't help

>e.g.: this box which appears automatically as part of the story in V7

![image (22)](https://user-images.githubusercontent.com/9134432/95146832-a9e3d100-07ca-11eb-8591-e0349d681af1.png)

**Comment by na9da** [comment]
Fixed in `#next` by #4846 
Test - http://ci.terria.io/next/#share=s-dp9RAOsBAPlomnYp9GMxHl9cVfd

**Comment by soyarsauce** [comment]
Thanks !
