### ISSUE TITLE
Missing expanded chart disclaimer in V8

### ISSUE THREAD

**Issue by robbibt** [TerriaJS/terriajs#4841]
### Expected behavior
In V7 of Terria, expanded charts could include a special disclaimer above the chart using the `"chartDisclaimer"` config option:
![image](https://user-images.githubusercontent.com/17680388/95275958-a406f200-0895-11eb-962e-fcee52471266.png)

### Actual behaviour
However, on the new V8 Terria no disclaimer appears:
![image](https://user-images.githubusercontent.com/17680388/95275902-7ae66180-0895-11eb-9136-7798499ef745.png)

### Steps to reproduce the behaviour
For V7, click on any labelled point here, then press "Expand": 
https://maps.dea.ga.gov.au/#share=s-qM4sthFmjR7JuXoBebG8JQN8OT6 

For V8, click on any labelled point here, then press "Expand": 
https://de-australia.prod.saas.terria.io/#share=s-6kcZ5pz3ektavVIKFeMlucW1Y2f

**Comment by rowanwins** [comment]
Resolved by #4842
