### ISSUE TITLE
Missing chart disclaimer for DEA Waterbodies in V8

### ISSUE THREAD

**Issue by CEKrause** [TerriaJS/terriajs#4851]
Same issue as #4841 , but for DEA Waterbodies

V7:
![image](https://user-images.githubusercontent.com/19562367/95539894-4ad8c300-0a3b-11eb-8113-b0a2432336af.png)

V8:
![image](https://user-images.githubusercontent.com/19562367/95539861-35639900-0a3b-11eb-9976-e59ba94c7212.png)

**Comment by vnewey** [comment]
The banner is also missing when you open a dea-maps sharelink in dea-maps.
eg. http://maps.dea.ga.gov.au/#share=s-AEP0gMUBH32CE7rpR1T1kW4Gln

in original:
![image](https://user-images.githubusercontent.com/2038292/95542667-2e8c5480-0a42-11eb-8329-89d819898021.png)

when opening sharelink:
![image](https://user-images.githubusercontent.com/2038292/95542846-a5295200-0a42-11eb-90be-52190e186431.png)

**Comment by rowanwins** [comment]
Resolved by #4842 which is already merged

**Comment by tephenavies** [comment]
The feature is present in version 8 however the disclaimer isn't translated to the new catalogue./ We need to work out how to add the chart disclaimer to those specific items in v8.

**Comment by soyarsauce** [comment]
@soyarsauce to discuss w/ @steve9164

**Comment by soyarsauce** [comment]
Lower prio on my radar

**Comment by na9da** [comment]
After Rowans fix, the chart disclaimer shows correctly, but if you open a share link it is missing.

**Comment by na9da** [comment]
Fixed by #4851.
Test url - http://ci.terria.io/4851-chart-fixes/#share=s-30Z2uc3aiNenWqSzh8Y3Vl7QbiT
