### ISSUE TITLE
Time series plotting in V8 behaves differently (unwanted) to V7 for DEA Waterbodies

### ISSUE THREAD

**Issue by CEKrause** [TerriaJS/terriajs#4852]
##DEAMaps V8 testing issue
### Expected behavior
In V7, when you click on a waterbody and hit expand, it will automatically only plot the 'percentage of surface area (not volume) observed as wet'. This is the preferred behavior.
![image](https://user-images.githubusercontent.com/19562367/95540037-a60ab580-0a3b-11eb-8506-1ef8cb76f8cc.png)

### Actual behaviour
In V8, if you click on a waterbody and hit expand it will automatically plot both timeseries
![image](https://user-images.githubusercontent.com/19562367/95540150-e66a3380-0a3b-11eb-931d-8f48035bb175.png)

In addition, the labels we applied to the timeseries graphs do not seem to be carried over to V8. I.e the legend refers to them as 'wet pixel percentage' and 'wet pixel count (n=x)', not 'percentage of surface area (not volume) observed as wet' and 'wet pixel count'.

### Steps to reproduce the behaviour
V7 sharelink http://maps.dea.ga.gov.au/#share=s-cI4nR0Elhu3IdyDg8gl8jeH45iM
V8 sharelink https://de-australia.prod.saas.terria.io/#share=s-sX8oOxariSJpj7tO2kKACYJ0BbO

**Comment by na9da** [comment]
Fixed in latest terriajs#next branch, eg: http://ci.terria.io/next/#share=s-ye5FKSqqcDGc2jrLYfbM9js3wpl

**Comment by soyarsauce** [comment]
It's fixed.

**Comment by soyarsauce** [comment]
Deployment via https://github.com/TerriaJS/de-australia-map/issues/60
