### ISSUE TITLE
'Ideal zoom' button zooms out waaaay too much for satellite data

### ISSUE THREAD

**Issue by CEKrause** [TerriaJS/terriajs#4853]
### Expected behavior
N/A - this is a new V8 feature

### Actual behaviour
If you load in a satellite scene, then select 'ideal zoom', it zooms to an unhelpful map view
2D basemap:
![image](https://user-images.githubusercontent.com/19562367/95540725-44e3e180-0a3d-11eb-939e-ee6e3abc99c3.png)

3D basemap
![image](https://user-images.githubusercontent.com/19562367/95540758-57f6b180-0a3d-11eb-9ddb-de12d45b5b1d.png)

### Steps to reproduce the behaviour
Load some satellite data, e.g. https://de-australia.prod.saas.terria.io/#share=s-t9qIomI0RVVey7AjNiIH4LMaXr7
Then select 'ideal zoom'

**Comment by CEKrause** [comment]
I just tested this on the Mangroves layer, and it works as expected, so I think it's just an issue for the striped satellite imagery.

**Comment by reginapramesti** [comment]
This should now be fixed by #4884
