### ISSUE TITLE
Clicking 'About data' button freezes the map/page in V8

### ISSUE THREAD

**Issue by CEKrause** [TerriaJS/terriajs#4854]
### Expected behavior
I was checking the metadata in V8 and clicked 'About data' from the legend panel, expecting the metadata to pop up as it usually does in V7.

### Actual behaviour
I clicked 'About data' and the whole page froze. After about 10 seconds the metadata pop up came up, but the page was still frozen. I tried to close the metadata pop up and the whole page crashed
![image](https://user-images.githubusercontent.com/19562367/95541029-faaf3000-0a3d-11eb-8cec-4c0a12f3fdfa.png)

### Steps to reproduce the behaviour
I had loaded up 'Daily Landsat and Sentinel-2 images' into the map. 
https://de-australia.prod.saas.terria.io/#share=s-7k7kxApmRdQVG4lQVJWFuxDQzui
Then clicked on the 'about data' button from here. 
While trying to load up the data again to get the share link for this bug report, the whole site froze up and crashed while trying to load in the satellite data. I refreshed the page and got it working again, but then it crashed again when I reproduced this bug.

**Comment by CEKrause** [comment]
I just did the same thing but with a WOfS layer and the Mangroves layer, and it worked perfectly as expected. It may be a layer specific issue?

**Comment by AnaBelgun** [comment]
@AnaBelgun to check other apps with different data turned on and report results + screen pics

**Comment by rowanwins** [comment]
I suspect this is probably related to https://github.com/TerriaJS/terriajs/issues/4855 and its PR: https://github.com/TerriaJS/terriajs/pull/4857

**Comment by soyarsauce** [comment]
Pending https://github.com/TerriaJS/terriajs/issues/4855

**Comment by reginapramesti** [comment]
This problem is linked to #4855, we previously created a new row for each character in the dimension text, and this item's dimension text in particular was a particularly long string, having to load that was the source of the freezing and crashing the page.

With the dimension text fix, I can confirm that this item doesn't freeze the page anymore
