### ISSUE TITLE
'About Data' metadata looks to be autogenerating incorrectly in V8

### ISSUE THREAD

**Issue by CEKrause** [TerriaJS/terriajs#4855]
### Expected behavior
In the 'About data' section, in V7, under the 'data source details' drop down is some metadata including bounding box
![image](https://user-images.githubusercontent.com/19562367/95542733-58457b80-0a42-11eb-8a1c-30686a5b3092.png)

### Actual behaviour
In V8, this metadata is no longer in an optional drop down, but is automatically included. It also appears to be wrong:
![image](https://user-images.githubusercontent.com/19562367/95542837-9e9ada80-0a42-11eb-85ee-a8c4616a4720.png)
It looks to be loading a date a line at a time, rather than an actual bounding box.

### Steps to reproduce the behaviour
V7 share link: http://maps.dea.ga.gov.au/#share=s-tLIku03p9X5FvkrsHnyyf88kExL
V8 share link: https://de-australia.prod.saas.terria.io/#share=s-yQCv61ML93oJ3eeAwhO5fjJsGYV

I was testing with 'Vegetation' > 'Fractional Cover' > 'Annual fractional cover'

**Comment by rowanwins** [comment]
Fixed by https://github.com/TerriaJS/terriajs/pull/4857 , just needs merging

**Comment by soyarsauce** [comment]
@reginapramesti to confirm if above issue is resolved for this dataset

**Comment by soyarsauce** [comment]
Please close https://github.com/TerriaJS/terriajs/issues/4854 if confirmed

**Comment by reginapramesti** [comment]
Can confirm on my local environment that the above issue is fixed
