### ISSUE TITLE
Dots on map that showed where you clicked are missing in V8

### ISSUE THREAD

**Issue by CEKrause** [TerriaJS/terriajs#4856]
### Expected behavior
When you click on a feature and expend the time series, you get a dot on the map that shows you where you have clicked, that relates to the colour of the line on the time series graph. That way, if you have loaded in multiple time series, you can see which one corresponds with which feature
![image](https://user-images.githubusercontent.com/19562367/95543860-56c98280-0a45-11eb-8cc9-aea786cf5edd.png)

### Actual behaviour
The dots and corresponding colour coordination of the time series graphs is missing from V8
![image](https://user-images.githubusercontent.com/19562367/95543904-7496e780-0a45-11eb-9414-074b561bab2c.png)

### Steps to reproduce the behaviour
Load in 'Surface Water' > 'DEA Waterbodies', then click on a waterbody and hit 'expand'. Then click on a second waterbody and click 'expand'.

**Comment by rowanwins** [comment]
Same as https://github.com/TerriaJS/terriajs/issues/4784

**Comment by na9da** [comment]
Fixed by https://github.com/TerriaJS/terriajs/pull/4876
