### ISSUE TITLE
Improve MagdaCatalogItem error messages

### ISSUE THREAD

**Issue by mwu2018** [TerriaJS/terriajs#4898]
In v8, there is no `MagdaCatalogItem` but in some cases the following error message may pop out:
![image](https://user-images.githubusercontent.com/41275384/96827771-052be980-1482-11eb-8844-337f59fd305c.png)

How to reproduce:
- Let magda post the following message to terria map (The message processing in terriajs is WIP atm.)
```
{
  "catalog": [
    {
      "name": "Credit Licence Dataset - National Map",
      "type": "magda",
      "recordId": "dist-dga-548075a1-c36e-4837-bf26-cc00567b5c23",
      "url": "https://dev.magda.io/"
    }
  ],
  "baseMapName": "Positron (Light)"
}
```
- Add the item in the catalog to the map
- Share the map
- Open the shared link

**Comment by wibily** [comment]
Mike: magdaCatalogItem no longer exists in v8 so the error message should be replaced

**Comment by nf-s** [comment]
https://github.com/TerriaJS/terriajs/blob/e3f6fe9b5985093ad9690082f29caee0f46cb32a/lib/Language/en/translation.json#L1125

**Comment by nf-s** [comment]
Added here https://github.com/TerriaJS/terriajs/pull/5454/commits/9df7cb271d2b017f529f58fec0a9d480345de6df

to this PR https://github.com/TerriaJS/terriajs/pull/5454
