### ISSUE TITLE
Consider switching from Travis CI to a new CI provider

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#4920]
Travis CI seem to have lowered the limits on the number of total open source linux builds they run to about half (see active and backlog linux builds at https://www.traviscistatus.com/#month). This means that many builds will have to wait before being run. This won't work for us as we are heavily reliant on fast test results and often need ci.terria.io deployments to be as immediate as possible.

It should be fairly easy to migrate our CI to another provider. Perhaps the hardest issue will be recreating secrets that we've put into Travis to connect to services if we no longer have the original keys.

We should consider:
* Paid Travis CI?
* GitHub Actions
    + Probably moderately easy to set up
    + Have to dig through logs for tests failures like Travis, or use something like https://github.com/marketplace/actions/junit-report-to-annotations to create "annotations" from failed tests (GitHub Actions annotations don't seem to quite work nicely with this unfortunately and there are rough edges)
    + Or you could use Testspace https://github.com/marketplace/testspace-com to make detailed stats about GH Action test suites available. The free open source plan is unlimited repos, unlimited users,12 months history.
    + Free open source plan is unlimited
* Azure Pipelines 
    + Also allows tracking individual failing tests using Karma Junit reporter
    + Looks like good integration with GitHub PRs (https://azure.microsoft.com/en-us/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/)
    + Free open source plan gives unlimited minutes & 10 concurrent builds (double our current in Travis CI)
    + Not sure about user auth/permissions/etc. but probably requires read/write for the whole org to Azure (which is still Microsoft first party, so maybe not a problem)
* GitLab (neat tracking of individual tests using Karma Junit reporter)
* CircleCI?
    + Required signing up to view test results when I looked at examples of projects using Circle CI. Not the end of the world, but not great
* Others?

GitHub Actions and Azure DevOps Pipelines look like the best out of those.

Discuss!

**Comment by zoran995** [comment]
We are using the azure pipelines on our end so I can provide some feedback about it if you need. 
Our use case is made just to work and using `gulp test-firefox` for tests, build and tests are between 10 and 12 minutes on free account (not sure if opensource plan is much different) - it can be optimised for sure.
We tried to use GitHub actions, but the free plan has a low power capacity so it failed.

**Comment by soyarsauce** [comment]
Haven't given it deep thought but throwing https://buildkite.com/ in the mix, they also have a generous open source plan

**Comment by tephenavies** [comment]
@peterhassall How has button click GH Actions been going for deploys? One of the advantages I see of GitLab and Azure Pipelines is having steps in a CI pipeline that can be optionally run by button clicks. How does GH's button click to run an Action compare to that?

**Comment by soyarsauce** [comment]
I love it (the tightly-integrated-with-your-repo/GH ecosystem part) - although nowhere near as polished nor exactly what gitlab has, and the visualisation aspect of it isn't up there with gitlab (and no idea re: azure pipelines), it is on their Q4 2020 roadmap though: https://github.com/github/roadmap/issues/88

Worked great since making this step manual for test/prod, but again is a little bit manual given you need to look at the results of the latest job when running:
https://github.com/TerriaJS/saas/actions?query=workflow%3Adeploy-test
https://github.com/TerriaJS/saas/actions?query=workflow%3Adeploy-prod

**Comment by soyarsauce** [comment]
(Also keen to hear what Pete thinks too!)

**Comment by tephenavies** [comment]
Migrating from travis-ci.org to travis-ci.com on the same open source plan fixed our immediate problem however with new plan changes https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing it's probably again worth considering switching to either GitHub Actions or Azure Pipelines.

**Comment by tephenavies** [comment]
We have migrated to GitHub Actions
