### ISSUE TITLE
No warning when trying to share with a local file in the catalog

### ISSUE THREAD

**Issue by KeyboardSounds** [TerriaJS/terriajs#4924]
To reproduce:
1. add a csv file from your local computer
2. hit share

In v7, you see this message: ![image](https://user-images.githubusercontent.com/3796838/97411505-52550300-193b-11eb-98a6-c228b1757552.png)

In v8, it's missing.

**Comment by nf-s** [comment]
Fixed by https://github.com/TerriaJS/terriajs/pull/6383
