### ISSUE TITLE
WMS select only one feature & missing highlight selected objects

### ISSUE THREAD

**Issue by zoran995** [TerriaJS/terriajs#4925]
- When a WMS layer is added on v7 and user click on the object it will select all available objects, on v8 currently, it will select only one object. 
- The v7 had an option to highlight the selected object, there is no such feature in v8. AFAIK it was done getting the geometry from feature response, but the WMS is not required to return Geometry in it (on MapServer it can be disabled, on GeoServer it is possible to use new geojson template and hide geometry). My thought on this is that we could utilise additional style request and load an overlay layer with a highlighted object (it should be set through catalog config).

[next test](http://ci.terria.io/next/#share=s-dKwaKSi84gryYm82uHd0zvgHy1I)
[nationalmap test](https://nationalmap.gov.au/#share=s-ebMPvcqmr6GOBP92iIhFFfxslae)

**Comment by nf-s** [comment]
Merged into https://github.com/TerriaJS/terriajs/issues/4983

**Comment by zoran995** [comment]
@nf-s The first point of this issue is not resolved?

**Comment by nf-s** [comment]
Hi @zoran995  
Sorry, yes you are right. I just wanted to get everything into a single ticket to make it easier to manage missing PickedFeatures/Feature highlighting issues.   
I have copied your first comment over to the other issue.

**Comment by nf-s** [comment]
Screenshot example

![image](https://user-images.githubusercontent.com/6187649/108317752-d5fc6d80-7212-11eb-80e7-653f23a6edd1.png)

**Comment by zoran995** [comment]
This is caused by missing `feature_count` in the GetFeatureInfo request. It was already reported and fixed in older versions

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/5612
