### ISSUE TITLE
lga_code not recognised as region column

### ISSUE THREAD

**Issue by KeyboardSounds** [TerriaJS/terriajs#4926]
In v7 NationalMap, a .csv with a column named `lga_code` will be region-mapped correctly, but in v8, it fails. The [csv-geo-au spec](https://github.com/TerriaJS/nationalmap/wiki/csv-geo-au) implies that `lga_code` should work.

**Comment by reginapramesti** [comment]
How does it fail? I'm trying out some of the test csv files (specifically `wwwroot/test/lga_code_2015.csv`), and they "behave" somewhat differently but seems to be fine wrt region mapping. Here's what I see 

on saas
![image](https://user-images.githubusercontent.com/16102484/98065221-41ab0c80-1ea8-11eb-8656-2db7a87db558.png)

on v7 natmap
![image](https://user-images.githubusercontent.com/16102484/98065246-52f41900-1ea8-11eb-914f-12622687d840.png)

Maybe you could share the csv you used so I can reproduce

**Comment by reginapramesti** [comment]
One major difference to note, is when I add `wwwroot/test/RDA_LGA_2015_16.csv`, an error message pops up in v7 for regions with unknown LGA, but doesn't happen in v8

**Comment by nf-s** [comment]
Working fine now
