### ISSUE TITLE
Add a plain light and a plain dark basemap

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#493]
It can be very hard to see the data displayed for some layers due to the detail in the underlying basemaps. Currently, I use the Bing Maps Roads basemap when it appears that the layer data is dark, and the NASA Black Marble when it appears that the data is light.

If we could switch to a very plain simple basemap then it would be much easier to see the data from the enabled layers. Maybe with some magic we could even have custom colour and light sliders or a colour picker or something like that, and just make the entire globe that colour?

I think the maximum amount of detail to show to orient yourself would be country borders, or maybe down to state borders, but not more than that.

**Comment by hilarycinis** [comment]
Thanks Mats, there is a plain base map, I'll leave you to find it in the new ui http://nationalmap.research.nicta.com.au/

Kevin has found some cesium functionality that handles saturation also, we're yet to evaluate its implementation. 

Thanks for your comment as it's an item we have had a bit of discussion over

**Comment by meh9** [comment]
Hmmm, I'm not finding it, could you give me a bit more of a hint please? None of the maps under the Maps drop-down are as simple as would like.

Just to give an example of how simple a map I'm talking about, go to the url below, click Basemap, select Dark Grey Canvas or Light Grey Canvas (and even these have a bit more detail than I'd like):

http://www.arcgis.com/home/webmap/viewer.html

**Comment by Meeena** [comment]
As an aside, attached is a mockup of low saturation version of the new GA Topographic Map for NM

![low_saturation_alt](https://cloud.githubusercontent.com/assets/8098239/5952775/7ea59374-a7d2-11e4-814c-d5e1812df8f3.jpg)

**Comment by Meeena** [comment]
and here's low saturation Melbourne...
![new_topo_low_saturation_mel](https://cloud.githubusercontent.com/assets/8098239/5952783/a2c87d02-a7d2-11e4-9c0b-cd3c8a70ece5.jpg)

**Comment by kring** [comment]
This is a duplicate (or really close to a duplicate) of #322.

**Comment by hilarycinis** [comment]
@kring do you want us to migrate the conversation there?

**Comment by hilarycinis** [comment]
Notes from Meena: Attached is a document that shows a comparison of the new GA topographic map against what we have now, and the default basemap for competitors like Bing and Google. 
The new GA map is much better than all the other options, but it would be good to clarify/suggest some refinements to the map – especially if this is to be the default basemap:
Opacity of map – Not sure what the default is supposed to be as this is different in Bing and in Google, but I think we should go for close to 100% opacity. The opacity also affects the legibility of the labelling.
Low Saturation option - I know Kevin has found some Cesium functionality that may adjust this. The last page of the document shows what low saturation of the new topo map might look like. I think it’s very good :-)
Zoom level missing? - at the moment it is possible to zoom in close ( in Bing) and lose the Topo map
Repeated text – some labels are repeating at certain zoom levels ( check out Altona Bay near Melbourne )
Pixelated text – in Google Earth, but not Bing. Would be good to see a deployment of this map in NM to see what problems we might see. 
Australian map bounding box. As already articulated, this looks strange. Would be good to see if we can do a more sophisticated cropping of the map, or make use of the box by making it look like an official GA map placed on top of the NM globe. 

Supporting pdf here: http://wiki.inside.nicta.com.au/download/attachments/92509622/NM_TopoMaps.pdf?version=1&modificationDate=1422584759332&api=v2

**Comment by kring** [comment]
> @kring do you want us to migrate the conversation there?

No, let's close that one and keep this one open.

**Comment by kring** [comment]
What's the URL of the new topographic map?  It should only take a second to drop it into National Map.

**Comment by Meeena** [comment]
Heres the most relevant comment from #322, so we don't have to flick back and forth:

KGGrochow commented:
"These appear to be CC BY 3.0 using Open Street Map datasets, so it appears we can add these:
toner - 6 flavours
terrain - 3 flavors
watercolor
The question is then if we use their servers or not. Based on this page they appear to be fine with it. We just need to decide if they are fast enough." 

My preference is Toner Lite:
http://maps.stamen.com/toner-lite/

**Comment by Meeena** [comment]
Here's the URL for the New Topographic map
http://www.ga.gov.au/gis/rest/services/topography/National_Map_Basemap_WM/MapServer

**Comment by kring** [comment]
Ok, here's an instance of National Map that has it as a basemap choice:
http://nationalmap.research.nicta.com.au/demo/

Hit the maps button and then choose the last one, labeled "New Australian Topography".

**Comment by hilarycinis** [comment]
I think the general view is ok, works really great with heavy layers like land cover.

Not sure if this is just a result of a quick put-together, between 300 and 500 km zoom the rendering pops from complete to incomplete (see attached)

**Comment by kring** [comment]
The attachment didn't come through, but I know what you mean.  Unfortunately that's just the way this map works.  Maps with drastic differences between different levels of detail work poorly in 3D because different levels of detail are visible simultaneously (unlike in 2D where the LOD is uniform).

**Comment by hilarycinis** [comment]
sorry, about to ask a dumb question... we can remove it as a 3D option?

**Comment by kring** [comment]
Sure, but then the majority (hopefully) of users wouldn't get it.

**Comment by kring** [comment]
I would love to do blending between different levels of detail, which would make this look a whole lot nicer.  That's a fairly significant Cesium feature, though.

**Comment by hilarycinis** [comment]
maybe @philipgrimmett and I can look a bit more at how the saturation settings could be added into the "Maps" selector to also handle that, with your help understanding how portable that is. No rush, we can discuss the effort with Bill. 

I think we'd all agree if we do a simple topo map, it will need to work really nicely and not to have anything if its a bit bumpy :)

**Comment by Meeena** [comment]
Below are supporting comments from me RE the new GA Topo Map:

Attached is a document that shows a comparison of the new GA topographic map against what we have now, and the default basemap for sites like Bing and Google. 
The new GA map is much better for our purposes, but it would be good to clarify/suggest some refinements to the map – especially if this is to be the default basemap:

1.Opacity of map – Not sure what the default is supposed to be as this is different in Bing and in Google, but I think we should go for close to 100% opacity. The opacity also affects the legibility of the labelling.
2.Low Saturation option - I know Kevin has found some Cesium functionality that may adjust this. The last page of the document shows what low saturation of the new topo map might look like. I think it’s very good :-)
3.Zoom level missing? - at the moment it is possible to zoom in close ( in Bing) and lose the Topo map
Repeated text – some labels are repeating at certain zoom levels ( check out Altona Bay near Melbourne )
4.Pixelated text – in Google Earth, but not Bing. Would be good to see a deployment of this map in NM to see what problems we might see. 
5.Australian map bounding box. As already articulated, this looks strange. Would be good to see if we can do a more sophisticated cropping of the map, or make use of the box by making it look like an official GA map placed on top of the NM globe.

Supporting pdf here: http://wiki.inside.nicta.com.au/download/attachments/92509622/NM_TopoMaps.pdf?version=1&modificationDate=1422584759332&api=v2

**Comment by Meeena** [comment]
have just been playing around with the Cesium Saturation options. Would be good to see 2 extra versions of the New Topo Map, to see how data looks over the top of it:
1. Black & White version ( Saturation= 0)
2. Low Colour version ( Saturation= 0.2)
![screen shot 2015-02-02 at 11 19 46 am](https://cloud.githubusercontent.com/assets/8098239/5994593/6435f570-aace-11e4-9267-5a82737af708.png)

![screen shot 2015-02-02 at 11 21 06 am](https://cloud.githubusercontent.com/assets/8098239/5994594/6a5ff9dc-aace-11e4-9be8-94414e77d83e.png)

**Comment by hilarycinis** [comment]
This was neither validated or dismissed as a requirement in usability testing. Discoverability of the maps is more important and from there folks can change layers. I think it's useful to offer a simple map as part of that collection.

**Comment by meh9** [comment]
I've been looking at layers again, and again saw the need for a really plain basemap. I found that the BoM Meteye has a super simple basemap that I'm going to use as an example.

So the problem I'm looking to solve is that it's hard to see the data when you first turn on a layer and you don't know what to look for, the basemap lines and features serves as camouflage for the data I'm interested in seeing.

Examples below, first with GA basemap, then Bing, then BoM Meteye, followed by a full Australia view of the BoM map:

![screen shot 2015-04-16 at 15 16 18](https://cloud.githubusercontent.com/assets/5283003/7174490/8cba095c-e44c-11e4-9ab7-8450512e6a56.png)

![screen shot 2015-04-16 at 15 16 42](https://cloud.githubusercontent.com/assets/5283003/7174492/93fe7a68-e44c-11e4-9f30-41f3d0a50d04.png)

![screen shot 2015-04-16 at 15 17 06](https://cloud.githubusercontent.com/assets/5283003/7174498/9fb5a3ae-e44c-11e4-9c99-ca68e51d6643.png)

![screen shot 2015-04-16 at 15 25 09](https://cloud.githubusercontent.com/assets/5283003/7174510/d30edeb4-e44c-11e4-92ff-aadb241eb0f4.png)

**Comment by stevage** [comment]
I've just two days of demoing NM and agree that we need to do something
about the basemaps. It felt a bit embarrassing that the first thing I
always had to do when refreshing the browser was switch to a more usable
basemap. For certain kinds of data, an almost featureless basemap is pretty
much ideal, as then any tiny detail is still visible.

As a reference, CartoDB has a reasonable selection of very plain basemaps,
for exactly this reason:

Positron:

Positron Lite:

Midnite Commander (great for light coloured data sources...)

Toner Lite

The last one is from Stamen Design, who have lots of pretty amazing and
creative basemaps: http://stamen.com/

Steve
​
​
​

**Comment by meh9** [comment]
I added the plain OpenStreetMaps as prototype basemap to AREMI, you can try them out on the dev site, http://aremi.nicta.com.au

Here's the Light basemap in the same area with the same enabled layers as I had above, and it's great:
![screen shot 2015-05-14 at 16 57 48](https://cloud.githubusercontent.com/assets/5283003/7627500/5fc89af6-fa5b-11e4-9320-1eede4cd44be.png)

**Comment by stevage** [comment]
Hmm, what exactly is that light one? I understand that it's derived from OpenStreetMap data, but the tiles themselves seem to come from [AURIN](https://maps.aurin.org.au/cgi-bin/tilecache.cgi?tiled=true&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&service=WMS&version=1.1.1&request=GetMap&layers=austatesgrey&srs=EPSG%3A3857&bbox=16280475.528516259%2C-3757032.814272985%2C17532819.79994059%2C-2504688.542848654&width=256&height=256)? It has a few weaknesses, including drawing the international boundary 50km(?) offshore, which is a bit distracting.

It looks like the CartoDB Positron maps are really free to use:

> Free to use
> Now that we’ve taken care of that, start animating these basemaps with stunning stories.

So I think I'd suggest those.

```
var layer = L.tileLayer('http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png', {
  attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, &copy; <a href="http://cartodb.com/attributions">CartoDB</a>'
});

var layer = L.tileLayer('http://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png',{
  attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, &copy; <a href="http://cartodb.com/attributions">CartoDB</a>'
});

```

(or `nolabels` instead of `all`)

etc.

**Comment by kgrochow** [comment]
Is this resolved with the 2 new basemaps?

**Comment by meh9** [comment]
They are certainly a huge improvement.

However, I'd still prefer less detail when you zoom in to places, but if everyone else are happy then AREMI can do something quick and dirty ourselves.

**Comment by stevage** [comment]
You might prefer the no-label version: http://{s}.basemaps.cartocdn.com/light_nolabels/{z}/{x}/{y}.png

<img width="582" alt="screenshot 2015-07-30 15 56 16" src="https://cloud.githubusercontent.com/assets/678344/8976659/9d648d84-36d3-11e5-8721-80e2d1d149c5.png">

**Comment by meh9** [comment]
The AREMI project has come to terms with the CartoDB Positron maps, so I think this can now be closed if everybody else are also happy.

I understand that Geoscience Australia may be working on another alternative, and will be interested to see what they come up with.

**Comment by stevage** [comment]
:+1:
