### ISSUE TITLE
Merge catalog groups with the same name

### ISSUE THREAD

**Issue by KeyboardSounds** [TerriaJS/terriajs#4938]
As a catalog organiser,
I want all references in a catalog to a catalog groups with the same name to be merged
So that I can define a single catalog group's members across multiple catalog.json files.

This works in v7, as seen in the current version of NEII Viewer, but doesn't work in v8.

**Comment by nf-s** [comment]
I think this may be due to the `mergeRecursive` issue in the catalog converter: https://github.com/TerriaJS/catalog-converter/pull/11#discussion_r505306297 - @steve9164 knows more about than me


I'm not sure I agree that catalog groups with the same name should be merged client-side

**Comment by KeyboardSounds** [comment]
Nah, I don't think it's the catalog converter. The NEII map catalog is made of a bunch of separate .json files that look like this:

catalog1.json
- Top level group ABCD
  - member y

catalog2.json
- Top level group ABCD
  - member x

The top level group is the same, and the intention is for "member x" and "member y" to be in the same group. This is a pretty contrived example, but specifying catalogs like this makes a lot of sense in cases like NEII's.

Since we supported this in v7, we should probably support something equivalent in v8. Maybe we allow specifying a group ID and merge groups with the same ID?

**Comment by tephenavies** [comment]
I would say many use cases that this merging supported are supported by our catalog editor, but that isn't available to open source users (yet?/ever?. We're unsure as of yet)
Without equivalent functionality available to and convenient for everyone to replace this feature I think we should re-implement it in version 8.

**Comment by AnaBelgun** [comment]
done, merged
