### ISSUE TITLE
Cesium OSM Buildings | TerriaMap-next

### ISSUE THREAD

**Issue by arytonsenna** [TerriaJS/terriajs#4949]
I am trying to load osm 3d Buildings using the following catalog item :

`{ "name": "Cesium OSM Buildings", "type": "3d-tiles", "isEnabled":"true", "isMappable":"true", "isShown":"true", "cacheDuration":"1d", "ionAssetId": 96188, "style": { "color": "Boolean(${feature['cesium#color']}) ? color(${feature['cesium#color']}) : rgb(255,255,255)" }, "colorBlendMode": "HIGHLIGHT" }`

But unfortunately when i open TerriaJsMap-next at localhost:3001 using gulp watch
i cannot load the osm buildings layer
and it says that -> "This dataset may currently be experiencing issues"
<img width="368" alt="cesium-osm-bug" src="https://user-images.githubusercontent.com/28485076/97778791-95171500-1b9f-11eb-90d0-b7c5f21151f9.PNG">

same is true for "cesium-terrain" layer, but i know for a fact that the layers are functional on TerriaJSMap on the previous version. What might be the issue ?

**Comment by hardreddata** [comment]
It looks like you got the code example off the gitter, from @kring so it should be good.

It works here on http://ci.terria.io/next/ where I have added my `"ionAccessToken"` to the catalogue item 

![image](https://user-images.githubusercontent.com/42530666/97914870-a9782f00-1da4-11eb-8993-626e3c26b2bb.png)

Maybe you encountered a legitimate outage?

Is your screenshot from a phone?

**Comment by KeyboardSounds** [comment]
@RussellGrew is right, it's likely to be an authentication issue because of a lack of an Ion access token. If adding your access token doesn't work, could you please post the output of the web console with any error messages in it?

**Comment by tephenavies** [comment]
I think this is error is due to the use of `terriajs@8.0.0-alpha.59` which was a bad npm release. We've reverted the problematic changes and published a new release `8.0.0-alpha.60` that should fix any errors introduced in alpha 59. See related conversation about this error on Google Groups: https://groups.google.com/u/1/g/terriajs/c/jAly3kDA4GU.

**Comment by arytonsenna** [comment]
> I think this is error is due to the use of `terriajs@8.0.0-alpha.59` which was a bad npm release. We've reverted the problematic changes and published a new release `8.0.0-alpha.60` that should fix any errors introduced in alpha 59. See related conversation about this error on Google Groups: https://groups.google.com/u/1/g/terriajs/c/jAly3kDA4GU.

@steve9164 Thank you so much for your prompt reply ! terriajs version 8.0.0-alpha.60 indeed fixes the issue and now we are able to load OSM Buildings in terriajs again !
