### ISSUE TITLE
Support splitting 3d tiles

### ISSUE THREAD

**Issue by KeyboardSounds** [TerriaJS/terriajs#4965]
As an end user of Terria,
I want to be able to use the splitter for 3D tiles, not just 2D imagery,
So that I can compare 2 models side by side.

---

The "proper" way to do this is to use a similar approach to the one taken with terrain rather than use Cesium's higher level clipping plane API (for code cleanliness and performance reasons). Basically, you need to add an extra parameter to the 3D tiles fragment shaders, and extend Cesium's API to allow setting that parameter from Terria. I believe the source for the 3dtiles shaders mostly live in the js source files, like https://github.com/CesiumGS/cesium/blob/0482770ae8e7e90f8bdfbb56fa194981f800d156/Source/Scene/Cesium3DTileBatchTable.js

@kring did something similar for terrain already, see [this commit](https://github.com/CesiumGS/cesium/commit/2916a07f23e4eed36be6972378a8de0e94ac7e9c)

Ideally, these changes should be made in upstream CesiumGS and not just our fork because it could be useful to other Cesium users too, and not just TerriaJS folks.

**Comment by KeyboardSounds** [comment]
@rober72hv no pressure, but to make this feature as useful as possible it would be super helpful if you could share some of your use cases, eg.
- What sort of models do you want to use this with?
- What benefit does being able to split them have? Are you trying to compare different versions of the same thing, or changes over time?

**Comment by nf-s** [comment]
Is there also interest in splitting terrain?  
I was asked about that in a project earlier this year

**Comment by rober72hv** [comment]
Hi Emma. @KeyboardSounds 
My main use case is comparing 3D tiles in the same location for different dates. Currently we create these models from images captured by drones.
We put in each 3Dtile an extra property called "ImplementationDate" that indicates its date. The idea for the future, to be able to carry out animations in time, at least to hide and show the 3DTile.
How do we do it now? (as a first approximation)
We load in Terria two models from the same location but with different dates and we add the opacity option to be able to change it in the workbench. (Basically we add a Trait "opacity" to 3DTile and change the style based on it)
We also hide/show the oldest model and it helps us to get an idea of ​​the changes. It helps us a lot as a visual inspection to see closed roads, rock falls etc. If I could do the split it would be very helpful.
I tried to do it with clipping planes but it was a bit cumbersome to keep the plane always perpendicular based on camera and the  splitter position. At the moment I am in another development that covers all my time. I notice that i'm have basic knowledge related to work with cameras and frustums (I need to study much more to accomplish this develop), to calculate the exactly plane direction that fits with the splitter position) 

In this [video ](https://youtu.be/NcI8l4luh7Y) you can see the prototype with the alpha change for a 3DTile. Is a very basic functionality but the idea is to show the need of comparison tool for 3DTiles.

![comp3dtljpg](https://user-images.githubusercontent.com/73897762/98120489-c38d3c80-1e8c-11eb-866d-f4282d2b295b.jpg)

[Link to video ](https://youtu.be/NcI8l4luh7Y) 

Thank you so much for everything

Cheers
Rob

**Comment by moisesrbd** [comment]
Hello Rob
Interesting idea to add opacity to a 3Dtile. It looks useful.
When using opacity in a 3Dtile it is necessary to change the Style, as I understand it.
You say you added a Trait to the 3DTile,  (assume to 3DTileCatalogItem) called "Opacity" but there is a Trait for the Style. 
Could you share the code to get both Traits together?
Thank you.
Moses

**Comment by rober72hv** [comment]
> Hello Rob
> Interesting idea to add opacity to a 3Dtile. It looks useful.
> When using opacity in a 3Dtile it is necessary to change the Style, as I understand it.
> You say you added a Trait to the 3DTile, (assume to 3DTileCatalogItem) called "Opacity" but there is a Trait for the Style.
> Could you share the code to get both Traits together?
> Thank you.
> Moses

Yes, I added a Trait "opacity" to the Cesium3DTilesCatalogItemTraits, then I modified the code of the Cesium3dTilesMixin.
I modified the cesiumTileStyle observable in the following way, to assign the color property its opacity. The code of course can be improved, it is just a test of functionality.

    computed get cesiumTileStyle() {  
    if (
        !isDefined(this.style) &&
        (!isDefined(this.opacity) || this.opacity === 1) &&
        !isDefined(this.showExpressionFromFilters)
      ) {
        return;
      }
      let style = clone(toJS(this.style) || {});
      let opacity = clone(toJS(this.opacity) || 1.0);     
      if (opacity <= 1) {
        const _color = `color('${style.color || "#FFFFFF"}', ${this.opacity})`;
        style = Object.assign(style, { color: _color });
      }
      if (isDefined(this.showExpressionFromFilters)) {
        style.show = toJS(this.showExpressionFromFilters);
      }
      return new Cesium3DTileStyle(style);
    }

**Comment by meh9** [comment]
> Yes, I added a Trait "opacity" to the Cesium3DTilesCatalogItemTraits, then I modified the code of the Cesium3dTilesMixin.
> I modified the cesiumTileStyle observable in the following way, to assign the color property its opacity. The code of course can be improved, it is just a test of functionality.

@rober72hv this is great - we have been discussing adding transparency to all datasets, and as late as yesterday discussed adding it for 3dtiles - do consider sending a PR our way! :)

**Comment by moisesrbd** [comment]
> > Yes, I added a Trait "opacity" to the Cesium3DTilesCatalogItemTraits, then I modified the code of the Cesium3dTilesMixin.
> > I modified the cesiumTileStyle observable in the following way, to assign the color property its opacity. The code of course can be improved, it is just a test of functionality.
> 
> @rober72hv this is great - we have been discussing adding transparency to all datasets, and as late as yesterday discussed adding it for 3dtiles - do consider sending a PR our way! :)

@meh9 and @rober72hv  I recently added a PR with this functionality, based on this thread.
You can see it in  [PR 4974](https://github.com/TerriaJS/terriajs/pull/4974)
Regards.
Moises
