### ISSUE TITLE
Request a better looking legend image when making GetLegendGraphic request

### ISSUE THREAD

**Issue by na9da** [TerriaJS/terriajs#4966]
In v7 [we customize](https://github.com/TerriaJS/terriajs/blob/master/lib/Models/WebMapServiceCatalogItem.js#L2178) the `GetLegendGraphic` url further to get a better looking legend image. Implement the same for `v8`

eg catalog item: https://map.drought.gov.au/#share=s-eyeP1c2InuzhXYoMpwyD64hFLFk

**Comment by nf-s** [comment]
Good timing!

I just merged https://github.com/TerriaJS/terriajs/pull/4923 which does a little of this

And I'm currently working on #4922 - which includes dpi settings (and general cleaning and tsification of `Legend.jsx`)

**Comment by na9da** [comment]
Looks fixed by - https://github.com/TerriaJS/terriajs/pull/4923
