### ISSUE TITLE
Cesium analytics SDK widget into terria js

### ISSUE THREAD

**Issue by sammyaxe** [TerriaJS/terriajs#4967]
Hello there, 

I would want to utilise Cesium Analytics SDK, more specifically include their measurement widget.
https://cesium.com/docs/analytics-sdk-reference/Measure.html

Is there is any way I can achieve this? 

Thanks

**Comment by rober72hv** [comment]
> Hello there,
> 
> I would want to utilise Cesium Analytics SDK, more specifically include their measurement widget.
> https://cesium.com/docs/analytics-sdk-reference/Measure.html
> 
> Is there is any way I can achieve this?
> 
> Thanks

It would be great to have this option. But as I understand the Analytics SDK is commercially licensed, it is not part of the open version of Cesium, so it is not part of terria-cesium.
But it would be very interesting to see if it can be used in the Terria project.
Maybe someone else can contribute ideas.

Best
Rob

**Comment by sammyaxe** [comment]
@rober72hv thanks for your answer, In my case I do have the license. 

I want to clone git clone https://github.com/TerriaJS/terria-cesium.git but I'm being asked for password. I'm a bit confused if https://github.com/TerriaJS/cesium.git is the same package? 

I want to make some edits to terria-cesium and see if I can get SDK implemented, but confused on how to clone that folder.
https://docs.terria.io/guide/contributing/development-environment/ says I should be able to clone terria-cesium?

Any ideas here?

**Comment by rober72hv** [comment]
> @rober72hv thanks for your answer, In my case I do have the license.
> 
> I want to clone git clone https://github.com/TerriaJS/terria-cesium.git but I'm being asked for password. I'm a bit confused if https://github.com/TerriaJS/cesium.git is the same package?
> 
> I want to make some edits to terria-cesium and see if I can get SDK implemented, but confused on how to clone that folder.
> https://docs.terria.io/guide/contributing/development-environment/ says I should be able to clone terria-cesium?
> 
> Any ideas here?

First you must  use the branch that corresponds to the version of TerriaJS,
For example the "next" branch of TerriaJS uses the version "terriajs-cesium": "1.73.1",
you can check the corresponding package.json, 
[ package.json of branch "next" of TerriaJS ](https://github.com/TerriaJS/terriajs/blob/next/package.json)   
Then you must clone the corresponding tag version of terria-cesium from https://github.com/TerriaJS/cesium.git

Hope it helps you.

How you get the licence of Analytics SDK? because Cesium is not selling this product right now.

Regards

**Comment by sammyaxe** [comment]
@rober72hv we are buying ION Engine and Analytics SDK came with it.

**Comment by sammyaxe** [comment]
@rober72hv do you have any examples of how I could implement Geocoder cesium widget that is part of the open version of Cesium?

**Comment by rober72hv** [comment]
> @rober72hv do you have any examples of how I could implement Geocoder cesium widget that is part of the open version of Cesium?

In this [link](https://sandcastle.cesium.com/?src=Custom%20Geocoder.html) you can see an example to use custom geocoder with cesium.
I don't know if this works for you, but  i'm don't have experience in this point.

Best
Rob

**Comment by sammyaxe** [comment]
Whoever is looking for answer to this, it can be done by editing terriajs package `/lib/models/Cesium.js` you can tap into Cesium instance.
