### ISSUE TITLE
Extract the Abstract from the GetCapabilities

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#497]
WMS/WFS Services and Layers can both have an Abstract. It would be great if there was an option to enable showing the Abstract on the National Map Layer Info screen, firstly from the Layer, and if not available then from the Service.

An example of a Service with an Abstract both in the Service and the Layers is this (yes I know the Layer Abstracts are not particularly useful):

http://www.ga.gov.au/gis/services/hazards/NEXIS_National_Exposure_Information_System_Population_Density_Exposure/MapServer/WMSServer?request=GetCapabilities&service=WMS

**Comment by kring** [comment]
@meh9 we already grab the layer abstract for datasets discovered by querying `GetCapabilities`:
https://github.com/NICTA/nationalmap/blob/master/src/Models/WebMapServiceCatalogGroup.js#L285

I like the idea of pulling the service abstract, too, although right now that would make us show the default Geoserver description for a bunch of datasets.

**Comment by kring** [comment]
For example, all the Broadband layers would say:

> A compliant implementation of WMS plus most of the SLD extension (dynamic styling). Can also generate PDF, SVG, KML, GeoRSS

Which is probably worse than useless.

**Comment by meh9** [comment]
From what I can tell the only place we show WMS `Abstract` and ArcGIS `serviceDescription` data is in the `Data Details` and `Service Details` sections on the Info page.

I think we should extract WMS `Abstract` and ArcGIS `serviceDescription` data by default, and put it under its own heading further up the page. At the moment when it's further down it's mixed in with other things like BoundingBoxes and CRS details - a normal user would be scared off by that stuff and will probably miss the useful information.

If we do this by default and then have an opt-out available for not showing it in the init file then we can control those with bad or not useful info.

**Comment by meh9** [comment]
By getting abstracts/serviceDescription automatically it saves us a lot of time for AREMI, as it is a requirement for us to have a good info page - it's one of the most requested features that each layer is documented properly.

We are pushing this down as hard as we can to the data custodian so that they can document their own data, but at the moment they have to ping us when they change the info so we can update ours.

**Comment by stevage** [comment]
Yeah I think ran into this recently, too - I think it's just an oversight that we don't pick it up.
