### ISSUE TITLE
Revert breaking magda root group ID

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4978]
Coming out of https://github.com/TerriaJS/qld-digital-twin/issues/237, some old share links are broken for certain magda based maps - this is due to the change brought in by https://github.com/TerriaJS/terriajs/pull/4887.

One idea to improve this compatibility before we get our [longer term share key compatibility layer](https://github.com/terriajs/terriajs/issues/4774), is below: 

>@soyarsauce said:

>    there's a really quick easy client-side fix for this, all the share key/alias id work withstanding. basically checking anything that uses `map-config` in its `knownContainerUniqueIds` to also inject `/` to it

**Comment by AnaBelgun** [comment]
to revert when Share keys PR is merged

**Comment by nf-s** [comment]
We have decided to leave magda root group ID as `/` - See adr 0005 for more info https://github.com/TerriaJS/terriajs/blob/next/architecture/0005-root-group-ids-and-shareKeys.md
