### ISSUE TITLE
Zoom doesn't work if you wait too long after stop moving pointer

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#498]
On OSX, if I move the pointer over the 3D map then stop moving it and wait a few seconds for the rendering loop to timeout and suspend, then use the touchpad to zoom in/out (which keeps the mouse pointer absolutely still), nothing happens until I move the pointer sideways. (I guess this may also happen when using an attached mouse and trying to zoom using the scroll wheel?)

If however immediately after I stop moving the pointer I then zoom then the zoom works straight away, and then even if you wait some seconds there is no further problem with zooming.

Steps:
1. move pointer over map then stop
2. wait 5 seconds without touching the pointer
3. zoom in/out
4. observe nothing happens
5. move pointer and observe the map instantly "pop" to the new zoom level

**Comment by kring** [comment]
I can't reproduce this with the scroll wheel, but I can believe it happens with touchpad zoom, assuming touchpad zoom doesn't generate click or mousemove events.  Should be an easy fix.  Thanks!
