### ISSUE TITLE
Support  Clipping Planes in 3DTiles

### ISSUE THREAD

**Issue by moisesrbd** [TerriaJS/terriajs#4981]
As an end user of Terria,
I want to be able to to use the Clipping Planes in 3DTiles from its catalog. This allows cuts sections of the 3DTiles to display only the important parts.
It is very useful when you have already generated a  big 3DTile and want to use a section to share a scene without having to process the 3Dtiles again.
Also in the future there could be a tool that allows to graphically edit the planes and make the cuts before sharing the scene.
The configuration could be:
```
{
                    "name": "Brisbane 3D city model (aero3Dpro)",
                    "type": "3d-tiles",
                    "url": "https://sample.aero3dpro.com.au/BrisbaneCBD/Scene/recon_h_3DTiles.json",
                    "options": {
                        "maximumScreenSpaceError": 1,
                        "maximumNumberOfLoadedTiles": 1000
                        "clippingPlanes" : [ 
                                            {"normal": [0.1,0,0.2], "distance": 10},
                                            {"normal": [0.4,0,0.4], "distance": 5}
                                           ]                        
                    }
                }

```

I propose to create a Trait "ClippingPlanesTrait" since this can be used by 3DTiles, GLTF Models and the Globe. Mixing with Cesium3DTilesTraits

Then modify the Cesium3DTilesMixins to load these Clipping Planes to 3DTile and create an Observer to handle the changes that are made in the UI.

**Comment by rober72hv** [comment]
Very good idea. It is useful for example to make cuts to models and share only those cuts.
It would be ideal to be able to associate from the workbench a tools for the edition of  planes, just like the Cesium ION SDK does.
See this video for more clarity. [Link to video](https://cesium.com/videos/clipping-planes-editor.mp4)
Do you have something in advance?
Can you create a PR?
Best

**Comment by moisesrbd** [comment]
We are evaluating developing it.
But we prefer to send the issue to see if other people are interested in making it part of Terria.
At the moment an extra tool could be used to obtain the planes and then configure them in the catalog.

**Comment by KeyboardSounds** [comment]
After merging #5004, the next step is to design a UI so that clipping planes can be defined by end users and moved around, rather than just statically defined in the catalogue.

**Comment by nf-s** [comment]
Clipping box UI added https://github.com/TerriaJS/terriajs/pull/6147
