### ISSUE TITLE
MobX - Inconsistent Feature Highlighting

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#4983]
Not yet ported to MobX (TBC):
In some of the features when you select the layer the selected polygon is not being highlighted e.g., if you select Murray Darling Region in the Australian Drainage Division Layer then you can see the feature information pop-ups but the boundary is not been selected; https://uat.drought.gov.au/#share=s-cwf9HLHblkoA7BQdQ4zupzaa70C 

**Note this particular layer has been fixed**

![image](https://user-images.githubusercontent.com/18452161/98770023-63bb0680-2435-11eb-8aef-c69095d13e2b.png)

**Comment by zoran995** [comment]
this seems to be the same as #4925

**Comment by nf-s** [comment]
This is partially fixed by https://github.com/TerriaJS/terriajs/pull/5010

But still doesn't work for:

- http://services.ga.gov.au/gis/rest/services/GA_Surface_Geology/MapServer
- Examples in https://github.com/TerriaJS/terriajs/issues/4925

**Comment by nf-s** [comment]
There are a few duplicate issues:

- https://github.com/TerriaJS/terriajs/issues/4925
- https://github.com/TerriaJS/terriajs/issues/4093

There is a PR:

- https://github.com/TerriaJS/terriajs/pull/4094

Related Issues:

- https://github.com/TerriaJS/terriajs/issues/1400
- https://github.com/TerriaJS/terriajs/issues/2616
- https://github.com/TerriaJS/terriajs/issues/1674

**Comment by nf-s** [comment]
Also, feature highlights aren't removed if a catalog item is removed from workbench.

**Comment by nf-s** [comment]
Region mapping layers don't highlight features

**Comment by nf-s** [comment]
@zoran995:

> - When a WMS layer is added on v7 and user click on the object it will select all available objects, on v8 currently, it will select only one object. 
> - The v7 had an option to highlight the selected object, there is no such feature in v8. AFAIK it was done getting the geometry from feature response, but the WMS is not required to return Geometry in it (on MapServer it can be disabled, on GeoServer it is possible to use new geojson template and hide geometry). My thought on this is that we could utilise additional style request and load an overlay layer with a highlighted object (it should be set through catalog config).
> 
> [next test](http://ci.terria.io/next/#share=s-dKwaKSi84gryYm82uHd0zvgHy1I)
> [nationalmap test](https://nationalmap.gov.au/#share=s-ebMPvcqmr6GOBP92iIhFFfxslae)

**Comment by tephenavies** [comment]
Add highlight colour to basemap JSON @nf-s

**Comment by AnaBelgun** [comment]
@nf-s to clean up the related tickets

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/6030
