### ISSUE TITLE
When loading config from magda, initializationUrls should be applied even if `group` aspect is not set

### ISSUE THREAD

**Issue by na9da** [TerriaJS/terriajs#4987]
Currently when defining magda config, one has to remember to set `group` aspect for `initializationUrls` to be loaded and applied. Ideally, `initializationUrls` should be loaded even when the group is not set.

[Relevant code](https://github.com/TerriaJS/terriajs/blob/next/lib/Models/Terria.ts#L957-L980).

**Comment by soyarsauce** [comment]
Thanks @na9da - as mentioned, may just be an artifact of magda-based-loading. (i think the logic that was initially written probably used the existence of that aspect as one check/hint that it's a magda map, ie https://github.com/TerriaJS/terriajs/blob/8c5397b39cad00be3610e4dc7d21963a9fa077e9/lib/Models/Terria.ts#L957)

**Comment by soyarsauce** [comment]
(& then subsequently, this block gets skipped:)
https://github.com/TerriaJS/terriajs/blob/8c5397b39cad00be3610e4dc7d21963a9fa077e9/lib/Models/Terria.ts#L980-L991
