### ISSUE TITLE
Catalog converter endpoint

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/terriajs#4992]
See https://github.com/TerriaJS/terriajs-server/issues/129

**Comment by soyarsauce** [comment]
>Run into a few scenarios already where we need the catalog converter, but (IMO) it's not enough to bundle the entire thing with the frontend:
https://github.com/TerriaJS/terrace/blob/master/lib/Helpers/parseCatalog.ts#L86
TerriaJS/terriajs#4938
TerriaJS/terriajs#4897

**Comment by soyarsauce** [comment]
Code split this and the extra upside is not needing terriajs-server to run terria

**Comment by nf-s** [comment]
closing in favour of https://github.com/TerriaJS/terriajs/issues/4897
