### ISSUE TITLE
More granular control over tools/panels 

### ISSUE THREAD

**Issue by smotornyuk** [TerriaJS/terriajs#5008]
It would be nice to have the ability to remove unnecessary controls and, for example, leave expand to full screen, etc. It can be done by passing either object with an explicit state of each available control element(`{zoom: true, workbench: false}`) or by choosing one of a predefined set of controls(like current `hideExplorerPanel=1`, but extended to `toolset=standard-no-explorer`), which is less flexible but, likely, easier to implement

**Comment by nf-s** [comment]
Yep love this idea! 

Somewhat related to #3832 and https://github.com/TerriaJS/terriajs/pull/4984

**Comment by tephenavies** [comment]
Fixed in #5131.
