### ISSUE TITLE
WebGl not supported or too slow in Firefox 83.0

### ISSUE THREAD

**Issue by bwyss** [TerriaJS/terriajs#5012]
When navigating to the map using Firefox 83.0 and Ubuntu 20.4 I am getting WebGl not supported or too slow error

![image (3)](https://user-images.githubusercontent.com/340159/100159500-1d20cf80-2e6b-11eb-991e-86f2a93604f0.png)
![image (2)](https://user-images.githubusercontent.com/340159/100159502-1e51fc80-2e6b-11eb-8fb4-f1708b5c6a92.png)

**Comment by nf-s** [comment]
Hi @bwyss 

If you don't mind, can you please post the output of https://webglreport.com/ ?

Depending on your GPU and drivers, WebGL may be blocked- https://wiki.mozilla.org/Blocklisting/Blocked_Graphics_Drivers#On_X11

It is also possible that WebGL is disabled - https://www.interplaylearning.com/help/how-to-enable-webgl-in-firefox - but I'm pretty sure version 83 will have it enabled.

Also, do you mind if I convert this issue into a GitHub Discussion post?
As it this may be useful for other users

Cheers,
Nick

**Comment by kring** [comment]
Those messages usually mean that WebGL is enabled and working, but it is using software rendering, so it will be very slow. On Linux especially, make sure your GPU driver house is in order. If you have an NVidia GPU, the proprietary drivers are likely to work better.
