### ISSUE TITLE
COLLADA support

### ISSUE THREAD

**Issue by KeyboardSounds** [TerriaJS/terriajs#5014]
As a user,
I want to be able to show COLLADA models on a map as easily as glTFs
So that I don't have to pre-convert models to glTF before adding them to the map.

**Comment by KeyboardSounds** [comment]
We can do this client side or via a conversion service in terriajs server.

**Client side:**
- No data sent over the internet
- Fewer security concerns
- Potentially slow
- Increasing the size of TerriaJS for everyone, not just the few people who use this feature
- We might have to implement the converter ourselves (I haven't found a js implementation of collada to gltf yet). We might be able to borrow some reader code from https://github.com/mrdoob/three.js/tree/dev/examples/jsm/loaders (MIT licensed)

**Server side:**
- not bloating the client with unnecessary extra code
- there's an existing C++ implementation we can use
- but we have to upload user data to a server, which raises security and privacy concerns
- Faster over fast networks

**Comment by AnaBelgun** [comment]
- next is to get the texture working (to check CesiumJS handling of textures in this case)

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/6348
