### ISSUE TITLE
OBJ Support

### ISSUE THREAD

**Issue by KeyboardSounds** [TerriaJS/terriajs#5015]
As a user,
I want to be able to show OBJ models on a map as easily as glTFs
So that I don't have to pre-convert models to glTF before adding them to the map.

**Comment by KeyboardSounds** [comment]
Related to #5014

**Comment by nf-s** [comment]
Related to #4951

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/6348
