### ISSUE TITLE
Write documentation on how and when to use AsyncLoader

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#5031]
AsyncLoader is powerful and gives us memoisation on data/metadata fetches however it abuses a couple of MobX features to do so. AFAIK it is the best solution we can make so we should write documentation to make it easier to understand and apply.

**Comment by nf-s** [comment]
I think we should try to come up with a better solution for `AsyncLoader` - it is pretty confusing when it throws random errors related to changing observables in computeds.

Especially when you have multiple layers - like `forceLoadTableMixin` which is triggered by `loadMapItems` and `loadChartItems`:

https://github.com/TerriaJS/terriajs/blob/6e7c66c565e5b87d8e30e64906f6768995386c83/lib/ModelMixins/TableMixin.ts#L487-L502

**Comment by nf-s** [comment]
Related https://github.com/TerriaJS/terriajs/issues/5233

**Comment by nf-s** [comment]
There are docs:
- https://github.com/TerriaJS/terriajs/blob/next/doc/contributing/model-layer.md#asyncloader
- https://github.com/TerriaJS/terriajs/blob/next/lib/Core/AsyncLoader.ts

And also in Mixins which use AsyncLoader:
https://github.com/TerriaJS/terriajs/blob/7efefad863f1e94c25288c481b874b368b52171d/lib/ModelMixins/MappableMixin.ts#L100-L108

https://github.com/TerriaJS/terriajs/blob/7efefad863f1e94c25288c481b874b368b52171d/lib/ModelMixins/GroupMixin.ts#L20-L31

https://github.com/TerriaJS/terriajs/blob/7efefad863f1e94c25288c481b874b368b52171d/lib/ModelMixins/CatalogMemberMixin.ts#L52-L58

**Comment by nf-s** [comment]
@KeyboardSounds :
> Due to how AsyncLoader works, it's a bad idea to call loadMetadata inside loadMapItems (or any similar nesting of load functions). Tell developers to avoid this.

From https://github.com/TerriaJS/terriajs/issues/5325
