### ISSUE TITLE
UX / UI - Design of workflow and UI for clipping planes

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#5069]
The newly merged clipping plane functionality needs UI for manipulation on TerriaMap; 

https://github.com/TerriaJS/terriajs/pull/5004 

User story from initial ticket https://github.com/TerriaJS/terriajs/issues/4981

[Cesium clipping plane sandpit reference](https://sandcastle.cesium.com/#c=7Vl7c9s2Ev8qON1MI11kyPIjzUl27mzHnXimqd1YSaYTZTIQCUtoSIIFQdlqxt+9ixcJUJQtN/fnecY2CSz2+cPuAhwM0EkcI4KihOU5y+YoT0hG+zCiH9Cc8pRKsUKSo2LBb5FcUCRoLmhBM0kk4xniN2p0mg0G1eosRhHPpOCJXpCSecZkGVNLa5nHrJAkiyi6ZXJhCHlZUDzNptmSCLRk9JYKdIwyeovOaMHKFH/QY91pJ9LvZyCFsIyKaaePvk0zhFh2w0/53QjdkKSgfTVU0IRGStWLLGYRkVzUs/e9sRFWRBRUOrZCsX4dO02Uey5nvwOXAkg+TTunF2+VxGnnirNMorOEl7EZuMiMUfb1LY9pMu18Htcm6SFgo9WN6aycn/ISNMvmH3hSprQ4z8gsobFvAo3n9FquEiCqZqUo7eQdSfOETlY5LUa+rno2KoWAWJ3XRAHNp93Pyg2VqZKIOZW/gX67eNdqrcN1nkkmGdUOcOYYz9L4ShGMa18pKOmxQvMFZFxrShv42wXNTKxRzG+tYPX0BpCTNEN+HQlKs+ucRPR8CZZYoq4yzo8WjggwKqaZCqnHDRdUXmR5KU80CLo3ZaYfUDflS5oCx56JhTaVRV9pbHwDahjGarAixjkvmFqvxADebpDWBDl1Y3oDgIy7Pqce+uGHR4kwi7elw9qPPUVqdUdhLED11iXjFlqcEkkFIwqTVuwZT7jAH99cTM6x2pwnSb4gXQDEYa+VAy8lQJPqZa1c3CrtzqIO6BlJqSBnJleoWFGNbh0uhTS9A/TiewBpfxMkFKrxz+c/Tb68vvz4S8+B7h0oSQqXbrjDXJkbxJX5k/DWgjUlqeKyGWc2RgoqjbgGbuy1x/IJ8Rl+Z3gaEIKsZPR0EdDZ9KkxVHlqvF303l9VsXufx2B2M3RqE5rgqaf/XbrwuG2dLrYPp05vNJFEpdUqj0CdEPLKJhO8Qjv1FM3iesIGxyXm58eW15bb4u3l++vzL28vP5wb31b2ADF4WKtqnP2Tnema7GK0F1SWIkNrYEYmNLgq4sdOQ6uvXVinHVVj7qsywxJoIeTY0yfhJJ6Y4W4pEisnLCdhqM/8uTMFPqO/ryBUxE/mFW1c2nUEIQmEB55Itq8yXx/pPztDvNvr1/Qw6F7c8Gf7X9XsjyyWi1Fd9vF6IUf/QcATjTR/7ScTJ+R81GhKcC5YCtBY0gKTOLa6+3rrf/uvnS+/OQXBqSP1p1I/9O2o8W7J7k2ZCXXCum+5ho4w7F3QsUV8ZfADDc7Yw5fjC5iMV1eCp6yghhWGxrAlmbp9NbOsr/MFFRqFllM4MfbXCBKzUmEppMFm3FrqzAC//8l5OuEeSqyMfitu3oAJyolMRot3JJtTgM8hIGcX7/Wd6H+hA8BRhRxPZN1PqJ9/WJ5viRTs7gDTP0qoiB5BHRHBucRSkKy44SLt+yQNJhevz3+ZXEx+q0lqTWrnIgRZeAJNeXg2QKyAHhvwR5JkhVwvBDAmUrfwVp1nBVIKoUohHPA9yXNYTTIECNYMoLqlWj110gCYQ8XT7BrCAQBq1MUNFSbqZoEnQqcYJ/rMsDtu+gGS1UTRJPoc81SntmeKnufU8SZ9gJzPBckXLPLKsTeKb2AHVFxDzUKrNosLsf19Mlu3FI4e0WBB2XwhXUowP5u1wpZ8p93adUpPWpi4cKoyj4nyetSVmZvC/lj2N4JbY3xfb2HQF3WVA5g6RY3h31FTw4Rmc7kYo+fPWbDlqtMWrGwsAbR2WdPF9clsVZcJak9qujx88+1z23WEWkMZ4FuzHqFgPZxXGTQoBbCActHmrb1uSI/qjLcHWfChyXCu16B1TfDo8R64sdIaEmibJDMSfYU6k1MhV2s6P9YardmhzykPG2CbcO/cvjanTWozMCC/997u/dKBwoM6zsti0fUQEoDV+j+ovmO/4kPl5ZBrxS1UYq/8UiG48DAbARR4QnHC53au4uL6vaDD013B//u76r7B7sgwJxu1dKp6TefQ1LuSvzPc28e7Px4cvBj+26pxAJ3E4e7+j7sv7MD+rlXaRMJkYt2SBMlwgSV/B8OQCbvD/UMwe1xfgkDrUt0A2Z4J3N8YWuSNo1fQ+QB918rtG459zaQWwwWrLhErzSYu4xd40WD3a6lyQFYnbec8azjoE5pNt0iMGZxe/a64TpEN7p62I//FTuua46XLUrCw2S4ikoCkl9VACm1UWqZX7I4m1+xPmBvuOoxs3503IGUMhbKpLn+qwmAcYWn+ZnnatjQ9sSxt9HdbBXq8+mjw980e8Pfx3ysfTywdTyobjZLhT24qFVuXifu+l4O9ZPlIabi3CRsa9Cuurt6VKRLFIGieGYSjXPAliyGtzVboFEKa0BW6XhWSpoU52c9Y+l54d1UXPHtHC16KiOqEdlKoC5a4+/LwxYG7fM/VLbq+RN9q6fDFwd7QrWXuwl0vVWZMOxgPrvV192siySA4EA+qC/r66bLezQPX6/5e8GzaGbvLJjDdqNZkrqcKK+OECfv0BR7xPJlpFtPMv9swDqouuiZqr5pPJho+5oDDdHdW6M2qBtQeMmrY+xPOAYcq/8Y8KvWlEezC80TfH52uwEnTjqWZdpQs69KvGY++Ao5MiuhWhauNhKhD2qnVpCbtO+HGhMYqFQClyuWsoGKpKqC/ctpZ/xwB+ulFRTkrIsFmfrcBO+8DSUpaZSGhXVjDWh2XHRE6Pj5ufNrwGpX2EOhdgiCC9GFWw02sAug+hePeJo4+oOuWTe9J2ysoQFRU1TURmfEloAeaMMKqntDBOTwSeQnt8WNRe8s0PNTt0uFL/KKPDnfxy73D4D7Dc0Ngpen/3IaqKL0q9kRAPXDB9BCylgGsWu5yred6XpQevfxCmuv327TeRW5vim58XGvqVPKb0GrvNKq4v6h6HntGVBLtJrRfzRrVXVB1jX0C3Z9txDbcXRq6ys2atvVDI1r7JulfjfrfKHTx6vQ7RwX4jr5yYfsvS3MupOrGupC8oVSBHMDxYFZClyRxVBT1Pvuny6xe26EK/lyoWI+QmM9I92Cvj9wvQN8/lefqRiubj9BBfucNz7iIqdgx591w8n5NNFOfH4JrAWg1GPSPOySBSjyC1jGOE7oudUfyfIT2Asluasal5Gk4uy5aN900sP6GZ3LnVt98qHuDJG4uPxr4/j6K2RKx+LjlEz0gjhQFzNyUiW55p51XRwOgX1uqMgUofQmGJ2SlyBbDVz+bQYzx0QBe21dWRa8K/5H5KoOgISM7qrACFc+l6SL9b+d9s1dGqK1GgTjDp+ZrwiRhWhm7oNHXGb8DKzUXZaXu8DqBYE2mvt4/kLasHqaFHKFnWs4zzyKVeuo70KVevLVWqqfcpNR63nlUF0OnV6LCLHWoMOExb38B)

As an end user of Terria,
I want to be able to to use the Clipping Planes in 3DTiles from its catalog. This allows cuts sections of the 3DTiles to display only the important parts.
It is very useful when you have already generated a big 3DTile and want to use a section to share a scene without having to process the 3Dtiles again.
Also in the future there could be a tool that allows to graphically edit the planes and make the cuts before sharing the scene.

**Comment by KeyboardSounds** [comment]
@philipgrimmett :)

**Comment by AnaBelgun** [comment]
Tools to look at: 
- Navis Works
- Revitzo

Clipping planes and sectioning tools

**Comment by philipgrimmett** [comment]
Figma prototype for clipping workflow: https://www.figma.com/proto/jtdgEiY0gxtZlGtxSJTzcZ/Terria---2021?page-id=8464%3A14594&node-id=8954%3A27390&viewport=241%2C48%2C0.36&scaling=min-zoom&starting-point-node-id=8954%3A27390

Prototype demonstrates the following:
- Simple box clipping
- Clipping mode selection (inside/outside box)
- Box rotation on z-axis (centred)
- Box lock/unlock

![Screen Shot 2022-01-19 at 1 23 34 pm](https://user-images.githubusercontent.com/5292858/150051791-9b43ac75-49fc-4a1e-8275-a5daed40df3f.png))

**Comment by AnaBelgun** [comment]
@meh9 would you please list here your feedback when you get a chance? in a new Clipping Planes v2.0 ticket?

**Comment by AnaBelgun** [comment]
Update 12 Jan 2023: 
- clipping box is not immediately visible to users when clicking on the "clip mode" box under the dataset name 
- how do we make it clear to users clipping box is active / non-active
- to check when adding a reality mesh, can we trigger the clipping box from the feature information panel (similarly with how we do it for scene editor)

**Comment by AnaBelgun** [comment]
Closing this ticket; information transferred into new ticket: https://github.com/TerriaJS/product/issues/124
