### ISSUE TITLE
KML/KMZ not supported in IE9

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#508]
We get this error even for valid KML or KMZ files:
![image](https://cloud.githubusercontent.com/assets/924374/5995725/e4bce7c4-aaee-11e4-8fc7-1cbcc11f5ca5.png)

**Comment by kring** [comment]
The problem here is that IE9 doesn't support the `Blob` type, which is used internally by the Cesium KML loader.

**Comment by stevage** [comment]
We're pretty unlikely to fix this now, right?

**Comment by kring** [comment]
Still an issue in current versions of TerriaJS, not that we probably care very much.

**Comment by kring** [comment]
This will never be fixed, closing it.
