### ISSUE TITLE
Add group trait to sort group items by name

### ISSUE THREAD

**Issue by na9da** [TerriaJS/terriajs#5081]
In v7 group members are automatically sorted by name whereas in v8 they appear in the order defined in the catalog. Add a trait like `sortByName` to GroupTraits that forces the members to be sorted alphabetically by their name.

**Comment by meh9** [comment]
I think alphabetic order should be the default, and maybe a setting to change that? Seem to remember that's what we had in v7.

**Comment by nf-s** [comment]
Related to arrayTrait sorting problem - https://github.com/TerriaJS/terriajs/issues/4559  
This should be done in a generic way to solve sorting arrayTraits across stratum
