### ISSUE TITLE
ArcGIS layer names are not converted to layer id's when requesting tiles in v8

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#5084]
ArcGIS does not do the right thing when requesting layers by name and need to be requested using their id's.

In v7 when using an ArcGIS layer like the Contours layer in NatMap, the layer names used are given as text, but when requesting the actual tiles they have been converted into the layers numerical id's:

<img width="565" alt="v7" src="https://user-images.githubusercontent.com/5283003/102147686-40192f00-3ebf-11eb-9468-6f34b731b94d.png">

<img width="580" alt="v7" src="https://user-images.githubusercontent.com/5283003/102147733-532bff00-3ebf-11eb-9b08-2f70026d7050.png">

<img width="489" alt="v7" src="https://user-images.githubusercontent.com/5283003/102147893-9c7c4e80-3ebf-11eb-888c-a7e291eda6e4.png">

In v8:

<img width="574" alt="v8" src="https://user-images.githubusercontent.com/5283003/102147835-83739d80-3ebf-11eb-984f-dcaa598e5dfe.png">

<img width="573" alt="v8" src="https://user-images.githubusercontent.com/5283003/102147857-8e2e3280-3ebf-11eb-92b7-e41a9e3a7da8.png">

<img width="464" alt="v8" src="https://user-images.githubusercontent.com/5283003/102147917-aa31d400-3ebf-11eb-86b4-ef9ddae66073.png">

As can be observed the output is very different. If you manually change the layer name to be the numerical id's in v8, then the layer works successfully.

**Comment by na9da** [comment]
I kinda understand the problem. We apply a logic similar to master to find the specified layers by id or name 

https://github.com/TerriaJS/terriajs/blob/30a684c8902bc43be0809b4bf73c2fde48e2a8c9/lib/Models/ArcGisMapServerCatalogItem.ts#L525-L540

But then when creating the imagery provider we use the original user provided list of names or layer name from the URL.

https://github.com/TerriaJS/terriajs/blob/30a684c8902bc43be0809b4bf73c2fde48e2a8c9/lib/Models/ArcGisMapServerCatalogItem.ts#L404-L415

A fix for this might be to build the `layers` parameter above from `this.allSelectedLayers`.

**Comment by meh9** [comment]
Fixed in `next`
