### ISSUE TITLE
UX/UI - reconsider Help pages from About tab/menu

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#5086]
With the Help menu now separately placed at  the bottom of the screen, the Help pages available from About tab should be reconsidered. 

Under About: 

![image](https://user-images.githubusercontent.com/18452161/102306917-7934ca80-3fb7-11eb-8da8-7978d9b3c479.png)

New Help button (bottom right): 

![image](https://user-images.githubusercontent.com/18452161/102306966-8ce03100-3fb7-11eb-8cf1-6ff91c42be5f.png)

**Comment by nf-s** [comment]
No longer relevant
