### ISSUE TITLE
No legend for MapServers

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#5096]
At the moment we aren't getting any legends for MapServers in v8.

v7:

<img width="349" alt="Screen Shot 2020-12-18 at 12 13 32" src="https://user-images.githubusercontent.com/5283003/102562105-74445800-412a-11eb-8ac7-3ab9cf84f076.png">

v8:

<img width="349" alt="Screen Shot 2020-12-18 at 12 13 48" src="https://user-images.githubusercontent.com/5283003/102562125-7d352980-412a-11eb-8b56-0972c9697025.png">

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/issues/5179
