### ISSUE TITLE
Region mapping doesn't work in IE9

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#511]
`test/2011Census_AUST_STE.csv` reports:
![image](https://cloud.githubusercontent.com/assets/924374/5995854/f72d2da4-aaf0-11e4-918b-5e442221ac9d.png)

**Comment by kring** [comment]
Turns out this is not IE9 specific.  Region mapping doesn't work in any browser when the CSV is added via a URL.  It does work when browsing for a local file or when dragging/dropping, but neither of those options are available in IE9 due to the lack of the File API.

**Comment by kgrochow** [comment]
Fixed as of our most recent release.
