### ISSUE TITLE
Question more than an issue

### ISSUE THREAD

**Issue by sammyaxe** [TerriaJS/terriajs#5125]
In latest project https://nsw.digitaltwin.terria.io/ I see something called scene editor, but can't find any documentation on this functionality. Is this part of Terria.js? Also does it allow to control the assets added on the left site bar?

**Comment by zoran995** [comment]
please check the https://github.com/TerriaJS/terriajs/issues/4782#issuecomment-722683187
> it is currently not an open feature available in the open source version of TerriaJS.
