### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by orangesunny** [TerriaJS/terriajs#5126]
Hi, dear community,

We in Weblate got contacted by one of your users (*arky*, I hope he’ll speak here) about the localization. As we love and support libre software, we offer free Weblate hosting for libre projects.

This is the checklist that has to be fulfilled to have libre hosting approval:

> - Translated content has to be released under a license approved by OSI or recognized as libre by FSF.
> - All the source code has to be publicly available in a supported version control system.
> - Translations have to be in the same repository as the source code, or under the same project/organization as the source code repository.
> - Using Weblate has been approved by the upstream project.
> - Mention you use Weblate for translations in the README. It’ll attract new translators and also help Weblate to be free for more projects.
> - The project has had active development for at least three months.
> - You will have 14 days to set up your project.
> - Please request project approval once you finish the setup.
> - Unapproved projects will be removed.
> - There is no guarantee of service availability or quality for a free service plan.
> 

With the [current setup](https://hosted.weblate.org/projects/terriajs-l10n/), I feel that:
- **Project is not approved by upstream here.**
- The CLA there is not needed and inappropriate as the project is under Apache 2.0. The translations will be the same.
- The naming of the projects doesn’t need to have L10N in it. Weblate is a l10n platform.

Can anybody from the maintainers clarify the situation for me, please, and register on [Hosted Weblate](https://hosted.weblate.org/) so they can be the admin of the translation project?

Cheers!

**Comment by arky** [comment]
Adding the link to discussion thread for TerriaJS localization  https://github.com/TerriaJS/terriajs/discussions/5072

**Comment by arky** [comment]
@meh9 @KeyboardSounds if you have time, please do join and manage  [TerriaJS project on weblate](https://hosted.weblate.org/projects/terriajs-l10n/terriajs/) ? It would help the community contribute localization more effectively. Thanks!

**Comment by arky** [comment]
Wonder if anyone from @TerriaJS developer team could join and manage TerriaJS project on weblate ? It would help the community contribute localization more effectively. Thanks!

https://hosted.weblate.org/projects/terriajs-l10n/terriajs/

**Comment by tephenavies** [comment]
Hi @orangesunny. We're keen to try out Weblate for our contributors to manage their localised languages more easily.

We meet all of the listed requirements for a libre project except the README entry. And we're happy to point to Weblate from our README when we get Weblate working.

As to your points:
* I'm not familiar with the CLA you're mentioning. Is this a CLA on the project terriajs-l10n set up by @arky?
* I agree that l10n doesn't need to be in the name

I have registered an account https://hosted.weblate.org/user/steve9164. What is your plan for adding us as admins? Will we take over the project that @arky started, or start another one and migrate the content that @arky has contributed? We should ensure that any translations aren't lost.

Could you please also clarify how users can contribute translations?
* Do users that wish to contribute translations have to be added as editors by us? Or;
* Can anyone registered suggest changes but the changes must be reviewed and accepted by us?

Thanks for contacting us!

**Comment by arky** [comment]
Thanks for the positive response @steve9164 . I have added you as admin of [terriajs-l10n](https://hosted.weblate.org/access/terriajs-l10n/) project. Also attaching a full list of translations that were done so far. 
 
[terriajs-l10n-terriajs.zip](https://github.com/TerriaJS/terriajs/files/5854985/terriajs-l10n-terriajs.zip)

You could rename this project component or start another one if you prefer. 

There is some documentation on setting up a localization peer review workflow here. 
https://docs.weblate.org/en/latest/workflows.html

**Comment by arky** [comment]
@steve9164  @KeyboardSounds Please let me know if I can help in anyway

**Comment by tephenavies** [comment]
I've renamed the project and changed its URL @arky.

Also there's a PR #5176 to add Weblate to our README.

**Comment by arky** [comment]
Thanks @steve9164 Please kindly look into setting up repository hooks for automated flow of updates to Weblate. 

I think that is last requirement we need to comply before @orangesunny could approve Libre hosting for TerriaJS project.

**Comment by orangesunny** [comment]
Hi all,
I apologize for the delay on my side.

**Most important thing: You‘re approved!**

@steve9164 
>  I'm not familiar with the CLA you're mentioning. Is this a CLA on the project terriajs-l10n set up by @arky?

Yes, it was not needed and it’s gone :)

>  Do users that wish to contribute translations have to be added as editors by us? Or;
>  Can anyone registered suggest changes but the changes must be reviewed and accepted by us?

As you have it set now, https://hosted.weblate.org/settings/terriajs/terriajs/#translation anyone can suggest, all registered users can translate. See https://docs.weblate.org/en/latest/admin/translating.html#translation-process

If you would like to limit contributions, read and make your settings :) https://docs.weblate.org/en/latest/workflows.html?highlight=review#translation-workflows

Fix your alerts to have all synced :) https://hosted.weblate.org/projects/terriajs/terriajs/#alerts


Welcome to the community, enjoy libre translation!

**Comment by arky** [comment]
Thank you @orangesunny !
