### ISSUE TITLE
Hide error report code, provide 'report crash and reset' button

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#514]
When the NM crashes (rendering stops etc.) hide the error report code (see attached screenshot) and provide a natural language 'something went wrong' message with a 'report crash and reload page' button underneath. This should probably be followed by something along the lines of "crash reports help to improve the National Map and are checked by humans." (thoughts on this?)

![screen shot 2015-02-04 at 11 08 54 am](https://cloud.githubusercontent.com/assets/5292858/6033176/a298ba34-ac66-11e4-8f52-e239f0a7ad35.png)

**Comment by kgrochow** [comment]
Resolved as of version 1 as far as I know.
