### ISSUE TITLE
Share URL doesn't capture 2D view (but should)

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#515]
Share URLs for 2D maps switch back to 3D on load. This is confusing, as it often results in different satellite imagery being shown to the link recipient.

2D
![screen shot 2015-02-04 at 2 23 12 pm](https://cloud.githubusercontent.com/assets/5292858/6034645/6e08ef60-ac79-11e4-95d2-b8992dd7c809.png)

3D
![screen shot 2015-02-04 at 2 23 15 pm](https://cloud.githubusercontent.com/assets/5292858/6034650/793e389a-ac79-11e4-9377-3243635e5ad8.png)

**Comment by kring** [comment]
I think this behavior is correct.  Yes, it can result in a slightly different view, but so can a different window size.

Also, our 3D bounding box computation is terrible, so the view often changes more than it should.  But that's a separate issue (#282).

**Comment by kgrochow** [comment]
2D is usually a function of the capabilities of the browser as opposed to the user selection at this time, so I think the existing behaviour is appropriate.  We show in the 'native' view of the browser.
