### ISSUE TITLE
Port WPS GetCapabilities (WPS Group) to v8

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#5150]
https://github.com/TerriaJS/terriajs/blob/master/lib/Models/WebProcessingServiceCatalogGroup.js

**Comment by AnaBelgun** [comment]
Although initial WPS support is available in v8 (https://github.com/TerriaJS/terriajs/pull/4068), some of the services relying on WPS do not work in our maps.

- [ ] Geoglam - https://github.com/TerriaJS/RaPPMap/issues/105
- [ ] NationalMap - AREMI - https://github.com/TerriaJS/nationalmap/issues/1009

TODO:

wps-getCapabilities: We don't support WPS-group in v8 TerriaJS/terriajs#5150 - @nf-s

 itemProperties
 cacheDuration
 contextItem
 name
 description
 layers
 url
 type
 legendUrls
 rectangle
 ignoreUnknownTileErrors

**Comment by na9da** [comment]
Fixed by #5309
