### ISSUE TITLE
Add compass to 2D map (without orbit)

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#516]
Retain a modified version of the compass in 2D map view (see attached)

![compass-2d](https://cloud.githubusercontent.com/assets/5292858/6034733/824285a8-ac7a-11e4-8147-17956feda9b9.png)

**Comment by kring** [comment]
What's the purpose of this?  Just to show that North is always up in 2D?  Or do you intend for the map to be rotatable?  I'm not sure if that's possible with Leaflet.

**Comment by kgrochow** [comment]
Done
