### ISSUE TITLE
Clicking animation control does not restart globe animation

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#518]
- Load a time-varying dataset, such as incidents.csv.
- Move the mouse over the play button and leave it there for a few seconds so the animation loop stops.
- Press the play button, being careful not to move the mouse over the map in the process.
- The play button highlights as expected, but the map doesn't change and the current time display doesn't update.
- Move the mouse over the map to trigger the animation loop and time starts ticking again.

**Comment by meh9** [comment]
This sounds like it might be related to #498.

**Comment by kring** [comment]
Yes, sort of.  Anytime we make a change to the map, we have to tell it to start redrawing itself again.  Someday we'll have animation loop pausing built into Cesium and won't have to do this, but alas that day is not today.

So the issue here is we're not restating the animation loop on timeline interaction.  The issue in #498 is we're not restarting the animation loop on touch events, only mouse events.
