### ISSUE TITLE
CZML with time not supported in v8

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#5182]
Drag and drop this CZML-with-time into v8 and watch it not work:

[BAMS_C4ISR.czml.zip](https://github.com/TerriaJS/terriajs/files/5884803/BAMS_C4ISR.czml.zip)

<img width="1231" alt="Screen Shot 2021-01-28 at 15 39 58" src="https://user-images.githubusercontent.com/5283003/106090787-18380f00-617f-11eb-94cb-ffc1ea5cec8e.png">

Do the same into any v7 map (e.g. https://nationalmap.gov.au/) to see what should happen:

<img width="1231" alt="Screen Shot 2021-01-28 at 15 34 34" src="https://user-images.githubusercontent.com/5283003/106090743-fc346d80-617e-11eb-8fc0-d8135c77c2f7.png">

**Comment by AnaBelgun** [comment]
Needs discussion about estimation/complexity

**Comment by tephenavies** [comment]
@steve9164 to investigate complexity and solve if small or comment and refine/plan if medium/large.

**Comment by AnaBelgun** [comment]
depended / blocked by asyncloader issue: https://github.com/TerriaJS/terriajs/issues/5233
