### ISSUE TITLE
How to handle broken/unsupported catalog items - UX

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#5188]
An idea - **Keep track of uptime of catalog items and report to user**

Might be a nicer UX than just throwing an error randomly - this would remind users that we don't host the data, and that quite a few services are down frequently

Also, maybe show placeholder for broken or unsupported datasets

**Comment by nf-s** [comment]
Related issues:
- https://github.com/TerriaJS/terriajs/issues/5184
- https://github.com/TerriaJS/terriajs/issues/3499
- #3486

**Comment by t83714** [comment]
https://sentry.io/for/javascript/

**Comment by nf-s** [comment]
**If we go for the error tracking service option**

>Pete: We have https://rollbar.com/ setup on some maps already

So see if we can use that - if not look at sentry

**Comment by AnaBelgun** [comment]
This ticket is superseded by other error handling tickets:
Only show supported file type in My Data and workbench #5184
Model architecture: Improve preview map #3499
[EPIC] Design and implement error handling #3486
