### ISSUE TITLE
2d base maps fail on iOS browsers and Mac Safari

### ISSUE THREAD

**Issue by geopast** [TerriaJS/terriajs#5209]
Hi folks,

In addition to #4366, there seems to be a general issue with 2D base maps across major iOS browsers and Mac Safari:

1. Open iOS/Safari
2. Go to https://nationalmap.gov.au/
3. Switch to any 2D base map
4. Zoom to any location

same experience with:

- iOS/Chrome
- iOS/Firefox
- Mac/Safari

No issue with:

- Mac/Chrome
- Mac/Firefox

Since 3D appears to work perfectly, a workaround for mobile could be setting mobileDefaultViewerMode to either "3DTerrain" or "3DSmooth" in config.json.

If anyone can test on Android, would be good to know how it goes with 2D also.

![nationalmap-mac:safari](https://user-images.githubusercontent.com/10397157/106680437-c118bb00-6612-11eb-93f7-c235daa80bbc.png)

![nationalmap-ios:chrome](https://user-images.githubusercontent.com/10397157/106680457-cbd35000-6612-11eb-893f-ef32832b5970.jpeg)

**Comment by irbian** [comment]
do we have some workaround to this?

**Comment by ashleysommer** [comment]
I'm hitting this same issue in my TerriaMap build for TERN-Landscapes. It affects not only the basemaps, but also WMS layers served by MapServer.
Only happens in Safari on macOS, and Safari, Firefox, Chrome on iOS.

**Comment by zoran995** [comment]
I can't reproduce this on terriajs v8
