### ISSUE TITLE
disambigDataReplacement doesn't exits in v8 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#5213]
AREMI / NatMap - *some region mapping issues**  - `disambigDataReplacements` doesn't exist in v8 - so LGA_name doesn't work

**Comment by nf-s** [comment]
Related to https://github.com/TerriaJS/terriajs/issues/4715

**Comment by wibily** [comment]
same as Terria-PacificMap#70

**Comment by AnaBelgun** [comment]
Fixes included in: https://github.com/TerriaJS/terriajs/pull/5740 and https://github.com/TerriaJS/terriajs/issues/4715

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/5740
