### ISSUE TITLE
WMS time data GetFeatureInfo

### ISSUE THREAD

**Issue by zoran995** [TerriaJS/terriajs#5216]
When using WMS with time data, there is pretty much weird issue. We are getting the feature info response for data that is currently not visible on the map and is available only the future.
The issue seems to come from the following code, listing data available in the future as available for this dataset. Do we need those items that are not visible on the map for something else, or is it safe to comment it and track if everything continues to work fine? @na9da @nf-s (tagging you since you did the most recent changes for WMS)
https://github.com/TerriaJS/terriajs/blob/a18897524dc904f1dcb482d515c1e3fa8c65cae7/lib/Models/WebMapServiceCatalogItem.ts#L937-L940
This is a pretty major issue for us, so I would like to fix it ASAP

![image](https://user-images.githubusercontent.com/19208948/106969801-df360680-674b-11eb-8076-ac1062eb5a0c.png)
it is available in the future point in time
![image](https://user-images.githubusercontent.com/19208948/106969839-f2e16d00-674b-11eb-8675-749690604b6b.png)

**Comment by nf-s** [comment]
Yeah you are right, it seems to be requesting `GetFeatureInfo` for both the current and next `imageryProvider`

![image](https://user-images.githubusercontent.com/6187649/106980133-bc3f3d00-67b3-11eb-962a-b665ee444dd6.png)

I'll have a look into it

**Comment by nf-s** [comment]
Hey @zoran995 let me know if this fixes your problem!
https://github.com/TerriaJS/terriajs/pull/5217

**Comment by zoran995** [comment]
@nf-s thank you for that

**Comment by nf-s** [comment]
Are you happy for me to close this issue @zoran995 ?

**Comment by zoran995** [comment]
yeah, resolved in #5217
thanks @nf-s
