### ISSUE TITLE
NominatimSearchProviderViewModel not zooming to feature on click.

### ISSUE THREAD

**Issue by spwoodcock** [TerriaJS/terriajs#5218]
I have a connected Nominatim instance to TerriaMap. The search returns and displays correctly, but when clicking on the SidebarSearch item an error occurs in the LocationMarkerUtils addMarker function (extracting coordinates from result.location.longitude).

The NominatimSearchProviderViewModel marker/zoom functionality independently, but the addMarker function requires coordinates to create the marker in the correct position.

![image](https://user-images.githubusercontent.com/78538841/107010962-4f1dae80-6797-11eb-9262-282af9c241f0.png)

I fixed this by passing the Nominatim item lat/lon through to the SearchResultViewModel item.

Original NominatimSearchProviderViewModel.js:

```
if (!findDbl(locations, resource.place_id)) {
  locations.push(
    new SearchResultViewModel({
      id: resource.place_id,
      name: name,
      isImportant: true,
      clickAction: createZoomToFunction(that, resource)
    })
  );
}
```

Modified NominatimSearchProviderViewModel.js:
```
if (!findDbl(
    locations, resource.place_id,
    resource.lon, resource.lat)) {
  locations.push(
    new SearchResultViewModel({
      id: resource.place_id,
      name: name,
      location: {
        longitude: resource.lon,
        latitude: resource.lat
      },
      isImportant: true,
      clickAction: createZoomToFunction(that, resource)
    })
  );
}
```

**Comment by zoran995** [comment]
We recently reimplemented NominatimSearchProvider in v8 using a new search providers model. This shouldn't be an issue any more
