### ISSUE TITLE
DEAMaps V8 testing issue - Delta Comparison date field name

### ISSUE THREAD

**Issue by GypsyBojangles** [TerriaJS/terriajs#5236]
### Expected behaviour
"Date B" picker should be labelled "Date Comparison B"

### Actual behaviour
"Date B" picker is labelled "Date Comparison A"
[
![screenshot](https://user-images.githubusercontent.com/15754245/107710079-68d07000-6d1a-11eb-9dcf-2dc3f9faaad2.PNG)
](url)
### Steps to reproduce the behaviour
- Explore map data
- Expaned Delta folder
- Add Delta blended service
- Click "vertical ellipsis"/more button on Delta Blended service layer
- Select Difference

**Comment by nf-s** [comment]
closed by https://github.com/TerriaJS/terriajs/pull/5248
