### ISSUE TITLE
Fix highlighting for region mapping 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#5243]
Related issues

High priority: 
#4925 https://github.com/TerriaJS/terriajs/issues/4925 - WMS - 
#4093 https://github.com/TerriaJS/terriajs/issues/4093 - imagery - PR open https://github.com/TerriaJS/terriajs/pull/4094 - NOT MERGED

Low priority: Related (older)  Issues:

#1400 - https://github.com/TerriaJS/terriajs/issues/1400
#2616 - zoom to selected feature - https://github.com/TerriaJS/terriajs/issues/2616 
#1674 - show nr of selected features - https://github.com/TerriaJS/terriajs/issues/1674

**Comment by nf-s** [comment]
closed by https://github.com/TerriaJS/terriajs/pull/5312
