### ISSUE TITLE
URL shortening not working

### ISSUE THREAD

**Issue by MoRadwan74** [TerriaJS/terriajs#5250]
I have a TerriaMap instance up and running with `terriajs: 7.11.16`. When I try to add data and share the map, it generates a very long URL that embeds all the data coming from the catalog file.
![Terria-share](https://user-images.githubusercontent.com/30727109/108181890-1bd10d00-7111-11eb-8bf7-7b467eaa3509.png)

On the other hand, when I use the [National Map](https://nationalmap.gov.au/), the shortening feature worked!
![NationalMap-share](https://user-images.githubusercontent.com/30727109/108181906-21c6ee00-7111-11eb-9aa7-f52042197fed.png)

So what's the problem? Is there some sort of a configuration that should be added to enable the shortening feature?

**Comment by zoran995** [comment]
URL shortening is `terriajs-server` feature and is configured in `serverconfig.json`, you can check the configuration example in https://github.com/TerriaJS/terriajs-server/blob/master/serverconfig.json.example#L137-L171. Important to define are `shareUrlPrefixes` and `newShareUrlPrefix`. You can use s3 bucket and gist

**Comment by MoRadwan74** [comment]
I've seen the `shareUrlPrefixes` property and tried to add it but nothing happens, figured out that I missed this line `"newShareUrlPrefix": "g"` and it works like a charm now. Thanks @zoran995
