### ISSUE TITLE
Pointcloud integration

### ISSUE THREAD

**Issue by giaplesg** [TerriaJS/terriajs#5255]
First of all, great work with terriajs its absolutelly amazing keep it up guys!!!
I have a pointcloud from some regions and i would like to import them at the globe, such as cesium does with these types of files. Is there any way in terria that i can implement this?
The types of files can be .laz or .ply or any other supported (binary) format.

**Comment by hardreddata** [comment]
Hi @giaplesg 

The simplest way would probably be to get a trial Cesium ion account and upload the model there.

You can then access via the Asset ID and https://docs.terria.io/guide/connecting-to-data/catalog-type-details/3d-tiles/ using something like this catalogue item.

```
{
   "name":"My Model",
   "type":"3d-tiles",
   "description":"My description",
   "ionAssetId":12345,
   "ionAccessToken": abc123
}
```
