### ISSUE TITLE
GeoJsonMixin forceLoadMapItems needs rewrite

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#5275]
https://github.com/TerriaJS/terriajs/blob/cd5bae29dfbbbed7721da9566e41ecf4c3ade8b3/lib/ModelMixins/GeojsonMixin.ts#L122-L138

Currently the whole function runs even if `customDataLoader` loads something. `customDataLoader` should return a Promise when it loads something and undefined when it doesn't load something. I think instead of using the Promise constructor it would be neater to use `Promise.resolve().then(` or maybe async/await.

**Comment by nf-s** [comment]
`GeoJsonMixin` now follows an approach similar to `TableMixin` https://github.com/TerriaJS/terriajs/pull/5900

https://github.com/TerriaJS/terriajs/blob/92f47a6872b4d521093d01ddf776178d3fb71d67/lib/ModelMixins/GeojsonMixin.ts#L305-L317
