### ISSUE TITLE
v7 - v8: EPSG:4326 WMS support missing in v8

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#5286]
NT (service doesn't have EPSG:3857 tiles. EPSG:4326 WMS not supported in v8)

Example to test with: 
http://wms1.ntlis.nt.gov.au/ilismap?service=WMS&version=1.1.1&REQUEST=GetCapabilities
https://nationalmap.gov.au/#share=s-1TWe0eilKs3KF7lB2PN1JUJ6so5
Name: 71
Title: Pastoral Properties

**Comment by nf-s** [comment]
I have added this in a random branch

https://github.com/TerriaJS/terriajs/blob/aa4537aaf3dc7acc27e88b422a8937e5c0bdcdd5/lib/Models/WebMapServiceCatalogItem.ts#L1102-L1112

I'll put it into a PR

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/5327
