### ISSUE TITLE
v7 - v8: set up Google analytics

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#5287]
Set up support for google analytics in v8

@nf-s is this done? shall I split the ticket with the remaining maps?

**Comment by AnaBelgun** [comment]
Options: 
- adding google analytics keys for the specific projects: 
- ideally we should use the same v7 keys if possible

- [x] DE Africa
- [x] DE Australia
- [x] PacificMap
- [x] NationalMap 
- [x] Geoglam
- [x] NEII

**Comment by wibily** [comment]
ensure v8 has same v7 keys
- check that the v7 keys have keys and use the same one

**Comment by wibily** [comment]
use ua keys not g keys

**Comment by wibily** [comment]
look at #devops-48 for list of keys

**Comment by wibily** [comment]
note: Pacificmap & beta.nationalmap.terria.io will require a Saas deploy
Nationalmap and NEII will require standalone deploy

**Comment by wibily** [comment]
note: NEII uses a completely new key as I could not determine who actually owns the old key from 5 years ago

**Comment by wibily** [comment]
from Ana: for the nationalmap.gov.au the google analytics is managed by Geoscience Australia so we don't have to touch that
4:17
we will only add it to beta.nationalmap.gov.au
4:17
not for neii yet
4:17
because that is moving to beta as well

standalone keys for NEII and nationalmap reverted
