### ISSUE TITLE
Fix branding logo overlap on small screens

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#5299]
Sometimes branding will overlap buttons, and sometimes this makes buttons not clickable

Related to https://github.com/TerriaJS/terriajs/issues/4085

## Examples

![image](https://user-images.githubusercontent.com/6187649/109908774-f63f2880-7cf8-11eb-9836-412e98f154a9.png)

![image](https://user-images.githubusercontent.com/6187649/109908753-ed4e5700-7cf8-11eb-9dd6-d181f43c60ee.png)

![image](https://user-images.githubusercontent.com/6187649/109908757-efb0b100-7cf8-11eb-9395-8fdd617c26f2.png)

![image](https://user-images.githubusercontent.com/6187649/109908746-ea536680-7cf8-11eb-8749-18b7fc21432c.png)

![image](https://user-images.githubusercontent.com/6187649/109908762-f2130b00-7cf8-11eb-8e99-0bbb858260ff.png)

**Comment by philipgrimmett** [comment]
![IMG_1817](https://user-images.githubusercontent.com/5292858/111970291-3dc61100-8b4f-11eb-93e9-2498c519b749.jpg)

@wibily Another one that needs spacing love (and light logos for better contrast on dark background)

**Comment by wibily** [comment]
Still need to go through all the maps and verify that the displayOne property has been set, however this issue will be partially alleviated by https://github.com/TerriaJS/terriajs/issues/5361

**Comment by nf-s** [comment]
![image](https://user-images.githubusercontent.com/6187649/116050057-63988580-a6ba-11eb-9dbc-8f52250ba9bb.png)

Closed by https://github.com/TerriaJS/terriajs/pull/5434
