### ISSUE TITLE
Using share link breaks composite WMS basemap

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#5300]
Edit: looks like maybe it's not the basemap that has broken, it's actually Sharing that's broken, note how this NSW DT share also fails to send the layer name: https://nsw.digitaltwin.terria.io/#share=s-6v1PgDzBbKchHEo12QoVP98TaM5

When using e.g. the QLD Digital Twin and using the `QLD Aerial` basemap, this is what you see when you first go to the site:

<img width="1185" alt="Screen Shot 2021-03-04 at 3 44 56 pm" src="https://user-images.githubusercontent.com/5283003/109912642-9482bc80-7d00-11eb-8603-6dd40bd6496d.png">

If you then immediately create a Share URL for that map, e.g.: https://qld.digitaltwin.terria.io/#share=s-udlNRMEedgnpr3vdDj1JwwJ9GEX
Then you will find that the composite basemap is broken when you open the share URL:

<img width="1185" alt="Screen Shot 2021-03-04 at 3 46 00 pm" src="https://user-images.githubusercontent.com/5283003/109912718-ba0fc600-7d00-11eb-9f91-8fee9447db92.png">

If you look at the differences in map requests you find that when it's working the map tile URL's are:

https://qld.digitaltwin.terria.io/proxy/_0d/http://geoserver.nationalmap.nicta.com.au/imagery/natural-earth-ii/wms?transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&service=WMS&version=1.1.1&request=GetMap&layers=NE2_HR_LC_SR_W_DR&bbox=-15028131.257091932%2C-15028131.257091936%2C-10018754.171394622%2C-10018754.17139462&width=256&height=256&srs=EPSG%3A3857

When it's broken the URL is:

https://qld.digitaltwin.terria.io/proxy/_0d/http://geoserver.nationalmap.nicta.com.au/imagery/natural-earth-ii/wms?transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&service=WMS&version=1.1.1&request=GetMap&layers=&bbox=-20037508.342789244%2C10018754.171394622%2C-10018754.171394622%2C20037508.342789244&width=256&height=256&srs=EPSG%3A3857

Note how the `layers` param is empty.

**Comment by meh9** [comment]
I suspect that for composite items we only record the share url/item to load for one of them?

**Comment by meh9** [comment]
Actually, looks like all sharing in most recent v8 is broken, e.g.:

https://nsw.digitaltwin.terria.io/#share=s-6v1PgDzBbKchHEo12QoVP98TaM5

**Comment by nf-s** [comment]
Sharing was fixed in https://github.com/TerriaJS/terriajs/pull/5320 (in version 8.0.0-alpha.68) - I'm not sure what version NSW or QLD DT is running - but I think they don't have this fix yet

**Comment by nf-s** [comment]
I mean sharing in general was fixed - not shares with composite WMS basemap

**Comment by nf-s** [comment]
https://github.com/TerriaJS/terriajs/pull/5310 has fixed a few `AsyncLoader` bugs which were causing some share links to break - I haven't been able to test a composite basemap yet

**Comment by nf-s** [comment]
Basemaps haven't been working in shares for a while, this is now also fixed in https://github.com/TerriaJS/terriajs/pull/5310

**Comment by nf-s** [comment]
I have tested QLD: https://github.com/TerriaJS/qld-digital-twin/pull/247 and NSW: https://github.com/TerriaJS/nsw-digital-twin/pull/489

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/5310
