### ISSUE TITLE
Pedestrian mode: minor styling updates

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#5318]
Minor styling updates to improve interaction with base maps

**Camera movement controls**
```
background-color: #ffffff;
box-shadow: 0 4px 8px 4px rgb(0 0 0 / 5%);
border-radius: 3px;
```

**Mini map**
```
box-shadow: 0 4px 8px 4px rgb(0 0 0 / 5%);
border-radius: 3px;
```
Not sure about the CSS for this (maybe `border-box`?), but the mini map internal border should be 2px so it doesn't blend into the bing base maps (the combination of this and box-shadow should help with light/dark base maps as well)

![Screen Shot 2021-03-10 at 5 15 15 pm](https://user-images.githubusercontent.com/5292858/110586234-fbebb100-81c5-11eb-8101-27707288ede4.png)

**Comment by na9da** [comment]
Should be fixed by #5321. Please re-open if not.
