### ISSUE TITLE
Docs: Tell developers to not call load inside a load

### ISSUE THREAD

**Issue by KeyboardSounds** [TerriaJS/terriajs#5325]
TODO: fill this out properly

Due to how AsyncLoader works, it's a bad idea to call loadMetadata inside loadMapItems (or any similar nesting of load functions). Tell developers to avoid this.

**Comment by nf-s** [comment]
There are docs:
- https://github.com/TerriaJS/terriajs/blob/next/doc/contributing/model-layer.md#asyncloader
- https://github.com/TerriaJS/terriajs/blob/next/lib/Core/AsyncLoader.ts

And also in Mixins which use AsyncLoader:
https://github.com/TerriaJS/terriajs/blob/7efefad863f1e94c25288c481b874b368b52171d/lib/ModelMixins/MappableMixin.ts#L100-L108

https://github.com/TerriaJS/terriajs/blob/7efefad863f1e94c25288c481b874b368b52171d/lib/ModelMixins/GroupMixin.ts#L20-L31

https://github.com/TerriaJS/terriajs/blob/7efefad863f1e94c25288c481b874b368b52171d/lib/ModelMixins/CatalogMemberMixin.ts#L52-L58

**Comment by nf-s** [comment]
Merged into https://github.com/TerriaJS/terriajs/issues/5031
