### ISSUE TITLE
Highlighting boundaries - change colour to black

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#5340]
Hi, I'm really happy to see that the bug with highlighting the boundaries of selected areas has been fixed. Great stuff! Is it possible to change that "selected boundary" colour from white to something else? In the current prod version of National Map the colour is black. I find the new white boundary difficult to see on many of the provided basemaps.
Keep up the great work. I love what the team is doing with this service.

**Comment by nf-s** [comment]
Highlighting color now uses basemap contrast color
