### ISSUE TITLE
Fix interaction between story and pedestrian modes

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#5345]
- [x] **Keyboard:** For example, currently editing the story scenes might use some of the keys needed for pedestrian's movement. 
- [ ] **Sharing** the story when pedestrian mode is active needs clarification for user: i.e. when in Story describing the landmarks of a city, the user should be able to "tour" the city, by activating Pedestrian mode, and then, get back to Story - next scene. It was discussed that even a prompt could be useful to try the pedestrian while on Tour / Story mode.
- [ ] When opening a share link with story, the initial prompt to open the story was not being shown sometimes. Check why it is happening.
- [ ] When capturing scenes in pedestrian mode and playing it back, it captures the first location correctly, but location for subsequent scenes appears to be wrong.

**Comment by wibily** [comment]
parts of the ticket that have not been done to be split out into other tickets and thrown onto the product backlog @na9da

**Comment by na9da** [comment]
1. Fixed by #5506 
2. I think we decided to drop this because we didn't have a concrete use case
3. Failed to repro the problem in the latest branch
4. Failed to repro the problem in the latest branch

**Comment by na9da** [comment]
Also I need to resolve conflicts in https://github.com/TerriaJS/terriajs/pull/5436 and get @steve9164 to merge it.
