### ISSUE TITLE
Problems rendering CZML in Leaflet

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#535]
Since Leaflet doesn't seem to support all CZML features it would be good if NM popped up a warning when a CZML layer was turned on. In our case nothing is displayed for a layer we have made, and it may be confusing for the user.

**Comment by kring** [comment]
@meh9 the goal is for Leaflet to support all features.  If you find something missing can you write a bug for that?

**Comment by axman6** [comment]
We've got two files which either don't work at all or have some features missing. The first is one we've created which only shows polygons whose colours change over time; nothing at all shows in the 2D map view. https://github.com/NICTA/aremi-natmap/blob/master/public/datasets/dance/DANCE-2012.min.czml

The other has some features that work and some that don't: http://cesiumjs.org/Gallery/BAMS_C4ISR.czml.

If this should be a new ticket let me know and we'll move the discussion there.

**Comment by kring** [comment]
Ok, we'll check it out, thanks.  No need for a new ticket, I'll just change the title of this one.

**Comment by kring** [comment]
I opened pull request #563 to make the polygons in DANCE-2012 render in Leaflet, and also fixed at least one of the problems in BAMS_C4ISR (access lines that appear when objects can see each other in this demo don't update once they're created).

I also wrote issue #564 to implement the remaining entity graphics that are not supported in the Leaflet visualizer in National Map, but most of this is pretty low priority at the moment I'd say (but correct me if I'm wrong).

**Comment by meh9** [comment]
You are not wrong, it's low priority.
