### ISSUE TITLE
Split/Compare function non-functional

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#5370]
The Split/Compare functionality has broken in v8, it no longer creates a second copy of the layer so you can't actually currently compare two different times.

When clicking Compare on the layer as below:
<img width="210" alt="Screen Shot 2021-03-26 at 15 53 06" src="https://user-images.githubusercontent.com/5283003/112584139-5bdf8a00-8e4b-11eb-8dd2-eaea8aedea67.png">

It turns on the splitter, but it does not create the second copy layer to compare with:
<img width="1220" alt="Screen Shot 2021-03-26 at 15 53 31" src="https://user-images.githubusercontent.com/5283003/112584170-6bf76980-8e4b-11eb-8e3e-fef6ac4af9c8.png">

When doing the same in a v7 map we get a layer copy:
<img width="504" alt="Screen Shot 2021-03-26 at 15 54 40" src="https://user-images.githubusercontent.com/5283003/112584245-9517fa00-8e4b-11eb-8a25-038e04183776.png">

**Comment by nf-s** [comment]
This is fixed in https://github.com/TerriaJS/terriajs/pull/5310

**Comment by nf-s** [comment]
closed by https://github.com/TerriaJS/terriajs/pull/5310
