### ISSUE TITLE
Consolidate naming for Mixin instance type

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#5374]
At the moment we have about 90% of Mixins using `XMixin.XMixin`:
```ts
namespace TableMixin {
  export interface TableMixin
    extends InstanceType<ReturnType<typeof TableMixin>> {}
  export function isMixedInto(model: any): model is TableMixin {
    return model && model.hasTableMixin;
  }
}
```

and 10% using `XMixin.Instance`:
```ts
namespace TileErrorHandlerMixin {
  export interface Instance
    extends InstanceType<ReturnType<typeof TileErrorHandlerMixin>> {}
  export function isMixedInto(model: any): model is Instance {
    return model?.hasTileErrorHandlerMixin;
  }
}
```

Note that removing the mixin name from the instance type name shouldn't make IDE types worse as the namespace is still displayed:
![image](https://user-images.githubusercontent.com/13863530/112802614-1d053a80-90be-11eb-8b31-70442e61bed7.png)

We should decide on a naming scheme, document it and apply it universally. I prefer `XMixin.Instance` because it's more descriptive. It's the instance type of XMixin

**Comment by nf-s** [comment]
I like `XMixin.Instance` over `XMixin.XMixin`

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/5661
