### ISSUE TITLE
Not removing selected geometry overlay after remove all layers

### ISSUE THREAD

**Issue by zoran995** [TerriaJS/terriajs#5381]
Steps to reproduce
- Add WMS layer with lines or polygons
- Select one object on the map, it will get a white geometry overlay
- Remove all layers from the map (using remove all button
- Information from getFeatureInfo panel is removed but geometry overlay is still visible on the map.

Removing the layer using its own remove correctly removes geometry overlay 
![image](https://user-images.githubusercontent.com/19208948/112965555-a877dd80-9149-11eb-980e-49d898484c9a.png)

**Comment by lstillwe** [comment]
I am experiencing this same issue. Has anyone found a solution? Thanks!

**Comment by nf-s** [comment]
I made a PR to fix the issue, sorry it took so long!

- https://github.com/TerriaJS/terriajs/pull/6930
