### ISSUE TITLE
Enable choosing of basemaps that are available

### ISSUE THREAD

**Issue by zoran995** [TerriaJS/terriajs#5382]
After playing around with basemaps and checking the #5366. We probably should do some changes to the basemap model:
- change the name of the array `baseMaps` to `baseMapCatalog` or `baseMapItems`
- add an array basemaps which will say which basemaps should be available to the user (similarly to how workbench property works)
- in this case default base maps list should be merged in the baseMapCatalog so the user doesn't have to redefine it in catalog file, but also can provide another one with different id and say use this one.

**Comment by tephenavies** [comment]
I like this solution. It's also important for someone to be able to remove base maps they don't want to have that might come in the default set and also to override thumbnails used.

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/5644
