### ISSUE TITLE
Upgrade to mobxjs v6

### ISSUE THREAD

**Issue by zoran995** [TerriaJS/terriajs#5385]
What is the opinion of terriajs team regarding an upgrade to the latest version of mobx 6. There are some breaking changes that would need to be taken care of, but it is becoming a lot harder to find examples that use an older version of mobx.
We might try to use `mobx-undecorate` as a starting point for this

**Comment by nf-s** [comment]
@na9da has started https://github.com/TerriaJS/terriajs/pull/5904

**Comment by pjonsson** [comment]
Did #6687 address this issue?
