### ISSUE TITLE
Add a "loading/working..." indicator

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#539]
Some layers can take a while to load, it would be very nice to have a "loading..." spinner in a corner somewhere (probably best not showing it in the middle of the screen) showing that things are still happening. 

This would be particularly nice for WFS layers where we don't even get individual tiles loading showing there is progress, there is just nothing for a long period until everything is drawn all at once.

**Comment by kring** [comment]
@philipgrimmett can you suggest a design for this?  It's possible to show a per-dataset loading indicator, or a global one.

**Comment by meh9** [comment]
Ooh nice, a per dataset indicator would be awesome.

From watching Cesium render datasets it seems to me that it requests tiles
from all datasets for a given square on the globe and waits for them to
finish downloading and rendering before moving to the next square. If this
is the case, wouldn't all datasets essentially finish at the same time?
(Having no idea how Cesium works internally this has just been a general
observation and might be totally wrong.)

**Comment by kring** [comment]
Well, it's not supposed to work like that. :)

Cesium requires that a given terrain tile have _some_ representation of every layer that is supposed to be drawn on that tile, before it will draw that tile.  But a lower-resolution parent imagery tile is good enough.  So when one layer is slower than the others, those others will finish loading and be displayed before the slow one finishes.

You can clearly see this by turning on, say, Ballarat BBQs, and click on it to zoom in.  The detailed Bing Maps imagery appears quickly, but it takes a little longer for the giant red blob to be replaced with individual BBQ points.

**Comment by hilarycinis** [comment]
we also need to work out where this should go - in catalog or larger part of screen ie a cog.

**Comment by axman6** [comment]
Personally I'd like to see this on a per dataset basis; if you turn enough things on you're just going to have the spinner working constantly to show _something_ is loading. Having one indicator per layer will probably mean that zoom changes mean everything visible will show that it is loading and may look somewhat busy, but I think that may be a good thing, because it shows that the software is actually doing something when it's taking a while to load slow layers. Takes the typical interaction from "Urgh, I've zoomed in and this thing is super slow, why is it taking so long to load" to "Ooo, look how much work it's doing, I guess that could take a while" - at least in my untrained UX opinion =)

**Comment by axman6** [comment]
An alternative interface would be a piece of text that says "Loaded n of N layers"; possibly over the map in the top left corner.

**Comment by philipgrimmett** [comment]
Re. global: If we are constantly loading data, I think we'll need a fairly unobtrusive loading bar/spinner animation. One example would be the safari/medium.com approach of running a progress bar (line?) at the top of the screen (sorry about the gif):
![nm-loader-global](https://cloud.githubusercontent.com/assets/5292858/7744714/f615ce1a-ffe8-11e4-9e0e-de971921ec02.gif)

**Comment by hilarycinis** [comment]
Thats a really nice solution Phil. In line with standards and discrete. Great idea.

**Comment by stevage** [comment]
Yeah, it looks good. It may be tricky to estimate how much data we're getting in some cases, and I'm not sure how it should display for a time-dynamic layer, where we keep fetching new images. I don't think it matters too much if the proportion isn't entirely accurate, as long as it's moving...
