### ISSUE TITLE
CkanCatalogGroup should create one member per dataset

### ISSUE THREAD

**Issue by mwu2018** [TerriaJS/terriajs#5404]
Take the following ckan group dataset as example.
```
{
        "type": "ckan-group",
        "name": "Catchment Scale Land Use",
        "id": "99fc7473",
        "url": "http://www.data.gov.au",
        "filterQuery": [
          {
            "fq": "+(res_format:(wms OR WMS)) organization:abares ACLUMP"
          }
        ],
        "groupBy": "none",
        "supportedResourceFormats": [],
        "shareKeys": [
          "Root Group/Renewable Energy/Bioenergy/National/Catchment Scale Land Use"
        ]
}
```

The ckan query will return 3 datasets but 4 members will be created with one being of GeoJson format that is not well supported at the moment.

**Technical Note**
The above problem occurs because one of dataset has both WMS and GeoJson formats. The method `createMemberFromDataset` finds that both formats are being supported hence creates one member for each format. The `CkanItemReference` should list the supported format in preference order (high to low). `createMemberFromDataset` should only create one member for the first found supported format.

**Comment by nf-s** [comment]
This can now be configured using the `onlyUseIfSoleResource` trait - and setting it to `true` for all resources except the highest priority resource

https://github.com/TerriaJS/terriajs/blob/af97be4dcb86ab6264aa46cf5737e7986426e58e/lib/Traits/TraitsClasses/CkanResourceFormatTraits.ts#L39-L44
