### ISSUE TITLE
Figure out when we should use the sld_version parameter for WMS services

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#5410]
There are certain WMS services that insist that an `sld_version` is sent or else it will not return a legend image:

https:/mrdata.usgs.gov/services/ofr20051294?service=WMS&version=1.3.0&request=GetLegendGraphic&format=image%2Fpng&layer=ofr20051294

When using this WMS service on v8 we get the data fine, but no legend:

https://beta.nationalmap.terria.io/#share=s-u85StoOCulf4BZ927K0vdMds1Pn

When we do it on v7 we do get a legend, because there we use the `sld_version` param:

https://nationalmap.gov.au/#share=s-A6O065xoWBTczBQk5zV1S2deSPV

The commit where we added that param to v7 is here:

https://github.com/TerriaJS/terriajs/pull/1096/commits/94a07708fc91cafe9838076057a76b5a1fc21a96

We should port across the ability to include that param to v8.

**Comment by hardreddata** [comment]
Perhaps https://github.com/georchestra/georchestra/issues/636#issuecomment-45887493

**Comment by nf-s** [comment]
Fixed by https://github.com/TerriaJS/terriajs/pull/6173
