### ISSUE TITLE
Allow upsertModelFromJson to return a full result, a partial result with a message or an error

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#5415]

**Comment by tephenavies** [comment]
In order to display better error messages for catalog JSON `upsertModelFromJson` must be able to pass details about the error it encountered up to the calling scope which can decide what to do with that.

**Comment by nf-s** [comment]
Added in:

- https://github.com/TerriaJS/terriajs/pull/5440
- https://github.com/TerriaJS/terriajs/pull/5429
