### ISSUE TITLE
UX: Review errors raised to users - what user problems do we want to solve in writing a better error handling system

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#5416]
As the v8 error system is new, we need to review the errors.
The purpose of this ticket is to run the possible errors to UX and then to decide what to do with those errors instead (ie show or not show).

Requires a dev to come up with a list of all possible errors.

**Comment by hardreddata** [comment]
On our Terria instance We get a lot of "please report this by emailing (me). Details of the error are shown below"

This mostly happens if some external source is not behaving and there is nothing I can do to assist.

**Comment by wibily** [comment]
Jacky: suggestion to show responsible system (e.g. remote datasoft) and possible course of action.

**Comment by t83714** [comment]
Just some idea to share (I am actually doing something similar for magda's map preview module [here](https://github.com/magda-io/magda-preview-map/issues/14) and [here](https://github.com/magda-io/magda/issues/3178)).

The approach I used might be a bit tricky (as I want to avoid changes in terraijs) but might be a good example to show what we want to achieve to minimise unnecessary inquiries from (less technical) users.

So the idea is to capture most errors (that I am interested in) here (and send back via postMessage):

https://github.com/magda-io/magda-preview-map/blob/fa0ebae03ce0142c86e4b32823d7c444e515e26f/lib/Models/MagdaCatalogItem.js#L762

And then at client side, I will do some error message detection (by keyword matching) and insert more explanation (for less technical people):

https://github.com/magda-io/magda/blob/fe0fa2645d38ce2162e8cb75db01a6d472061047/magda-web-client/src/Components/Common/DataPreviewMap.tsx#L361

**Comment by AnaBelgun** [comment]
We have done a review and came up with new/updated messages for 3 major groups of errors: https://github.com/TerriaJS/terriajs/issues/5459
