### ISSUE TITLE
Stop importing full lodash module

### ISSUE THREAD

**Issue by na9da** [TerriaJS/terriajs#5417]
Stop importing full lodash modules. In some places we unknowingly import the full lodash module instead of an individual function like `lodash/minBy` . This adds around ~450kb which creates a delay of ~200msecs in the initial load. I think this an easy mistake to make. We could use something like [eslint-plugin-lodash](https://www.npmjs.com/package/eslint-plugin-lodash) to help us catch this mistake.

**Comment by na9da** [comment]
Following suggestion from @steve9164, I think the best way to optimize `lodash` imports will be to use [webpack resolve](https://webpack.js.org/configuration/resolve/#resolvealias) to alias all `lodash` imports (including our dependencies) to `lodash-es`.

~`lodash-es` uses es6 modules and are tree-shakeable by default, so we wont have to use any other babel plugins.~ Tree shaking is not working on our builds, so we still use `babel-plugin-lodash` for automatically using granular imports.

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/5430
