### ISSUE TITLE
PHB ticket of the week: please fix "Cameron Corner" of the Story panel

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#5423]
The Story display panel at the bottom of the screen has some alignment issues in one of the corners:

<img width="187" alt="Screen Shot 2021-04-13 at 16 56 39" src="https://user-images.githubusercontent.com/5283003/114638458-fe827e80-9d0e-11eb-8ef3-d62f88ad3751.png">

We should fix this so the lines align.

**Comment by staffordsmith83** [comment]
I think this issue is resolved?

**Comment by meh9** [comment]
Yes, now fixed since the restructure of the story panel.
