### ISSUE TITLE
Story v2.0 - Mobile - improve interaction on mobile devices

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#5427]
Example: https://maps.dea.ga.gov.au/#share=s-DEACoastlines&playStory=1 

Another issue we had with the DEA Coastlines story was that Terria currently seems to show different zoom level depending on the size of the screen the story is viewed on. For example, the DEA Coastlines layers have zoom-dependent symbology that transition at certain zoom levels. If a story is created on a large screen, but then viewed on a smaller screen (i.e. laptop or mobile), the difference in zoom levels causes different layers to show up than was originally intended (e.g. points showing when annual coastlines are described in the story scene text).

Check: 

- [x] missing arrow to go to next story scene
- [x] text modal covering the map almost entirely

**Comment by AnaBelgun** [comment]
Update 7 Jan 2022: 
@philipgrimmett we need to connect this issue to the design pages/sections addressing at least those 2 problems above..

**Comment by philipgrimmett** [comment]
Updated Figma prototype:

https://www.figma.com/file/jtdgEiY0gxtZlGtxSJTzcZ/Terria---2022?node-id=9115%3A34756

**Notable changes**
- Bottom aligned story navigation: _prev, scene menu, exit, next_
- Scrollable panels, allowing partial map view: _feature info, scene menu, data workbench_
- Floating data workbench button (bottom left)
- Updated workbench (same layout as desktop)
- Merged Map tools, prioritised for mobile: _geolocate, share, overflow menu_
- Dark theme (to discuss: light theme)

**Next steps**
- Review with team to identify edge cases, development issues etc
- Walk through prototype with 2-3 story authors (internal, GA?), capture feedback

**Comment by AnaBelgun** [comment]
@philipgrimmett it looks great. few comments: 
- when opening a story on mobile, I found useful to have a small notification letting you know there is a story and actionable options i.e. continue/not. In this version, would that be replaced by the Story play button bottom left corner? 
- looove the fact you can collapse the story scene to see the actual map; really annoying atm you can't do that

**Comment by wibily** [comment]
meeting tmr with Phil, Will & ana

**Comment by wibily** [comment]
Meeting with Phil, Ana & Will
- Story to be collapsible as per attached design
- Bottom bar to be refactored to the controls (attached design)
- ideal zoom icon to be at the bottom bar

- Menu button to pop up a list of screens
- long headings should expand to two lines of text but anything after that will be ellipses
- empty bodies should appear like they are collapsed
- collapse view should persist between different stories
- next button to turn into restart button at the end of the list of stories

undecided:
tension between empty bodies and going next to a story with a body

Stretch goal:
colors

**Comment by philipgrimmett** [comment]
Updated Figma concepts based on design compromise:

Desktop
https://www.figma.com/proto/0IrsjWUaA3QPYPNtDcoiNr/Terria---Stories---Compromise----Feb22?page-id=0%3A1&node-id=1%3A421&viewport=241%2C48%2C0.66&scaling=min-zoom&starting-point-node-id=1%3A421

Mobile
https://www.figma.com/proto/0IrsjWUaA3QPYPNtDcoiNr/Terria---Stories---Compromise----Feb22?page-id=0%3A1&node-id=4%3A1924&viewport=241%2C48%2C0.66&scaling=min-zoom&starting-point-node-id=4%3A1924&show-proto-sidebar=1

**Inspect link**
https://www.figma.com/file/0IrsjWUaA3QPYPNtDcoiNr/Terria---Stories---Compromise----Feb22?node-id=1%3A421

**Terria icon library**
https://www.figma.com/file/P5kHwUa4J1Zl7HAspf9sC9/Terria-Library---Icons?node-id=0%3A1

**Behaviour notes:**
- Clicking menu button on desktop should dismiss story player and open story editor
- Scenes without body content should appear collapsed with the 'info' button disabled (0.1 opacity)
- If story player is manually collapsed by the user, respect that state until it is manually expanded again

**Prototype notes:**
- Mobile: feature info example can be triggered by clicking on the map
- Mobile: scene list example can be triggered by clicking the menu button

**Comment by wibily** [comment]
note: fix ideal zoom z-index showing up below story prompt

**Comment by wibily** [comment]
note: was not able to create dark theme nor was i able to create the story switcher element at the bottom. I have instead opted for a static {current story} / {total stories} display

**Comment by wibily** [comment]
also the alignment of the icons and the text is not perfect. Two line clamped header was implemented though
