### ISSUE TITLE
"Expanding" a chart data series sometimes replaces already active series

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#5443]
For some datasets that show a data series preview in the Feature Info with the Expand to chart button, clicking the Expand button on two different features should and do results in two lines being shown on the chart, but for some datasets the new series replaces the existing one - this means you can't compare the data series.

When clicking two different features and then Expand on both this is what should happen (using this share url: http://maps.dea.ga.gov.au/#share=s-dpkQ6bw0QzUdhNk83TuoCmIieKL):

<img width="1920" alt="Screen Shot 2021-04-22 at 18 38 46" src="https://user-images.githubusercontent.com/5283003/115684112-6c2b4c00-a39a-11eb-8cd5-85ddb36e409a.png">

However, for other datasets Expanding a second data series replaces the first one (using this share URL: http://maps.dea.ga.gov.au/#share=s-6rPSUJPy61Cf8szBAUgVSxEe3lx):

<img width="1920" alt="Screen Shot 2021-04-22 at 18 39 46" src="https://user-images.githubusercontent.com/5283003/115684495-bf9d9a00-a39a-11eb-9197-01117366d138.png">
<img width="1920" alt="Screen Shot 2021-04-22 at 18 40 00" src="https://user-images.githubusercontent.com/5283003/115684629-dba13b80-a39a-11eb-8693-5a0920c8a9f7.png">

Both datasets should show up on the chart together for comparison.

**Comment by nf-s** [comment]
This is an issue with SDMX #3524 also

**Comment by nf-s** [comment]
No longer the case - https://maps.dea.ga.gov.au/#share=s-nX2Uf0IL3OGbLL7y5QR3ImuabLK

<img width="1723" alt="image" src="https://user-images.githubusercontent.com/6187649/182608189-52af7325-96b5-4ba1-8dcb-88e324f25bfd.png">
