### ISSUE TITLE
Better handling of time series visualisation 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#5470]
Some of the issues with time series visualisation are related to missing / sporadic values. 
Here is an example: 

Data sparsely spread in time so there is only one or two countries with data for a given year. I.e for Sustainable Development Goal indicators such as 1.1.1 pop Below Poverty Line https://map.pacificdata.org/#share=s-x6i3YkaMgkAx4Pj3whq4UtKYB1z. 

2005: 
![image](https://user-images.githubusercontent.com/18452161/117085205-7f6feb80-ad8c-11eb-8837-8a4c57fa533d.png)

2006: 
![image](https://user-images.githubusercontent.com/18452161/117085215-8991ea00-ad8c-11eb-87d7-1d1990ea6eb4.png)

2008: 
![image](https://user-images.githubusercontent.com/18452161/117085237-944c7f00-ad8c-11eb-906a-ebddf888b950.png)

Possible solution: Only display most recent value for each country (no matter what the year) and disable time series.

**Comment by AnaBelgun** [comment]
@nf-s is this done by the merge or partially done?

**Comment by nf-s** [comment]
Only partially. I only fixed this for points, but it will be easy to fix for region mapping now

**Comment by wibily** [comment]
same as terriajs #5213
