### ISSUE TITLE
MapServer group infinite loading

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#5483]
Type "esri-mapServer-group" tries to load infinitely many times while the group is expanded. When the first request returns the group is created with children that work however AsyncLoader is not correctly caching the load and something is causing the AsyncLoader to be called infinitely.

**Comment by AnaBelgun** [comment]
When adding https://portal.spatial.nsw.gov.au/server/rest/services/NSW_Features_of_Interest_Category/FeatureServer the loading spinner never stops
![image](https://user-images.githubusercontent.com/18452161/117914308-6afc9780-b326-11eb-9b47-c2b69085c1fe.png)

Could be related to this: https://github.com/TerriaJS/terriajs/issues/5041 but it needs investigation.

**Comment by nf-s** [comment]
Closed by #5535
