### ISSUE TITLE
Data catalogue tabs break layout on mobile

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#5486]
Tested on:
iPhone 11, iOS14.4.2

Screenshot:
map.drought.gov.au

Impact: 
13.21% of all users between May 1 2020 - May 21 2021 accessed the drought map on an iOS device

![IMG_1907](https://user-images.githubusercontent.com/5292858/117918484-6fc54980-b32e-11eb-8a0a-b9578f4080aa.PNG)

**Comment by tephenavies** [comment]
Possibly caused by a mismatch in managing the state of the explorer window between ViewState and react-router

**Comment by tephenavies** [comment]
Fixed in https://github.com/TerriaJS/terriajs/tree/recreate-prerendering. The next drought map release shouldn't have this problem.
