### ISSUE TITLE
Printing v2.0 - development

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#5490]
This captures the designs for improving the printing functionality. 
It should start with these acceptance criteria: 

- [x] cleaner map print preview  - currently the preview include too much text, not nicely formatted and arranged on the page
- [x] options to hide some sections if not relevant

**Comment by wibily** [comment]
this ticket is only for the design

**Comment by wibily** [comment]
implementation by august

**Comment by philipgrimmett** [comment]
### Design concept
https://user-images.githubusercontent.com/5292858/125239339-dfa28100-e32b-11eb-8b9f-643cfacae0b1.mov

### Change log
**Share panel**
Updated print preview button

**Map legends**
Appended time to dataset title

**Map image**
Added north arrow
Added scale
Added timestamp
Added share link (to discuss)

**Metadata**
Added metadata download options

Ping @AnaBelgun

**Comment by wibily** [comment]
@philipgrimmett looks good!
I have a few thoughts though
1) would we be able to expand out all the accordions and move the buttons out of the print preview? In my mind, what we provide in the print preview should be what comes out of the printer
2) we need a way to exit from the print preview mode
3) it might be nice to add a print button as a convenience

**Comment by AnaBelgun** [comment]
@philipgrimmett looks good, thank you. One other thought was is there an elegant way to hide/unselect items users wants to include in the print /preview; for example some would want to add the metadata in case it's nice, clean and short; in other cases, when it's too complicated, not; giving the choice to add or hide such things would be great

**Comment by philipgrimmett** [comment]
Thanks @wibily @AnaBelgun, comments below:

>1. would we be able to expand out all the accordions and move the buttons out of the print preview? In my mind, what we provide in the print preview should be what comes out of the printer

'Print preview' might be a little misleading here; one of the main issues with the current print implementation is information overload, where junk metadata properties are expanded by default. Better typography won't fix that, so I think our best option is to collapse properties by default and provide an 'expand/collapse' all option. I've tried to find a middle ground where the client can expand some/all properties and print to PDF directly from the browser (retaining an active share link) or alternatively just grab the ingredients they need (map image + select metadata) to quickly compile a report (with timestamp and share link to retain data provenance) with custom formatting.

@AnaBelgun I'm a bit concerned that building a system to selectively hide metadata will add more work and be less flexible for the client in the long run. We could consider adding a quick copy button for each property, but depending on the amount of metadata they want to capture it would probably still be faster to download a CSV or Word doc.

>2. we need a way to exit from the print preview mode

Not communicated in the prototype, but print preview should launch in a new tab (current behaviour)

>3. it might be nice to add a print button as a convenience

Yep, done. Are we able to hide all download buttons in the final print view?

**Comment by AnaBelgun** [comment]
@wibily is presenting the items under metadata with a select/unselect button difficult to implement? 
I'm concerned that having the entire metadata shown in the print preview without an option to get rid of the non-relevant sections (which can be different, for different users) it misses the point of having the print view/preview clearer and cleaner (if the user wants to use it as is: i.e as a printed version of the map view)

**Comment by wibily** [comment]
Selectable sections to print should be fine as long as the process is to get to the browser default print preview page. Downloading straight to pdf from a browser as a file is a bit of a nightmare

Note to self: print media query to add/remove class for display:none

**Comment by philipgrimmett** [comment]
For reference, this is what it looks like if you expand all properties for just the first dataset (place names). 

![terria-printMetadata](https://user-images.githubusercontent.com/5292858/126103002-5bffe162-0439-494e-9c77-7c3c8249d45f.png)

Once you're dealing with multiple datasets, what are the pros/cons of selecting properties to print from the browser instead of  exporting or copy/pasting into Word, where you have more control over presentation?

**Comment by AnaBelgun** [comment]
I see; I think we need to have a refinement chat

**Comment by zoran995** [comment]
When I think about printing dataset metadata it would be a valid option from catalog, but not from map view. I think it will go out of control pretty quickly. Also I am not aware of any other web gis that print dataset metadata.

Even legend will be tricky when dealing with larger number of datasets or land cover ones just because size of image (surface geology has legend on 4 pages). @AnaBelgun I would think about moving a legend entirely to second page, with option to enable disable legend. We probably should request new legend image when printing (where possible to enhance it). Geoserver has pretty nice option ~~(since 2.15)~~ to break a legend in columns (`columns` and `columnHeight` in `legend_options`), not sure if esri has something similar or it returns json legend.

One feature that would be nice for users is having a qr code to open map share url in browser, that way live metadata is available.

**Comment by AnaBelgun** [comment]
thank you @zoran995; the use case we're trying to solve is using the print preview for briefings and reports. Some users currently use a combination of tools to get to a page where they have all the items 'arranged'. What they show on that page: 
- map image (with one or more layers)
- legend
- some metadata 
- title of report 

hence why I thought to manage the metadata being too long one way is to select what you want to include in the print preview.

**Comment by philipgrimmett** [comment]
Thanks @zoran995 @AnaBelgun 

Yep, refinement sounds like a good idea. Re. management of legends in the map preview: there are times where it's valuable to show dataset titles but not the legends themselves e.g. local government areas, surface geology (notoriously inaccessible for humans, requires interaction/filters). We could address this by providing overlay controls for collapsing/removing legends from the map preview (concept below)

![Screen Shot 2021-07-20 at 11 56 57 am](https://user-images.githubusercontent.com/5292858/126252250-852ab31f-e35b-46dc-bc6c-8c328271beac.png)

**Comment by zoran995** [comment]
In that case, I would probably go with a chosen metadata subset, and keep it simple as much as possible i.e. 
Dataset title - dataset type
description
contact information in the table form
extents in the table form

But I expect most user would like this is some editable format so they adapt it for their document, or to have it prepared as attachment, at least that would be case with our users. Just looking into future usability and what users might expect.

Also as an idea split printing into 2 parts one basic with only map and legend as general use functionality (with qr code), and second advanced combination of basic with metadata and other data (second can then also be used in catalog to print specific dataset info)

**Comment by AnaBelgun** [comment]
Update 26 Jul 21: 
- @wibily to create wireframes with option 1 - CSS based solution; option 2 - HTML extension of current print 
- @philipgrimmett to update invisio designs based on wireframes

Notes: 
- separate download map image from print and have 2 distinct options under Share tab: Print and Download Image 

**When selecting Print:**
- overt the map image, show North and scale 
- accompany map image with legends (beside) 
- ideally allow to expand / collapse metadata items for each data set under the map image and legends 
- consider users wanting to screen shot the top part of print page (legends and map); hence allow enough white space on margins
- consider users wanting to print as is: map image, legends, some metadata; hence pay attention to scaling on page 

Questions: 
- can a title be added before printing?
- what happens with Feature Info? - currently is captured if opened
- if the location search bar has a location typed, and map zoomed into, can that location / search bar be available in the print?

**Comment by wibily** [comment]
@philipgrimmett 
wireframes for option 1
Key idea is that we are adding/removing CSS classes to enable/disable visibilty for printing for different elements of the UI

![untitled_page](https://user-images.githubusercontent.com/4196561/126947860-ba7dbdca-22f7-46b7-bdf6-77c3969b870c.png)
![untitled_page_1](https://user-images.githubusercontent.com/4196561/126947872-a9cd1b6a-37da-4bbe-ab13-22fd613b52d7.png)

**Comment by AnaBelgun** [comment]
hi @philipgrimmett is it possible to post here the link to the latest designs in invision please? I need to confirm with Krystal (product owner) the latest designs. Thank you.

**Comment by AnaBelgun** [comment]
Invision link: 
https://invis.io/KG11FLQYM59X#/455107523_share_1

**Comment by AnaBelgun** [comment]
Update 8 Sep 2021: 
From drought map team: This looks great and it meets all the requirements.

**Comment by wibily** [comment]
no need to merge back into terriajs-droughtmap branch as routing will be implemented in normal terriajs and can just upgrade terriajs version in droughtmap

**Comment by wibily** [comment]
MVP:
- Focus is on getting physical printing working first
- catalog items with legends rendered nicely on the left
- scale
- collapsible dataset descriptions at the bottom
- no compass, export dataset options or conditional printing

**Comment by wibily** [comment]
Todo:
- [ ] Initial popup blocker stops initial showing of print view
- [x] Show print view button does not work if the print view window is still open
- [x] QR code library has size limits - QR library removed
- [x] Legend does not scale correctly with the image
- [ ] Compass is missing
- [x] Legends are not aligned with the map
- [] Map image, CSV/JSON download buttons are missing
- [ ] Dataset checkbox/Collapse controls are not yet implmented
- [ ] Elements are overall not styled correctly
- [ ] Time formating not great
- [ ] Share link does not regenerate correctly

**Comment by wibily** [comment]
Looks good!

A few small things - I realise this is not the final version - so feel free to respond to them in another PR:

1. Time format is not great
2. Dealing with scale in 3D mode is hard, not sure how best to do it. In this example the camera angle is quite low, so scale will change a lot from bottom of the map to the top. Maybe it is better to not show a scale if there is large variation across the map?
3. There are some `Collapsible` caret icon things missing here
4. The share link doesn't update when you re-generate the Print view if there is an existing window

![Screen Shot 2022-01-25 at 1 38 23 pm](https://user-images.githubusercontent.com/6187649/150900946-69d2f4e7-c535-42ae-bc48-b0d3d125b5c3.png)

Other things 

- general typography things (multiple fonts, spacing...) - not my area of expertise

_Originally posted by @nf-s in https://github.com/TerriaJS/terriajs/pull/6099#pullrequestreview-861728345_

**Comment by AnaBelgun** [comment]
@philipgrimmett please have a look at the latest version of Print using this test link: http://ci.terria.io/main/

- in the print preview appears "down" (top right corner of the page). Is that intentional? 

![image](https://user-images.githubusercontent.com/18452161/151719358-ddc92420-7f71-45ed-809d-a9a75910b5f5.png)

- collapsible icons: they work well, but is not very obvious they are collapsible 
- branding (name and logo) - although, the print preview retains the information about the source very well, shall we keep the logo and name at the top of the page as well for clarity or simpler is better in this case?
