### ISSUE TITLE
2D map disappears after changing basemap

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#550]
1. Load nationalmap.nicta.com
2. Click Maps > 2D
3. Click any basemap
4. Map area turns grey, map fails to appear. (Blue highlight remains around original basemap)

Happens every time on my machine (Chrome 0.0.2214.111, Macbook Pro mid 2014, Intel Iris, Mavericks)

**Comment by kring** [comment]
Thanks @stevage.  I broke this 10 days ago (without realizing it).  I just opened a pull request to fix it.
