### ISSUE TITLE
ArcGIS MapServer TilesOnly not supported

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#5500]
MapServer has (AFAIK) a WMTS-like tiles endpoint. Sometimes a MapServer layer only supports the tiled API, not export as is currently used by Terria. This has been observed for datasets served from https://tiles.arcgis.com.

We should add support so we can continue to support easily adding datasets hosted by ArcGIS.

**Comment by nf-s** [comment]
So I think part of the reason this confused me was that CesiumJS actually handles this with it's `ArcGisMapServerImageryProvider`, namely the `usePreCachedTilesIfAvailable` property, which Terria is leveraging.
https://github.com/TerriaJS/terriajs/blob/main/lib/Models/Catalog/Esri/ArcGisMapServerCatalogItem.ts#L475-L486

It's just a bit obscure, and needs a fairly detailed understanding of how Esri MapServers & Cesium & Terria work. So maybe there is a better way by implementing a `ArcGisTiledMapServerCatalogItem`?

_Originally posted by @rowanwins in https://github.com/TerriaJS/terriajs/issues/6161#issuecomment-1048465776_

**Comment by nf-s** [comment]
Maybe the other distinguishing thing is that you potentially have a different set of traits? Of the [`ArcGisMapServerCatalogItemTraits`](https://github.com/TerriaJS/terriajs/blob/main/lib/Traits/TraitsClasses/ArcGisMapServerCatalogItemTraits.ts) only the `tokenUrl` is relevant to tiled services, the rest like `parameters`, or `layers` are irrelevant.

_Originally posted by @rowanwins in https://github.com/TerriaJS/terriajs/issues/6161#issuecomment-1049240630_

**Comment by nf-s** [comment]
## Current state

We **do** support tiles only, but only if no `layers` are defined:

https://github.com/TerriaJS/terriajs/blob/de7b97b68fb13b8559e0bc276bfc8eb206867042/lib/Models/Catalog/Esri/ArcGisMapServerCatalogItem.ts#L475-L486

In `cesium`, it is handled like so (`usePreCachedTilesIfAvailable` maps to `_useTiles`)

https://github.com/TerriaJS/cesium/blob/1fd27c5d7c9e542abf83bf9e9fd900b9468d9b69/Source/Scene/ArcGisMapServerImageryProvider.js#L443-L452

```js
  if (imageryProvider._useTiles) {
    resource = imageryProvider._resource.getDerivedResource({
      url:
        `tile/${level}/${y}/${x}` +
        (Object.keys(imageryProvider.parameters).length > 0
          ? "?" + objectToQuery(imageryProvider.parameters)
          : ""),
      request: request,
    });
  }
```
