### ISSUE TITLE
Simple geojson attribute-based styling

### ISSUE THREAD

**Issue by KeyboardSounds** [TerriaJS/terriajs#5513]
As a catalog curator,
I want to be able to colour different features in a geojson catalog item according to their properties
To facilitate better data visualisation and communication.

In addition to our current support of the GeoJSON [simple style sepc](https://github.com/mapbox/simplestyle-spec) for all features in a catalog item, we should allow users to specify different styling for specific features according to their properties. Eg. Allow users to colour all polygons with the property `DATE` = `2021-05-26` blue.

**Comment by nf-s** [comment]
I believe this is closed by this - https://github.com/TerriaJS/terriajs/pull/5534

More complex styling will come later (eg color ramps)
