### ISSUE TITLE
App crashes when opening share links in next branch.

### ISSUE THREAD

**Issue by na9da** [TerriaJS/terriajs#5515]
I think this is happening in #next branch because of[ some references to](https://github.com/TerriaJS/terriajs/blob/next/lib/ReactViews/StandardUserInterface/StandardUserInterface.jsx#L186) `viewState.notifications` object that no longer exists.

### Testing
1. Open http://ci.terria.io/next/#share=s-lk9pQX3Yx6W8rl8Rj2OsetkWumA
2. Witness the app crash.

**Comment by nf-s** [comment]
closed by https://github.com/TerriaJS/terriajs/pull/5516
