### ISSUE TITLE
initialMessage: Cyclic dependency with app spinner and mapItems loading issue

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#5528]
The whole app spinner shows until everything is loaded and the initialMessage doesn't allow an item to be loaded until the user has clicked through a modal that's underneath the loading spinner.

URL that demonstrates this currently: https://nationalmap.dev.saas.terria.io/#share=s-cUtTQ1LUnLXAhRZKWpcP8TVsy8p

**Comment by tephenavies** [comment]
`initialMessage` can also cause a dataset not to load when added to the map. Reproduction:
* Use a catalogue that has at least 2 csvs using the same `intialMessage.key`
* Click the plus button to add the first csv to the map
* Accept the disclaimer. The first csv should begin loading and display on the map
* Click the plus button on the second csv. This csv won't load until you select the dataset and load metadata

**Comment by nf-s** [comment]
Fixed by https://github.com/TerriaJS/terriajs/pull/5576
