### ISSUE TITLE
Can't distinguish layers

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#553]
Currently there is no reliable way for the user to distinguish one visible layer from another. If they look similar, then the best you can do is click on a feature and hope that an attribute like `FEATTYPE` contains a value which makes it obvious. (Which, to be fair, in my testing is generally the case).

Suggestions:
- contain the layer name in the feature attributes pop up box
- have a mouseover that contains the layer name and maybe one or two key attributes (eg, name)

**Comment by hilarycinis** [comment]
Thanks Steve, yep there is a bit of work to do around layer rendering and distinguishing. We have explored some of the solutions you suggest, thanks for popping them!

**Comment by hilarycinis** [comment]
Thanks @kring but I'm not sure its addressing the data visualisation limitations? I think this may resolve it's self either with the user of less complicated base maps, more experience with the system and better access to the legend/opacity controls. Am going to close it.

**Comment by kring** [comment]
Never claimed #609 addressed this, I just said in that pull request that it would help us with this one.

Steve's first suggestion (indicate the layer name in the feature info popup) is easy and there's really no reason we shouldn't do it.

**Comment by RacingTadpole** [comment]
Fixed via #994
