### ISSUE TITLE
Feature attribute dialog is 100% opacity in 2D

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#554]
![screenshot 2015-02-27 16 19 02](https://cloud.githubusercontent.com/assets/678344/6407831/9625ffbc-be9c-11e4-83c1-b544160124a3.png)

**Comment by kgrochow** [comment]
The feature info popup uses the Cesium one in 3D and the Leaflet one in 2D.  It would be nice at some point to use a similar one in both modes.

**Comment by kring** [comment]
Fixed by #568
