### ISSUE TITLE
is URL-Reference the replacement for URL-Template?

### ISSUE THREAD

**Issue by geospatialmapmashup** [TerriaJS/terriajs#5545]
https://docs-v8.terria.io/guide/connecting-to-data/catalog-type-details/url-reference/
I don't see in V8/Next URL-TEMPLATE for adding Raster Tiles  (I know I can use Open Street Map https://docs-v8.terria.io/guide/connecting-to-data/catalog-type-details/open-street-map/) but that does not include placeholders and some sites have placeholders differently or are TMS how do I set the Y/ROW Flipping? or some sites have things in the URL like API KEYS or Tokens after the {z}/{x}/{y} placeholders. I am confused How I support these with the V8 Next Terriajs

V7 Terriajs had URL-Template
https://docs.terria.io/guide/connecting-to-data/catalog-type-details/url-template/

**Comment by t-takata-sy** [comment]
I also want to know how to use url-template in V8.

**Comment by geoffrowland** [comment]
I too would like to use url-template, or equivalent, in V8

**Comment by himby** [comment]
Bumping this
