### ISSUE TITLE
Show licence instead of just link

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#555]
Currently, licence info is indicated with the word "Licence", which is a hyperlink to somewhere like http://creativecommons.org/licenses/by/3.0/au/:

[Licence](http://creativecommons.org/licenses/by/3.0/au/)

Suggest displaying it like this:

Licence: [CC-BY 3.0](http://creativecommons.org/licenses/by/3.0/au/)

(This would obviously require special handling of CC URLs, which are probably the most common?)

**Comment by kring** [comment]
I believe this was addressed by my scrub of the catalog awhile back.  Everything in National Data Sets, at least, now states the name of its license on the info panel.
