### ISSUE TITLE
v8 doesnt load add web data from ows completely

### ISSUE THREAD

**Issue by pindge** [TerriaJS/terriajs#5551]
ows endpoint: https://ows.dea.ga.gov.au

from older version of terria
![image](https://user-images.githubusercontent.com/24644475/122173229-e83a9f80-cec4-11eb-8523-6aa550fc8044.png)

v8
![image](https://user-images.githubusercontent.com/24644475/122173348-00aaba00-cec5-11eb-99ad-fd183c15a40d.png)

**Comment by hardreddata** [comment]
Can reproduce.

**Comment by AnaBelgun** [comment]
Thank you for prompting this. I've created a ticket in DE Australia repo to include in next sprint. 

https://github.com/TerriaJS/de-australia-map/issues/102
