### ISSUE TITLE
Buildings disappearing when zooming in and out

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#5567]
When viewing both the NSW `Buildings 3D` as well as the updated `Buildings 3D (Hosted)` some buildings disappear when you zoom in.

Does this happen in when viewing it in the Portal?

https://user-images.githubusercontent.com/5283003/123017896-e155e480-d410-11eb-8285-97f63b7b0605.mov

**Comment by hardreddata** [comment]
For information I have the quirky https://github.com/CesiumGS/cesium-ion-rest-api-examples/issues/291 though this is when zooming _out_.

**Comment by meh9** [comment]
@na9da try this one: https://nsw.digitaltwin.terria.io/#share=s-5uG6exYYNpHCh9SRTFymc1SxT4B

**Comment by na9da** [comment]
The dataset looks fine in the portal.

After some debugging, it looks like the bounding volume of some nodes are outside the culling volume of the camera frustum and so cesium marks those nodes as invisible. The code here returns the tile as outside the camera frustum - https://github.com/TerriaJS/cesium/blob/621e7254b357360c30351ad412769a1f677bc973/Source/Scene/Cesium3DTile.js#L1168-L1170
Not sure if this has something to do with how the converter calculates bounding volumes.

**Comment by na9da** [comment]
Fixed for the hosted version - https://nsw.digitaltwin.terria.io/#share=s-6hfOVErdKHovvNuXns4Im9UoEkF
Created a new ticket for fixing the portal version - https://github.com/TerriaJS/nsw-digital-twin/issues/521
