### ISSUE TITLE
Possible UI improvement for data set legend viewing and opacity control

### ISSUE THREAD

**Issue by bsimyo** [TerriaJS/terriajs#557]
At the moment, if you are viewing a data set and you want to see the legend or change the opacity, you need to select "Now Viewing", find the data set and do the deed.  An idea for making this more intuitive for new users and more efficient for seasoned users... there could be another icon (next to the info icon) for a data set such that pressing it opens the "Now Viewing" panel with that data set's legend/opacity open and all others closed.  Just a thought... over to the UX guys to consider.

**Comment by hilarycinis** [comment]
Thanks Bill, I'm looking at it for a short term fix now, usability testing may provide further insights into a more holistic solution.

Its a bit vanilla but I've just made a wee list style icon to suggest a legend (which is a really tricky icon as it usually houses a set of icons, cartographically speaking)
![data_cat_legend_icon](https://cloud.githubusercontent.com/assets/6046521/6470876/df0ec0d2-c23a-11e4-81c2-7da3b94e1b5a.png)

**Comment by hilarycinis** [comment]
I'm going to close this as it will be addressed in the over all Legend IxD and content review.
