### ISSUE TITLE
Item search: Investigate lunr.js for indexing text fields

### ISSUE THREAD

**Issue by na9da** [TerriaJS/terriajs#5590]
Currently we use the minisearch library to generate full text indexes for text fields. This works great but we have clients requesting text search support for non-english languages. The lunr.js library appears to have the [most support](https://lunrjs.com/guides/language_support.html) for non-english languages. This ticket is to investigate switching to lunr.

Other factors to consider:
* Generated index size
* Online & offline index generation speed
* Size of library

If found suitable, we could also utilize the library for client side catalog searching.

**Comment by zoran995** [comment]
We might also check [flexsearch](https://github.com/nextapps-de/flexsearch/#performance-benchmark-ranking). I am not sure how it plays with non-english languages

**Comment by na9da** [comment]
That's a good find @zoran995 - looks promising. I'll definitely test out flexsearch and some others listed in the benchmark.

**Comment by zoran995** [comment]
This doesn't seem relevant anymore as IIRC we are using `flexsearch` to handle this
