### ISSUE TITLE
Story v3.0 - Improve editing stories

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#5595]
- Once formatted text is pasted into the body of the scene text editor, it was very difficult to revert to the original default formatting (e.g. font and font colour). I was pasting content from a word document and accidentally forgot to paste as plain text, resulting in non-matching formatting. To make the text consistent with my other scenes, I had to copy existing text from another scene, then plain text paste my new text into that to restore the default formatting (simply clearing the badly formatted text then pasting as plain text still retained the incorrect formatting). Proposed solution: include a "restore default formatting"/"convert to raw text"/"remove formatting" button that would restore all formatting to the defaults.

- Email links don't currently seem to be supported. I tried both "dea@ga.gov.au" (which was converted into a relative link), and "mailto:dea@ga.gov.au" (which was converted to plain text)

- In addition to Header 1 and Header 2 options, I would have liked an option for smaller caption-style text too. This would allow us to include a figure caption or reference below any included images in a less distracting/obvious way

**Comment by staffordsmith83** [comment]
I am working on replacing the [pell](https://github.com/jaredreich/pell) WYSIWYG editor library with [tinyMCE](https://github.com/tinymce/tinymce).

Regarding removal of formatting from text, this is possible with tinyMCE editor solution, enabling the `removeformat` button. Problematic formatting is also removed on paste, and this behaviour can be further customised.

Email links are supported, but the experience can be further improved using a custom plugin such as [this solution](https://gist.github.com/Melros/9119246).

TinyMCE will allow full range of h1-h6 heading tags. We could just include those required.

Currently have this range of features included in local development branch: 
![image](https://user-images.githubusercontent.com/7980991/169250799-16e6ef84-ff17-44ca-bb28-787a385211b9.png)
