### ISSUE TITLE
Make supported filetypes clearer

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#560]
I wanted to test the "add data" function, so attempted to upload a shapefile (.shp). It seems like a reasonable thing to try to do (although probably it wouldn't work because you need the auxiliar files, hence zipped shapefiles work better.)

The current UX isn't great:

![screenshot 2015-03-02 12 26 20](https://cloud.githubusercontent.com/assets/678344/6434189/7f6d9a90-c0d7-11e4-966e-7740ea1c0a34.png)

Followed by:

> An error occurred while attempting to convert this file to GeoJson. This may indicate that the file is invalid or that it is not supported by the National Map conversion service. If you would like assistance or further information, please email us at nationalmap@lists.nicta.com.au.

Suggest:
- including a list of supported file types and protocols in the "add data" dialog
- skipping the first dialog (IMHO the average user is going to always click "OK" because we've just told them it _might_ work). 
- add filetype detection even for non-supported filetypes, in order to give a more specific message (eg, "Shapefiles aren't supported by NationalMap. Try uploading a GeoJSON or a KML file.", and even better (if possible), aborting the upload at this stage.
- remove references to "National Map conversion service". I don't think the user needs to know there is a "conversion service" - there's just National Map.
- distinguish between the two causes of failure: unsupported file type or invalid file.
- hence perhaps reword the second dialog as: "We couldn't process the file [filename]. National Map supports GeoJSON, KML, [...]." or "We couldn't process the file [filename] - it might be corrupt or incompatible with National Map. For assistance, try nationalmap@lists.nicta.com.au"

**Comment by kring** [comment]
Good suggestions.  A couple of comments:
- National Map does support a zipped shapefiles via the conversion service.
- I think it's important to get confirmation before sending a user's file to our server.  I believe we've heard this from a number of other folks as well.

**Comment by stevage** [comment]
Oh! So the dialog is asking the user to make a choice between viewing their dataset _in the browser_, versus _uploading_ the dataset? I missed that. (I somehow interpreted the dialog as offering a choice between uploading it, or uploading and converting it).

Perhaps in that case the dialog wording could be something like:

"To view this file type, it must first be uploaded and converted on our servers. This may take a long time for large files. 

Do you wish to upload it?"

(That also avoids the bad UX of having to explain to the user what "OK" and "Cancel" mean.)

Might also be worth mentioning any privacy implications?
