### ISSUE TITLE
Update useTranslation to require prefix

### ISSUE THREAD

**Issue by zoran995** [TerriaJS/terriajs#5603]
Currently `useTranslation` will check any value for translation and if it exists apply that translation. This can lead to getting translation when we actually want to receive the exact string in only string in specified language. 
We should change this to require prefix `translate#string` like bellow
https://github.com/TerriaJS/terriajs/blob/c49f3f948801b1b56167c3bc98e31c5ad6ed7f75/lib/Language/languageHelpers.ts#L6-L23
this is a breaking change (used for help in `config.json`) so it will be good to handle it before v8 release (in that case we don't need deprecation warning)
file above is from https://github.com/TerriaJS/terriajs/pull/5145/

**Comment by zoran995** [comment]
Already mentioned in https://github.com/TerriaJS/terriajs/issues/4819#issuecomment-763167436

**Comment by tephenavies** [comment]
Done, pending https://github.com/TerriaJS/TerriaMap/pull/534
