### ISSUE TITLE
Add typeDescription property to catalog items, show in Metadata window

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#562]
![screen shot](https://cloud.githubusercontent.com/assets/678344/6434437/f4f41028-c0dc-11e4-936b-630c6ce76e44.png)

Our current dialog with information about the datasource looks like this. But realistically, very few non-GIS people know what WMS is, or what it means for them.

Suggestion: reword this part of the dialog like this:

**Data source URL**

`http://geoserver-nm.nicta.com.au/geotopo_250k/ows`

_This is a Web Map Service (WMS) layer: a pre-rendered image of the data provided by the data custodian. [More information]_

That "more information" link could expand to a paragraph or so explaining what the user can (and can't do) with a WMS layer.

**Comment by hilarycinis** [comment]
Thanks Steve, I agree. Even if GIS folk get it there it's polite to inform non-GIS folks.

**Comment by stevage** [comment]
Partially addresses https://github.com/TerriaJS/terriajs/pull/843

**Comment by stevage** [comment]
Ok, so currently I implemented this as some text hardcoded in the HTML view: https://github.com/TerriaJS/terriajs/blob/e703c4a00d29325c8e301b138d998c7bf13fc607/lib/Views/CatalogItemInfo.html#L76

This really should be a (static) property of the CatalogItem, which is shown if present.

**Comment by kring** [comment]
We shouldn't put such text in the `CatalogItem`, as it's pretty much a UI concern.  You know how the Now Viewing panel now has a configurable (even at the app level) list of sections that may be used or not depending on properties of the catalog item?  Something like that could be useful for the catalog item info panel, too.

**Comment by kring** [comment]
(I should say, the Now Viewing works that way as of #1090)

**Comment by stevage** [comment]
Hrm. I'm not sure it's a "UI concern" exactly - it's almost more like documentation about the class itself. It would be displayed in the layer info box, but potentially in other places too.

If we don't have it as a property on the catalog item, that means there is going to be some other code somewhere going:

thing.csv = "A comma separated value file...";
thing.wms = "..."
thing.wfs = "..."

which seems like centralising that information that wants to be object-oriented?

**Comment by kring** [comment]
Yeah, you're right.  Or at least it's no more a UI concern than the `typeName` static property on catalog items currently.  Something like `typeDescription` would be fine.

**Comment by kring** [comment]
Closing this because Steve implemented the important, user-facing part of it already, and we're unlikely to  add the `typeDescription` without motivation.
