### ISSUE TITLE
Metadata collapse/expand icons are misaligned in data catalogue

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#5623]
Tested in Chrome and Safari

![Screen Shot 2021-07-12 at 4 02 41 pm](https://user-images.githubusercontent.com/5292858/125238809-1d52da00-e32b-11eb-9c67-c0f7aaff67bb.png)

**Comment by nf-s** [comment]
Duplicate issue https://github.com/TerriaJS/terriajs/issues/5614

PR here #5616
