### ISSUE TITLE
v8 ~ wms-group could benefit from opacity property

### ISSUE THREAD

**Issue by hardreddata** [TerriaJS/terriajs#5631]
Being able to set all the layers to load with `"opacity": 1` can be helpful. 

Not required for going live.

**Comment by hardreddata** [comment]
Also the v7 WMS group would sort items by `title` and not `name`.

**Comment by tephenavies** [comment]
Hi @RussellGrew. I think this could be done using "itemProperties":

```json
{
  "name": "The WMS Group",
  "type": "wms-group",
  "url": "...",
  "itemProperties": {
    "opacity": 1
  }
}
```

The above should work for v8 and the same but using `"type": "wms-getCapabilities"` should work for v7.

**Comment by hardreddata** [comment]
Thanks @steve9164 the `itemProperties` worked for opacity. 

If you have any ideas for sorting the group contents by title and not name from the catalogue this is very welcome. 

Maybe I just need to swap these around https://github.com/TerriaJS/terriajs/blob/7c13c941fcce45f87c8dd597104154cb2429b7f8/lib/Models/Catalog/Ows/WebMapServiceCatalogGroup.ts#L291 but this might not be good for everyone.

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/6218
