### ISSUE TITLE
Create UX wireframes for Help menu redesign

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#5636]
Discuss with UX team about reconfiguring Help menu as follows: 

- [ ] remove Related Maps button - to be included as configuration change when releasing NatMap as standalone map https://github.com/TerriaJS/nationalmap/issues/1054 - NOT TO BE DONE PART OF THIS TICKET
- [x] moving Help content from Help button at the bottom right corner under new tab
- [x] include link to End User manual into Help content (https://terriajs.gitbook.io/terriajs/)
- [ ] have default generic Get Started video and workflows under Help page 

note to Phil: set up metrics for GA when we do it

**Comment by wibily** [comment]
ticket includes having the meeting, does not include wireframes

**Comment by wibily** [comment]
Phil: ticket is to address help not being discoverable enough

**Comment by wibily** [comment]
Make it look like this:
(settings | help | lang ) (story) (share/print)

**Comment by philipgrimmett** [comment]
Invision link: https://invis.io/TA11KT4XEYKS#/457213471_help_1

**Comment by wibily** [comment]
GA events on opening help panel and on individual help menu items

**Comment by wibily** [comment]
note: help is currently disabled in mobile view

**Comment by AnaBelgun** [comment]
related maps button should not be removed unless map owners are asking for it
i.e. national map and digital twins should keep related maps button

**Comment by wibily** [comment]
note to self: restore in SASS and digital twins

**Comment by wibily** [comment]
https://github.com/TerriaJS/terriajs/pull/5775

**Comment by AnaBelgun** [comment]
Sorry I need to reopen this because I noticed a discrepancy in the design

![image](https://user-images.githubusercontent.com/18452161/132425979-3c2ce705-049c-4a59-a826-da41da85295e.png)

**Comment by AnaBelgun** [comment]
Update 8 Sep 2021: 
Team to discuss and decide on: 
1) how to handle Help in mobile - do we include Help in the hamburger menu with either a) same sub menu as in desktop; b) just a link to the user guide (my preference if it works on mobile, to keep the same items as in desktop, but let's let @philipgrimmett  weigh in on that)
2) Help items listed need a design correction (i.e. the last item - Terria guide - needs an icon and the name to match the guide's name "Terria Platforms User Guide"

**Comment by wibily** [comment]
ticket to include removing icons from help items and instead showing a generic '>'. Will probably require updating all the client config for the maps

**Comment by philipgrimmett** [comment]
> 1. how to handle Help in mobile - do we include Help in the hamburger menu with either a) same sub menu as in desktop; b) just a link to the user guide

If we make the existing help content available on mobile we'll have to update it to make sure it is relevant for the mobile UI.

![terria-help-iPhone11](https://user-images.githubusercontent.com/5292858/132604573-1dda2687-7462-4f36-a7dd-9a59b1afb6f0.png)
![terria-gettingStarted-iPhone11](https://user-images.githubusercontent.com/5292858/132604581-b340e1fe-eb14-460e-b20f-59df3774fca5.png)

> 2. Help items listed need a design correction (i.e. the last item - Terria guide - needs an icon and the name to match the guide's name "Terria Platforms User Guide"

Not sure the icons are that helpful for navigating the current help content, so I suggest we remove them on desktop and mobile for now. As the list of guides grows over time we should revisit.

**Comment by wibily** [comment]
@philipgrimmett decisions made in after standup session with Ana/Nanda/Will:

**desktop**
Terriamap user guide text to be terria platforms user guide
We will use the existing pattern for help menu items and use the external icon to be the left hand side 
We will move the user guide link into map specific config and update the different map configs to enable end users to ovverride the display of it
**Mobile:**
Add a link to the terria platforms user guide in the hamburger menu. If "terria platforms user guide" is too long, we can use "Terria user guide"

**Comment by AnaBelgun** [comment]
hi @philipgrimmett please check what we discussed today about Help; happy to discuss on slack

**Comment by AnaBelgun** [comment]
Update 10 Sep 2021 (@philipgrimmett @nanda)

**Desktop**
- Help moved at the top 
- Listed items - lower case (all) - https://projects.invisionapp.com/share/TA11KT4XEYKS#/screens/457213471_help_1
- "Map user guide" - to be used for linking to the https://userguide.terria.io/
- Phil to send a picture representing a generic terria map to be included on landing page of the external user guide 

**Mobile**
- Include "Map user guide" in the hamburger menu and link to the https://userguide.terria.io/
- maintain separate configuration for mobile than desktop because the content is different 
- Mobile configuration is generic enough to be used in all apps

**Comment by na9da** [comment]
The help configuration doesn't look very extendable. So the changes I make for this will be hacky at best. If @philipgrimmett has ideas for re-working help going forward, then it should be temporary, so maybe it is alright.

**Comment by na9da** [comment]
[Test link](http://ci.terria.io/restyle-help-panel/#configUrl=https://gist.githubusercontent.com/na9da/b326147a3cc7a066d6501ecef2b93960/raw/834af0d311ccf1b4d6b73872b0b3cfdb6a914412/config-with-map-user-guide.json).

@philipgrimmett @AnaBelgun - I have changed the help panel styling and added map user guide to help and mobile menu (if it is configured). Please test and let me know if any further changes are required.

Once the PR is merged, we need to update individual map config for the map user guide to be shown.
