### ISSUE TITLE
Support all entity/data source/CZML primitives in Leaflet

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#564]
The following graphical primitives on `Entity` are not currently rendered in Leaflet:
- Box
- Corridor
- Cylinder
- Ellipse
- Ellipsoid
- Model
- Path
- Polyline Volume
- Rectangle
- View From
- Wall

The most important of these are probably Path and View From.

**Comment by kgrochow** [comment]
This will happen as needed and probably will never be complete unless the cesium folks write a leaflet plugin.

**Comment by stevage** [comment]
Perhaps we should use [Leaflet Omnivore](https://github.com/mapbox/leaflet-omnivore)?

**Comment by kring** [comment]
We should try to keep the pipelines for our geospatial formats as much the same between Leaflet and Cesium as possible.  One way to do that is to teach Leaflet how to visualize Cesium entities, which is what we've done.  Another possibility is to teach Cesium how to render data loaded by Leaflet Omnivore, if it has the necessary decoupling for that.

**Comment by kring** [comment]
To be done as needed, don't need an issue for it.
