### ISSUE TITLE
Migration v7 - v8 - reinstate allow load for WMS group 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#5641]
In v7 this WMS group works
https://www.asris.csiro.au/arcgis/rest/services/rowra/Roper_TreeHort_CropSuit/MapServer 

But in v8, same WMS group gets this error
![image](https://user-images.githubusercontent.com/18452161/125956103-f12f6ce4-1c53-410f-8496-766f28bb12a2.png)

**Comment by wibily** [comment]
check with @nf-s first to see whether or not it has already been done

**Comment by na9da** [comment]
Hi @AnaBelgun,

I didn't see any problems when loading the URL directly on v8 - http://ci.terria.io/next/#share=s-mw07ap0Ec4Tf3cDv8Haz5J6MORL

Which map is giving the error? It could be possibly be a mis-configured catalog item. Could you share a link to the catalog entry please?

**Comment by AnaBelgun** [comment]
@na9da I've tried it and it works now; I'm checking with the data custodian and if any issues, will re-open the ticket. Thank you.
