### ISSUE TITLE
Migration v7 - v8 - Update warnings

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#5645]
There is a number of warnings we need to include in different files, ideally min 2 weeks before the migration. 

- [x] Update ReadME in Master
- [x] Update ReadME in master TerriaMap
- [x] handle warnings for both git and npm, depending on what users are pulling from and for what (code or map)
- [ ] Post in GitHub Discussions about v8 migration end of July - captured in blog ticket
- [x] rename "next" as "main" instead of "master" 
- [x] decommission Gitter forum; final message for users to move to "Discussions" - posted in Gitter

**Comment by wibily** [comment]
decide on how to deal with the current git master branch

**Comment by wibily** [comment]
@wibily take on first three asap then assign to crispy
