### ISSUE TITLE
Story v2.0 - handle re-arranging catalogue not to break sharelinks (public only)

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#5646]
Currently re-arranging / re-organising catalogue breaks sharelinks and stories if they are shared. 
i.e. if a catalogue item is renamed or moved within a different group, it will break the share links and stories. 
reproduction of steps: 
- create a share link with a nr of data sets 
- change / reorder datasets in catalogue
- sharelink created initially will break

Does not include changing the format of datasets

**Comment by wibily** [comment]
check that it hasn't been fixed as part of #5459

**Comment by wibily** [comment]
look at at product#89 https://github.com/TerriaJS/product/issues/89

**Comment by AnaBelgun** [comment]
This is currently blocking Story v2.0 on addressing the data changes we control

**Comment by wibily** [comment]
refinement meeting to take place

**Comment by wibily** [comment]
- share links also do not handle local uploads which are then subsequently shared

**Comment by nf-s** [comment]
Some background

- https://github.com/TerriaJS/terriajs/blob/main/architecture/0005-root-group-ids-and-shareKeys.md
- https://github.com/TerriaJS/terriajs/blob/main/architecture/0006-dynamic-groups-and-shareKeys.md

**Comment by nf-s** [comment]
## Decision from 16/08/2021 meeting

Try creating a "terria catalog index" JSON file which contains fully resolved catalog tree with member IDs and names.

For example:

```json
[
  {
    "id": "some-id",
    "name": "some name",
    "members": [
      {
        "id": "a-nested-id",
        "name": "a nested name"
      }
    ]
  }
]
```

OR

```json
[
  {
    "id": "some-parent-id",
    "name": "some parent name"
  },
  {
    "id": "some-id",
    "name": "some name",
    "knownContainerIds": [
      "some-parent-id"
    ]
  }
]
```

This JSON file can then be used to resolve share member `ids` if they don't exist in `terria.model`.

The file can also be used to search through entire catalog using the `name` property

**Comment by nf-s** [comment]
We can extend https://github.com/TerriaJS/terriajs-indexer to support terriajs init sources

**Comment by wibily** [comment]
nick: catalog indexer works with magda data sets, does not work with restricted datasets, it is run manually and is part of the terriajs build-tools.

**Comment by wibily** [comment]
crispy: suspect that this is actually working

**Comment by wibily** [comment]
communicated with DEA team about the use of ids. As long as they use ids, moving catalog items will not break.
Possible to maintain share links when moving items around in a json catalog and not possible when moving itmes around in a WMS group. This should also be put into terriajs docs

**Comment by wibily** [comment]
ticket acceptance criteria can be an explanation
