### ISSUE TITLE
Improve ArcGisMapServerCatalogGroup and FeatureInfoSection

### ISSUE THREAD

**Issue by mwu2018** [TerriaJS/terriajs#5650]
If map server layers provide incorrect extents, such as http://services.ga.gov.au/gis/rest/services/NEXIS_Residential_Dwelling_Density/MapServer, we need to be able to override those values.

Also need to be able to present correct feature info to users.

See https://github.com/TerriaJS/nationalmap/issues/1036 for details.

**Comment by wibily** [comment]
Talk to Nanda about whether this is the right approach

**Comment by na9da** [comment]
Hi @mwu2018 - I think the problem with this approach is that `MappableTraits` are meant for items that can be directly shown on the map whereas `ArcGisMapServerCatalogGroup` is a container of such items. Mixing in the `MappableTraits` will result in the group getting properties like `show`, `disablePreview` etc that are not meaningful for a group. So I think we should follow the approach of [WebMapServiceCatalogGroup](https://github.com/TerriaJS/terriajs/blob/d97e6b4e8a7defa30eab0b162008d9c1ed29ff2f/lib/Models/WebMapServiceCatalogGroup.ts#L279-L283) by adding  `itemProperties` trait to this class and propogate it to child members of the group.
