### ISSUE TITLE
Documentation on how to customise error message with customised language pack

### ISSUE THREAD

**Issue by t83714** [TerriaJS/terriajs#5666]
# Documentation on how to customise error message with customised language pack

When build customised TerriaMap, the default error message (defined [here](https://github.com/TerriaJS/terriajs/blob/426f5b04e4842aed1d1501f6e5764be3ea1a1c90/lib/Language/en/translation.json#L1422)) might not suit all use cases.

See relevant discussion here: https://github.com/TerriaJS/terriajs/issues/5459

One solution could be allowing developers to customise the language pack (which contains the error message string) when create a customised Terria Map project.

We need the documentation on how to supply a new language or override the language string entry without forking TerriaJS when build a Terria Map site.

**Comment by zoran995** [comment]
Documentation is available in the repo https://github.com/TerriaJS/terriajs/blob/next/doc/customizing/translation-guide.md#language-overrides-language-file---languageoverridesjson, we should add it to the nav menu on the docs site

created a new issue for linking in the doc #5672

**Comment by t83714** [comment]
Thanks a lot @zoran995  
I think I can close this ticket as we already have a doc for it
