### ISSUE TITLE
v7 - v8: Gitter to be decommissioned 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#5669]
https://gitter.im/TerriaJS/terriajs to be decommissioned to streamline support and avoid confusion. 

On 23 July 2021: message was edited on main banner advising the community that Gitter forum will be decommissioned on the 9th of August 2021. Forum has moved to GitHub Discussions.

**Comment by wibily** [comment]
Ana to archive/ turn off

**Comment by AnaBelgun** [comment]
Go to settings, click Delete Room

**Comment by AnaBelgun** [comment]
done
