### ISSUE TITLE
Identify popup style problems

### ISSUE THREAD

**Issue by Layoric** [TerriaJS/terriajs#567]
Hi Team,

The 2D leaflet popout seems to have issues displaying some of the data coming back from the identify tool. Eg, Taxation Stats 2011-2012.

![image](https://cloud.githubusercontent.com/assets/234642/6455484/86013d0e-c1a8-11e4-8815-0c6e437960b3.png)

Tested with IE9 and Chrome 40, result is consistent.

**Comment by kgrochow** [comment]
Fixed.  Just waiting for it to be merged.

**Comment by kring** [comment]
Fixed by #568.
