### ISSUE TITLE
`{{terria.currentTime}}` not supported in feature info templating

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#5685]
Using template `{{terria.currentTime}}` see v7: 
http://ci.terria.io/master/#https://gist.githubusercontent.com/steve9164/e53a942a49aa4a2300aeec99624e27ba/raw/036a1224624f04fbea5bc8ca4a0e6b93f561cbb8/test-wms-feature-template.json
![image](https://user-images.githubusercontent.com/13863530/127276538-b508e35c-a890-41b1-8cd4-98d678f5ed97.png)

against v8:
http://ci.terria.io/next/#https://gist.githubusercontent.com/steve9164/e53a942a49aa4a2300aeec99624e27ba/raw/036a1224624f04fbea5bc8ca4a0e6b93f561cbb8/test-wms-feature-template.json
![image](https://user-images.githubusercontent.com/13863530/127276573-418ea060-f3c4-42b1-9e22-b2dc6801cf76.png)

**Comment by zoran995** [comment]
`discreteTime` is no longer available on catalog item instances, it is used here https://github.com/Terriajs/terriajs/blob/next/lib/ReactViews/FeatureInfo/FeatureInfoSection.jsx#L128

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/6441
