### ISSUE TITLE
Get clicked point feature info for all enabled layers

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#569]
When several layers are enabled and a point on the map is clicked, get the feature info for that point for all the enabled layers instead of just one of them. Then display these in the feature info popup as different tabs, or initially minimised expandable stack (like the Now Viewing tab), or something like that.

Probably a good idea to expand the info in real-time as they are returned, so we don't have to wait for all the info requests to finish before showing results.

**Comment by chloeleichen** [comment]
Anyone working on this issue? Are we going ahead with @meh9 's recommendation?

**Comment by stevage** [comment]
Yeah, this is a really important feature that is required for the new Northern Australia map project. The use case there is that a user will click on a point and we want to show them all native title, indigenous land use agreements etc that affect it. Each is present as a WMS layer.

I have a vague recollection that implementing this isn't trivial, but unfortunately I don't remember why. It may be that the feature picking happens in Cesium, so would require changes at that level. But maybe I'm misremembering - so please do dive in and see if you can make it work.

The final result will need to be fairly flexible - some projects will want to immediately display properties stacked, others will want to concertina them etc. The UX that Mitch and I discussed for Northern Australia would be something like:
- "Native Title"
  - Name: ...
  - _Click for more info..._
- "Indigenous Land Use Agreement"
  - Name: ...
  - _Click for more info..._

Where clicking expands that section (and collapses any other expanded sections).

**Comment by chloeleichen** [comment]
@kring would you please have a look at this? just dump all the html into the template and I will update the template and styles based on @philipgrimmett 's design.
