### ISSUE TITLE
Hide/show layer action in Now Viewing

### ISSUE THREAD

**Issue by hilarycinis** [TerriaJS/terriajs#570]
After reading the revised help notes, I realised there is a broken interaction pattern with regards to showing or hiding the data layer when in "Now Viewing". 

I've revised the icon use to use a more established hide/show pattern.
![now_view_hide_layer](https://cloud.githubusercontent.com/assets/6046521/6470911/2c82ddc6-c23b-11e4-8f4e-44c3489a833c.png)

**Comment by kring** [comment]
IMO the eye icon (rather than checkbox) is a nice improvement.  Not sure why you closed this.

**Comment by kgrochow** [comment]
If it was because of discoverability, then I'm with Hilary.

**Comment by kring** [comment]
Sorry, I don't know what you mean @kgrochow.  Are you saying you think the eye wouldn't be sufficiently discoverable?

**Comment by kgrochow** [comment]
It's not clear to me that I should click on it.  It seems like an indicator as opposed to a control/indicator.

**Comment by kring** [comment]
Well it's not an uncommon pattern:
https://www.google.com/search?q=eye+icon+show+hide&source=lnms&tbm=isch

**Comment by hilarycinis** [comment]
we are not the users :)

**Comment by hilarycinis** [comment]
yep, why the pattern was selected. Anyhoo, we are doing a full redesign so maybe another solution will present itself

**Comment by kring** [comment]
So @hilarycinis did you intend to close this issue?  Dropping in a new icon is really simple if you think it would be an improvement (I do).  It doesn't stop us from doing a more drastic redesign later, of course.

**Comment by hilarycinis** [comment]
cool
