### ISSUE TITLE
Search not returning all results

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#571]
The Search will often not return all relevant results.

For example, searching for "Macgregor" will only return Macgregor, QLD, and not show Macgregor, ACT, I have to actually type "Macgregor A" (or the full "Macgregor, ACT" if the comma is included) before the Macgregor in ACT shows up as a result.

**Comment by kring** [comment]
Unfortunately the Bing Maps geocoder is a black box, I don't think we can do anything about this.

**Comment by stevage** [comment]
I [improved the use of the Gazetteer service](https://github.com/NICTA/nationalmap/commit/5a2f25e6f98774ce6450bbbba893a247a521c2fb), which fixes this:

![screenshot 2015-04-29 16 58 58](https://cloud.githubusercontent.com/assets/678344/7385932/0cbbbbc0-ee91-11e4-99c6-9e9111db4308.png)

Should we consider this closed?

**Comment by hilarycinis** [comment]
looks good to me, thanks @stevage
