### ISSUE TITLE
Support styling of vector features

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#574]
It would be great to be able to specify the colour to draw WFS features with in the layers configuration in the NM init file. This would help when you have several WFS layers you want to show.

For example, this WFS layer of power stations has no visualisation associated with it, so adding it in NM draws it with thick green lines:

http://www.ga.gov.au/gis/services/energy/ASEIS_Features/MapServer/WFSServer?service=WFS&version=1.1.0&request=GetFeature&typeName=energy_ASEIS_Features:Power_Stations&srsName=EPSG%3A4326&maxFeatures=1000

It would be great to say to draw it as red or blue or whatever.

**Comment by Meeena** [comment]
[cid:B0C70221-45D3-4395-87B0-46792425882D]
NICTA
Senior User Experience Designer

Locked Bag 9013 Alexandria NSW 1435
T + 612 9376 2108 | M 0403 941 363
www.nicta.com.au | meena.tharmarajah@nicta.com.au<mailto:hilary.cinis@nicta.com.au>

**Comment by kring** [comment]
A similar styling system can apply to other types of vector features, such as GeoJSON.

**Comment by nf-s** [comment]
🥳 This is now supported! https://github.com/TerriaJS/terriajs/pull/5900

GeoJson styling follows `TableStyleTraits` specification
