### ISSUE TITLE
v7 - v8 migration: tryToLoadObservationData (SOS) missing in v8

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#5744]
Investigate this SensorObservationServiceCatalogItem: tryToLoadObservationData

**Comment by wibily** [comment]
investigate that this hasn't been done already

**Comment by nf-s** [comment]
`tryToLoadObservationData` is not implemented in v8.

There are also a few related traits which aren't used

https://github.com/TerriaJS/terriajs/blob/0c001498e63fc689ed46bd440d371bfc8db7e414/lib/Traits/TraitsClasses/SensorObservationCatalogItemTraits.ts#L50-L64

Either way, this issue doesn't impact natmap SOS items:

![image](https://user-images.githubusercontent.com/6187649/134292675-0974bd3a-cc77-4a08-8099-262122380dd0.png)
