### ISSUE TITLE
NatMap v7-v8 migration: Colour binning issues

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#5750]
Update 10 Sep 2021: 

- following testing there were 4 major issues identified, in order of priority:

**1) Faded colour range in V8** - ACTION: to move the range up the scale to increase the depth & contrast - https://github.com/TerriaJS/terriajs/issues/5805 
**2) White colour for boundary lines** - ACTION: to 1st investigate how difficult and then if possible change colour to black: https://github.com/terriajs/terriajs/issues/5340
**3) No data showing for some WA Bioenergy layers** - see below; it might be related to binning / ranges or faded colours TBC
**4) Colour binning** - issues with the range values due to changes to binning approach 

To test: 
**AREMI - Solar -> Rooftop Solar - colour binning not the same**

v7: 
- https://nationalmap.gov.au/#share=s-tGBFlN56F3eCICfNZcaxaYgCLaV
![image](https://user-images.githubusercontent.com/18452161/132800776-ce1f798e-cf7a-4833-bd21-7629a3521e6a.png)

v8: 
- https://nationalmap-2021-09-03.nm.terria.io/#share=s-A64zKh4pJfH4JxtDl4re1sQzA32
![image](https://user-images.githubusercontent.com/18452161/132800837-1aef4ef1-4ea7-4b3d-b32a-0e0c0041e06a.png)

**AREMI - Bioenergy - QLD - Bioenergy -> QLD ** - colour binning not the same**
v7: 
- https://nationalmap.gov.au/#share=s-t1tVw5a8A4qrg62QE6q3Ch6DTm6
![image](https://user-images.githubusercontent.com/18452161/132801124-bbce0dfa-51b7-4d11-abfa-5e79b42fa887.png)

v8:
- https://nationalmap-2021-09-03.nm.terria.io/#share=s-quP5dmoSUw6VqZmfagGnnOEqYZh
![image](https://user-images.githubusercontent.com/18452161/132801216-3dad2408-d19d-45ff-9678-929f97a63ec5.png)

**AREMI - Bioenergy -> VIC ** - colour binning not the same
AREMI - Bioenergy -> VIC ** - TOTAL_RESIDUES is not binning correctly in v7 and 8**

v7:
- https://nationalmap.gov.au/#share=s-rdFT20ip7np0QAOkw3jaIzu2bgW
![image](https://user-images.githubusercontent.com/18452161/132801372-0cdeb704-06ea-465b-84d7-b3818910320c.png)

v8: 
- https://nationalmap-2021-09-03.nm.terria.io/#share=s-9ynQkCppKlrx0ykrj4NDCUjw2Im
![image](https://user-images.githubusercontent.com/18452161/132801404-f1905056-ef65-4c6b-92bf-570048e9f74a.png)

**AREMI Bioenergy -> WA - colour binning not the same - BROKEN - not showing data in v8** 
This might be an issue with the data from WA CKAN instance: https://catalogue.data.wa.gov.au/dataset/a93e9ea9-134d-49e9-9945-7515147fbcfb/resource/a600d6ff-e205-4cf6-9ab8-4c6ee0f11c02/download/oma-database-shire-summary-data_101219_dw.csv

v7: 
- https://nationalmap.gov.au/#share=s-h1zCSk0UWq8k1OaO7Hc8kUFeHbn
![image](https://user-images.githubusercontent.com/18452161/132801711-95e816ed-2bed-473d-b492-bf90e543790f.png)

v8:
- https://nationalmap-2021-09-03.nm.terria.io/#share=s-5qxliMYxPKdm7w2jMEPzf6BBeXx
![image](https://user-images.githubusercontent.com/18452161/132801789-f3e97e9c-7f89-4a3b-9f8d-0d77f962d972.png)

v7: 
- https://nationalmap.gov.au/#share=s-yUcZw5cbs8tVXPfz8tjDbneKyPM
![image](https://user-images.githubusercontent.com/18452161/132802095-907f2607-5c9e-4e1a-868e-97562a605b3a.png)

v8: 
- https://nationalmap-2021-09-03.nm.terria.io/#share=s-kO70tc8bTGNp6UboXSCzBEJPoEq
![image](https://user-images.githubusercontent.com/18452161/132802146-ed58b8b4-b311-4667-bfba-5b28ef940739.png)

Same data but tested with CSV file downloaded from data.wa - still not showing anything for Total Residues
![image](https://user-images.githubusercontent.com/18452161/132802330-1764c65f-a072-4eeb-8165-8ca55ba48d59.png)

**AREMI - Generation -> Small Scale Installations - colour binning not quite the same**

v7: 
- https://nationalmap.gov.au/#share=s-bVqTmJ7lEnyuQrcppQx3X7xetVw
![image](https://user-images.githubusercontent.com/18452161/132802630-44dec6c0-6ad4-409c-ba69-4739ad8d8b89.png)

v8: 
- https://nationalmap-2021-09-03.nm.terria.io/#share=s-fdcMvIUwG4vrJyB2zLblt6ixCe4
![image](https://user-images.githubusercontent.com/18452161/132802974-39b0966d-c10d-422c-b334-0b728269d343.png)

**Comment by wibily** [comment]
this ticket is to address the difference in how v7 and v7 colour binning works

**Comment by wibily** [comment]
check if the colour binning is sensible in v8 versus v7

**Comment by wibily** [comment]
look here for URLS:
https://github.com/TerriaJS/handbook/blob/master/DeveloperGuides/Services.md
