### ISSUE TITLE
Embeding iFrame

### ISSUE THREAD

**Issue by anujdivesh** [TerriaJS/terriajs#5752]
is it possible to embed iFrame in featureInfoTemplate. Similar to how we embed images.
"featureInfoTemplate": {
              "template": "<img style='width:100%;height:400px;' src='{{Primary image}}'/>"
 }

**Comment by iamsaswata** [comment]
Any update on this one?

**Comment by anujdivesh** [comment]
@iamsaswata Its been long, but I am pretty sure I was able to do this last time around. The way i think it works, TerriaJS rejects some file extensions such as `.html`. Its either this file https://github.com/TerriaJS/terriajs/blob/main/lib/ReactViews/Custom/parseCustomHtmlToReact.ts or https://github.com/TerriaJS/terriajs/blob/main/lib/ReactViews/Custom/parseCustomMarkdownToReact.ts where I basically added `.html` as a known tag in the array.

After making the changed you can rebuild terriaJS using https://docs-v8.terria.io/guide/contributing/development-environment/

Hope this is helpful.

**Comment by iamsaswata** [comment]
Thank you so much @anujdivesh for giving the direction.
