### ISSUE TITLE
Allow users to exclude story from sharelink

### ISSUE THREAD

**Issue by robbibt** [TerriaJS/terriajs#5756]
## Issue

An increasingly common use case for Terria stories is to provide an easy way to access a preloaded set of layers or products (e.g. https://maps.dea.ga.gov.au/#share=s-DEACoastlines&playStory=1). 

Once a user completes a story and starts to explore the layers/product, they often wish to share examples of interesting locations of interest they have found in the data. Currently, a user can achieve this by creating a share link via "Share/print". However, these share links currently include a link to the original story too. This means that when a user visits this new share link, they get this result with the story dialogue ("This map contains a story"):

![image](https://user-images.githubusercontent.com/17680388/130374228-e78dd38f-588e-4a23-8574-88e37b89a5a5.png)

For new users who are not familiar with Terria, the natural response to seeing this pop-up is to click "Yes", which takes them away from the specific share link scene captured by the original user. Currently, the only way to exclude the story from a share link is to delete the entire story manually then copy the link, which is not intuitive.

## Possible solution

It would be fantastic to have a "Include story" checkbox in the "Share/print" popup so that users can choose to exclude the story when creating a share link. This would allow share links to be created from a shared story link without including the original story itself:

![image](https://user-images.githubusercontent.com/17680388/130374521-9ccc6961-2469-4ac1-a1db-dac8892d3b94.png)

**Comment by staffordsmith83** [comment]
PR https://github.com/TerriaJS/terriajs/pull/6282 is ready to implement the behaviour requested. Is this what we want @meh9 and @AnaBelgun ? Another option is to enable exporting stories by default, and to have an option 'Exclude Story from Share' hidden in advanced options?

**Comment by AnaBelgun** [comment]
@staffordsmith83 I think @philipgrimmett would be best to comment but my preference would be to include that under advanced options. It looks cleaner. 
That real estate (where the Include story sits in the proposal) might soon be used in having a "Save" function which we need to deliver this June. That function will allow users to save the sharelink like any other web page.
