### ISSUE TITLE
Allow fields in init.json files to internally reference values

### ISSUE THREAD

**Issue by axman6** [TerriaJS/terriajs#576]
For one of the datasets we're working with, we have 24 layers which should all have the same description when clicking on the info button for the layer. We'd like to be able to place a description on the group which contains all the layers (or in our case, the group which contains the groups of layers), and be able to reference that from each layer. After speaking with @kring, the initial design we've come up with so far looks something like:

``` json
{
  "name": "Group",
  "type": "group",
  "description": "Hopefully this description is inherited",
  "items": [
    {
      "name": "Subgroup",
      "type": "group",
      "items": [
        {
          "name": "Layer 1",
          "description": {"$jref":"../../description"},
          "description2": {"$jref":"../../../../description"},
          "dataCustodian": "Someone Inc.",
          "type": "kml",
          "url": "foo.kmz",
          "rectangle": [
            "137.0",
            "-39.5",
            "154.0",
            "-18.5"
          ]
        }
      ]
    }
  ]
}
```

It's not clear which path (description or descriotion2) would be the correct one here; it would depend on whether there is also support for indexing into an array:

``` json
...
"description":{"$jref": "../0/description"},
...
```

may be used to point to the description of the first layer in the array of items.

I believe that something like "$jref" should be used instead of "$ref" because I'm not sure that this behaves in the same was as the [proposed son reference syntax](https://tools.ietf.org/html/draft-zyp-json-schema-03).

**Comment by kring** [comment]
I think something like this would be a bit cleaner and avoids the awkward relative paths:

```
{
    "catalog": {
        "name": "Group",
        "type": "group",
        "description": "Give the group an actual description here, rather than the one its children will inherit",
        "items": [
            {
                "name": "Subgroup",
                "type": "group",
                "items": [
                    {
                        "dataCustodian": "Someone Inc.",
                        "description": {
                            "$ref": "#/longDescriptions/awesomeGroup"
                        }
                        "name": "Layer 1",
                        "rectangle": [
                            "137.0",
                            "-39.5",
                            "154.0",
                            "-18.5"
                        ],
                        "type": "kml",
                        "url": "foo.kmz"
                    }
                ]
            }
        ]
    },
    "longDescriptions": {
        "awesomeGroup": "Hopefully this description is inherited"
    }
}
```

It also follows the JSON referencing proposal described here:
https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03
https://tools.ietf.org/html/draft-ietf-appsawg-json-pointer-04

**Comment by axman6** [comment]
Personally I'd prefer to use the relative version, because it means that the description for a group of datasets is kept with the group itself, but I feel (hope?) it wouldn't be too difficult to support both forms and have general references to and from anywhere within the document.

**Comment by kring** [comment]
Yep, that shouldn't be a problem.  I just find all those `../`'s unwieldy.

**Comment by kring** [comment]
Also, since you said the description in this case is really long, taking it out of the flow of the rest of the init file makes the init file a little easier to work with IMO.

**Comment by stevage** [comment]
I hadn't seen this request before. I've recently added something similar (but maybe simpler) for WMS layers: 6a2421df

It wouldn't quite handle the above case, but it allows you to do this:

```
"catalog": {
        "name": "Group",
        "type": "group",
        "itemProperties": {
          "description": "This description will be set on every item"
        }
        "items": [...]
}
```

IMHO pushing a value downwards is a little easier on the brain. 

It doesn't handle the above case in that it only goes one level down (not group --> subgroup --> item), and it's only implemented for WMS layers. It also doesn't handle dynamic properties (ie, ones retrieved from the service at runtime), if that's important.

Also, in case we're thinking about expanding our JSON logic, it might be worth thinking instead about just invoking some extra build step, possibly based on JQ. So then, this particular use case might be solved by a single line of JQ to be executed during the build.

**Comment by kring** [comment]
I'm closing this because I think it's handled ok by ejs or (even better) by the JavaScript-based catalog generation that is used in Northern Australia Map and elsewhere.
