### ISSUE TITLE
Difference workflow adds layers with full 0 opacity

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#5762]
The Difference workflow appears to initialise with 0 Opacity for the layer being viewed. Using the left/right buttons on the date picker leaves it in 0 Opacity. However if clicking the date and using the full date picker to select a day appears to reset the Opacity so that the data can be shown. See attached video for the behaviour.

https://user-images.githubusercontent.com/5283003/130710719-1d06a370-a8ff-4b97-a7c8-a22c30e8b81f.mov

**Comment by na9da** [comment]
PR to fix the problem - https://github.com/TerriaJS/terriajs/pull/5764

**Comment by nf-s** [comment]
closed by https://github.com/TerriaJS/terriajs/pull/5764
