### ISSUE TITLE
Opacity slider support for GeoJSON

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#5767]
Some datasets have lost the opacity slider in v8. 
To test: 
- Go to a v7 platform http://neii.gov.au/viewer/#share=s-gDKxs7G9NoN92tK5QsAmAfLNb6c 
using a GeoJSON data format: http://neii.bom.gov.au/cgi-bin/nemsr/get_geojson.py?network_id=29&1630038107
- Opacity slider is available
![image](https://user-images.githubusercontent.com/18452161/131076678-c877875b-cbcc-472a-a86e-6f93351b2c85.png)

- Go to v8 platform using the same data: https://beta.neiiviewer.nicta.com.au/#share=s-11o2eu6cEARa7bGueyh3pEUIntF
- Opacity slider not available 
![image](https://user-images.githubusercontent.com/18452161/131076706-644a60fd-84a9-4e1e-9067-25b861b296d8.png)

- Opacity slider available for WMS

**Comment by nf-s** [comment]
This is enabled for new ProtomapsImageryProvider geojson items. To use this you will need to set `Terria.configParameters.enableGeojsonVt = true`
