### ISSUE TITLE
deprecate unused SAAS repos

### ISSUE THREAD

**Issue by wibily** [TerriaJS/terriajs#5778]
this is to prevent confusion when users look at a codebase that isnt' used

The following maps are now served from `terrace` code base via `saas` configuration. Ticked boxes have PRs to be reviewed and merged.
- [x] https://github.com/TerriaJS/de-australia-map 
- [ ] https://github.com/TerriaJS/terria-cube **Wait for further decision.**
- [ ] https://github.com/TerriaJS/de-africa-map **delete**
- [x] https://github.com/TerriaJS/aremi-natmap **Available in nationalmap**
- [ ] https://github.com/TerriaJS/easi-eo **Wait for further decision.**
- [ ] https://github.com/TerriaJS/easi-config **Wait for further decision.**
- [x] https://github.com/PacificCommunity/Terria-PacificMap **We don't own this repo. Merge this fork back https://github.com/mwu2018/Terria-PacificMap**

`kaleidoscope` ~and `pacificmap`~ are also served from `terrace` but seem to have no their own repos.

Repos to do later (when they're running v8 SaaS in production):
- [ ] https://github.com/TerriaJS/neii-viewer
- [ ] https://github.com/TerriaJS/RaPPMap

**Comment by wibily** [comment]
look at what was done for de-africa

**Comment by tephenavies** [comment]
I suggest making a few commits on the default branch:
* Delete all code
* Leave the `architecture` folder with architecture decision records
    * In a separate commit, add an ADR that says that we've decided to host the map on our managed maps platform and update other ADRs to **Status: Superseded** that are affected by this new decision. Also link to the new ADR (with a relative path to new ADR)
* If there are docs that are still relevant in a doc folder leave the docs folder
* Update README with a message similar to https://github.com/TerriaJS/de-africa-map/
    * Include instructions on how to restore the code (which will probably be to revert the code-deleting commit(s))

**Comment by AnaBelgun** [comment]
@steve9164 is it possible not to action DE Africa yet? I need to discuss with you first what does that mean for the team taking it over next year? they also want to fork this for their own South African platform and they wanted to have a look at the code soon.

**Comment by tephenavies** [comment]
If others are going to look at the repo, we should either bring it up to date now, or remove old code, otherwise they're looking at how it used to work. It's too hard to communicate that the repo isn't up to date, and to say which parts are and aren't.

**Comment by wibily** [comment]
decision during sprint planning: Ana/Crispy to send email informing them of the deletion. Map specific config files to be sent when they want it

**Comment by zoran995** [comment]
Hi @AnaBelgun, are there any updates on this? Is it still relevant?

**Comment by AnaBelgun** [comment]
not relevant any longer, can be closed. thank you.
