### ISSUE TITLE
Mobile: Add exit compare button

### ISSUE THREAD

**Issue by wibily** [TerriaJS/terriajs#5781]
When a user visit a story with a compare mode in it, we want to give them the ability to view the story and then exit the compare mode. We, (Ana, Phil, Nanda, Will) decided in a meeting on the 2/9 that it is acceptable if they are not able to re-enter the compare mode in mobile.
![IMG_2222 PNG](https://user-images.githubusercontent.com/4196561/131801347-2e194e83-64b9-41b5-bc4f-9434d717b265.png)

**Comment by zoran995** [comment]
![image](https://github.com/user-attachments/assets/89b3f5ca-18e2-42c2-9204-3b0084d287f8)
Compare buttons are available on mobile while viewing the story. Let me know if I misunderstood the issue
