### ISSUE TITLE
Mobile: Check whether optimisation slider impacts mobile experience

### ISSUE THREAD

**Issue by wibily** [TerriaJS/terriajs#5783]
Does the following bar do anything? If not, we should remove it for mobile otherwise leave as is:
![IMG_2225 PNG](https://user-images.githubusercontent.com/4196561/131801818-d8cd05be-557d-417e-afab-cf465a55213f.png)

**Comment by AnaBelgun** [comment]
@philipgrimmett @na9da @will 
Following testing, I observed that for: 
**1) Image optimisation** - I could not see any changes in visualisation nor performance when ticking the "use native device resolution" 
**2) Raster Map Quality slider** - I did see changes in the visualisation from high quality to lower when moving the slider

Hence my suggestion is to remove the Image Optimisation from mobile and leave the Raster map quality slider.

**Comment by will** [comment]
Yeah remove it

**Comment by meh9** [comment]
> **1) Image optimisation** - I could not see any changes in visualisation nor performance when ticking the "use native device resolution" **2) Raster Map Quality slider** - I did see changes in the visualisation from high quality to lower when moving the slider

Both settings have significant visual impact if you have a high resolution screen. The higher resolution you have the more impact it has.

**Comment by meh9** [comment]
Use Native Device Resolution OFF:
![native off](https://user-images.githubusercontent.com/5283003/142381781-b8386a77-46bf-447b-a55a-887d2c826ecd.jpg)

Use Native Device Resolution ON:
![native on](https://user-images.githubusercontent.com/5283003/142381749-d786a90e-85b1-4118-b2f3-b8c88ee156b3.jpg)
