### ISSUE TITLE
Mobile: Fix 'copied to clipboard' styling

### ISSUE THREAD

**Issue by wibily** [TerriaJS/terriajs#5784]
![IMG_2228 PNG](https://user-images.githubusercontent.com/4196561/131801988-61434e8b-652e-45bf-b60a-12cc468ec6de.png)

**Comment by na9da** [comment]
Can't repro on my android browsers.

**Comment by zoran995** [comment]
This seems to be resolved; I can't reproduce it on iOS, and na9da confirmed it can't be reproduced on android. Feel free to open a new issue if still happening
