### ISSUE TITLE
Mobile: Remove opacity from feature information

### ISSUE THREAD

**Issue by wibily** [TerriaJS/terriajs#5788]
Feature info should be solid colour
![IMG_2238 PNG(1)](https://user-images.githubusercontent.com/4196561/131802630-81a84b76-7e84-40c2-ad14-2fbbd1f534f0.png)

**Comment by na9da** [comment]
I think the reason why the feature-info-panel is translucent is because the search box which is part of a larger mobile modal is active. If you close the search bar, it returns to full opacity. Does this need fixing? :thinking:

**Comment by zoran995** [comment]
This is not happening anymore
