### ISSUE TITLE
Mobile stories: make left/right arrows visible

### ISSUE THREAD

**Issue by wibily** [TerriaJS/terriajs#5790]
Check with @philipgrimmett if this design can work
![Screen Shot 2021-09-02 at 5 40 37 pm](https://user-images.githubusercontent.com/4196561/131803047-5fef71a4-4b0d-4c64-9063-cc6de7f289bc.png)

**Comment by zoran995** [comment]
Buttons are not available on mobile
![Image](https://github.com/user-attachments/assets/222202cb-96e9-413d-b561-e83cc083df2d)
