### ISSUE TITLE
When using mouse wheel or touch pad to zoom, zoom at the pointer location

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#580]
Currently, when using a mouse wheel or touch pad to zoom in the view is zoomed at the centre of the Cesium viewport. It is more intuitive if when zooming we zoom into where the mouse pointer currently is.

**Comment by meh9** [comment]
Note that Leaflet zooms in on the pointer location, so we are currently inconsistent.

**Comment by kring** [comment]
Dan just opened a pull request for this in Cesium:
AnalyticalGraphicsInc/cesium#2810
