### ISSUE TITLE
Colour range for regions is faded 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#5805]
To test: 
**AREMI - Solar -> Rooftop Solar - colour binning not the same**

v7: 
- https://nationalmap.gov.au/#share=s-tGBFlN56F3eCICfNZcaxaYgCLaV
![image](https://user-images.githubusercontent.com/18452161/132800776-ce1f798e-cf7a-4833-bd21-7629a3521e6a.png)

v8: 
- https://nationalmap-2021-09-03.nm.terria.io/#share=s-A64zKh4pJfH4JxtDl4re1sQzA32
![image](https://user-images.githubusercontent.com/18452161/132800837-1aef4ef1-4ea7-4b3d-b32a-0e0c0041e06a.png)

**Comment by nf-s** [comment]
This is due to logarithmic binning in v7, which isn't supported in v8 currently

**Comment by nf-s** [comment]
Adding log scale might be useful for https://github.com/PacificCommunity/Terria-PacificMap/issues/70

**Comment by nf-s** [comment]
Closing - we have somewhat fixed this with #5822 - and there is another ticket for implementing color binning https://github.com/TerriaJS/terriajs/issues/4228
