### ISSUE TITLE
CSV Postcode header matching fails if there is a space before Postcode

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#581]
When writing a CVS with postcodes, the figuring out that it's a postcode based CSV fails if there are spaces in the header definition for the Postcode column.

This works:

```
Thing,Postcode
400, 2615
```

This fails:

```
Thing, Postcode
400, 2615
```

**Comment by kgrochow** [comment]
Fixed in absNew branch which isn't merged yet.  The fix is trivial if you need it before the end of the week.

**Comment by meh9** [comment]
Not urgent at all.

**Comment by kgrochow** [comment]
This fix was merged somewhere along the way.
