### ISSUE TITLE
Add ABS SDMX metadata 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#5824]
If by 'metadata link' we mean: 

Metadata URL http://stat.data.abs.gov.au/sdmx-json/dataflow/RT 

Here is the equivalent link in the new ABS Data API. The URL below returns XML by default, but it will also return json if you use the following header "accept: application/vnd.sdmx.structure+json"
This is a standard URL format that will return metadata for all our dataflows.
https://api.data.abs.gov.au/dataflow/ABS/RT?references=all 

Additionally, next week we will update all our dataflows to include an "External Resource" annotation. This annotation will link to the Methodology section for that publication on the ABS website, which has information on how the data was collected, processed, etc.
Once this feature is available we can send you an example.

**Comment by nf-s** [comment]
![image](https://user-images.githubusercontent.com/6187649/134849113-22d2772d-1460-480a-abcf-1f72f4e53643.png)

- [x] #5823

**Comment by nf-s** [comment]
Done!
