### ISSUE TITLE
Specifying stroke-opacity for geojson polygons in init files does not work

### ISSUE THREAD

**Issue by hakoncarlsen** [TerriaJS/terriajs#5870]
My assumption here, is that the parameter stroke-opacity should control the opacity of the outline of GeoJson polygons the same way as the cesium function Cesium.GeoJsonDataSource.load does.

I have a catalog item like this:

```json
{
    "name": "myname",
    "type": "geojson",
    "url": "https://urlFetchingGeojsonPolygons.com",
    "style": {
        "stroke": "#4400AA",
        "fill": "#4400AA",
        "fill-opacity": 0.4,
        "stroke-opacity": 0.5,
        "stroke-width": 1
    }
}
```

The parameter stroke-opacity does however not have an effect on the outline of the polygons specified in the GeoJSON file. 

I think I have found out why however. In the file GeojsonMixin.ts, there is a function called stylesWithDefaults(): 

https://github.com/TerriaJS/terriajs/blob/1dbf508460521de4b452a62d3a046b596e8537a3/lib/ModelMixins/GeojsonMixin.ts#L432-L464

The parameter options.stroke.alpha is overwritten by the parameter style["stroke-opacity"].
The variable which controlls the outline of the polygons, is however not options.stroke, it is options.polygonStroke.

By changing the code:

```javascript
 if (isDefined(style["stroke-opacity"])) {
      options.stroke.alpha = style["stroke-opacity"];
}
```

to 

```javascript
 if (isDefined(style["stroke-opacity"])) {
      options.stroke.alpha = style["stroke-opacity"];
      options.polygonStroke.alpha = style['stroke-opacity'];
}
```

the opacity of the polygon-outlines changes as specified by the parameter stroke-opacity. I could make a pull-request, but this is all a bit confusing to me.

GeojsonMixin uses the function geojsondatasource.prototype.load in terriajs-cesium:

https://github.com/TerriaJS/cesium/blob/terriajs/Source/DataSources/GeoJsonDataSource.js#L901-L994

This function  expects the parameters "polygonStroke" and "polylineStroke". But according to the documentation above the function, this is not the case. It seems like at some point, terriajs-cesium has changed the function to accept new options, but according to the documentation, the options it accepts is the same as the original cesium function.

**Comment by tephenavies** [comment]
I think the change you've suggested is correct. `polygonStroke.alpha` should be set as well as `stroke.alpha`.

**Comment by nf-s** [comment]
I have made this fix in PR

- [x]  https://github.com/TerriaJS/terriajs/pull/5900

**Comment by nf-s** [comment]
Should be fixed since https://github.com/TerriaJS/terriajs/pull/5900
