### ISSUE TITLE
Layer persistence across browser sessions

### ISSUE THREAD

**Issue by 867530-Nan** [TerriaJS/terriajs#5938]
Heya TerriaJS team,

I'm wondering if there's a recommended way for caching selected layers via localstorage / another method?? 

Objective: Selected layers persist in the workbench across browser sessions.

I accomplished this in version 7 by simply storing the name & url of selected layers, and, upon page load, finding the layers and calling each item's 'toggleEnabled' method. Layer-Persistance was trivial with previous versions, because of each catalog item being able to toggle itself. However, with version 8, it looks like adding a layer to the workbench is done through passing the entire layer into the 'terria.workbench.add' method. Because not all layers are loaded on app-launch (e.g. layer group layers), this is appearing to be much more involved.

Any ideas / implementations?

Thanks

**Comment by zoran995** [comment]
Hi @867530-Nan,

I would look into how share URLs are implemented, this could reuse most of the logic. V8 version for adding items to workbench uses array `workbench` as part of `initData` ([docs](https://docs.terria.io/guide/customizing/initialization-files/)). The same is done for shareURL, when you create a share URL it will create a json that contains all models added to the workbench as part of an array `workbench`
https://gist.githubusercontent.com/zoran995/a11c124e253dbdb1200f1ad7036db857/raw/e422a32283fbbddb9f68b7a819a4cc913f8ff4b8/share-url.json
When opened, share URL is applied to the Terria as a regular initialization file, and I believe this part is most relevant for adding data workbench:
https://github.com/TerriaJS/terriajs/blob/6b68a43bfc1c4b294965a6a8036e285ccc4c1b00/lib/Models/Terria.ts#L1417-L1430

I would consider those two options: 
1. converting data when loaded from localStorage into the structure of initData, push it to `initSources`, and let Terria do the rest (same as for share), or
2. read workbench item ids from localStorage and trigger `terria.getModelByIdOrShareKey`

I mentioned localStorage but any other caching method should work.

Zoran

**Comment by 867530-Nan** [comment]
Really appreciate the help with this Zoran. My current solution - from your suggestion - is to simply update / store the 'share url' when workbench items are added/removed. Then on page load, fetch this value from localStorage and update browser location.href. Works like a charm without any first-paint glitch effect. 

Thank you again.

**Comment by stevenjh** [comment]
Hi @867530-Nan , wondering if you're able to share how you implemented this or if it made it into a pull request?
