### ISSUE TITLE
Timeline not enabled when adding an item to workbench using "Add to the map", and inconsistency with GA events fired on adding data

### ISSUE THREAD

**Issue by na9da** [TerriaJS/terriajs#5966]
When adding a time varying item to the workbench by using "Add to the map" button in the catalog explorer, the timeline doesn't get enabled for some reason.

**Comment by tephenavies** [comment]
Caused by change that removed timelineStack.addToTop from the Add to the map button. See comment https://github.com/TerriaJS/terriajs/pull/5821#discussion_r758000152

**Comment by nf-s** [comment]
Sorry 😢

**Comment by tephenavies** [comment]
I think there's another inconsistency: 1 method of adding doesn't fire an analytics event. I'll investigate and fix that too.
