### ISSUE TITLE
Investigate issues with WPS integration in v8

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#5988]
Please refer to: 
- https://github.com/TerriaJS/terriajs/discussions/5942
- https://github.com/opendatacube/datacube-wps/issues/135
- https://github.com/TerriaJS/RaPPMap/issues/105

**Comment by nf-s** [comment]
https://github.com/opendatacube/datacube-wps/issues/135#issuecomment-971134026

> 
> ODC-WPS is returning Terria catalog models in the old version 7 format. We try to automatically upgrade it to version 8, but there seems to be an issue here:
> 
> https://github.com/TerriaJS/terriajs/blob/80737c16a4d7e8fe0616f292bd24d599664a1ea8/lib/Models/Catalog/Ows/WebProcessingServiceCatalogFunctionJob.ts#L416-L434

**Comment by nf-s** [comment]
closed by https://github.com/TerriaJS/terriajs/pull/6030
