### ISSUE TITLE
new terria version doesn't show "Use Native Device Resolution" on mobile

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#5989]
The latest version of Terria is for some reason not showing the "Use Native Device Resolution" setting on mobile, but it's still there on a computer. Please enable the setting on mobile again as it does improve the rendering quality (I just used it a couple of days ago).

On computer:
<img width="432" alt="Screen Shot 2021-11-18 at 09 18 26" src="https://user-images.githubusercontent.com/5283003/142291969-04ff16de-b8c2-4118-98a5-8c1f8086f37e.png">

On mobile:
![Screenshot_2021-11-18-09-18-03-86_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/5283003/142292002-bed3797d-987a-4bcc-9510-e472ffd4495a.jpg)

**Comment by zoran995** [comment]
This one is on me, I went after @AnaBelgun suggestion here https://github.com/TerriaJS/terriajs/issues/5783#issuecomment-912231985 and it got removed from mobile. Creating a PR for this - _edit #5990_

**Comment by AnaBelgun** [comment]
Hi @zoran995 no problem; it's on me following an internal discussion what's useful and not for a mobile user. Thank you for the fix; it seems some users _do_ find it useful :)
