### ISSUE TITLE
Design 'What's new" 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#6002]
A number of users and product owners would like to flag to end users: 
- new datasets published 
- new features

What are the options to flag those while not introducing yet another popup window?

**Comment by philipgrimmett** [comment]
@AnaBelgun some followup questions on the brief:

1. New datasets: do we currently have a way of automatically collating a list recently published datasets (eg. <2 months), or will that list have to be manually maintained? Similarly, should all new datasets appear in the 'what's new' feed, or just items relevant for the broadest user group?
2. Is the 'What's new' feed expected to be manually curated eg. titles, blurbs, links to blog posts etc.? Will it be text-only, or require images, videos etc.? What is the expected cadence for posting updates to this feed?

**Comment by AnaBelgun** [comment]
hi @philipgrimmett 
1. we don't have an automatic way yet to collate a list of datasets published. If we apply a manual process, then a curated list (i.e. the relevant items for the broadest group); if automatic, then probably easiest would be to show all new in the list. The 'new' will be compared to latest release of the catalogue. 

2. Ideally, not manually curated. We would start simple, with datasets list and a generic pop-up/other. 

3. Another new items would be features, not just datasets. And they would be generated from terriajs rather than the catalogue. Again, a question for the team. 

@nf-s @steve9164 @wibily would it be possible to automate the generation of new datasets list in any way? or the new features list? 

or, instead of having a pop-up approach, maybe try having the "new" tool tip next to the datasets, or features. 

or, a combination: pop-up approach for datasets list (because they are usually buried deep in the catalogue) and a tool-tip approach for the features, because they are visible on landing page/s.

**Comment by wibily** [comment]
@philipgrimmett 
After discussions with @nf-s and @steve9164 due to the lack of a proper backend for now, this is best implemented with a manually curated list of featured ids which is loaded in as part of initialisation urls.
I imagine that visually it might look something like the following:
![exampleFlags](https://user-images.githubusercontent.com/4196561/151915447-eb475f25-bbb9-4b93-9062-3957f213ac78.png)

**Comment by philipgrimmett** [comment]
If the goal is to provide visitors with a quick summary of recent map changes (new datasets and feature releases etc.) and we expect all content will be manually curated for the foreseeable future, I'd suggest we introduce a notifications / what's new button above feedback that launches a simple full screen or modal 'what's new' blog. Concise post summaries should either link to longer external articles or open dataset previews in the catalogue. Concept videos below.

Full screen (pros: minimises distractions, retains map UI arrangement, cons: new pattern, might require more dev time )
https://user-images.githubusercontent.com/5292858/155062833-cf8d6ab2-2b94-47d1-8306-03fb73f96cdb.mov

Modal (pros: easier to implement, cons: adds more visual clutter)
https://user-images.githubusercontent.com/5292858/155062874-c6b5724a-642b-409f-a6d6-9f13f0562457.mov

Re. publishing;
- Who is responsible for creating new posts?
- Will some posts be shared across multiple maps?
- Will clients need us to post for them, or would we provide a simple CMS?

**Comment by AnaBelgun** [comment]
Ana to refine with Phil on options. 
- create a page with the new items: data and features
- maintaining the content - to refine

**Comment by AnaBelgun** [comment]
Update 7 Jun 2022: 
- discussed with NSW DTVS team and agreed that this will be a maintenance overhead and is not in the current contract. 
- will close and reopen if re-prioritised.
