### ISSUE TITLE
Investigate why checkboxes don't work in some CI builds.

### ISSUE THREAD

**Issue by na9da** [TerriaJS/terriajs#6003]
How to reproduce issue:

- Visit http://ci.terria.io/handle-external-link/
- Open "Map Settings" or the Feedback form
- Click the checkboxes
- See that the checboxes don't change

So far we have found that the generated code for `HiddenCheckbox.tsx` is different for the working and broken one.

Generated code for working build:
```js
return /*#__PURE__*/_react["default"].createElement(_StyledInput, _extends({
    type: "checkbox"
  }, props, {
    ref: ref,
    "aria-checked": isIndeterminate ? "mixed" : props.checked
  }));
```

Generate code for broken build:
```js
return /*#__PURE__*/_react["default"].createElement(_StyledInput, {
    type: "checkbox",
    ref: ref,
    "aria-checked": isIndeterminate ? "mixed" : props.checked
  });
```

See how in the broken build, props don't get passed to createElement. Because `props` get elided, the hidden input element will not trigger `onChange` callback passed via props.

We need to narrow down and figure out if this is caused by some updated package or something else.

**Comment by wibily** [comment]
timebox to 1 day to investigate.
Heissenbug that only affects Mike's machine and CI on handle-external-link

**Comment by na9da** [comment]
It now affects the build for main too - http://ci.terria.io/main/

**Comment by na9da** [comment]
Looks related to - https://github.com/styled-components/babel-plugin-styled-components/pull/359#issuecomment-976521077 
and a fix is on the way - https://github.com/styled-components/babel-plugin-styled-components/pull/361

**Comment by klarstrup** [comment]
just fyi this problem is not in `babel-plugin-styled-components` 2.0.0 - only 2.0.1
