### ISSUE TITLE
[Development Enviroment] AllowProxyFor is not working

### ISSUE THREAD

**Issue by malnajdi** [TerriaJS/terriajs#6023]
Greetings, 

I am using the latest version of terriajs 8.1.12 i have following the setting up a development env with yarn using workspaces.
The terriajs package exists in /packages/ now and i ran everything smoothly and i can edit and change configs. 

But when i add any url to AllowProxyFor and restart pm2 i still don't get the URLs to be proxied. 

Not sure what is the error.

**Comment by tephenavies** [comment]
Hey @malnajdi. One problem you might be having is that the proxy server purposely excludes proxying to "local" IP addresses. This is to prevent the proxy from being used to access internal servers that are accessible to the server running terriajs-server but behind a firewall from users.

For local testing, you can remove some IP ranges from the exclusion list by copying and customising `blacklistedAddresses` in your own devserverconfig.json, or replacing it with an empty array:
https://github.com/TerriaJS/terriajs-server/blob/d96739c4702383c2301f473768c52cb896fb8619/serverconfig.json.example#L34-L61

For any deployed application available to others (intranet or internet) you should consider the risks of customising `blacklistedAddresses` before changing it.

**Comment by malnajdi** [comment]
Hi @steve9164, I did try to proxy both localhost and external DNS names and they all did not get proxied. I am not sure how to debug this.
