### ISSUE TITLE
How to handle canonical and user-added datasets

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#6031]
...to be refined

How do we tell users which datasets are canonical, and which aren't

For example - I have injected a dataset into [this URL](https://nationalmap.gov.au/#start={%22initSources%22:[{%22catalog%22:[{%22name%22:%22Public%20Weighbridge%20List%20-%20Jul%202020%20%22,%22type%22:%22magda%22,%22recordId%22:%22dist-dga-9bba55fa-1d12-42f3-9eaa-2c5f32f7bfb6%22,%22url%22:%22https://data.gov.au/%22,%22id%22:%22data.gov.au-postMessage-dist-dga-9bba55fa-1d12-42f3-9eaa-2c5f32f7bfb6%22}],%22workbench%22:[%22data.gov.au-postMessage-dist-dga-9bba55fa-1d12-42f3-9eaa-2c5f32f7bfb6%22],%22baseMapName%22:%22Positron%20(Light)%22}]}) , which is not apart of the NationalMap catalog.

But if you open the catalog you will now see it at the bottom

### Thoughts

- Datasets should not be added to catalog outside of "official" init sources - for example the `init` files in `config.json`
- User added data can be shared (provided there are no files) - but with a clear warning that the data is **not** affiliated with the map
- If a dataset as been significantly changed by the user (for example styling traits) - and then a share link created - should we warn users of share link that changes have been made?

**Comment by tephenavies** [comment]
> If a dataset as been significantly changed by the user (for example styling traits) - and then a share link created - should we warn users of share link that changes have been made?

Yeah this might have to be considered. Probably the easiest change here that would completely change the meaning of a dataset is changing the legend. And since share data/urls are user generated content there's no way to know if it's safe other than checking the saved data.
