### ISSUE TITLE
CSV download disable issue

### ISSUE THREAD

**Issue by imakihi** [TerriaJS/terriajs#6051]
I wanted to disable my csv file download hyperlink at the top-right of my chart using "disableExport":true but I could not remove the link. I could disable an Export data button from the "About Data" panel though.

<img width="449" alt="2021-12-16_9-48-17" src="https://user-images.githubusercontent.com/4824436/146423182-fda8b432-53b2-413b-93ca-f0d85d33a05f.png">

It would be nice if "disableExport" could take care of both export/download capabilities.

Thank you!

**Comment by staffordsmith83** [comment]
The issue is now resolved, download button is no longer available on charts for catalog items marked with `"disableExport" : true`
