### ISSUE TITLE
App crash when duplicating a TableMixin type item.

### ISSUE THREAD

**Issue by na9da** [TerriaJS/terriajs#6058]
There is an app crash when calling `duplicateModel` on any item that inherits from `TableMixin`. This happens for eg when rendering a feature info chart for the item. 

Because we use `toJS` to copy a non-loadable model stratum:
https://github.com/TerriaJS/terriajs/blob/90e42a5d8f1a852539658d74406285f9fd34b21a/lib/Models/Definition/CreateModel.ts#L99-L103

if the stratum contains a nested computed object then `toJS` throws an error:

```
Uncaught Error: [mobx] 'keys()' can only be used on observable objects, arrays, sets and maps
```

 `TableMixin` sets a loadable stratum as the value of `legend` in the default stratum. This triggers the crash when invoking `toJS` on the default stratum.

https://github.com/TerriaJS/terriajs/blob/90e42a5d8f1a852539658d74406285f9fd34b21a/lib/ModelMixins/TableMixin.ts#L63-L69

**Comment by na9da** [comment]
To be discussed with @nf-s for a solution.

**Comment by KeyboardSounds** [comment]
When this is fixed, we can get rid of the temp fix in https://github.com/TerriaJS/terriajs/blob/f2590d135f6f267da73399d0de074aeac505c53a/lib/Models/Catalog/Ows/SensorObservationServiceCatalogItem.ts

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/6083
