### ISSUE TITLE
Centralise color definitions in CSS

### ISSUE THREAD

**Issue by nahidakbar** [TerriaJS/terriajs#606]
I am finding the current way colors are mapped a bit hard to work around. Not sure what the standard practice is but it has color codes everywhere.

e.g. 

<pre>
...
// Panels
@panel-background-color: #2F353C;
@panel-text-color: #CCCCCC;
@panel-emphasized-text-color: #FFFFFF;
@panel-selected-text-color: @highlight-color;
@panel-box-shadow: 2px 2px 5px rgba(0,0,0,0.26);
@panel-element-border: 1px solid rgba(100,100,100, 0.6);
@panel-section-background-color: #282D32;
@panel-form-input-background-color: #838689;
@panel-form-input-text-color: #FFFFFF;
@panel-form-button-background-color: #A1A3A6;
@panel-form-button-text-color: #FFFFFF;
...
</pre>

So for my custom widgets, I have to either refer to things like "panel-background-color" or write custom color codes which will go out of date as soon as one of the original colors change. Also makes re-themeing harder.

Might I recommend moving to somehting like:

<pre>

/* all the unique colors I could find; in order of brightness; put them into a separate less file plz */
@color1: #282D32;
@color2: #2F353C;
@color3: #555555;
@color4: #666666;
@color5: #757f88;
@color6: #838689;
@color7: #A1A3A6;
@color8: #CCCCCC;
@color9: #FFFFFF;
@colorH: #68ADFE;

...

// Panels
@panel-background-color: @color2;
@panel-text-color: @color8;

...
</pre>

etc.

I believe less can also do things like rgba(red(@color8), green(@color8), blue(@color8), 0.5); and brightening and darkening etc functionality.

@kring @philipgrimmett

**Comment by RacingTadpole** [comment]
@AlexGilleran / @chloeleichen - does our new css modules approach help here?

**Comment by chloeleichen** [comment]
sure we can do something like that

**Comment by stevage** [comment]
@AlexGilleran has been refactoring a lot of this stuff. Is this still relevant?

**Comment by AlexGilleran** [comment]
Kinda... it's better than it was but that's by accident, we haven't deliberately done this refactoring. `#FFFFFF` pops up in a lot of different places, for instance.

**Comment by kring** [comment]
Closing this because the new UI took a decent step toward solving the underlying problem, and I'm not sure the specific suggestion here (`color1`, `color2`, etc.) is the way we want to go.
