### ISSUE TITLE
Compare tool geojson don't work

### ISSUE THREAD

**Issue by zoran995** [TerriaJS/terriajs#6062]
Compare from workbench doesn't work for vector layers
Steps to reproduce:
- add vector layer (i.e. geojson)
- start compare tool from layer `show more actions` menu
- error is thrown 
![image](https://user-images.githubusercontent.com/19208948/147469999-82734a79-b75b-4f5e-be24-bd6fac7c270b.png)

**Comment by KeyboardSounds** [comment]
Yep, I can reproduce this.

@nf-s is this an easy fix, by any chance? It already works if you activate the splitter from the tool button on the right hand side

**Comment by nf-s** [comment]
I believe this is due to https://github.com/TerriaJS/terriajs/issues/6058
