### ISSUE TITLE
Show WMS names, not just titles

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#607]
Probably the real cause of issue #605 is that we only show the `title` of each WMS layer when fetching a getCapabilities request, not the `name`:

![screenshot 2015-03-27 12 14 50](https://cloud.githubusercontent.com/assets/678344/6860362/1fd94a18-d47b-11e4-9790-a301a0d67cd6.png)

Here we see dozens of indistinguishable layers "mass_concentration_of_chlorophyll_in_sea_...", because that's the title of each. Yet they each have a different `name`, like the `dR_MIM_n_obs` seen here, and a meaningful `abstract`.

Perhaps we need an option to indicate that a WMS catalogue's `name` properties should be shown instead of its `title` (`WebMapServiceCatalogGroup.js.createWmsDataSource`).

**Comment by kring** [comment]
Fixed by #608.
