### ISSUE TITLE
MagdaReference should accept request of overriding magda record aspects

### ISSUE THREAD

**Issue by mwu2018** [TerriaJS/terriajs#6088]
In some magda applications such as https://data.nsw.gov.au and https://data.gov.au, the "Open in DigitalTwin" or "Open in NationalMap" action will request the targeted terria (DigitalTwin or NationalMap) to render a dataset distribution referenced by a magda record. If the record's "dataset-format" aspect specifies the "WMS" format, the terria will try to render all layers at the WMS endpoint, which may cause some problems:
1. The WMS service endpoint may represent a complicated hierarchical structure, some layers may contain errors, which will cause the terria to completely abandon the rendering entirely.
2. The number of layers may be too large to be rendered at the same time.

In any cases, users will see an error message that does not tell the root causes. See https://github.com/TerriaJS/nsw-digital-twin/issues/519 for example.

A possible solution to the above problems follows.
When a record has "wms" format, treat it as "wms-group". This approach has been successfully used in DigitalTwin managed catalogue items because its magda records will have customised aspect called "terria" that tells MagdaReference the record is of "wms-group" type (format). However, magda records living outside of DigitalTwin do not have such aspect. If a record has no "terria" aspect, MagdaReference will get type info from the record's "dataset-format" aspect. We need a mechanism to override that "dataset-format" aspect. 

Luckily the external magda application can include "override" attribute in the message to DigitalTwin or NationalMap. This approach does not change external magda application's internal format logic. It only needs to make minimal changes in the post message in `magda-web-client/src/Components/Common/DataPreviewMapOpenInNationalMapButton.tsx` in magda repo. The code looks like this
```
            const id = "data.gov.au-postMessage-" + distribution?.identifier;
            const overriddenFormat = (distribution?.format.toLowerCase() === "wms") ? "wms-group" : undefined;
            const override = overriddenFormat
                ? {
                    "aspects": {
                        "dataset-format": {
                            "format": "wms-group"
                        }
                    }
                }
                : undefined;
            
            catConfig = {
                version: "8.0.0",
                initSources: [
                    {
                        stratum: "user",
                        catalog: [
                            {
                                name: distribution?.title,
                                type: "magda",
                                recordId: distribution?.identifier,
                                url: config.baseExternalUrl,
                                override: override,
                                id
                            }
                        ],
                        workbench: [id],
                        previewedItemId: override? id : undefined
                    }
                ]
            };
```

where `previewedItemId` is to tell the target to open the catalogue panel so the user can see the catalogue group.

Of cause MagdaReference needs to be modified to meet the override request.

**Comment by mwu2018** [comment]
https://github.com/magda-io/magda/pull/3299 creates `terria` aspect in a post message, which is better approach than the one in the above description.

**Comment by wibily** [comment]
@nf-s to verify approach
