### ISSUE TITLE
Opacity precision issue

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#6091]
![image](https://user-images.githubusercontent.com/6187649/149686451-06bc8e6f-0a53-4116-b251-7f792331c18e.png)

**Comment by zoran995** [comment]
I believe that I ran into this when working on #5344 and fixed it but a long time since I worked on that one 😃

**Comment by nf-s** [comment]
Yeah... Sorry it has taken us so long to review your PR 😞
