### ISSUE TITLE
Ideal Zoom not supported in Open Data Soft live data 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#6111]
'Ideal zoom" feature is not supported in Open Data Soft live datasets. 
Here are few examples: 

https://nsw.digitaltwin.terria.io/#share=s-4C9e12A8U1GmISB9aqLoxYkueqW

**Comment by wibily** [comment]
emma: unable to reproduce locally
Ana: confirmed fixed
