### ISSUE TITLE
Download chart data button - error message

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#6112]
It was noticed that the download data button has inconsistent behaviour for chart (able) datasets. 

**Working (i.e. CSV file created with charted dataset).** 
https://maps.dea.ga.gov.au/#share=s-blZFW2pswMZroPyMejRrfyPpQyj
![image](https://user-images.githubusercontent.com/18452161/151095440-5f174229-6566-4f94-923d-4a19964fb6a7.png)

Not working (i.e 404 error message shown)
https://nsw.digitaltwin.terria.io/#share=s-yliT5qzpSbAdZdfSfujUjNvddUc
![image](https://user-images.githubusercontent.com/18452161/151096265-901d0e6e-d893-4733-9e42-cc763a83318c.png)

![image](https://user-images.githubusercontent.com/18452161/151096300-c45f9b23-7250-400e-9871-e7ad29318c0f.png)

If related to availability of data to be downloaded, the button should appear only when data is available or change the error message to clarify to the user "data is not available to download".

**Comment by na9da** [comment]
Fix merged to terria in #6175
