### ISSUE TITLE
Print preview crashes the app

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#6123]
In https://github.com/TerriaJS/terriajs/blob/main/CHANGES.md#8119 

To replicate: 
- use https://preprod.nationalmap.gov.au/
- clicking print and print preview results in blanc screen 

![image](https://user-images.githubusercontent.com/18452161/152274589-52da9f89-2e65-4479-b1fd-3ef7a7a83905.png)

**Comment by wibily** [comment]
`gulp build-app` creates a build without this issue whereas `gulp release-app` creates a build with this issue. Problem is somewhere in the difference between creating a dev build versus a production build

**Comment by wibily** [comment]
fixes committed in wc-print2 branch. Problem appears in `<StyleSheetManager target={}>` where setting the target to the new document head seems to work but not when it is set to the rootNode
