### ISSUE TITLE
Enable 3DTiles to affect the loading progress bar

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#6130]
It would be great if 3DTiles could be included in the loading progress bar along the top of the screen. Apparently it's as simple as:

> yeah should be able to just hook into this event: https://github.com/CesiumGS/cesium/blob/main/Source/Scene/Cesium3DTileset.js#L486

**Comment by staffordsmith83** [comment]
Hooking into the loadProgress event results in a pretty jumpy progress bar, as Cesium requests tiles in batches. The total number of pending tiles is never exposed. What happens is that the progress bar jumps between halfway and full rapidly as cesium makes new batches of tile requests. As such the progress bar is not a good indicator of the time remaining to load the 3DTiles layer. But at least it does disappear when the 3DTiles layer is fully loaded!

![progress_bar](https://user-images.githubusercontent.com/7980991/169807650-6b92d7f8-95c7-49b5-88cd-3945d6f92f29.gif)

I feel that an indeterminate progress spinner may be more appropriate for these datasources (i.e. just spins until finished loading with no concept of progress), unless I can figure out a solution to translate the messages available into meaningful progress indicator.

**Comment by staffordsmith83** [comment]
@philipgrimmett thoughts from a UX perspective?

**Comment by philipgrimmett** [comment]
@staffordsmith83 Can we modify the progress bar to support indeterminate loading states? There's a bunch of UX research on this, but we probably don't have to overthink it. Unless we have some way of predicting significant load times, something like the video below should be fine:

https://user-images.githubusercontent.com/5292858/169940803-b2dd096c-b31d-4f2e-8f85-16e9f12f872f.mov

**Comment by staffordsmith83** [comment]
@philipgrimmett great idea, there is certainly an event fired when those data sources start loading and when they finish, so I should be able to implement that. Leave it with me!

**Comment by staffordsmith83** [comment]
@philipgrimmett and @steve9164 any objections to me using a component library for this so that we can get some nice animation for indeterminate progress bar? I should be able to keep styling pretty similar.

https://chakra-ui.com/docs/components/feedback/progress
MIT license, open source, actively maintained, 26k stars.

![Animated Progress Bar](https://user-images.githubusercontent.com/7980991/169942118-ef8f8947-bd6d-4fc9-a59d-5971acf3e715.gif)
