### ISSUE TITLE
Colours repetition 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#6133]
Although we are using a 22 colour scheme palette, it seems that for 20 items listed in the workbench, not all the colours in the scheme are used at the same time: https://nationalmap.gov.au/#share=s-miqh4r15gAQqdBIBbThknLozR2f. 
This issue makes it harder to differentiate  (up to 20) zones on the map.

**Comment by nf-s** [comment]
Sorry @AnaBelgun I gave you wrong information, we use a 8-class colour scheme palette for items which have no styling.

https://github.com/TerriaJS/terriajs//blob/86d68c06f681d5e043884d1d1b299b4ba7058b57/lib/Core/StandardCssColors.ts#L43-L54

It looks like

<img width="716" alt="image" src="https://user-images.githubusercontent.com/6187649/161694639-fd556f97-4809-499d-90b4-c33d335040eb.png">

The 22 colour scheme palette is used for "enum" data types types - it is used to represent different values for a single dataset - for example https://nationalmap.gov.au/#share=s-963Focm6BC3DhJ1vllTIkb3M1qQ

I think we should keep the 8-class colour scheme for datasets with no styling, and 22-class for "enum" data types

The SIP data is quite a special use-case - I would rather just style it manually and keep our existing defaults - https://github.com/terriajs/nationalmap/issues/1129
