### ISSUE TITLE
Error pages

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#614]
GA have asked for error pages for the common HTTP error status codes:
- 401
- 403
- 404
- 500

It's complicated apparently, GA and NICTA sysadmins probably need to advise on how we should do it.

**Comment by hilarycinis** [comment]
Please ensure error codes have some kind of natural language explanation that accompany them, were possible!! Give us a yell if you need authoring help.

**Comment by stevage** [comment]
These codes have to be implemented in NM (with NM branding), TerriaJS-Server (to know to serve up the right page if it occurs), and here. The action here is to have a couple of generic Terria-branded pages.

Can 401 and 403 ever occur in Terria?

**Comment by kring** [comment]
Steve implemented this awhile ago.
