### ISSUE TITLE
When webgl context cannot be created v7 terriajs shows a nice error but in v8 terriajs the app crashes.

### ISSUE THREAD

**Issue by na9da** [TerriaJS/terriajs#6159]
Error in v7:

![image](https://user-images.githubusercontent.com/1430/155054617-c4a30dfb-38cb-491f-bb90-e43d64f4afdc.png)

To test in firefox, you can temporarily disable webgl from `about:config` by setting `webgl.disabled` to `true`.

**Comment by tephenavies** [comment]
Set up a development environment: https://docs.terria.io/guide/contributing/development-environment/

When checking out a version of `terriajs`, just use the latest (i.e. `origin/main`). To make the version number match, you can put `"terriajs": "*"` into the package.json of TerriaMap before running `yarn install`.

**Comment by tephenavies** [comment]
Of interest for this ticket: https://github.com/TerriaJS/terriajs/blob/main/lib/Models/Cesium.ts

and `terria.raiseErrorToUser`

**Comment by tephenavies** [comment]
Using 4.x of MobX. Gist of MobX: https://mobx.js.org/the-gist-of-mobx.html

**Comment by tephenavies** [comment]
Check docs for CesiumWidget: https://github.com/TerriaJS/terriajs/blob/4ece7aa1c51da67ff8cada5cb915a126c07142ed/lib/Models/Cesium.ts#L165-L168

Docs on cesium site: https://cesium.com/learn/cesiumjs/ref-doc/CesiumWidget.html

**Comment by tony-p1** [comment]
http://get.webgl.org/
