### ISSUE TITLE
Polylines are not updated in Leaflet

### ISSUE THREAD

**Issue by himby** [TerriaJS/terriajs#6189]
in the _updatePolyline method of LeafletVisualizer.ts there is a section updating existing polyline positions:
``` 
const curLatLngs = polyline.getLatLngs();
let bPosChange = latlngs.length !== curLatLngs.length;
for (let i = 0; i < curLatLngs.length && !bPosChange; i++) {
  const latlng = curLatLngs[i];
  if (latlng instanceof L.LatLng && latlng.equals(latlngs[i])) {
    bPosChange = true;
  }
}
if (bPosChange) {
  polyline.setLatLngs(latlngs);
}
```
In v7 Js version of the same code:

```
var curLatLngs = polyline.getLatLngs();
var bPosChange = latlngs.length !== curLatLngs.length;
for (var i = 0; i < curLatLngs.length && !bPosChange; i++) {
  if (!curLatLngs[i].equals(latlngs[i])) {
    bPosChange = true;
  }
}
if (bPosChange) {
  polyline.setLatLngs(latlngs);
}
```

If I add a Not-operator to   **if (latlng instanceof L.LatLng && !latlng.equals(latlngs[i]))**  in the v8-version the polylines seems to update correctly. I'm just wondering if this is just a blunder during port to TS? or is there another reason behind this?

**Comment by tephenavies** [comment]
Hi @himby. I think you're right. Could you open a PR to fix this? And do you have an example dataset that we can verify the problem with? (If you don't have an example, I'll craft something in CZML or similar).
