### ISSUE TITLE
Some datasets throw error when added from Search results

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#6214]
Steps to reproduce:
- go to NationalMap https://nationalmap.gov.au/
- search for "native titles" and a list with relevant datasets will be displayed
- click on Native Titles Determinations and / or Native Titles Determinations outcomes
- an error message will be displayed
![image](https://user-images.githubusercontent.com/18452161/160332950-2d3bfdc7-e693-4a4f-a159-733fa7548445.png)
- go to data.gov.au group
- next, expand the National Native Title Tribunal and add the same data onto the map (it works)
![image](https://user-images.githubusercontent.com/18452161/160332890-9f91e093-d8be-404e-93f1-50a3553708d4.png)

**Comment by nf-s** [comment]
This is due to the nature of the `CatalogIndex`.

This is a JSON file we generate manually which contains the index used for searching - it is never going to be perfect - but it provides much faster searching.

We just have to remember to re-generate this file frequently to minimise errors

**Comment by nf-s** [comment]
See https://github.com/TerriaJS/saas-catalogs-public/issues/118

**Comment by nf-s** [comment]
I have just updated catalog index - so "Native Title Determinations" is now working
