### ISSUE TITLE
Templated feature info popup not outputting templated values

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#6228]
There are problems on NatMap with templated feature info popups not correctly incorporating the raw values in the template output. This issue was identified by a user who took the time to contact us.

Using this share URL: https://nationalmap.gov.au/#share=s-4hOUMxGiSHgQjxqGBJuuM7b5SqN
The layer is National -> Energy -> Electricity -> Network -> New -> Distribution -> Substations.

1. Notice that it is using the field `Indicative new generation connection capacity available (MW)` by default to visualise the points on the map, and the points have different colours and sizes indicating that there are values for that field.
2. Click any of the points. 
3. You will see that the `Indicative new generation connection capacity available (MW)` field is not showing any values.
4. Click `Show Raw Data`.
5. You will see that `existing_new_connection_capacity` actually has a value.

The value `Indicative new generation connection capacity available (MW)` is a remapping from the "raw" field `existing_new_connection_capacity` which can be found in the catalog (https://github.com/TerriaJS/saas-catalogs-public/blob/main/nationalmap/catalog/energy/prod.json):
```
                            {
                              "name": "existing_new_connection_capacity",
                              "title": "Indicative new generator connection capacity (MW)"
                            },
```

Please fix the feature info templating to correctly output values.

<img width="1920" alt="Screen Shot 2022-03-30 at 16 00 37" src="https://user-images.githubusercontent.com/5283003/160954494-8e6b19bc-a6ea-4c78-912b-5ec1be3d413c.png">

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/6441
