### ISSUE TITLE
JSON submodules

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#623]
Maintaining large config json files for providers is pretty difficult and very error-prone. Should we consider a JSONCatalogGroup type that loads another JSON file as its contents?

Or is that just silly?

**Comment by stevage** [comment]
Hmm, probably not necessary, since it's already possible to split a config file up and refer to each one in the overall `config.json`. Only really an issue if you're trying to call that config file from a URL.

**Comment by kring** [comment]
FWIW, an editor that knows how to collapse JSON sections is a huge help.

As our catalog gets big, this could be useful just as a way to avoid requiring the client to download a giant catalog at startup, especially if we don't download the nested catalogs until the user opens the group.  We'll need a better approach to catalog searching, though.

**Comment by stevage** [comment]
> FWIW, an editor that knows how to collapse JSON sections is a huge help.

I'm using Sublime, and even still it's tough. Particularly if for some reason your syntax gets broken, I can't find any easy way to repair it.

**Comment by axman6** [comment]
There’s a JSON sublime package which does live syntax validation which you might find useful. It complains about comments in json which are accepted in sublime settings files, but it’s quite nice apart from that. Also using a decent colour scheme which supports json well helps a lot. the Neon theme works well (though is somewhat ugly) and can be set as the syntax for only json files by going to Preferences -> Settings - More -> Syntax specific - User and adding something like:

```
{
  "color_scheme": "Packages/Colorsublime - Themes/Neon.tmTheme"
}
```

(I have the Neon theme installed via Colorsublime)

Finally, installing jq can make working with json much easier; you can use it to reformat json by running

```
cat foo.json | jq . | subl
```

Hope that helps a bit, happy to answer questions on HipChat if you have any.
