### ISSUE TITLE
Print preview triggers white screen

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#6256]
Print preview triggers a white screen 
Go to https://staging.nm.terria.io/
- click on print/share
- click on print preview
- white screen

**Comment by tephenavies** [comment]
Caused by a bad code merge that deleted the import of `PrintView`. This sort of thing should be caught at compile time by Typescript, but StandardUserInterface.jsx is still in Javascript. I am now exploring feasibility of changing this file to Typescript.
