### ISSUE TITLE
DEAfrica and DEAustralia catalogue start page shows just a "/"

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#6277]
The DEAfrica and DEAustralia catalogue start page shows just a "/" instead of the normal `Select a dataset to see a preview` text and map button:
<img width="439" alt="Screen Shot 2022-05-02 at 14 22 05" src="https://user-images.githubusercontent.com/5283003/166184104-51f4dd12-9ea4-40ab-bbcf-2559f732935c.png">
<img width="539" alt="Screen Shot 2022-05-02 at 14 22 18" src="https://user-images.githubusercontent.com/5283003/166184114-6c31e43b-8094-4f57-9072-6e1deb628570.png">

Meanwhile, all other maps show the usual screen:
<img width="702" alt="Screen Shot 2022-05-02 at 14 23 48" src="https://user-images.githubusercontent.com/5283003/166184129-0f7809bc-5e97-4ed7-bbb7-d002872d3f77.png">

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terrace/commit/0fd264b921f26534600ce46243282a2e3517aa7d

This will be fixed on next SaaS release
