### ISSUE TITLE
DEA Difference Tool doesn't load, errors

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#6278]
When trying to use the DEA Difference Tool it doesn't work at the moment, it just immediately errors before actually starting:

<img width="1245" alt="Screen Shot 2022-05-02 at 14 29 01" src="https://user-images.githubusercontent.com/5283003/166184387-bdeb4492-75ea-4185-afc2-30a56cd3385f.png">

**Comment by nf-s** [comment]
Proper error message

![image](https://user-images.githubusercontent.com/6187649/166411668-00941944-a5b9-46d4-a5fa-70781e8babab.png)

http://ci.terria.io/main/#configUrl=https://terria-catalogs-public.storage.googleapis.com/de-australia/map-config/prod.json
