### ISSUE TITLE
Editing style - app crashes when changing values using keyboard

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#6331]
Steps to reproduce: 
- go to https://map.pacificdata.org/
- select pacific data hub.stat - Population - Household counts, population and average household size
- go to Edit style
- select Type - Sequential discrete
- select Bins and chose one of the bins in the list
- Use Min or Max and update the numbers using the arrows - all works fine
- Same action of updating the numbers using the keyboard - the app crashes (white screen of death)

**Comment by nf-s** [comment]
Seems fixed - I can't reproduce
