### ISSUE TITLE
Map credits not translated and rendered as translation key

### ISSUE THREAD

**Issue by zoran995** [TerriaJS/terriajs#6336]
I just noticed that credits at the map footer are rendered as a translation key instead of translation. Also changing of language won't update them.
![image](https://user-images.githubusercontent.com/19208948/173154265-70028270-0839-4504-ba57-9a3e0ebc2057.png)
Rendering as a translation key started happening after the merge of #6219, and the reason behind this is that the translation is not available when initializing cesium, and this is not in react context so it is not updated later.
https://github.com/TerriaJS/terriajs/blob/bd6198e66b9cf4314a95464acba8ab5d40516ef8/lib/Models/Cesium.ts#L270-L278
Not updating the value on a language change is an older issue.

We probably should go with this approach https://github.com/TerriaJS/terriajs/pull/6219#issuecomment-1084101382, as it sometimes happens to see a glitch with translation load, less than a half of a second; without any throttle, don't know what is different from a few months ago (sorry for bad image quality)
![image](https://user-images.githubusercontent.com/19208948/173154023-53430834-9e45-47c5-a25b-1530c0e06096.png)

Steps to reproduce

- Open http://ci.terria.io/main/
- Notice the credits being a translation keys
- Change the view to 2D and then back to 3D
- Now they are translated into the chosen language since the translation file is already loaded.

**Comment by tephenavies** [comment]
Using a preload link doesn't seem to fix this. It only warms the cache so downloading translation.json is fast. I think we need to wait on the promise of `i18next.init({...})` before rendering to avoid no-language flash.
