### ISSUE TITLE
Clicking to get feature info causes crosshair to jump at high zoom levels in Cesium when using Esri REST layers

### ISSUE THREAD

**Issue by axman6** [TerriaJS/terriajs#634]
When clicking on the map at high zoom levels, the crosshair tends to jump towards the middle of the view. When zoomed into a level where trees are resolvable and clicking anywhere on the map causes the crosshair to jump to the centre of the view when clicking at essentially any location on the view. WMS layers appear to work correctly.

A video of the bug is available here: https://cloudstor.aarnet.edu.au/plus/public.php?service=files&t=058d7c299e8821153f2eeca9e1e281ce (available until 30 April)

Tested in Chrome 42.0.2311.90 on OS X 10.10.3.

**Comment by kring** [comment]
This is a parallax issue; the height of the selection indicator is changing, making it appear as if the horizontal position is changing.  For point features, NM moves the selection indicator to the actual location of the selected point.  These points typically don't include a height, so NM uses 0.0.  If the terrain surface is above or below the ellipsoid (which it usually is), this makes the point appear to move relative to the terrain surface as the camera moves around.  This will likely happen with some WMS layers, too.

I'm going to try to fix it by sampling the terrain height at the feature's location (if the feature doesn't already have a height) and using that.

**Comment by axman6** [comment]
Sounds good. It's not a high priority issue; I doubt many people will be using NM/AREMI at such high zoom levels.
