### ISSUE TITLE
Share URL with Feature Info works in 3D mode but not in 2D mode

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#6346]
For some reason we can create Share URL's in 3D mode but not in 2D mode, in 2D mode the Feature Info popup comes up, but it says "no data".

Share URL in 3D with Feature info: https://maps.dea.ga.gov.au/#share=s-ezh26Ar7Zq0YspAetBpTuJY43ky

<img width="617" alt="Screen Shot 2022-06-15 at 19 03 49" src="https://user-images.githubusercontent.com/5283003/173788501-2453665a-10fa-4162-a7dc-61cfa4c5ea10.png">

Share URL in 2D with Feature info: https://maps.dea.ga.gov.au/#share=s-w4CFI8lirt9W0dJpRh6T7h16tm3

<img width="430" alt="Screen Shot 2022-06-15 at 19 02 45" src="https://user-images.githubusercontent.com/5283003/173788299-955e2cbf-d88d-455b-8dff-3d628fc0d3a3.png">

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/6441
