### ISSUE TITLE
Fix naming of map tools bug appearing as translation strings

### ISSUE THREAD

**Issue by staffordsmith83** [TerriaJS/terriajs#6352]
![image](https://user-images.githubusercontent.com/7980991/174937135-ce5317fa-1c1c-447a-b6a8-e5e39765b407.png)

Related to #6340  to fix map attribution labels.

**Comment by zoran995** [comment]
The issue with this is that function useTranslationIfExists will return the translation key if it's not found in translations and it won't react to language changes.

**Comment by nf-s** [comment]
![image](https://user-images.githubusercontent.com/6187649/176596788-cfe23cd3-34c6-41f2-b52f-480eb05f7a65.png)
