### ISSUE TITLE
A lot of broken WMS-Services in V8

### ISSUE THREAD

**Issue by leylines** [TerriaJS/terriajs#6355]
I have a lot of WMS-Services that do not work anymore in V8. All of them are working in V7. All of them do not work in Nationalmap (all kind of errors and faulty mapping). 

Thank you for taking a deeper look at this issue.

Jörg

https://gibs.earthdata.nasa.gov/wms/epsg4326/best/wms.cgi?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0
https://tiles.maps.eox.at/wms
https://www.gebco.net/data_and_products/gebco_web_services/web_map_service/mapserv?request=getCapabilities&service=wms&version=1.3.0
https://gis.ngdc.noaa.gov/arcgis/services/EMAG2v3/MapServer/WMSServer?request=GetCapabilities&service=WMS

**Comment by leylines** [comment]
The Gebco-Stuff seems to be fixed now, the others still do not work. Any news on this?

**Comment by leylines** [comment]
Still no news?

**Comment by himby** [comment]
Experiencing similar issues with:
[https://wms.geonorge.no/skwms1/wms.nmg?service=WMS&version=1.3.0&request=GetCapabilities](https://wms.geonorge.no/skwms1/wms.nmg?service=WMS&version=1.3.0&request=GetCapabilities)

![image](https://user-images.githubusercontent.com/77962945/219694786-04785cb0-8408-49b9-ac26-0ce2bc6832ea.png)

**Comment by nf-s** [comment]
Sorry for the delay in response!

These seem to be working now (note some of the layers don't support Web Mercator - so they will only work in 3D mode)

- https://gibs.earthdata.nasa.gov/wms/epsg4326/best/wms.cgi?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0
- https://gis.ngdc.noaa.gov/arcgis/services/EMAG2v3/MapServer/WMSServer?request=GetCapabilities&service=WMS

I know have a PR that fix the following (https://github.com/TerriaJS/terriajs/pull/6864)

- https://tiles.maps.eox.at/wms
- https://wms.geonorge.no/skwms1/wms.nmg?service=WMS&version=1.3.0&request=GetCapabilities

**Comment by nf-s** [comment]
Closing in favour of https://github.com/TerriaJS/terriajs/issues/6860
