### ISSUE TITLE
Cesium ion as a Catalog Groups

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#6388]
### Discussed in https://github.com/TerriaJS/terriajs/discussions/6311

<div type='discussions-op-text'>

<sup>Originally posted by **@imakihi** June  4, 2022</sup>
So I have lots of 3D data in my Cesium ion account. I thought it would be nice I could bring all assets from my account instead of registering as an indivisual catalog item.
Just a thought.

Thank you!
Hiroo</div>

**Comment by imakihi** [comment]
It is going to be so easiy to bring 3D models to terria if we have this capability!
