### ISSUE TITLE
WPS results are showing columns twice after sharing

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#6392]
https://beta.geo-rapp.terria.io/#share=s-eLoi6D4gSxt6RWMxWgRlxJD0D0s

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/6187649/177452944-05c2eb2e-31b5-4ec0-8c8c-1307b83e8789.png">

**Comment by na9da** [comment]
Can still be replicated with a recent version - https://map.geo-rapp.org/#share=s-uZZUHl3brKNOup0nVzUfOMBQbRH

Original workbench output has just 1 entry for columns like `Bare Ground`:
![image](https://github.com/TerriaJS/terriajs/assets/1430/a9b78691-24f2-4504-bcf2-197593613491)


The share link has 2 entries for columns like `Bare Ground`:

![image](https://github.com/TerriaJS/terriajs/assets/1430/d80b8090-0ab4-4919-99dc-a33d1e56acde)
