### ISSUE TITLE
Intermittent bug where CSV items can't be shown/hidden in the workbench

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#6399]
Possibly the same as https://github.com/TerriaJS/terriajs/issues/6344

- http://ci.terria.io/main/#https://gist.githubusercontent.com/nf-s/67e44309245f3caca1cee5cdf2eee3eb/raw/75c50871fd972f8d6f35039c6e5278f3f7437a69/colorscale-minmax.json
- **Turn both layers on**
- Try toggling show/hide either

**Comment by nf-s** [comment]
Proof

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/6187649/177780804-47d50dba-320f-4321-85cd-c1459035345c.png">

**Comment by nf-s** [comment]
Layers will reset when map mode is changed

**Comment by zoran995** [comment]
This works correctly now, probably fixed in #6639
