### ISSUE TITLE
App unresponsive after adding empty geojson

### ISSUE THREAD

**Issue by zoran995** [TerriaJS/terriajs#6400]
If user adds an empty geojson file to the map in 3D viewer it will become unresponsive and there is an error in console
![image](https://user-images.githubusercontent.com/19208948/177870389-b1830365-a6a5-4ab9-b01e-bca0bd8b67fa.png)

Steps to reproduce
1. opet http
2. switch to 3D viewer
3. add https://gist.githubusercontent.com/zoran995/5f350db19f5ef6bb4f337aa19e203914/raw/360ae49233a491256a4af1f7b7d9e1b55fb58c3d/test.geojson
4. observe that viewer is unresponsive

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/6945
