### ISSUE TITLE
Add cesium native I3S support

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#6416]
See PR - https://github.com/CesiumGS/cesium/pull/9634

Depending on PR outcome - we can always merge it into https://github.com/TerriaJS/cesium

**Comment by Tamrat-B** [comment]
Hello, I'm pleased to let you know that this PR has been merged and is available now. The next release of CesiumJS should have these changes. Of course, if you are building from current source you'll be able to access it now (look for I3S 3D Object layer, I3S Feature Picking and I3S IntegratedMesh Layer sandcastle samples for usage (under Gallery/DataSources Tab).

**Comment by nf-s** [comment]
We have just upgraded cesium to `6.2.0` - so we can progress with adding I3S to Terria now

- https://sandcastle.cesium.com/?src=I3S%203D%20Object%20Layer.html
- https://sandcastle.cesium.com/?src=I3S%20IntegratedMesh%20Layer.html
- https://sandcastle.cesium.com/?src=I3S%20Feature%20Picking.html

**Comment by Techmaven-geospatial** [comment]
Is there a new catalog item for this ?

**Comment by nf-s** [comment]
Hi @Techmaven-geospatial 

Not yet, but we are planning on creating one in the next few months.

**Comment by Tamrat-B** [comment]
Just wanted to let you know we were able to merge our [PR](https://github.com/CesiumGS/cesium/pull/11678) for consuming, filtering and visualizing of Building Scene Layer (BSL) – an OGC standard for streaming BIM data, and is now included in Today’s release of CesiumJS, version [1.115.](https://github.com/CesiumGS/cesium/releases/tag/1.115)
 
With this release an I3S BSL could be visualized, queried, and filtered in CesiumJS. To see all the I3S based samples working in CesiumJS go to the Cesium [SandCastle](https://sandcastle.cesium.com/)  (The DataSources section has all the I3S examples, including the latest I3S Building Scene Layer example).

**Comment by nf-s** [comment]
Thanks @Tamrat-B - that is great to know!

**Comment by nf-s** [comment]
For BSL support we need to do this

- [x] https://github.com/TerriaJS/terriajs/issues/7083

**Comment by nf-s** [comment]
Looks like no projection support - need to figure out how difficult it is for data owners to publish scene layers as WGS84 on their end

**Comment by stevenjh** [comment]
I was thinking about this projection issue for some Auckland mesh model
that is only published to I3S in NZTM (2319).

Thinking is it technically possible to implement tile-set reprojection?

**Comment by ljowen** [comment]
Update 26 Jun 24:
- Feature picking and highlighting now implemented

**Comment by ljowen** [comment]
Update 8 Jul 24:
- Responding to Nanda's review

**Comment by ljowen** [comment]
Update 8 Jul 24:
- Responding to Nanda's review
