### ISSUE TITLE
WFS (or all Cesium drawn?) points appearance look worse in latest release

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#642]
WFS points used to look like this:

![screen shot 2015-04-23 at 9 26 57](https://cloud.githubusercontent.com/assets/5283003/7287735/7501aabe-e99b-11e4-8be1-b3b4e12bba05.png)

In the latest release they changed to look like this:

![screen shot 2015-04-23 at 9 28 01](https://cloud.githubusercontent.com/assets/5283003/7287738/8260463e-e99b-11e4-924f-8edad1458c67.png)

Was this an intentional change, or is it a bug?

**Comment by kring** [comment]
Not intentional.  This is possibly a Cesium bug, as the black outline still exists in Leaflet.

**Comment by kring** [comment]
It's our bug, not Cesium's.  I just opened a pull request to fix it in TerriaJS.  If you need the fix without switching to TerriaJS (which I recommend for now), just look at the diff and add the same two lines in your version.
