### ISSUE TITLE
Text contrast broken 

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#6433]
The contrast for text in some features is currently not working i.e. text is illegible (e.g white text over cream background)  

![image](https://user-images.githubusercontent.com/18452161/179467159-fa74d88b-f760-48a9-9981-ea5c857548a1.png)

To test: 
 - go to https://nationalmap.gov.au/
 - select and add any dataset or group and click Share from the About this data page 
 - check the text in the window showing the Share url

**Comment by zoran995** [comment]
This should be fixed in #6428
