### ISSUE TITLE
Contrast problem in FeatureInfo panel

### ISSUE THREAD

**Issue by staffordsmith83** [TerriaJS/terriajs#6443]
@staffordsmith83 commented on [Wed Jul 20 2022](https://github.com/TerriaJS/saas-catalogs-public/issues/177)

![image.png](https://images.zenhubusercontent.com/62673fa28d46e59cec18c8f1/848a46eb-8d51-4252-8d5b-2693b72095d9)

I think this occurs with WMS catalog items with two layers? E.g. the WA Cadastre in national Map (layers should be merged and available in `prod` in next couple of days.

![Screen Shot 2022-07-20 at 12.51.55 pm.png](https://images.zenhubusercontent.com/62673fa28d46e59cec18c8f1/7149976f-8a40-4081-865d-353dd521fee0)

**Comment by nf-s** [comment]
Fixed by https://github.com/TerriaJS/terriajs/pull/6936
