### ISSUE TITLE
Document JSON schema for data providers

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#646]
As we bring on more data providers, we should perhaps nicely document the JSON schema for their configurations.

We could:
1. Do something ad-hoc with a sample .json file and embedded comments (which will automatically be webified by JSDoc)
2. Create a [JSON-Schema](http://json-schema.org/), which has its own way of webifying
3. Use [MSON](https://github.com/apiaryio/mson)

I'm happy to pursue this if it's valuable.

**Comment by kring** [comment]
I agree, that would be really valuable.

FWIW, we used JSON-Schema for CZML.  It seemed to work pretty well:
https://github.com/AnalyticalGraphicsInc/czml-writer/blob/master/Schema/Packet.jsonschema

**Comment by stevage** [comment]
Great, I'll follow suit.

**Comment by stevage** [comment]
Progress here: https://github.com/NICTA/nationalmap/blob/datasource-schema/schema/schema2.hjson

(Should be in this repo, not NM).

**Comment by kring** [comment]
Looks like a great start!  One minor error I noticed: `corsDomains` is the list of domains that DO support CORS, so we won't use the proxy (except in IE9).

**Comment by stevage** [comment]
Thanks. I really should have known that. For now, this work is happening here: http://github.com/terriajs/DataSourceEditor

Eventually I think the schema file should live in this repo (in `/`? in `wwwroot`?) , and the editor should ajax it from there.

**Comment by stevage** [comment]
Pretty well covered by https://github.com/TerriaJS/generate-terriajs-schema
