### ISSUE TITLE
Usability of search

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#647]
I was surprised while demoing NM how useful the Search box is, for finding layers. I'd never noticed it before (like all the usability participants). But I found that searching for a place was something I never wanted to do.

Here's my suggestion for a different UX:
1. Move the search box to the top of the Data Catalogue pane, where it's always visible. This box only searches for layers.
2. To search for places, have a search button within the map area:

![screenshot 2015-04-24 14 05 44](https://cloud.githubusercontent.com/assets/678344/7312202/0b1d5256-ea8b-11e4-9b95-c84ad3228609.png)

One caveat is the search box can only find layers that are opened (ie, layers have to have been retrieved from web-based catalogues first), and that caveat isn't communicated to users currently.

(Not sure how to flag this for UX attention, so: @hilarycinis @philipgrimmett )

**Comment by bsimyo** [comment]
Re the searching limitation... yes, you are right that it isn't communicated effectively in the UI.  It recently got into the user documentation - see http://nationalmap.nicta.com.au/help/SearchTab.html - but isn't well enough indicated in the UI.

**Comment by hilarycinis** [comment]
will be part of the new ui redesign underway
