### ISSUE TITLE
National Map "About" link doesn't work on IE

### ISSUE THREAD

**Issue by bsimyo** [TerriaJS/terriajs#648]
Apparently it doesn't work on various versions of IE including IE11

**Comment by bsimyo** [comment]
Reported by Dept of Comms

---

Below is a screen shot when clicking on the ‘about’ page when using IE.

Cheers,
Michelle

![image001](https://cloud.githubusercontent.com/assets/1151940/7313946/88fd9890-eaa2-11e4-839e-8e2d36067d49.jpeg)

**Comment by stevage** [comment]
Fixed in 349c2ff.
