### ISSUE TITLE
Terria crash when searching for locations

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#6513]
It is possible to repeatably make terria crash by following these steps, also as recorded in the attached video:
1. Open NatMap
2. Add National -> Energy -> Electricity -> Generation -> NEM -> All (I don't know why this is required, but I can't seem to get it to crash without this step)
3. Search for some location e.g. `-35, 147`, click on the search result to zoom to location
4. Move the map
5. Clear the search
6. Search for some other location e.g. `-36, 147`, click on the search result to zoom to location
7. 🛬🎆

https://user-images.githubusercontent.com/5283003/185063156-2cb75765-9257-41da-83c7-6f82402add51.mov

**Comment by meh9** [comment]
Still happens, now with an error message!

<img width="525" alt="Screenshot 2023-03-01 at 10 58 11" src="https://user-images.githubusercontent.com/5283003/222010306-ca98b9f1-886a-4344-b95d-785e0122d4ba.png">

**Comment by KerriG1** [comment]
@AnaBelgun are we able to bring this into the April Release?

**Comment by zoran995** [comment]
It seems to be working now; feel free to reopen it if still happening
