### ISSUE TITLE
Provide an option to override WFS `srsName` parameter by passing it as URL parameter?

### ISSUE THREAD

**Issue by na9da** [TerriaJS/terriajs#6518]
Our current WFS implementation hardcodes `srsName` parameter as `urn:ogc:def:crs:EPSG::4326` ([here](https://github.com/TerriaJS/terriajs/blob/ddc258a132c7252c5aa20d689b31ba372e00737a/lib/Models/Catalog/Ows/WebFeatureServiceCatalogItem.ts#L363)).

WFS servers accepts different formats for `srsName`:
 -  `urn:` is a good default setting because it has a well known [spec enforced](https://docs.geoserver.org/latest/en/user/services/wfs/axis_order.html) lat,lon ordering for the returned WFS geometries.  
 - `EPSG:XXXX` is not reliable because different servers return different ordering (lat,lon or lon,lat) and it is hard to tell.

There are however some servers that return the correct lat,lon ordering that Terria epxects for `EPSG:4326` but does not accept the `urn:` format. Currently, it is not possible for a user to use the `Add web data` option to add such a WFS endpoint to Terria. 
eg: https://webmap.yvw.com.au/YVWassets/service.svc/get?request=GetFeature&service=WFS&typeName=yvw:NDWHYDRANTS&version=1.1.0&srsName=EPSG:4326

This issue is to discuss whether we should read the `srsName` parameter from the WFS input url to override our default `urn:` setting.

**Comment by staffordsmith83** [comment]
Also in https://github.com/TerriaJS/terriajs/blob/ed98942e9f9635e30b98ff00e6e53fd2909a41eb/lib/Models/Catalog/Ows/WebFeatureServiceSearchProvider.ts#L113

**Comment by staffordsmith83** [comment]
@na9da can you please clarify what you mean by: "whether we should read the srsName parameter from the WFS input url to override our default urn"

Whilst they mostly do, not all of our `wfs` type catalog items specify the srsName in the url, e.g.:
https://github.com/TerriaJS/saas-catalogs-public/blob/b3a7e173de513bb96700e7e731ad0a1f1c5cbdd1/neii/_in/neii-oceans-v7-2021-04-20.json#L1974

Do you mean the srsName param from urls of `getFeature` type? Like this:
              "url": "http://geo-prototype1.aremi.d61.io/acma/wfs?service=WFS&request=GetFeature&typeName=acma%3Aacma_licenses&version=1.1.0&outputFormat=JSON&srsName=EPSG%3A4326",

And if we were to use that, and to replace the `urn: ...` string with `ESPG:...` dont we get the same problem where we cannot be sure of the lat,long order returned?

Cheers, just give me a few more hints :-)

**Comment by na9da** [comment]
Hey @staffordsmith83 , there is some more context in this issue - https://github.com/TerriaJS/vic-digital-twin/issues/400

Basically, we always send `urn:` because it has a strict ordering. In the above issue, the user is trying to load the WFS using the `Add web data` flow. Their server does not support the `urn:` format but happens to return the correct lat,lon ordering for `EPSG:` that works with Terria. For such cases, where the user knows that the `EPSG:` has the expected ordering, it could be beneficial if they can override the `urn:` format by simply adding `&srsName=EPSG:4326` in the URL they supply.

eg: https://geoserver.data.aims.gov.au/ows?service=WFS&version=1.0.0&request=GetCapabilities&srsName=EPSG:4326

This is not so useful when the dataset is defined using the JSON catalog, only when the user manually adds it from the `Add web data` flow. It is also not a very discoverable feature,  hence why I tagged it as "Needs discussion".

**Comment by staffordsmith83** [comment]
Another issue, related but perhaps needs to be in a separate ticket: 
In `WebFeatureServiceCatalogItem` the output format is pre-set.
With the example WFS url given in this ticket, the server returns an error because it does not support `gml3` format.
This is where its preset:

https://github.com/TerriaJS/terriajs/blob/ed98942e9f9635e30b98ff00e6e53fd2909a41eb/lib/Models/Catalog/Ows/WebFeatureServiceCatalogItem.ts#L362

```json
outputFormat: supportsGeojson ? "JSON" : "gml3",
```

**Comment by staffordsmith83** [comment]
Defaults in `WfsFeatureServiceCatalogItem` have been there for a long time (since pre-V8).
We really need to parse the GetCapabilities response for a layer to determine which `outputFormat` and `srsName` to use.
Current defaults are here:

https://github.com/TerriaJS/terriajs/blob/ed98942e9f9635e30b98ff00e6e53fd2909a41eb/lib/Models/Catalog/Ows/WebFeatureServiceCatalogItem.ts#L353-L371

What other parts of Terria parse the GetCapabilities response?
