### ISSUE TITLE
Remove or update link to terriamapstatic

### ISSUE THREAD

**Issue by do-me** [TerriaJS/terriajs#6520]
The repo \[terriamapstatic\](https://github.com/terriajs/terriamapstatic) appears to be deleted for some reason. Can anyone elaborate why? 

Anyway, the reference in the Readme.md should be updated as right now it's pointing to a non-existing repo, see \[here\](https://github.com/TerriaJS/terriajs#related-components).

**Comment by zoran995** [comment]
Terriamap static is available at https://github.com/terriajs/terriamap-static; add the current URL in readme points to it
