### ISSUE TITLE
Drag & Drop bug

### ISSUE THREAD

**Issue by BarryReidPropeller** [TerriaJS/terriajs#653]
When AddDataPanelViewModel (Add Data) is open and a user tries to drag a file onto the map and then drags it off again, the "Drop a data file anywhere to add it to the map!" screen gets stuck on the screen until the "Add Data" screen is closed and a file is dragged on and off the map again.

The "Drop a data file anywhere to add it to the map!" screen should not open when any type of light box is on screen eg, the Add Data screen or Error screens.

**Comment by kring** [comment]
Thanks for the report, Barry.  We'll fix this up before the next release, planned for May 15.

**Comment by BarryReidPropeller** [comment]
Thanks Kev

We have actually written out own uploader in the "Add Data" section that has its own drag and drop file uploader and the National Maps one is firing at the same time when we drag files onto the Add Data window.
