### ISSUE TITLE
Allow HTML in search location results

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#656]
A minor issue I ran into. It would be nice to allow HTML in the text of results in the search panel, to allow better styling (eg, "Perth <small>WA</small>"). Tried it and the HTML came out raw.

**Comment by kring** [comment]
It might be better to extend `SearchResultViewModel` with whatever information you need (kind of like that isImportant flag), and handle the style separately, rather than letting the search providers generate styled HTML.

**Comment by stevage** [comment]
Yeah, good idea. Probably two fields, like `locatedWithin` for a brief description of state or possibly city/state if available, and `locationDescription` with a longer text explaining the kind of thing that it is (eg, "Mountain" or "Unbounded locality" or whatever). The latter could be either displayed as small text below the main result, or as mouseover.

But yeah, separating display from content is the right thing to do.

**Comment by kring** [comment]
Closing this.  It's describing how to implement something we don't know if we even need.
