### ISSUE TITLE
Upgrade to CesiumJS 1.98.1

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#6569]
https://github.com/CesiumGS/cesium/releases/tag/1.98

**Comment by kring** [comment]
An upgrade to CesiumJS v1.98.1 is working (but not well tested) in these branches:

https://github.com/TerriaJS/terriajs/tree/update-to-1-98-1
https://github.com/TerriaJS/cesium/tree/update-to-1-98-1

Known to not be working yet:
* ZIP'd data files (e.g. KMZ)
* `TERRIA_solid_outlines`

**Comment by tephenavies** [comment]
I was able to build locally, but unfortunately can't create a CI branch as there are some TypeScript errors that I come across https://github.com/TerriaJS/terriajs/actions/runs/3324858845/jobs/5496952814#step:7:224

**Comment by AnaBelgun** [comment]
@kring is it possible to help with the type script errors please? when you get a chance

**Comment by kring** [comment]
Yeah, this isn't done yet.

**Comment by na9da** [comment]
@kring you might already know but draco compressed gltfs are also broken.

**Comment by nf-s** [comment]
This is done!
