### ISSUE TITLE
Location-sensitive searching

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#657]
Gazetteer supports sorting results based on distance from a point, and it may help with queries that return too many results to retrieve (such as "Park St") - #556 .

Implementation:

```
http://www.ga.gov.au/gazetteer-search/gazetteer2012/select?pt=-37.792103243511%2C144.9258518219
&fq=%7B!bbox%7D
&sort=geodist()+asc
```

The `{!bbox}` bit just seems to truncate results that are too far away.

**Comment by kring** [comment]
This is easy enough to do, but it's not clear that the user expects to find results that are close to the center of the map over other results.  I'm going to close this because it seems unlikely we'll ever do it.
