### ISSUE TITLE
Searching for layers in dynamic catalogs

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#658]
Currently, when a user searches for a layer, it only finds layers that are either:
1. in a static catalog (a .json file); or
2. in a dynamic catalog that has been expanded (and hence, the list of layers pulled down)

I understand why this is the case. But I don't think it's really adequate for discovering layers. If a user wants to know if there is any dataset anywhere about, say, "health", they need to expand all the top level catalogs, then an unknown (and difficult to ascertain) number of second-level catalogs (potentially dozens). 

And of course they have no way of knowing that they need to do this, or what "Sorry, no catalogue items match your search query" really means.

Unfortunately, this is one of our most important use cases (user trying to find whether or not there exists a government geospatial dataset on a given topic), so we can't ignore it. Maybe it's even our most important use case.

I can think of a few solutions, but they're not exactly trivial:
1. Replace all dynamic catalogs with static ones that are frequently updated dynamically. (Downside: massive JSON download)
2. Have a separate search index (eg, a generated JSON file which is just layer names without most of the other metadata) which is frequently updated using all the dynamic catalogs (Downside: More work, could be tricky to implement so you can click on a result and then the main catalog finds its way to the layer you clicked on)
3. Create a web service with this pre-computed list (bonus: free analytics on what people are searching for)
4. Have a mechanism allowing the user to do a "super search", retrieving the contents of every single dynamic catalog prior to searching. (Downside: super slow, probably bad UX)

Number 2 or 3 seems the best at first glance.

**Comment by stevage** [comment]
Just sketching idea 3 out a bit, we'd need code to:
1. Fully expand the catalog tree
2. Serialise the expanded tree to disk
3. Do this regularly (ie, put a cron job into the install process, or whatever)
4. Provide a lookup service
5. Implement a search provider that uses that lookup service
6. Navigate back from a clicked result to the possibly-not-yet-expanded catalog item. (Especially fun if it's several layers of unexpandedness deep)

**Comment by stevage** [comment]
With option 2, step 4 and 5 get implemented client side, which probably doesn't really simplify very much.

OTOH, if you have a minimal catalog tree available in the browser, then maybe step 6 is simpler.

And then if you follow idea 1 instead, then you also get the benefit that the whole user experience of navigating the catalogs is much faster to begin with. (Every catalog behaves like "National datasets" in speed)

**Comment by hilarycinis** [comment]
I'm really keen to see how you progress with this, thanks for outlining your ideas in detail!

The main issue is one of understanding the meaning and use of the application. I can see your use case fitting with that. 

We have observed users wanting to explore the entire catalog to get a "feel" for whats in there (especially evident in the previous UI when they kept trying to pull open the corners of the component module to get a better view to scan the catalog content.

We've also observed the 'consumer' level user is trying to use the application like google maps or earth but not really getting what they need from it. 'Engaged' users are using an activity specific instance that has the data sets they are already expecting (eg AREMI)... or hope to see. 'Experts' are just making their own versions so not really included in this scenario (although would be beneficiaries of it).

**Comment by meh9** [comment]
@stevage, what about a version of 4 where the browser downloads all the catalogs in the background once all the other NM initialisation has been done? This way it's likely that by the time a user does a search the data would be there.

There would be a time period before all catalogs have been retrieved that the search would return incomplete results, but if there is a spinner and possible message that catalogs are still being downloaded (or "Updating search index..." or something like that) maybe that would be acceptable.

The downsides may be increased load on the providers if every client downloads every dynamic catalog, but do we care?

Other than that I like option 3: web service.

**Comment by kring** [comment]
I agree 3 is the "right" solution.  There goes our stateless server, though, so there's more than just the development cost involved.

4 might not be as slow as you think, especially if we start it early as @meh9 suggests.  I wouldn't make it an option (that's where the UX becomes bad, right?) but instead just always do it, and continue to display "Loading..." (or whatever) until all results are in.

**Comment by stevage** [comment]
@meh9 That's a pretty nice idea - and thanks for making explicit my assumption that hitting provider catalogs is bad. We could theoretically even just proxy them if that ever turned out to be an issue?

> There goes our stateless server, though, so there's more than just the development cost involved.

@kring Could you elaborate on that? I'm imagining some kind of hourly cronjob that updates an index which a client can query by REST. It would still be "stateless" in the REST sense (ie, it doesn't keep track of any information about user state). What other kind of "state" do you think we'd be tracking? (Just not quite getting what you mean...)

**Comment by kring** [comment]
> We could theoretically even just proxy them if that ever turned out to be an issue?

I believe we're already proxying / caching most if not all provider catalogs, with a 1 day TTL.

> Could you elaborate on that? I'm imagining some kind of hourly cronjob that updates an index which a client can query by REST. It would still be "stateless" in the REST sense (ie, it doesn't keep track of any information about user state). What other kind of "state" do you think we'd be tracking? (Just not quite getting what you mean...)

It might not be as bad as I thought when I wrote that, assuming the server itself is update its index periodically, as opposed to something external that then has to publish the updated index to the server.  You're right that there's no per-user state, of course.

Currently, we deploy an instance of NM by spinning up an entirely new VM.  Then, that VM Is basically immutable.  If we want to change it (e.g. to publish a new version), we spin up a new one VM rather than changing the existing one.

If the server has an index, it may change this approach.  We'd either have to wait until the index population was complete before switching over to a newly-deployed version, or we'd need a way to maintain the index when upgrading.

And then what if we suddenly need to scale up the number of number of NM instances?  If we have to wait for the index to populate, that hinders our ability to rapidly scale up under load.

These things are worth thinking about, but probably not as bad as the Great MongoDB Fiasco of 2014, which is what I was originally thinking of.

**Comment by stevage** [comment]
> I believe we're already proxying / caching most if not all provider catalogs, with a 1 day TTL.

Ah yes, seems so - the slow catalogs I saw were presumably ones that hadn't been opened in a day or so. 

The more I think about it, the more this seems the right approach. We could improve the caching setup with pre-emptive cache refreshes (eg, during the night) so they're always fresh and populated. 

> Currently, we deploy an instance of NM by spinning up an entirely new VM. Then, that VM Is basically immutable. If we want to change it (e.g. to publish a new version), we spin up a new one VM rather than changing the existing one.

Thanks for explaining that. It may make sense to separate the proxying/caching infrastructure anyway. Does `corsProxy.js` really need to exist? It could be just as easily implemented as a couple of lines of nginx config along these lines:

```
location /proxy/[Insert proxyable domains here]/ {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
}
```

(that's just a cut and paste, not an exact solution...)

If we go down this road, then the work becomes:
1. Reconfigure server side proxying and caching (or see what happens if we don't)
2. Add code to automatically recursively populate (but not expand) every catalog

Seems to have lots of benefits (including the fact that all the layers are now client-side, meaning when they do expand each catalog it's instant), few downsides. 

I think the total download cost of opening all the catalogs on nationalmap.gov.au currently is 817KB (Chrome, filtering for XHR with 'wms' in URL). If that's happening in the background, I think it's still reasonable. What would an upper bound for reasonableness be though?

**Comment by kring** [comment]
> It may make sense to separate the proxying/caching infrastructure anyway. 

I'm not sure what you mean here.  Separating the proxying from the caching, or separating the proxying+caching from everything else?

I guess I'm not sure what problem you're aiming to solve, either.  @meh9's suggestion is totally doable without any changes to that end of things, unless I'm missing something.

> Does corsProxy.js really need to exist?

`corsProxy.js` is used on the client to decide when to use the proxy, and adjust URLs entirely.  So yes, it's needed.

But to answer your real question (I think), there's no reason the proxy has to be in node, it could just as easily be nginx or whatever else.  It's convenient to be able to list the proxy whitelist in a JSON file though, rather than an nginx config file.  I have an irrational (probably) distrust of node, so I'd probably support using something else if it were convenient.

**Comment by stevage** [comment]
> Separating the proxying from the caching, or separating the proxying+caching from everything else?

Separating the proxying/caching from the application itself. 

> corsProxy.js is used on the client to decide when to use the proxy, and adjust URLs entirely. So yes, it's needed.
> But to answer your real question (I think),

Whoops, yes.

> It's convenient to be able to list the proxy whitelist in a JSON file though, rather than an nginx config file. 

Yeah. [nginx-conf](https://www.npmjs.com/package/nginx-conf) maybe? Would need to be triggered somehow. It should be fairly trivial to pull down the JSON file, and update the nginx config as required.
