### ISSUE TITLE
Upgrade to MobX 6.6.2

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#6588]
As part of upgrading to React v18, we should really upgrade mobx from v4 to v6 major version.
The main reason is that we get build errors from the mobx4 dependency when we upgrade to React v18, as mobx v4 is using the now deprecated `RefForwardingComponent`

As part of this we should also upgrade packages `mobx-react` and `mobx-react-lite`

please see draft PR #6594

**Comment by AnaBelgun** [comment]
Update 15 Feb 23: 
- @na9da to write a PR and ADR for the 2 solutions - https://github.com/TerriaJS/terriajs/pull/6687
- @na9da Testing branch for the digital twins 
- @steve9164 full code review of all the React component changes - https://github.com/TerriaJS/terriajs/pull/6687
- Community notice about the changes: TS4 and MobX

**Comment by na9da** [comment]
Done.

Please refer to [upgrade guide](https://github.com/TerriaJS/terriajs/discussions/6787) for info on upgrading.
