### ISSUE TITLE
Failed to expand service on IE10

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#659]
An IE10 user in WA reports that expanding "Culture & Society" (WA Landgate) failed with error message "Group is not available" (plus the long spiel about CORS). 

Using IE11 in a VM, I get the same thing.

**Comment by stevage** [comment]
It may have something to do with encodings or strange characters in the WMS getCapabilities response. IE apparently sees this much of the document:

![screenshot 2015-04-30 13 08 30](https://cloud.githubusercontent.com/assets/678344/7405717/0682bc82-ef3a-11e4-8bb9-c352a6d71ca0.png)

That is, the response starts at `x="153.626466" maxy="-9.087989"></LatLonBoundingBox></Layer><Layer...`

**Comment by stevage** [comment]
Strangely, accessing the getCapabilities directly in IE works fine (that is, it retrieves the complete XML document.)

**Comment by stevage** [comment]
The IE debugger log is complaining about the copyright symbol (©) on line 6 ("XML5617: Illegal XML character. Line: 6, Column 1".

That symbol also fails to render in Chrome:

![screenshot 2015-04-30 13 43 54](https://cloud.githubusercontent.com/assets/678344/7406012/f96f10f4-ef3e-11e4-9424-30771c8d655f.png)

**Comment by stevage** [comment]
Hmm, by playing around with Sublime encoding choices, I think that maybe what's going on is the document (or at least these descriptions) are actually encoded in something like [1252](https://en.wikipedia.org/wiki/Windows-1252), but the XML document claims to be encoded in UTF-8. Presumably that sequence isn't a valid character in UTF-8, which Chrome ignores, but IE chokes on.

**Comment by stevage** [comment]
(Confirmed, it's a simple 0xA9, whereas the [correct](http://www.fileformat.info/info/unicode/char/00a9/index.htm) UTF-8 encoding would be two bytes, 0xC2A9)

**Comment by stevage** [comment]
Ok, as for what to do about it, this nginx configuration works:

```
include win-utf;
server {
  listen 5080;
   location /... {
     proxy_pass https://mapsengine.google.com;
     source_charset windows-1251;
     charset        utf-8;
  }
}
```

**Comment by kgrochow** [comment]
If gme has fixed their wms support, we can close this.
