### ISSUE TITLE
Layer names are not recorded in Google Analytics when user enters via Share URL

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#6610]
When a user goes to a Terria instance and adds a layer using the catalogue we record an Event in Google Analytics. However, it appears that we do not record an event for the specific layer(s) when they view a layer using a Share URL (we do however record it when using a Story URL). We do record the Share URL itself which is good and potentially helpful in certain situations, but we should also record an event for the layer.

We have been asked by a stakeholder if we record an event when they come in using a Share URL. We will need to fix this.

What we want is for a layer that has been shown to a user using a Share URL to be recorded as a Google Analytics event, so we can find it in the list of layers being accessed in Google Analytics, and accurately report on it, e.g. the Transmission Lines in NationalMap:

<img width="1264" alt="Screen Shot 2022-11-01 at 17 02 42" src="https://user-images.githubusercontent.com/5283003/199169148-cfdc6e05-3662-4b88-9982-b0863c933f80.png">

When you go to NatMap and navigate the catalogue and add it through the catalogue (you can do it from a share to the metadata page in the catalogue, just click Add To The Map here: https://nationalmap.gov.au/#share=s-9el4phg2QZzUfbkBdTUHCm4vIfC), we record this Google Analytics Event:

<img width="942" alt="Screen Shot 2022-11-01 at 17 55 41" src="https://user-images.githubusercontent.com/5283003/199176549-57c9d9d5-1d7c-4676-b427-fde286c2caca.png">

That is:
> Event Category: Data Source
> Event Action: Add from preview button
> Event Label: National Datasets/Energy/Electricity Infrastructure/Transmission/Electricity Transmission Lines

For the purposes of telling our stakeholders how often their layer has been shown, it's the `Event Label` that is key to this, and what we need to also record when the user comes in through a Share URL.

To solve this issue, a Google Analytics Event should be recorded when you visit this Share URL that has the Transmission Lines layer added: https://nationalmap.gov.au/#share=s-l7HlrvjWRTWqLgOY67Q1NkK4wm6

Currently we record an Event with an `Event Label` set to the Share URL only.

The event details should likely be along the lines of:
> Event Category: Data Source
> Event Action: Add from share URL
> Event Label: National Datasets/Energy/Electricity Infrastructure/Transmission/Electricity Transmission Lines

**Comment by AnaBelgun** [comment]
- add tracking on Share url

**Comment by tephenavies** [comment]
- [ ] Determine potential locations in terriajs for this GA event
- [ ] Pick a location that isn't deep in terriajs models system

**Comment by sixlighthouses** [comment]
URL with config using ConsoleAnalytics with a shorted shareURL

http://ci.terria.io/6610-ga-share-url/#configUrl=https%3A%2F%2Fga-testing-bw.storage.googleapis.com%2Fconfig.json&share=s-9AxYHpzxyt4HZ07zqrwdvL7iGHW

Logging event seen in console window

![Pasted image 20230105193016](https://user-images.githubusercontent.com/1597830/210894261-adcd3dd3-ca3d-4def-b7b0-0946878aa7d3.png)
