### ISSUE TITLE
TerriaJS 8.2.22

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#6619]
- [x] https://github.com/terriajs/terriajs/issues/6319
- [x] https://github.com/terriajs/terriajs/issues/6602
- [x] https://github.com/TerriaJS/terriajs/pull/6621
- [x] https://github.com/terriajs/terriajs/issues/6618
- [x] https://github.com/TerriaJS/terriajs/pull/6589
- [x] https://github.com/TerriaJS/terriajs/pull/6640

**Comment by t83714** [comment]
we will release v8.2.22 without 
- https://github.com/TerriaJS/terriajs/pull/6626
- https://github.com/TerriaJS/terriajs/pull/6494

Those two will be released in v8.2.23

**Comment by t83714** [comment]
closed as release pipeline has finished the job:
https://github.com/TerriaJS/terriajs/actions/runs/3598161888/jobs/6060663302
