### ISSUE TITLE
Related Maps popup doesn't scale to mobile screens

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#6633]
The close button gets cut off - the related maps window needs a max-width

<img width="441" alt="image" src="https://user-images.githubusercontent.com/6187649/203907005-97a35d30-2237-48ef-8e9e-78cbe739a35c.png">

**Comment by tephenavies** [comment]
Start in this file: https://github.com/TerriaJS/terriajs/blob/main/lib/ReactViews/RelatedMaps/RelatedMaps.tsx

**Comment by sixlighthouses** [comment]
added media query for mobile screen size and then use max-width: fit-content.
