### ISSUE TITLE
Preview map does not show shapefile points

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#6637]
The following dataset (points only zipped shapefile) displays correctly in Leaflet and Cesium 3D, however the preview map does not show it, apart from a bounding rectangle:

http://ci.terria.io/main/#share=s-czM8vXbXoF6bLHT3SC02D2ckCQw

![image](https://user-images.githubusercontent.com/13863530/204673143-14f6dbb9-ad99-4539-b4f6-8d30fcb06467.png)

**Comment by sixlighthouses** [comment]
Working ![image.png](https://images.zenhubusercontent.com/6396cf6ae52d054e37b49345/3623618e-c6fa-4740-a1f8-55eb2b003104)
