### ISSUE TITLE
Generate more readable URLs

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#669]
Our sharing URLs are just url-encoded JSON. This library would make that better: https://github.com/sage/jsurl

For instance,

`%23start%3D%7B%22version%22%3A%220.0.04%22%2C%22initSources%22%3A%5B%22init%2Fnm.json%22%2C%7B%22catalog%22%3A%5B%7B%22name%22%3A%22National%20Data%20Sets%22%2C%22items%22%3A%5B%7B%22name%22%3A%22National%20Boundaries%22%2C%22items%22%3A%5B%7B%22name%22%3A%22Australian%20Drainage%20Divisions%22%2C%22nowViewingIndex%22%3A0%2C%22isEnabled%22%3Atrue%2C%22isShown%22%3Atrue%2C%22isLegendVisible%22%3Atrue%2C%22opacity%22%3A0.6%7D%5D%7D%2C%7B%22name%22%3A%22Social%20and%20Economic%22%2C%22items%22%3A%5B%7B%22name%22%3A%22Population%20Estimates%22%2C%22nowViewingIndex%22%3A2%2C%22isEnabled%22%3Atrue%2C%22isShown%22%3Atrue%2C%22isLegendVisible%22%3Atrue%2C%22opacity%22%3A0.6%7D%2C%7B%22name%22%3A%22Taxation%20Statistics%202011-2012%22%2C%22nowViewingIndex%22%3A1%2C%22isEnabled%22%3Atrue%2C%22isShown%22%3Atrue%2C%22isLegendVisible%22%3Atrue%2C%22opacity%22%3A0.6%7D%5D%7D%5D%7D%5D%2C%22catalogOnlyUpdatesExistingItems%22%3Atrue%7D%2C%7B%22initialCamera%22%3A%7B%22west%22%3A105.49179470710085%2C%22south%22%3A-40.41550378496932%2C%22east%22%3A163.5158488530014%2C%22north%22%3A-9.333869047319673%2C%22position%22%3A%7B%22x%22%3A-6848574.639326404%2C%22y%22%3A6968230.381870976%2C%22z%22%3A-4981797.819729918%7D%2C%22direction%22%3A%7B%22x%22%3A0.6244648002125203%2C%22y%22%3A-0.635375216364417%2C%22z%22%3A0.4542488830205393%7D%2C%22up%22%3A%7B%22x%22%3A-0.3184088609285113%2C%22y%22%3A0.3239719818249961%2C%22z%22%3A0.8908748241333305%7D%7D%2C%22homeCamera%22%3A%7B%22west%22%3A105.00000000000001%2C%22south%22%3A-45%2C%22east%22%3A155%2C%22north%22%3A-5%7D%7D%5D%7D`

becomes

`~(version~'0.0.04~initSources~(~'init*2fnm.json~(catalog~(~(name~'National*20Data*20Sets~items~(~(name~'National*20Boundaries~items~(~(name~'Australian*20Drainage*20Divisions~nowViewingIndex~0~isEnabled~true~isShown~true~isLegendVisible~true~opacity~0.6)))~(name~'Social*20and*20Economic~items~(~(name~'Population*20Estimates~nowViewingIndex~2~isEnabled~true~isShown~true~isLegendVisible~true~opacity~0.6)~(name~'Taxation*20Statistics*202011-2012~nowViewingIndex~1~isEnabled~true~isShown~true~isLegendVisible~true~opacity~0.6))))))~catalogOnlyUpdatesExistingItems~true)~(initialCamera~(west~105.49179470710085~south~-40.41550378496932~east~163.5158488530014~north~-9.333869047319673~position~(x~-6848574.639326404~y~6968230.381870976~z~-4981797.819729918)~direction~(x~0.6244648002125203~y~-0.635375216364417~z~0.4542488830205393)~up~(x~-0.3184088609285113~y~0.3239719818249961~z~0.8908748241333305))~homeCamera~(west~105.00000000000001~south~-45~east~155~north~-5))))`

Still not great. Maybe there's a better way to have meaningful, readable URLs.

**Comment by maxious** [comment]
Eh, I like that I can debug the share URls anywhere using http://urldecode.org/ and http://jsonformatter.curiousconcept.com

**Comment by stevage** [comment]
Yeah I think you're probably right. Either we make genuinely nice understandable URLs (remove a lot of the boilerplate stuff) or keep as is.

**Comment by kgrochow** [comment]
Not exactly the same issue, but we can probably close based on #875.

**Comment by stevage** [comment]
Agreed.
