### ISSUE TITLE
Location/Locate Me functionality Ideal Zoom zooms in too far and places you under terrain

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#6716]
When using the `Location` button (what I call Locate Me) it adds `My Location` as an item on the workbench. Clicking the `Ideal Zoom` button on this item zooms you in too far, far enough to place the viewport below terrain.

<img width="216" alt="Screenshot 2023-02-28 at 16 12 27" src="https://user-images.githubusercontent.com/5283003/221760127-91567a14-3619-4dd4-8536-ec39e08a0419.png">

<img width="362" alt="Screenshot 2023-02-28 at 16 12 46" src="https://user-images.githubusercontent.com/5283003/221760169-8bb3ee20-160a-4607-a994-1d71b5daf9ab.png">

See video of bug:

https://user-images.githubusercontent.com/5283003/221760489-22bd9677-6d33-47d8-b43a-50066364cd87.mov

We should not zoom in to such an extreme degree, and instead place the viewport e.g. just when the scale switches to be `100m`:

<img width="97" alt="Screenshot 2023-02-28 at 16 16 59" src="https://user-images.githubusercontent.com/5283003/221760776-46eee53d-7729-4731-89a9-3bd2f6e900f1.png">

**Comment by na9da** [comment]
I think this can be fixed. 
[zoom.webm](https://user-images.githubusercontent.com/1430/221775064-219ea184-b55b-403a-9044-0f578a17e73d.webm)



The my location marker is created as geojson catalog item. 
In the current implementation for zoom, we do know how to correctly zoom to a `rectangle` object. But this code path is not used when zooming to a catalog item. 

The zoom code path is a bit of a mess, so it can do with a bit of refactoring.

**Comment by AnaBelgun** [comment]
Update 4 Apr: 
- ideally to be used for visit on 11-12 Apr (training session)

**Comment by AnaBelgun** [comment]
Update 11 Apr: 
- this issue needs a more generic fix which is being discussed within the D61 terria core technical team

**Comment by AnaBelgun** [comment]
Update 18 Apr: 
- @steve9164 kindly reminder to check the PR for this one by next week
