### ISSUE TITLE
Support nested WMS layers

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#672]
Here's an instance of a WMS server with deeply nested layers: http://srss-ows.landgate.wa.gov.au/wxs/firewatch.php?service=wms&request=getCapabilities

Loading it into Terria, it gets flattened out and looks bad - lots of layers with duplicate names like "Band 5". 

I'm guessing the behaviour change is around [here somewhere](https://github.com/TerriaJS/terriajs/blob/master/lib/Models/WebMapServiceCatalogGroup.js#L255) - probably needs to be configurable, as I'm guessing the current flattening behaviour was intentional for existing data sources.

**Comment by kring** [comment]
:+1:
