### ISSUE TITLE
Magda v2 auth upgrade: Update padlock icon UI display logic

### ISSUE THREAD

**Issue by t83714** [TerriaJS/terriajs#6726]
This ticket is created for [DTV Magda v2 Auth Upgrade](https://github.com/TerriaJS/vic-digital-twin-app/issues/63)

The required logic has been specified in section 3.2.2:

https://github.com/TerriaJS/vic-digital-twin-app/blob/17b1729823757282f5a10e8b58dab4167ba4d71e/doc/access-control-in-magda-v1-and-migration-plan.md#322-padlock-ui-logic-changes-in-terriajs

### Technical Notes

- For ease of version management & deployment, we should make the changes backward compatible.
e.g. We can check if aspect "esri-access-control" exists (i.e. it's a Magda v1 backend) to tell whether we should apply the new logic (for Magda v2)
Another option to check the backend version is to check the `authnReadPolicyId` field of the registry record --- the `authnReadPolicyId` field has been removed since Magda v2

- Pseudocode of the desired logic

```
if (`esri-access-control` exists) {
  if(!isEmpty(`esri-access-control`.`access`) && `esri-access-control`.`access` != 'public') {
    show padlock
  } else {
    hide padlock
  }
} else if(`access-control` exists) {
  // the logic here should be updated according to our migration plan setup
  if(isUuid(access-control`.`orgUnitId `)) {
    show padlock
  } else {
    hide padlock
  }
} else {
  hide padlock
}
```
p.s. the link to `access-control` aspect definition
https://github.com/magda-io/magda/blob/master/magda-registry-aspects/access-control.schema.json

**Comment by mwu2018** [comment]
@t83714 What is the ID of the new Magda access control aspect? Is it `access-control` or something else?
I'd suggest that underscore be used instead of hyphens so that we are able to write code like
```
  if (isUuid(record?.aspects?.access_control?.orgUnitId)) {
    ...
  }
```

**Comment by t83714** [comment]
@mwu2018 
yes it's `access-control`. 
And the definition is here: https://github.com/magda-io/magda/blob/master/magda-registry-aspects/access-control.schema.json
You still can use `optional operator` like `record?.aspects?.["access-control"]?.orgUnitId `

> By the way, `access-control` is the id return from registry API and used by Magda but if your frontend code already reformat the spelling, it could be something else (e.g. `accessControl`) 

> p.s. the logic above assumes we are going to make records (that not carry any access control info) public. I will consult more people to see if it's a good idea. If we go the other way around, we might need a different logic.

**Comment by mwu2018** [comment]
I think magda v2 should override v1 if both aspects are present. My PR implements this logic.
