### ISSUE TITLE
Discuss whether we should continue using Leaflet in Terria

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#6739]
8 years ago it was a good idea to have an alternate renderer that didn't require WebGL, and was a little lighter on resources. Should we now switch our 2D map to Cesium 2D? Or maplibre? This might improve performance of the 2D view.

**Comment by nf-s** [comment]
Related

- https://github.com/TerriaJS/terriajs/issues/6550
- https://github.com/TerriaJS/terriajs/pull/6605

Things we need to think about

- Preview map
- Printing from 2D view
- Pedestrain view map

I am all for simplification here. If we decide to remove it (and I think we should), then I think using cesium 2D is the way to go.

Adding maplibre would be a lot of work. I don't think TerriaJS needs another huge dependency 😂

**Comment by nf-s** [comment]
We have decided against this for the following reasons

- Leaflet is useful to keep for low-performance devices
- We would need to replace the Leaflet preview map (for the catalog and pedestrian mode) with Cesium - which would have performance overhead
- Leaflet is more reliable and well-maintained than Cesium's 2D mode
