### ISSUE TITLE
Refine error messages for authorisation

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/terriajs#6749]
Error messages shown after logged in users try to access un-authorised datasets, are not clear and different. 
This ticket is to: 
- audit the current error messages
- create one error message for auth / un-authorised data access use case

Examples of behaviours: 
1. User clicks on share url with restricted datasets; logs in; there is no error message unless the user clicks on "Explore map data" 
2. User logs in; tries to add restricted data (padlock) and gets a variety of error messages. 

![Screenshot 2023-04-04 at 11 24 16 am](https://user-images.githubusercontent.com/18452161/229662216-49802260-776b-4ee0-8bd1-3434115a57d4.png)
![Screenshot 2023-04-04 at 11 25 09 am](https://user-images.githubusercontent.com/18452161/229662322-0b9e446a-4df7-41a4-9a29-935c6a96eaa9.png)

**Comment by nf-s** [comment]
Dupe
