### ISSUE TITLE
Error message templating issue

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#6788]
When we get an error message (in this case because the layer `fcp_seasonal_rgb` no longer exists on this WMS server) the error message shows some uninterpolated templating strings:

<img width="513" alt="Screen Shot 2022-11-07 at 14 33 39" src="https://user-images.githubusercontent.com/5283003/200221016-f3300577-e3e9-4c91-8e4d-c365e3040272.png">

Test it using this layer: https://nationalmap.gov.au/#share=s-qMsFwR9q6F2PJB3IycvgMdKcQEi
As we are going to fix that layer you may have to create your own test case - just change the specified WMS layer name in the config to something that doesn't exist.

**Comment by tephenavies** [comment]
Probably mismatched parameters between the error message in the translation strings file (en/translation.json) and the parameters passed to `t` function (wherever that translation string is being used). Maybe terriajs 7 used to pass these and the parameters no longer exist since version 8?

**Comment by mwu2018** [comment]
@meh9 A request to the URL you provided will get different error message from yours. I am unable to identify which catalog item caused the error with that shared URL alone. Could you please help? It looks like that the ticket has been out-of-date and the issue no longer exists.

![image](https://user-images.githubusercontent.com/41275384/235391422-30c40b75-f31a-4c08-a396-05fb48967603.png)

The shared link provides the following data
```
{
  "version": "8.0.0",
  "initSources": [
    {
      "stratum": "user",
      "models": {
        "1g57wdJg": {
          "dereferenced": {
            "isOpen": true
          },
          "knownContainerUniqueIds": [
            "Root Group/National Data Sets"
          ],
          "type": "terria-reference"
        },
        "sUetdV1C": {
          "isOpen": true,
          "knownContainerUniqueIds": [
            "1g57wdJg"
          ],
          "type": "group"
        },
        "z3iM4N75": {
          "isOpen": true,
          "knownContainerUniqueIds": [
            "sUetdV1C"
          ],
          "type": "group"
        },
        "SIKHTCzc": {
          "isOpen": true,
          "knownContainerUniqueIds": [
            "sUetdV1C"
          ],
          "type": "group"
        },
        "/": {
          "type": "group"
        },
        "Root Group/National Data Sets": {
          "knownContainerUniqueIds": [
            "[/](https://nationalmap.gov.au/)"
          ],
          "type": "group"
        }
      },
      "workbench": [],
      "timeline": [],
      "initialCamera": {},
      "homeCamera": {},
      "viewerMode": "3d",
      "showSplitter": false,
      "splitPosition": 0.5,
      "settings": {
        "baseMaximumScreenSpaceError": 1.5,
        "useNativeResolution": true,
        "alwaysShowTimeline": false,
        "baseMapId": "basemap-bing-aerial-with-labels",
        "terrainSplitDirection": 0,
        "depthTestAgainstTerrainEnabled": false
      },
      "previewedItemId": "80df5d0b",
      "stories": []
    }
  ]
}
```
where `80df5d0b` is `previewedItemId` that does not exist.

**Comment by AnaBelgun** [comment]
not a problem anymore; will reopen if error is reproduced again

**Comment by tephenavies** [comment]
Can be reproduced with this catalogue: http://ci.terria.io/main/#clean&https://gist.githubusercontent.com/steve9164/9b5b6d5c4f763cd6f320b1cd98520b8e/raw/2501e68d4357f2be36e2d77f2c5e314a8b0a7f57/no-layer.json
