### ISSUE TITLE
Losing Z values when multiple KML files are overlaid

### ISSUE THREAD

**Issue by imakihi** [TerriaJS/terriajs#6799]
When I drag and drop the same KML file twice, then it looks like the second data lose the Z value on the map. 
In the following image and video, those two triangles are the exactly the same KML data. I added #1 first followd by #2.
I attached the KML file I tested.

![image](https://github.com/TerriaJS/terriajs/assets/4824436/f54c65d6-2996-4bb7-b40d-b7ba369c3581)
[test.zip](https://github.com/TerriaJS/terriajs/files/11673243/test.zip)

https://github.com/TerriaJS/terriajs/assets/4824436/a06a7b17-02e8-4192-8ff8-1be069863504

**Comment by imakihi** [comment]
I realized that this doesn't happen on https://vic.digitaltwin.terria.io/
![image](https://github.com/TerriaJS/terriajs/assets/4824436/630f307b-505f-4282-b1ce-820d5044f017)

**Comment by imakihi** [comment]
And it always appeard as flat polygon on https://nsw.digitaltwin.terria.io/
![image](https://github.com/TerriaJS/terriajs/assets/4824436/7c05de95-eb7d-4cca-bda8-5090e5d6ef1b)

**Comment by imakihi** [comment]
So, I tested ver 8.3.0 and I didn't see this issue. So, I guess this issue is resolved in the latest version.
So, I am going to close this.
Thank you!!
Hiroo

**Comment by imakihi** [comment]
Hi there. I need to reopen this issue.
After we examined various Terria sites, only the Victoria site doesn't have this problem. We tested TerriaJS 3.2.X, 8.3.2 and 8.3.3 but they all had this issue. 

Issue:
When I locally import KML files twice, KML layers lose their hight (z). Sometime, KML layers are showed as 2D polygon in the 3D mode.

To replicate this issue, please locally import KML polygons. Here is my sample data (you need to change its extension to .kml).
[test_polygon.txt](https://github.com/TerriaJS/terriajs/files/12810841/test_polygon.txt)

Here is the version of Victoria instance
![image](https://github.com/TerriaJS/terriajs/assets/4824436/d6cd7bbd-8d39-4897-ae47-abb00a0d25e8)

We tried this version
![image](https://github.com/TerriaJS/terriajs/assets/4824436/a9d49ab7-e2d4-4fa9-8eb7-802e2c92eee0)

and others. When you load this data in the 2D mode and change to the 3D mode, it shows as 3D geometry but if you import the same KML again, it become 2D polygon.

It would be great if someone can find the solution.

Thanks.

**Comment by nf-s** [comment]
Hi @imakihi 

Please see my PR here and let me know if that fixes your issue

- https://github.com/TerriaJS/terriajs/pull/6952

**Comment by imakihi** [comment]
Hi Nick. Thank you for working on this. I will check this shortly.
Best regards.
Hiroo

**Comment by imakihi** [comment]
@nf-s 
It worked!! Thank you for this!!!!!!
Best. Hiroo
