### ISSUE TITLE
Dataset - Coverage map - Victoria - Optus - 4G - 2022 - causes Geoserver to timeout when querying

### ISSUE THREAD

**Issue by sixlighthouses** [TerriaJS/terriajs#6810]
To reproduce, 
In DTV load 
Projects -> Telecommunications Infrastructure -> ACCC Mobile Infrastructure Report 2022 -> Coverage map - Victoria - Optus - 4G - 2022

Use Search function on the above dataset.  Returns a timeout error to DTV and on checking Geoserver it will return 504's for around 5 mins.

![image.png](https://images.zenhubusercontent.com/6396cf6ae52d054e37b49345/2ac43f5b-4fbc-47be-8fbb-10042815e17e)![Screenshot 2023-06-22 133549.png](https://images.zenhubusercontent.com/6396cf6ae52d054e37b49345/657aaae9-b7b3-4ad7-99b9-1e24c8209e69)

**Comment by AnaBelgun** [comment]
moved to https://github.com/TerriaJS/devops/issues/145
