### ISSUE TITLE
Fix broken embedded video link in story panel

### ISSUE THREAD

**Issue by mwu2018** [TerriaJS/terriajs#6843]
A user is able to create a story with embedded video. However, when the story is loaded, the video part is dropped.

Related issue https://github.com/TerriaJS/vic-digital-twin/issues/541.

**Comment by nf-s** [comment]
From discussion today

- Happy with Mike's current approach of checking iframes in story body
- There is a hard-coded list of allowed URLS (eg YouTube and Vimeo)
  - We will avoid adding to configuration, as it may allow use of `#configUrl` to change allowed URLs
- If any iframes exist in the story with URL that is not allowed - all iframes are removed
- This approach will work with Story Editor "Media" button

**Comment by nf-s** [comment]
- [x] Add youtube "no-cookies" domain
- [x] Add vimeo domain
