### ISSUE TITLE
missing styles parameter on wms getfeatureinfo requests

### ISSUE THREAD

**Issue by pvgenuchten** [TerriaJS/terriajs#6849]
in a default installation [mapserver](https://mapserver.org) requires the styles parameter to be included on wms getfeatureinfo requests (as mandated by ogc) (but you can deactivate it with the `wms_allow_getmap_without_styles` on web metadata). terria does not include this parameter, which makes featureinfo requests fail

to consider is to add the styles parameter to wms requests, the parameter can be empty, to use the default style

note: i remember an issue with some esri server, it requires &styles=&, not &styles&

**Comment by na9da** [comment]
Thanks @pvgenuchten for the report. 

Looks like you are correct. [From the spec](https://docs.geoserver.org/2.23.x/en/user/services/wms/reference.html#getfeatureinfo):
![image](https://github.com/TerriaJS/terriajs/assets/1430/4aed5462-6dc1-49ce-bd13-95c4b1e75c80)


We currently set the `styles` param only if it has a non-empty value but I think we should set it for all requests:
https://github.com/TerriaJS/terriajs/blob/b14835b75232eb8be722c6255f9c6e1789b1f5cb/lib/Models/Catalog/Ows/WebMapServiceCatalogItem.ts#L526-L529

**Comment by na9da** [comment]
If you need a temporary fix, you could try forcing it by setting `getFeatureInfoParameters` in your catalog:

eg: 
```json
{
  ...
  "getFeatureInfoParameters": {
        "styles": ""
   },
}
```

**Comment by nf-s** [comment]
Not sure I agree that `styles` is strictly required on `GetFeatureInfo` requests.

The spec states "Partial copy of the Map request parameters that generated the map for which information is desired."

![image](https://github.com/TerriaJS/terriajs/assets/6187649/73f64739-379b-4038-8777-a104c018c84e)

Which is vague. In this issue they assumed that `styles` is not required

- https://github.com/mapserver/mapserver/issues/6812

**Comment by nf-s** [comment]
Oh wait I got that reversed! I should have read https://github.com/mapserver/mapserver/issues/6812 more closely

Looks like they are assuming `styles` as part of "Partial copy of the Map request parameters that generated the map for which information is desired."

Also from the spec

<img width="898" alt="image" src="https://github.com/TerriaJS/terriajs/assets/6187649/256d59df-a494-4a73-b168-68ba4a44d649">
