### ISSUE TITLE
WMS bbox doesn't inherit from parent `Layers`

### ISSUE THREAD

**Issue by pvgenuchten** [TerriaJS/terriajs#6860]
when adding url https://gaez-services.fao.org/server/services/LR/ImageServer/WMSServer?request=GetCapabilities&service=WMS to a v8.3.2 terria via my-data > add-web-data, i'm able to select a layer, but when adding it to the map, get this error:

```
[mobx] uncaught error in 'Reaction[Autorun]' TypeError: Cannot read properties of undefined (reading 'east')
    at u.intersection (3.TerriaMap.js:6:147988)
    at F._createTileImagerySkeletons (3.TerriaMap.js:91:767661)
    at 3.TerriaMap.js:243:1663438
    at Rn.forEachLoadedTile (3.TerriaMap.js:243:1695526)
    at kt._onLayerAdded (3.TerriaMap.js:243:1663405)
    at i.raiseEvent (3.TerriaMap.js:6:77894)
    at bn.add (3.TerriaMap.js:243:1683346)
    at 3.TerriaMap.js:91:390978
    at u (3.TerriaMap.js:1:34610)
    at et (3.TerriaMap.js:1:27670)
```
Also tried adding it via a config file, with isEsri:true and/or crs:"epsg:4326", all failed. any guidance on using wms which does not support epsg:3857?

Thanx for checking, great work there on Terria!

**Comment by nf-s** [comment]
Hi @pvgenuchten

This is an interesting issue! I'm not entirely sure what is going on here. I think there is something going wrong in how Ceisum is calculating the bounding box for your WMS services.

I was able to get your WMS group working by manually specifying a `rectangle` - (note `itemProperties` will automatically apply `rectangle` to all `WebMapServiceCatalogItems` created by the `WebmapServiceCatalogGroup`)

```json
{
  "homeCamera": {
    "north": -8,
    "east": 158,
    "south": -45,
    "west": 109
  },
  "catalog": [
    {
      "url": "https://gaez-services.fao.org/server/services/LR/ImageServer/WMSServer?request=GetCapabilities&service=WMS",
      "type": "wms-group",
      "name": "Test WMS",
      "itemProperties": {
        "rectangle": {
          "west": -180,
          "south": -90,
          "east": 180,
          "north": 90
        }
      }
    }
  ],
  "viewerMode": "3dSmooth",
  "baseMaps": {
    "defaultBaseMapId": "basemap-positron",
    "previewBaseMapId": "basemap-positron"
  }
}
```

You can test it with the following link

http://ci.terria.io/main/#start={%22version%22:%228.0.0%22,%22initSources%22:[%7B%22homeCamera%22%3A%20%7B%22north%22%3A%20-8%2C%22east%22%3A%20158%2C%22south%22%3A%20-45%2C%22west%22%3A%20109%7D%2C%22catalog%22%3A%20%5B%7B%22url%22%3A%20%22https%3A%2F%2Fgaez-services.fao.org%2Fserver%2Fservices%2FLR%2FImageServer%2FWMSServer%3Frequest%3DGetCapabilities%26service%3DWMS%22%2C%22type%22%3A%20%22wms-group%22%2C%22name%22%3A%20%22Test%20WMS%22%2C%22itemProperties%22%3A%20%7B%22rectangle%22%3A%20%7B%22west%22%3A%20-180%2C%22south%22%3A%20-90%2C%22east%22%3A%20180%2C%22north%22%3A%2090%7D%7D%7D%5D%2C%22viewerMode%22%3A%20%223dSmooth%22%2C%22baseMaps%22%3A%20%7B%22defaultBaseMapId%22%3A%20%22basemap-positron%22%2C%22previewBaseMapId%22%3A%20%22basemap-positron%22%7D%7D]}&share=s-uYaqG876u1nnKoCv50UYsMW0wxm

**Comment by nf-s** [comment]
Your WMS service works in the latest version of Cesium

https://sandcastle.cesium.com/#c=bVNdb9owFP0rVp5AAns00A9K0RCrtklUq4g0pCkvJrkJVh0b2TdUdOK/z44DSru++d5z7s3x8UmmlUVyEPAKhjwQBa9kCVbUFf3d9HpplDX1UivkQoFJo/59qlLFGFnkOeFk85QQUfESzJFIfnQMlTVbm+L90p+Bt/JIL1Wki21g+8T3CZiDyKAlPht9ELnj/vVkQtKoNjKNpu6wQ9zbKWMlh7ehDVOWFlxTbUrmG2DYuc9Wa9asTELfaQ6nNBqcNzdybVi+Wk8Xj3/IUnJrRSEyjkIr0ovj0ALb7wzuueEVYDvcKg0QGq6sw0Ghx9DUMOjihTYVx/DNxkO2V+VldeBYPEpodeVQ8FriB4a7h3X6AmVEY/oljQJ+uojMzld7fE6+T8fx1XXnBigkbESOO0+5mly/A36AKHfYIh449VPlMxBSQ0XnTS3led5rnLykJEFukOiiIFLrF6FKwpEsauu8kYLTy57MmWg4tYA+euHFc7AoVOP+9JyTNWTIVSmBFkZX36A0ALYXFI9GYzq5G7X6h+MJvY1v2mo0vqV352I4oTexP/Zd49S/J9EgmjVOz8/OfhXVXjvlLnE9ShlCtZccXZa2dfYCSDNr/R09dca6o7NcHIjIHz75dUjm4+OQopYyEW+QRvMZc/z/RqXmufPql3tbZ6en7UbzVWhSSmfMlZ9PotZyy82Hzf8A

**Comment by pvgenuchten** [comment]
Ah, so probably the capabilities has no boundingbox (or in unexpected axis order), I’ll try your suggestion, thanx. Does it make sense to keep this open, maybe for nicer error handling?

(This wms is outside my control, but I can point them to this issue)

**Comment by nf-s** [comment]
I actually found two bugs in TerriaJS! So please leave this issue open until the PR has been merged.

The WMS capabilities you provided is totally fine. Our first issue was we were missing a null check - so Layers without bbox were returning a bbox of 0 size. The second issue is that Layers should inherit the bbox property from parent Layers - but TerriaJS didn't have that capability.

I have a PR to fix both of these - https://github.com/TerriaJS/terriajs/pull/6864

Until that is merged and released you can set the `rectangle` manually.

Thanks for bringing the bugs to our attention!
