### ISSUE TITLE
The `y-column` attr in `FeatureInfoPanelChart` (`<chart>`) is not working

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#6882]
Related to 

- #6434 
- https://github.com/TerriaJS/terriajs/issues/6758
- https://github.com/TerriaJS/terriajs/issues/2258

Example - the feature info template is supposed to show `z` column along x-axis and the `plant height` column along y-axis.

```json
    {
      "name": "Test",
      "type": "csv",
      "url": "http://ci.terria.io/main/build/TerriaJS/test/csv/lat_lon_nullvalue.csv",
      "featureInfoTemplate": {
        "name": "Number {{value}}",
        "template": "<p>All train stations have the same x-y plot.</p><chart src='http://ci.terria.io/main/build/TerriaJS/test/csv_nongeo/x_height.csv' x-column='z' y-columns='plant height'></chart>"
      }
    }
```

Instead it uses `z` as the `yColumn`

- [Test link](http://ci.terria.io/main/#clean&start=%7B%22version%22%3A%20%228.0.0%22%2C%20%22initSources%22%3A%20%5B%7B%22catalog%22%3A%20%5B%7B%22name%22%3A%20%22Train%20Stations%22%2C%22type%22%3A%20%22csv%22%2C%22url%22%3A%20%22http%3A%2F%2Fci.terria.io%2Fmain%2Fbuild%2FTerriaJS%2Ftest%2Fcsv%2Flat_lon_nullvalue.csv%22%2C%22featureInfoTemplate%22%3A%20%7B%22name%22%3A%20%22Number%20%7B%7Bvalue%7D%7D%22%2C%22template%22%3A%20%22%3Cp%3EAll%20train%20stations%20have%20the%20same%20x-y%20plot.%3C%2Fp%3E%3Cchart%20src%3D'http%3A%2F%2Fci.terria.io%2Fmain%2Fbuild%2FTerriaJS%2Ftest%2Fcsv_nongeo%2Fx_height.csv'%20x-column%3D'z'%20y-columns%3D'plant%20height'%3E%3C%2Fchart%3E%22%7D%7D%5D%7D%5D%7D)
- Add "Test" to workbench
- Click on feature
- It looks like

<img width="330" alt="image" src="https://github.com/TerriaJS/terriajs/assets/6187649/ba135739-98dc-4ad9-8354-3870befaff53">

It should look something like

<img width="522" alt="image" src="https://github.com/TerriaJS/terriajs/assets/6187649/3f664830-5b16-4094-95b0-4cc2b7740256">

**Comment by nf-s** [comment]
`idProperty` in `objectArrayTrait` strikes again!

https://github.com/TerriaJS/terriajs/blob/08d90daf6d51b3dcbc2247002aec4fbb0dff5c87/lib/Traits/TraitsClasses/Table/ChartStyleTraits.ts#L58-L65

`y-column` and `y-columns` are correctly setting `CsvCatalogItem` `Traits` - but they are being merged in a funky way with the `defaultChartStyle`

https://github.com/TerriaJS/terriajs/blob/ed7c97fc722a1719e3b24f661bdde41c6bf7edce/lib/Table/TableAutomaticStylesStratum.ts#L146-L171

### The `user` stratum set in `CsvChartCustomComponent`

```json
{
  "styles": [
    {
      "id": "chart",
      "chart": {
        "xAxisColumn": "z",
        "lines": [
          {
            "yAxisColumn": "plant height"
          }
        ]
      }
    }
  ]
}
```

### The `defaultChartStyle` from `automaticTableStyles` stratum set in `TableAutomaticStylesStratum`

```json
{
  "chart": {
    "xAxisColumn": "x",
    "lines": [
      {
        "yAxisColumn": "z"
      },
      {
        "yAxisColumn": "plant height"
      }
    ]
  }
}
```

### Merged

```json
{
  "xAxisColumn": "z",
  "lines": [
      {
          "yAxisColumn": "z"
      },
      {
          "yAxisColumn": "plant height"
      }
  ]
}
```

**Comment by tephenavies** [comment]
We could:
* Add `merge: false` (see [changes to be PR'd](https://github.com/TerriaJS/terriajs/compare/fix-columns-merging)) to 
https://github.com/TerriaJS/terriajs/blob/4f419c5f23203e023683532b67057082358bd666/lib/Traits/Decorators/objectArrayTrait.ts#L26-L29
* Set `isRemoval` and allow `name` to be set to `null`, similar to [`InfoSectionTraits`](https://github.com/TerriaJS/terriajs/blob/4f419c5f23203e023683532b67057082358bd666/lib/Traits/TraitsClasses/CatalogMemberTraits.ts#L44-L78)
https://github.com/TerriaJS/terriajs/blob/4f419c5f23203e023683532b67057082358bd666/lib/Traits/TraitsClasses/CatalogMemberTraits.ts#L75-L77
Doing it that way means you don't permanently change the merging behaviour in all cases (you might want to e.g. set the color and name in a different stratum to yAxisMinimum)


* Add a full DSL for manipulating arrays from lower strata to ObjectArrayTraits 🤯

**Comment by nf-s** [comment]
Yeah I think setting merge to false may be the best way forward. I can’t find any catalog items in our maps that use `lines`/`TableChartLineStyleTraits` - so it shouldn’t break anything.

**Comment by nf-s** [comment]
I think it's worth doing a quick survey of all uses of `objectArrayTrait`. I like @na9da's idea of making `merge` a required property - and thinking about which traits should have `merge=false`.

Also, maybe there needs to be a generic `isRemoval` property on all objects - for example `__removeElement__`. It isn't pretty, but we've struggled with this issue in the past

**Comment by nf-s** [comment]
Raised in `open-data-cube` Slack

**Comment by nf-s** [comment]
Also impacts AREMI datasets in NationalMap
