### ISSUE TITLE
WPS: default value for time widgets?

### ISSUE THREAD

**Issue by sppigot** [TerriaJS/terriajs#6895]
It would be nice if WPS datetime inputs would use the current value of the date-time slider e.g. Here is an datetime input to a WPS from a DescribeProcess WPS call:

```
<Input minOccurs="1" maxOccurs="1">
                <ows:Identifier>ReportTime</ows:Identifier>
                <ows:Title>Surf report time</ows:Title>
                <ows:Abstract>The time at which to produce the surf report</ows:Abstract>
                <ComplexData maximumMegabytes="1024">
                    <Default>
                        <Format>
                            <MimeType>application/vnd.geo+json</MimeType>
                            <Schema>http://www.w3.org/TR/xmlschema-2/#dateTime</Schema>
                        </Format>
                    </Default>
                    <Supported>
                        <Format>
                            <MimeType>application/vnd.geo+json</MimeType>
                            <Schema>http://www.w3.org/TR/xmlschema-2/#dateTime</Schema>
                        </Format>
                    </Supported>
                </ComplexData>
</Input>
```

At the moment, when collecting info for the WPS inputs via the auto generated form, Terria will use a widget for this input with no values set: 

![terria-wps](https://github.com/TerriaJS/terriajs/assets/1842016/84035d25-0e69-4fc8-8e5e-9ac1c0d603bc)

Yet it is often the case with a time series layer (say from THREDDS) that a date-time has been selected in the time slider. Could this be used as a default value for the date-time widget?

**Comment by sixlighthouses** [comment]
merged with PR #7026
