### ISSUE TITLE
WPS: Date or time widget reset after typing in values is unexpected (chrome)

### ISSUE THREAD

**Issue by sppigot** [TerriaJS/terriajs#6896]
When manually typing in either a date to the date time widgets in chrome (116.0.5845.188 or 117.0.5938.89 but this has been around in earlier versions too) the browser will reset and lose the value in the time widget. The opposite also happens in that, if you type in a time in the time widget, then your previously entered date will be reset and lost. e.g.

Typed in a date to the date widget:

![typing-in-date](https://github.com/TerriaJS/terriajs/assets/1842016/0f049afe-a3c1-48f7-aeca-b82913636356)

Then typing in a time to the time widget and the date widget gets reset: and my previously entered date is lost:

![typing-in-a-time](https://github.com/TerriaJS/terriajs/assets/1842016/832a10f9-a3d2-43a1-ada3-945b72c96c7e)

This is a bit frustrating for power users who don't use the click helpers.

Doesn't seem to happen with firefox.

**Comment by AnaBelgun** [comment]
Update 5 Jan 
- patching it as a React 18 tss component (convert to a class component as a transitionary step) or refactoring? Brendon will look into properly refactoring because it's a popular component/used in many places

**Comment by sixlighthouses** [comment]
Draft PR https://github.com/TerriaJS/terriajs/pull/7021

**Comment by sixlighthouses** [comment]
requires some rework, with reference to PR comments
