### ISSUE TITLE
WPS: allowedValues and defaultValue support for WPS Input LiteralData

### ISSUE THREAD

**Issue by sppigot** [TerriaJS/terriajs#6897]
For any literal input a WPS can specify a list of allowed values as a range or as a list of values e.g.

''''
<Input minOccurs="1" maxOccurs="1">
  <ows:Identifier>KeelDepth</ows:Identifier>
  <ows:Title>Keel Depth</ows:Title>
  <ows:Abstract>Draft of the landing boat</ows:Abstract>
  <LiteralData>
    <ows:DataType ows:reference="http://www.w3.org/TR/xmlschema-2/#float">float</ows:DataType>
    <ows:AllowedValues>
      <ows:Range ows:rangeClosure="closed">
        <ows:MinimumValue>1.0</ows:MinimumValue>
        <ows:MaximumValue>2.0</ows:MaximumValue>
      </ows:Range>
    </ows:AllowedValues>
    <DefaultValue>2.0</DefaultValue>
  </LiteralData>
</Input>
''''

TerriaJS should read and require user input to follow the allowed values (range or list) and initialise the form field with the defaultValue. Currently, if I include a WPS LiteralData Input (KeelDepth) with an AllowedValues element, TerriaJS trips an error on the browser console with the message: "The parameter KeelDepth is not a supported type of parameter."

**Comment by sixlighthouses** [comment]
Draft PR https://github.com/TerriaJS/terriajs/pull/7033
