### ISSUE TITLE
Pedestrian mode - mouse capture bug

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#6935]
When using the pedestrian mode, sometimes the mouse down behaviour will revert to the normal camera movement.

- Go to http://ci.terria.io/main/
- 3d mode
- Activate pedestrian mode
- Press "space" for a few seconds to increase the height of the camera
- Click on the terrain and drag mouse down the screen
- Observe that the camera starts to move along the terrain (as it does when pedestrian mode is not active)
- Instead, the camera should just tilt down without changing position

**Comment by na9da** [comment]
Yeah, there is definitely something weird happening evening at ground level and is most evident when dragging the mouse to look up which pushes the pedestrian slightly backwards. Definitely not the desired behaviour. Needs further investigation.
