### ISSUE TITLE
Issue causing fail to build

### ISSUE THREAD

**Issue by RayShao01010010** [TerriaJS/terriajs#6979]
I'm using a different sass and it's more strict on the syntax. You are missing a `;` 
```
ERROR in ./node_modules/terriajs/lib/ReactViews/Analytics/invoke-function.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: expected ";".
   ╷
34 │ @include empty-module("description") .btn {
   │   
```

Change this
```
@include empty-module("description") .btn {
  composes: btn from "../../Sass/common/_buttons.scss";
  composes: btn-primary from "../../Sass/common/_buttons.scss";
}
```

to this will fix this issue
```
@include empty-module("description"); 

.btn {
  composes: btn from "../../Sass/common/_buttons.scss";
  composes: btn-primary from "../../Sass/common/_buttons.scss";
}
```

**Comment by nf-s** [comment]
Hi @RayShao01010010 

We have just replaced `node-sass` with `sass` - so this should be fixed now in TerriaJS `8.4.0`

You can see the changes here

https://github.com/TerriaJS/terriajs/pull/6862/files#diff-b44db48868dd0b79a2324cc4ee9fc563808f11910d835f969e73edf1c03a015d

I am going to close this issue, feel free to re-open if you have any issues. Thanks!
