### ISSUE TITLE
Adapt existing apps to configurable search providers

### ISSUE THREAD

**Issue by ljowen** [TerriaJS/terriajs#6990]
After breaking changes to terriajs we need to update existing applications to be compatible with this change.

[] - DTV
[] - EAP
More to come

**Comment by nf-s** [comment]
Hi @ljowen 

I have replaces this with tickets for each map/platform

- https://github.com/TerriaJS/vic-digital-twin/issues/585
- https://github.com/TerriaJS/eap-digital-twin/issues/186
- https://github.com/TerriaJS/saas-catalogs-public/issues/386

Do you mind if I close this ticket?

**Comment by ljowen** [comment]
Go for it!
