### ISSUE TITLE
TerriaJS release `8.5.0` - Cesium upgrade

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/terriajs#7027]
- [x] Change terriajs-cesium main branch to `main` - with latest changes
- [ ] Add cesium CHANGELOG (see [comment](https://github.com/TerriaJS/terriajs/issues/7027#issuecomment-1928654415))
- [ ] Test it

**Comment by nf-s** [comment]
Cesium upgrade from `1.92.0` to `1.113.0`. You can see the full list of changes here

- https://github.com/CesiumGS/cesium/blob/main/CHANGES.md#1113---2024-01-02

High-level changes that may be of interest:

#### Breaking changes

- Firefox 114 is now the minimum Firefox version required to run CesiumJS. [#11400](https://github.com/CesiumGS/cesium/pull/11400)

#### Additions

- Vertical exaggeration can now be applied to a `Cesium3DTileset`. Exaggeration of `Terrain` and `Cesium3DTileset` can be controlled simultaneously via the new `Scene` properties `Scene.verticalExaggeration` and `Scene.verticalExaggerationRelativeHeight`. [#11655](https://github.com/CesiumGS/cesium/pull/11655)
- Added `createGooglePhotorealistic3DTileset` to create a 3D tileset streaming Google Photorealistic 3D Tiles.
- Added smooth zoom with mouse wheel. [#11062](https://github.com/CesiumGS/cesium/pull/11062)
- CesiumJS now defaults to using a WebGL2 context for rendering. WebGL2 is widely supported on all platforms and this results in better feature support across devices, especially mobile.
  - WebGL1 is supported. If WebGL2 is not available, CesiumJS will automatically fall back to WebGL1.
  - In order to work in a WebGL2 context, any custom materials, custom primitives or custom shaders will need to be upgraded to use GLSL 300.
  - Otherwise to request a WebGL 1 context, set `requestWebgl1` to `true` when providing `ContextOptions` as shown below:
    ```js
    const viewer = new Viewer("cesiumContainer", {
      contextOptions: {
        requestWebgl1: true,
      },
    });
    ```
- Added experimental support for 3D Tiles voxels with the [`3DTILES_content_voxels`](https://github.com/CesiumGS/3d-tiles/tree/voxels/extensions/3DTILES_content_voxels) extension. The current implementation is intended for development use, as the voxel format has not yet been finalized and is subject to breaking changes without deprecation.
- Added support for I3S 3D Object and IntegratedMesh Layers. [#9634](https://github.com/CesiumGS/cesium/pull/9634)
- CesiumJS has switched to a new architecture for loading glTF models and tilesets to enable:
  - User-defined GLSL shaders via [`CustomShader`](Documentation/CustomShaderGuide/README.md)
  - Support for [3D Tiles Next](https://cesium.com/blog/2021/11/10/introducing-3d-tiles-next/) metadata extensions: [`EXT_structural_metadata`](https://github.com/CesiumGS/glTF/tree/proposal-EXT_structural_metadata/extensions/2.0/Vendor/EXT_structural_metadata), [`EXT_mesh_features`](https://github.com/CesiumGS/glTF/tree/proposal-EXT_mesh_features/extensions/2.0/Vendor/EXT_mesh_features) and [`EXT_instance_features`](https://github.com/CesiumGS/glTF/tree/3d-tiles-next/extensions/2.0/Vendor/EXT_instance_features)
  - Support for [`EXT_mesh_gpu_instancing`](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Vendor/EXT_mesh_gpu_instancing)
  - Support for [`EXT_meshopt_compression`](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Vendor/EXT_meshopt_compression)
  - Texture caching across different tiles
  - Numerous bug fixes
- Usage notes for the new glTF architecture:
  - Those using `ModelExperimental.fromGltf()` should now use `Model.fromGltf()`.
  - The `enableModelExperimental` flag was removed, as tilesets and entities always use the new architecture.
  - The new implementation of `Model` uses the same public API as before, so no other changes are necessary.
- Models and tilesets that use the `CESIUM_primitive_outline` extension can now toggle outlines at runtime with the `showOutline` property. Furthermore, the color of the outlines can now be controlled by the `outlineColor` property. [#10506](https://github.com/CesiumGS/cesium/pull/10506)
- Improved rendering of ground and sky atmosphere. [#10063](https://github.com/CesiumGS/cesium/pull/10063)

#### Fixes

- Changes the default `RequestScheduler.maximumRequestsPerServer` from 6 to 18. This should improve performance on HTTP/2 servers and above. [#11627](https://github.com/CesiumGS/cesium/issues/11627)
- Fixed Repeated URI parsing slows 3D Tiles performance [#11197](https://github.com/CesiumGS/cesium/issues/11197). Together with [#11211](https://github.com/CesiumGS/cesium/pull/11211), this can reduce tile parsing time by as much as 25% on large tilesets
- Fixed atmosphere rendering performance issue. [10510](https://github.com/CesiumGS/cesium/issues/10510)

**Comment by mwu2018** [comment]
@nf-s 
There is no `main` branch in terriajs-cesium repo https://github.com/TerriaJS/cesium/. I can see two major branches
- terriajs
- terriajs-new

`terriajs` currently uses `v6.2.0` of `terriajs-cesium`. What is the procedure of releasing new version of `terriajs-cesium`? 

Since we are testing the new releases, should we make them alpha versions?
