### ISSUE TITLE
custom styling of WFS

### ISSUE THREAD

**Issue by uwer** [TerriaJS/terriajs#7038]
Hi guys
is it possible to customise styling of point layer via WFS beyond the simple maki icons? I am in particular thinking of clustering points and adjusting size based on attribute - client side.

**Comment by nf-s** [comment]
Hi @uwer 

I am going to transfer this issue to the TerriaJS repository and convert it into a discussion post.

We currently do not have the ability to cluster points

- Please see https://github.com/TerriaJS/terriajs/issues/695

We do have the ability to adjust size based on attributes client-side. You can set these attributes in the "Edit Style" workflow

- Load WFS layer
- Open options menu and select "Edit Style"
- <img width="427" alt="image" src="https://github.com/TerriaJS/TerriaMap/assets/6187649/b47a5c1e-1f8e-4b4a-a30a-f0b0c25ddad6">
- Select "Point/Marker style" in the "Symbology" drop-down
- <img width="351" alt="image" src="https://github.com/TerriaJS/TerriaMap/assets/6187649/ea8f1131-583a-4355-ba3b-4172a09ff105">
- Then you can specify marker height/width - this can also be based on an attribute - to do this select a "Variable"
- You can also specify point size for numeric attributes - to do this select "Point size" in the "Symbology" drop-down
- <img width="358" alt="image" src="https://github.com/TerriaJS/TerriaMap/assets/6187649/d6f8c283-1d8e-424a-88d4-35d4239ccff1">
