### ISSUE TITLE
ArcGisMapServerCatalogItem should not use "pre-cached tiles" if a layer ID is specified in URL path.

### ISSUE THREAD

**Issue by mwu2018** [TerriaJS/terriajs#7041]
Upload data to http://ci.terria.io/main from URL https://portal.spatial.nsw.gov.au/server/rest/services/NSW_Administrative_Boundaries_Theme/MapServer/8 will result in error. 

***Note***
The logic is wrong at https://github.com/TerriaJS/terriajs/blob/b1b8753dac2b4fdfa4ef5fbe73bf4af6f0b8fb76/lib/Models/Catalog/Esri/ArcGisMapServerCatalogItem.ts#L588

It should be something like

```
  usePreCachedTilesIfAvailable:
    !this.layers &&
    ( this.layersArray.length === 0 ||
      setsAreEqual(
        this.layersArray.map((l) => l.id),
        stratum.allLayers.map((l) => l.id)
      )
    ),
```

**Comment by nf-s** [comment]
`this.layersArray.length === 0` _should_ be equivalent to `!this.layers`

**Comment by mwu2018** [comment]
this.layersArray does not include layer specified in the path. It only looks at "layers" property. See https://github.com/TerriaJS/terriajs/blob/b1b8753dac2b4fdfa4ef5fbe73bf4af6f0b8fb76/lib/Models/Catalog/Esri/ArcGisMapServerCatalogItem.ts#L625

**Comment by mwu2018** [comment]
Ok, I might be wrong. Need to check further.
