### ISSUE TITLE
Support ESRI MapServer catalogs

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#705]
We support MapServer layers and layer groups, but not full catalogs. APHCRI has a lot of great datasets accessible at this URL: http://graphc.aphcri.anu.edu.au/arcgis/rest (and they'll be adding more)

(Already discussed with Kevin, I'll hopefully have a crack at it in the next few weeks.)

**Comment by kring** [comment]
@stevage I'm going to grab this one since it would be good to have it for a meeting Peter is having today.
