### ISSUE TITLE
Support Socrata

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#708]
Requested for [City of Melbourne](http://data.melbourne.vic.gov.au) and [ACT](http://data.act.gov.au).

**Comment by stevage** [comment]
Now, a couple of issues here. Geospatial support in the versions of Socrata running those two platforms is poor. They don't have GeoJSON enabled:
- https://www.data.act.gov.au/resource/22rs-ycdh.geojson
- https://data.melbourne.vic.gov.au/resource/tdvh-n9dv.geojson

You can get a listing of all datasets like this:  https://data.melbourne.vic.gov.au/data.json

Unfortunately the `?type=maps` parameter seems to be ignored. (It works for HTML view).

From that listing you can access the raw data, but the columns are inconsistent. For example [this one](https://data.melbourne.vic.gov.au/api/views/a945-pqqr/rows.csv?accessType=DOWNLOAD) has "Latitude - processed", and "Geocoded" columns (`(-37.5, 144.5)`). [This one](https://data.melbourne.vic.gov.au/api/views/axts-5eu4/rows.csv?accessType=DOWNLOAD) has "Latitude" and "GeoCode"

Line and polygon maps generally have a KMZ download, identifiable by `mediatype: application/vnd.google-earth.kmz`. [Example](https://data.melbourne.vic.gov.au/api/geospatial/6yxs-smdz?method=export&format=KMZ). Zipped shapefile [also available](https://data.melbourne.vic.gov.au/api/geospatial/6yxs-smdz?method=export&format=Shapefile).

**Comment by kgrochow** [comment]
You should talk with Pia and/or Alex at data.gov.au about it if you haven't. They had tried to import from socrata to migrate users and found it unworkable in the end as I remember.  They - or Alex with Pia on secondment - may remember more of the details.

**Comment by stevage** [comment]
@maxious, any comments?

(man Github is great like that...)

**Comment by maxious** [comment]
Socrata are on github too ;) It would be nice if the data catalogue APIs were better documented especially around filtering and pagination. It would be even better if www.opendatanetwork.com had an API to get all results by jurisdiction (GovPond for Socrata)
I don't know any more about it other than Vizicities asked the same question about how to get just spatial data as well so there's demand.

**Comment by stevage** [comment]
Ok, spoke to Socrata this morning. Where we got to:
- confirmed that there's no API way to find spatial datasets
- they will work with us to get Socrata users to tag spatial datasets appropriately, so at least we can filter that way
- it's also possible to iterate over every dataset, looking for columns where `dataTypeName` = `location`. For instance: https://data.melbourne.vic.gov.au/api/views/axts-5eu4.json So I may attempt to script something, but it would need to be a server side process, so doesn't fit well into the Terria model.

There's also this, but not sure if relevant: http://labs.socrata.com/docs/search.html

Seems to allow meta searching across (US?) Socrata instances.

**Comment by stevage** [comment]
Ah, even better, here's the JSON catalogue: https://data.melbourne.vic.gov.au/api/search/views

That should be enough - look for datasets with `"displayType" : "map"`,

**Comment by maxious** [comment]
https://data.melbourne.vic.gov.au/api/search/views?limitTo=MAPS :)

**Comment by stevage** [comment]
Awesome, nice find!

**Comment by stevage** [comment]
Done: https://github.com/TerriaJS/terriajs/commit/21f7a09b26c9736482237a45f7bfa2ebe1b85e72
