### ISSUE TITLE
Importing "inobounce" in a node.js build of terriajs code causes `ReferenceError: document is not defined`

### ISSUE THREAD

**Issue by tephenavies** [TerriaJS/terriajs#7128]
We should find a new way of using `"inobounce"` that silently skips initialising when `document` is unavailable.

### Problem

[StandardUserInterface.tsx](https://github.com/TerriaJS/terriajs/blob/main/lib/ReactViews/StandardUserInterface/StandardUserInterface.tsx) imports `"inobounce"`, which calls a browser API `document.createElement` as a side-effect. And since `StandardUserInterface/index.ts` imports `StandardUserInterface/StandardUserInterface.tsx`, importing either of these when running in node.js causes a problem because `document` doesn't exist.

All our ts/tsx/js/jsx files should be able to be imported in a node.js build of terriajs code. 

_Originally posted by @steve9164 in https://github.com/TerriaJS/terriajs/issues/7123#issuecomment-2089665637_

**Comment by pjonsson** [comment]
Can you use dynamic imports (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) from ES2020?

**Comment by tephenavies** [comment]
I went down a bit of a rabbit hole to see how many of our jsx/tsx files fail to import in node.js, and I've changed my mind. I don't think it makes sense to make all of our jsx/tsx files compatible with a node.js environment. We should instead endeavour to separate imports of jsx/tsx from models. The model layer of TerriaJS should be able to run, but you should expect importin and using React components from jsx/tsx files to fail if running in an environment without `window` and `document`. Thus I'm closing this issue
