### ISSUE TITLE
Filter on multiple properties

### ISSUE THREAD

**Issue by mwu2018** [TerriaJS/terriajs#7165]
If it is a csv dataset. the code can render the data with automatically generated colour shades based on a selected data property. E.g. The following map shows wheat's `Yield Mean t/Ha` in different areas.
<img width="1686" alt="Screenshot 2024-05-27 at 2 13 42 PM" src="https://github.com/TerriaJS/terriajs/assets/41275384/9b0ccb2d-655f-4c60-9e47-b0be58a69fa8">

Sometimes it is desirable to further filter data based on some criteria, e.g., show wheat's `Yield Mean t/Ha` where `Poe 3 T/Ha > 0.2`, as shown below.

<img width="1686" alt="Screenshot 2024-05-27 at 1 32 11 PM" src="https://github.com/TerriaJS/terriajs/assets/41275384/28aae230-04af-46b1-91fd-a03468a78671">

**Comment by ljowen** [comment]
Wanted for AgriTwin

**Comment by nf-s** [comment]
There are a few existing tickets related to this

- https://github.com/TerriaJS/terriajs/issues/1407
- https://github.com/TerriaJS/terriajs/issues/1196
- https://github.com/TerriaJS/terriajs/issues/6617

There is also an experimental PR that adds this feature

- https://github.com/TerriaJS/terriajs/pull/6421

**Comment by nf-s** [comment]
I'm going to close this as duplicate, we can re-open if you think it needs it's own ticket
