### ISSUE TITLE
Disabling or removing the HelpPanel/MenuBar

### ISSUE THREAD

**Issue by Lazouoi** [TerriaJS/terriajs#7180]
After spending a lot of time I tried to remove the  Help menu (need to substitute for something else) using different tricks but none worked well. For example: 
1. Disabling the help button in the menu bar (didn't work)
2. Commenting last line of "HelpPanel". (Didn't work and the build failed).
3. Commenting in the StandUserUi (same results to 2)

Is it really possible to remove this help menu?

**Comment by na9da** [comment]
Hi @Lazouoi, 

You can hide elements using the `elements` setting in the init file. 

Here's an [example configuration](https://gist.github.com/na9da/646ef6ee0147faa7f9604ab88e576622?short_path=89ef407#file-hide-elements-json-L8-L18), and you can [see it in action here](http://ci.terria.io/main/#clean&https://gist.githubusercontent.com/na9da/646ef6ee0147faa7f9604ab88e576622/raw/16e2983189fd015f37b81d83d6a7cfa1a45fd96a/hide-elements.json):
