### ISSUE TITLE
Esri MapServer that works from an init file but not when added using Add Data

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#721]
When trying to add the following Esri MapServer using the Add Data (with the type set to Auto-detect or as Esri MapServer) the layer is detected, but turning it on does nothing:

http://www.actmapi.act.gov.au/actmapi/rest/services/mga/windlab/MapServer

However, if you put the server into a JSON init file then it all works fine:

```
{
  "catalog": [
    {
      "name": "ACT Wind",
      "type": "group",
      "items": [
        {
          "name": "ACT Wind",
          "description": "ACT Mapi Windlab 100m resolution average wind at 80m above ground.",
          "dataCustodian": "ACT Mapi",
          "type": "esri-mapServer",
          "url": "http://www.actmapi.act.gov.au/actmapi/rest/services/mga/windlab/MapServer",
          "rectangle": [
            "148.7",
            "-36.0",
            "149.4",
            "-35.1"
          ]
        }
      ]
    }
  ]
}
```

Turns out, it only works in the init file if the "rectangle" array is specified - take it out and the init file no longer works either.

**Comment by meh9** [comment]
Just to clarify, the Add Data seems to work fine when using any random GA MapServer URL, seems specific to just the ACT server.

**Comment by kring** [comment]
This MapServer has two layers.  One is a "Feature Layer" that is apparently blank.  That's the only one Add Data was showing in the catalog.  The other is a "Mosaic Layer" that actually has the data.  I modified TerriaJS in the pull request above to add the Mosaic Layer to the catalog, too.

Another problem with this dataset is that its extent is specified in an unusual projection.  So TerriaJS doesn't know how to zoom to it.  I didn't fix this part.  If it's important, please write a separate issue to support arbitrary projections for MapServer extents.
