### ISSUE TITLE
Configuration Options  "disableSplitter,  disablePedestrianMode, disableMyLocation" Not Working in Latest Build

### ISSUE THREAD

**Issue by luca-moscatelli** [TerriaJS/terriajs#7358]
## Description
The following configuration options are not working as expected in the latest build of TerriaMap (`ghcr.io/terriajs/terriamap:latest`):

1. **`disableSplitter`**: Despite being set to `true`, the splitter is still visible and functional in the map interface.
2. **`disablePedestrianMode`**: Setting this to `false` does not enable pedestrian mode, nor does changing it to `true` disable the feature as expected.
3. **`disableMyLocation`**: Even when set to `true`, the "My Location" feature remains accessible in the user interface.

## Steps to Reproduce
1. Pull the latest version of TerriaMap:
   ```
   docker pull ghcr.io/terriajs/terriamap:latest
   ```
2. Set the following configuration in `config.json`:
   ```json
   parameters{
     "disableSplitter": true,
     "disablePedestrianMode": true,
     "disableMyLocation": true,
     "otherThings":{}
   }
   ```
3. Restart the TerriaMap application and observe the interface.

## Expected Behavior
- When `disableSplitter` is set to `true`, the splitter should be hidden or disabled.
- When `disablePedestrianMode` is set to `false`, pedestrian mode should be enabled.
- When `disableMyLocation` is set to `true`, the "My Location" button should be hidden or non-functional.

## Actual Behavior
- The splitter remains visible and functional.
- Pedestrian mode does not toggle as expected.
- The "My Location" feature is still accessible.

## Environment
- **TerriaMap Version**: `ghcr.io/terriajs/terriamap:latest`

Thank you for looking into this issue!

**Comment by zoran995** [comment]
Hi @luca-moscatelli, thanks for raising the issue. Those config options have not been relevant for quite some time; we just forgot to update the configuration definition and docs. There is an option to use `elements`, which is not documented anywhere.
I have created a new ticket to handle config and documentation update #7377. In the meantime, you can find more details in #5131.
