### ISSUE TITLE
Add CSW support

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#777]
We have a requirement for handling CSW catalog services in AREMI.

A live CSW 2.0.2 server is available here:

http://www.marlin.csiro.au/geonetwork/srv/eng/csw?&request=GetCapabilities&service=CSW&version=2.0.2

To run a local service we can use this:

http://sourceforge.net/projects/geonetwork/files/GeoNetwork_opensource/v2.10.4/

**Comment by rsignell-usgs** [comment]
CSW support would be great.   We are big fans of pycsw (http://pycsw.org/).

**Comment by rsignell-usgs** [comment]
Perhaps this JS library could be used to provide CSW query ability?
https://github.com/OSGeo/ows.js

**Comment by kring** [comment]
Thanks @rsignell-usgs, I'll take a look.  I've added experimental CSW support to the `csw` branch if you want to check it out in the meantime.  Do you guys have a public CSW server I can test against?

**Comment by rsignell-usgs** [comment]
https://github.com/rsignell-usgs/notebook/blob/master/CSW/CSW%20Testing%20NGDC%20Geoportal.ipynb

**Comment by kring** [comment]
Thanks @rsignell-usgs.  I took a look at these, but didn't have much success.

Initially I was accessing `GetRecords` via an HTTP `GET` and a `CQL_TEXT` query.  But it seems Esri and MapInfo servers don't support `GET` access to `GetRecords` (only the `POST` mechanism is required by the standard).  So I switched to using `POST`.  My posted query, intended to find all WMS services, looks like this:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<csw:GetRecords xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" version="2.0.2" service="CSW" resultType="results" startPosition="1" maxRecords="100">
    <csw:Query typeNames="csw:Record" xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml">
        <csw:ElementSetName>full</csw:ElementSetName>
        <csw:Constraint version="1.1.0">
            <ogc:Filter>
                <ogc:PropertyIsEqualTo>
                    <ogc:PropertyName>Format</ogc:PropertyName>
                    <ogc:Literal>OGC:WMS</ogc:Literal>
                </ogc:PropertyIsEqualTo>
            </ogc:Filter>
        </csw:Constraint>
    </csw:Query>
</csw:GetRecords>
```

This works on the marlin server at the top of this issue (though the server is _really_ slow to return responses), but it doesn't work on any of the servers on your linked page.  Here are the problems:
- `http://www.ngdc.noaa.gov/geoportal/csw`: successful request, no results.
- `http://data.nodc.noaa.gov/geoportal/csw`: successful request, no results.
- `http://geodiscover.cgdi.ca/wes/serviceManagerCSW/csw`: successful request, no results.
- `http://cida.usgs.gov/gdp/geonetwork/srv/en/csw`: successful request, no results.
- `http://cmgds.marine.usgs.gov/geonetwork/srv/en/csw`: responds with a 404 when POSTing the XML above.  KVP GET requests seem ok, but no results just like the servers above.  Possibly the server is (mistakenly?) configured to reject POSTs?
- `http://geoport.whoi.edu/gi-cat/services/cswiso`: times out after several minutes

For the ones without results, it's likely that I'm querying incorrectly for WMS layers, or that I should be looking for other types of data as well.  I tried browsing the catalogs via their web interfaces to deduce what data I could reasonably pull from them, but it wasn't at all obvious to me.  Any ideas?

I'd like to have your insight into what you would like TerriaJS to display when querying from these catalogs.  Then maybe I can figure out how to make that happen. :)

**Comment by rsignell-usgs** [comment]
@kring, grrr...   looks like CSW doesn't support querying service endpoints very well.   The problem seems to be that there is not a standard way to populate the data in the queryable `apiso:ServiceType`.   As described to me this morning by pycsw developer @tomkralidis, `apiso:ServiceType` only gets the value `OGC:WMS` if it's harvested from a WMS service.   Whereas our data is always loaded from WAFs of ISO metadata, which contain WMS as well as other links.  The other problem is that pyCSW is only assigning a single `ServiceType`.     We obviously need this to be a list. 

I never realized we had this weakness because our workflows with CSW have been:
- query CSW to find metadata records based on geospatial, temporal and keyword (or freetext) search
- extract WMS and other service endpoints from the returned metadata records. 

@tomkralidis is thinking about how to handle this, but for now, we can't do a query on a CSW endpoint and reliably return the WMS (or other) endpoints.  :crying_cat_face:

**Comment by kring** [comment]
Ok, thanks for looking into it.  It looks like even the marlin server above, which I can successfully query for `dc:format=OGC:WMS` has no records for `apiso:ServiceType=OGC:WMS`.  My understanding of CSW is admittedly naive, but it seems like CSW defines a method for querying metadata while imposing little to no guidance on what the content of the metadata should actually be.  So I think that means a TerriaJS CSW capability needs to be quite flexible.  The person defining the CSW catalog in the init file needs to be able to specify the query to use as well as the mapping of CSW metadata to the various bits that TerriaJS cares about.  Does that sound right to you?

**Comment by rsignell-usgs** [comment]
Well, unfortunately, right now, I guess that's pretty much true.   And there hasn't been that much use of CSW across different communities to develop best common practices, but with pycsw being used by more folks (http://pycsw.org/community/) and more CSW use in general, I hope we (the community) can change that.   

Some steps we've made in these directions:
1. Agreeing on a common way to call various services:  https://github.com/OSGeo/Cat-Interop/blob/master/LinkPropertyLookupTable.csv
2. Agreeing on a common way to specify a bounding box query that works on CSW services on geoportal, gi-cat and pycsw:

```
<ogc:BBOX>
   <ogc:PropertyName>ows:BoundingBox</ogc:PropertyName>
   <gml:Envelope srsName="urn:ogc:def:crs:OGC:1.3:CRS84">
     <gml:lowerCorner> -158.4 20.7</gml:lowerCorner>
     <gml:upperCorner> -157.2 21.6</gml:upperCorner>
   </gml:Envelope>
</ogc:BBOX>
```

See discussion of the bounding_box issue here: https://groups.google.com/forum/#!topic/ioos_tech/FFZ_IoXbdUk.

@tomkralidis, anything to add here?

**Comment by tomkralidis** [comment]
@rsignell-usgs good points.  There's also a gap in how a catalogue ingests a given metadata record and how certain things are exposed and made queryable.  Perhaps we can continue the above in pursuit of a best practice over at https://github.com/OSGeo/Cat-Interop ?

**Comment by kring** [comment]
Thanks for the insights, guys!  I'll keep an eye on that Cat-Interop repo.  We'll likely keep our CSW support simple for now (see the pull request referenced above) and extend it incrementally as users have a specific need.
