### ISSUE TITLE
No download link for locally hosted files?

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#783]
Locally hosted files (at least CZML?) don't seem to generate a download link:

![screenshot 2015-06-25 10 00 54](https://cloud.githubusercontent.com/assets/678344/8344178/2ab5b240-1b21-11e5-93f0-b43446b68211.png)

Adding the URL fragment to the base URL [works fine](http://nationalmap.gov.au/renewables/datasets/dance/DANCE-2012-AD.czml)

**Comment by hilarycinis** [comment]
IxD note: replicate any other download patterns for other file types

**Comment by stevage** [comment]
To reproduce:
1. http://nationalmap.gov.au#test
2. Select CZML files > Simple Test (CZML)
3. Click (i)

**Comment by chloeleichen** [comment]
You mean it should have a link like this? @stevage 
![sc](https://cloud.githubusercontent.com/assets/7508939/10298074/e070b490-6c25-11e5-9b9a-0cd2ef78c030.png)

**Comment by chloeleichen** [comment]
I see, you mean this one:
![dl](https://cloud.githubusercontent.com/assets/7508939/10298336/b92ee132-6c29-11e5-964e-bf8246b23c0a.png)

**Comment by chloeleichen** [comment]
This happens to not only locally hosted file, for example:
![screen shot 2015-10-06 at 4 08 10 pm](https://cloud.githubusercontent.com/assets/7508939/10300610/90abf6f8-6c44-11e5-9767-aee8c879bcfd.png)
I think this is because for some data type(e.g: CZML) , the dataUrl and dataUrlType has not been given a fallback when they don't have any value, so I set them to the url of the catalogue url if they dont have a dataUrl defined, and dataUrlType is set to 'direct':#954

**Comment by stevage** [comment]
Looks good. Doesn't work for GeoJSON yet? (eg, the GeoJSON files in the #test init file)

**Comment by chloeleichen** [comment]
it should work with geojson, let me check again

**Comment by stevage** [comment]
Ah, actually there's only one that doesn't work, the zipped airports.

**Comment by chloeleichen** [comment]
yeah I don't know why that dataset doesn't work, I can't select that dataset on my local at all. When i try to select it I get:
`An error occurred while attempting to convert this file to GeoJson. This may indicate that the file is invalid or that it is not supported by the AREMI conversion service. If you would like assistance or further information, please email us at aremi@nicta.com.au.`

**Comment by stevage** [comment]
I guess it requires the server-side conversion service to work. It worked fine for me locally, fwiw.

Anyway, looking at the code, it seems a bit repetitive to have the same `overrideProperty()` on every item, I wonder if there isn't a way we can have this on the base `catalogItem` class instead. I guess that can wait for a future refactor though.

**Comment by chloeleichen** [comment]
sure I can move them into catalogItem, thanks @stevage

**Comment by chloeleichen** [comment]
hi @stevage , I have moved the download dataurl to base class:  #954

**Comment by stevage** [comment]
Ok, great. I think I'll leave this one to @kring to merge, if that's ok - he's best to review architectural changes.

**Comment by kring** [comment]
Fixed by #954.
