### ISSUE TITLE
Documentation or tools for creating catalogs?

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#787]
I created a local catalog json with one dataset, and it worked fine. 
I then added another and broke it.    The offending catalog is here:
https://github.com/rsignell-usgs/map/blob/master/wwwroot/init/ww.json

How would I go about debugging the issues with this catalog? 

Is there any documentation or tools to help with getting the catalog syntax correct?

**Comment by meh9** [comment]
The problem is the trailing comma on the Bottom Temp "parameters" object - unfortunately JSON does not allow trailing commas.

**Comment by meh9** [comment]
One way to check that your JSON is valid is to the use `jq` command:

```
$ jq . ww.json 
parse error: Expected another key-value pair at line 26, column 17
```

Another good way would be to edit your JSON using a syntax highlighting editor like Sublime Text, in which case you would have seen something like this:

![screen shot 2015-06-26 at 8 44 02](https://cloud.githubusercontent.com/assets/5283003/8367234/926c6046-1bdf-11e5-9f7b-5310834ac85b.png)

**Comment by rsignell-usgs** [comment]
Grrr, rookie error!   Thanks @meh9 for showing me ideas to check for valid JSON.    I wasn't getting errors in notepad++, but I guess that's because you need a plugin that wasn't installed.

**Comment by rsignell-usgs** [comment]
I just realized that if I bring up the raw github content in Chrome (with the JSONView extension installed), it clearly shows me the error:
![2015-06-26_0714](https://cloud.githubusercontent.com/assets/1872600/8376265/1ac538e4-1bd3-11e5-97f3-1872eb9b2c93.png)

**Comment by stevage** [comment]
Oh, I didn't see this issue! 

I made a data source editor (soon to be renamed catalog editor):

terria.io/DataSourceEditor

Would love feedback, suggestions etc.

@rsignell-usgs @meh9

**Comment by meh9** [comment]
@stevage I use it a lot to make little snippets since I don't always remember what attributes are available for different elements.

At the moment I get a JSON error when loading the General Settings JSON:

```
There's a problem with your JSON code. 

[root] Object is missing the required property 'catalog'
```

The only other thing I'd say is that there doesn't seem to be a way to create a brand new catalog using the clicky tools, you have to load a General Settings first before any of the tools appear?

**Comment by stevage** [comment]
> At the moment I get a JSON error when loading the General Settings JSON:

Oh, didn't realise that. I think I can probably make `catalog` optional without causing any harm.

> The only other thing I'd say is that there doesn't seem to be a way to create a brand new catalog using the clicky tools, you have to load a General Settings first before any of the tools appear?

I should fix this. The workaround is to type a space somewhere in the JSON box, then click 'update'.

**Comment by stevage** [comment]
Fixed both those things.

**Comment by rsignell-usgs** [comment]
@stevage , I tried out the catalog editor on the [problematic catalog that started this issue](https://github.com/rsignell-usgs/map/blob/master/wwwroot/init/ww.json), and it correctly identified that I had an error in the JSON:
![7-31-2015 6-07-50 am](https://cloud.githubusercontent.com/assets/1872600/9005262/a9d03510-374a-11e5-934a-7a1165db35b1.png)

Would it also be possible to have it identify the line number, as the JSONView extension for Chrome does?  ![2015-06-26_0714](https://cloud.githubusercontent.com/assets/1872600/8376265/1ac538e4-1bd3-11e5-97f3-1872eb9b2c93.png)

**Comment by stevage** [comment]
Hmm, the tool really expects you to have valid JSON as a starting point. There are other tools that can help you get to that point (as you obviously know), so not really a high priority. Pull request welcome though :)
