### ISSUE TITLE
Allow lat-lon CSVs to be shown with no data variable (all points the same color)

### ISSUE THREAD

**Issue by bsimyo** [TerriaJS/terriajs#791]
I'm putting this in for CSV files that have lat/lons but it probably applies more broadly. At the moment, it seems that there needs to be at least one variable checked.  However, for some csvs, it only makes sense to show points for the lat/lons and not use different colours for different values in the value range. At the moment, you can't do this from the UI.  It would be good to be able to have all checked off (actually this is probably a good default for CSVs which have not had an initial set of variable states specified)
Eg see csv file of bus stops at http://data.gov.au/dataset/bus-stops-brisbane-city-council

**Comment by kgrochow** [comment]
Are you still liking this approach better?  As per the discussion today, I'm coming around to this idea and now is a reasonable time to look into it.

**Comment by stevage** [comment]
I think this is still an issue. @RacingTadpole is there any difficulty in doing this?
