### ISSUE TITLE
Add OGC WPS support

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#816]
We have a project that wants to do processing using WPS, so some form of support for it in Terria would be very useful to us.

This is also related to adding CSW support, issue #777, as that would be the plan for reading the results of the processing back.

**Comment by metanomy** [comment]
We officially have a use case for WPS now, so unless there is current work underway, do you mind if I add a bounty to this?

**Comment by meh9** [comment]
@metanomy, so there is a bit of work going on that may lead to this.

I know @kring is working on something that may eventually turn into WPS.

There is also a fork, https://github.com/awavea/terriajs, that may get WPS first and that may eventually get added to TerriaJS.

I'm not very up to date on how these efforts are going though - a bounty may speed things up!

**Comment by metanomy** [comment]
Bounty added: https://www.bountysource.com/issues/23901250-add-ogc-wps-support

**Comment by kring** [comment]
This was added months ago.  It went into the `newUI` branch without an explicit pull request.
