### ISSUE TITLE
Use digital signatures instead of an explicit proxy whitelist

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs#821]
The most frustrating aspect of trying to add new datasets to a TerriaJS-based app is that it never works the first time.  Inevitably, the server doesn't support CORS and it's not in the proxy whitelist.  Since we can't update the whitelist without redeploying the software, it's not possible to even try out the new dataset with the production application.

So this is an idea for avoiding that problem, while still ensuring that we only proxy for approved servers.

First, we remove the `proxyDomains` list from `config.json`.  Instead, any init file can specify a list of domains to be proxied along with a digital signature that proves authority to proxy to that domain.  When making proxy requests, the client application includes the digital signature either in the URL or in the HTTP headers.  The node-based proxy server validates the signature using a public key (which need not be kept secure; it can even be in the open source code) and refuses to proxy requests with an invalid signature.  To avoid validating a signature on each request (which could get slightly costly), the server can maintain a whitelist of domain/signature pairs that it has already validated and wave those through without revalidating.

This way, anyone with proper authority (that is, access to the private key used to sign domains) can create an init file with new datasets at new domains and the proxy will happily forward requests for them.

Eventually domain signing could be integrated into Steve's data source editing tool, though it would presumably require that the tool itself have a login of some sort.

**Comment by nahidakbar** [comment]
Is it possible to make this proxy into a separate component instead which supports proper CORS implementation? Preferably managed as a separate entity common for all Terria derivations.
May reduce support for some [old browsers](http://caniuse.com/#feat=cors).

**Comment by kring** [comment]
Yes, we've talked a lot about making the proxy (also the converter and projection lookup services) separate from any application.  Until we drop support for IE9, though, we'll need to continue deploying the proxy on the same domain as the app.

**Comment by stevage** [comment]
Hooray, we finally did do that separation: https://github.com/terriajs/terriajs-server

Think this is still worth pursuing, @kring ?

**Comment by kring** [comment]
Yes, I still think this is quite valuable.  Once we're able to update the catalog outside of software releases, the next thing we'll run into is that we'll want to add a new server to the proxy whitelist outside software releases as well.  This issue describes a secure way we can allow new hostnames to be proxied without actually needing to update the whitelist on the deployed server!

**Comment by kring** [comment]
I still think this is cool, but probably not happening anytime soon.  Closing.
