### ISSUE TITLE
Low-bandwidth mode

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#827]
Something that got mentioned the other day - it'd be good to have a URL flag that would minimise bandwidth. Useful for developing while tethered to mobile data. Maybe even just disabling terrain, switching to 2D and using a low-bandwidth basemap. 

Hmm, might be as simple as having a flag like "#lowbandwidth" translate to: 

```
#start=%7B%22version%22%3A%220.0.04%22%2C%22initSources%22%3A%5B%22init%2Fnm.json%22%2C%7B%22initialCamera%22%3A%7B%22west%22%3A85.60546875%2C%22south%22%3A-52.26815737376816%2C%22east%22%3A181.40625%2C%22north%22%3A8.928487062665504%7D%2C%22homeCamera%22%3A%7B%22west%22%3A109%2C%22south%22%3A-45%2C%22east%22%3A158%2C%22north%22%3A-8%7D%2C%22baseMapName%22%3A%22Bing%20Maps%20Roads%22%2C%22viewerMode%22%3A%222d%22%7D%5D%7D
```

**Comment by kgrochow** [comment]
Starting with #map=2d should cove a lot of this for now - leaflet, no terrain, no rendering loop

**Comment by nahidakbar** [comment]
For saving bandwidth / faster loading, GV also uses version controlled offline caching for static content and indexedDB caching for visualisation data. Few other things that could be looked at.

**Comment by stevage** [comment]
Thanks @kgrochow, that's pretty much perfect. @nahidakbar, what's GV?

**Comment by nahidakbar** [comment]
@stevage http://groundwater.research.nicta.com.au/

**Comment by kgrochow** [comment]
Kevin just also fixed a bug I probably introduced that was keeping the render loop from stopping.  Doing a pull from master should make 3D much more reasonable on a laptop again.
