### ISSUE TITLE
Rendering issues when using many layers

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#850]
When you enable a bunch of layers in Google Chrome on a 13" retina Macbook Pro (integrated GPU) you get weird rendering issues:

<img width="1280" alt="screen shot 2015-07-20 at 16 48 58" src="https://cloud.githubusercontent.com/assets/5283003/8771083/cfdc2898-2eff-11e5-83d7-3c0ec4b144d6.png">

Zooming in or out will change the size and location of the dark bars, but they will always happen. Turning just one layer off makes them go away, turning more on will will not change the bars except make them darker.

**Comment by philipgrimmett** [comment]
I get the same thing (also on a 13" Macbook Retina Pro), but pretty quickly get this message:

<img width="696" alt="screenshot 2015-07-20 18 20 39" src="https://cloud.githubusercontent.com/assets/5292858/8772120/718e856c-2f0c-11e5-9ce0-a9c5835fc572.png">

..before NM turns of the eighth/top data set

**Comment by kring** [comment]
I don't see this, even on my laptop with an older integrated GPU (Intel HD Graphics 4600), and even when enabling far more layers than in the screenshot.  I'm inclined to blame a GPU driver bug.

Can one of you guys go to www.webglreport.com and paste a screen grab in here?  Just to see if there's anything particularly quirky about that GPU.

**Comment by meh9** [comment]
<img width="1037" alt="screen shot 2015-07-23 at 15 16 07" src="https://cloud.githubusercontent.com/assets/5283003/8843581/cc6cc208-314d-11e5-925c-c76d4d0c2f2f.png">

**Comment by meh9** [comment]
I'm also having some other issues with disappearing CZML layers, that Alex does not on his Retina 15".

**Comment by kring** [comment]
Thanks.  Nothing suspicious there, unfortunately.  I'll probably need to borrow someone's machine for a day to investigate further.

**Comment by kring** [comment]
By any chance, does the problem go away if your browser window is small, like say less than 1/4 of your screen?  I'm just trying to rule out running out of GPU memory.

**Comment by meh9** [comment]
Unfortunately it does not go away, so it appears it's not that simple.
