### ISSUE TITLE
Catalogue API

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#886]
Currently, the full catalogue is constructed in the browser by querying all catalogue groups (CKAN, WMS, Socrata...) when searching. This has two big downsides:
1. It's very slow. (Something like 30 seconds for all data providers to complete)
2. Because there is no server API, there is no way for anyone else to build a tool off our catalogue.

A solution to these two problems would be to run the catalogue (or at least an index of the catalogue) on a server, updating it from time to time (hourly?), and exposing an API, which Terria would call.

A couple of very different approaches:
1. A lightweight, standalone nodeJS app which uses the TerriaJS catalogue logic (and a local catalog .json file) to construct the catalogue and answer queries by API (eg, Express)
2. Scrap the whole concept of our own catalogue and run a CKAN instance, replacing our existing CatalogItem types with CKAN connectors (including custom development...)
3. Some other tool?

**Comment by bsimyo** [comment]
Keith did a version of 2 a while back and had a working prototype but we decided to stick with the catalogue file approach just for now to keep things simple.  I think we should go with 2.

**Comment by JJediny** [comment]
+1 for 2

**Comment by stevage** [comment]
Ok, I'm going to do some investigation into various options here. @kring suggested a few goals:
1. faster and/or more thorough search, 
2. detecting datasets being down, temporarily removing them and informing the custodian, 
3. providing an API to let others query the NM catalog programmatically?, 
4. detecting changes in metadata and notifying someone, e.g. the description coming from this WMS server just changed. (so perhaps we don't need to override it in the init file)

And of course it has to do the things that our init files already do:

a. Provide all the metadata that TerriaJS wants
b. Allow unlimited depth of hierarchy
c. Allow explicit orderings to be provided

I have some doubts about a CKAN approach:
- it means we need to run a CKAN for every big project, with all the attendant administration, upgrades etc
- the configuration and deployment of it is likely to be messy, and to involve various plugins in various places. We've got to a point where deploying Terria Map is very easy, but this is going the other way
- it's Python. So Terria would become a mix of JS and Python plugins, two different dependency systems etc.
- a lot of the code in the CKAN plugins is essentially going to duplicate TerriaJS code, unless we're making some drastic change and ditching all the catalog items from TerriaJS somehow.
- it's still not obvious to me how CKAN is even an answer. Out of the box it doesn't meet any of the goals. We would need to develop plugins that do the equivalent of so many of our catalog types. Eg, a plugin to connect to a WMS server and create resources for each of the layers, so that they can be searched through the CKAN API.

So for those reasons I'll start looking at a Node approach first. The major difficulty there is trying to get TerriaJS modules to run in Node. We could bundle the whole thing inside PhantomJS but I'll see if we can do it more cleanly first.

**Comment by meh9** [comment]
Re CKAN, from talking to @peterhassall it is clear that it is quite difficult to run CKAN in production with any kind of guarantee of level of service.

**Comment by stevage** [comment]
Yeah. And Renee had a lot of difficulty getting it set up.

Adding another goal of a catalogue server here:

5) Pre-canned dataset image previews

**Comment by kring** [comment]
I think the path forward now is to make Magda (optionally) the basis for the TerriaJS catalog.  So I'm closing this.
