### ISSUE TITLE
`getFeatureInfoFormats` type `plain` breaks `wms-getCapabilities` services

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#895]
I have a `wms-getCapabilities` service group that supports only two `GetFeatureInfo` formats:

```
<GetFeatureInfo>
    <Format>text/plain</Format>
    <Format>application/vnd.ogc.gml</Format>
```

The default if you don't specify anything is the GML format, which is less useful in the info popup than the `text/plain` format. (We should add GML support, or better yet implement info box templating: #496)

However, when you do specify a format for the group in the Terria init file, then when you try to expand the group to see the layers Terria instead throws an error:

```
Group is not available

An error occurred while invoking GetCapabilities on the WMS server.
...
```

With a bit of testing I've found that it will always break for all `wms-getCapabilities` services when you specify `plain` for `getFeatureInfoFormats`.

Example:

```
        {
          "name": "Test",
          "url": "http://geoserver.nationalmap.nicta.com.au/admin_bnds_abs/ows",
          "type": "wms-getCapabilities",
          "itemProperties": {
            "getFeatureInfoFormats": [
              {
                "type": "plain"
              }
            ]
          }
        }
```

If you change the `plain` to `html`, which is also supported for that service, then it works and you can expand the group.

So this will work, and will show HTML in the info popup:

```
            "getFeatureInfoFormats": [
              {
                "type": "html"
              }
            ]
```

**Comment by kring** [comment]
Right, `plain` isn't a valid type.  The valid values are `text`, `json`, `xml`, or `html`.  Try this:

``` json
        {
          "name": "Test",
          "url": "http://geoserver.nationalmap.nicta.com.au/admin_bnds_abs/ows",
          "type": "wms-getCapabilities",
          "itemProperties": {
            "getFeatureInfoFormats": [
              {
                "type": "text",
                "format": "text/plain"
              }
            ]
          }
        }
```

**Comment by meh9** [comment]
Right right, I discovered my mistake when I was debugging a different layer... I had assumed that because it was `html` for `text/html` it would be `plain` for `text/plain` and not `text`... :)

Will retest with `text`.

**Comment by meh9** [comment]
Yeah, this was just my confusion.
