### ISSUE TITLE
Not possible to specify `rectangle`s for Zoom To capability of `csv` type layers

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#898]
When specifying a CSV type layer it isn't possible to specify a `rectangle` list in the init files in order to get Zoom To capability. When the CSV data contains points, the rectangle is computed automatically and you can click Zoom To or the layer name to zoom to the bounds of that layer, but when the data contains areas (postcodes etc) then no bounds are computed, and any specified `rectangle` list is ignored.

**Comment by kring** [comment]
@steve9164 another one for you.

**Comment by kring** [comment]
Sorry, nevermind!  It's already closed. :)
