### ISSUE TITLE
Include active 'tab' state in share URL

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#902]
When using the Share feature to get an iframe for inclusion on other people web pages, users are requesting that we switch to the NowViewing tab automatically.

Since we have existing behaviour we might want to just make it possible to track the state of the tabs, so that we can view the state as it was when share was clicked.

**Comment by hilarycinis** [comment]
Thanks Mats -

Which users are requesting this?

Do we know in the current UI if they can navigate back to the catalogue effectively or are we just replacing one discoverability problem with another one?

**Comment by meh9** [comment]
The Clean Energy Council wants to put AREMI on their website, with certain enabled layers, basemap, and initial camera view, and has requested that the legend page be shown.

**Comment by hilarycinis** [comment]
oh cool, that sounds perfect.

**Comment by stevage** [comment]
Is there an argument that any shared URL should always default to the Now Viewing tab? Think about it: you're intentionally sharing _these datasets_ with someone, so they should see the legend etc as well. If you just wanted to share AREMI/NationalMap/... you wouldn't have gone to the share URL page...
