### ISSUE TITLE
Add support for WMS Dimensions other than time

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#911]
So, since WMS can have Dimensions other than time, we should support that.

The easiest way is probably to put a slider on the legend page for each extra Dimension, and then you can just slide it between the given 'indents' so select the layer property.

An example of a WMS service with extra Dimension parameters is the NCI Thredds server, this one (which is still in testing as far as I know) for showing Cyclone Risk over time. Here, the extra Dimension is given as `elevation`, which is used to actually select the number of years horizon (as far as I understand it) to display the layer for:

http://dapds00.nci.org.au/thredds/wms/fj6/TCRM/benchmark/hazard/hazard.nc?request=GetCapabilities&service=WMS

```
<Dimension name="elevation" units="years" default="2.0">
2.0,5.0,10.0,20.0,25.0,50.0,100.0,200.0,250.0,500.0,1000.0,2000.0,5000.0,10000.0
</Dimension>
```

To see it in action have a look at:

http://np.ga.gov.au/interactive-maps/#/theme/hazards/map/windhazards

**Comment by kring** [comment]
As part of #1512, we'll allow any WMS dimension to be selected in the UI, probably using a drop down list rather than a slider.  Closing this on the assumption that that will meet the needs described in this issue too, but re-open if I'm mistaken.
