### ISSUE TITLE
Do not hide magic DataTable/CSV columns from Feature Info popup

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#914]
There are some columns in DataTable/CSV's that have special meaning - `elevation`, `time`, `date`, etc, which are used to place a point in 3D space or for generating timeseries control. When matched, the data is then not shown in the Feature Info popup when you click on a feature. However, in most cases we actually want to see the values even if they are used for other purposes. For example, if we hide the elevation data, the user can only get a visualisation of that information back if they tilt their view, but if the user never does that the information has simply been lost to them.

**Comment by stevage** [comment]
Specifically, `VarType.ALT` and `VarType.TIME` should not be suppressed. It's probably still right to hide `LON` and `LAT`.

**Comment by stevage** [comment]
Oh, for some reason I misread this as talking about the variables shown in the "Now Viewing" tab. Probably ok to show everything in the popup.

**Comment by stevage** [comment]
Wait, I misunderstood this issue again. :) That commit doesn't address it.
