### ISSUE TITLE
"Zoom To" doesn't seem to work for this WMS service

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#916]
"Zoom To" doesn't seem to work for this WMS Service 
https://www.sciencebase.gov/catalogMaps/mapping/ows/519bee13e4b0e4e151f0232c?service=wms&request=getcapabilities&version=1.3.0

I added this to the nationalmap.gov.au via the "add data" button, and it displays fine, but clicking on "Zoom To" doesn't seem to do anything.

**Comment by kring** [comment]
@rsignell-usgs I tried it out and it seems that we can't zoom to the "(all)" layers, but the other two work fine.  TerriaJS creates the "(all)" layer when a parent layer has a `<Name>` element.  Now the weird thing is that on this server, there exist parent layers that have a name but do not have an `EX_Geographic_BoundingBox`.  The way I read the WMS 1.3.0 spec, this should not be allowed.  See section 7.2.4.6.6 where it says:

> Every named Layer shall have exactly one `<EX_GeographicBoundingBox>` element that is either stated explicitly or inherited from a parent Layer.

So I _think_ this is a case of a WMS server not corresponding to the WMS spec.  We could work around it, of course, probably by making parent layers without a bounding box create one from the union of the bounding boxes of all their child layers.

**Comment by rsignell-usgs** [comment]
@kring, okay, thanks for looking into this.   I'll notify the provider and see what they say.

**Comment by allenj** [comment]
@rsignell-usgs the sciencebase.gov WMS service should conform to the WMS 1.3.0 spec now.

**Comment by rsignell-usgs** [comment]
@allenj, yes, it's working!   Woohoo!
![2015-09-29_11-36-13](https://cloud.githubusercontent.com/assets/1872600/10169368/bdfc5c52-669e-11e5-963e-5395bd02fd80.png)

**Comment by kring** [comment]
Great, thanks!  Is it ok if we close this issue?

**Comment by rsignell-usgs** [comment]
Or perhaps I am capable of closing.  :flushed:
