### ISSUE TITLE
Highlight selected geometry

### ISSUE THREAD

**Issue by rtaib** [TerriaJS/terriajs#922]
It would be very useful to highlight "selected" (clicked or hovered) geometries for the purpose of data analysis. For example, hovering over a linestring would highlight it (e.g. bolder and/or different colour) over the other linestrings in the same layer. Same applies to other geometries. This is somehow related to #553 although within a layer instead of between layers.

@stevage and @axman6 told me they would also be happy to see that feature, but my first attempt at finding where/how this should be done in such a massive code base wasn't successful, so I'm resorting to posing an issue. I guess it should carry the UX/Design tag (@philipgrimmett or @hilarycinis ?).

**Comment by hilarycinis** [comment]
Thanks Ronnie, yep we've had similar idea and its definitely related to #553 but really it comes down to what is technically viable. Thanks for posting the issue.

**Comment by axman6** [comment]
This is something that's also been requested several times for AREMI and would help greatly with user confusion with some of our layers (particularly ones with overlapping polygons).

**Comment by rtaib** [comment]
Hi all,
Maybe this wasn't clear from my post: I am happy to give it a try, but I
need a bit of guidance to get started...
Cheers,
Ronnie

Alex Mason wrote on 18/09/2015 11:23 AM:

> This is something that's also been requested several times for AREMI and
> would help greatly with user confusion with some of our layers
> (particularly ones with overlapping polygons).

---

The information in this e-mail may be confidential and subject to legal professional privilege and/or copyright. National ICT Australia Limited accepts no liability for any damage caused by this email or its attachments.

**Comment by kring** [comment]
Current problems in the `highlightClickedFeatures` branch:
- [x] Does not work at all in 2D
- [x] Surface Water -> Watercourse Areas shows a GeoJSON error when clicking the map.
- [x] Surface Water -> Waterholes shows a GeoJSON error when clicking the map.
- [x] When multiple features are picked, switching to a different one and back causes the feature highlight to disappear.
- [x] Created `GeoJsonCatalogItem` shows up in the Now Viewing.
- [x] Doesn't work for actual vector data.
