### ISSUE TITLE
ESRI group type failing

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#926]
It can't handle this URL:

`https://eia-ms.esri.com/arcgis/rest/services/`

The generated URLs lack the layer name: `https://eia-ms.esri.com/arcgis/rest/services//export...`

**Comment by kring** [comment]
Looks like URLs with a service name starting with a number (e.g. https://eia-ms.esri.com/arcgis/rest/services/20141208StateEnergyProfilesMap/MapServer) are incorrectly matching the regex intended to detect URLs to specific dynamic layers within a MapServer.  You added that code didn't you?  Care to take a crack at the fix?

**Comment by stevage** [comment]
Oh. Thanks @RacingTadpole  :)
