### ISSUE TITLE
Add capabilities for interacting with dynamic WMS services like ncWMS and sci-wms

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#927]
There is a tremendous amount of met, ocean and hydro data on THREDDS Data Servers accessible via enhanced WMS services provided by ncWMS.   The THREDDS Data Server also includes a web client interacts with ncWMS called Godiva2, which allows a user to interactively explore model results and see dynamically generated maps of the results.     It allows for selection of specific variables in a model dataset, start/stop time for animation, and selection of vertical level, basically specifying all the parameters defined in the ncWMS query like 

http://geoport.whoi.edu/thredds/wms/coawst_4/use/fmrc/coawst_4_use_best.ncd?LAYERS=temp&ELEVATION=-0.03125&TIME=2015-09-02T00%3A00%3A00.000Z&TRANSPARENT=true&STYLES=boxfill%2Frainbow&CRS=EPSG%3A4326&COLORSCALERANGE=10%2C30&NUMCOLORBANDS=64&LOGSCALE=false&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&FORMAT=image%2Fpng&SRS=EPSG%3A4326&BBOX=-74.034469266079,39.001515676078,-69.427272277647,43.608712664509&WIDTH=256&HEIGHT=256

including the standard WMS GetMap query parameters plus these [ncWMS extensions](http://www.resc.rdg.ac.uk/trac/ncWMS/wiki/WmsExtensions)

The capabilities are demonstrated in my short (7 min) [YouTube demo of Godiva 2](https://www.youtube.com/watch?v=Mvy_mAvXVwk).

It would be super cool to create a sample client that had the functionality of Godiva2 to access ncWMS, but written using TerriaJS.    This would allow anyone to interactively explore data from any THREDDS data server, but with the flexibility and power of TerriaJS to integrate/overlay with other sources.

**Comment by rsignell-usgs** [comment]
@metanomy  hey, thanks!
https://www.bountysource.com/issues/26850201-build-a-godiva2-like-client-for-interacting-with-ncwms-services
I guess the concept here is that for folks who like contributing to open-source, it's like getting a free t-shirt, but instead it's $500, right?

**Comment by metanomy** [comment]
Correct. In theory, it's almost a kind of micro-task approach to Open source.

**Comment by ghost** [comment]
Hi. I just came across this project and I am interested in taking a stab at this issue! 
*_Question 1) Is this bounty still active and need working on? *_
*_Question 2) I need some pointers on how to get everything set up locally. My understanding is: *_

a) get the ncWMS server running on my computer. This also gives me a local version of the godiva2 client. 

Namely, this: 
https://github.com/Reading-eScience-Centre/edal-java.git

b) get the TerriaJS codebase on my computer. 

Namely, this:
https://github.com/TerriaJS/terriajs

*_Please let me know whatever I am missing here. *_
I am basically diving head first. Been doing some googling to understand the components in this system. 

_*_Question 3) The changes I need to make are in TerriaJS. *_

**Comment by metanomy** [comment]
@foreverundecided89: the bounty is still active!

If you have any experience with Docker, I recommend going down that path for both ncWMS and Terriajs:

ncWMS Docker: https://github.com/pacificclimate/docker-ncwms

TerriaJS Docker: https://github.com/NICTA/nationalmap/wiki/Developers'-Handbook

Don't hesitate to reach out to me for any help with the infrastructure.

@rsignell-usgs is the one who can guide you on the interaction types we want to add to terriajs

**Comment by rsignell-usgs** [comment]
@foreverundecided89, yes, this is still active.   I think the first thing you could try is seeing if you can add widgets to the TerriaJS "Now Viewing" panel to specify the min/max colorrange values to the WMS request. 

On a dataset like this water level forecast, for example:
http://comt.sura.org/proxy_3001/#https://raw.githubusercontent.com/rsignell-usgs/ehzrap/master/testing/nfwf.json
success would be if you could add min/max widgets like this:
![2016-02-02_13-53-23](https://cloud.githubusercontent.com/assets/1872600/12760538/d1f27dda-c9b4-11e5-9d0b-cb5da7e48fe3.jpg)
and the values from those widgets would go into the `colorscalerange` parameter on the WMS requests.   

Here's an example WMS request generated from TerriaJS:  
https://geoport.usgs.esipfed.org/wms/datasets/estofs?time=2015-11-20T01%3A00%3A00Z&colorscalerange=-3.00%2C3.0&numcontours=40&styles=filledcontours_jet&version=1.1.1&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&tiled=true&feature_count=101&service=WMS&request=GetMap&layers=zeta&bbox=-7514065.628545966%2C5009377.085697312%2C-6887893.4928338025%2C5635549.221409475&width=256&height=256

You shouldn't need to do anything with ncWMS or Godiva2. 

Does this all make sense to you?

**Comment by ghost** [comment]
@metanomy 

I am currently going through the setup process; taking a while. 

@rsignell-usgs 
I get "cannot using file globbing for remote (OPeNDAP) datasets" when I visit the second link (the example WMS request). That doesn't look like the expected value? 

I'll get back to you after I attempt the the min/max button.

**Comment by rsignell-usgs** [comment]
@foreverundecided89 , we have some tips for setting up TerriaJS here:
https://github.com/neracoos-open/NFWF/wiki/Setting-up-TerriaJS-for-NFWF

I just tried the WMS request above and it worked fine, so perhaps it was a temporary issue?

**Comment by ghost** [comment]
Yes it seems to be a transient issue. 

Got terriajs and nationalmap setup. I think that for the max/min widgets, I would need to add a viewmodel object, then reference it in the NowViewingTabViewModel.js file, since that's where the opacity slider and legend are used. 

I am having trouble wrapping my head around how the data flow works. Namely, 
a) which files are responsible for grabbing the initial data to display when the webapp loads? 
b) when I select a data set on the data catalogue view, some data gets loaded. can you give an example call chain of how the UI change triggers the REST call, and how the resulting data is bound back to the map view?

**Comment by rsignell-usgs** [comment]
Well, basically TerriaJS constructs the WMS request like the one here https://github.com/TerriaJS/terriajs/issues/927#issuecomment-178759824
combining parameters specified in the JSON (for example: 
https://github.com/rsignell-usgs/ehzrap/blob/master/testing/nfwf.json#L54-L64
with other dynamically controlled parameters (the time slider, the zoomed window extent).

**Comment by metanomy** [comment]
a) Take a look at [this](https://github.com/metanomy/ehzrap/blob/master/config/ehzrap_test.json) file, specifically the COAWST (THREDDS) section. Because we're using the [aremi](https://github.com/NICTA/aremi-natmap) branch of terriajs, the config file for the initial data catalog is stored in wwwroot/init, and nationalmap.js defines which file name is loaded from that directory.

b) Not sure (I'm no JS expert), but I think the UI change trigger is handled by [Catalog.js](https://github.com/TerriaJS/terriajs/blob/master/lib/Models/Catalog.js) model. The code that actually constructs the WMS call is (I believe) [WebMapServiceCatalogItem.js](https://github.com/TerriaJS/terriajs/blob/master/lib/Models/WebMapServiceCatalogItem.js).

**Comment by ghost** [comment]
@metanomy 
I am currently using the master branch of **NICTA/nationalmap** and **TerriaJS/terriajs repos**.  
https://github.com/NICTA/nationalmap
terriajs: https://github.com/TerriaJS/terriajs
1. Based on what you said, seems like I should be testing with the master branch of **NICTA/aremi-nat** repo instead (https://github.com/NICTA/aremi-natmap) 
2. Is it fine to use master branches or are there specific branches you want me to work off from?

**Comment by ghost** [comment]
Hi. I am able to create a KO view model and 2 text fields on the UI, so the catalog item's COLORSCALERANGE field changes. 

However, I am not sure what's the mechanism in the current setup to trigger a refetching of data if some of the catalog item's parameter changes. I am assuming there is such a mechanism, since I see the 'parameters' property in ./lib/Models/WebMapServiceCatalogItem.js is made into an observable property by knockout (https://github.com/TerriaJS/terriajs/blob/master/lib/Models/WebMapServiceCatalogItem.js#L113).

**Comment by metanomy** [comment]
@foreverundecided89 The simplest choice might be to simply re-use the code that activates the query and displays the results when a user initially selects a layer. In other words, once a user has made the changes to the color scale range (and perhaps then selected a "requery" or "done" button), a new query (with the new parameters) is made and display, re-using the WebMapServiceCatalogItem.js code (but adding in additional parameters as entered by the user for the color scale).

Make sense?

**Comment by rsignell-usgs** [comment]
@foreverundecided89 , any branch should be fine.   Neither @metanomy or myself are developers, so it would be great if @kring, @RacingTadpole could answer your question about how to trigger a new request when the user changes a parameter.

**Comment by RacingTadpole** [comment]
Hi @foreverundecided89, thanks for getting involved!
It doesn't currently automatically redisplay an imagery layer when its parameters change, but you could define:

```
knockout.getObservable(this, 'parameters').subscribe(...)
```

to make it kill the old one and create a new one whenever parameters change.

An example where we do this: when the display variable of a region-mapped csv file is changed,  https://github.com/TerriaJS/terriajs/blob/master/lib/Models/RegionMapping.js#L84 .

Hope that helps!

Re the branch to work off - `master` is fine, but be aware that we are also actively working on a new user interface in `newui`, which involves rewriting all the viewmodels and views. So if you want to build off that branch, it will be less merging down the track, which would be great; however, be aware there's a fair bit of work still to go before we will merge `newui` into `master`, so your changes may take longer to hit production.

**Comment by axman6** [comment]
This is something we also will probably need for AREMI, we're currently looking at deploying two Threads based services, one which needs to select between different elevations, and one which (currently) has hourly data (which works well at the moment via the time slider, but mentioning it for completeness).

**Comment by metanomy** [comment]
@RacingTadpole - if @foreverundecided89 uses the master branch of NICTA/aremi-natmap it would be easier for us to do some iterative development and testing, unless you think newui will be merged within a month or two.

**Comment by RacingTadpole** [comment]
Yes, that sounds sensible. I think it will be at least 2 months before `newui` gets merged into master (but hopefully not much more than that!).

**Comment by ghost** [comment]
Hi all. The scope of this task is larger than I anticipated, and I don't think I can commit the time necessary to implement this feature.

**Comment by metanomy** [comment]
@foreverundecided89 If I increased the amount of the bounty would you help you to commit the time? :)

**Comment by rsignell-usgs** [comment]
@foreverundecided89 , a related question.  Did you get into this enough to estimate the amount of time it might take you to complete the task?

**Comment by ghost** [comment]
@metanomy 
That sounds tempting, but I'd have to pass at this point. 

@rsignell-usgs 
I haven't had a chance to fully understand the parameters in the GetMap api or the ncWMS extensions. I think you should specifically itemize what new parameters are to be added to the existing call, so it is clear how many widgets need to be added. Another thing that would help is to specify what each widget should look like, and how the user would interact with it. Without this info it is pretty hard to give a time estimate.

**Comment by stevage** [comment]
Ok, so we did a bit of speccing out of this feature. Here's how the catalog (init) file could look:

```
{
  "type": "wms",
  "url": "http://...",
  "userParameters": [
    {
      // name of the UI label
      "name": "Color scale range",
      // range displays two numeric selectors, and outputs a string like "230-310"
      // number is a single numeric selector
      "type": "range",
      // the URL parameter sent to the WMS server
      "param": "COLORSCALERANGE"
      // the initial values of the numeric selectors
      "rangeDefaults": [230, 310],
      // the minimum and maximum values that the min and max are constrained within
      "rangeLimits": [0, 500]
    }
  ]
}
```

**Comment by rsignell-usgs** [comment]
Closing this general issue in favor of more granular/specific issues:
https://github.com/TerriaJS/terriajs/issues/774
https://github.com/TerriaJS/terriajs/issues/1512
https://github.com/TerriaJS/terriajs/issues/1976
https://github.com/TerriaJS/terriajs/issues/1977
https://github.com/TerriaJS/terriajs/issues/1511
@kring, please make sure these are included in the USGS CMG milestone at https://github.com/TerriaJS/terriajs/milestone/17
