### ISSUE TITLE
Definable behaviour for CSV regions with no value 

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#928]
From https://github.com/TerriaJS/terriajs/pull/924#discussion_r40048811

I don't think it is the right behaviour. Consider:

```
lga_name,coffee
melbourne,great
sydney,bad
adelaide
```

I think we both agree that every LGA other than Melbourne, Sydney and Adelaide should not be shown. But hiding Adelaide seems surprising and not wanted.

So, I suggest that the display of "no data" regions should be a property in `tableStyle`, like:

```
tableStyle: { 
   dataVariable: coffee,
   noDataColor: hsla(0, 0%, 50%, 50%);
}
```

and IMHO it should probably default to something like that: translucent grey. It's "no data for this variable" not "not present in dataset".

**Comment by stevage** [comment]
I think this has been implemented by @RacingTadpole. Right?

**Comment by RacingTadpole** [comment]
Yep, thanks.
