### ISSUE TITLE
Cannot zoom past level 18 in leaflet

### ISSUE THREAD

**Issue by keattang** [TerriaJS/terriajs#939]
When loading in a `TileMapServiceImageryProvider` via an `ImageryLayerCatalogItem` that has tiles at levels higher than level 18, these tiles are inaccessible in leaflet because you can't zoom in past level 18.

I tried fixing this by changing the code at line 85 of `CesiumTileLayer` from: 

```
if (defined(this.imageryProvider.maximumLevel)) {
    this.options.maxNativeZoom = this.imageryProvider.maximumLevel;
}
```

to:

```
if (defined(this.imageryProvider.maximumLevel)) {
    this.options.maxNativeZoom = this.imageryProvider.maximumLevel;
    this.options.maxZoom = this.imageryProvider.maximumLevel;
}
```

However this only allowed me to zoom to level 20 which I believe is the max zoom level for the `BingMapsImageryProvider`

**Comment by kring** [comment]
@keattang try setting the `maxZoom` at `L.map` creation time:
https://github.com/TerriaJS/terriajs/blob/master/lib/ViewModels/TerriaViewer.js#L490
http://leafletjs.com/reference.html#map-constructor

**Comment by kring** [comment]
Also, did you confirm that `maximumLevel` is set correctly on your `TileMapServiceImageryProvider`?  It could be wrong either because the information is missing from your `tilemapresource.xml`, or due to a bug in Cesium.

**Comment by keattang** [comment]
The `TileMapServiceCatalogItem`'s `maxZoom` attribute is being correctly overridden and the  `maximumLevel` is being correctly set to level 23. `this.options.maxZoom` is also being set to 23. I think the Bing level of 20 is somehow overriding the max zoom. I think setting the max zoom setting on the map however may work

**Comment by keattang** [comment]
Setting it on map creation has worked perfectly. I'll make a few changes to allow you to set the maxZoom through options and then make a pull request.

**Comment by keattang** [comment]
actually I think I've spoken too soon. setting the zoom level on map creation allows me to zoom past level 18 to level 23, however, past level 20 all I get is blank (slightly grey) tiles

**Comment by kring** [comment]
do you still have your change mentioned in the original issue description?  I think you might not want that.

**Comment by keattang** [comment]
no I reversed that. I'm going to try setting the zoom level on `CesiumTileLayer` creation in `ImageryLayerCatalogItem`

**Comment by keattang** [comment]
created the above fix. will make a pull request

**Comment by kring** [comment]
Fixed by #941.

**Comment by kring** [comment]
I was just browsing through the Leaflet changelog, and say this:

> Fixed a bug where tile layers were not respecting their minZoom or maxZoom options (by @ivansanchez) #3778

https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md#074-september-1-2015

So it sounds like the difficulties here were a Leaflet bug.

**Comment by keattang** [comment]
What's the timeline for getting this into terria? I'm happy to revisit this when it gets merged in. 

Cheers
Keat

**Comment by kring** [comment]
@keattang No specific plans currently.  It should be easy, though (change the version in package.json, run npm install, test) so maybe I'll do it if I get a free minute next week.
