### ISSUE TITLE
Handle WMS time inverval specification

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#942]
In our WMS services serving model results, which tend to have unifom time spacing, we can save a lot of space in the `getCaps` by using the WMS time interval specification like this instead of specifying the complete list of time values explicitly

```
<Extent name="time">
2013-12-05T01:00:00/2014-09-29T12:00:00/PT1H,2014-10-07T01:00:00/2015-09-24T12:00:00/PT1H
</Extent>
```

Here's a full example `getCaps`: 
http://tampabaymap.org/sci-wms/wms/datasets/wfsfvcomagg?service=WMS&version=1.3.0&request=GetCapabilities

But it seems that the TerriaJS code cannot handle this, expecting a simple list of times instead:
https://github.com/TerriaJS/terriajs/blob/master/lib/Models/WebMapServiceCatalogItem.js#L527-L541

It would be great to handle the WMS  time interval specificatiion in TerriaJS so that problems like this could be solved: https://github.com/sci-wms/sci-wms/issues/80#issuecomment-144071139

**Comment by kring** [comment]
Thanks @rsignell-usgs.  It should be straightforward to support those ISO8601 intervals - especially if we can find a decent third party library to parse them.

**Comment by metanomy** [comment]
@kring Something like this? https://gist.github.com/jmrocela/7167208

**Comment by rsignell-usgs** [comment]
I'm surprised nobody else needs these WMS time intervals to work.    Perhaps that means that WMS providers don't know about them, or that most WMS services aren't smart enough to use them!

**Comment by metanomy** [comment]
Both. I don't know many WMS clients that treat time as a first-class citizen (as opposed to just another data parameter).

**Comment by meh9** [comment]
We are certainly treating time as very important - many (most?) of the cool datasets we want to visualise are time based. However, I have yet to see a service that presents the time intervals this way, but it could just be that we are dealing with more immature service providers. I does look very useful for when there are a large number of intervals since we make many many GetCaps calls.

**Comment by metanomy** [comment]
@meh9 I should have said "...many WMS clients - with a very notable exception being Cesium/TerriaJS".   The core of the issue is increased time-series data being made available from the climate and forecast scientific communities, as well as slower adoption of the latest OGC standards and extensions in the codebase of traditional GIS clients.

**Comment by meh9** [comment]
@metanomy sorry, I should have been clearer with what I said as well - I wasn't trying to defend Terria! Since we have been working a lot with timeseries data lately I'm very aware of where we could do better, and this will definitely improve with time as we put more resources into this problem.

I don't actually know in what way many of the other GIS clients handle timeseries data. If we are already doing well then that is fantastic to hear. :)

**Comment by metanomy** [comment]
@meh9 The only other extension to TerriaJS/Cesium for time I think would be valuable is to integrate a time-slider query, e.g., the ability to define a span of time and query the data of a layer (or layers) using that span. That's as much an extension to the timeslider within Cesium as it is in the catalog query logic of TerriaJS.

**Comment by RacingTadpole** [comment]
Hi @rsignell-usgs, the server at http://tampabaymap.org seems to be down - is that getCapabilities info anywhere else? Thanks!

**Comment by RacingTadpole** [comment]
Hi @rsignell-usgs, the link http://tampabaymap.org/sci-wms/wms/datasets/wfsfvcomagg?service=WMS&version=1.3.0&request=GetCapabilities isn't giving me any capability info - is there another link with a fuller example? thanks!

**Comment by rsignell-usgs** [comment]
http://sci-wms.whoi.edu/wms/datasets/ugridtest?REQUEST=GetCapabilities

**Comment by RacingTadpole** [comment]
thanks, that's working.

**Comment by RacingTadpole** [comment]
Hi @rsignell-usgs, with some changes I've made, terria is generating requests like this, but they're returning 500 errors:
`http://sci-wms.whoi.edu/wms/datasets/ugridtest?time=2015-04-27T16%3A15%3A00&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&service=WMS&version=1.1.1&request=GetMap&layers=avg_salt&bbox=15028131.257091936%2C-7514065.628545966%2C17532819.79994059%2C-5009377.085697312&width=256&height=256` 
I've tried a few different formats for the time parameter (eg. adding a Z to it, leaving the time parameter out altogether), but still get 500 errors. Do you know what format I should be using? Thanks!

**Comment by metanomy** [comment]
@RacingTadpole Here's an alternative layer to test: http://dev.tampabaymap.org:7002/wms/datasets/wfsfvcom?REQUEST=GetCapabilities

**Comment by metanomy** [comment]
@RacingTadpole I tried your query against my url above, and found this in the sci-wms logs;
MultiValueDictKeyError: "'bbox'"

**Comment by RacingTadpole** [comment]
interesting, thanks @metanomy - I'll look into these...

**Comment by RacingTadpole** [comment]
Hi @metanomy, when I use the alternative layer in terria, it produces this layer URL - which unfortunately also gives me a 500 error - do you have an example of a correctly formed request? `http://dev.tampabaymap.org:7002/wms/datasets/wfsfvcom?time=2013-12-04T14%3A00%3A00Z&srs=EPSG%3A3857&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&service=WMS&version=1.1.1&request=GetMap&layers=u&bbox=15028131.257091936%2C-15028131.257091936%2C20037508.342789244%2C-10018754.17139462&width=256&height=256` Thanks!

**Comment by metanomy** [comment]
That URL itself isn't working against the sci-wms server. I'm not sure why. Can you try using some different parameters (perhaps the EPSG needs to be standard 4326?)

**Comment by RacingTadpole** [comment]
Interesting - changing the URL to EPSG%3A4326 still gives a 500. But - I see that the GetCapability for these layers declare `<SRS>EPSG:3857</SRS>`, but the bounding box is not defined with that standard - instead it's `<BoundingBox SRS="EPSG:4326" ...>`. I don't know if that's a problem.

**Comment by rsignell-usgs** [comment]
Here's a WMS endpoint with time and height:

http://ecowatch.ncddc.noaa.gov/thredds/wms/ncom_amseas_agg/AmSeas_Apr_05_2013_to_Current_best.ncd?service=WMS&version=1.3.0&request=GetCapabilities

And here's a valid WMS GetMap query:

http://ecowatch.ncddc.noaa.gov/thredds/wms/ncom_amseas_agg/AmSeas_Apr_05_2013_to_Current_best.ncd?LAYERS=water_temp&ELEVATION=0&TIME=2015-10-20T00%3A00%3A00.000Z&TRANSPARENT=true&STYLES=boxfill%2Frainbow&CRS=EPSG%3A4326&COLORSCALERANGE=21.63%2C33.19&NUMCOLORBANDS=20&LOGSCALE=false&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&FORMAT=image%2Fpng&SRS=EPSG%3A4326&BBOX=-93.80859375,17.7392578125,-72.2607421875,39.287109375&WIDTH=256&HEIGHT=256

**Comment by metanomy** [comment]
@rsignell-usgs Do you know if sci-wms reprojects layers to 4326 as a default?

**Comment by RacingTadpole** [comment]
Thanks for the ecowatch endpoint! That's looking good.

**Comment by metanomy** [comment]
@RacingTadpole: Trying to figure out why sci-wms doesn't like your query. Specific line is: IndexError: list index out of range

Here's the full section:

ERROR:tornado.access:500 GET /wms/datasets/ugridtest?time=2015-04-27T16%3A15%3A00&srs=EPSG%3A4326&transparent=true&format=image%2Fpng&exceptions=application%2Fvnd.ogc.se_xml&styles=&tiled=true&service=WMS&version=1.1.1&request=GetMap&layers=avg_salt&bbox=15028131.257091936%2C-7514065.628545966%2C17532819.79994059%2C-5009377.085697312&width=256&height=256 (100.13.22.14) 17.35ms
ERROR:django.request:Internal Server Error: /wms/datasets/ugridtest
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/opt/conda/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, _args, *_kwargs)
  File "/opt/conda/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, _args, *_kwargs)
  File "/srv/sci-wms/wms/views.py", line 263, in get
    request = enhance_getmap_request(dataset, layer, request)
  File "/srv/sci-wms/wms/views.py", line 122, in enhance_getmap_request
    colormap=wms_handler.get_colormap(request),
  File "/srv/sci-wms/wms/wms_handler.py", line 195, in get_colormap
    requested_cm = request.GET.get(parameter).split(',')[0].split('_')[1]
IndexError: list index out of range

**Comment by RacingTadpole** [comment]
@rsignell-usgs - I looked more carefully at the ecowatch getCapabilities time specification, and it uses the comma-separated values style... do you know of one that uses the time/time/period syntax? Thanks!

**Comment by rsignell-usgs** [comment]
Oh crud.  I forgot which issue we were talking about and specifically picked an endpoint with all times listed!  Oh, now that I'm back on track, here is a WMS endpoint with time intervals:

http://geoport-dev.whoi.edu/thredds/wms/coawst_4/use/fmrc/coawst_4_use_best.ncd?service=WMS&version=1.3.0&request=GetCapabilities

And here's a sample WMS getMap query:

http://geoport-dev.whoi.edu/thredds/wms/coawst_4/use/fmrc/coawst_4_use_best.ncd?LAYERS=temp&ELEVATION=-0.03125&TIME=2015-10-20T00%3A00%3A00.000Z&TRANSPARENT=true&STYLES=boxfill%2Falg2&COLORSCALERANGE=11.76%2C30.23&NUMCOLORBANDS=100&LOGSCALE=false&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&FORMAT=image%2Fpng&SRS=EPSG%3A4326&BBOX=-83.006379190914,31.242026011357,-58.757973988643,55.490431213629&WIDTH=256&HEIGHT=256

Here's a JS fiddle that shows using moment.js to decode the time values:
http://jsfiddle.net/3eyoqLaw/6/

**Comment by rsignell-usgs** [comment]
@sasignell did the fiddle http://jsfiddle.net/3eyoqLaw/6/ reference above, but didn't have time to integrate, test and submit a PR.  

He told me offline:

"Basically I (think) all it really needs is an if,then statement after they've split and are iterating through timestamps that does looks for slashes in the string (highlighted) and parses accordingly

```
function getTimeStamps() {
    var array=[];
    var input= document.getElementById('myTextField').value;
    if(input.indexOf('/') === -1)
        {
          $("#result").html(input);
        }       
    else if(input.indexOf('/') > 0)
        {
           var start=moment(input.split('/')[0]);
            var end=moment(input.split('/')[1]);
            var duration=moment.duration(input.split('/')[2]);
            var range=moment.range(start,end);
            range.by(duration, function(moment) {
              array.push(moment.toISOString());
            });
            $("#result").html(array);
        }  
}
```

Of course, the `moment.js` and `moment-range.js` libraries would have to be referenced somewhere for this to work, and I don't know how nicta does that.  "

@sasignell was okay with someone else bringing this home....

**Comment by RacingTadpole** [comment]
Great, thanks!
