### ISSUE TITLE
Hierarchies and aggregation in CSV files

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#943]
This came up in a client meeting today. Take a file like:

```
Category, Subcategory, Value, Region,
Industry, Manufacturing, 33, Suburbia
Industry, Mining, 16, Suburbia
```

We would like to tell Terria to aggregate by items in `Category`, combining values in the `Value` column. Something like:

```
type: csv,
tableStyle: {
  dataVariable: "Value",
  regionVariable: "Region"
},
aggregations: {
  "Category": {
    groupBy: "Subcategory",
    operation: "sum"
  }
}
```

Points to consider:
- flexibility for user: defining aggregations should open pre-defined pathways for the user, not prevent them viewing columns individually
- UI: do we want the user to be able to define their own aggregations as well (eg, changing "sum" to "mean")
- do we want to define "hierarchies" (Category, Subcategory, Subsubcategory) or just spell out how to aggregate at each level? It would be pretty unusual to have more than 3 levels.

**Comment by stevage** [comment]
Closely related (and possibly just a different take on the same underlying need) is being able to aggregate all the CSV items that are contained within a group, or within a group inside a group etc.

Imagine a group like this:

Energy
- Residential
  -- Houses
  --- Hot water
  --- Heating
  --- Cooling
  --- Lighting
- We want to click "Houses" and have this aggregate the 4 things below that, showing the sum as a region map. (And similarly for "Residential" and "Energy")
- Say we click on "Houses", and then click on a particular region. Now we want to see a time series that is a stacked area chart, showing how the composition of residential energy use changes over time - lighting goes down, cooling goes up, or whatever.

This could look something like:

![nm-hierarchy-aggregation](https://cloud.githubusercontent.com/assets/678344/10386186/77cf3f02-6e9f-11e5-97dd-4b9b0bd3d28e.png)

The difference between this and what's described above is probably just perspective.

## Approach 1:

One CSV file that contains information about hot water, heating, cooling, lighting, and a column that says "Houses"

TerriaJS creates sub "items" that can be independently enabled or disabled.  Or you just enable the whole layer.

Viewed this way, the "sub items" are basically filters, and it starts to look a lot like the AbsIttCatalogItem.

![absitt](https://cloud.githubusercontent.com/assets/678344/10386291/120349be-6ea1-11e5-9f6d-f8edfc91458e.png)

## Approach 2:

One CSV file for hot water, another for heating, etc. These are all listed as `items []` in a `group` item "Houses".

TerriaJS treats them independently, but has a (novel) way of aggregating them. This is probably really hard to implement, as it requires loading the CSVs, looking for fields in common, taking guesses about how to aggregate, suppressing their normal way of displaying, etc.

## Conclusion

All in all, Approach 1 is probably much better.

**Comment by kring** [comment]
This sounds cool, but probably not going to happen without a specific client need.  Closing.
