### ISSUE TITLE
Snap timeline scrubber to closest datapoint

### ISSUE THREAD

**Issue by philipgrimmett** [TerriaJS/terriajs#946]
When dealing with time series data, the timeline scrubber should snap to the closest datapoint on click-drag-release. This should help to communicate the granularity of the data currently being displayed.

**Comment by meh9** [comment]
Use case and real world existing service that we would like this for in https://github.com/TerriaJS/terriajs/issues/896

**Comment by stevage** [comment]
Some details:
- the timeline needs to show where the data points are
- we should maybe apply the "snapping" also in play mode, so the timeline advances in discrete jumps from datapoint to datapoint. (Not sure if there are times when this is the wrong thing to do)
