### ISSUE TITLE
Composite group type

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#956]
There are cases where it may be useful to have several layers act as if they were one combined layer. For instance, if we have data providers that cover spatially disjoint rejoins (eg, different states). 

The behaviour would be like `group` (maybe with a flag), but:
- The group behaves in the interface like an item (can be enabled or disabled)
- Individual items in the group are not shown in the catalog
- All items in the group are shown if the group is enabled, and vice versa
- What the group info popup box shows is a messy question

The immediate need is for Northern Australia, where many of the data sources come from WA, NT and QLD, but the end user doesn't really care which.

**Comment by kring** [comment]
Check out CompositeCatalogItem.  It may not do everything that's needed, but it's a good start.

**Comment by kring** [comment]
Fixed by #977
