### ISSUE TITLE
Data-labelled region maps

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#957]
The one thing preventing me using Terria instead of CartoDB for http://map.opencouncildata.org is region labelling:

<img width="324" alt="screenshot 2015-10-07 17 13 30" src="https://cloud.githubusercontent.com/assets/678344/10330278/d48d5b6e-6d16-11e5-9033-03e324b4c026.png">

We don't have a specific client need for this yet, but it probably won't be long. The configuration would probably look like this:

```
tableStyle: {
  dataVariable: platform,
  regionVariable: lga_name,
  labelVariable: datasets  
}
```

Of course we have to decide how much effort to put into controlling styling etc.

**Comment by kring** [comment]
Probably not happening without a specific client need, so closing for now.
