### ISSUE TITLE
semantic html

### ISSUE THREAD

**Issue by chloeleichen** [TerriaJS/terriajs#959]
I think we can make the html more semantic. For example, the CatalogGroups and CatalogItems  on the left hand side can be in `ul`s rather than `divs`, and some `divs` can be `button`s. Then it'll be easier for us to address accessibility issues like #507 and #506

![screen shot 2015-10-08 at 3 40 38 pm](https://cloud.githubusercontent.com/assets/7508939/10357876/4c19e1f4-6dd3-11e5-8e89-9bba1f9bfe99.png)

**Comment by kring** [comment]
Sounds great!

**Comment by stevage** [comment]
Yep, definitely!

**Comment by stevage** [comment]
Closing because it got implemented?

**Comment by chloeleichen** [comment]
it was related to the old ui and the newui is more semantic than the old ui in many ways
