### ISSUE TITLE
UI for selecting color ramps

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#961]
Currently there is no way to choose a different color ramp ( `tableStyle { colorMap: ... }`) in the Terria interface. We really need some kind of selector, with at least a few basic choices.

This issue depends on #936.

**Comment by chloeleichen** [comment]
This is the color ramp selection interface of cartodb, pretty awesome
![interface](https://cloud.githubusercontent.com/assets/7508939/10385754/360372c4-6e99-11e5-8707-70ef9b5a6010.png)

**Comment by kring** [comment]
This website has color schemes for maps downloadable in JSON and other formats:
http://colorbrewer2.org/#

**Comment by kring** [comment]
We recently added the ability to select WMS styles.  The UI for this wouldn't be much different and should be pretty straightforward to implement.

**Comment by rowanwins** [comment]
Carto have also open sourced some color schemes [here](https://github.com/CartoDB/cartocolor), and an [associated blog post](https://carto.com/carto-colors/) with a quick overview

**Comment by nf-s** [comment]
Closed by https://github.com/TerriaJS/terriajs/pull/6188
