### ISSUE TITLE
Smarter choroplething using Jenks, Quantile, etc.

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#962]
In our region mapping and point choroplething (mapping values to colors), we currently always do a linear map: https://github.com/TerriaJS/terriajs/blob/d034381ef7b686001c88acf2991956f8d166ead1/lib/Map/TableDataSource.js#L447

This gives a poor result cartographically, because one outlying value can make all other values indistinguishable by colour. This has been remarked by participants in our workshops.

The solution is to use smarter binning functions, such as the Jenks Natural Breaks. Fortunately, there is a library for this already: https://github.com/simogeo/geostats

So I think what we need is:
- incorporate the library (in the smallest way possible)
- pick a sensible default (CartoDB uses 'quantile' as its default - perhaps we follow suit in the absence of a compelling reason not to)
- allow alternatives to be specified in init files:

```
{ tableStyle:
    colorFunction: "jenks"
}
```
- respect this setting [here](https://github.com/TerriaJS/terriajs/blob/region-mapping-advanced-matching/lib/Models/CsvCatalogItem.js#L741)
- bonus points: a UI for selecting them (alongside #961)

**Comment by stevage** [comment]
Just putting this here. If/when we do GeoJSON:
- https://github.com/morganherlocker/geocolor
- http://turfjs.org/static/docs/module-turf_jenks.html

**Comment by stevage** [comment]
geostats wasn't up to the job. Switching to [simple-statistics](http://simplestatistics.org/docs/) (16KB min)

**Comment by RacingTadpole** [comment]
Solved by #1180, right?

**Comment by stevage** [comment]
Thanks, yup.
