### ISSUE TITLE
Timeseries controls disappear when any layer is disabled even when other timeseries are enabled

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#965]
When multiple timeseries layers are enabled, turning any layer off removes the timeseries controls.

Steps:
1. Go to: http://nationalmap.gov.au/#test
2. Turn on at least two layers in Test Data -> Temporal.
3. Turn any layer off.
4. Observe timeseries controls disappear, even though there are still timeseries layers visible.

**Comment by AlexGilleran** [comment]
Changing nature of this based on the discussion in the PR - the timeline disappears because it's specific to the layer that just got hidden. To fix this, all layers should be visible in the one timeline.

**Comment by AlexGilleran** [comment]
So in the PR thread, @kring wrote:

> > Either that or actually make it so that the timeline automatically expands to fit the earliest and latest points in all the layers
> 
> This sounds ok to me.  Ideally we'd indicate on the timeline (somehow!) which sub-intervals actually have data.  The Cesium timeline (which we're not using anymore) has basic support for this:
> 
> http://cesiumjs.org/releases/1.17/Apps/TimelineDemo/index.html
> 
> ![image](https://cloud.githubusercontent.com/assets/924374/12157597/f3e6990a-b526-11e5-86f6-959f80cf1b20.png)

So it's possible to do something like that in Terria quite easily using the Cesium timeline:

![image](https://cloud.githubusercontent.com/assets/900555/12190090/931de93c-b618-11e5-9fb7-0c099bd9bf12.png)

However, figuring out what timeline track belongs to what data layer remains a problem - all Cesium supports is turning them different colours, but our layers aren't colour coded like that. I'd like some UX guidance on this - does it make sense to have them reveal the name of the layer on mouse hover? Maybe make them a bit taller and put the name in them?

**Comment by AlexGilleran** [comment]
@cam-grant

**Comment by AlexGilleran** [comment]
So based on discussion last week, the new solution is to just make it so that the timeline displays the name of the layer that it's currently tracking. If there are two time-series layers enabled and the one currently being tracked by the timeline is disabled, the timeline will simply track the remaining one, with the displayed name changing to the name of the remaining layer.
