### ISSUE TITLE
Data layer interactivity issues 

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#968]
There are a number of related (and often hard to solve) issues around users interacting with data layers on the map.
1. Users don't realise that they can click on layers, because the mouse cursor doesn't change when hovering.
2. Selected features or whole layers are not highlighted (#922)
3. We would like to show some information "on rollover". For example, on AREMI, showing the name of electricity grid segments.
4. We would like to highlight feature geometry on rollover.
5. It's not clear when you click on a layer what you clicked on (#553)
6. When you click on a point where two layers overlap, you should see information from all layers (#569)
7. Clicking on a feature retrieves the whole geometry for that layer, but it isn't used for anything. (#963)

To spell out some of the underlying difficulties:
- most of our data comes from WMS sources.
- WMS is raster tile service, "pictures of data". So generally, we don't have the geometry of features or whole layers in the browser.
- WMS has a "`getFeatureInfo`" action, which returns the geometry, but that can be a huge amount of data - way too much to do on rollover, and probably too much for on-click. (And there's no easy way to know how much data it would be before we requested it.)
- anything we implement has to work in both Leaflet and Cesium.

And some possible solutions (or directions for solutions):
- [vector tiles](http://en.wikipedia.org/wiki/Vector%20tiles) are a very efficient way of transporting geometry into the browser, but could be 5 years away before government servers support them. Plus there is no Cesium support yet.
- There is a MapBox technology, [UTFGrid](https://www.mapbox.com/blog/how-interactivity-works-utfgrid/), which is pretty good at making raster tile sources interactive, but would require server-side support, and Cesium development, and probably doesn't help us.
- Or maybe we could have some lighweight "featureinfo proxy" service which specifically just returns a very small amount of information about a given point, like "no data here", or the attributes (but no geometry), for point #1 above.

**Comment by kring** [comment]
This is a great summary of the current state, and the possible solutions are useful as well, but overall this issue isn't actionable.  Let's close this issue, and write separate, more specific ones if there are any current needs.
