### ISSUE TITLE
2 tests (specs) fail

### ISSUE THREAD

**Issue by RacingTadpole** [TerriaJS/terriajs#970]
2 specs fail on opening http://localhost:3002/SpecRunner.html in a browser:

CsvCatalogItem has a blank in the description table for a missing number
CsvCatalogItem renders a point with no value in transparent black

**Comment by RacingTadpole** [comment]
Closing as this will be fixed as part of #924

**Comment by stevage** [comment]
Yep. The behaviour of the first one changed for no particular reason (and the test was too specific), and the behaviour of the second one isn't well defined (#928).
