### ISSUE TITLE
Choroplething for WFS, GeoJSON, and other types

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#973]
So far we only choropleth CSV region mapped types. But there are cases (eg, with some AURIN data) where it would be very helpful to color code regions from a WFS server, or even GeoJSON. Currently we display both WFS and GeoJSON features with their default styling, usually grey.

**Comment by kring** [comment]
Perhaps an alternative approach is to make it easy to stand up region mapping servers and to interactively add them to a TerriaJS app.  In any case, unlikely that anything is going to happen here without a specific client need, so I'm closing this.
