### ISSUE TITLE
CSV with both lat/long and state columns no longer renders

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#978]
We have a CSV file with both lat/long and state columns that used to render fine. We now get an error message saying the values in the state column are incorrect, and the points from the lat/long are not rendered. In this case the data in the state column is actually only there for information, it should not be used to show the data on the map, the lat/long is what should be used.

The CSV file:

https://github.com/NICTA/aremi-natmap/blob/master/wwwroot/datasets/SolarStationHistoricalObservations/SolarStations.csv

**Comment by RacingTadpole** [comment]
This file works now.
