### ISSUE TITLE
CSV legend is calculated incorrectly

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#985]
I have a case where the CSV legend is calculated incorrectly when a `minDisplayValue` and `maxDisplayValue` is specified - the min value is ignored and instead the smallest value of the data points is used instead when colouring in the points.

Using the following `tableStyle` and data (files attached as well):

```
          "tableStyle": {
            "dataVariable": "Data",
            "minDisplayValue": 0,
            "maxDisplayValue": 100
          }
```

```
Point,Data,Lat,Lon
A,60,-31.9887,141.3846
B,50,-31.5569,147.0849
```

The initial legend looks like this:

<img width="148" alt="screen shot 2015-10-21 at 9 15 52" src="https://cloud.githubusercontent.com/assets/5283003/10622598/5f0bcb64-77d4-11e5-80fa-e2066b754cb0.png">

But the points are coloured like this:

<img width="77" alt="screen shot 2015-10-21 at 9 16 21" src="https://cloud.githubusercontent.com/assets/5283003/10622614/735e99ac-77d4-11e5-99bb-2e576119e6d0.png">

Since the data point values are 50 and 60, the expected outcome is a green point and a green-on-its-way-to-yellow point.

When you switch legend column to Point then back to Data, the specified range is removed, and the colours are correctly between the lowest and highest value.

[test_init.txt](https://github.com/TerriaJS/terriajs/files/17174/test_init.txt)

[test.txt](https://github.com/TerriaJS/terriajs/files/17178/test.txt)

**Comment by meh9** [comment]
I believe this is existing behaviour from before the new CSV changes from @stevage.

**Comment by stevage** [comment]
Yeah I'm also working on making the colour mapping stuff work better. IMHO the current semantics are a bit murky.

**Comment by stevage** [comment]
I think this is not an issue any more. Reopen if it is.
