### ISSUE TITLE
when layer is proxied, also proxy the legends

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#988]
Currently when a layer is proxied the legend still uses a straight URL. If the layer is proxied we should also proxy the legend since sometimes this is done because the proxy supplies the required username and password, i.e. Landgate.

**Comment by kring** [comment]
@steve9164 want to take a look at this one?

**Comment by kring** [comment]
Do this as a branch of `nowViewingSections` (described in [this pull request](https://github.com/TerriaJS/terriajs/pull/1090)) in order to avoid conflicts later.  The file you'll need to modify is `LegendSection.html` and probably also `LegendSectionViewModel.js`.

**Comment by tephenavies** [comment]
@kring Should this issue be closed now?

**Comment by kring** [comment]
Yes, it should, thanks @steve9164.  For future reference, if you include text like "Fixes #988" in the initial description of your pull request, GitHub will automatically close the issue when the pull request is merged.

**Comment by axman6** [comment]
@steve9164 (and @kring) preferably you should use "Fixes TerriaJS/terriajs#988" because it's possible to close bugs in other projects if they merge them in. I speak from experience, it can be very confusing =)

**Comment by kring** [comment]
@axman6 that will only happen if you say "Fixes #988" in a commit.  PRs don't get merged between projects.

**Comment by axman6** [comment]
Ah yes, good point.
