### ISSUE TITLE
Support WMTS servers that don't support web mercator projection, only geographic

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/terriajs#989]
NASA has a bunch of data available via OGC WMTS as described here:
https://wiki.earthdata.nasa.gov/display/GIBS/GIBS+API+for+Developers#GIBSAPIforDevelopers-OGCWebMapTileService(WMTS)

When I try dropping the WMTS WGS84 KVP endpoint (http://map1.vis.earthdata.nasa.gov/wmts-geo/wmts.cgi) into TerriaJS, it shows a bunch of layers, but when I select one, I get no tiles displayed. 

If I take a look at one of the tile requests, it looks like
http://map1.vis.earthdata.nasa.gov/wmts-geo/wmts.cgi?service=WMTS&version=1.0.0&request=GetTile&tilematrix=15&layer=MODIS_Aqua_CorrectedReflectance_TrueColor&style=default&tilerow=13743&tilecol=8841&tilematrixset=urn%3Aogc%3Adef%3Awkss%3AOGC%3A1.0%3AGoogleMapsCompatible&format=image%2Fjpeg

which doesn't return a jpeg, instead returning 

```
<ExceptionReport xmlns="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd" version="1.1.0" xml:lang="en">
<Exception exceptionCode="InvalidParameterValue" locator="TILEMATRIXSET">
<ExceptionText>TILEMATRIXSET is invalid for LAYER</ExceptionText>
</Exception>
</ExceptionReport>
```

Here's a valid request (that NASA provides):
http://map1.vis.earthdata.nasa.gov/wmts-geo/wmts.cgi?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=MODIS_Terra_CorrectedReflectance_TrueColor&STYLE=&TILEMATRIXSET=EPSG4326_250m&TILEMATRIX=6&TILEROW=13&TILECOL=36&FORMAT=image%2Fjpeg&TIME=2012-07-09

Any ideas how to get this working?

**Comment by kring** [comment]
Currently TerriaJS only supports WMTS servers that can provide tiles according to the Web Mercator projection. WGS84/CRS84 is not supported, in part because Leaflet is not able to display tiles using this projection (See #1020).

We're getting the strange error from the server because, when TerriaJS can't find a compatible TILEMATRIXSET in the GetCapabilities, it just blindly asks for `urn:ogc:def:wkss:OGC:1.0:GoogleMapsCompatible` and hopes for the best.

**Comment by rsignell-usgs** [comment]
@kring, okay, thanks for the explanation (and light slightly brighter at end of the tunnel!)

**Comment by nf-s** [comment]
This has been implemented in V8 https://github.com/TerriaJS/terriajs/pull/4720
