### ISSUE TITLE
point.pixelSize seems to have a limit in 3D mode

### ISSUE THREAD

**Issue by dcrossleyau** [TerriaJS/terriajs#991]
I want to show time-series data on a map, and have an example working by using CZML "point" and changing the colour and radius (pixelSize) over time.
See http://www.nationalmap.gov.au/#share=8yHd9U and enable the layer "Repower Shoalhaven : Output".

(I use "point" rather than "ellipse" so that the data is portrayed the same at any scale.)

Notice that the point grows to the desired maximum when in 2D mode. However in 3D mode it will not increase past a certain limit.

I have two test CZML files, but cannot attach here because no write permission.
These plot concentric circles near Sydney Opera House, in 10-pixel increments. It seems that the 3D limit is 60 pixels.

(Not sure where to report this issue, so starting with TerriaJS.)

**Comment by kring** [comment]
Hi @indexgeo, thanks for the report.  Can you visit this page and tell me what you have under the Rasterizer, Aliased Point Size Range section?
http://webglreport.com/
I think you may be running into a WebGL limitation on your hardware.

**Comment by dcrossleyau** [comment]
Added the two test files as a Gist:
https://gist.github.com/indexgeo/830361f6d1997dfe5099

**Comment by dcrossleyau** [comment]
Thanks @kring ... with Firefox-41.0.2 on Mac ... Aliased Point Size Range:  [1, 64]

**Comment by kring** [comment]
The circles grow pretty big on my system, which has a maximum point size of 2047 pixels according to WebGL report:
![image](https://cloud.githubusercontent.com/assets/924374/10654265/df201082-78b3-11e5-9f68-dce5bfb28f10.png)
So I think we can confirm that's the problem.

**Comment by dcrossleyau** [comment]
Drat. Thanks Kevin, i may need to find a different way to portray such data.

**Comment by kring** [comment]
Given that this is a hardware limitation, it's going to be fairly hard to work around.  We could potentially use a billboard instead of a "real" point when the point size gets bigger than the hardware limit.  This will have some performance implications, but at least it will continue to work.  This will actually be a change to Cesium, not TerriaJS, so you may want to raise an issue there.

**Comment by kring** [comment]
By the way, I'd be interested in hearing about what you're working on if you're willing to share!  My email address is on the web page linked from my GitHub profile.

**Comment by dcrossleyau** [comment]
Will do. I love what you guys are doing, so neat.

**Comment by kring** [comment]
Closed this because it will require a change to Cesium that TerriaJS will pick up automatically once it's made.
