### ISSUE TITLE
CZML drawing order in 3D is opposite to 2D

### ISSUE THREAD

**Issue by dcrossleyau** [TerriaJS/terriajs#992]
Use the CZML data files mentioned at Issue #991. Switch between 2D and 3D modes. Notice that the draw order is different.

The two test files as a Gist:
https://gist.github.com/indexgeo/830361f6d1997dfe5099

**Comment by dcrossleyau** [comment]
These plot concentric circles near Sydney Opera House, in 10-pixel increments. In one mode the data has an "archery target" effect, in the other mode the outer larger point obscures the other points. And vice versa when the packets in the CZML file are in the reverse order.

**Comment by stevage** [comment]
Sorry to take so long to respond to this. Is there a clearly defined "correct" order? Or is the behaviour undefined, and we just happen to be displaying it differently in the two modes?

**Comment by dcrossleyau** [comment]
AFAIK, it is the latter.

This message indicates that a way to actually specify that is on the roadmap:
Re: z index in cesium
https://groups.google.com/forum/#!msg/cesium-dev/Wf04lWlzf_Y/j8xRp2c4hJgJ

Also found this:
Z-ordering
https://github.com/AnalyticalGraphicsInc/czml-writer/issues/20

**Comment by kring** [comment]
Not something we can do without support from Cesium, which is a major undertaking.  Closing.
