### ISSUE TITLE
Support ESRI FeatureServer

### ISSUE THREAD

**Issue by stevage** [TerriaJS/terriajs#993]
The URLs provided by ESRI OpenData sites ([eg](http://data.melbournewater.opendata.arcgis.com/datasets/b0181addb35840779802f66bf5d98a07_0?geometry=143.237%2C-38.122%2C147.099%2C-37.471)) look like this:

`https://services5.arcgis.com/ZSYwjtv8RKVhkXIL/arcgis/rest/services/HWV_Overview/FeatureServer/0/query?outFields=*&where=1%3D1`

But we can't paste that directly into TerriaJS. We should accept a wider range of ESRI URLs.

**Comment by kring** [comment]
We don't currently support `FeatureServer` at all, right?

**Comment by stevage** [comment]
Well, that would explain it. :)

**Comment by RacingTadpole** [comment]
I've added this capability in #1882, although it won't work with the "query" at the end of the url - 

`https://services5.arcgis.com/ZSYwjtv8RKVhkXIL/arcgis/rest/services/HWV_Overview/FeatureServer/0` 

should work though.
