### ISSUE TITLE
Default to 2D on Windows Phone (like we do on Android and iOS)

### ISSUE THREAD

**Issue by meh9** [TerriaJS/terriajs#996]
We had a report that there was an error shown when using 3D mode on a Windows 8.1 Lumia phone so I tested on someones phone and got the following error:

```
Error rendering in 3D
An error occurred while rendering in 3D. This probably indicates a bug in AREMI or an incompatibility
 with your system or web browser. We'll now switch you to 2D so that you can continue your work. We
 would appreciate it if you report this error by sending an email to aremi@nicta.com.au with the
 technical details below. Thank you!
RuntimeError: Program failed to link.  Link log: Internal linking error
Error
at n (http://nationalmap.gov.au/renewables/build/nationalmap.js:36:18340)
at i (http://nationalmap.gov.au/renewables/build/nationalmap.js:49:27766)
at l (http://nationalmap.gov.au/renewables/build/nationalmap.js:49:29690)
at y.prototype._bind (http://nationalmap.gov.au/renewables/build/nationalmap.js:49:31334)
at p (http://nationalmap.gov.au/renewables/build/nationalmap.js:48:3653)
at ie.prototype.draw (http://nationalmap.gov.au/renewables/build/nationalmap.js:48:21469)
at o.prototype.execute (http://nationalmap.gov.au/renewables/build/nationalmap.js:49:1590)
at P.prototype.update (http://nationalmap.gov.au/renewables/build/nationalmap.js:65:11711)
at w (http://nationalmap.gov.au/renewables/build/nationalmap.js:63:8410)
at x (http://nationalmap.gov.au/renewables/build/nationalmap.js:63:11892)
```

Once I managed to close the error popup things worked well in 2D.

There were some other unrelated usability problems:
1. Due to unfortunate screen sizing the arrow to show/hide the sidepanel is off the side of the screen in portrait mode on this particular phone screen, this makes is very hard to hide the sidepanel after you have selected layers. Turning the phone to landscape mode made it accessible again, but a lot of people may not think to do that.
2. Once a layer was enabled (in this case AREMI Transmission Lines) the Legend was shown on top of the map even though the sidepanel was hidden and on the Data Catalog tab. Going onto the Now Viewing/Legends tab and "minimising" the legend made it go away once the sidepanel was hidden again.

**Comment by kring** [comment]
@meh9 any idea if that phone was completely up-to-date?  We used to see exceptions just like that on the earliest versions of Internet Explorer 11, but Microsoft fixed it quite awhile ago now.  I was under the impression that the phone version of IE11 would more or less keep pace with the desktop version, so I'm surprised to see such problems.

**Comment by meh9** [comment]
@lpostniece says that her phone is fully up to date as of this morning.

**Comment by kring** [comment]
@lpostniece we're way late on this, but we should at least default to 2D on this phone.  If you still have it, can you tell us the user agent it reports?  You can get your user agent here:
http://www.whoishostingthis.com/tools/user-agent/

**Comment by kring** [comment]
The new UI should work much better, and Windows Phone is not really a thing any more, so I'm closing this.
